### ISSUE TITLE
Should Screenshotting be removed from Neofetch?

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#1001]
I’m going through a purge of the Neofetch source. Removing anything that
does not belong. I stumbled across the screenshot functions and thought to
myself; Why are they even there in the first place?

Taking a screenshot is as easy as `neofetch; scrot` (*or equivalent
tool*). Is `-s`/`--scrot` really necessary? We’re duplicating
functionality here.

This also extends to the feature of uploading screenshots to teknik.io
and imgur. This feature is not as easy to replicate
outside of Neofetch but it definitely does not belong.

What are your thoughts on this matter? Should the functionality stay or
go? :+1: or :-1: this post and comment below if you’d like to add your
view to the discussion.

- Remove the feature: :+1:
- Keep the feature :-1:

**Comment by iandrewt** [comment]
I’ve never used it myself nor seen it used, and Neofetch is a system Information tool, not a screenshotting tool. It can go imo

**Comment by dylanaraps** [comment]
I've removed the feature from master but I'll keep this open to keep the discussion going.
