### ISSUE TITLE
Failure to detect music players other than iTunes on macOS

### ISSUE THREAD

**Issue by JadeMatrix** [dylanaraps/neofetch#1004]
## Description

Back in v3.3 I noticed Neofetch failed to detect any audio player (that I had installed) other than iTunes, even if iTunes itself wasn't running.  I tracked this down to the `iTunes Helper.app` "daemon" which is always running on macOS.  This had the side effect of always launching iTunes when Neofetch was run due to the AppleScript used to get the song info.  My solution was to change the iTunes detection regex from `iTunes.app`, which matches both iTunes and the Helper (which is contained in the iTunes.app package), to `iTunes$`, which will match only the `iTunes` executable in the iTunes.app package.  Neofetch then properly detected either Spotify or iTunes when only one of the two was running.  This change was added in be893d4 and merged in b6b1dfc (#904).  Apparently this broke things for other people, because the `$` was removed from the regex in 33d6dd7 (PR #1003) and 5756eb9.  However, Neofetch once again fails to detect Spotify for me for the same reason as before, and again always launches iTunes.

I went back and checked the commit history and found a couple other things:

* Detection was apparently broken again in ece335d, changes which seem to be only partially related so I'm not sure what's up with that
* Detection was sort-of fixed in 9825247 but the song title & artist strings seem to be corrupted with odd characters; again, not sure what's up with that since the changes were unrelated, but that was the current state until #1003 

I haven't tested this with other players on macOS; I tried using the Audacious version from Homebrew but it installs command-line only and I think more work would need to be done to support that.

#### Neofetch version

Neofetch `master` branch, macOS 10.12.6

## Screenshot

I disabled everything but song printing in my config file for these screenshots:

At commit bac9dcf (before my original changes); iTunes is launched if not already running when Neofetch runs:
<img width="570" alt="screen shot 2018-05-24 at 12 45 15 pm" src="https://user-images.githubusercontent.com/1753533/40499629-83d4dc7c-5f50-11e8-9767-7207372c5104.png">

At commit b6b1dfc (after my original changes were merged):
<img width="573" alt="screen shot 2018-05-24 at 12 45 35 pm" src="https://user-images.githubusercontent.com/1753533/40499634-86698172-5f50-11e8-9451-b93e584e87ac.png">

At commit ece335d (broken again):
<img width="555" alt="screen shot 2018-05-24 at 12 45 52 pm" src="https://user-images.githubusercontent.com/1753533/40499641-8dab9a9c-5f50-11e8-8ace-6ede01041fee.png">

At commit 9825247 (fixed-ish):
<img width="697" alt="screen shot 2018-05-24 at 12 46 04 pm" src="https://user-images.githubusercontent.com/1753533/40499644-8ffb3640-5f50-11e8-8aee-a5cccd2a4dad.png">

At commit e8ab52d (PR #1003, current state); iTunes is launched if not already running when Neofetch runs:
<img width="558" alt="screen shot 2018-05-24 at 12 46 20 pm" src="https://user-images.githubusercontent.com/1753533/40499647-95f4a6bc-5f50-11e8-92cc-262f483b052e.png">

## Config file

https://gist.github.com/JadeMatrix/693642cc8bb232f3f6fbd45d2b295a35

## Verbose log

I can grab this for any of the revisions above if needed.

**Comment by dylanaraps** [comment]
Does https://github.com/dylanaraps/neofetch/pull/1005 fix the issue?

**Comment by dylanaraps** [comment]
Try it with `--config off`.

**Comment by JadeMatrix** [comment]
It's still not fixed in #1005 — instead, Neofetch pauses for 13 seconds, opens iTunes, then prints nothing (I've only enabled the song again).  This happens with or without Spotify open, and with or without it currently playing.
<img width="489" alt="screen shot 2018-05-24 at 5 31 08 pm" src="https://user-images.githubusercontent.com/1753533/40514788-8244aab8-5f78-11e8-888f-59fb85c48477.png">

With `--config off` it prints out the standard information but no song info, and does so more or less instantly.  These are both on `master`.
<img width="523" alt="screen shot 2018-05-24 at 5 35 08 pm" src="https://user-images.githubusercontent.com/1753533/40514905-d6a261c2-5f78-11e8-9a5f-54fa26b8b93b.png">

**Comment by dylanaraps** [comment]
Try the latest commit. https://github.com/dylanaraps/neofetch/commit/01ef60445eeeccb88416c236e0b383aac7fa90b9

**Comment by JadeMatrix** [comment]
Okay, that's working for both iTunes & Spotify, and iTunes isn't launched anymore (makes sense).  It's still inserting `�` (Unicode "replacement character") and `‡` (Unicode "double dagger") into the song info as introduced in 9825247, but that seems like a separate issue.  I'll look into that.
<img width="722" alt="screen shot 2018-05-25 at 10 39 27 am" src="https://user-images.githubusercontent.com/1753533/40550382-ef58931e-6007-11e8-95c1-89159429a6b6.png">

**Comment by iandrewt** [comment]
What’s the expected output for that song? And separately for song, album and artist too. That might be an issue with all players for that song

**Comment by JadeMatrix** [comment]
The double-dagger has something to do with the song information splitting fix in cfcd6ff being removed at some point; not sure about the replacement character because that occurs in only one place in master that's unrelated to song splitting.

The expected output is `Camouflage - Count on Me - Count on Me - Single Version`.

**Comment by JadeMatrix** [comment]
Okay so the issue with the odd characters is that `LFS` can't be a Unicode character for some reason, even when I change the song info split to explicitly use the `en_US.UTF-8` locale instead of `$sys_locale`.  I tested this in both iTerm2 & Terminal and it fails in both, so it seems to be a macOS issue.  Info splitting works correctly when I change the separator from double-dagger to something ASCII like underscore.

**Comment by dylanaraps** [comment]
We'll change it to an ascii character. :+1:

**Comment by dylanaraps** [comment]
Try the latest commit. I've swapped the single char separator to `-@-` which doesn't appear in any music databases based on my searches.

**Comment by JadeMatrix** [comment]
Looks like the last two commits fixed it 👍 

Although, if I'm reading this right you replace that sequence with newlines then use that to split the info — can't you just use a newline to begin with, or does that mess up other stuff?  I tried converting `-@-` back into double-dagger and that worked, too.

**Comment by dylanaraps** [comment]
That’s a good idea actually. I’ll see if this works 👍

**Comment by dylanaraps** [comment]
Try the latest commit. Your idea works!

**Comment by JadeMatrix** [comment]
Yeah that works 👍
