### ISSUE TITLE
Image not displaying with w3m backend

### ISSUE THREAD

**Issue by Bukimari** [dylanaraps/neofetch#1006]
## Description
Images will not display with the w3m backend. w3m can display images when called directly, and other backends such as catimg display (although very pixelated). Have tried running manually using 'neofetch --w3m ~/Pictures/dock.jpg', and again with the no config option. I've also tried disabling transparency on terminator as suggested in a previous issue and even disabling my compositor with no luck.

-Arch Linux 4.16.10-1
-Terminator terminal

#### Neofetch version
4.0.2-1
## Screenshot
![2018-05-25-105411_1366x768_scrot](https://user-images.githubusercontent.com/12791486/40553984-fae382c8-6009-11e8-82dc-0b45ba1b7010.png)

## Config file
https://pastebin.com/raw/VpxrtZbz
## Verbose log
https://pastebin.com/raw/1VNrjh42

**Comment by dylanaraps** [comment]
This isn't a Neofetch issue. `w3m-img` is very unreliable and sometime outright doesn't work.

**Comment by Bukimari** [comment]
Well crap, just weird because it was working before a reinstall on this same computer. Thanks for the quick response though!

**Comment by dylanaraps** [comment]
Yeah, `w3m-img` works using a hack and it's up to the terminal emulator to try and support it properly. Your best bet for `w3m-img` is URxvt, XTerm or a VTE terminal (xfce4-terminal, termite). :+1:
