### ISSUE TITLE
How to install on Windows.

### ISSUE THREAD

**Issue by liudonghua123** [dylanaraps/neofetch#1008]
## Description

I read this on the README
> Neofetch supports almost 150 different operating systems. From Linux to Windows, all the way to more obscure operating systems like Minix, AIX and Haiku. 

And I also read https://github.com/dylanaraps/neofetch/wiki/Installation, but couldn't find any documentation about Windows installation.

**Comment by dylanaraps** [comment]
You need to be using Cygwin, MSYS/MingGW or Linux substrate for Windows. You can install Neofetch using the Makefile or by just downloading the script and running it.

**Comment by NatoBoram** [comment]
Personally, I installed it using [`scoop`](https://scoop.sh/)
