### ISSUE TITLE
Missing command line options reference on the Wiki

### ISSUE THREAD

**Issue by adalvigi** [dylanaraps/neofetch#1011]
First of all, my sir, I really like the artwork in [this image](https://camo.githubusercontent.com/289c5b1c6fe6b77fde4fab691b1f07acd73c996b/68747470733a2f2f692e696d6775722e636f6d2f47466d433541642e706e67) and if you could provide a source about it and the artist who made it I would really appreciate it!

Then, I was tweaking around with neofetch and realized that not all of the command line options are documented on the wiki. For example I sometimes use `neofetch --ascii_distro distroname` and I think I only got it by reading the config file and putting dots together, but I don't remember how to use the default distro logo instead of my waifu's picture. 

Even just a page about how to use the config file options temporarly from the command line would be nice for newbies!

**Comment by konimex** [comment]
Try `man neofetch` or `neofetch --help`.

**Comment by adalvigi** [comment]
It was what I was looking for, and the issue can be considered closed, but I'd still like to have the source on that image. Thanks anyway!

**Comment by dylanaraps** [comment]
![wallhaven-295990](https://user-images.githubusercontent.com/6799467/41183507-4fb1a842-6bbe-11e8-823a-85939ab65ae9.png)
