### ISSUE TITLE
Wayland window manager detection

### ISSUE THREAD

**Issue by SethBarberee** [dylanaraps/neofetch#102]
Great job on fetch so far but I have a slight problem... On sway, it detects xwlc as the compositor so it uses that as the window manager. Screenfetch overrides that in their case function but I see that you are using native functions to find the window manager name. Is there a way to detect the Wayland window mangers properly?

**Comment by dylanaraps** [comment]
I'd love to add support for Wayland DE/WMs, we just need to figure out a few things.

- How do we check to see if we're in a Wayland session? (X sets the $DISPLAY envar)
- How do we find out which DE/WM is running under Wayland without checking running processes?

I want to add full support for Wayland if possible, I don't want to hardcode anything.

**Comment by dylanaraps** [comment]
Alright, I've installed wayland/sway and it seems like wayland also sets the "$DISPLAY" variable.

**Comment by dylanaraps** [comment]
It looks like we'll have to check running processes at least for Wayland DEs/WMs.

**Comment by dylanaraps** [comment]
Done.

I've added hardcoded support for Wayland window managers until we can find a 
non-hardcoded way to do it similar to xprop.

**Comment by SethBarberee** [comment]
Thanks! Can't wait to try it out later!

**Comment by SirCmpwn** [comment]
FYI

https://github.com/dylanaraps/neofetch/blob/87a28b139acb422cc6b6c899050a99914f6f7b9f/neofetch#L704

Veelox does not use WLC, so this won't work.

**Comment by dylanaraps** [comment]
Thanks for the heads up, reopening this issue.
