### ISSUE TITLE
Wrong DE info on Bunsenlabs

### ISSUE THREAD

**Issue by robertwolter** [dylanaraps/neofetch#1022]
I'm just using BunsenLabs GNU/Linux 9.4 (Helium) x86_64 using Openbox and a Tint2 panel. The most recent version of neofetch shows "Xfce" as DE, perhaps because some XFCE programs are installed and running?
![bildschirmfoto_2018-06-06_18-42-54](https://user-images.githubusercontent.com/18753171/41052679-c396bd76-69b9-11e8-821e-e7c5c56639de.png)

**Comment by konimex** [comment]
Please provide full logs.

**Comment by robertwolter** [comment]
Here it is.
[neofetch.log](https://github.com/dylanaraps/neofetch/files/2077877/neofetch.log)

**Comment by dylanaraps** [comment]
What's the output of the following commands?

```sh
echo "$XDG_CURRENT_DESKTOP"
echo "$DESKTOP_SESSION"

# I think this command is causing the issue.
xprop -root | awk '/KDE_SESSION_VERSION|^_MUFFIN|xfce4|xfce5/'
```

**Comment by dylanaraps** [comment]
This isn't a neofetch bug. Something on your PC has set the `CURRENT_DESKTOP` environment variable to XFCE.

**Comment by robertwolter** [comment]
Yes, this is a BunsenLabs issue, closing.
