### ISSUE TITLE
[RPM] behaviour during upgrades

### ISSUE THREAD

**Issue by marcinbojko** [dylanaraps/neofetch#1024]
## Description

I am not sure if it's by design or not but:
When neofetch is being upgraded (CentOS 7, repository, yum) file /etc/neofetch/config.conf is being constantly overwritten by new version.
Old version is written as *.rpmsave.

I can agree it can be desired behaviour in case of massive changes, but it makes neofetch usage very hard to predict.
For example - default config.conf has a lots options being set to 'on'. This can affect login time (for example, login via ssh from Linux with WindowManager can take up to 1 minute).
For this reason our config.conf is being set to have only minimum required information. Yet, after every upgrade config.conf is being overriden and set to defaults.

If you're suggesting a new feature then just a description will suffice.

#### Neofetch version
3.x and 4.x
## Screenshot

Cleanup    : neofetch-3.4.0-1.el7.centos.noarch                                                                                                                                                                             147/234 
warning: /etc/neofetch/config.conf saved as /etc/neofetch/config.conf.rpmsave

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
The `/etc/neofetch/config.conf` file doesn't exist anymore in the new versions.
