### ISSUE TITLE
Problem printing packages

### ISSUE THREAD

**Issue by Podesta** [dylanaraps/neofetch#1026]
Screenshot: https://i.imgur.com/W3698Pg.png

Logs and config: [Gist.](https://gist.github.com/Podesta/99887bcda0d07a39223fd033e3ee8b54) Full program also under revisions.

**Comment by dylanaraps** [comment]
I just noticed the second issue. Packages from `dpkg` aren't being detected.

**Comment by Podesta** [comment]
Just deleted the gist. Want me to reup it?

**Comment by dylanaraps** [comment]
Yeah

**Comment by Podesta** [comment]
https://gist.github.com/Podesta/ca83d1d9cdc4271ee91919098b774210

**Comment by dylanaraps** [comment]
What's the output of this command?:

```sh
dpkg-query -f '\n' -W
```

**Comment by Podesta** [comment]
A lot of empty lines. Or, if I change it to another character, it prints it normally.

**Comment by dylanaraps** [comment]
Try the latest commit

**Comment by Podesta** [comment]
Still no.
https://i.imgur.com/fFXFoBk.png

**Comment by Podesta** [comment]
Seems to be good now
