### ISSUE TITLE
song: Banshee and Pogo not detected

### ISSUE THREAD

**Issue by ghost** [dylanaraps/neofetch#1028]
## Description

Banshee and Pogo are not detected with the new player-detection. Maybe others too, did not test with all..

```bash
    printf -v players "|%s" "${players[@]}"
    player="$(ps -e | awk -v pattern="(${players:1})$" '$0 ~ pattern {print $NF; exit}')"
```
Changing `ps -e` to `ps -x` works for Pogo but not Banshee.
For both `ps -e` output does not contain the player name.

ps -x
```
ps -x | grep banshee
24447 pts/1    Sl+    0:01 banshee /usr/lib/banshee/Banshee.exe
24468 pts/0    S+     0:00 grep banshee

ps -x | grep pogo
24480 pts/1    Sl+    0:00 python3 /usr/bin/pogo
24492 pts/0    S+     0:00 grep pogo
```

#### Neofetch version
git-master

**Comment by dylanaraps** [comment]
I’ll fix this 👍

**Comment by dylanaraps** [comment]
Fixed. https://github.com/dylanaraps/neofetch/commit/01bd13a3b555f0e8b4eb201c1a68423a1bd7bcf7

Let me know if the issue still occurs, I couldn't get `banshee` or `pogo` working on my machine.

**Comment by arisinfenix** [comment]
Both working now. :+1:

**Comment by dylanaraps** [comment]
Cheers :+1:
