### ISSUE TITLE
Neofetch Fails to connect to MPD

### ISSUE THREAD

**Issue by KeckleKnight** [dylanaraps/neofetch#1033]
Neofetch v4.0.2 fails to retrieve song info from an mpd server if its password protected. An option to manually define the args that mpc uses could fix this.

**Comment by dylanaraps** [comment]
I’ll add an option for this 👍

**Comment by dylanaraps** [comment]
Is there a command-line flag for this? I checked the man page but I couldn't really find anything.

This solution should also work however:

```sh
 If  the  server requires a password, it
              can be specified using password@host in
              the MPD_HOST variable.
```

**Comment by KeckleKnight** [comment]
when i use mpc, this is how i connect
```
mpc -h IPADDRESS -p PORT -P PASSWORD
```
