### ISSUE TITLE
number of installed packages not taken into account on ArchLinux

### ISSUE THREAD

**Issue by bambinos007** [dylanaraps/neofetch#1034]
Hi, 

Since version 5.1 of pacman (early June), Neofetch (verison 4.0.2-1) no longer lists installed packages.
The problem does not arise with Screenfetch which uses the variable 

  `pacman -Qq | wc -l`

to list the total number of installed packages.

Is that a known bug??
This is related to the new version of pacman because with pacman 5.0, the problem disappears.

I purged and reinstalled neofetch but no change.
By downgrading pacman to 5.0, neofetch lists the installed packages again.

And there's also a bug with Optimus technology.
For graphics cards, only the Intel chipset is taken into account.
But the Nvidia isn't.
It is replaced by the Ethernet card...

As you can see on the screenshot.
<a href='https://postimg.cc/image/b9ycnisi3/' target='_blank'><img src='https://s33.postimg.cc/b9ycnisi3/Capture_du_2018-06-18_23-28-57.png' border='0' alt='Capture_du_2018-06-18_23-28-57'/></a>

For your information, I use ArchLinux Cinnamon.
Thank you.
cheers.

**Comment by dylanaraps** [comment]
Fixed in master already, a new release will be made soon.

**Comment by dylanaraps** [comment]
Open a new issue for the GPU 👍
