### ISSUE TITLE
neofetch prints wrong GPU type

### ISSUE THREAD

**Issue by steven-omaha** [dylanaraps/neofetch#1036]
## Description

Neofetch prints the wrong GPU type. Currently it prints:

    CPU: Intel i5-4670 (4) @ 3.800GHz
    GPU: Intel Xeon E3-1200 v3/4th Gen Core Processor

I would expect it to print something like

    GPU: Intel HD Graphics 4600`

#### Neofetch version
5.0.0

## Screenshot
Can't currently provide one. Sorry. [Here](https://pastebin.com/eHvGn4z5) is the output.

## Config file
[Link](https://pastebin.com/RBFvX2CU)

## Verbose log
[Link](https://pastebin.com/q1VuPV4Z)

**Comment by dylanaraps** [comment]
Output of this command?:

```sh
glxinfo | grep "Device:.*Intel"
```

**Comment by steven-omaha** [comment]
$ glxinfo | grep "Device:.*Intel"
          Device: Mesa DRI Intel(R) Haswell Desktop  (0x412)

**Comment by dylanaraps** [comment]
Try (this updates the PCI ID database):

```sh
sudo update-pciids
```

Then:

```sh
lspci -mm | awk -F '\\"|\\" \\"|\\(' '/"Display|"3D|"VGA/ {a[$0] = $3 " " $4} END {for(i in a) {if(!seen[a[i]]++) print a[i]}}'
```

**Comment by steven-omaha** [comment]
I updated the database. The second command results in 
    Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller

**Comment by dylanaraps** [comment]
I'm unable to fix this as `lspci` and `glxinfo` both don't have the correct information. The best I can do is display `Intel HD Graphics` instead of the line `Xeon Processor` line above.

Try the latest master and let me know if it works.

**Comment by steven-omaha** [comment]
It works. 

     GPU: Intel HD Graphics

Thanks for responding quickly. Issue can be closed.
