### ISSUE TITLE
No longer fetching wallpaper (Ubuntu Bionic / Gnome)

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/neofetch#1037]
## Description

My neofetch is no longer diplaying my wallpaper, and just substitutes with my chosen ascii logo. Pictures using a path/to/folder do work fine, tho.

Version: 5.0.0 (from ppa)
https://pastebin.com/3cfpK6cr

Can someone help?

**Comment by dylanaraps** [comment]
Fixed, try the latest master and let me know if the issue still occurs.
