### ISSUE TITLE
The "model" could be made more useful

### ISSUE THREAD

**Issue by Monty** [dylanaraps/neofetch#1038]
## Description
The "model" i.e. "MacBookPro14,3" could be more helpful as "MacBook Pro (15-inch, 2017)". 
I added this to my config file to print that out.

#### Neofetch version
Neofetch 5.0.1

I would have sent a pull request, but it's not "pure bash" has pipes and otherwise doesn't fit your style.
I hope the idea is useful, and someone with more coding skills can add it.

```sh
    # modified from https://apple.stackexchange.com/questions/98080/can-a-macs-model-year-be-determined-with-a-terminal-command
    # Setup variables for getting marketing model info from web
    serialNumberKey="$(system_profiler SPHardwareDataType | awk '/Serial/ {print substr($4,9)}')"
    onlineModel="$(curl -s https://support-sp.apple.com/sp/product?cc=$serialNumberKey |
        sed 's|.*<configCode>\(.*\)</configCode>.*|\1|')"
    #
    # Setup variables for getting marketing model info from local plist
    marketingModelFile=/System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A
    marketingModelFile+=/Resources/English.lproj/SIMachineAttributes
    if ! [ -f "${marketingModelFile}.plist" ]; then
        # 10.7 or 10.6
        marketingModelFile=/System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A
        marketingModelFile+=/Resources/English.lproj/XSMachineAttributes
    fi
    if [ -f "${marketingModelFile}.plist" ]; then
        model_ID="$(sysctl -n hw.model)"
        marketingModel="$(defaults read "${marketingModelFile}" "${model_ID}" |
            sed -n -e 's/\\//g' -e 's/.*marketingModel = "\(.*\)";/\1/p')"
    else
        marketingModel="${onlineModel}"
    fi

    prin "Online Model Type" "${onlineModel}"
    prin "Local Model Type" "${marketingModel}"
```

Here's a test using Mac models I've owned over the years

```sh
#!/usr/bin/env bash

echo "Marketing model from online Apple serial number database:"
j=0
for i in HTD5 FY11 DNMP DKQ1 DMW8 642 U36 NRZ; do
    onlineModel=$(curl -s https://support-sp.apple.com/sp/product?cc=${i} |
        sed 's|.*<configCode>\(.*\)</configCode>.*|\1|')
    j=$((j+1))
    echo "    ${j} - ${onlineModel}"
done

echo ""
echo "Marketing model from local plist:"

marketingModelFile=/System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A
marketingModelFile+=/Resources/English.lproj/SIMachineAttributes
j=0
for i in MacBookPro14,3 iMac15,1 iMac13,2 MacBookPro10,1 iMac12,2 MacBookPro5,3 \
    Macmini1,1 PowerBook5,2; do
    model_ID=${i}
    marketingModel="$(defaults read "${marketingModelFile}" "${model_ID}" |
        sed -n -e 's/\\//g' -e 's/.*marketingModel = "\(.*\)";/\1/p')"
    j=$((j+1))
    echo "    ${j} - ${marketingModel}"
done

echo ""
echo "Description from local plist:"

j=0
for i in MacBookPro14,3 iMac15,1 iMac13,2 MacBookPro10,1 iMac12,2 MacBookPro5,3 \
    Macmini1,1 PowerBook5,2; do
    model_ID=${i}
    marketingModel="$(defaults read "${marketingModelFile}" "${model_ID}" |
        sed -n -e 's/\\//g' -e 's/.*description = "\(.*\)";/\1/p')"
    j=$((j+1))
    echo "    ${j} - ${marketingModel}"
done
```

**Comment by JadeMatrix** [comment]
FWIW, the macOS detailed system report uses the `MacBookNN,N` notation, so it's not like this isn't something Apple already exposes to users:

<img width="445" alt="screen shot 2018-06-21 at 9 09 43 pm" src="https://user-images.githubusercontent.com/1753533/41752835-bdde7204-7597-11e8-97a5-b5a469163f83.png">

**Comment by dylanaraps** [comment]
The current information output is fine. If the code to display the English model names wasn’t so very complex I’d consider it.

Thanks for opening this issue.

**Comment by dylanaraps** [comment]
If there was a simpler method of getting that information I’d add it but that doesn’t seem to be the case.

**Comment by Monty** [comment]
Sorry about the unneeded complexity. I started looking at the neofetch code and realized you’d prefer pure bash.

    serialNumberKey="$(system_profiler SPHardwareDataType | awk '/Serial/ {print substr($4,9)}')"
    onlineModel="$(curl -s https://support-sp.apple.com/sp/product?cc=${serialNumberKey})"
    onlineModel="${onlineModel##*<configCode>}"
    onlineModel="${onlineModel%%<*}"

The above seems similar in form to that used in the Mac GPU code.
    gpu="$(system_profiler SPDisplaysDataType |\
    awk -F': ' '/^\ *Chipset Model:/ {printf $2 ", "}')"
    gpu="${gpu//'/ $'}"
    gpu="${gpu%,*}”

BTW,  I can understand most of the code, but I was wondering what “gpu" string this code fixes?
    ${gpu//'/ $’} 

This is even shorter, but less immune to changes in the XML
    marketingModel="$(curl -s https://support-sp.apple.com/sp/product?cc=${serialNumberKey} |
        awk -F '[<>]' '{printf $11}')"

**Comment by dylanaraps** [comment]
I'd rather not make network requests or add the dependency of an internet connection to Neofetch. If it's stored on the system itself in a file that would help.

**Comment by Monty** [comment]
It is stored in a local plist at 
	/System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A/Resources/English.lproj/SIMachineAttributes (or XSMachineAttributes)
but using
	defaults read /System/Library/PrivateFrameworks/ServerInformation.framework/Versions/A/Resources/English.lproj/SIMachineAttributes ${modelid}
and processing the result seems too complex and prone to breakage.

I’m perfectly happy leaving the model code in my config file.

Thanks for neofetch! And the pure-bash-bible. It’s a great resource.

Marketing model from local plist:
    1 - 15" MacBook Pro with Thunderbolt 3 and Touch ID (Mid 2017)
    2 - 27" iMac (Late 2014)
    3 - 27" iMac (Late 2012)
    4 - MacBook Pro with Retina display, Intel Core i7, 15" (Mid 2012)
    5 - 27" iMac (Early 2011)
    6 - MacBook Pro Intel Core 2 Duo (aluminum unibody) (Mid 2009)
    7 - Mac mini Intel Core (Early 2006)
