### ISSUE TITLE
Minor aesthetic nit in config file

### ISSUE THREAD

**Issue by Monty** [dylanaraps/neofetch#1039]
## Description

When testing various flags, I noticed (only) one flag description had a dot at the end.

$ grep -n Flag neofetch | grep "\.$"
204:# Flag:    --speed_shorthand.

#### Neofetch version
Neofetch 5.0.1

**Comment by dylanaraps** [comment]
I’ll fix this when I’m near a PC, thanks for pointing it out. 👍
