### ISSUE TITLE
Neofetch fails to detect the CPU on NetBSD/evbarm

### ISSUE THREAD

**Issue by rkujawa** [dylanaraps/neofetch#1041]
## Description

The CPU line just displays `CPU: (0)` without information about used CPU.

This information could be extracted for example from `hw.model` sysctl. On this particular machine:
```
$ sysctl hw.model
hw.model = ARM1176JZ-S r0p7 (ARM11J V6ZK core)
```

#### Neofetch version

5.0

## Screenshot

```
                     `-/oshdmNMNdhyo+:-`   rkujawa@rpi.c0ff33.net
y/s+:-``    `.-:+oydNMMMMNhs/-``           ----------------------
-m+NMMMMMMMMMMMMMMMMMMMNdhmNMMMmdhs+/-`    OS: NetBSD 8.0_RC1 evbarm
 -m+NMMMMMMMMMMMMMMMMMMMMmy+:`             Uptime: 4 days, 10 hours, 30 mins
  -N/dMMMMMMMMMMMMMMMds:`                  Packages: 11 (pkg_info)
   -N/hMMMMMMMMMmho:`                      Shell: sh
    -N/-:/++/:.`                           Terminal: /dev/pts/4
     :M+                                   CPU: (0)
      :Mo                                  Memory: 325MiB / 448MiB
       :Ms
        :Ms
         :Ms
          :Ms
           :Ms
            :Ms
             :Ms
              :Ms
```

## Config file

Default.

## Verbose log

https://gist.github.com/rkujawa/5a16020bea8c3240f027ea22571b2f94

**Comment by dylanaraps** [comment]
Neofetch uses `/proc/cpuinfo` for CPU on NetBSD so that it can use the Linux related code. I'll fix this.

**Comment by rkujawa** [comment]
`/proc/cpuinfo` contents is platform dependent on NetBSD. Some ports (platforms) do not implement Linux compatibility fully (or at all) and will have completely empty cpuinfo file.

**Comment by dylanaraps** [comment]
I’ll change it to use sysctl :+1:

**Comment by dylanaraps** [comment]
This should be fixed now :+1:
