### ISSUE TITLE
Feature Request: A New Title in Each Run

### ISSUE THREAD

**Issue by Dentrax** [dylanaraps/neofetch#1043]
There is a title that comes by default;

```
Never Knows Best 
---------------- 
OS: Arch Linux x86_64 
Kernel: 4.17.2-1-ARCH 
...bla bla bla 
```

Neofetch can be set to be a different title each when it runs. May can use the mod for title sequences.

There can be an array that we defined in config file.

`declare -a arr=("1st Msg" "2nd Msg" "3rd Msg" "...bla bla bla...")`
`isSequential: true, if false it should be generate randomly`

1st run: Hello, Mr.X
2nd run: How are you today, Mr.X
3rd run: Welcome!
4st run: ...
...

Thanks in advance!

**Comment by dylanaraps** [comment]
Here's how you can do it randomly:

```sh
messages=(
    "Hello"
    "Goodbye"
    "test"
    "test2"
)

print_info() {
    prin "${messages[RANDOM % ${#messages[@]}]}"

    #  Rest of info functions here...
}

# Rest of config...
```

**Comment by dylanaraps** [comment]
This can't be done sequentially without using a temporary file. The config file is a `bash` script so none of this needs to be implemented in Neofetch itself.

**Comment by dylanaraps** [comment]
Here's how to do it sequentially:

```sh
messages=(
    "Hello"
    "Goodbye"
    "test"
    "test2"
)

[[ -f /tmp/cycle ]] && i="$(< /tmp/cycle)"
printf '%s\n' "$((i<=${#messages[@]}-2?${i:--1}+1:0))" > /tmp/cycle

print_info() {
    prin "${messages[$i]}"

    # Rest of info functions...
}

# Rest of config...
```

**Comment by Dentrax** [comment]
Thank you so much, @dylanaraps ! :)

I think it would be cool if it came as a built-in feature. :1st_place_medal: You should think about it. :+1:
