### ISSUE TITLE
Some bash substitutions are broken

### ISSUE THREAD

**Issue by Monty** [dylanaraps/neofetch#1044]
## Description

```image="${image/'file://'}"``` should probably be ```image=${image/file:\/\/}"```

```gpu="${gpu//'/ $'}"``` should probably be ```gpu="${gpu//\'/ }"```

Possibly other substitutions using single quotes instead of \escapes are broken.

#### How I got to this conclusion
I wanted to learn to use bash string substitution instead of sed in simple cases.

I grabbed a few examples to study from the person who basically wrote the book on the topic.
```grep '="\$.*//.*/' neofetch | sort -b```
	
I planned to figure out what each snippet should do and write a test to confirm I was correct. For an easy example,
```cpu="${cpu//Core2/Core 2}"```
should change _all_ occurrences of "Core2" to "Core 2"

I started with simple tests like this, but ended up with a number of more complex tests.
```
tst='Intel Core2 or Intel(tm) Core2'
res="${tst//Core2/Core 2}"
printf "%s\n"  '${tst//Core2/Core 2}'
printf "\"%s\" changed to\n\"%s\"\n\n"  "$tst" "$res"
```
Which yielded this correct result:
```
${tst//Core2/Core 2}
"Intel Core2 or Intel(tm) Core2" changed to
"Intel Core 2 or Intel(tm) Core 2"
```

It was more difficult to understand the substitutions using literal quoted strings -- until I saw
```image="${image/'file://'}"```
which seems it should strip the prefix from file:// URLs. But it doesn't.

```
image="file://test.txt"
image="${image/'file://'}"
echo $image
```
Which yields:
```/'//test.txt```

Having to work backwards to divine the intents makes this process difficult. I'm not an expert
so without test input data I can't detect all the possible problems, or ensure my tests are accurate.

#### Neofetch version
501

**Comment by Monty** [comment]
It's hard to type tests correctly since you have to be careful with both quotes and escapes. Here's one that should run.
```
#!/usr/bin/env bash

printf "### Broken code followed by working code ###\n\n"

# 3518:  image="${image/'file://'}"
tst="file:///Users/test/neofetch/bug.txt"
res="${tst/'file://'}"
printf "==> %s\n"  "\${tst/'file://'}"
printf "\"%s\" changed to\n\"%s\"\n\n"  "$tst" "$res"

tst="file:///Users/test/neofetch/bug.txt"
res="${tst/file:\/\/}"
printf "==> %s\n"  '${tst/file:\/\/}'
printf "\"%s\" changed to\n\"%s\"\n\n"  "$tst" "$res"

# 2114:  gpu="${gpu//'/ $'}"
tst="'Single quoted string'"
res="${tst//'/ $'}"
printf "==> %s\n"  "\${tst//'/ \$'}"
printf "\"%s\" changed to\n\"%s\"\n\n"  "$tst" "$res"

tst="'Single quoted string'"
res="${tst//\'/ }"
printf "==> %s\n"  "\${tst//\'/ }"
printf "\"%s\" changed to\n\"%s\"\n\n"  "$tst" "$res"
```

Here's the output.
```
### Broken code followed by working code ###

==> ${tst/'file://'}
"file:///Users/test/neofetch/bug.txt" changed to
"/'///Users/test/neofetch/bug.txt"

==> ${tst/file:\/\/}
"file:///Users/test/neofetch/bug.txt" changed to
"/Users/test/neofetch/bug.txt"

==> ${tst//'/ $'}
"'Single quoted string'" changed to
"'Single quoted string'"

==> ${tst//\'/ }
"'Single quoted string'" changed to
" Single quoted string "
```

**Comment by dylanaraps** [comment]
Weird, they work on my machine.

**Comment by Monty** [comment]
Maybe it’s my environment.  I’ll have to try it on a Linux box.

OS: macOS High Sierra 10.13.5 17F77 x86_64
Kernel: Darwin 17.6.0
Shell: bash 3.2.57

**Comment by Monty** [comment]
I've enjoyed the learning exercise of reverse engineering what the intent of the substitutions is.

**Comment by dylanaraps** [comment]
Are you by any chance running a version of `bash 3`?

**Comment by dylanaraps** [comment]
Should be fixed in https://github.com/dylanaraps/neofetch/commit/c99fc64b67a837739242fb1f63e356f91a15e016

**Comment by Monty** [comment]
The old Ubuntu VM I have is running a later bash.
Host: VMware Virtual Platform None
OS: Ubuntu 17.04 x86_64
Kernel: Linux 4.10.0-28-generic
Shell: bash 4.4.7

${tst/'file://'} does indeed remove the prefix.
but
${tst//'/ $'} doesn't remove single quotes. Maybe that's not the intent. Is there a different string I should use as test input?

```
==> ${tst/'file://'}
"file:///Users/test/neofetch/bug.txt" changed to
"/Users/test/neofetch/bug.txt"

==> ${tst//'/ $'}
"'Single quoted string'" changed to
"'Single quoted string'"
```
Although my Mac is running bash 3.2.57, it's from the current High Sierra release 
OS: macOS High Sierra 10.13.5 17F77 x86_64

**Comment by dylanaraps** [comment]
This is how this one works:

```sh
string="Test Test/ $Test Words Here"
string="${string//'/ $'}"
```

Either way, I've fixed this issue in master now so I'm closing this.

**Comment by dylanaraps** [comment]
Thanks for bringing this to my attention.

**Comment by Monty** [comment]
No problem.

I hit it initially when running my copy of neofetch through shfmt.

shfmt -i 4 -s ~/bin/neofetch >neofetch-test
2108:13: if statement must end with “fi"

That error was bogus, and I traced it back to 
gpu="${gpu//'/ $’}"

shfmt was thinking there was an unclosed single quote

— Monty
