### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by filipekiss** [dylanaraps/neofetch#1045]
## Description

I've updated my config to use an image instead of the ascii art but it's not working. If I don't pass any parameters, it will use the ascii art and if I pass, for example, `--imgcat --source /path/to/img` it breaks. iTerm is ok with the images because `imgcat` works as expected. I've also tried running `neofetch` under `bash` instead of `zsh` but the result is the same.

#### Neofetch version
Neofetch 5.0.0
OS: macOS High Sierra 10.13.5 17F77 
Host: MacBookPro14,1 
Shell: zsh 5.5.1 
Terminal: iTerm2 

## Screenshot

If i run `neofetch` with no arguments:

![image](https://user-images.githubusercontent.com/48519/41862152-7a866ad6-7879-11e8-8e63-b1c6cbe611ce.png)

If I pass `--imgcat --source $HOME/neofetch.png` it hangs for a while at this screen:

![image](https://user-images.githubusercontent.com/48519/41862510-7550ec20-787a-11e8-9c1e-0687393a252d.png)

Then this flashes:
![image](https://user-images.githubusercontent.com/48519/41862210-9d01f724-7879-11e8-91a0-44ba4e40fbb3.png)
and then the screen is cleared

## Config file

https://gist.github.com/filipekiss/39c459ba4d7b9703b3a11f306a1a8533#file-config-conf

## Verbose log

https://gist.github.com/filipekiss/39c459ba4d7b9703b3a11f306a1a8533#file-neofetch-log

**Comment by onedr0p** [comment]
Same issue here, I am on 5.0.1. I installed with `brew install neofetch --HEAD`

**Comment by MindTooth** [comment]
Well, I don't think there is a `--imgcat` option.

Tried with `neofetch --iterm2 $HOME/neofetch.png`?

**Comment by sharkytowers** [comment]
I had the same issue on arch/arcolinux.  I rolled back to the version of neofetch that is on the aur (as opposed to the one in the repo it arcolinux wants to update) and it works.  Hope that helps someone.

**Comment by filipekiss** [comment]
@MindTooth yeah, the result is the same :/

**Comment by sharkytowers** [comment]
@filipekiss I think I have version 3.3.0-1 which I know is old, but it is working for me.  I did a makefile after cloning whatever was on the AUR

**Comment by erikdubois** [comment]
I can confirm this is a problem and narrow it down for you.

If you update to the latest version of neofetch on Arch 5.0.0-1 and use config.conf the images do NOT work.
If you rename the same config.conf to config the images WILL display.

Something in the renaming of the file has gone wrong.

Using the naming convention **config.conf**

![arcolinux-neofetch_2018-06-28_10-39-42](https://user-images.githubusercontent.com/10594806/42023482-36d50a9c-7ac0-11e8-9244-7c4dadde571d.png)


Using the same code but naming convention **config**.

![arcolinux-neofetch-config_2018-06-28_10-46-19](https://user-images.githubusercontent.com/10594806/42023598-8b28d79a-7ac0-11e8-93e4-87a5646f67c9.png)

**Comment by filipekiss** [comment]
@erikdubois I'm running macOS and tried this, but did not work :( I still get the weird binary dump.

**Comment by erikdubois** [comment]
Make sure that none of the images are being used.
All hashtags before them.
Backend should be ascii

**Comment by StarryTony** [comment]
Hi, I have created a pull request to fix this. However, you can manually add "unset IFS" to the function: 
```
get_window_size(){
    old_ifs="$IFS"
    IFS=';t' read -d t -t 1 -sra term_size
    **unset IFS**
}
```

enjoy!

**Comment by erikdubois** [comment]
I have added this line to the variables at the top

config_file="${XDG_CONFIG_HOME}/neofetch/config.conf"

and then the image shows. Can it be that the variable is empty when first used?

**Comment by StarryTony** [comment]
@erikdubois I debugged on MacOS and found the issue is caused by empty assigned variables because the IFS is not unset after usage.

**Comment by erikdubois** [comment]
The variable I mentioned up there.  It works here now.

**Comment by filipekiss** [comment]
Hey @StarryTony, thank you for your time. That still doesn't work for me =(

I'll keep fiddling around and see if I can find what's causing this.

**Comment by StarryTony** [comment]
@filipekiss For my MacOS (the same version but with zsh 5.3, iterm2), I found it caused by null windows size and had the same error output. The solution works for me. You may try -vv option to get a full diagnosis information. Hope it helps.

**Comment by iwestlin** [comment]
I have same issue on macOS and found it also caused by null windows size.
But adding `unset IFS` did not solve it, after some debug I found out the reason and the solution for me.
It turns out that macOS is using bash version `3.2.57` which did not support `read -t 0.05` option.
so I just change
`IFS=';t' read -d t -t 0.05 -sra term_size`
to
`IFS=';t' read -d t -sra term_size`
and it worked!

For those who still have the problem, there is another way: update bash to the newest version.
For macOS user is:
`brew install bash`
then add `#!/usr/local/bin/bash` to the first line of neofetch(which locate at `/usr/local/bin/neofetch`).

**Comment by StarryTony** [comment]
Oh sorry to forget mentioning that if you have an old version of bash, you probably change the timeout option to 1 because it cannot support 0.05. My code has changed that but I forgot mentioning that. I am using bash 3.2 for the neofetch too.

**Comment by filipekiss** [comment]
Updating bash version was the solution! Thank you @StarryTony! (Just updated it, didn't even need to change the shebang nor the `IFS`!)

**Comment by StarryTony** [comment]
Congrats!

**Comment by onedr0p** [comment]
Installing bash `brew install bash` worked for me too.

**Comment by davidmrdavid** [comment]
Hey folks, I'm a little confused about this.
I'm using Bash 4.4 and iterm2 on MacOS Sierra. 
I tried adding `get_window_size` with little success. Whats the expected `~/.config/neofetch/config.conf` to get this working?
