### ISSUE TITLE
Wrong memory display in OS X

### ISSUE THREAD

**Issue by keysona** [dylanaraps/neofetch#1047]
## Description

The memory display may be wrong in os x(10.13.5).
I find the strange code in neofetch.

In my mac(os x: 10.13.5), I run ```vm_stat```, the output is:

```
$ vm_stat
...
Pages active:                           1508737.
Pages inactive:                         1122740.
...
```

```bash
# neofetch file's line: 2204
mem_active="$(vm_stat | awk '/active / { printf $3 }')"
```
There is space after ```active```.

I echo the ```mem_active```, the output is blank string.

I think the space should be ahead of the ```active```, as follows: 

```
mem_active="$(vm_stat | awk '/ active/ { printf $3 }')"
```

The output
```
$ vm_stat | awk '/ active/ { printf $3 }'
1673460.
```

#### Neofetch version
5.0.0

## Screenshot

No.

## Config file

Default.

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
@iandrewt
