### ISSUE TITLE
More shell information on KDE

### ISSUE THREAD

**Issue by Krotera** [dylanaraps/neofetch#1052]
## Description

It'd be nice if neofetch had information parity in framework and Plasma version with screenfetch. E.g.,
- My screenfetch: `DE: KDE 5.44.0 / Plasma 5.12.5`
- My neofetch: `DE: KDE`

#### Neofetch version

3.4.0-1

**Comment by plgruener** [comment]
I just dug a bit through screenfetch's code. Just for the record, you can get
* KDE major version (4/5) via `$KDE_SESSION_VERSION`
* KDE-Framework version via `kded[45] --version`
* KDE Plasma version via `plasmashell --version` (`kwin --version` seem to yield the same)

There is currently #971, but I'm not so sure where Plasma really belongs to (DE or WM?).
Also if one added the KDE/Plasma version, one should do the same for GNOME,Xfce,…

**Comment by alexandergraul** [comment]
I'd say (KDE) Plasma is the DE and kwin the WM.

I agree that version information would be a nice addition (regardless of DE).

**Comment by roachsinai** [comment]
Agree, too.
