### ISSUE TITLE
Running neofetch causes iTunes to open

### ISSUE THREAD

**Issue by Julian-Heng** [dylanaraps/neofetch#1059]
## Description

Neofetch is incorrectly detecting that iTunes is running due to the song detection matching iTunesHelper instead.

```
julian@Julians-MacBook-Pro: (~)
$ ps aux | awk -v pattern="(${players:1})" '!/ awk / && match($0,pattern){print substr($0,RSTART,RLENGTH); exit}'
iTunes
julian@Julians-MacBook-Pro: (~)
$ ps aux | awk -v pattern="(${players:1})" '!/ awk / && match($0,pattern){print $0}'
julian             807   0.0  0.1  4332620   9064   ??  S     1:03pm   0:00.14 /Applications/iTunes.app/Contents/MacOS/iTunesHelper.app/Contents/MacOS/iTunesHelper
```

Hence, Neofetch will attempt use osascript to get song info, causing iTunes to launch.

This can be fixed by changing the awk command to match at the end of the string, but I'm not sure if it would break detection for other players.
```
awk -v pattern="(${players:1})$" '!/ awk / && match($0,pattern){print substr($0,RSTART,RLENGTH); exit}'
```

#### Neofetch version
Neofetch 5.0.1

## Config file
https://gist.github.com/Julian-Heng/1933d5e8bc8935f13976b17591fe35a8
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

https://gist.github.com/Julian-Heng/3a2d196b8992e1f1589cb5c4c6c3244b

**Comment by JadeMatrix** [comment]
It's broken again?

Looks like it happened in 01bd13a `song: Fix detection.`  It seems every time song detection is "fixed" it breaks on macOS again.

Anyways #1004 might be helpful fixing this.

**Comment by iandrewt** [comment]
God dammit. I’ll give this another look next week if someone hasn’t submitted a PR by then. Gonna try solve this once and for all

**Comment by JadeMatrix** [comment]
@iandrewt Just updated to 6.0.0 and this is broken (again).  It also doesn't detect the currently playing song properly (probably because there isn't one).
macOS 10.12.6, iTunes 12.5.5.5.  Want a new issue opened?

<img width="601" alt="Screen Shot 2019-08-05 at 10 02 29 PM" src="https://user-images.githubusercontent.com/1753533/62505987-c6523b00-b7cc-11e9-9ae3-431591e04bdb.png">
