### ISSUE TITLE
ADM GPU detect

### ISSUE THREAD

**Issue by sr-tream** [dylanaraps/neofetch#1060]
## Description
Incorrect detecting my GPU RX560. Neofetch detect my GPU as RX550

#### Neofetch version
5.0
## Screenshot
![neofetch](https://dl.prime-hack.net/2018-07-18-202800_721x351_scrot.png)
![glxinfo](https://dl.prime-hack.net/2018-07-18-202827_768x60_scrot.png)

## Verbose log
https://pastebin.com/iPLXwUkC

**Comment by sr-tream** [comment]
@konimex 
![screenshot](https://dl.prime-hack.net/2018-07-24-090506_826x380_scrot.png)

**Comment by konimex** [comment]
Merged with master. Thanks for the report.
