### ISSUE TITLE
Not Detect System iPhone

### ISSUE THREAD

**Issue by Am1nCmd** [dylanaraps/neofetch#1061]
## Description

Well hello again bro, i use neofetch with version 5.0.1 on iOS 11.3.1, as previusly i installed on 11.1.2 that running well,

but on 11.3.1 didn't detect system

when i run neofetch show (maybe error) on line 4166
i hope this report can help you to fix it on newer version

thx

#### Neofetch version
5.0.1

## Screenshot
![screenshot at jul 26 08-39-56](https://user-images.githubusercontent.com/15339573/43236476-8694964c-90af-11e8-83be-431358dcc765.png)

**Comment by konimex** [comment]
Please provide full logs.

>1. Run `neofetch -vv 2> neofetchlog`
>2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by kraxarn** [comment]
I have the same issue and thought I would just add to this issue rather than creating a new one.
Also running iOS 11.3.1, but on an iPhone X. Output from neofetch looks the same, but [here's the log](https://gist.github.com/kraxarn/d49939938c3cb0fe753f13358b82d6da).

Should also probably point out that the repository (`http://dylanaraps.com/repo`) no longer works, so I downloaded the file from the releases page and just moved it to `/usr/bin/neofetch`.

**Comment by dylanaraps** [comment]
Install `awk`.

If that doesn't work, reopen this issue.

**Comment by Am1nCmd** [comment]
> Please provide full logs.
> 
> > 1. Run `neofetch -vv 2> neofetchlog`
> > 2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

where is the neofetch log directory?
1 have try no 1 but didn't show the log

**Comment by Am1nCmd** [comment]
> Install `awk`.
> 
> If that doesn't work, reopen this issue.

what is awk and how to install it?

**Comment by Am1nCmd** [comment]
> Please provide full logs.
> 
> > 1. Run `neofetch -vv 2> neofetchlog`
> > 2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

ah i found it

and here is inside the neofetchlog https://pastebin.com/HgN2u2BV

**Comment by konimex** [comment]
Yep. This is missing dependency problem.

You can install gawk (GNU awk, an implementation of [AWK](https://en.wikipedia.org/wiki/AWK)) in Cydia.

**Comment by Am1nCmd** [comment]
> Yep. This is missing dependency problem.
> 
> You can install gawk (GNU awk, an implementation of [AWK](https://en.wikipedia.org/wiki/AWK)) in Cydia.

alright let me try

**Comment by Am1nCmd** [comment]
> Yep. This is missing dependency problem.
> 
> You can install gawk (GNU awk, an implementation of [AWK](https://en.wikipedia.org/wiki/AWK)) in Cydia.

i have installed gawk from cydia right now, and got like this

Am1nCmd:~ root# neofetch
                    'c.          root@Am1nCmd 
                 ,xNMM.          ------------ 
               .OMMMMo           OS: 1983-2018 Apple Inc. (Unknown) iPhone8,1 
               OMMM0,            Kernel: 17.5.0 
     .;loddo:' loolloddol;.      Uptime: secs 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Shell: sh 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: /dev/ttys001 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Memory: MiB / MiB 
;MMMMMMMMMMMMMMMMMMMMMMMM:
:MMMMMMMMMMMMMMMMMMMMMMMM:                               
.MMMMMMMMMMMMMMMMMMMMMMMMX.
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.
    kMMMMMMMMMMMMMMMMMMMMMMd
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.

Am1nCmd:~ root#
