### ISSUE TITLE
[Terminal Font] default font not displayed if no custom terminal config

### ISSUE THREAD

**Issue by plgruener** [dylanaraps/neofetch#1064]
## Description
For some terminal emulators (e.g. xterm,urxvt,kitty,roxterm,terminator), if **no** custom terminal font is set, neofetch fails to detect the default terminal font that is used in this case.
In my main terminal where I've customized the font, everything works as expected.

These were just the terminal I have installed. Some of them may use the system font as default, but especially xterm/urxvt does not. Also I was not able to detect 'by hand' where xterm gets it default font from. The problems is of course that neofetch cannot detect the termfont from config when there is no config file for that terminal.

This is probably no big issue at all, since everyone who uses neofetch to display his termfont will have set the config.

One could probably get around that by checking for default configs in /etc or wherenot, but if you think it's not worth the hassle, feel free to close this issue. Maybe an entry in the wiki would be a good idea, too.

#### Neofetch version
v5.0.0 (ArchLinux) as well as recent github master

## Config file
info term_font is enabled, else default config.

## Verbose log
in xterm with recent github master (commit 78f355ba6d40bcd02e59626e43691bce85309844) see here: https://gist.github.com/plgruener/eefac3ad3c83e4ecbf262fc2a2376c19

**Comment by konimex** [comment]
The only problem here would be how can we detect the default font itself.

**Comment by dylanaraps** [comment]
If it's just defaults then we should leave it.

**Comment by rien333** [comment]
I'm having trouble understanding why this was closed. For starters, what is a "custom font" in this context? I'm using the kitty terminal, and have set an explicit default font in its configuration file, which is not displayed in neofetch's output. Is this just purely the terminal's fault? 

Neofetch displays my font just fine when running in the st terminal, if that matters.
