### ISSUE TITLE
--logo parameter changes primary terminal font

### ISSUE THREAD

**Issue by PedroBarcha** [dylanaraps/neofetch#1065]
## Description
I just noticed that running Neofetch with `--logo` parameter changes the primary color of the terminal's font. By issuing `ls` , things turn back to normal for some reason.

#### Neofetch version
5.0.0 (arch)

## Config file
Default

## Verbose log
`neofetch --logo -vv 2`
https://gist.github.com/PedroBarcha/7b84a44ec8e895b3355edc6a0e5433bf

**Comment by plgruener** [comment]
I can confirm, the error also persists with the recent git version (commit 78f355ba6d40bcd02e59626e43691bce85309844).
But: only in bash, not in zsh/fish, and only with the `--logo` switch. Also I had to issue `ls --color` explicitly to revert textcolor to normal.
