### ISSUE TITLE
Mac not supported?

### ISSUE THREAD

**Issue by sunlight0-0** [dylanaraps/neofetch#1066]
## Description

If you're suggesting a new feature then just a description will suffice.

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by plgruener** [comment]
As far as I know it should be, see:
https://github.com/dylanaraps/neofetch/wiki/Installation#macos-homebrew

Also, it would be useful for the developers if you could leave a more descriptive message consisting of more than just the title.

**Comment by konimex** [comment]
neofetch does support MacOS, but it is a bit bugged right now.

If you have a bug report, please open a new issue.
