### ISSUE TITLE
Pentoo logo missing

### ISSUE THREAD

**Issue by gkroon** [dylanaraps/neofetch#1069]
## Description

Could you create a logo for Pentoo [1]? :slightly_smiling_face: 

#### Neofetch version
Neofetch 3.4.0

## Screenshot

<img src="https://preview.ibb.co/iZe0mK/2018_08_06_213851_932x432_scrot.png">

## Verbose log
https://pastebin.com/GHFVHH5y

[1]
<img src="https://avatars0.githubusercontent.com/u/6411603">

**Comment by dylanaraps** [comment]
oof. That logo won't translate to ascii. I'll come up with something.

**Comment by dylanaraps** [comment]
Done.
