### ISSUE TITLE
Unable to remove image

### ISSUE THREAD

**Issue by tcpun** [dylanaraps/neofetch#1071]
## Description
image_source="off" should remove logo

#### Neofetch version
2.0.2-1 500
raspbian stretch

## Screenshot
  .',;:cc;,'.    .,;::c:,,.    pi@XXXXX 
 ,ooolcloooo:  'oooooccloo:    --------------- 
 .looooc;;:ol  :oc;;:ooooo'    OS: Raspbian GNU/Linux 9.4 (stretch) armv7l 
   ;oooooo:      ,ooooooc.     Model: Raspberry Pi 3 Model B Plus Rev 1.3 
     .,:;'.       .;:;'.       Kernel: 4.14.52-v7+ 
     .... ..'''''. ....        Uptime: 16h 
   .''.   ..'''''.  ..''.      Packages: 507 
   ..  .....    .....  ..      Shell: bash 4.4.12 
  .  .'''''''  .''''''.  .     ​ 
.'' .''''''''  .'''''''. ''.   CPU: ARMv7 rev 4 (v7l) (4) @ 1.4GHz 
'''  '''''''    .''''''  '''   CPU Usage: 15% 
.'    ........... ...    .'.   ​ 
  ....    ''''''''.   .''.     CPU Temp: 56.8°C 
  '''''.  ''''''''. .'''''     GPU Temp: 56.4°C 
   '''''.  .'''''. .'''''.     ​ 
    ..''.     .    .''..       Memory: 101MB / 976MB 
          .'''''''             Disk: 1.4G / 17G (9%) 
           ......              ​ 
                               Local IP: XX.XX.XX.XX 
                               Public IP: XXXX:XXXX::XXXX

**Comment by konimex** [comment]
>2.0.2

Does this still happen in the latest version?

**Comment by konimex** [comment]
Closing as this is a very old version of neofetch.
