### ISSUE TITLE
Image displays disappears automactically or upon mouse hover over 

### ISSUE THREAD

**Issue by JackieMium** [dylanaraps/neofetch#1074]
## Description

I am using Debian sid, neofetch 5.0.0-1. `w3m-img` and `imagemagic` both installed.
I have a line like:

```
image_source="/home/adam/Pictures/giantPanda.128.jpg"
```

in `~/.config/neofetch/config`. However, neofetch cmd in xfce4-terminal displays non-sense like this:

![image](https://user-images.githubusercontent.com/12944832/44245889-d1a00580-a20d-11e8-95ea-29d6e421e742.png)

I've changed the font but they all resulted in this. And I tested in Xfce4-terminal, LXterminal and Sakura, all the same results.

Then I try to run the cmd `neofetch --w3m ~/Pictures/Gakki.jpg --size 400px 400px` to specify a picture to display( to test if it's related to the picture so I changed to another one). In LXterminal, image just won't show up(first in the pic below), while Xfce4-terminal and Sakura (2nd and 3rd below) shows the picture but it disappear soon after a sec or two, or it disappears when you hover over your mouse. As you can see in the 2nd below, the picture is half-displayed. It was because I hover over my mouse from bottom to middle of the pic(so the bottom half disappeared). Sometimes the picture in Sakura or Xfce4-terminal just diappears automactically without any mouse movement, let alone hover over the picture.

![image](https://user-images.githubusercontent.com/12944832/44246295-f72e0e80-a20f-11e8-97ab-e054aa4778aa.png)

Maybe  it is related to #18 , I don't know as there seemed no solution in that issue, either.
Just to make it clear, chafa and imgcat both works fine in Xfce4-terminal.

**Comment by konimex** [comment]
Please provide a full log when your xfce4-terminal displays the.. thing.

**Comment by konimex** [comment]
Use `-vv`, not `--vv`.

**Comment by JackieMium** [comment]
@konimex great, now the non-sense content is all over, contents of `stderr.log` and `stdout.log`, as well as terminal output( I don't know why there is still output in terminal). Contents I am not sure can be copied and pasted to pastebin. To make it the raw file you can see I share it on Mega:

`stdout.log`: https://mega.nz/#!8GoGQa5K
`stderr.log`: https://mega.nz/#!sbhkiSzA

Hope it's some stupid mistake I am making that results in this mess.

**Comment by konimex** [comment]
I cannot open both logs since it's I need a "Decryption Key".

You can upload your log to [ptpb.pw](https://ptpb.pw) or [termbin](https://termbin.com), or just unlock your files.

**Comment by JackieMium** [comment]
@konimex Sorry, my bad. I've added the key string now. I've tested in a incognito windows and made sure they can be downloaded.

**Comment by konimex** [comment]
CMIIW but after downloading both files it seems `stderr.log` and `stdout.log` is the exact same file.

Can you just do a `neofetch -vv 2>stderr` (leave stdout be)?

**Comment by JackieMium** [comment]
@konimex Yes, I noticed that and mentioned before. They look exactly the same.
Anyway, this is the outpout from `neofetch -vv 2 > stderr.log` :  https://mega.nz/#!4a4hGIIQ!sK5jrcHAIEN99_DMONv2fb7VyXa3REsBj6c5a9-HCLk

I am sorry if this is helping as I think they are still the same non-sense as above, but it's definitely not the file I uploaded before.

**Comment by konimex** [comment]
Can you test the [ascii-image](https://github.com/dylanaraps/neofetch/tree/ascii-image) branch to see if the problem is resolved? Thanks.

**Comment by JackieMium** [comment]
@konimex
OK, will try that.

**Comment by konimex** [comment]
Can you upload the logs and your config with the ascii-image branch?

**Comment by JackieMium** [comment]
@konimex the log is really strange. I ran the cmd `./neofetch --w3m ~/Desktop/Gakki.png --size 400px 400px  -vv 2 > stderr.log`  and opened `stderr.log` with mousepad. There was only one line:

![image](https://user-images.githubusercontent.com/12944832/44617410-3f929f80-a894-11e8-8100-94cf32f427ca.png)

If I ran `cat stderr.log` in terminal and it seemed to run "clear terminal" as terminal content was cleared and resulted in a prompted with ` ;900;1530t` already inputed:

![image](https://user-images.githubusercontent.com/12944832/44617415-605af500-a894-11e8-9bd4-3f59648708a4.png)

I've uploaded the log file here: http://zipansion.com/3EtRW

**Comment by konimex** [comment]
When you're testing neofetch, what are you using? What's the result for any other terminals?

Also, do NOT use any adf.ly links.

**Comment by JackieMium** [comment]
@konimex 
Do you mean what I was doing in that terminal? I don't think I was doing anything, as I launched a new terminal the result remained the same. I tried this in Xfce4-terminal and LXterminal.

**Comment by konimex** [comment]
I meant what terminal are you using when you're testing neofetch.

**Comment by JackieMium** [comment]
OK. I think we're on to something here. I opened a UXTerm and used the very same cmd as above. The picture display seemed to be fine. It won't disappear or flash anymore. Only if I double clicked on the picture a gray block line appeared where I clicked and quicly turned to black(one line each double click):

![image](https://user-images.githubusercontent.com/12944832/44617825-a1570780-a89c-11e8-9e2b-1555888d9061.png)

While when I did this in fresh launched Xfce4-terminal and LXterminal, I still got the same results as before. So could this be a problem with Xfce4-terminal and LXterminal specificly?  And is the gray line expected when I double click on the picture?

Here is `./neofetch --w3m ~/Desktop/Gakki.png --size 400px 400px  -vv 2 > stderr.log` from UXTerm:
https://ptpb.pw/VbCF

**Comment by konimex** [comment]
About the grey line: Yes, it's expected due to the limitations of w3m-img.

I also tested this on xfce4-terminal and lxterminal and looks like w3m-img refuses to show the image at all. I don't know if it's a neofetch bug or w3m-img bug.

**Comment by JackieMium** [comment]
@konimex Well then, bad luck for me. Thanks for your time and patience along the way : )

**Comment by LionNatsu** [comment]
Are you sure you are using `2 > stderr.log`? I mean there is a whitespace.

I think the correct cmdline should be `2> stderr.log`, 

> both files it seems stderr.log and stdout.log is the exact same file.

No wonder…

**Comment by JackieMium** [comment]
@LionNatsu My bad. Thanks for your information.
@konimex Anyway, I tried `neofetch --w3m ~/Desktop/Gakki.png --size 400px 400px -vv 2> stderr.git.log` with both Debian repo version neofetch and ascii-image branch version. Here are the log files:

repo version log: [stderr.org.log](https://github.com/dylanaraps/neofetch/files/2321561/stderr.org.log)
ascii-image branch version log: [stderr.git.log](https://github.com/dylanaraps/neofetch/files/2321562/stderr.git.log)

**Comment by dylanaraps** [comment]
`w3m-img` issues aren't our problem. Nothing we can do to fix them.
