### ISSUE TITLE
Small question about weather info

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/neofetch#1075]
If this isn't the appropriate place, my apologies.
I have weather info displaying in my neofetch config file:

prin "Weather" "$(curl wttr.in/?0?q?T | awk '/°(C|F)/ {printf $(NF-1) $(NF) " ("a")"} /,/ {a=$0}')"

But I don't want the location info displayed, just the temp. Can someone show me how to alter the line? Sorry for the noob question.

Thanks.

**Comment by konimex** [comment]
This is an invalid question for neofetch (we don't officially support custom functions).

However, to answer your question, you can remove the  ` " ("a")"` (be careful to **not** delete the closing bracket!) and the ` /,/ {a=$0}` part.
