### ISSUE TITLE
Neofetch error, doesnt show ASCII image

### ISSUE THREAD

**Issue by denzveloper** [dylanaraps/neofetch#1076]
## Description

My neofetch have a error while i running that on tty console. this outputing randomly unicode text.
It begin when i upgraded version neofetch. before i update version, neofetch send a logo of my linux distro. i'm using zsh shell, when i bring back to bash, username, hostname and command following randomly unicode text. But in terminal GUI(konsole, xfce4-terminal, etc) no have a problem.
-Thanks to resolve my problem. Sorry Bad English-

#### Neofetch version
Neofetch 5.0.0

## Screenshot
-None- I Can't Capiture the screenshoot(You Can look in verbose log)

## Config file
http://save.unaux.com/upload/files/configneofetch

## Verbose log
http://save.unaux.com/upload/files/neofetchlog

**Comment by konimex** [comment]
Can you test the [ascii-image](https://github.com/dylanaraps/neofetch/tree/ascii-image) branch to see if the problem is resolved? Thanks.

**Comment by denzveloper** [comment]
Thanks, Its works for me!
