### ISSUE TITLE
xterm doesn't display w3m image

### ISSUE THREAD

**Issue by TheCactusBlue** [dylanaraps/neofetch#1077]
## Description
what the title says, I've installed the dependencies.

## Screenshot
![screenie](https://i.imgur.com/kuRdfVb.png)

## Config file
https://pastebin.com/v9Wxfsfc

## Verbose log
https://pastebin.com/Wh6ucmED

**Comment by konimex** [comment]
Does this error occur on 5.0.0 / git version?

**Comment by TheCactusBlue** [comment]
how would I go about installing the git version?

**Comment by konimex** [comment]
Just clone the git repo of neofetch and run it.

**Comment by TheCactusBlue** [comment]
https://pastebin.com/U42vhjnK

**Comment by dylanaraps** [comment]
There's something wrong in your system causing the window size to be reported as `1x1`.

```sh
+ term_width=1
+ term_height='1
```
