### ISSUE TITLE
Lower Image Quality in 5.0.0 than 3.2.0 for iTerm2

### ISSUE THREAD

**Issue by n8ta** [dylanaraps/neofetch#1079]
## Description
The current fix for iterm2 images shows lower quality images than the previous version.

#### Neofetch version
Two in question 3.2.0 and 5.0.0

## Screenshot
Top : current master, Bottom: 3.2.0
https://s15.postimg.cc/9peikrbdn/Screen_Shot_2018-08-24_at_11.17.12_PM.png

## Config file
https://pastebin.com/M6ngFYx0

## Verbose log
 https://pastebin.com/iFaPUkRN

This was spawned from #1053 and @konimex mentioned @dylanaraps may be relevant to the discussion.

**Comment by dylanaraps** [comment]
Fixed.

Try it out and let me know if this needs tweaking.
