### ISSUE TITLE
Fortune command instead of ascii distro art or picture

### ISSUE THREAD

**Issue by xWayfarer** [dylanaraps/neofetch#1081]
## Description

I thought it would be fun to have something like fortune command instead of picture or just ascii art. So I tried something with `fortune | parrotsay`. It has to be enhanced, but it works !

- https://github.com/matheuss/parrotsay

## Screenshot

- https://imgur.com/a/HVDQ9tj

## Config file

I changed this 
```bash
"Ubuntu"*)
            set_colors 1 7 3
            read -rd '' ascii_data <<'EOF'
${c1}            .-/+oossssoo+/-.
        `:+ssssssssssssssssss+:`
      -+ssssssssssssssssssyyssss+-
    .ossssssssssssssssss${c2}dMMMNy${c1}sssso.
   /sssssssssss${c2}hdmmNNmmyNMMMMh${c1}ssssss/
  +sssssssss${c2}hm${c1}yd${c2}MMMMMMMNddddy${c1}ssssssss+
 /ssssssss${c2}hNMMM${c1}yh${c2}hyyyyhmNMMMNh${c1}ssssssss/
.ssssssss${c2}dMMMNh${c1}ssssssssss${c2}hNMMMd${c1}ssssssss.
+ssss${c2}hhhyNMMNy${c1}ssssssssssss${c2}yNMMMy${c1}sssssss+
oss${c2}yNMMMNyMMh${c1}ssssssssssssss${c2}hmmmh${c1}ssssssso
oss${c2}yNMMMNyMMh${c1}sssssssssssssshmmmh${c1}ssssssso
+ssss${c2}hhhyNMMNy${c1}ssssssssssss${c2}yNMMMy${c1}sssssss+
.ssssssss${c2}dMMMNh${c1}ssssssssss${c2}hNMMMd${c1}ssssssss.
 /ssssssss${c2}hNMMM${c1}yh${c2}hyyyyhdNMMMNh${c1}ssssssss/
  +sssssssss${c2}dm${c1}yd${c2}MMMMMMMMddddy${c1}ssssssss+
   /sssssssssss${c2}hdmNNNNmyNMMMMh${c1}ssssss/
    .ossssssssssssssssss${c2}dMMMNy${c1}sssso.
      -+sssssssssssssssss${c2}yyy${c1}ssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
EOF
;;
```
To this
```bash
"Ubuntu"*)
IFS='%'
read -rd '' ascii_data<<<"$(fortune | parrotsay)"
;; 
```

**Comment by xPMo** [comment]
While you *could* add fortune and parrotsay as optional depends, what's probably easier is overriding the `get_ascii` function in your ~/.config/neofetch/config.

I don't have parrotsay installed (nor do I want to, I don't have npm installed), but here is a basic implementation based on neofetch's `get_ascii` function.  Add this to your config file, and when neofetch sources it, it will override the default function.

You will probably need to change the line calculation a bit, and maybe add flags to reduce the size of your parrot because of ANSI escape sequences, but this is a good start.

```bash
get_ascii() {
    ascii_data="$(fortune | parrotsay)"

    # Set locale to get correct padding.
    LC_ALL="$sys_locale"

    # Calculate size of ascii file in line length / line count.
    while IFS=$'\n' read -r line; do
        ((${#line} > ascii_length)) && ascii_length="${#line}"
        ((++lines))
    done <<< "${ascii_data}"

    ((text_padding=ascii_length+gap))
    printf '%b\n' "$ascii_data"
    LC_ALL=C
}
```

**Comment by dylanaraps** [comment]
Done.

https://github.com/dylanaraps/neofetch/pull/1153

Example:

```sh
# fortune + cowsay
neofetch --ascii "$(fortune | cowsay -W 30)"

# figlet
neofetch --ascii "$(figlet -w 30 hello world)"
```

**Comment by dylanaraps** [comment]
![popop](https://user-images.githubusercontent.com/6799467/50778662-3506fe80-12a7-11e9-96d5-a5caadf6700c.png)
