### ISSUE TITLE
Neofetch Shows Wrong Vega

### ISSUE THREAD

**Issue by ibrokemypie** [dylanaraps/neofetch#1083]
## Description

If you're suggesting a new feature then just a description will suffice.
I have a vega 56 and it is shown as vega 64 by neofetch

#### Neofetch version
5.0.0-1

## Screenshot
![image](https://user-images.githubusercontent.com/7827846/44942839-f85d5f00-adfd-11e8-9a3d-e05c65116b56.png)

## Config file
https://bpaste.net/show/215516504c18

## Verbose log
https://bpaste.net/show/7bf46897b88b

**Comment by konimex** [comment]
Can you provide the output of `lspci -nn` ?

**Comment by ibrokemypie** [comment]
https://bpaste.net/show/7af414c5adad

**Comment by konimex** [comment]
So this is technically not a neofetch bug but more of a bug within the pci-ids database itself. Just to be sure, what is the output of `glxinfo | grep -F 'OpenGL renderer string'`?

**Comment by ibrokemypie** [comment]
OpenGL renderer string: Radeon RX Vega (VEGA10, DRM 3.26.0, 4.18.5-arch1-1-ARCH, LLVM 8.0.0)

**Comment by konimex** [comment]
Alright. I'll report it to the [pci-ids database](https://pci-ids.ucw.cz/read/PC/1002/687f) later. In the meantime, I'll keep the issue open.

**Comment by konimex** [comment]
I'm closing this since the database has been updated.
