### ISSUE TITLE
Neofetch is not looking at config.conf for settings after successful initial startup

### ISSUE THREAD

**Issue by erikdubois** [dylanaraps/neofetch#1088]
#### Neofetch version
5.0.0

ArcoLinux uses Neofetch standard in the terminal.

We have a config file called **config.conf** that is being applied at first run. No problems there. But when you want to edit this file and add or delete lines in the config then nothing happens. We still get the initial config.conf settings.

I have found out that adding a symlink fixes this issue.

`ln -s config.conf config`

At some point in the script it is still looking for the old configuration file **config**. That is my educated guess ;-) or I could be totally wrong.

**Comment by konimex** [comment]
So if I get this right, to reproduce this behavior you have to:

1. Install a fresh instance of neofetch in any OS
2. Run neofetch with a pre-existing `config.conf`

Is that right? Or am I missing something?

**Comment by erikdubois** [comment]
correct and no config file present nor a symlink
it will read the config.conf.
Then you change it to add more or less lines and it will not change.

**Comment by erikdubois** [comment]
https://youtu.be/pkCgHal1lKI

**Comment by erikdubois** [comment]
Need more info let me know. The sooner it works the better.

**Comment by konimex** [comment]
Alright. I cannot reproduce this on all machines and VMs I currently have.

1. Can you reproduce what you linked and post it again, but instead of running plain `neofetch`, run `neofetch -v` instead?
2. Can you provide a full log (without symlinking)?

**Comment by erikdubois** [comment]
Forgot to do this yesterday with the launch date coming closer.
And I understand what is happening
![neofetch](https://user-images.githubusercontent.com/10594806/45262078-3581ac80-b40f-11e8-9a80-9d7abfa21089.jpg)

For some strange reason he is taking the backup file and not the official file. 
So when we edit the backup file then everything works straight away.

I would rather keep the backup file for users that do not know the original version anymore after editing the code and then can put it back.

Thanks for looking into it.

**Comment by konimex** [comment]
Alright.

Here's what I got.

In function `get_user_config()`. Particularly in `files=("$XDG_CONFIG_HOME"/neofetch/confi*)`, neofetch gets `config-backup.conf` first then `config.conf`.

A **workaround** is to delete `config-backup.conf` so it'll read `config.conf` instead. However, this does **not** resolve what happened.

I'm going to keep this issue open for when @dylanaraps comes back since I'm not sure on how to handle this.

**Comment by erikdubois** [comment]
yes it might be best to tell neofetch to look ONLY for the file called config.conf and nothing else.

**Comment by erikdubois** [comment]
any more info needed on this?
