### ISSUE TITLE
Distro ascii art really big

### ISSUE THREAD

**Issue by hallonfras** [dylanaraps/neofetch#1089]
## Description

If you're suggesting a new feature then just a description will suffice.

#### Neofetch version
Latest from the arch repos as of writing this

## Screenshot
![2018-09-10-212456_1366x768_scrot](https://user-images.githubusercontent.com/42581623/45319410-0454c980-b540-11e8-9ba7-3b2333b67f14.png)
![2018-09-10-212502_1366x768_scrot](https://user-images.githubusercontent.com/42581623/45319413-061e8d00-b540-11e8-93cc-bd23090b5e0b.png)

## Config file
Default (just installed)
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

Thanks in advance for the help

**Comment by xPMo** [comment]
Your terminal emulator's character width is very wide (due to your language).  I'd look for a terminal which handles variable-width better than urxvt, since [a previous patch for it was rejected](http://lists.schmorp.de/pipermail/rxvt-unicode/2014q4/002041.html)

**Comment by hallonfras** [comment]
i fixed it by setting urxvts letterspacing to -1

**Comment by konimex** [comment]
Closing since this is a terminal issue and not a neofetch issue.
