### ISSUE TITLE
Please add ASCII art for Reborn OS

### ISSUE THREAD

**Issue by laughinginloud** [dylanaraps/neofetch#1092]
## Description

Reborn is missing its logo's ASCII art. Could it be added?

### Logo

![immagine](https://user-images.githubusercontent.com/33002186/45586567-a3d7da80-b8f9-11e8-8d5d-b78aca1b34a1.png)

**Comment by dylanaraps** [comment]
Need a screenshot of Neofetch running on Reborn OS.
