### ISSUE TITLE
Neofetch is not displaying image

### ISSUE THREAD

**Issue by Oslint** [dylanaraps/neofetch#1093]
#### Neofetch version

Neofetch 5.0.0

## Config file

https://gist.github.com/Oslint/e798d77dfcdd75d780a31570e634622a

## Verbose log

https://gist.github.com/Oslint/a5e106d85c9c23bea66e1de73f6c474c

## Using terminal

gnome-terminal

Neofetch isn't displaying image..

**Comment by Oslint** [comment]
No, it doesn't work in version 4.0.2

**Comment by konimex** [comment]
I cannot reproduce it on my GNOME Terminal 3.30, what GNOME Terminal version are you using?

**Comment by angus-y** [comment]
My GNOME version is 3.28.2

**Comment by dylanaraps** [comment]
There's an issue with `w3m-img` on your system.

**Comment by gmikhail** [comment]
Same issue. It works in `xterm`, but not works in [ElementaryOS default terminal](https://github.com/elementary/terminal).

**Comment by JosephCW** [comment]
Same issue where it works in xterm but not in GNOME Shell on Ubuntu 18.10

**Comment by akbrucke** [comment]
Same issue, also works in xterm but not in gnome terminal or any other terminal I try, running ArcoLinux
