### ISSUE TITLE
"Terminal" line disapperas when xterm is launched with -hold option

### ISSUE THREAD

**Issue by leewdch** [dylanaraps/neofetch#1097]
#### Neofetch version
Neofetch 5.0.0
## Screenshot
![image](https://user-images.githubusercontent.com/11262717/45892493-96729280-bdc8-11e8-8fd5-b4e1d5cc8ac0.png)
## Config file
https://pastebin.com/0WhC3QFm
## Verbose log
https://pastebin.com/PC72uUx8

This is the command I used to launch xterm:
`uxterm -geometry 64x20 -hold -name float -e neofetch`
When launched with this line Terminal correctly shows..
`uxterm -geometry 64x20 -hold -name float -e "neofetch -vv 2> neofetchlog"`

**Comment by leewdch** [comment]
I just tried with URxvt and the same thing happens
![image](https://user-images.githubusercontent.com/11262717/45928147-3baf7700-bf3f-11e8-9ae3-a7ee166217de.png)

**Comment by dylanaraps** [comment]
This only happens with `w3m-img` right?

**Comment by leewdch** [comment]
Ok apparently if I use the same command in terminal it works, if I run it with sxhkd the issue happens. This is the command:
`urxvt -geometry 68x16 -hold -e neofetch --backend w3m --source wallpaper`

**Comment by dylanaraps** [comment]
`w3m-img` issues aren't my problem.
