### ISSUE TITLE
[opensuse] bash shebang

### ISSUE THREAD

**Issue by rudreais** [dylanaraps/neofetch#1100]
## Description

shebang: bash is not found on opensuse leap 15

#### Neofetch version
release v5.0.0

### Fix
changes `/usr/bin/env bash` with `/bin/bash` (for opensuse, tho)

**Comment by rudreais** [comment]
addition: it maybe comes from default PATH of zsh.
so it probably applies to zsh users

**Comment by konimex** [comment]
Are you using git version?

[openSUSE](https://build.opensuse.org/package/show/openSUSE:Factory/neofetch)'s official repo shows that they patched it manually.

**Comment by rudreais** [comment]
yep i used git version, didn't see about the official repo, so it's my bad on this one

**Comment by dylanaraps** [comment]
Yeah, not gonna make this change. It's more an OpenSUSE issue than a neofetch one.
