### ISSUE TITLE
Song info is broken for some players

### ISSUE THREAD

**Issue by arisinfenix** [dylanaraps/neofetch#1102]
## Description
Commit e6b8f4f broke some players that use a query command with a format string.

e.g.: `deadbeef --nowplaying-tf '%artist% \n %album% \n %title%'`
The newline in the format string is not interpreted/printed as was intended.

I have not tested all players that use a query command with format string,
but at least deadbeef, rhythmbox and qmmp are affected.

#### Neofetch version
git

## Screenshot
deadbeef
![deadbeef](https://user-images.githubusercontent.com/40315484/47254174-aed4dc00-d45e-11e8-9cb8-e2017875e1d2.png)

rhythmbox, qmmp
![rhythmbox](https://user-images.githubusercontent.com/40315484/47254179-c318d900-d45e-11e8-8f4f-73b7ebb47245.png)

**Comment by arisinfenix** [comment]
Rhythmbox can use `get_song_dbus`, see #1110

A possible solution for the other affected players would be to add back separator to the query commands and then pipe the output to awk.
```bash
        "deadbeef"*)    "$(deadbeef --nowplaying-tf '%artist%-@-%album%-@-%title%' |
                           awk -F'-@-' '{print $1"\n"$2"\n"$3}')"
        ;;
```

And perhaps add a function.
```bash
    get_song_query() {
        song="$(eval "${1}" | awk -F'-@-' '{print $1"\n"$2"\n"$3')"
    }

    case "${player/*\/}" in
        ...
        "deadbeef"*)      get_song_query "deadbeef --nowplaying-tf '%artist%-@-%album%-@-%title%'" ;;
        "qmmp"*)          get_song_query "qmmp --nowplaying '%p-@-%a-@-%t'" ;;
        and so on
        ...
    ;;
```
What do you think @dylanaraps ?

**Comment by dylanaraps** [comment]
No `eval`. 

I have a laptop again so I'll try and fix this tomorrow.

**Comment by dylanaraps** [comment]
Does #1151 fix the issue?

**Comment by arisinfenix** [comment]
:+1:

I have not tested other players yet.

**Comment by arisinfenix** [comment]
mocp is not affected, works with master branch.

**Comment by dylanaraps** [comment]
**Players**

- [x] amarok
- [x] audacious
- [] banshee
- [x] bluemindo
- [x] clementine
- [x] cmus
- [] deadbeef
- [x] deepin-music
- [x] dragon
- [x] elisa
- [] exaile
- [x] gnome-music
- [x] gmusicbrowser
- [x] guayadeque
- [] iTunes
- [x] juk
- [x] lollypop
- [x] mocp
- [] mopidy
- [] mpd
- [x] netease-cloud-music
- [] pogo
- [x] pragha
- [] qmmp
- [] quodlibet
- [x] rhythmbox
- [x] sayonara
- [x] smplayer
- [] spotify
- [x] tomahawk
- [x] vlc
- [x] xmms2d
- [] yarock

**Comment by arisinfenix** [comment]
Yes I think so.

**Comment by dylanaraps** [comment]
Only `banshee` left now. Currently building it. Thanks for the help. :)

**Comment by arisinfenix** [comment]
I had no luck with `banshee` the last time I built it on Arch. It crashed when I used the `--query` commands.
As far as I know `banshee` is unmaintained/dead project, probably just too old..

**Comment by dylanaraps** [comment]
I got `banshee` working and it has no issues.

**Comment by dylanaraps** [comment]
Merged :)
