### ISSUE TITLE
Add a counter for snap packages. 

### ISSUE THREAD

**Issue by KristijanZic** [dylanaraps/neofetch#1108]
When I run neofetch I just see see:
Packages: 2740 (dpkg), 50 (flatpak),

It doesn't show the installed snaps.
Pls add snap counter too.

**Comment by konimex** [comment]
Snap support was already added in neofetch 5.0.0.

Please provide full logs.

**Comment by KristijanZic** [comment]
Sorry for the late response.

Here you go: [https://paste.ubuntu.com/p/Hwvp9rJ8bb/](https://paste.ubuntu.com/p/Hwvp9rJ8bb/)

**Comment by konimex** [comment]
At line 724 until 756 in your logs, it seems `snap` is detected properly.

So I think this is not a neofetch problem but your terminal window is too small.

**Comment by KristijanZic** [comment]
Indeed it is! :rofl:
