### ISSUE TITLE
Does not show bars

### ISSUE THREAD

**Issue by Jole94** [dylanaraps/neofetch#1109]
##Neofetch Version
version="5.0.0"

## Description
When I used the command --battery_display after a fresh install, it doesn’t showed me any bar. 
You can fix this by going into .config/neofetch/config.conf and remove the # before the line:      
#info "Battery" battery. Then the program draws the battery information. The same for cpu and memory bar. Its not an important bug, but it was a bit strange in the beginning.

**Comment by konimex** [comment]
AFAIC it's the default behaviour to not show battery info (even after `--battery_display`) unless its specified in the `print_info()` function (by removing the comment line).

Closing for the time being, but if you're adamant this is a bug, please reopen this.
