### ISSUE TITLE
Old GFX card still being reported after installation of new one on Mac

### ISSUE THREAD

**Issue by benmadethis** [dylanaraps/neofetch#1112]
## Description

Just swapped out a Radeon HD 7850 for a Nvidia GTX 970, but Neofetch is still reporting the old card (Radeon HD 7xxx). 

#### Neofetch version
Neofetch 5.0.0
## Screenshot
Neofetch output:

![neofetch output](https://user-images.githubusercontent.com/682839/47754799-fac02600-dc93-11e8-8f41-7246aae373a9.png)
`system_profiler SPDisplaysDataType` output:

![system_profiler spdisplaysdatatype output](https://user-images.githubusercontent.com/682839/47754835-13304080-dc94-11e8-86dc-264f8621cf51.png)

## Verbose log

https://gist.github.com/benmadethis/7de54535abe79fca61f6614ac64ac492

**Comment by konimex** [comment]
Delete your `/Library/Caches/neofetch/gpu` file as a workaround, but I don't know if this is a bug or not. Ping @iandrewt

**Comment by benmadethis** [comment]
Thanks @konimex that did the trick.
