### ISSUE TITLE
Release 5.0.1

### ISSUE THREAD

**Issue by marlonn** [dylanaraps/neofetch#1113]
I've been asked to nag you about releasing 5.0.1 on behalf of the Lubuntu team :D

Would be neat to have a proper (minor) release to pull into Debian soon-ish, 5.0.0 is getting a little stale.

**Comment by konimex** [comment]
That would depend on @dylanaraps.

Allow me to ask a question though, what's so "stale" about 5.0.0?

**Comment by dylanaraps** [comment]
A new release will be made when I've worked through the open issues and pull requests.
