### ISSUE TITLE
How do you make ascii logo

### ISSUE THREAD

**Issue by azzamsa** [dylanaraps/neofetch#1119]
Hi

I've read couple of issue and wiki but I can't find this. There are issue requesting to support foo distribution and the OP comes with an image. But you replied "oof. That logo won't translate to ascii. I'll come up with something."

I want to make some app that print tools and language ascii logo to terminal. e.g python, emacs, vim. I need a way to make their corresponding ascii logo. Converting their 'plain' logo will result in bad result [like this](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/4732/versions/1/screenshot.gif)

Thanks :)

**Comment by konimex** [comment]
Not a neofetch issue, so I'm closing it.

I've used [text-image](https://www.text-image.com/convert/ascii.html) to convert logo images to ASCII. Results tend to vary.
