### ISSUE TITLE
neofetch [infoname]

### ISSUE THREAD

**Issue by techtonik** [dylanaraps/neofetch#1120]
`neofetch` doesn't show GPU driver info by default. And I forget how to configure it, unless I go to GitHUb and search for the issue I created. NVIDIA driver constantly causes me random problems, and that's basically the only thing why I need `neofetch` badly - I could not remember all the hacky command to get various gfx info.

After going back to this GitHub and searching for my previous issue, I've (re)discovered that I need to find `~/.config/neofetch/config.conf` and uncomment `gpu_driver` line.

        info "GPU Driver" gpu_driver  # Linux/macOS only

But doing this on every host where I need to get quick info about is tedious, so I thought that maybe I can just run `neofetch gpu_driver` but it didn't work. And it would be nice for have this ability like for `i3status`. It would be also nice to list all supported infonames from command line.

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/neofetch/pull/1152

**Comment by dylanaraps** [comment]
Done.
