### ISSUE TITLE
Small peeves

### ISSUE THREAD

**Issue by yuannan** [dylanaraps/neofetch#1122]
## Description
1)When using color blocks range 0 to 15 there will be an extra new line.
2)There is an "extra" new line even without the blocks, this might be intentional but I find it annoying personally.
3) There should be an option to have cpu usage put along with the CPU info, same with the GPU.
4) CPU usage per core would be very nice to have.
5) Memory usage should have a percentage along like the disk usage.
6) Should be able to have a user definable timeout option for the public IP fetch. A slow request really kills the amazing speed that neofetch currently runs at.
7) Custom underline, currently while it does allow us to change the string, the string is repeated. Might as well let the user just set whatever they want as the underline as an entire string.
8) underline cannot be printed if title is not, multiple underlines cannot be used.

#### Neofetch version
5.0.0

## Screenshot
https://i.imgur.com/V4JB2AR.png

## Config file
https://pastebin.com/c1n3bPeY

## Verbose log
https://pastebin.com/PXeDicP6

**Comment by dylanaraps** [comment]
1. Fixed
2. Fixed

https://github.com/dylanaraps/neofetch/commit/85a1bd0af7e5b5752683c586305164f0d6444550

**Comment by dylanaraps** [comment]
5. Fixed

https://github.com/dylanaraps/neofetch/commit/617769059bcdb58582f842a03f9e7531fa051c7e

**Comment by dylanaraps** [comment]
7. Can just use `prin "string here"` under title to set whatever you want.

The purpose of `underline` is to match the length of the above string.

**Comment by dylanaraps** [comment]
6. Fixed

https://github.com/dylanaraps/neofetch/commit/de5a260f6b6fb0f5186a833a0612007e5c4ba8ad

**Comment by dylanaraps** [comment]
8. Works for me with master.

Config exerpt:

```sh
print_info() {
    # info title
    info underline

    info "OS" distro
    info underline
    info "Host" model
    info underline
    info "Kernel" kernel
    info underline
}
```

**Comment by dylanaraps** [comment]
4. Not sure if per core CPU usage is possible across every OS in a simple way. Hell, even the current method is inaccurate and rather messy.

**Comment by dylanaraps** [comment]
3. Will take a lot of work and I need to think about it. Also GPU usage isn't possible across every OS and GPU brand iirc.

This can be achieved in the config file like so:

```sh
print_info() {
    get_cpu; get_cpu_usage; prin "CPU" "$cpu [$cpu_usage]"
}
```
