### ISSUE TITLE
use icat backend for images (kitty terminal)

### ISSUE THREAD

**Issue by joshuah345** [dylanaraps/neofetch#1123]
## Description

Im a user of the kitty terminal which has a built in image renderer called icat. is it possible to add this feature to neofetch? for example   `kitty +icat /path/to/image` i also used the w3m backend but it seems to be broken as the image flashes and then goes away

![kazam_screenshot_00001](https://user-images.githubusercontent.com/29195927/49216031-1bb18f00-f398-11e8-86c4-57e78d3e40e9.png)

this is kitty^

**Comment by konimex** [comment]
Kitty image backend has been supported since [neofetch 4.0.0](https://github.com/dylanaraps/neofetch/releases/tag/4.0.0). Closing this.
