### ISSUE TITLE
Image not working

### ISSUE THREAD

**Issue by skintigth** [dylanaraps/neofetch#1124]
## Description
The option to display only works on terminoly, any other terminal (xfce4, xterm, mate, kitty, termite) don't show the image and the log shows `w3m failed to display the image` also tried using `jp2a` and `tycat` with the same error

#### Neofetch version
5.0.0

## Screenshot
[Link to the album](https://imgur.com/a/Q4jaeXO)

## Config file
[pastebin with config](https://pastebin.com/NJFjFDbh)

## Verbose log
[pastebin with log](https://pastebin.com/mvxLX8Px)

**Comment by dylanaraps** [comment]
Log tells me it's an issue with `w3m-img` on your system and not neofetch.
