### ISSUE TITLE
Return iOS Support

### ISSUE THREAD

**Issue by FivePixels** [dylanaraps/neofetch#1125]
## Description

I remember iOS support once existed and you could actually download the Debian package from the repository, however it seems the repository is down or doesn't exist anymore. If the Debian package could be shared once more or the binary could be recompiled that would be great. 👍

**Comment by dylanaraps** [comment]
Just download neofetch to your phone. No need to compile or anything. Repo is down since I no longer jailbreak and care enough to maintain it.
