### ISSUE TITLE
scp doesn't work in neofetch

### ISSUE THREAD

**Issue by Marslo** [dylanaraps/neofetch#1127]
## Description
ssh works. but scp doesn't

#### Neofetch version
```bash
$ neofetch --version
Neofetch 5.0.0
```

### Debug Info:
```bash
$ scp -o LogLevel=DEBUG test.txt wpc:~
....
debug1: Connection established.
...
...
Warning: Permanently added '10.69.78.55' (ECDSA) to the list of known hosts.
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LC_ALL = en_US.UTF-8
debug1: Sending env LC_MONETARY = en_US.UTF-8
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending env LC_COLLATE = en_US.UTF-8
debug1: Sending env LC_CTYPE = en_US.UTF-8
debug1: Sending env LC_NUMERIC = en_US.UTF-8
debug1: Sending env LC_MESSAGES = en_US.UTF-8
debug1: Sending env LC_TIME = en_US.UTF-8
debug1: Sending command: scp -t ~
\033[?25l\033[?7l\033[0m\033[33m\033[1m                 ..
debug1: client_input_channel_req: channel 0 rtype exit-signal reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
Transferred: sent 3180, received 4476 bytes, in 1.8 seconds
Bytes per second: sent 1749.2, received 2462.1
debug1: Exit status -1
```

## Screenshot
<img width="1105" alt="neofetch-2" src="https://user-images.githubusercontent.com/5822057/49338501-cb1e8800-f65c-11e8-95c9-0cd3dbec0bb8.png">

Here are ssh and debug mode screenshots:
ssh: `$ ssh wpc`
<img width="1292" alt="ssh-1" src="https://user-images.githubusercontent.com/5822057/49338546-48e29380-f65d-11e8-9d31-975189ff0261.png">

scp debug `$ scp -o LogLevel=DEBUG test.txt wpc:~`
<img width="1224" alt="debug-1" src="https://user-images.githubusercontent.com/5822057/49338556-6879bc00-f65d-11e8-8c60-72b8d059f38f.png">

Compare with the shell without neofetch:
<img width="1507" alt="debug-normal" src="https://user-images.githubusercontent.com/5822057/49338565-7cbdb900-f65d-11e8-8a1d-e4f92bfef20d.png">

## Config file
no config, use default settings

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

Here are netfetchlog:
[neofetchlog.zip](https://github.com/dylanaraps/neofetch/files/2636832/neofetchlog.zip)

**Comment by konimex** [comment]
I'm not even sure if neofetch is designed to work with `scp` as `scp` is used to copy files.

Can you provide a step-by-step on how to reproduce this behavior?

**Comment by iandrewt** [comment]
I'm trying to figure out what exactly you're trying to do. Are you trying to show neofetch every time you run SCP?

**Comment by Marslo** [comment]
Hi, really sorry my late response. The neofetch can show or not during the scp, but the thing is, if the neofetch enabled, the scp doesn't work. It will be better if show neofetch in scp, but it really doesn't matter if it doesn't.

**Comment by dylanaraps** [comment]
no clue.

**Comment by gavinlaking** [comment]
I see this issue has closed but I just encountered the same thing, but I think I've isolated how it happens.

I added `neofetch` to my `.bashrc` in Linux. I think `scp` must read `.bashrc`. Removing it from `.bashrc` allows `scp` to work as it did before. The solution is to add `neofetch` to `.bash_profile` instead.
