### ISSUE TITLE
Manjaro Gnome issues

### ISSUE THREAD

**Issue by maique** [dylanaraps/neofetch#1128]
## Manjaro Gnome terminals

I'm trying to display a custom image (same as desktop) in Manjaro, Gnome. It's not working.
I have no issues on i3 but, as soon as I get back to Gnome, it stops working. Config file is edited, is it a terminal issue ?

It works in xterm, but not on gnome terminal and Tilix.

Using Neofetch 5.0.0

## Screenshot
![](https://raw.githubusercontent.com/mrBatsu/tutorials/master/img/terminals.png)

**Comment by konimex** [comment]
Please provide logs from all 3 terminal programs.

**Comment by nickschiffer** [comment]
@konimex I'm also having this issue on gnome terminal on manjaro. I'd be happy to provide the log but I'm having trouble doing so. Piping the -vv output to a txt file just fills it with garbage and I'm unable to copy and paste it all here. Could you advise how to capture the log? Thanks.

**Comment by konimex** [comment]
@nickschiffer

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent
