### ISSUE TITLE
WM Theme broken on MacOS

### ISSUE THREAD

**Issue by danyisill** [dylanaraps/neofetch#1130]
## Description

No matter which color accent I choose, it displays as `WM Theme: Blue (Light)` on Mojave. Even Graphite. Also sometimes it shows up as `WM Theme: 6 (Light)`, but not always.

#### Neofetch version
Neofetch 5.0.1
## Screenshot
![2018-12-06 4 32 16](https://user-images.githubusercontent.com/23189912/49555161-f7156400-f90f-11e8-9677-9f641d03b904.png)
![2018-12-06 4 33 31](https://user-images.githubusercontent.com/23189912/49555225-36dc4b80-f910-11e8-96c3-174431b84d10.png)

## verbose log
https://gist.github.com/danyisill/3efa99b754540f7969b65fd1f325b69e

**Comment by konimex** [comment]
Please provide full logs.

**Comment by danyisill** [comment]
sorry, added

**Comment by konimex** [comment]
Pinging @iandrewt as I don't have a Mac to reproduce this.

**Comment by iandrewt** [comment]
Seems the new Dark Mode in Mojave has changed how the theme information is stored. `AppleAquaColorVariant` is always `1` for me. The new accent colour feature is stored in the `AppleAccentColor` key, as a different number for each colour option. What should we be showing for WM Theme in Mojave then?

**Comment by konimex** [comment]
Hmm... Since I'm unfamiliar with a Mac, I'll leave that up to you. But maybe we can make use of the new `AppleAccentColor` variable.

**Comment by iandrewt** [comment]
I'll need to do some more investigation as to what information I'm actually able to collect, but if it's possible I'd like the output to be in the form `{Light|Dark} ({Accent})`
