### ISSUE TITLE
Text disappearing off screen to the right

### ISSUE THREAD

**Issue by mskelo** [dylanaraps/neofetch#1133]
The text disappears off screen and I can't really figure out what's causing it. I don't remember screwing around in any config files lately either. I've attached a screenshot of the issue and the logs.
![nf](https://user-images.githubusercontent.com/9822138/49669339-5c2c9f00-fa61-11e8-92fa-0a6e13dc1e8b.png)
Log: https://pastebin.com/RZxggDZd

**Comment by dylanaraps** [comment]
This is a locale issue and not a neofetch one.
