### ISSUE TITLE
Please Could you add the fedora 29 repo

### ISSUE THREAD

**Issue by hhlp** [dylanaraps/neofetch#1136]
## Description

I'm getting this :

Failed to synchronize cache for repo 'konimex-neofetch', ignoring this repo.

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by konimex** [comment]
My apologies. I didn't update it because of some real-life needs.

Fedora 29 has been added to the my neofetch copr. Although if you want you can use the official repo instead and disable the copr.
