### ISSUE TITLE
Issues with w3m scaling

### ISSUE THREAD

**Issue by eprevodilac** [dylanaraps/neofetch#1137]
Not sure if I should open an issue on this repo or w3m's, but I thought I'd try here first.

I'm having a few problems with image scaling when running `neofetch --w3m`:  

 Resolution of any image I give w3m gets severely reduced, even when I use the source image (as opposed to letting it grab my wallpaper), and

The image is scaled to be a few lines too big and overflows into the bash prompt.

![](https://i.imgur.com/tBF7whW.png)

Not sure if there's any way to fix this in the config or what.

**Comment by dylanaraps** [comment]
You need to mess around with the config file. Image support is a huge hack.
