### ISSUE TITLE
add Huayra GNU/Linux OS support

### ISSUE THREAD

**Issue by DiegoAccorinti** [dylanaraps/neofetch#1138]
Add Huayra GNU/Linux OS support 

(https://huayra.conectarigualdad.gob.ar/)

![imagen](https://user-images.githubusercontent.com/4205235/49751720-ef95e800-fc8c-11e8-937a-a8b7011d947d.png)

HUAYRA LOGO
![logo-huayra](https://user-images.githubusercontent.com/4205235/49752001-c3c73200-fc8d-11e8-9fd6-1e1cef68ca99.png)

tnks.

**Comment by dylanaraps** [comment]
Done. That's the best I could do with the provided logo.

**Comment by DiegoAccorinti** [comment]
tnks!
