### ISSUE TITLE
Problem with Chinese song title & please add support for NetEase Music

### ISSUE THREAD

**Issue by 4679** [dylanaraps/neofetch#1140]
## Description

When I'm trying to add support for the ![NetEase Music](https://en.wikipedia.org/wiki/NetEase_Music), I found this line in source code:
`2481 [[ "$song" != *[a-z]* ]] && { unset -v song; return; }`

So some song title that only contain Chinese characters won't show.

As the matter of the support for NetEase Music, it got MPRIS implementation, so you can just add `netease-cloud-music` in to the players list. Works fine.

Thank you for creating this masterpiece, and sorry for my bad english.

**Comment by arisinfenix** [comment]
Does this work?
```bash
    [[ "$song" != *[[:alpha:]]* ]] && { unset -v song; return; }
```

**Comment by xudong-yang** [comment]
That's not the only cause. Check the code starting from the 2381 line. You will see netease-cloud-music is not supported. You may write your own, but I am not sure if any one is still watching this repo since my pull request was opened nearly half a month ago and nobody even replied. 

For the regex thing, we can work this around by saying ```[\u4e00-\u9fa5]```, but how about Japanese Arabic etc. I think it's better to know the intention of that line first, instead of directly building up more conditions.

**Comment by 4679** [comment]
@xudong-yang I just add netease-cloud-music to the player list,and comment out that line,and it's working.
![Imgur](https://i.imgur.com/EZSaJQa.png)

Yeah man, I really don't know what is that line for.

**Comment by arisinfenix** [comment]
> I think it's better to know the intention of that line first

It was originally added as
```bash
[[ "$(trim "$song")" = "-" ]] && unset -v song
```
in 8e32dc78 to avoid printing a `-` when the song info (artist and title) was empty.
(Album was not supported at that time)

And changed to it's current form in 3ece779d.

**Comment by arisinfenix** [comment]
>I am not sure if any one is still watching this repo since my pull request was opened nearly half a month ago and nobody even replied

@xudong-yang have you seen https://github.com/dylanaraps/neofetch/pull/1118#issuecomment-447560872 ?

**Comment by xudong-yang** [comment]
> > I am not sure if any one is still watching this repo since my pull request was opened nearly half a month ago and nobody even replied
> 
> @xudong-yang have you seen [#1118 (comment)](https://github.com/dylanaraps/neofetch/pull/1118#issuecomment-447560872) ?

errrrr... I didn't see that. I read that thread when I opened mine, and then I am not following it. That makes sense. I have edited my comment above. Thank you for pointing that out

**Comment by dylanaraps** [comment]
Does https://github.com/dylanaraps/neofetch/pull/1151 fix the issue?

**Comment by xudong-yang** [comment]
> Does #1151 fix the issue?

Yes, I can confirm it fixed the issue, but I would recommend adding the support of `netease-cloud-music` because its popularity in China is kind of as much as Spotify in many other regions. 


It can be easily supported with 2 lines: 

```
get_song() {
     players=(
         ......
         "netease-cloud-music"
         ......
     )

......

case "${player/*\/}" in
         ......
         "netease-cloud-music"*)     get_song_dbus "netease-cloud-music" ;;
         ......
```

**Comment by dylanaraps** [comment]
Done. Try #1151 again.

**Comment by xudong-yang** [comment]
> Done. Try #1151 again.

Cool! I have tested it, and It is working flawlessly now 👍

**Comment by dylanaraps** [comment]
Thanks for testing. Will merge the changes once I've confirmed a second issue is fixed (PR solves two issues).
