### ISSUE TITLE
Ryzen 2400G (Raven Ridge) iGPU model.

### ISSUE THREAD

**Issue by M-Klekowicki** [dylanaraps/neofetch#1141]
## Description

When running neofetch on the desktop APU **AMD Ryzen 2400G** with **Vega 11** integrated gpu, the gpu name is wrongly reported as **Vega 8 mobile**.

#### Neofetch version
3.4.0
## Screenshot
![neofetch](https://user-images.githubusercontent.com/19647983/50307697-6c00a600-0499-11e9-9c5f-cf1784a97e33.jpg)
## Config file
https://pastebin.com/6pp4teLk
## Verbose log
https://pastebin.com/LaRGH6kf

**Comment by arisinfenix** [comment]
Version 3.4.0 is pretty old, have you tried a more recent version?

This is the output on my system.

5.0.0
```
CPU: AMD Ryzen 5 2400G (8) @ 3.600GHz 
GPU: AMD ATI Radeon Vega Series
```
git-master
```
CPU: AMD Ryzen 5 2400G (8) @ 3.600GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
```

**Comment by M-Klekowicki** [comment]
@arisinfenix Gotta admit I've installed the version from the repositiories. There is no information about the Ubuntu repo being out of date in this article: https://github.com/dylanaraps/neofetch/wiki/Installation (while there is a note about debian stretch) . If it's the version problem, the problem is with the package in the repo being outdated (3.4 vs 5.0 is a MASSIVE gap) or the article being outdated.

**Comment by konimex** [comment]
Shouldn't be a problem with neofetch version (since virtually we still use `lspci` to gather data between 3.4.0 and 5.0.0).

This means your PCI database is outdated.

See [this](https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linuxfreebsd-why-does-getgpu-doesnt-show-my-exact-video-card-name) for information.

**Comment by M-Klekowicki** [comment]
@konimex "sudo update-pciids" fixed the issue for neofetch. Thank you:)
