### ISSUE TITLE
Add arcolinux_small logo in

### ISSUE THREAD

**Issue by arcolinuxz** [dylanaraps/neofetch#1146]
## Description
Our users have asked if we can provide them with a smaller logo.

#### Neofetch version
5.0.0

## Config file

Line 4954
https://github.com/erikdubois/neofetch/blob/master/neofetch

## Verbose log

```
        "ArcoLinux_small"*)
            set_colors 7 4
            read -rd '' ascii_data <<'EOF'
${c2}          A
         ooo
        ooooo
       ooooooo
      ooooooooo
     ooooo ooooo
    ooooo   ooooo
   ooooo     ooooo
  ooooo  ${c1}<oooooooo>${c2}
 ooooo      ${c1}<oooooo>${c2}
ooooo          ${c1}<oooo>${c2}
EOF

        ;;

```
If you rather prefer a pull request let me know.

**Comment by konimex** [comment]
>If you rather prefer a pull request let me know.

Sure thing. Do a PR and I'll merge it.

**Comment by erikdubois** [comment]
is this ok now?
