### ISSUE TITLE
neofetch --w3m in konsole became ascii

### ISSUE THREAD

**Issue by AnasR7** [dylanaraps/neofetch#1148]
Im using manjaro OS  kde, I have installed w3m & imagemagick...

i have already change image_backend to w3m & image source to my images..

and when i type neofetch that became mess and looks like ascii...
![screenshot_2018-12-31_11-22-26](https://user-images.githubusercontent.com/23519166/50554518-53408d80-0cee-11e9-966c-d6de7d84d7ca.png)

can you help me thanks.

**Comment by byjtje** [comment]
I have the same issue. Though interestingly enough, calling neofetch and ranger (in any order) seems to "corrupt" the terminal, depending on the image (see attachment).
Also not sure if it's intended, but absolute paths don't work (first log), even ~/... is taken relative.

**Comment by byjtje** [comment]
Oh that was is, many thanks! For some reason I thought I had xdotools already installed, sorry!
Though the Ranger issue only happened after calling neofetch, though I guess it is an issue with st and not neofetch then.

**Comment by AnasR7** [comment]
thanks
