### ISSUE TITLE
Kitty, cannot display font if set via include.

### ISSUE THREAD

**Issue by ReiLucio** [dylanaraps/neofetch#1150]
V5

e.g.
kitty.conf : 

`include /foo/bar/font.conf`

https://sw.kovidgoyal.net/kitty/conf.html

**Comment by dylanaraps** [comment]
I'm not sure if we can fix this. I mean we could parse the config and find the include file but I don't think that's a viable fix. Does kitty perhaps provide a command we can use to spit out the font information (or other config information)?

**Comment by ReiLucio** [comment]
`kitty --debug-config` may work .

**Comment by dylanaraps** [comment]
Fixed.
