### ISSUE TITLE
 Version is still set to 5.0.1

### ISSUE THREAD

**Issue by Popkornium18** [dylanaraps/neofetch#1155]
## Description

Version is still set to 5.0.1

#### Neofetch version
5.1.0

## Screenshot

![image](https://user-images.githubusercontent.com/46488511/50833321-12c9bb00-1351-11e9-9507-4332cf8c0a98.png)

**Comment by dylanaraps** [comment]
The release was a misclick. It's not ready yet.

**Comment by konimex** [comment]
Ah damn I already deployed it to SlackBuilds and COPR since the tag already existed.

**Comment by dylanaraps** [comment]
The release will use the same tag. I'm working on a draft and GitHub doesn't have any sort of confirmation before release and I misclicked the release button. I deleted the release as fast as I could but the tag is stuck.

I can rush the release right now if need be. It's ready, I'm just hunting for bugs.
