### ISSUE TITLE
Bold text displayed with background color

### ISSUE THREAD

**Issue by SolitudeSF** [dylanaraps/neofetch#1156]
## Description
e155df7a726177d2bbde55cbb7ddd6dd123ad69b introduced regression. bold text now uses background color. Bedrock Linux/kitty terminal

#### Neofetch version
Latest master

## Screenshot
![image](https://user-images.githubusercontent.com/10168645/50838795-92fb1b00-1367-11e9-8bc9-b73da47b0ffb.png)

## Verbose log
https://bpaste.net/show/96e4dbc03405

**Comment by dylanaraps** [comment]
Fixed.
