### ISSUE TITLE
Line breaks arent displayed

### ISSUE THREAD

**Issue by SolitudeSF** [dylanaraps/neofetch#1157]
`info line_break` is ignored on latest master

**Comment by SolitudeSF** [comment]
nvm, looking at commits, i get that its deprecated

**Comment by SolitudeSF** [comment]
printf'ing newlines creates a sideeffect of redundant newlines after neofetch. whats the correct replacement for `info line_break` then?

**Comment by dylanaraps** [comment]
Fixed.

Alternative is now `prin '\n'`
