### ISSUE TITLE
Neofetch not in epel 7

### ISSUE THREAD

**Issue by jrhutchins** [dylanaraps/neofetch#1158]
## Description

If you're suggesting a new feature then just a description will suffice.

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by jrhutchins** [comment]
I was unable to find neofetch in the epel 7 repositories.

**Comment by konimex** [comment]
There's a COPR for EPEL-7 here.
http://copr.fedorainfracloud.org/coprs/konimex/neofetch/
