### ISSUE TITLE
--chafa not working

### ISSUE THREAD

**Issue by marcosroot** [dylanaraps/neofetch#1159]
## Description
dont display the image

#### Neofetch version
Neofetch 6.0.0
## Screenshot
https://i.imgur.com/PCetOBY.png
## Config file
default (?)
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
https://pastebin.com/DXPCDtNt

**Comment by dylanaraps** [comment]
```sh
[0m[31m[!][0m Image: Imagemagick not found, falling back to ascii mode.
```
