### ISSUE TITLE
Ascii art not working after update

### ISSUE THREAD

**Issue by pelomedusa** [dylanaraps/neofetch#1164]
## Description

Ascii art doesn't seems to be working since i upgraded to 6.0.0.
$> neofetch --ascii /home/username/ascii.txt

#### Neofetch version
6.0.0
## Screenshot
![screenshot from 2019-01-09 12 07 27](https://user-images.githubusercontent.com/15833842/50895740-3bac8780-1407-11e9-8b71-883daf769cec.png)

## Config file
Not changed

## Verbose log
$> neofetch -vv --ascii /home/username/ascii.txt 2> neolog
https://pastebin.com/nst3fZ7A

**Comment by dylanaraps** [comment]
Already fixed in master. A new release will be made over the next few days. A workaround while you wait is to rename the file to anything other than `ascii`. :+1:

**Comment by pelomedusa** [comment]
thank you, that was fast

**Comment by dylanaraps** [comment]
No problem. Multiple devices around me ding when something on GitHub happens. :)

**Comment by ccokee** [comment]
Still happens in debian buster
