### ISSUE TITLE
Showing lf as my terminal instead of termite

### ISSUE THREAD

**Issue by ngenisis** [dylanaraps/neofetch#1166]
## Description

I'm using `termite` as my terminal and have the `lf` file manager installed from the AUR. After the update, `neofetch` is incorrectly reporting `lf` as my terminal

#### Neofetch version

```
$ neofetch --version
Neofetch 6.0.0
```

## Screenshot

![image](https://user-images.githubusercontent.com/13491129/50914127-7dcfcc00-13fb-11e9-8b45-bc7e177bb46d.png)

## Config file

[Arch default config](https://gist.github.com/ngenisis/1d916275240eeed143ad71b9867c7866)

## Verbose log

[gist](https://gist.github.com/ngenisis/744c5f3a132de2ba990e207b0e93de06)

**Comment by dylanaraps** [comment]
Are you by any chance running neofetch through lf?

**Comment by ngenisis** [comment]
I can't replicate, so maybe I was.
