### ISSUE TITLE
commenting 'info "GPU" gpu' is not enough to not print GPU

### ISSUE THREAD

**Issue by m-svo** [dylanaraps/neofetch#1167]
## Description

I have an Ubuntu in the cloud, so neofetch shows me `GPU: Vendor 1234 Device 1111`
I decided to turn that off, so as per wiki edited: `info "GPU" gpu` to `# info "GPU" gpu`
However, `GPU: Vendor 1234 Device 1111` is still printed.
I am not good at bash to propose a fix, but I worked around that by changing `get_gpu` function name to `not_get_gpu`.

#### Neofetch version
6.0.1 (git master, 415ef5d4aeb1cced7afcf9fd1223dd09c3306b9c)
## Screenshot
![image](https://user-images.githubusercontent.com/32303844/51022131-7c85d700-1594-11e9-8aac-bba2020dcb1c.png)

## Config file
[defaults](https://raw.githubusercontent.com/m-svo/neofetch/customized_print/config.conf)
## Verbose log
[log](https://raw.githubusercontent.com/m-svo/neofetch/customized_print/neofetchlog)

**Comment by dylanaraps** [comment]
What config file are you editing?

This one?: `/home/svobonas/.config/neofetch/config.conf`.

**Comment by m-svo** [comment]
Sorry, I was editing `/usr/bin/neofetch` instead of `~/.config/neofetch/config.cfg`
