### ISSUE TITLE
Small image with huge spacing

### ISSUE THREAD

**Issue by TredixHQ** [dylanaraps/neofetch#1168]
So, I have updated to Ubuntu 19.04 and now when I open up neofetch the image now is definelly smaller and with a huge spacing between the picture and the informations.

- Ubuntu 19.04
- XFCE-Terminal 0.8.7.4
![schermata del 2019-01-15 18-24-37](https://user-images.githubusercontent.com/39876044/51197838-e08d0000-18f2-11e9-883c-2d72a21a95d6.png)

**Comment by dylanaraps** [comment]
VTE terminals seem to be reporting window size incorrectly(?) when using `printf '\e[14t'`. Can you reproduce?

**Comment by dylanaraps** [comment]
`xdotool` seems to print it correctly.

```sh
xdotool getactivewindow getwindowgeometry --shell %1
```

**Comment by dylanaraps** [comment]
Does this PR fix the issue?: https://github.com/dylanaraps/neofetch/pull/1169

**Comment by TredixHQ** [comment]
> Does this PR fix the issue?: #1169

I'll give it a try, thanks!

**Comment by dylanaraps** [comment]
Ping @TredixHQ. Does the PR fix the issue?

**Comment by NO-ob** [comment]
> Ping @TredixHQ. Does the PR fix the issue?

Worked for me on xfce term 4

**Comment by TheoOliveira** [comment]
I use termite. Doesnt work either. Using i3 and compton. could be that the issue?

**Comment by 916253** [comment]
I know this is a necrobump, but I am having this same issue on macOS with iterm
