### ISSUE TITLE
Option to show memory in GB

### ISSUE THREAD

**Issue by ShayBox** [dylanaraps/neofetch#1170]
An option for the memory module that will let you show in more formats than MiB, maybe allow bits, bytes, KB, MB, GB, TB, with/without decimal place, and maybe an option for how many decimal places to show.

So instead of `3433MiB / 23974MiB` It could show `3.4GiB / 24GiB`

**Comment by TriMoon** [comment]
How about using this example to make it output like you want: :wink: 
```bash
#!/usr/bin/env bash
num=3000000
divider=1024
units="GiB"
printf -v out "%'.2f %s" $(($num / $divider)).$(($num % $divider)) $units
printf "out='%s'\n" $out
```
gives
```console
out='2,929.70 GiB'
```

**Comment by ShayBox** [comment]
How do I use that with the neofetch memory module though :thinking:

**Comment by dylanaraps** [comment]
We can also do this to "fake" it.

```sh
    # Use $mem_label if available.
    case "${mem_label:-$memory_format}" in
        "GiB")
            mem_used="${mem_used:0:-3}.${mem_used/${mem_used:0:-2}}"
            mem_total="${mem_total:0:-3}.${mem_total/${mem_total:0:-2}}"
            mem_label="GiB"
        ;;

        "KiB")
            ((mem_used=mem_used*1024))
            ((mem_total=mem_total*1024))
            mem_label="KiB"
        ;;
    esac
```

**Comment by TriMoon** [comment]
> Only issue is it throws away the value after the decimal.

Why not use `printf` like i showed in https://github.com/dylanaraps/neofetch/issues/1170#issuecomment-455576889 ?
For example using a part of the code you posted:
```shell
    case "${mem_label:-$memory_format}" in
        "GiB")
            mem_label="GiB"
            printf -v mem_used "%'.*f" \
                        ${mem_precision:-2} \
                        $(($mem_used / 1024)).$(($mem_used % 1024))
            printf -v mem_total "%'.*f" \
                        ${mem_precision:-2} \
                        $(($mem_total / 1024)).$(($mem_total % 1024))
        ;;
    esac
```

**Comment by konimex** [comment]
Neofetch almost never calls printf directly. It'll be taken care of in user's config (the `print_info()` part).

For instance, neofetch (from user config) will fetch the `memory` variable [here](https://github.com/dylanaraps/neofetch/commit/e3a6b9f40d479cea510e1a2c4b7d489b41b498c5#L2357)

**Comment by TriMoon** [comment]
printf in the way i use is not outputting anything to stdout/stderr, the -v varname is equivalent of sprintf in C/C++

**Comment by dylanaraps** [comment]
This has been implemented.

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/neofetch/commit/0435dcd0cd44bb22afa9b986f15742cc05de7b20

**Comment by ShockedCoder** [comment]
> In bash, our normal math operations don't really allow decimals so it'd require some hack (e.g. `$((3433/100))` and add a `.` manually (and IIRC neofetch used to do this, forgot when).
> 
> Maybe we can use both KiB, MiB, and GiB, but bits, bytes, and even TiB seems pointless unless there are someone out there that uses at least 1024GiB RAM.

Someone ordered a 4TB computer from linustechtips, don't remember the video tho

**Comment by Konpaku-LVX** [comment]
is there a way to make it show GB instead of GiB?

**Comment by ShockedCoder** [comment]
> is there a way to make it show GB instead of GiB?

Replace 1024 to 1000 in the code where needed and rebuild neofetch
