### ISSUE TITLE
URxvt no longer shows neofetch w/w3m backend if internalBorder is unset in Xresources

### ISSUE THREAD

**Issue by William-Imm** [dylanaraps/neofetch#1174]
## Description

Starting with neofetch version 6.0.0, running it within my URxvt terminal with w3m image display enabled only produced an error, [as shown within this gist](https://gist.github.com/William-Imm/faeee2bb380e74445d30a9b3e0602616)

Adding `URxvt.internalBorder: 0` to my Xresources allowed Neofetch to work once more. I suspect that commit 4d6a4fb4256d00aa9a2a8693c6ac8f0fa67057f5 caused the issue

#### Neofetch version
6.0.0

**Comment by dylanaraps** [comment]
Fixed. Thanks
