### ISSUE TITLE
Image too far from text output in xfce4-terminal, also dissapears when window loses focus

### ISSUE THREAD

**Issue by ifohancroft** [dylanaraps/neofetch#1176]
## Description
Image is too far from text output in xfce4-terminal, using w3m-img. Also, the image dissapears when the window loses focus

#### Neofetch version
Neofetch 5.0.0

## Screenshot
https://i.imgur.com/K207qWK.png

## Config file
https://gist.github.com/ifohancroft/e111a326ab10b7f39739e51e78993d56

## Verbose log
https://gist.github.com/ifohancroft/13a9e0300b105159a96fff5e0202b8c1

**Comment by dylanaraps** [comment]
Duplicate of https://github.com/dylanaraps/neofetch/issues/1168

Also: The image disappearing on loss of window focus isn't a neofetch issue.
