### ISSUE TITLE
Problem with writing out system info in terminal by neofetch.

### ISSUE THREAD

**Issue by WassiliaPL** [dylanaraps/neofetch#118]
It's small but very annoying issue. Below you can see my neofetch in stock size terminal:
![1](https://cloud.githubusercontent.com/assets/12752488/13398303/077cdfa0-defe-11e5-8e30-ab776234820d.png)
Problem is that when the text won't fit in line a fragment of it goes to the beggining of the next line. When you want to expand terminal window to see it in the same line you get something like this:
![2](https://cloud.githubusercontent.com/assets/12752488/13398491/d1a47950-defe-11e5-965b-d63cddae3248.png)
It causes that logo is being distrupted...
If you start neofetch in smaller window then you get worse result:
![3](https://cloud.githubusercontent.com/assets/12752488/13398574/44ed8488-deff-11e5-9cd3-aaa099169982.png)
I can only add that if you expand window at first and then do neofetch everything is fine an changing size of a window don't cause any problems.

**Comment by dylanaraps** [comment]
- Have you tried `fetch --line_wrap off`?
- What terminal emulator are you using?

**Comment by dylanaraps** [comment]
To add to this, we can't do any sort of dynamic sizing as all neofeth does is print to the terminal.
We can't make use of ncurses to do this as it's a shell script, had neofetch been writen in python
then yes I could add dynamic sizing but that isn't the case.

What I'll do is shorten the GPU output for you by adding some more substitutions.

**Comment by dylanaraps** [comment]
Try the latest master.
