### ISSUE TITLE
manjaro Kconsole terminator

### ISSUE THREAD

**Issue by testerfr810** [dylanaraps/neofetch#1180]
i will just for test and work only on Xterm ???

any idea for Kconsole and terminator ???
ty
![2](https://user-images.githubusercontent.com/46194414/51841220-66a34080-230e-11e9-811e-aa6651ce3c3e.png)
![10](https://user-images.githubusercontent.com/46194414/51841225-6a36c780-230e-11e9-83ee-bc0f4aa3193b.png)

**Comment by dylanaraps** [comment]
Not a neofetch issue. `w3m-img` only works in some terminals.
