### ISSUE TITLE
PonyOS

### ISSUE THREAD

**Issue by lond-en** [dylanaraps/neofetch#1183]
I noticed that my operating system, PonyOS, is not supported by neofetch. This is clearly an issue and should be fixed posthaste.

**Comment by dylanaraps** [comment]
Output of `uname`, `lsb_release` and `cat /etc/os-release`?

**Comment by dylanaraps** [comment]
I see. I'll install it in a VM. :+1:

**Comment by jprfts** [comment]
@lond-en do you have a link to where I can download PonyOS? I'd like to try it out.

**Comment by lond-en** [comment]
@jprfts https://www.ponyos.org/... have fun

**Comment by jprfts** [comment]
@lond-en huh. dunno what i expected.

and its not based on something else? w h y y y y y

**Comment by konimex** [comment]
Does bash even exist or can be compiled in this OS? We can't add support if it doesn't even exist.
