### ISSUE TITLE
Show swap usage

### ISSUE THREAD

**Issue by cynicastic** [dylanaraps/neofetch#1189]
Suggest adding the ability to show swap used / available (percentage) similar to memory & disk.  Should include flag for swap percentage similar to memory and disk.

While most modern systems have enough memory to make swapping relatively rare, embedded devices (e.g. routers running entware) generally need to use swap for extended functions.

**Comment by dylanaraps** [comment]
This should already be possible using the disk feature.

**Comment by dm17** [comment]
https://github.com/dylanaraps/neofetch/issues/1261 -> seems not possible to display correctly, is it? htop works fine but neofetch gets it wrong if I use /dev/partition. Found a work around?
