### ISSUE TITLE
Image Clipping into the menu bar

### ISSUE THREAD

**Issue by NO-ob** [dylanaraps/neofetch#1190]
## Description
Image is clipping into the menu bar, It isn't broken up like in the screenshot though its shows the full top of the image. I have tried using the crop feature but no image displays when using it. I have both w3m-img and image magic and am using xfceterm4, the clipping issues also happen in gnomes default terminal

#### Neofetch version
6.0.0
## Screenshot
https://i.imgur.com/shBdGQq.png
## Config file
Default Config File
## Verbose log
https://pastebin.com/bNrY1X8R

**Comment by dylanaraps** [comment]
Use `--yoffset pixels`. This is a w3m-img issue.
