### ISSUE TITLE
Neofetch breaks when trying to show up background.

### ISSUE THREAD

**Issue by The-Sound** [dylanaraps/neofetch#1195]
## Description
When launched it should just throw standard output.  Instead, if breaks at line "4205" with following description: `/usr/bin/neofetch: line 4205: ((: padding=*.background:	#061830: syntax error: operand expected (error token is "*.background:	#061830")
` 
Then again, it breaks again at line "3734" listing all my Xresource content for some reason. Using link instead of copypasting for clarity sake: https://i.imgur.com/ZNnQXI4.png

If I use neofetch --ascii it does not break.

#### Neofetch version
Neofetch 6.0.0

## Screenshot
Extended screenshot: https://i.imgur.com/qdVo5mK.png
## Config file
I think it is pretty standard, not weird things changed: https://pastebin.com/NgSk4MMT

## Verbose log
https://pastebin.com/QMp2N54a

OS is Linux Void, terminal is URXVT, background source would be used through w3m-img which works fine on other programs like ranger with preview. Tried already reinstalling with and without libraries.

**Comment by dylanaraps** [comment]
Output of `xrdb -query`?

**Comment by The-Sound** [comment]
Here, I think everything is normal. I tested it at some point removing something and everything but the result was the same.
![clipboard](https://user-images.githubusercontent.com/24360204/52571702-03390880-2e0e-11e9-8280-7710099f181b.png)

**Comment by dylanaraps** [comment]
I'm fairly certain I've fixed the issue. I'm trying to push the commit but gpg keeps hanging. Will report back when you can test (*shouldn't be too long*).

**Comment by dylanaraps** [comment]
Try this commit: https://github.com/dylanaraps/neofetch/commit/7fd9ff75a35ed3394530d645227c59ad2eab6184

**Comment by The-Sound** [comment]
After I few tries I think I'm at almost same point, with the difference that at least is not broken and it shows ascii. I've tried:

`--source w3m`
`--source wallpaper`
`--source /path/to/wallpaper`
`--source wallpaper (after moving it to same folder)`
`--source wallpaper (after testing permissions in case it was my OS)`

And a few more. Now, when I've tried too debug it through -v and -vv, it ended up saying `Image: Check the 'Images in the terminal' wiki page for more info` so I went to the wiki, checked if I had enough dependencies, and I disovered I have ImageMagick 7, and that it is an ImageMagick 6 version. I didn't try this. Could it be the thing behind all of this? Is the first time I checked ImageMagick on its own.

Log here: 

[ShortV.txt](https://github.com/dylanaraps/neofetch/files/2851695/ShortV.txt)
[LongV.txt](https://github.com/dylanaraps/neofetch/files/2851694/LongV.txt)

PS: Thank you for sticking and replying so fast.

**Comment by dylanaraps** [comment]
It's failing to find the window size. Do you have the dependencies installed for window size (*check the dependencies wiki page*)? Also, can you confirm that the commit above stops the crashes?

**Comment by The-Sound** [comment]
At first sight, it seems to be I have everything in order, as it was when it started to fail. Yes, I confirm crashes stopped, as I added on the previous post. As far as I understand it, I need `xprop` to handle size windows, and I had it. Then I tried to change the tool, moved to `xdotool` and seems to work. What could be the reason behind of this? Thank you once again.

**Comment by dylanaraps** [comment]
You need `xwininfo` + `xprop` or `xwininfo` + `xdpyinfo` or just plain `xdotool`.

`xprop` or `xdpyinfo` are used to grab the current window ID and `xwininfo` is used to grab the window size (in pixels). `xdotool` can handle both in a single command.

**Comment by The-Sound** [comment]
Oh, I didn't know that, thank you for explaining it. I wonder why it was working then, since I never installed anything than xprop but it was getting the window size just right.

So I can confirm 6.0.1 does not crash and with the xdotool tool I can get neofetch just right with my old conf and everything. I just need the people on Void Linux to update repository package and ready to go. Final thanks to you for sticking along this fast.

**Comment by dylanaraps** [comment]
No problem, thanks for working through this with me.

**Comment by Riiskyy** [comment]
I'm also having a similar issue. If I set w3m as the backend nothing is output, when I run with `-v` I'm  getting errors. Here is my config and the output of `neofetch -v and -vv`. I have w3m, xwininfo & xdotool installed and I still cannot get an image to display. Ascii works fine.

[config.txt](https://github.com/dylanaraps/neofetch/files/3194339/config.txt)
[neofetch-v.txt](https://github.com/dylanaraps/neofetch/files/3194333/neofetch-v.txt)
[neofetch-vv.txt](https://github.com/dylanaraps/neofetch/files/3194334/neofetch-vv.txt)

**Comment by almajiro** [comment]
Try to add this line into .Xresources or .Xdefaults
`
*.internalBorder:           0
`

**Comment by The-Sound** [comment]
I just hope commenting this won't reopen the issue. Following some other issues I've tried the `URxvt.internalBorder: 0` and it fixed the issue with the background image in the old version (6.0.0). Just adding this here. Thank you.
