### ISSUE TITLE
Artix Linux ascii art is incorrect

### ISSUE THREAD

**Issue by JamsNJellies** [dylanaraps/neofetch#1197]
## Description

The artix linux distro has been given a new logo so the ascii art need to be updated

Link to the new logo:

![Link](https://gitea.artixlinux.org/artix/artwork/src/commit/a708561cc4b0ef0914eac4cd0805d9df739b3bb3/icons/logo-1024x1024.png)

**Comment by konimex** [comment]
I have updated it yesterday.

https://github.com/dylanaraps/neofetch/commit/2fccec783e6822aaa7ce67c93d05857d2962eb8c
