### ISSUE TITLE
/usr/bin/neofetch: 14: /usr/bin/neofetch: Bad substitution

### ISSUE THREAD

**Issue by JPRuehmann** [dylanaraps/neofetch#1201]
## Description
just updated my kubuntu to 18.04 now I get this.
/usr/bin/neofetch: 14: /usr/bin/neofetch: Bad substitution
If you're suggesting a new feature then just a description will suffice.

#### Neofetch version
/usr/bin/neofetch: 14: /usr/bin/neofetch: Bad substitution
## Screenshot
/usr/bin/neofetch: 14: /usr/bin/neofetch: Bad substitution
## Config file
What?

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
/usr/bin/neofetch: 14: /usr/bin/neofetch: Bad substitution

**Comment by dylanaraps** [comment]
- Version of bash?: `bash --version`.
- Operating system?: `uname`.
- Version of neofetch?: `neofetch --version`.

**Comment by JPRuehmann** [comment]
Sorry for the unqualified Bug Report.
The Error was on my Side.
`which -a bash` results in /usr/local/bin/bash and /bin/bash
a` bash --version` gives invalid option
after `sudo rm /usr/local/bin/bash` `bash --version` works and therefore neofetch to.
Thanks,
