### ISSUE TITLE
Image does not work on urxvt

### ISSUE THREAD

**Issue by Signifies** [dylanaraps/neofetch#1202]
## Description
So I wanted to experiment with using images with my terminal. So far no luck. I've been using `neofetch --w3m --source My/Image` 
The second I enter the command, there is a brief glitch across my screen and I'm left with [this](https://imgur.com/a/v0fEmFf) 

#### Neofetch version
Neofetch 6.0.0
## Screenshot
[command](https://imgur.com/a/OuATcCy)
[result](https://imgur.com/a/v0fEmFf)
## Config file
[config](https://gist.github.com/Signifies/6f233fec3cb82fa5d595ac22e13d6c91)
## Verbose log
[log](https://gist.github.com/Signifies/5e3e1f7e6a8ff9df21f4b550e9ad424e)
1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
The log file needs to be generated with `--w3m source/to/img.jpg`.

**Comment by Signifies** [comment]
What do you mean exactly?

**Comment by Signifies** [comment]
So I was playing around with it, and was able to get an image to work by using `neofetch --w3m --source` however, I have no idea what I did to get it to work, and after rebooting, I am once again stuck with my previous issue.

**Comment by dylanaraps** [comment]
`neofetch --w3m /path/to/img.jpg` or edit your neofetch config.
