### ISSUE TITLE
Redundant hostname on Windows

### ISSUE THREAD

**Issue by DRSDavidSoft** [dylanaraps/neofetch#1205]
## Summary
Neofetch user info on windows needs to remove redundant host name.

### Details
```shell
david-pc\david@David-PC
```

It should read either:
- `david-pc\david`
- `david@David-PC`

but not both.

### Neofetch version
Latest "master" release as of writing this.
```
Neofetch 6.0.1
```

## Screenshot
<img width="565" alt="neofetch1" src="https://user-images.githubusercontent.com/4673812/53448636-262e0400-3a2d-11e9-9101-d6757aee17a9.png">

## Config file
None

## Verbose log
📦 [neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/2907673/neofetchlog.txt)

**Comment by konimex** [comment]
Is this on Cygwin? What's the output of `whoami`?

**Comment by DRSDavidSoft** [comment]
Yes, it's on Cygwin.

- **`whoami`**: `David`
- **`echo $HOME`**: `/mnt/c/Users/David`

BTW, my username is `David` (with the capitalized D), and I've modified the `fstab` as follows:
```
none /mnt cygdrive acl,binary,posix=0,user 0 0
```

<img width="284" src="https://user-images.githubusercontent.com/4673812/53459528-7a49e000-3a4f-11e9-8138-43f8f0272e1e.png">

**Comment by DRSDavidSoft** [comment]
@konimex I think I found the cause of problem:

```shell
λ C:\Windows\System32\whoami.exe
david-pc\david

λ C:\development\cygwin\bin\whoami.exe
David
```

This is a mistake of mine, because I executed neofetch via `bash ./neofetch` from cmd.exe and not from Cygwin.

This causes the `$PATH` to prefer win32 .exe binaries instead of Cygwin's -- and since there are two `whoami.exe` binaries, the bash script in neofetch will execute Windows' `whoami.exe` instead of Cygwin's.

If I run `./neofetch` from the Cygwin shell with proper `$PATH` pointing out to the Cygwin's `whoami`, I'll get `David` instead of `david-pc\david` as you see in my earlier comment.

---

Possible options are:

1. Add a little regex to neofetch to match and remove the hostname part if it appears
2. Force neofetch to use the absolute `/usr/bin/whoami` binary instead of the one in the path
3. Just ignore and close this issue, since it should be rare for a user to execute `neofetch` the way I do

**Comment by konimex** [comment]
Option 1 is maybe possible, but since this is an outlier case for Windows `whoami.exe` specifically, I doubt it will be added. I need @dylanaraps' opinion on this.

Option 2 is impossible since we'll have to account if `whoami` binary exists outside `/usr/bin` (e.g. NixOS, GuixSD, GoboLinux)

Option 3 is being considered.

**Comment by dylanaraps** [comment]
Option 3. Neofetch shouldn't touch the hostname or user string. I don't think this is a bug either.
