### ISSUE TITLE
Feature request: refresh information when image_loop="on"

### ISSUE THREAD

**Issue by olav35** [dylanaraps/neofetch#1207]
## Description
Hello. I have neofetch display album cover of currently playing song or if im not playing a song my wallpaper. These images changes pretty often and since when image_loop="on" is set neofetch doesnt return to shell instantly i see no reason not to have them be updated while running.

The battery percentage, currently playing song, memory, uptime, packages, cpu usage and disc usage are among others values which change frequently.

I think neofetch could become even more usefull if it was possible to update the values in real time. I can imagine using it with some sort of screensaver to dispay information such as the current time or weather.

**Comment by Kraust** [comment]
You can modify neofetch to do this pretty easily.
Just open neofetch and replace
{code}
    while [[ "$image_loop" == "on" && "$image_backend" == "w3m" ]]; do display_image; sleep 1; done
{code}
with
{code}
    while [[ "$image_loop" == "on" && "$image_backend" == "w3m" ]]; do printf "\033[0;0f"; print_info; display_image; sleep 1; done
{code}

This won't work well with all terminals, and you have to use w3m. I've been using terminology with this.

**Comment by dylanaraps** [comment]
I have no interest in this feature an it'll require major code changes. No one else seems to want to work on this either.
