### ISSUE TITLE
Enhance the user line to better deal with popular hosts

### ISSUE THREAD

**Issue by jmccorm** [dylanaraps/neofetch#1208]
The users section could use some mild enhancement. On more popular servers, there isn't enough space to see the names of everyone who is logged in. See attached image. Who all is logged in? How many users total? I don't know.

I'll leave the solution to you (if any) but I'd like to offer two suggestions:

1) Half of an 80 column display just isn't enough to display more than just a few users. What I'd like is some sort of way to tell it to limit the output to _X_ rows and _Y_ columns. Or something. You guys are certain to have your own view on how this kind of thing should be integrated.

2) The user list can (should) exclude my own userid. Getting rid of my own userid creates a tiny bit more room, and really, listing my own username really wasn't that helpful in the first place. Hopefully, removing the current user's name would be an easy code change: `users="$(who | grep -v ${user} | awk....`

![neofetch](https://user-images.githubusercontent.com/18018091/53701176-09dcef00-3dc0-11e9-8ee0-2bcc3f808a93.png)

Thank you for listening, and thank you for maintaining this _boss_ tool.

**Comment by dylanaraps** [comment]
This isn't something I'm going to enhance as it is a tiny wrapper around the `who` command. You are able to customize the Neofetch output through your config file using `prin subtitle output` with the full power of the shell and utilities.

The feature was not intented as a full fledged user list!

Thanks for opening this issue.
