### ISSUE TITLE
Arch linux crashed when using neofetch

### ISSUE THREAD

**Issue by Xileon310** [dylanaraps/neofetch#1214]
I have installed neofetch, when i try to open it writting neofetch on terminal, arch linux crashes. 

What could be happen?

Pd: i reinstalled neofetch but it didn"t work

**Comment by dylanaraps** [comment]
Can you send me a verbose log?

```sh
neofetch -vv 2> ~/neofetch.log
```

Also, does neofetch crash arch with: `neofech --config off`?

**Comment by Xileon310** [comment]
I have noticed that neofetch only crashes my arch linux if battery adapter is unpluged

**Comment by dylanaraps** [comment]
Can you upload the `neofetch.log` file?

**Comment by Xileon310** [comment]
Where is it?

**Comment by dylanaraps** [comment]
In the directory you were in when you ran `neofetch`.

**Comment by Xileon310** [comment]
The problem was nouveau driver. I installed bumblebee and neofetch works perfectly.
Thanks for all and sorry for the confusion.
