### ISSUE TITLE
Linux Mint 19.1, cannot use custom photo OR distro logo ascii

### ISSUE THREAD

**Issue by gwennshinguji** [dylanaraps/neofetch#1215]
## Description
When doing `neofetch --w3m --source ~Pictures/[username]/[photo].png`, all that is displayed is my default distro information rather than the image I have selected.

On top of that, when I do `neofetch --distro mac/mint/windows/etc` I still get my default distro

I've done fresh reinstall on top of fresh reinstall, fiddled with the config a few times, and still haven't been able to get an image OR custom ascii art to work.

#### Neofetch version
Latest
## Config file
https://pastebin.com/7WdHS9mM
## Verbose log
https://i.imgur.com/DFHQlzX.png nothing appears except a bunch of empty space when running `neofetch -vv 2> neofetchlog`

**Comment by gwennshinguji** [comment]
Nevermind, editing the config works, but I can't do the commands.

**Comment by ltgouvea** [comment]
@gwennshinguji could you paste your updated config, please? I'm experiencing the same issue on LM 19.1 as well.

**Comment by gwennshinguji** [comment]
config: https://pastebin.com/dMTB6RCC

linux_alt is the ascii art, the ascii art must be located at /usr/share/neofetch/ascii/distro and the file needs to be created as sudo or root (i used vim).

if you would like the ascii art i am using, here you go: https://pastebin.com/W4Pj0JpE
