### ISSUE TITLE
IOS uptime and memory issue

### ISSUE THREAD

**Issue by iraizo** [dylanaraps/neofetch#1217]
## Description

The memory and uptime won’t show up on iOS 12.1.1b3

#### Neofetch version
6.0.1

## Screenshot
https://gnu.cat/oqi.png

## Config file
Default
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or 

Uuuh
![uuuh](https://gnu.cat/wfa.png)

**Comment by dylanaraps** [comment]
I need a verbose log (*see the instructions in your post*).

**Comment by iraizo** [comment]
Where is the log located I don’t find it

**Comment by dylanaraps** [comment]
`neofetch -vv 2> neofetchlog` will write the log to `neofetchlog`. Upload the contents of that file.

**Comment by iraizo** [comment]
and where is that neofetchlog because its not in the neofetch folder

**Comment by konimex** [comment]
...the folder where you execute neofetch?
e.g. `[konimex@apple /tmp]$ neofetch -vv 2> neofetchlog` will generate a log in `/tmp`.

**Comment by iraizo** [comment]
https://pastebin.com/cUXixBqM

**Comment by dylanaraps** [comment]
Outputs of `cat /proc/meminfo` and `cat /proc/uptime`?

**Comment by iraizo** [comment]
https://gnu.cat/xhe.png

**Comment by dylanaraps** [comment]
@iandrewt Are you able to take a look at this? It's macOS territory :P

**Comment by jkhsjdhjs** [comment]
My PR fixes this issue: #1216

**Comment by jkhsjdhjs** [comment]
#1216 has been merged, this can probably be closed.
