### ISSUE TITLE
ITerm Mac OS X ZSH image not loading or has trouble text goes over image 

### ISSUE THREAD

**Issue by vsedov** [dylanaraps/neofetch#1221]
## Description

I use Mac OS X Mojave, with ZSH Shell running with Chunkwm , so sometimes, which is the issue , is that neofetch, won't load the image at all and give a stupid error which I dont understand, the way I kept testing this was opening new windows of iterm seeing what would happen, some loaded with the apple logo which I dont want and others with the image, the ones that did load with the image also had a few issues, say If I opened another window right next to it, sometimes the image would disappear or the text would go over it . 

#### Neofetch version

Neofetch 6.0.0

## Screenshot

![Screenshot 2019-03-17 at 12 04 15](https://user-images.githubusercontent.com/28804392/54492048-1e8aae00-48bb-11e9-86e7-a5458801e886.jpg)
![Screenshot 2019-03-17 at 12 01 06](https://user-images.githubusercontent.com/28804392/54492049-1e8aae00-48bb-11e9-8315-77dfae0ce342.jpg)

![Screenshot 2019-03-17 at 13 51 10](https://user-images.githubusercontent.com/28804392/54492133-bab4b500-48bb-11e9-8cc3-d41185c71b30.jpg)

-- in this image the shell loaded on the right was when I started iterm, it loads with the apple logo which I dont want then : 

![Screenshot 2019-03-17 at 13 52 05](https://user-images.githubusercontent.com/28804392/54492151-dae47400-48bb-11e9-93b1-965470661a30.jpg)

there is this issue where sometimes the image would load but when another window is open, the text override it and the image shouldn't be that large, could it be something to do with the image or have I done something wrong ? 

if further information is required do let me know, thanks 

## Config file
https://pastebin.com/VrzUDkRg

## Verbose log
https://pastebin.com/0P5AuLaW

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by phlind** [comment]
I have a similar configuration, macOS 10.14.4, iTerm2 and zsh, and I configured neofesch to show an ascii "image" (image backend ascii), but it just shows the standard Apple logo. Maybe the problem is related.

**Comment by rodrigocmn** [comment]
same problem here... macOS 10.14.4, iTerm2 and zsh... no image... just apple logo.

**Comment by dylanaraps** [comment]
Can you reproduce this issue on `master`?

**Comment by rcreasey** [comment]
Yes, it's still present as of `e235ae9238cfd81747e34878f67abc76d54c5249`.
![Screen Shot 2019-11-11 at 1 23 08 PM](https://user-images.githubusercontent.com/18412/68622213-7ac3c300-0486-11ea-9056-80860defcabf.png)
[log.txt](https://github.com/dylanaraps/neofetch/files/3833293/log.txt)

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/neofetch/issues/1392
