### ISSUE TITLE
Can you add Serbian debian distro support?

### ISSUE THREAD

**Issue by gorstak-7** [dylanaraps/neofetch#1227]
Id love to see Serbian debian distro logo in neofetch output, instead of tux. Thanks!

**Comment by vitalkanev** [comment]
I don't understand.
Can you explain what is *Serbian* Debian distribution? Link? `cat /etc/os-release` output? Also for `uname -a` and `lsb_release -a`?

**Comment by vitalkanev** [comment]
Hi there! I am writing this because this issue is quite a bit old. Any updates? Or notes? Maybe explain a bit? Thanks.

**Comment by knuxify** [comment]
Quick Google search results in this: https://wiki.debian.org/Derivatives/Census/SerbianLinux

So, somebody would just need to make an ASCII version of the logo and add it to neofetch.

**Comment by gorstak-7** [comment]
Sorry for late late response...

`$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

`$ uname -a
Linux t1500 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
`

`
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
`

[serbian.txt](https://github.com/dylanaraps/neofetch/files/3775724/serbian.txt)

**Comment by dylanaraps** [comment]
This distribution identifies itself as Debian so Neofetch is working correctly here. For support to be added this distribution will need to identify itself correctly.
