### ISSUE TITLE
still show only adwaita

### ISSUE THREAD

**Issue by blazessdd** [dylanaraps/neofetch#1229]
cant manage to show the correct theme  :(

ps: i don t know how to embed pastebin

[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/3043614/neofetchlog.txt)

**Comment by konimex** [comment]
What's your theme? And any screenshots?

**Comment by charlydelta** [comment]
Not OP, but I have the same issue. here's the output of neofetch:

```
 user@pc:~$  neofetch
       _,met$$$$$gg.          user@pc 
    ,g$$$$$$$$$$$$$$$P.       ------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux buster/sid x86_64 
 ,$$P'              `$$$.     Kernel: 4.19.0-4-amd64 
',$$P       ,ggs.     `$$b:   Uptime: 1 day, 2 hours, 25 minutes 
`d$$'     ,$P"'   .    $$$    Packages: 3498 (dpkg) 
 $$P      d$'     ,    $$P    Shell: zsh 5.7.1 
 $$:      $$.   -    ,d$$'    Resolution: 1920x1080, 1920x1080 
 $$;      Y$b._   _,d$P'      DE: GNOME 3.30.2 
 Y$$.    `.`"Y$$$$P"'         WM: GNOME Shell 
 `$$b      "-.__              WM Theme: Adwaita 
  `Y$$                        Theme: Materia [GTK2/3] 
   `Y$$.                      Icons: Papirus [GTK2/3] 
     `$$b.                    Terminal: gnome-terminal 
       `Y$$b.                 CPU: Intel i7-3770K (8) @ 3.500GHz 
          `"Y$b._             GPU: NVIDIA GeForce GTX 680 
              `"""            GPU: Intel HD Graphics 
                              Memory: 4133MiB / 7873MiB 
```

The actual gnome-shell theme I use is Materia as well (installed from Debian Stretch repo. Neofetch was installed from the repo as well).

**Comment by dylanaraps** [comment]
Output of `neofetch --version`?

**Comment by blazessdd** [comment]
sorry for the absence and thanks for you time
![Screenshot from 2019-05-09 15-41-10](https://user-images.githubusercontent.com/45053339/57458038-f3945900-7270-11e9-9500-96e1196acea5.png)
need anything else? im running on arch fully upgraded gnome 3.32

**Comment by dylanaraps** [comment]
This is an issue with your system and not Neofetch. `gsettings` is reporting the theme as Adwaita.
