### ISSUE TITLE
Feature Request: Recognize BunsenLabs Openbox DE

### ISSUE THREAD

**Issue by hhhorb** [dylanaraps/neofetch#1232]
## Description

Currently neofetch detects the BunsenLabs DE as Xfce. While it's true that BL uses xfce4-power-manager, xfce4-notifyd and xfconfd in it's OOTB experience, it is not an Xfce4 desktop, there is no settings-manager or xfdesktop4 session running.

It would be preferable if neofetch could display "DE: None" or "DE: BunsenLabs Openbox" as the DE.

Thanks for your great work, and for considering this feature.

:D

#### Neofetch version

```roy@TyrellCorp:~$ apt-cache policy neofetch
neofetch:
  Installed: 6.0.0-2
  Candidate: 6.0.0-2
  Version table:
 *** 6.0.0-2 500
        500 https://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

## Screenshot

https://cdn.scrot.moe/images/2019/04/14/Screenshot_2019-04-14_14-30-15.png

## Config file

default
## Verbose log

https://pastebin.com/j7R3CHhA

**Comment by konimex** [comment]
What's the output of `$XDG_CURRENT_DESKTOP`? Maybe one of `xfce4-power-manager`, `xfce4-notifyd` and `xfconfd` changed it to Xfce causing neofetch to detect it.

**Comment by hhhorb** [comment]
Sorry for the delayed response...

```roy@TyrellCorp:~$ $XDG_CURRENT_DESKTOP
bash: XFCE: command not found
```

However, the is no Xfce.desktop file in /usr/share/applications, but there is an Openbox one.

And since my awesome wm session is properly detected and displayed by neofetch, and I'm running xfce4-power-manager and therefore also xconfd there, I gues the culprit is xfce4-notifyd, but that seems pretty weird.

Any more info I can give, please let me know. Thanks for looking into this!

**Comment by hhhorb** [comment]
Oh, for the awesome session...

```roy@TyrellCorp:~$ $XDG_CURRENT_DESKTOP
roy@TyrellCorp:~$
```

**Comment by dylanaraps** [comment]
This isn't a neofetch issue as `$XDG_CURRENT_DESKTOP` reports `XFCE`. "Working as intended".

**Comment by hhhorb** [comment]
Thanks for your responses here, it's solved the issue. BL sets the environment to XFCE in ~/.config/openbox/environment to solve some xdg-open issues, I had forgotten all about it. I can override it there if needed for a prettier screenshot. :p

Cheers.
