### ISSUE TITLE
How can I install it on openSUSE leap 15.0?

### ISSUE THREAD

**Issue by mbarra320** [dylanaraps/neofetch#1234]
This. I have openSUSE leap 15.0 but neofetch is not in repositories. I could install it adding Tumbleweed repositories but my system will be eventually more insecure. Any idea?

**Comment by Quads9** [comment]
I switched from Leap 15 to Tumbleweed but I'm guessing you can download the script from github and manually add it to your $PATH.

Try:
```
git clone https://github.com/dylanaraps/neofetch.git

cd neofetch
```

and then either:

```
sudo mv neofetch /usr/bin/
```
or link it
```
sudo ln -s /path/to/neofetch /usr/bin/neofetch
```

**Comment by konimex** [comment]
`zypper in neofetch` should suffice.
