### ISSUE TITLE
Font recognition wrong on Konsole

### ISSUE THREAD

**Issue by rapsaGnauJ** [dylanaraps/neofetch#1235]
## Description

The program shows athe font in the first profile it finds (alphabetically) and shows it's font regardless wether that profile is the one in use or not. For example, if you have a profile called "Comic Sans" with font Comic Sans MS and the one in use is "Default" with font Fira Code, neofetch will show terminal font as Comic Sans MS despite Fira Code being the font in use.

#### Neofetch version

6.0.0

## Screenshot

![Screenshot_20190420_193935](https://user-images.githubusercontent.com/24842781/56460513-42527f80-63a4-11e9-8ad2-2609e7a4ee5a.png)
![Screenshot_20190420_194010](https://user-images.githubusercontent.com/24842781/56460514-42527f80-63a4-11e9-91ef-07a452d2753d.png)

## Config file

Default configuration, unchanged.

## Verbose log

[neofetch.log](https://github.com/dylanaraps/neofetch/files/3100440/neofetch.log)

**Comment by arisinfenix** [comment]
```
+ read -d '' -ra konsole_sessions
++ qdbus ' org.kde.konsole-6779'
++ grep -F /Sessions/
Service ' org.kde.konsole-6779' is not a valid name
```
Looks similar to #1186

Can you try the latest version from git master?
Should be fixed with https://github.com/dylanaraps/neofetch/commit/95fb38e73fd974d3a89ec38762407ade7d26e4e2. (hopefully)

**Comment by rapsaGnauJ** [comment]
Works fine on master branch. Sorry for the inconvenient.

**Comment by konimex** [comment]
Closing since #1187 fixes this.
