### ISSUE TITLE
Neofetch doesn't pipe into lolcat correctly on Ubuntu

### ISSUE THREAD

**Issue by Glitchifox** [dylanaraps/neofetch#1237]
## Description

Piping neofetch into lolcat does not work correctly in Ubuntu 18.04

#### Neofetch version
3.4.0-1
## Screenshot
https://media.discordapp.net/attachments/440356095609929728/570394364027731988/unknown.png?width=465&height=683

**Comment by konimex** [comment]
Please update to the latest version as we already supported it.

**Comment by Glitchifox** [comment]
This IS the latest version of neofetch

**Comment by konimex** [comment]
The latest version of `neofetch` is [6.0.0](https://github.com/dylanaraps/neofetch/releases/tag/6.0.0). Please try it.
