### ISSUE TITLE
Piping neofetch into lolcat causes appearance issues

### ISSUE THREAD

**Issue by Glitchifox** [dylanaraps/neofetch#1238]
## Description

Piping neofetch into lolcat causes errors in appearance on Ubuntu 19.04

#### Neofetch version
6.0.0
## Screenshot
https://media.discordapp.net/attachments/184802320565927936/570448012992577536/unknown.png?width=317&height=468

**Comment by knuxfanwin8** [comment]
[Works fine for me.](https://imgur.com/a/QtRh8As)\
Perhaps it's an issue with ``lolcat``. Which version do you have?\
Also, you can use ``neofetch --stdout | logcat`` which does not have escape codes (I think).

**Comment by Glitchifox** [comment]
I fixed the issue, apparently even in 19.04 the lolcat version in the repos is out of date.
