### ISSUE TITLE
--ascii-color might not work

### ISSUE THREAD

**Issue by slaw0** [dylanaraps/neofetch#124]
I use it like this: `neofetch --ascii_distro arch --ascii_color 6`
I want the logo to be cyan as the original dark blue part doesnt look very good on the black background. From what I experimented the `--ascii_color` doesnt have any effect even if I use `neofetch --ascii_color 6`

**Comment by dylanaraps** [comment]
The correct flag is `--ascii_colors 1 2 3 4 5 6`.

I 've just forgotten to update the docs, thanks for reminding me.

**Comment by dylanaraps** [comment]
Fixed in master.

**Comment by slaw0** [comment]
Certanly, I could have noticed this in the config. `neofetch --ascii_colors 14 14` works, but if I set it int the config `--ascii_colors 14 14` it doesnt. Also tried setting it as the text color is being set: `--ascii_colors=( 14 14 )` but that doesnt work either.

**Comment by dylanaraps** [comment]
I just tested it and it works fine for me. `ascii_colors=(1 2 3 4)`

- Where is the config file you're editing?
- Can you upload your config file?

**Comment by slaw0** [comment]
I found the problem, instead of `ascii_colors` the config file had `--ascii_colors`. I commented out the default `ascii_colors=(distro)` and uncommented the line above in the config file so I missed this detail. Thanks for the help.
