### ISSUE TITLE
Subtle improvement for Void (distro) logo

### ISSUE THREAD

**Issue by DarthWound** [dylanaraps/neofetch#1244]
Hello, thank you for neofetch :)

IMO, replacing the `L` at top right of "VOID" with a dot makes a more readable shape for the "D".

![neofetch-void](https://user-images.githubusercontent.com/1771322/56970777-33b85500-6b68-11e9-862a-8eda3651bc16.png)

**Comment by dylanaraps** [comment]
Done!
