### ISSUE TITLE
plasma-browser-integration player support

### ISSUE THREAD

**Issue by RaitaroH** [dylanaraps/neofetch#1246]
## Description

Simply enough, add the lines needed for plasma-browser-integration as a player. Example:

```
get_song() {
    players=(
    ...
        "plasma-browser-integration"
```
```
    case "${player/*\/}" in
    ...
        "plasma-browser-integration"*) get_song_dbus "plasma-browser-integration" ;;
```
Now this works fine if given `--music_player` option, but is not doing it automatically so I must miss something 😛 

The one little problem is: the cover art.
```
▶ qdbus org.mpris.MediaPlayer2.plasma-browser-integration /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | awk -F':' '/artUrl/ {print $4}' | cut -c 3-
i1.ytimg.com/vi/rUVWLhkpAKk/mqdefault.jpg
```
The way I deal with this is by downloading it with wget. So I suppose instead of `/tmp` you could put it in the cache folder for neofetch instead.
```
cover=$(qdbus org.mpris.MediaPlayer2.$player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | awk -F':' '/artUrl/ {print $4}' | cut -c 3-)
   if [[ $player == "plasma-browser-integration" ]]; then
       wget $cover -O /tmp/cover.jpg > /dev/null 2>&1
       cover="/tmp/cover.jpg"
  fi
```

**Comment by RaitaroH** [comment]
Example usage:

```
▶ cover_art
▶ neofetch --music_player plasma-browser-integration --source $cover
```
![image](https://user-images.githubusercontent.com/19552720/57010472-88f67400-6c05-11e9-8b06-d8b4344a8811.png)

**Comment by dylanaraps** [comment]
Added support for getting song information here: https://github.com/dylanaraps/neofetch/commit/ad16b5925c7eae850d8324417a9a6e1d873f8b35

Automatic detection won't work unless there's some method of knowing when `plasma-browser-integration` is in use. Detection currently works through checking the list of running processes.

**Comment by RaitaroH** [comment]
Well the way I deal with what is playing is this:
```
#!/usr/bin/env bash
check() {
    for player in audacious plasma-browser-integration vlc; do
        state=$(qdbus org.mpris.MediaPlayer2.$player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus 2> /dev/null)
        if [[ $state == *$1* ]];then
            i=0
            qdbus org.mpris.MediaPlayer2.$player /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
            break
        else
            i=$((i+1))
        fi
    done
}

i=0
check Playing
[ $i != 0 ] && check Paused
```

So for example:
```
▶ qdbus org.mpris.MediaPlayer2.plasma-browser-integration /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlaybackStatus
Service 'org.mpris.MediaPlayer2.plasma-browser-integration' does not exist.
```
But if it is running then it will give either "Playing" or "Paused".

Now this would mean a special rule just for plasma-browser-integration I suppose.

**Comment by dylanaraps** [comment]
Closing this as I see no further resolution. Album art as Neofetch source is something that should be handled outside of Neofetch for obvious reasons.
