### ISSUE TITLE
Support to GuixSD

### ISSUE THREAD

**Issue by adamantinum** [dylanaraps/neofetch#1247]
Hi,
I ask you for add GuixSD support, now that version 1.0 was released, so I can post screenshots on reddit! :)
Thanks!

**Comment by konimex** [comment]
We already supported GuixSD. The [ASCII](https://github.com/dylanaraps/neofetch/blob/6.0.0/neofetch#L6282) and package manager are there.

**Comment by adamantinum** [comment]
Thanks! Ok, the problem is that Guix doesn't have uname...
