### ISSUE TITLE
Wayland cant show image

### ISSUE THREAD

**Issue by denzveloper** [dylanaraps/neofetch#1249]
## Description
I try neofetch on Plasma(Wayland) with Xfce-terminal. then terminal doesnt show image. and i try second time with Konsole and only shown ascii distro logo.

## Screenshot
Wayland+Xfceterminal: https://ufile.io/085liumx
Wayland+Konsole: https://ufile.io/ljjxzir5
Xorg: https://ufile.io/5oluibvr
## Config file
https://pastebin.com/91nsCRhm
## Verbose log
https://pastebin.com/AqWP620z

**Comment by dylanaraps** [comment]
Neofetch is failing to find the current terminal window's size.

```sh
+ to_ascii 'Image: Failed to find terminal window size.'
+ err 'Image: Failed to find terminal window size.'
```

Is there a method on Wayland to get window size?

**Comment by denzveloper** [comment]
I dont know to get Wayland window size.

**Comment by dylanaraps** [comment]
See: https://github.com/dylanaraps/neofetch/issues/1392

**Comment by madjoe** [comment]
You should install the following packages in order to make it work (restart your terminal before you try it):

```
pacman -S xorg-xwininfo xorg-xdpyinfo xdotool
```
