### ISSUE TITLE
Expected release of 1.4?

### ISSUE THREAD

**Issue by iandrewt** [dylanaraps/neofetch#125]
I'm making the Homebrew formula for Neofetch, but the renaming of Fetch to Neofetch is going to break things when it's released. Because of this, I'm going to hold off on publishing it until 1.4 is released. Is there an expected timeframe for this?

**Comment by dylanaraps** [comment]
Expect 1.4 over the next few days, I still have a few things to complete. The blockers are:

- Alpine Linux support
- Polishing the progress bars PR

**Comment by dylanaraps** [comment]
IIRC, you can still clone using the old name (`github.com/dylanaraps/fetch`) so we might not have an issue after all.

**Comment by iandrewt** [comment]
Okay awesome, and the old name won't help as it'll result in an abandoned formula when 1.4 is released. Homebrew uses tags (the tarballs) as its primary method of downloading and installing, and requires it. The --HEAD option (git clone) is optional and would actually make it more complicated (currently, it'll be easy when 1.4 is out)

I've currently got the formula named as neofetch, and it downloads and installs as fetch, so if i published that and later updated it to 1.4, 1.3 would remain with its symlink and script (which it shouldn't) and 1.4 would be installed with the proper name.

**Comment by dylanaraps** [comment]
Awesome!

Are you able to write up some homebrew install instructions for the Readme? I want to include the homebrew stuff in the changelog for 1.4 so that it doesn't get pushed back to 1.5.

**Comment by iandrewt** [comment]
Sure. It won't be available to install from homebrew for about (probably less than) 24 hours after the release of 1.4 though because of the auditing and approval system.

**Comment by dylanaraps** [comment]
1.4 has been released.
