### ISSUE TITLE
Failing to read gtk2 theme

### ISSUE THREAD

**Issue by Al2Me6** [dylanaraps/neofetch#1250]
## Description

I have Adapta and Papirus installed and enabled for both gtk2 and 3. However, only gtk3 is reported correctly. From a cursory look it seems like Neofetch is failing to properly read the contents of my [`.gtkrc-2.0`](https://pastebin.com/ke0xgBgq).

#### Neofetch version

`6.0.0`

## Screenshot

![image](https://user-images.githubusercontent.com/35266431/57204423-c18baa00-6f85-11e9-8cc8-0eefcfd78ef0.png)

## Config file

Default config was used.

## Verbose log

Log: https://pastebin.com/AkbCjVMY

**Comment by dylanaraps** [comment]
This was fixed in master. Try these steps:

```sh
git clone https://github.com/dylanaraps/neofetch --depth 1
cd neofetch
./neofetch
```

**Comment by Al2Me6** [comment]
Thank you, confirmed fixed.
