### ISSUE TITLE
Incorrect terminal font detection in URxvt

### ISSUE THREAD

**Issue by vaygr** [dylanaraps/neofetch#1253]
## Description

It seems neofetch doesn't handle some specific case, which I have.

I have a plugin for URxvt configured. It allows to change font size on the fly.

Configuration is as simple as this line in `~/.Xdefaults`:

```
URxvt.perl-ext-common:  font-size
```

The plugin handles X resources later on its own. For more info see https://github.com/majutsushi/urxvt-font-size

#### Neofetch version

**6.0.0**

## Screenshot

N/A

## Config file

N/A

## Verbose log

The relevant debug part:

```shell
++ grep -im 1 -e '^urxvt\**\.*font' -e '^\*font'
+ term_font='URxvt.font-size.step:	2'
+ term_font='URxvt.font-size.step:	2'
+ term_font='URxvt.font-size.step:	2'
+ term_font='URxvt.font-size.step:	2'
++ trim 'URxvt.font-size.step:	2'
++ set -f
++ set -- URxvt.font-size.step: 2
++ printf '%s\n' 'URxvt.font-size.step: 2'
++ set +f
+ term_font='URxvt.font-size.step: 2'
+ [[ -z URxvt.font-size.step: 2 ]]
++ trim 'URxvt.font-size.step: 2'
```

**Comment by dylanaraps** [comment]
Can I see the entire output of `xrdb -query`?

**Comment by vaygr** [comment]
Oh, absolutely: https://bpaste.net/show/272c8dacf545

**Comment by vaygr** [comment]
I think I know what the fix could be:

```diff
index ae32366..f42e539 100755
--- a/neofetch
+++ b/neofetch
@@ -3071,7 +3071,7 @@ END
 
         "urxvt" | "urxvtd" | "rxvt-unicode" | "xterm")
             xrdb="$(xrdb -query)"
-            term_font="$(grep -im 1 -e "^${term/d}"'\**\.*font' -e '^\*font' <<< "$xrdb")"
+            term_font="$(grep -im 1 -e "^${term/d}"'\**\.*font:' -e '^\*font:' -e '^*.font:' <<< "$xrdb")"
             term_font="${term_font/*"*font:"}"
             term_font="${term_font/*".font:"}"
             term_font="${term_font/*"*.font:"}"
```

The thing is that I have global font specification (`*.font: <font>`), but at the same time we should filter out resources like `URxvt.font-size.step:`, so only `*font:`, ending with a colon, would be taken into account.
