### ISSUE TITLE
i3 displayed as DE instead of WM and wrong WM

### ISSUE THREAD

**Issue by avalonv** [dylanaraps/neofetch#1258]
## Description
Neofetch incorrectly displays the DE as "i3" and the WM as "LG3D". I am using i3wm with no DE.

#### Neofetch version
Neofetch 6.0.0

## Screenshot
![2019-05-25-141211_maim](https://user-images.githubusercontent.com/29720696/58372713-e6759c00-7ef7-11e9-8ad4-9a761a431dbc.png)

## Config file
it's the default, no settings were changed.
https://pastebin.com/ZzjkJu22

## Verbose log
https://pastebin.com/fmDGw70L

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
Your X11 is reporting the `WM_NAME` as `LG3D`.

```
_NET_WM_NAME = "LG3D"
```

I also believe `echo $XDG_CURRENT_DESKTOP` will print `i3`.

Both of these are not `neofetch` issues and are issues with your system.

**Comment by avalonv** [comment]
Apologies. It's odd that I had never heard of LG3D before, the only mention I can find is a now defunct project https://en.wikipedia.org/wiki/Project_Looking_Glass.
