### ISSUE TITLE
Images not displayed Gnome URxvt W3m

### ISSUE THREAD

**Issue by ionguy5665** [dylanaraps/neofetch#1259]
## Description

Images not displayed Gnome URxvt W3m.  ASCII distro logo displayed without issue.  When executing 'neofetch --w3m' URxvt screen clears and goes to Bash prompt, exit code 1.

## Screenshot

![image](https://user-images.githubusercontent.com/51039118/58377003-873e7880-7f45-11e9-8da6-50e34bd4e0a9.png)

#### Neofetch version
6.0.0-1

## Config file
https://pastebin.com/pWX5e04R

## Verbose log

https://pastebin.com/Tqs0mMWv

**Comment by dylanaraps** [comment]
The log file you sent me is incomplete. Are you able to try again?

**Comment by ionguy5665** [comment]
This is all that is logged when executing:
 
$ neofetch --w3m -vv /home/artaucruz/Pictures/us2018.png

https://pastebin.com/gMQB7FZU

**Comment by dylanaraps** [comment]
My apologies. Try the latest git master.

```sh
git clone https://github.com/dylanaraps/neofetch --depth 1
cd neofetch
./neofetch --w3m /home/artaucruz/Pictures/us2018.png
```

**Comment by ionguy5665** [comment]
Thank you!  Issue resolved.  Appreciate your support.
