### ISSUE TITLE
Feature request: colours but not ASCII

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [dylanaraps/neofetch#1260]
## Description

So far as I can tell, there is no option to have coloured text but no ASCII. Such output - colours, no ASCII - would look reasonably nice (by dint of the colours) but additonally would paste well into text editors and webforms.

Thank you for this program.

#### Neofetch version

6.0.0.

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
`neofetch --off` or `neofetch --backend off`.

**Comment by LinuxOnTheDesktop** [comment]
Ah. Nice. Thanks. Any config file option, though?

**Comment by dylanaraps** [comment]
```sh
image_backend="off"
```
