### ISSUE TITLE
Swap partition seems to be incorrectly reported

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [dylanaraps/neofetch#1261]
## Description

My swap partition seems to be incorrectly reported - both in its `/dev` identifier and its size.

#### Neofetch version

6.0.0.
## Screenshot

This first screenshot shows some Neofetch output - see its last line for the problem - together with a list - generated by `blkid` - of filesystems.

![image](https://user-images.githubusercontent.com/47056543/58678903-42597e00-8359-11e9-82e9-c0c9fda321a9.png)

This next screenshot shows information from the `gparted' program.

![image](https://user-images.githubusercontent.com/47056543/58678974-8b113700-8359-11e9-85cb-bd6bde38fe41.png)

Neofetch seems to be reporting some sort of 'udev' file system:

![image](https://user-images.githubusercontent.com/47056543/58679144-2efae280-835a-11e9-9f42-e63c73b7a734.png)

## Config file

Relevant parts:

```
# disk_show=('/')
disk_show=('/' '/dev/nvme0n1p2' '/dev/nvme0n1p3')
```

```
# disk_subtitle="mount"
disk_subtitle="name"
```

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
https://pastebin.com/057CbRY9

**Comment by konimex** [comment]
Apologies for the late response, but can you proivde the full output of `df -P -h`?

**Comment by LinuxOnTheDesktop** [comment]
Here you are. Thanks.

```
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G   12M  1.6G   1% /run
/dev/nvme0n1p4   40G   14G   24G  37% /
tmpfs           7.8G  4.0K  7.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/loop0       23M   23M     0 100% /snap/fwupd/880
/dev/loop1       23M   23M     0 100% /snap/fwupd/816
/dev/loop2       89M   89M     0 100% /snap/core/7270
/dev/nvme0n1p1  523M   16M  508M   4% /boot/efi
/dev/nvme0n1p2  405G  164G  221G  43% /home
Firefox         301M   79M  223M  26% /ramdisk
tmpfs           1.6G  5.5M  1.6G   1% /tmp
tmpfs           5.0M   12K  5.0M   1% /mnt/ramdisk
tmpfs           1.6G   48K  1.6G   1% /run/user/1000
```

**Comment by konimex** [comment]
So, `df` can't detect swap.

I'll see what I can do.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Perhaps you could look at the Gnome and/or KDE system monitors to see how they detect swap.

**Comment by dylanaraps** [comment]
Seeing as `get_disk` functions by using `df` and `df` doesn't support swap, there's nothing we can do here.
