### ISSUE TITLE
Terminal: wrong output under tmux

### ISSUE THREAD

**Issue by Walther** [dylanaraps/neofetch#1266]
## Description

On macOS, if both Alacritty and iTerm2 are installed, and you run `tmux` in your Alacritty window, `neofetch` will report Terminal as being iTerm2.

#### Neofetch version

`[!] Neofetch version: 6.0.0`

## Screenshot

<img width="962" alt="Screen Shot 2019-06-12 at 23 50 37" src="https://user-images.githubusercontent.com/2943750/59410155-ed603380-8d6c-11e9-82ec-b862aee6c684.png">

**Comment by dylanaraps** [comment]
Output of `echo $TERM_PROGRAM` in each window.

**Comment by dylanaraps** [comment]
A verbose log (as required for issues) would be helpful too.

**Comment by Walther** [comment]
Empty in plain alacritty, `iTerm.app` in tmux. Odd 🤔 tmux.conf doesn't contain anything that would refer to iTerm.

Logs for both:

https://gist.github.com/Walther/a63455aefab6d04f8593be5842fa2602

**Comment by dylanaraps** [comment]
I don't think this is a Neofetch issue then. For some reason your system is setting the environment variable to an incorrect value.

**Comment by dylanaraps** [comment]
Possibly related: https://github.com/jwilm/alacritty/issues/781

**Comment by dylanaraps** [comment]
This could be an issue with your ZSH configuration. Have you tried disabling your ZSH config?

**Comment by Walther** [comment]
Ahh, figured it out - sorry, my bad! I had another tmux session running from a previous iTerm, launching `tmux` from Alacritty ended up just adding & drawing a new window - and in that session, the `$TERM_PROGRAM` env var had been populated by iTerm.

Classic PEBKAC, sorry!
