### ISSUE TITLE
GUIXSD is reported as the distribution if GUIX is installed.

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#1267]
The `guix` package manager can be installed on any distribution. Installing it outside of GUIXSD causes `neofetch` to incorrectly detect the distribution as GUIXSD.

**Comment by dylanaraps** [comment]
Problem code:

```sh
            elif type -p guix >/dev/null; then
                case "$distro_shorthand" in
                    "on" | "tiny") distro="GuixSD" ;;
                    *) distro="GuixSD $(guix system -V | awk 'NR==1{printf $5}')"
                esac
```

**Comment by konimex** [comment]
#1265 solves this, but I suggested to move the whole if block below the `/etc/os-release` instead of an additional `/etc/os-release` check so I don't merge it yet.
