### ISSUE TITLE
Dylan Araps should apologize for his hit piece on screenfetch.

### ISSUE THREAD

**Issue by kori** [dylanaraps/neofetch#1273]
## Description
Dylan Araps wrote a hit piece on screenfetch a few years ago, and as far as I know, still hasn't apologized for it.

https://github.com/dylanaraps/neofetch/wiki/Neofetch-vs-Screenfetch/a9c174beecfa9a4e547a9dfd7fac0491e35de84b

It is not a technical issue, however, it is a thing that prevents me, personally, from ever considering using Neofetch.

Screenfetch was written across many years, and it is obvious it would pile up on issues over time. The quality of the script is not the question here. Neofetch is unquestionably implemented cleaner, on a technical level.

The issue is how many people definitely were influenced by this hit piece to absolutely shit on screenfetch, **for no reason whatsoever.**

If this issue is addressed, I think it would be a great sign of maturity on the author's part.

### Parts of the hit piece that served as motivation for me to open this issue:
Especially offending parts were highlighted.
#### Nitpicking
>Compare the latest master of Neofetch to the latest master of Screenfetch and you'll find that Neofetch (in ascii mode) is **3 times faster** than Screenfetch on average. This is all while Neofetch is displaying more system information and your terminal colors.
>Despite Image mode being much slower, Neofetch is still on average **70ms** faster than Screenfetch.

>Screenfetch calls the external program cat when it's totally unnecessary. As of me writing this wiki page there are **10~** unnecessary uses of cat in Screenfetch. They can all easily be avoided by replacing the word cat with < . < is a bash builtin and doesn't spawn external programs.

>Screenfetch constantly mixes POSIX syntax with BASH only syntax for no apparent reason. The whole script is an inconsistent mess; variables/functions are all named differently; printf/echo are mixed and matched throughout and there's even **useless cat usage!**

And last, but not least, the absolute **worst** thing one could write about a predecessor project, that served as inspiration and that paved the way for Neofetch to exist. [1]
> There's nothing Screenfetch does that Neofetch doesn't do better. Neofetch is faster, more customizable, supports more operating systems, displays more info and **isn't a fucking mess on the inside.** 

### The way forward.
My suggestion is that the article is written so that it is a constructive criticism of screenfetch, with the intention of teaching new shell users why these sorts of issues are important to know, and what's important not to do.

The information needed to create such an article was collected in the original post, but it wasn't used for this purpose.

This is a great opportunity, because neofetch and screenfetch do ostensibly the same thing, and it would be a great way to compare how these two projects differ, **constructively**. As an example, this reminds me of this article: http://thume.ca/2019/04/29/comparing-compilers-in-rust-haskell-c-and-python/, where the author compared the same project in multiple languages.

Considering bash is very flexible, and there are visible improvements to the performance, creating a similar article would be an awesome contribution to the community.

Like I said, I don't question the technological improvements of neofetch over screenfetch. I just wish this information was used for a better purpose than to aggrandize neofetch and put down screenfetch.

I hope this is addressed.

[1]: Source: https://github.com/dylanaraps/neofetch/blob/f1d52bd240e4cd6fb886b5da4f1c6096b5310412/README.md#thanks
>Screenfetch: I've used some snippets as a base for a few functions in this script. 

### Nota bene:

I wrote the original title as "Dylan Araps needs to apologize for his hit piece on screenfetch.", and changed it to "Dylan Araps should apologize for his hit piece on screenfetch".

After some thought, I decided this was not the best way to address this problem. I think the section "The way forward" makes a better point.

With that said, I'm going to keep the original title,  because it is the strongest claim I'm going to make about this issue, and it's the part I feel more strongly about.

**Comment by kori** [comment]
Changed the title to be slightly less inflammatory.

**Comment by dylanaraps** [comment]
What you have failed to mention is that I voluntarily removed the page over a year ago with the intent of rewriting it in a seemingly less offensive manner. However, I do still stand by the opinions and words of my much younger self.

Therefore, I see no reason nor obligation to retrospectively apologize for something that no longer exists as a living entity in this WIKI. 

Despite my opinions on Screenfetch, I have and will continue to contribute to it.
