### ISSUE TITLE
Wrong number of snap packages reported

### ISSUE THREAD

**Issue by JacksonMcKay** [dylanaraps/neofetch#1274]
## Description

Neofetch claims my system has 9 snap packages instead of 8. I suspect all package managers with extraneous output (headers, etc.) are affected. I had a look at the source, notably:
https://github.com/dylanaraps/neofetch/blob/175915d0a6a8183cf00030b6e88412cb13284289/neofetch#L1392
where the packages are counted by `tot` and then `((packages-=1))` is done to eliminate the header line. I believe this only decrements the **total** package count, not the package count for individual package managers which seems to be set in `pac()`
https://github.com/dylanaraps/neofetch/blob/175915d0a6a8183cf00030b6e88412cb13284289/neofetch#L1311-L1312
with the fragment `managers+=("$1 (${manager})")`. It's only *after* all this that `((packages-=1))` comes into play.

Apologies, I don't think my bash-fu is up to scratch to fix it myself 😅

Package managers affected: `tazpkg`, `snap`, `port`, `scoop`, `versions`

#### Neofetch version

Neofetch 6.0.0

## Screenshot

Notice how `--package_managers off` seems to list one less package than the default option
![neofetch_snap_bug](https://user-images.githubusercontent.com/16645707/60022773-cc3a0400-96d7-11e9-8e92-f3201080b119.png)

## Config file

N/A

## Verbose log

https://pastebin.com/w5n5JLJg

**Comment by dylanaraps** [comment]
Great catch! 

This will be interesting to solve.

**Comment by A-725-K** [comment]
Good afternoon ! I think I could have a solution for this bug, but since this is my first contribution to an open source project I would appreciate a little help to test some of the package managers that I don't have to be sure that my fix work before making the pull-request :smile:

**Comment by JacksonMcKay** [comment]
Hi! I'd be happy to test your solution with `snap` and `scoop` - could you make a pull request or push your code somewhere where I can get my hands on it?

**Comment by A-725-K** [comment]
> Hi! I'd be happy to test your solution with `snap` and `scoop` - could you make a pull request or push your code somewhere where I can get my hands on it?

First of all thank you for your kind help ! If you want to get the code you can clone my fork and switch the the branch called `packagenum`. I will really appreciate your feedback, especially on _scoop_ since I haven't it on my system and it is the most doubtful change I've made to the code :sweat_smile:

**Comment by A-725-K** [comment]
I was able to test my fix on both GNU/Linux (Parrot OS) and Windows 10 [scoop and snap] and it actually worked! I'll submit soon the pull request. If anybody is able to test the script with other package managers that were affected by the bug I would appreciate much. Thank you all ! 😃

**Comment by JacksonMcKay** [comment]
Hi, sorry for the delay!
I was able to test your fix with `snap` on Manjaro Linux, `scoop` on Windows and `port` on a Mac and all returned the correct number of packages both for individual package managers and with the `--package_managers off` option (meaning there was no regression there).
Looking at your changes it looks like you've covered all bases and I don't see any reason why there would be issues with the other two package managers mentioned - Nice work!

**Comment by A-725-K** [comment]
Thank you so much @JacksonMcKay for your help and feedback, it was fundamental and you were very kind ! I hope this will be merged soon 😄

**Comment by Uniminin** [comment]
similar thing also happens on Bedrock. Neofetch prints the wrong number of portage installed packages (gentoo stratum).

**Comment by A-725-K** [comment]
> similar thing also happens on Bedrock. Neofetch prints the wrong number of portage installed packages (gentoo stratum).

In theory my fix should address also Bedrock. May I ask you to test my solution on gentoo since I'm not able to do it, please? It would be great. Thank you for your cooperation !
