### ISSUE TITLE
Add support for Synology Linux

### ISSUE THREAD

**Issue by vibbix** [dylanaraps/neofetch#1275]
I would like to see support for Synology added.
The output of `uname -a` is:
```
Linux diskstation 3.10.105 #24922 SMP Fri May 10 02:50:17 CST 2019 x86_64 GNU/Linux synology_braswell_916+ ```

**Comment by dylanaraps** [comment]
I'll need more information.

- `cat /etc/os-release`
- `lsb-release` or `lsb_release`.
- Package manager?

**Comment by MelvinGr** [comment]
dpkg is used as a package manager, none of the others are available.

Don't know what the best way of detecting would be

uname -a: Linux HOSTNAME 4.4.59+ #24922 SMP PREEMPT Wed Jul 3 16:38:29 CST 2019 x86_64 GNU/Linux synology_apollolake_918+

/proc/cmdline: syno_hdd_powerup_seq=1 HddHotplug=0 syno_hw_version=DS918+ vender_format_version=2 console=ttyS0,115200n8 withefi quiet syno_hdd_detect=0 root=/dev/md0 sn=xxx mac1=xxx netif_num=1 SataPortMap=4

**Comment by konimex** [comment]
>Don't know what the best way of detecting would be

Either one of these:

- `/etc/os-release`
- `lsb_release` (if available)

**Comment by vibbix** [comment]
```
mark@synology:~$ cat /etc/synoinfo
synoinfo.conf     synoinfo_8G.conf
mark@synology:~$ cat /etc/synoinfo.conf
unique="synology_braswell_916+"
company_title="Synology"
...
```
There is no `lsb_release` or `/etc/os-release`

**Comment by konimex** [comment]
Do you have any download links so we can test it out?

**Comment by vibbix** [comment]
Synology is a commercial offering, I don't believe it's possible to send any ISO download links for it.

**Comment by dylanaraps** [comment]
What does Neofetch currently look like on it?

**Comment by hobbsy** [comment]
would love to see neofetch on Synology NAS boxes
