### ISSUE TITLE
Song info for mpd not being displayed

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/neofetch#1276]
## Description
Song info for mpd doesn't work. 

#### Neofetch version
Neofetch version: 6.0.0

## Config file
[Pastebin](https://pastebin.com/rb4YF1RC)

## Verbose log

[Pastebin](https://pastebin.com/mJFTfPMA)

MPD works fine otherwise. Any help would be appreciated.
Thanks.

**Comment by martin640** [comment]
For those having problem with neofetch showing "Unknown Artist - Unknown Song" when using MPD as music player: neofetch is using mpc to get currently playing song details. Make sure you have it installed.

**Comment by JettScythe** [comment]
@martin640 You sure? 
![image](https://user-images.githubusercontent.com/37233887/186834060-09b9d28c-f190-4cdb-af09-28683cb1b4ab.png)
