### ISSUE TITLE
Incorrect OS in Fedora Silverblue

### ISSUE THREAD

**Issue by FastOSlinux** [dylanaraps/neofetch#1280]
## Description
Incorrect OS in Fedora Silverblue 30

#### Neofetch version
6.0.0-2.fc30

## Screenshot
![Captura de tela de 2019-07-09 14-59-26](https://user-images.githubusercontent.com/17401812/60911715-2dc2ac80-a25a-11e9-92d9-e5d9a2cef0a5.png)

**Comment by konimex** [comment]
Uh... Am I missing something? It is `Fedora 30`.

Also, what's the `lsb_release -irc` and `cat /etc/os-release` output?

**Comment by FastOSlinux** [comment]
> Uh... Am I missing something? It is `Fedora 30`.
> 
> Also, what's the `lsb_release -irc` and `cat /etc/os-release` output?

cat /etc/os-release
NAME=Fedora
VERSION="30.20190701.0 (Workstation Edition)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30.20190701.0 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
OSTREE_VERSION=30.20190701.0

**Comment by konimex** [comment]
Uh... So it is a Fedora 30. I don't see any incorrect OS so I'm closing this.
