### ISSUE TITLE
Add Feren OS to the logos

### ISSUE THREAD

**Issue by feren** [dylanaraps/neofetch#1283]
## Description

Pretty much just, if appropriate, add a Feren OS logo to Neofetch. Don't worry about 'Feren OS Next Beta' (that PRETTY_NAME is only temporary and won't be used for much longer in what's currently 'Feren OS Next'), it'd just be appreciated if the PRETTY_NAMES of these two are supported and show a Feren OS Logo:
- 'Feren OS'
- 'Feren OS Classic'

Otherwise, here's an example os-release file from Feren OS for any other referencing:
```
NAME="Feren OS"
VERSION="2019.07"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Feren OS"
VERSION_ID="18.04"
HOME_URL="https://ferenos.weebly.com/"
SUPPORT_URL="https://ferenos.weebly.com/feren-os-on-social-media.html"
BUG_REPORT_URL="https://gitlab.com/Feren-OS/feren-OS-Bug-Reporting/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D="
PRIVACY_POLICY_URL="https://ferenos.weebly.com/privacy-policy.html"
VERSION_CODENAME=bionic
FEREN_CODENAME=xenon
```

Logo:
If you need the logo for Feren OS, here:
- Logo file (PNG): ![Logo no space](https://user-images.githubusercontent.com/11057934/61322990-cb901b80-a806-11e9-8b08-fd26bd7f1402.png)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by konimex** [comment]
`PRETTY_NAME` should properly detect `Feren OS`, but the ASCII will be Tux.

```
 `----------`                           
 :+ooooooooo+.                          
-o+oooooooooo+-                         
..`/+++++++++++/...`````````````````    
   .++++++++++++++++++++++++++/////-    
    ++++++++++++++++++++++++++++++++//:`
    -++++++++++++++++++++++++++++++/-`  
     ++++++++++++++++++++++++++++:.     
     -++++++++++++++++++++++++/.        
      +++++++++++++++++++++/-`          
      -++++++++++++++++++//-`           
        .:+++++++++++++//////-          
           .:++++++++//////////-        
             `-++++++---:::://///.      
           `.:///+++.            `      
          `.........
```

Is this good enough for the ASCII art? Since I'm horrible in making ASCII art I just used a generator.

**Comment by dylanaraps** [comment]
That looks fine to me, if the distribution has their own ASCII version of the logo it can be changed later.

**Comment by feren** [comment]
That looks good enough to be honest for an ASCII logo. Don't mind if it's all one colour by the way.

**Comment by feren** [comment]
As long as pretty names of `Feren OS` and `Feren OS Classic` result in that logo, I'd be more than happy to see this change occur. 'Feren OS Classic' is going to be used in the future as a PRETTY_NAME once Feren OS becomes Feren OS Classic and Feren OS Next becomes Feren OS.

**Comment by konimex** [comment]
Added in https://github.com/dylanaraps/neofetch/commit/9d4855a18fd4dcbfbb334e50e31626a9d39bf1f3. Thanks for the issue.
