### ISSUE TITLE
Uncommenting lines in `printinfo ()` doesn't change result

### ISSUE THREAD

**Issue by iandrewt** [dylanaraps/neofetch#129]
I tried uncommenting lines such as `# info "Battery" battery` and `# info "Local IP" localip` but upon running `neofetch` the output doesn't include this information.

Running OS X 10.11.3 build 15D21

And no, its not a write permission error :P

**Comment by dylanaraps** [comment]
Are you editing the script or the config file located at `$HOME/.config/neofetch`?

**Comment by iandrewt** [comment]
The script itself, just tried the config file and it worked... Oops

**Comment by dylanaraps** [comment]
You can use the flag `--config none` if you don't want to use the config file.

**Comment by iandrewt** [comment]
Good to know, thanks
