### ISSUE TITLE
Images displayed using pixterm image backend are stretched horizontally

### ISSUE THREAD

**Issue by enveeed** [dylanaraps/neofetch#1292]
## Description

`neofetch` displays images in `--pixterm` mode stretched horizontally.

This issue is probably within the way `neofetch` calls pixterm, cause `pixterm` apparently does not automatically keep aspect ratio unless specified with `-s fit` or the correct `-tc` / `-tr` numbers, so either that mode is not used or the calculation of those numbers are wrong.

#### Neofetch version
`6.0.0`

## Screenshot

![](https://s.put.re/Lje2kLTT.png)

(the [image used](https://s.put.re/JFPaC6Tm.jpg), for reference)

## Config file
(default, nothing changed at all)

## Verbose log

https://s.put.re/stQiZ5Ch.neofetchlog

**Comment by hpjansson** [comment]
Does output look ok with the chafa backend? It's character-based also.

**Comment by enveeed** [comment]
![](https://s.put.re/9CX8QHgG.png)

Also not right, way too small this time and square for some reason.
I thought for a second that it may be a problem in `gnome-terminal` but I tried it out in tilix and it has the exact same problem. :/

**Comment by enveeed** [comment]
I just tried it out with terminus, and for some reason it *works fine* there (both chafa and pixterm).
All the 3 terminals I tested use the same font in the same size (Source Code Pro Semibold), so this can't be the problem.

I'm not sure if this is neofetch related after all, considering that it works in terminus, but not in gnome-terminal or tilix. Do you have any other idea on how I could test this?

**Comment by hpjansson** [comment]
gnome-terminal and tilix both use the VTE terminal widget, so it's likely related to that, or how neofetch deals with it. Do chafa and pixterm display the image fine when not running under neofetch? In that case you're probably right in suspecting an issue with how neofetch fetches/calculates the dimensions.

**Comment by dylanaraps** [comment]
Try the latest `git` master.

```sh
git clone https://github.com/dylanaraps/neofetch --depth 1
cd neofetch
./neofetch --flags go here
```

**Comment by enveeed** [comment]
@hpjansson That could be it. Both chafa and pixterm display images correctly in all 3 terminals when used directly.

@dylanaraps using the latest version from git fixed it for pixterm, but the image is still too small and in the wrong aspect ratio for chafa
![](https://s.put.re/NvkhFjX4.png)

**Comment by dylanaraps** [comment]
This issue is actually new versions of the VTE library reporting incorrect pixel sizes for windows. Not a neofetch issue at all. The current `git` master works around it as best it can.

**Comment by enveeed** [comment]
Ah I see, thanks for figuring that out!

**Comment by hpjansson** [comment]
From your log:

> term_height=696
> term_width=432

> font_width=4
> font_height=29

Term size looks ok... probably. But it looks like neofetch is calculating a strange font size. What's the output from `stty size` and `printf %b '\e[14t'` there?

**Comment by enveeed** [comment]
`stty size`: `24 80`
`printf %b '\e[14t'`: `640;432t`

**Comment by hpjansson** [comment]
The reason Chafa prints a smaller image is that by default, it preserves the aspect of the input image (pre-cropped by neofetch). I filed issue #1295 with a pull request fixing that.
