### ISSUE TITLE
Incorrect package count.

### ISSUE THREAD

**Issue by Phate6660** [dylanaraps/neofetch#1294]
## Description

So, I'm currently on Gentoo. Using Neofetch would give me the correct package count. Then I decided to hijack my Gentoo install with Bedrock as I have been curious about it for a while. However, after doing so, my package count is significantly higher than it's supposed to be. I currently have 720 packages installed, however Neofetch says I have 2880 packages installed.

#### Neofetch version

6.0.0

## Screenshot

![2019-07-29-222434_1366x768_scrot](https://user-images.githubusercontent.com/44369810/62095890-4f1f2300-b271-11e9-8921-68ba7bc990c2.png)

## Config file

https://privatebin.net/?9d17274c908b35be#BwDEviuxxAXpKwnUJk9iLykzSDpSdd7Ggx5KUJGTY3o

## Verbose log

https://privatebin.net/?8a73bfc16c883472#DwMdAtfPx4ekb8CJdxv9iKRX1JHTapa7TwstxzvHa3Ny

**Comment by dylanaraps** [comment]
This isn't a bug as you are running neofetch as "bedrock" and not an individual strata.

**Comment by nezuSTDdos** [comment]
@dylanaraps Someone on Discord just informed me that this problem is also present within seperate stratas. I'll be attaching an image that someone called Elder from the Bedrock discord provided.
![unknown](https://user-images.githubusercontent.com/56595252/87557380-237e8e00-c6b8-11ea-91b2-67a9c127c37a.png)

**Comment by paradigm** [comment]
_For the most part_ it works as expected for me.

Here's a quick and dirty script I wrote to sanity check things:

```
#!/bin/sh

echo "Neofetch reported system emerge package count:"
neofetch | awk -vRS=' ' '
	/(emerge)/ {
		print x;exit
	}
	{
		x=$0
	}
'

echo "Neofetch reported individual strata emerge package counts:"
for s in $(brl list -i); do
	echo "stratum=$s="
	strat -r $s ./neofetch 2>/dev/null
done | awk -vRS=' ' '
	/stratum=/ {
		split($0, a, "=")
		s=a[2]
	}
	/(emerge)/ {
		print s":\t"x
		t+=x
	}
	{
		x=$0
	}
	END {
		print "------"
		print "total:\t"t
	}
' | column -t
```

On my system it outputs:

```
Neofetch reported system emerge package count:
1637
Neofetch reported individual strata emerge package counts:
brl-build-cross-ppc:  226
brl-build-i386:       219
brl-build-i486:       218
brl-build-i586:       221
brl-build-ppc:        220
brl-build-ppc64:      220
gentoo:               313
------
total:                1637
```

which checks out.

-----

One catch: notice the `-i` in `brl list -i` above.

Package managers `neofetch` counts with `tot` only consider enabled/non-hidden strata, while package managers `neofetch` counts with `dir` do _all_ strata, irrelevant of their state.

My guess is the users here reporting an issue have disabled and/or hidden strata which they didn't expect `neofetch` to count.  The fix here will be to redefine `dir` for specifically Bedrock to only consider strata listed by `brl list`, as is already done for `tot`.

I can try to get an MR for this over my next free weekend.  May be a while; I'm swamped.

-----

Not long after Bedrock support for `neofetch` landed, Bedrock started setting `BEDROCK_RESTRICT=1` on restricted strata.  Refactoring `neofetch` to do something along the lines of 

```
[[ -f /bedrock/etc/bedrock-release && $BEDROCK_RESTRICT -ne 1 ]]
```

might be slightly cleaner than the existing

```
[[ -f /bedrock/etc/bedrock-release && $PATH == */bedrock/cross/* ]]
```

If we're poking around here anyways, that might be worth considering.

**Comment by paradigm** [comment]
After more digging, seems like `dir` strata have their aliases counted as well.

Note in nezuSTDdos's image, the 1734 emerge packages for the system is exactly three times the emerge packages for the gentoo stratum: one for the stratum proper, and probably one for `local` and `init` aliases.

My proposed fix for counting disabled/hidden strata by redefining `dir` for Bedrock to loop over `brl list` output, like `tot`, should fix this as well.
