### ISSUE TITLE
Resolution: Wayland support

### ISSUE THREAD

**Issue by luispabon** [dylanaraps/neofetch#1301]
## Description
neofetch reports screen resolution as 1920x1080 instead of 3840x2160 under sway when display's scale is 2.

#### Neofetch version
6.0.0 (Ubuntu 19.04 package)

## Screenshot
![image](https://user-images.githubusercontent.com/6388823/62784464-7a4a1380-bab6-11e9-8819-92912924d34d.png)

```
~ swaymsg -t get_outputs
Output eDP-1 'Sharp Corporation 0x1476 0x00000000' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 0,0
  Scale factor: 2.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Available modes:
    3840x2160 @ 59.997002 Hz
```

## Config file
n/a

## Verbose log
https://pastebin.com/nTke2aAZ

**Comment by macowie** [comment]
I'm also seeing the scaled resolution instead of the actual. It's reporting 3072x1728 when it's actually
 3840x2160 at 125% scale. 

neofetch 6.0.0
Fedora 31 / GNOME / Wayland session

**Comment by dylanaraps** [comment]
This is the resolution at which `xrandr` detects from Xwayland. Nothing I can do here.

Changing the title to a feature request for Wayland resolution support.

**Comment by dylanaraps** [comment]
I will need information:

1). Can the resolution be retrieved in a portable way across all Wayland compositors? Even just GNOME/KDE/wlroots-based is fine.
2). Can a wayland session be detected in an **entirely** portable way?

**Comment by dylanaraps** [comment]
Fixed https://github.com/dylanaraps/neofetch/commit/c323470f2fbe21fe3b7528a542da5749d27f6e72

**Comment by luispabon** [comment]
:ok_hand:
