### ISSUE TITLE
OpenWRT not retriving cpu info

### ISSUE THREAD

**Issue by aeri** [dylanaraps/neofetch#1302]
## Description

The CPU model is not reading correctly because only shows the number of cores, instead the cpu model in /proc/cpuinfo

`root@OpenWrt:~# cat /proc/cpuinfo`
`system type             : bcm63xx/96348GW-11 (0x6348/0x00B0)`
`processor               : 0`
`cpu model               : Broadcom BCM6348 V0.7`
`BogoMIPS                : 254.97`

#### Neofetch version
6.0.1
## Screenshot

![alt text](https://i.imgur.com/skDRN2v.png)

## Config file

NS/NC

## /proc/cpuinfo

https://pastebin.com/kfC6F0YS

## Verbose log

https://pastebin.com/X9RxGRhz

**Comment by dylanaraps** [comment]
I can't reproduce this in the latest master.
