### ISSUE TITLE
GPU info inaccuracy

### ISSUE THREAD

**Issue by mossbyte** [dylanaraps/neofetch#1306]
## Description
Setting the GPU to display 'all' or 'dedicated' only picking up 2 of 3 Nvidia cards, yet displaying the ASPEED Graphics from a Supermicro motherboard. This is despite the rest of my system, and other software seemingly finding all three Nvidia cards just fine.

Wondering if you could confirm this possible bug, please?  *(reddit follow up) Thank you for taking a look at this!

#### Neofetch version
Neofetch 6.0.0
## Screenshot
![multi_gpu](https://user-images.githubusercontent.com/48395655/63832084-e638d280-c924-11e9-8846-a078816ae68e.png)

## Config file
http://ix.io/1TFq

## Verbose log
(Here's the `lspci -mm` you had requested)
http://ix.io/1TEf

**Comment by dylanaraps** [comment]
Fixed in master. :+1:
