### ISSUE TITLE
Strange characters with w3m

### ISSUE THREAD

**Issue by Sergey-Voskresenskiy** [dylanaraps/neofetch#1313]
## Description

What's wrong? Where do these symbols come from? 
I saw similar [issues](https://github.com/dylanaraps/neofetch/issues/916) but did not understand at all how its author solved this

#### Neofetch version
6.0.0
## Screenshot
https://imgur.com/Yb7Hnji
## Config file
https://pastebin.com/MZ1nTYf9
## Verbose log
https://pastebin.com/yrTWJzWS

**Comment by dylanaraps** [comment]
The user in the other bug had his locale unset or set incorrectly. What is your locale set to?

**Comment by Sergey-Voskresenskiy** [comment]
This

http://imgur.com/a/njzjGJr

**Comment by dylanaraps** [comment]
That explains it. You're using the `C` locale despite setting `en_us.UTF-8`.

**Comment by Sergey-Voskresenskiy** [comment]
thank you very much! heh,my fall, but, again, thanks for the help!
