### ISSUE TITLE
Cannot open neofetch in new terminal

### ISSUE THREAD

**Issue by userLegacy** [dylanaraps/neofetch#1315]
## Description

I am unable to open neofetch in a new terminal window? It works fine when i load it in the same terminal session. Like if i launch it like this _$ neofetch_, it loads but then i do _$ 'terminal' -e neofetch_ it closes immediately after opening the new terminal window. I am running on a new install i don't know if this is related to any dependencies 

#### Neofetch version
Neofetch 6.0.0
## Screenshot
https://imgur.com/a/AsI5Ypu
## Config file
Default one!?!

**Comment by dylanaraps** [comment]
This happens as `neofetch` is a one-shot utility and isn't a `neofetch` issue.

See: https://github.com/thestinger/termite/issues/55
