### ISSUE TITLE
No package counting of default Nix profile

### ISSUE THREAD

**Issue by ilya-fedin** [dylanaraps/neofetch#1317]
There are `/nix/var/nix/profiles/default` default profile that should be counting also.

**Comment by dylanaraps** [comment]
I don't believe this is needed from what I've been reading about this path. Please reopen with more information if you still believe this is needed.

**Comment by ilya-fedin** [comment]
This is necessary for nix on non-nixos that don't have /run/current-system. Moreover, the default profile can also be used on nixos.

**Comment by dylanaraps** [comment]
I'm going to need more information than that. How does this affect a nixOS machine? I need to understand the change before I implement it.

**Comment by ilya-fedin** [comment]
Nix has default storage, user storage, and system storage. When using Nix on non-NixOS, there is no way to install the package globally except in the default storage. Thus, neofetch does not show a significant portion of the packages.
This will affect NixOS only if a user has something in the default storage (and if it does, then neofetch should count it, right?).
