### ISSUE TITLE
My neofetch doesn't show any information

### ISSUE THREAD

**Issue by Thom2503** [dylanaraps/neofetch#1328]
I installed it and when I tried it it didn't show anything except for the ascii art. I then tried to edit the config file and I just did the normal config. And still got nothing but know with an error saying I have a syntax error; 
/home/thom/.config/neofetch/config.conf: line 1: syntax error near unexpected token `$'{\r''
'home/thom/.config/neofetch/config.conf: line 1: `print_info() {
Here is a screenshot of the problem.
![scrnshot](https://user-images.githubusercontent.com/53975935/66420637-872baa80-ea06-11e9-87f8-b6ee53617342.png)

**Comment by dylanaraps** [comment]
How did you install `neofetch` and which version did you install?

**Comment by Thom2503** [comment]
I did, sudo pacman -S neofetch. And the version is if I'm right version 6.0.0

**Comment by dylanaraps** [comment]
Does `neofetch` work in a different terminal emulator?

**Comment by Thom2503** [comment]
no, it doesn't. I tried konsole, termite, zsh. Nothing worked

**Comment by dylanaraps** [comment]
Does `neofetch --config off` work?

**Comment by Thom2503** [comment]
No still a blank screen, but without the syntax error.

**Comment by dylanaraps** [comment]
Output of `env` (*omit any sensitive information if it exists*)?

**Comment by Thom2503** [comment]
I don't see anything with env or something.

**Comment by dylanaraps** [comment]
You ran the `env` command?

**Comment by Thom2503** [comment]
Yes, still nothing.

**Comment by dylanaraps** [comment]
Try `neofetch` from this repository:

```
git clone https://github.com/dylanaraps/neofetch --depth 1
cd neofetch
./neofetch --config off
```

**Comment by Thom2503** [comment]
It still doesn't work, I tried with different terminals.

**Comment by dylanaraps** [comment]
Does Screenfetch work?

You can also try: https://github.com/dylanaraps/pfetch

We need to see if this is a `neofetch` issue or one with your system.

**Comment by Thom2503** [comment]
Sorry for the late response, it was getting late. But pfetch works.

**Comment by dylanaraps** [comment]
Send me a log file?: Run `neofetch -vv --config off &> neofetchlog` and upload the `neofetchlog` file.

**Comment by Thom2503** [comment]
Where do I find that log file? After I run that command

**Comment by dylanaraps** [comment]
In your current directory named "neofetchlog".

**Comment by Thom2503** [comment]
I can't find it.
