### ISSUE TITLE
Cannot find shell type in terminal

### ISSUE THREAD

**Issue by jakewilliami** [dylanaraps/neofetch#1340]
## Description

Cannot find shell type in terminal.  I don't know if it is related, but I recently changed my font menlo to courier new.  I am on a MacBook Pro, using OS version 10.14.6.

#### Neofetch version
Neofetch 6.1.0

## Screenshot
<img width="1414" alt="Screen Shot 2019-10-22 at 11 07 38 PM" src="https://user-images.githubusercontent.com/54291317/67276353-01891e00-f521-11e9-8666-ad8029c3b828.png">

## Config file
https://pastebin.com/fv71GVCL

## Verbose log
https://pastebin.com/EKMPL4ki

**Comment by dylanaraps** [comment]
Your shell is for some reason being detected as `shell='[1;38;5;28m '`???? What's the output of `echo $SHELL`?

**Comment by jakewilliami** [comment]
Running `echo $SHELL` comes up as a blank space in my terminal, but pushing into a text file it is actually echoing `[1;38;5;28m`

**Comment by dylanaraps** [comment]
Yup. This is an error in your system and not `neofetch`. 

`echo $SHELL` should look something like this:

```sh
-> echo $SHELL
/bin/sh
```
