### ISSUE TITLE
Incorrect ram usage

### ISSUE THREAD

**Issue by DevYama** [dylanaraps/neofetch#1345]
## Description
Neofetch reports different ram usage compared to what ksysguard reports. 

#### Neofetch version
6.1.0
## Screenshot
Attached
## Config file
https://pastebin.com/4ix8VAdN
## Verbose log
https://pastebin.com/NLaqceaS
1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

![Screenshot_20191101_160736](https://user-images.githubusercontent.com/26037681/68030511-5287d780-fcc2-11e9-9edf-7ba478d0b4e1.png)

**Comment by dylanaraps** [comment]
Neofetch is right here. See: https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
