### ISSUE TITLE
Could not find app path for 'git'. even though its in my PATH

### ISSUE THREAD

**Issue by lucidsleepy** [dylanaraps/neofetch#1348]
## Description

When running neofetch on windows 10 i get the following error:

Could not find app path for 'git'.
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\Aleksandar Vucenovic\scoop\apps\neofetch\current\neofetch.ps1:1 char:15
+ & $(join-path $(scoop prefix git) 'bin\bash.exe') $(join-path $psscri ...
+               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
   mand

The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command
name, a script block, or a CommandInfo object.
At C:\Users\Aleksandar Vucenovic\scoop\apps\neofetch\current\neofetch.ps1:1 char:3
+ & $(join-path $(scoop prefix git) 'bin\bash.exe') $(join-path $psscri ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

**Comment by dylanaraps** [comment]
This is not a neofetch issue (looks to be a scoop/windows issue).

**Comment by plain-dev** [comment]
@vucenovic I found a [solution.](https://github.com/lukesampson/scoop/issues/4004#issuecomment-643349485)
