### ISSUE TITLE
Bonsai linux detection conflicts with bonsai.sh

### ISSUE THREAD

**Issue by al2me6** [dylanaraps/neofetch#1351]
## Description
(Yes, this issue is as weird as it sounds.)
[This commit](https://github.com/dylanaraps/neofetch/commit/42bed8b60e49246c355a09c87f9faffb088ebde5) added support for Bonsai Linux. However, on (decidedly not Bonsai Linux) systems with the [bonsai.sh](https://gitlab.com/jallbrit/bonsai.sh) script installed, Neofetch will erroneously display package count for the bonsai package manager.

#### Neofetch version
6.1.0 (git)

## Screenshot
![image](https://user-images.githubusercontent.com/35266431/69113717-cb708880-0a51-11ea-9653-e42fc00d5bb4.png)

## Config file
None; default

## Verbose log
Logging seems to explode dump lots of errors to terminal. Can provide later if necessary.

**Comment by JakeStanger** [comment]
Can confirm. I have bonsai.sh on my path as `bonsai` and it is displaying as 5 packages from Bonsai. Also using Arch.

**Comment by dylanaraps** [comment]
"Fixed". I need input from @mitchweaver regarding some kind of detection which doesn't conflict.
