### ISSUE TITLE
Image backend not working on macOS

### ISSUE THREAD

**Issue by e-caste** [dylanaraps/neofetch#1352]
## Description
I've tried on a MacBook Pro and a Mac Mini running macOS Catalina 10.15.1 and a MacBook Pro running macOS Mojave 10.14.6, each on iTerm2 3.3, and no device is able to show custom settings like the wallpaper instead of the Apple logo or adding an entry to the list on the right.
Neofetch was installed with `homebrew`.
Even the default macOS Terminal can't seem to work for finding the terminal window dimensions.

#### Neofetch version
6.1.0

## Screenshot
Skipping this since it shows the default for macOS.

## Config file
See [this file](https://github.com/e-caste/tmp/blob/master/config.conf), especially lines 595 and 609.

## Verbose log
See [this file](https://github.com/e-caste/tmp/blob/master/neofetchlog) in the same repo of config.conf.

**Comment by AzimovParviz** [comment]
4.0.0 is the last version that is able to show images on macOS, so I suggest downloading it from releases and compiling it

**Comment by e-caste** [comment]
Thanks a lot, that version actually works well! I don't really understand why the latest versions don't work anymore, though.

**Comment by soarn** [comment]
Same on MacBook Pro (13-inch, Late 2011), macOS High Sierra v10.13.6 with iTerm2 Build 3.3.8beta3.   Installed using `homebrew`.

**Comment by dylanaraps** [comment]
Please try the latest master. :+1:

**Comment by e-caste** [comment]
@dylanaraps can confirm it works! 👌🏼 (macOS Catalina 10.15.2, Neofetch "v6.1.0", iTerm2 Build 3.3.7)
Still no fix on the version from the Homebrew repo, I'll wait for it!
Feel free to close this issue

**Comment by dylanaraps** [comment]
Thanks for testing, I thought I had fixed this a while ago. :)

I'll be making a new release soon. :+1:

**Comment by strafe** [comment]
Until there's a new release you can install the HEAD version (assuming you're using Homebrew).
```
brew uninstall neofetch
brew install neofetch --HEAD
```

Just keep in mind HEAD versions don't support upgrading, so you'll want to switch back to stable releases at some point in the future.
