### ISSUE TITLE
Gnome Terminal Image doesn't work

### ISSUE THREAD

**Issue by gaetan1903** [dylanaraps/neofetch#1357]
## Description

Image doesnt'work in my gnome-terminal 

OS: Arch Linux
![Capture d’écran du 2019-12-04 11-29-04](https://user-images.githubusercontent.com/43904633/70126153-78b9e200-1689-11ea-899a-9d3a6f9c1441.png)

However it's working for xterm

#### Neofetch version
Neofetch 6.1.0

**Comment by dylanaraps** [comment]
I'll need a log from Gnome terminal.

**Comment by gaetan1903** [comment]
https://gist.github.com/gaetan1903/e4b0f75e3c31798357787ac2febba84

**Comment by gaetan1903** [comment]
<script src="https://gist.github.com/gaetan1903/e4b0f75e3c31798357787ac2febba840.js"></script>

**Comment by gaetan1903** [comment]
https://gist.githubusercontent.com/gaetan1903/e4b0f75e3c31798357787ac2febba840/raw/58c9ed23cba145bf626fa0a92339bc6dfb280a68/neofetchlog

**Comment by dylanaraps** [comment]
The error is due to `w3mimgdisplay` exiting with a status code of `1` (error) in GNOME terminal.

```
Image: w3m failed to display the image.
```

This isn't a Neofetch issue but an issue with GNOME terminal or `w3mimgdisplay`. Either GNOME terminal is incompatible with `w3mimgdisplay` or there's an issue with your system.
