### ISSUE TITLE
[Feature Request] Wayland Support

### ISSUE THREAD

**Issue by TakuyaSama** [dylanaraps/neofetch#1367]
## Description
I see lack of Wayland support, since every dependency mentioned on the wiki, is for X Windowing System, which is alright at the past, but now it's more than interesting to be able to run seamlessly under Wayland (which is my standard session with Plasma).

Thank you for your great work, neofetch is one of the best changes i made in a long time (i was using the simpler screenfetch before :)).

If you're suggesting a new feature then just a description will suffice.

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
Thanks for opening this issue.

A few questions:

- Where do you see Wayland support lacking?
- Are there well supported (*across compositors*) command-line tools for Wayland which fill the gaps in support? ie, replacements for `xprop`, `xdotool`, `xdpyinfo` and other Xorg related utilities.

**Comment by dylanaraps** [comment]
Closing this due to no reply.

**Comment by TakuyaSama** [comment]
> Thanks for opening this issue.
> 
Hi @dylanaraps, sorry for the waiting and lack of reply and thank you very much for your really quick response and interest.


>     * Where do you see Wayland support lacking?
> 
I'm saying basically because of the dependencies at the distribution i use (Arch Linux), so the reason for me to saying this is simple, because of the lacking pure and Wayland native software to supply the functionalities that these dependencies provide.

>     * Are there well supported (_across compositors_) command-line tools for Wayland which fill the gaps in support? ie, replacements for `xprop`, `xdotool`, `xdpyinfo` and other Xorg related utilities.
>
That's precisely what i wanted to say, but yes, looks like there's no reason for me to open this issue (Feature Request), because neofetch has no responsibility here.

After a few search, i couldn't find anything related to these Xorg related utilities equivalents for Wayland.

So the right thing IMHO is to keep the issue closed.

Thank you very much and sorry for the inconveniences.

Bests ^^.

**Comment by dylanaraps** [comment]
The dependencies are all strictly optional regardless though. Arch is a distribution which packages things "heavily", including most if not all of the "optional" dependencies.
