### ISSUE TITLE
Wrong CPU Frequency displayed

### ISSUE THREAD

**Issue by pakro** [dylanaraps/neofetch#1370]
## Description

My neofetch is showing an absurd high CPU frequency. I saw this bug already reported here and it also was a Sandy Bridge CPU.

Unfortunately I'm not even sure this is a neofetch bug.

#### Neofetch version

6.1.0-1

## Screenshot

![neofetch_madness](https://user-images.githubusercontent.com/8904139/70865188-7fcad500-1f52-11ea-8bc2-88f99d1d12bc.png)

## Config file

[config.conf.txt](https://github.com/dylanaraps/neofetch/files/3965109/config.conf.txt)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

https://gist.github.com/pakro/6aed8e0cc3dc9d08c3cbd66d6807fc4f

**Comment by dylanaraps** [comment]
Have you tried playing with the speed type?:

```sh
# CPU speed type
#
# Default: 'bios_limit'
# Values: 'scaling_cur_freq', 'scaling_min_freq', 'scaling_max_freq', 'bios_limit'.
# Flag:    --speed_type
# Supports: Linux with 'cpufreq'
# NOTE: Any file in '/sys/devices/system/cpu/cpu0/cpufreq' can be used as a value.
speed_type="bios_limit"
```

This isn't a neofetch bug regardless though. :)
