### ISSUE TITLE
Add support for heroku Python app

### ISSUE THREAD

**Issue by alexa-v2** [dylanaraps/neofetch#1371]
## Description

My Python app requires neofetch functionality for some functionality. However, the currently provided buldpack by this repository doesn't work as heroku states it's incompatible and refuses to deploy.

Using heroku-community/apt and specifying neofetch on the Aptfile does no good either - it simply complains about missing config files.

Obviously at this point some sort of special adaptation will be necessary

**Comment by alexa-v2** [comment]
Temporary workaround is:

`git clone https://github.com/dylanaraps/neofetch
cd n* && make PREFIX=/app/.apt/usr`

**Comment by alexa-v2** [comment]
Obviously being required to do that on every re-deploy or Dyno restart is strongly undesirable

**Comment by dylanaraps** [comment]
I feel this is out of scope for Neofetch and something you can very easily workaround. Thanks for opening this issue. :+1:
