### ISSUE TITLE
Getting Plasma wallpaper from plasmarc is wrong

### ISSUE THREAD

**Issue by arisinfenix** [dylanaraps/neofetch#1379]
## Description
The `usersWallpapers` entry in `plasmarc` lists wallpapers that the user added manually to the available wallpapers list in the plasma wallpaper settings gui. But _not_ the actual wallpaper that is used.

e.g.
```bash
$ cat ~/.config/plasmarc
 
[Wallpapers]
usersWallpapers=/home/tux/Bilder/icecold2.png,/home/tux/Bilder/s1I6ht.jpg
```
But `~/.config/plasma-org.kde.plasma.desktop-appletsrc` contains the actual wallpaper.

e.g.
```bash
$ grep Image .config/plasma-org.kde.plasma.desktop-appletsrc
Image=file:///usr/share/wallpapers/Next/contents/images/1366x768.png
```
So reverting commit ce39f1bdbd4c75c1afa60c05e0a8b354ab66678c should fix it. I don't know if all image backends work with `file://` or if that needs to be stripped from the final string?

**Comment by dylanaraps** [comment]
:+1:
