### ISSUE TITLE
neofetch 6.1.0 not getting display size

### ISSUE THREAD

**Issue by firnen0** [dylanaraps/neofetch#1383]
## Description
neofetch version 6.1.0 fails to get the window size using \033[14t on raspberry pi with gnome-terminal even though \033[14t does get the terminal size and prints it to the terminal. I've already changed the image.

#### Neofetch version
6.1.0

## Screenshot
![Screenshot from 2020-01-03 21-27-18](https://user-images.githubusercontent.com/37234915/71758665-d734d480-2e70-11ea-9864-1e0ddb3bbfe0.png)

## Config file
https://gist.github.com/firnen0/cef490fcd7514ff82e64f5b1d4f0b438
## Verbose log
https://gist.github.com/firnen0/a05aaa7f9079081f02bee450fbefe973

**Comment by dylanaraps** [comment]
This should be fixed in master. If not: https://github.com/dylanaraps/neofetch/issues/1392
