### ISSUE TITLE
[Chrome OS] logo only shows when using --distro_shorthand tiny

### ISSUE THREAD

**Issue by cstrouse** [dylanaraps/neofetch#1384]
## Description

There are two issues on Chrome OS.

First, the ```/etc/lsb-release``` output has changed and has an extra line that's being matched when trying to detect the version. The regex needs to be more specific. I'll open a PR with that once I get the second issue figured out. A second version line was added for the Android support that was added a while back.

Second, the Chrome OS ascii logo only shows when using ```--distro_shorthand tiny```. If I add another * before "Chrom"* then it works but I figure there's some other problem here.

```bash
chronos@localhost:/usr/local/tmp $ cat /etc/lsb-release 
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=6065001
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_RELEASE_BOARD=kevin-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=58
CHROMEOS_RELEASE_BUILDER_PATH=kevin-release/R79-12607.58.0
CHROMEOS_RELEASE_BUILD_NUMBER=12607
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=79
CHROMEOS_RELEASE_DESCRIPTION=12607.58.0 (Official Build) stable-channel kevin 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12607.58.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12607.58.0
```

```bash
chronos@localhost:/usr/local/tmp $ cat /proc/version 
Linux version 4.4.196-16940-geab5e6346fdb (chrome-bot@chromeos-ci-legacy-us-central2-d-x32-119-9vi7) (Chromium OS 9.0_pre365631_p20190821-r21 clang version 9.0.0 (/var/cache/chromeos-cache/distfiles/host/egit-src/llvm-project 6b043f051836635a1e88da4d0464e6569bd7b625) (based on LLVM 9.0.0svn)) #1 SMP PREEMPT Thu Dec 12 22:39:18 PST 2019
```

- [Y] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
6.1.0

## Screenshot
![Screenshot 2020-01-05 at 1 36 17 PM](https://user-images.githubusercontent.com/849044/71785995-b204ab00-2fc3-11ea-9048-a80b079c7eca.png)
![Screenshot 2020-01-05 at 1 36 11 PM](https://user-images.githubusercontent.com/849044/71785996-b204ab00-2fc3-11ea-9c3c-3b0a0e5bf84a.png)
![Screenshot 2020-01-05 at 1 36 04 PM](https://user-images.githubusercontent.com/849044/71785997-b204ab00-2fc3-11ea-98db-2431f24dddb8.png)

## Config file
None

## Verbose log
https://termbin.com/dj51

**Comment by cstrouse** [comment]
@dylanaraps I just tried the updated version and the results are the same. If I don't force ```--distro_shorthand tiny``` the ChromeOS logo isn't used.

**Comment by dylanaraps** [comment]
Send me a verbose log from the latest version. :+1:

**Comment by hykilpikonna** [comment]
This is now [fixed in HyFetch](https://github.com/hykilpikonna/hyfetch/commit/206fa8d7263dde235b5c59230803c644df887982)!

![Screenshot 2022-08-21 08 07 26](https://user-images.githubusercontent.com/22280294/185770120-fe643ece-248f-45ed-81c2-2dc79ccc1a4a.png)

**Comment by RockyYT1** [comment]
i have the same issue too 
![Screenshot 2022-12-22 4 50 53 PM](https://user-images.githubusercontent.com/86290259/209232250-d3cd5ab4-a122-4315-896d-6b698f52e07f.png)
Details for my chromebook
os: ChromeOS Developer mode
package manager: Chromebrew And Python3-Pip
fetch: Neofetch

**Comment by RockyYT1** [comment]
![Screenshot 2022-12-22 4 53 29 PM](https://user-images.githubusercontent.com/86290259/209232514-ed926589-2c09-4959-8fe8-e437b17a388e.png)
on hyfetch
its normal

**Comment by RockyYT1** [comment]
i want a spongebob themed neofetch btw
