### ISSUE TITLE
image display not working in gnome-terminal

### ISSUE THREAD

**Issue by OMGdaDPS** [dylanaraps/neofetch#1385]
Just as the title states, trying to display and image in the neofetch output doesn't work when using gnome-terminal. pretty much using the same exact config that I use in Konsole, which works. 

Ubuntu 19.10

**Comment by dylanaraps** [comment]
I need a log and your neofetch config to be of any help. :+1:

**Comment by OMGdaDPS** [comment]
oh man, im a retard. I was supposed to do that, and even had a text editor open to type it out... but got caught up in something and posted the little that I did. Give me just a min and I'll have it typed up.

**Comment by OMGdaDPS** [comment]
here is my config file:
[neofetchconf.txt](https://github.com/dylanaraps/neofetch/files/4048974/neofetchconf.txt)

I have uploaded a screenshot of the output of neofetch, after editing the conf file.

![Screenshot from 2020-01-10 23-30-20](https://user-images.githubusercontent.com/47292884/72198853-7aea2b80-3401-11ea-9f21-cded66dcd291.png)

here is the verbose log:
https://paste.ubuntu.com/p/nGxCvzjg6g/

**Comment by OMGdaDPS** [comment]
this is what it looks like when I dont try and use the w3m back end, and just change the ascii art to the lfs distro:

![Screenshot from 2020-01-10 23-37-20](https://user-images.githubusercontent.com/47292884/72198887-2c895c80-3402-11ea-920f-b006d15a176d.png)

**Comment by OMGdaDPS** [comment]
Also, I have installed w3m of course.

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/neofetch/issues/1392

**Comment by mattdm** [comment]
It works fine, just not in wayland.
