### ISSUE TITLE
Neofetch not shown images > sakura terminal

### ISSUE THREAD

**Issue by satanyachan** [dylanaraps/neofetch#1387]
## Neofetch version

> 6.1.0

## Screenshot

> https://imgur.com/a/akP62p7

## Config file

> https://pastebin.com/CBNap8Hy

## Verbose log

 https://pastebin.com/E47nxWR7

**Comment by dylanaraps** [comment]
Neofetch is failing to find your terminal's window size. Do you have `xdotool` or `xprop` installed?

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/neofetch/issues/1392
