### ISSUE TITLE
Binary releases for Windows?

### ISSUE THREAD

**Issue by ComputerPark** [dylanaraps/neofetch#1389]
## Description

I can't find any windows compiled binaries in this repository. Do I have to compile myself using mingw?

Also, It'll be awesome if we have choco releases.

**Comment by bgkillas** [comment]
this is impossible as its written in bash and bash is not supported for windows you have to use a alt or use wsl

**Comment by ComputerPark** [comment]
Then why README.md says you can run this on windows?

**Comment by dylanaraps** [comment]
You can run this on Windows through CYGWIN, MINGW, MSYS, WSL1, WSL2, GIT BASH etc.
