### ISSUE TITLE
[feature request] color block ordering

### ISSUE THREAD

**Issue by dasco597** [dylanaraps/neofetch#1390]
Hi there!

I was wondering if there was a way to rearrange the order of the colors in the color blocks?

I'm asking because I have my colors in a nice gradient, but not in order. So for example yellow, green, cyan, blue look really nice arranged like so, but don't look great in neofetch as the blocks are in the default order. I know swapping around my color assignments can achieve the same effect, but I'm used to my color outputs so I'd rather not.

I'm pretty sure this isn't supported so I've labeled it a feature request. I hope you think this is worth implementing!

Cheers.

**Comment by dylanaraps** [comment]
This is a little out of scope for the color blocks feature and would make things more complex than they already are..

In your config file you could tell neofetch to launch whatever color script you like (or write your own). The whole shell as a language is at your disposal.  

Thanks for opening this issue.
