### ISSUE TITLE
Linux Wayland resolution logic is not right

### ISSUE THREAD

**Issue by jdonofrio728** [dylanaraps/neofetch#1401]
## Description
The logic used to resolve the resolution for a Wayland display is not correct.

The logic just looks at the monitor devices and grabs the native resolution. This is fine as long as you are using that native resolution and not one of the other supported modes. The second issue is that it will only output the resolution of the first monitor since it breaks the loop after the variable is set.

If you're suggesting a new feature then just a description will suffice.

- [x] Does this issue still occur in the master branch? (**Required if issue**)
Yes

#### Neofetch version
6.1.0

## Screenshot
![image](https://user-images.githubusercontent.com/10515329/73711418-c88e4700-46d4-11ea-8696-9c59dd905483.png)

my actual resolution is currently set to 1920x1080 and I have two monitors:
```
(22:33:03) ± [donofrj@NOV13FG5Q2] ~/workspace/github/neofetch (master U:1 ✗)
→ swaymsg -pt get_outputs | grep "Current mode"
  Current mode: 1920x1080 @ 60.000000 Hz
  Current mode: 3840x2160 @ 59.997002 Hz
```

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

https://gist.githubusercontent.com/jdonofrio728/36c5eaf88179b0bb187eec303d76c098/raw/bf0ddc52778a46c6a82f6cdbadf74e0025652ee3/neofetchlog

**Comment by dylanaraps** [comment]
The Wayland logic is right. Showing only the maximum resolution is the sole way to display *something* on Wayland in a portable way. Your solution will only work on Sway and I am not going to hard-code resolution based on which Wayland Compositor is installed.

1) This needs detection for which compositor is in use.
2) This needs a list for the ever growing amount of Wayland compositors.

Until there's a tool which works in all compositors or some kind of standard, I won't be adding any kind of "real" support. I don't see a hardcoded list per compositor as any kind of solution. 

Thanks for opening this issue.

**Comment by jdonofrio728** [comment]
Your kind of already headed down that path with get_de() and get_wm() get_wm_theme etc ...

But that is fine. If you change your mind, I can submit a PR for a few of them.
