### ISSUE TITLE
Option: Display ZSH theme

### ISSUE THREAD

**Issue by MihailIosilevitch** [dylanaraps/neofetch#1405]
## Enhancement: Display ZSH theme
Neofetch should display ZSH theme! You can get it just taking $ZSH_THEME(if you are using ZSH). What about this idea?

**Comment by dylanaraps** [comment]
You can easily do this through your Neofetch config file.

Inside of `print_info()`:

```sh
prin "ZSH Theme" "$ZSH_THEME"
```
