### ISSUE TITLE
Updating the Linux Mint ASCII Logo

### ISSUE THREAD

**Issue by Gamegenorator** [dylanaraps/neofetch#1407]
## Description

In Linux Mint 19.3 the Mint Team changed the Linux Mint logo from the one neofetch currently uses, to a more circular one.

Old Mint Logo:
![image](https://user-images.githubusercontent.com/38223298/74092574-c92f3080-4a7a-11ea-8972-e63dc1d44d07.png)

New Mint Logo:
![image](https://user-images.githubusercontent.com/38223298/74092567-ab61cb80-4a7a-11ea-933c-e033f20c184a.png)

## My Proposal

To Account for the change I propose we update the Logo in neofetch

I propose 3 designs,

1. Larger design:
![image](https://user-images.githubusercontent.com/38223298/74092674-34c5cd80-4a7c-11ea-9760-989c00c23abb.png)

2. Larger design with white inter-text:
![image](https://user-images.githubusercontent.com/38223298/74092690-68a0f300-4a7c-11ea-811b-91243a739d73.png)

3. Smaller more compact design:
![image](https://user-images.githubusercontent.com/38223298/74092695-7d7d8680-4a7c-11ea-885d-dc5b01d71681.png)

However, I do not know which one the devs and community prefer (If they prefer to have it updated at all). So I am here to ask which design is generally liked best. And to ask the devs if I have implemented anything incorrectly before I create a pull request.

## References

[The Mint Team created a blog article talking about the Logo change.](https://www.linuxmint.com/rel_tricia_cinnamon_whatsnew.php) (You can find the information at the bottom under the header "Artwork improvements").

You can find the source code to my proposal on my fork ([HERE](https://github.com/Gamegenorator/neofetch))(Each proposal has its own branch)

**Comment by dylanaraps** [comment]
I like #1 though it'd be nice if it were a little smaller. Maybe somewhere between #1 and #3? The best course of action here is to add the new logo and keep the old one around as `mint_old`.

**Comment by Gamegenorator** [comment]
@dylanaraps I've updating my fork to include the old logo, I don't know what format to write it in when you say `mint_old` so I made an assumption, if you want me to format it differently let me know.

As far as shrinking #1, I'm having difficulty find a size balance while maintaining its symmetry and losing as little detail as possible. I will continue looking into it though.

**Comment by Gamegenorator** [comment]
@dylanaraps What do you think of this slimmed down version?

![image](https://user-images.githubusercontent.com/38223298/74094402-66975e00-4a95-11ea-82ce-95008a004fe5.png)

Source code is on my fork as usual.

**Comment by dylanaraps** [comment]
I like it, nice. :+1:

**Comment by Gamegenorator** [comment]
Shall I create a PR then?

**Comment by dylanaraps** [comment]
Yeah. :+1:

**Comment by Gamegenorator** [comment]
[Pull Request Created a Merged](https://github.com/dylanaraps/neofetch/pull/1408)
