### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by YHYJ** [dylanaraps/neofetch#1411]
## Description

If you're suggesting a new feature then just a description will suffice.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version

Neofetch 6.1.0

## Screenshot

![neofetch.png](https://i.loli.net/2020/02/18/94k6iJv1KScZRCE.png)

## Config file

[neofetch config file](https://pastebin.com/embed_js/tYX1f0Eu)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

[neofetch](https://pastebin.com/embed_iframe/097d6S7r)

---

My other computer (thinkpad) not have this problem
I think the difference between the two computers is: thinkpad not block ‘nouveau’ and ‘nvidia’, and this computer blocks

**Comment by dylanaraps** [comment]
What's the problem exactly?

**Comment by YHYJ** [comment]
The information displayed in the "GPU Driver" column is error, because it shows my disk info

**Comment by dylanaraps** [comment]
Send me the full output of `lspci -nnk`.

**Comment by YHYJ** [comment]
See [lspci](https://pastebin.com/embed_iframe/21V0mJMw)

Thanks!

**Comment by dylanaraps** [comment]
Fixed, thanks.
