### ISSUE TITLE
not grep compatible

### ISSUE THREAD

**Issue by badlandz** [dylanaraps/neofetch#1413]
## Description

If you're suggesting a new feature then just a description will suffice.

If you do a "neofetch > 1.txt" "neofetch > 2.txt" etc a few times, then try to "grep *.txt $USER" it goes weird.... Just saying... I'd look at the code, but I am guessing each line isn't ending with a reset to terminal colors??

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

TBD, I'll give it a shot if I have time in the next few days.

## Screenshot
Not going to do that...
## Config file
none
## Verbose log
none
1. Run `neofetch -vv 2> neofetchlog`

2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by badlandz** [comment]
test script:
`mkdir ~/SysDat
neofetch > ~l/SysDat/$(date '+%Y-%m-%d-%H:%M:%S')
sleep 1
neofetch > ~l/SysDat/$(date '+%Y-%m-%d-%H:%M:%S')
sleep 1
neofetch > ~l/SysDat/$(date '+%Y-%m-%d-%H:%M:%S')
sleep 1
neofetch > ~l/SysDat/$(date '+%Y-%m-%d-%H:%M:%S')
sleep 1
neofetch > ~l/SysDat/$(date '+%Y-%m-%d-%H:%M:%S')
grep ~/SysDat/*.txt $HOST`

**Comment by dylanaraps** [comment]
There are multiple ways to get parseable information output.

- `neofetch --json`.
- `neofetch cpu`, `neofetch battery`, etc etc.
- `neofetch --stdout`
