### ISSUE TITLE
Support macOS Catalina firmlinked volumes

### ISSUE THREAD

**Issue by schrodincat** [dylanaraps/neofetch#1414]
## Description

Disk section reports misleading info on macOS Catalina due to the new feature of macOS Catalina: a separation of system volume using firmlink.

Used space, free space and the usage percent are incorrect for `/` and `/System/Volumes/Data` volumes as a result (see screenshot, it should be the sum of two: `410G / 466G`).

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
`6.1.0`

## Screenshot
<img width="682" alt="Screenshot 2020-02-24 at 22 23 53" src="https://user-images.githubusercontent.com/13354491/75183844-644f2800-5754-11ea-8662-09c4c8dca8e0.png">

## Relevant config part

```
print_info() {
    info title
    info underline

    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "WM Theme" wm_theme
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "Terminal Font" term_font
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory
    info "Disk" disk

    info cols
}

disk_show=('/' '/System/Volumes/Data')
disk_subtitle="mount"
```

**Comment by dylanaraps** [comment]
I need a log or I can't help you.

Also, neofetch just parses the output of `df`. Does that display correctly? (`df  / /System/`)

**Comment by schrodincat** [comment]
@dylanaraps no, it doesn't, `df` is not aware of this macOS feature:

```
❯ df -P -h / /System/Volumes/Data
Filesystem      Size   Used  Avail Capacity  Mounted on
/dev/disk1s5   466Gi   10Gi   55Gi    16%    /
/dev/disk1s1   466Gi  398Gi   55Gi    88%    /System/Volumes/Data
```

**Comment by dylanaraps** [comment]
Then there's nothing I can do about it. Thanks for opening this issue.
