### ISSUE TITLE
--ascii stopped working

### ISSUE THREAD

**Issue by MikeyBeez** [dylanaraps/neofetch#1415]
neofetch --ascii `fortune|cowsay -W 30 in my zhr.rc file no longer works.  Neofetch produces what neofetch alone would produce.  
neofetch --version is 3.4.0.

**Comment by dylanaraps** [comment]
Please reopen with the issue template filled in.

**Comment by MikeyBeez** [comment]
I cloned the latest and ran make.  It works fine now.  Thank you.
