### ISSUE TITLE
Incorrect font parsing in Kitty

### ISSUE THREAD

**Issue by kaewhyes** [dylanaraps/neofetch#1419]
## Description

Kitty does not parse font names correctly.

- [ ] Does this issue still occur in the master branch 
(The issue does not occur in master)

#### Neofetch version
`Neofetch 6.0.1`
## Screenshot
![screenshot](https://i.salejandro.me/A7N3ZS.png)
## Config file
https://termbin.com/xlf8
## Verbose log
https://termbin.com/k95u

**Comment by dylanaraps** [comment]
If the issue does not occur in master, it has already been fixed. Wait for the next release. :+1:
