### ISSUE TITLE
Malposition in gjs terminal

### ISSUE THREAD

**Issue by tuberry** [dylanaraps/neofetch#1420]
## Description
The info isn't aligned with logo in [gjs terminal](https://github.com/bigbn/drop-down-terminal-x)
And also neofetch can't detect terminal font in both tilix and gjs terminal (which uses system monospace font)

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
6.1.0
## Screenshot
![neofetch](https://user-images.githubusercontent.com/17917040/76084981-10620000-5fec-11ea-980c-0282192ea911.png)

## Config file
The default
## Verbose log
https://paste.ubuntu.com/p/2wWpVHctxm/
1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
This isn't a fault in neofetch. It's in the terminal itself. As a workaround you can disable ascii art or maybe even swap to a smaller ascii art file. 

Open a separate issue for the fonts. :+1:
