### ISSUE TITLE
uptime_shorthand=off; doesn't display secs (Linux)

### ISSUE THREAD

**Issue by PureArtistry** [dylanaraps/neofetch#1422]
title says it all  EDIT: doesn't matter what uptime option, just checked default config, no seconds.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)
yes

#### Neofetch version
7.0

## Screenshot
![neofetch](https://user-images.githubusercontent.com/53883649/76164114-13700400-6144-11ea-977a-e8fe7e98e2a2.png)

## Config file
[config.conf.txt](https://github.com/dylanaraps/neofetch/files/4303271/config.conf.txt)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/4303273/neofetchlog.txt)

personal aside: I prefer the old full days, minutes, seconds readout. This is something I can easily change for myself, just thought I'd mention it.

**Comment by dylanaraps** [comment]
Fixed, thanks!

**Comment by PureArtistry** [comment]
Pleasure, love your work.

**Comment by ghost** [comment]
Hi, i know this is a closed and old issue, but i'm facing the same thing.
I tried many configurations for uptime and none of them are showing the seconds if it's less than a minute. Funny thing is that i use WSL and i have two distros, Ubuntu and Debian, and neofetch is installed on both of them but it only display seconds on Debian.
![image](https://user-images.githubusercontent.com/34722707/168393467-0a914b9c-989d-4cf0-bad0-2d06fe778bea.png)

![image](https://user-images.githubusercontent.com/34722707/168393488-21aff7ca-0f39-4cde-a59c-a4461b94930e.png)


This is my conf file for Ubuntu: 
[config.conf.txt](https://github.com/dylanaraps/neofetch/files/8691505/config.conf.txt)

And here is neofetchlog: 
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/8691506/neofetchlog.txt)


Neofetch version 7.0
