### ISSUE TITLE
Which config file should we use?

### ISSUE THREAD

**Issue by tonijarjour** [dylanaraps/neofetch#1423]
Distro: Arch Linux

The wiki has this config file which I copied and edited: https://github.com/dylanaraps/neofetch/wiki/Config-File

I decided to check what would happen if I ran without a config file, and it generates one. But that one is very different from the one in the wiki:
https://gist.githubusercontent.com/tonijarjour/6f72ab9a4679272d1ba57c76f979115f/raw/7de9f2ae9d3b193ea18ac4dd0e966ce0f1160ae2/config.conf

And this begs the question, which one are we supposed to use? Is it a problem with the distro package having an old file, or is the wiki the old one?
Also the default config that's supposed to be in `/etc/neofetch/config` isn't there, nor is it inside `/usr/share` or `/usr/share/doc`. There is no neofetch folder at all.

**Comment by dylanaraps** [comment]
Neofetch will create the config file in `~/.config/neofetch/neofetch.conf` on first run. It respects the `$XDG_` variables so the location will differ based on your configuration.

The Wiki config file is outdated as I forgot to update it with the latest release. The `/etc` directory is up to you or your distribution to create.

**Comment by Brottweiler** [comment]
You could also do `neofetch --print_config > neoconf.conf` then if you want to update your local config with the latest one you use a diff tool to see what changed.

**Comment by bwoodruff** [comment]
Can you please clarify where the default config is coming from if `/etc/neofetch` doesn't exist?
I copied my config to `/etc/neofetch/config` (and also tried `/etc/neofetch/config.conf`) hoping that would cause it to apply to any users who didn't yet have a config, but it doesn't.

**Comment by Brottweiler** [comment]
It comes from the script itself. But I don't know how to apply config for all users, which path it should be in.
