### ISSUE TITLE
In Ubuntu Docker, Neofetch treat zsh with oh-my-zsh as bash

### ISSUE THREAD

**Issue by Veronan** [dylanaraps/neofetch#1428]
## Description

If you're suggesting a new feature then just a description will suffice.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version

Neofetch 3.4.0

## Screenshot

<img width="718" alt="屏幕截图 2020-03-24 19 50 01" src="https://user-images.githubusercontent.com/60590726/77422729-eccef000-6e08-11ea-8838-0530d329ddd2.png">

## Config file

No config file.

## Verbose log

https://gist.github.com/ada420728af8191ca71a82724a4f6464

**Comment by dylanaraps** [comment]
Your shell isn't correctly set in the environment (`$SHELL`). This isn't a neofetch issue.

Also see: https://gist.github.com/Veronan/ada420728af8191ca71a82724a4f6464#file-neofetchlog-L642

**Comment by Veronan** [comment]
Thanks! It works after `export SHELL=/usr/bin/zsh` 👍
