### ISSUE TITLE
Default config for all users (where?)

### ISSUE THREAD

**Issue by bwoodruff** [dylanaraps/neofetch#1429]
## Description

Following up on https://github.com/dylanaraps/neofetch/issues/1423#issuecomment-602110386

I'm running Fedora 32 and have a config.conf file that I want to be applied to all users who don't already have a config stored in /etc/neofetch. When a new user runs neofetch they do not get this config file applied.

```
ls -la /etc/neofetch
total 36
drwxr-xr-x.   2 root root  4096 Mar 28 12:11 .
drwxr-xr-x. 151 root root 12288 Mar 28 12:10 ..
-rw-r--r--.   1 root root 17778 Mar 28 12:11 config.conf
```
Instead they get the default out of the box config. For example, the config I have in /etc/neofetch/config.conf has color boxes turned off, but when new users run neofetch they get the color boxes.

#### Neofetch version

Neofetch 7.0.0

**Comment by dylanaraps** [comment]
Neofetch will create a config for the current user automatically unless `--no_config` is given at runtime. The argument `--config none` can also be used to disable reading the user's config file. In fact, there's no code for `/etc/` based configuration files at all anymore (going four years now).

I understand the use-case but it's not something I want to address right now. I can't see a method of implementation which doesn't break the current (and now expected) behavior. Do we read `/etc/neofetch/config.conf` only when a user config doesn't exist? Do we still automatically create user config files? etc.

Thanks for opening this issue.

**Comment by bwoodruff** [comment]
That's reasonable, thank you. I was able to work around this for my use case by adding
`neofetch --config /etc/neofetch/config.conf`
to my /etc/profile.d/mymotd.sh
instead of simply `neofetch`

It does mean that users who _do_ have their own config won't have it applied, but for this purpose, I'm okay with that. Thank you.
