### ISSUE TITLE
[Suggestion] Text-only mode (No VTE cursor escapes)

### ISSUE THREAD

**Issue by martmists** [dylanaraps/neofetch#1431]
## Description

I'm aiming to embed neofetch output in a custom zshrc I'm writing, but the escape codes make it impossible for me to move the entire thing around relatively with VTE escape codes (mainly indents) and since that would be hell to support, I'm asking for a text-only output mode (i.e. no VTE escapes for cursor movement, output already as it should be), that way I can e.g. use python's textwrap module to indent it and print it wherever I need to.

**Comment by dylanaraps** [comment]
`neofetch --json` or `neofetch --stdout`.

**Comment by martmists** [comment]
--stdout and --json both don't output the ASCII.

**Comment by dylanaraps** [comment]
Right. You'll have to then strip the cursor sequences yourself from Python. Display without cursor movement sequences isn't really a possibility at all given the output requirements.
