### ISSUE TITLE
No GPU displayed for Ubuntu on Windows 10 WSL

### ISSUE THREAD

**Issue by ddilanchi** [dylanaraps/neofetch#1434]
GPU: "GPU NAME"
does not display and can not be enabled.

![Annotation 2020-03-31 162320](https://user-images.githubusercontent.com/30396611/78084025-fc4fbb00-736b-11ea-805b-bb3124505dab.png)

**Comment by JaylonGu** [comment]
wsl still doesn't support gpu

**Comment by dylanaraps** [comment]
I think this is the case, it should use `lspci` (if it works).
