### ISSUE TITLE
Hide logo through config?

### ISSUE THREAD

**Issue by zacanger** [dylanaraps/neofetch#1437]
## Description

It could be that I couldn't find it, but is there an option to hide the logo through config or a flag?

#### Neofetch version

3.4.0 (Ubuntu), 6.1.0 (Brew)

## Screenshot

N/A

## Config file

N/A

## Verbose log

N/A

**Comment by arisinfenix** [comment]
Try `neofetch --stdout`.

**Comment by zacanger** [comment]
Thank you, that works perfectly for my use case!
