### ISSUE TITLE
Art's author name missing in readme file

### ISSUE THREAD

**Issue by anakimluke** [dylanaraps/neofetch#1438]
I noticed the image at the left side used in the screenshot:

![image](https://user-images.githubusercontent.com/22756345/78850802-7fb58000-79ee-11ea-82af-3eb1392fb119.png)

I found it incredibly pretty and wanted to know who's the author of it.

I searched the readme file, the wiki, issues and commit history but couldn't find it.

By using google images, I was able to get to this [imgur album](https://imgur.com/gallery/zmgwB), which suggests Ilya Kuvshinov painted it.

![image](https://user-images.githubusercontent.com/22756345/78851388-0d459f80-79f0-11ea-9e21-8d16f326da51.png)

I think if we could have confirmation that's the author it'd be a good idea to credit them in the readme file :)

**Comment by dylanaraps** [comment]
Will do so soon. Thanks
