### ISSUE TITLE
HP/UX 11iv3 (11.31) INOP

### ISSUE THREAD

**Issue by ehowton** [dylanaraps/neofetch#1440]
## Description

neofetch-7.0.0 returns:
Unknown OS detected: 'HP-UX', aborting...
Open an issue on GitHub to add support for your OS.

using the tarball i found on another thread (https://github.com/dylanaraps/neofetch/archive/hp-ux.tar.gz):
[neofetch-hp-ux] root@belanna# neofetch
ABORT instruction (core dumped)

[neofetch-hp-ux] root@belanna# strings core | wc -l
9630
strings core output here: http://unixspook.com/strings_core.txt

RX2600 2x dual-core Itanium 12GB RAM 

#### Neofetch version

both 7.0.0 & hp-ux

How can I help??

**Comment by michael-o** [comment]
Does not fail for me, but does not work either:

```
$ uname -a
HP-UX deblndw0 B.11.31 U ia64 HP-UX
osipovmi@deblndw024v:~/neofetch (master=)
$ ./neofetch
Unknown OS detected: 'HP-UX', aborting...
Open an issue on GitHub to add support for your OS.
```

**Comment by dylanaraps** [comment]
Yes. There's no HP-UX support. There was an attempt in the past by someone though it was never done iirc. Contributions are welcome as I don't have access to a HP-UX machine.
