### ISSUE TITLE
--refresh_rate option displays the text "--refresh_rate"

### ISSUE THREAD

**Issue by amosbatto** [dylanaraps/neofetch#1443]
## Descripition
The `--refresh_rate` option displays the text "--refresh_rate" rather than displaying information if it is used after another option. 

If I use the command `neofetch --refresh_rate` or `neofetch --refresh_rate --cpu_temp`, then the `--refresh_rate` option doesn't display anything. However, the command `neofetch --cpu_temp --refresh_rate` displays something like: `CPU: Intel i5-5200U (4) @ 2.700GHz [56.0°--refresh_rate]`

#### Neofetch version
Neofetch 6.0.0 (from Debian buster repo)

## Screenshot
![neofetch_bug](https://user-images.githubusercontent.com/4958913/79455646-33081100-7fbb-11ea-85d5-9e612f5353ce.png)

## Config file
I don't know where the config file is.

## Verbose log
[neofetchlog.log](https://github.com/dylanaraps/neofetch/files/4486980/neofetchlog.log)

**Comment by arisinfenix** [comment]
The problem is that you ommited the values for the flags.
e.g. `neofetch --cpu_temp C --refresh_rate on`.
