### ISSUE TITLE
info "Disk" disk strange output & some extras info doesn't display

### ISSUE THREAD

**Issue by lucknaumann** [dylanaraps/neofetch#1445]
## Description

Uncommenting `info "Disk" disk` results in a partially correct output: `Disk (81%): 495G / Fles/Git (97G%)`. What is `Fles/Git (97G%)`? I'm guessing this might be my external SSD.

Also uncommenting `info "Font" font` `info "Users" users` `info "Song" song` ` [[ "$player" ]] && prin "Music Player" "$player"` results in no display of this info.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.0.0

## Screenshot
_Git-for-Windows_ 
````
                                ..,   AW@AW-17
                    ....,,:;+ccllll   ---------
      ...,,+:;  cllllllllllllllllll   OS: Windows 10 Home x86_64
,cclllllllllll  lllllllllllllllllll   Host: Alienware Alienware 17
llllllllllllll  lllllllllllllllllll   Kernel: 10.0.17763
llllllllllllll  lllllllllllllllllll   Uptime: 25 days, 22 hours, 40 mins
llllllllllllll  lllllllllllllllllll   Shell: bash 4.4.23
llllllllllllll  lllllllllllllllllll   Resolution: 1920x1080
llllllllllllll  lllllllllllllllllll   DE: Aero
                                      Terminal: mintty
llllllllllllll  lllllllllllllllllll   Terminal Font: 12
llllllllllllll  lllllllllllllllllll   CPU: Intel i7-4700MQ (8) @ 2.394GHz
llllllllllllll  lllllllllllllllllll   GPU: NVIDIA GeForce GTX 770M Intel(R) HD Graphics 4600
llllllllllllll  lllllllllllllllllll   Memory: 5969MiB / 16269MiB
llllllllllllll  lllllllllllllllllll   Disk (81%): 495G / Fles/Git (97G%)
`'ccllllllllll  lllllllllllllllllll
       `' \*::  :ccllllllllllllllll
                       ````''*::cll
                                 ``
````

## Config file

Only uncommented `info "Disk" disk` `info "Font" font` `info "Users" users` `info "Song" song` ` [[ "$player" ]] && prin "Music Player" "$player"`.

[Config file](https://gist.github.com/lucknaumann/78f9f76ac8c1052a6a8f0fc7b7ec253d)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

[Verbose log](https://gist.github.com/lucknaumann/7919d052ceb8c264fbb088a0b3b6d882)

**Comment by dylanaraps** [comment]
Not everything supports Windows (typically not the optional info outputs). This is more an issue with your version of `df`. Can you send me the full output of `df -P -h /`?

**Comment by lucknaumann** [comment]
Yeah, I thought it might it might be something like that. 
Sure, thanks:
````
Filesystem            Size  Used Avail Use% Mounted on
C:/Program Files/Git  495G  401G   94G  82% /
````

**Comment by dylanaraps** [comment]
Ah, the issue is that the path has a space inside its name. We can't parse the information in a reliable way in this case. I don't think there's anything that I can do either as we're limited to working with the output as it is right now.

**Comment by lucknaumann** [comment]
I understand. Sounds great! Thanks for your responses! =)
