### ISSUE TITLE
Terminal font displayed for st (font2 patch)

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/neofetch#1446]
## Description

In st terminal, the terminal font displayed is the second font listed in config.def.h and not the default (after font2 patch has been applied). Occurs in latest master branch.

#### Neofetch version

7.0.0 (latest git)

## Screenshot

![2020-04-17_06-21-24_AM](https://user-images.githubusercontent.com/33555080/79559499-dc124280-8073-11ea-91db-d1603ce19198.png)

## Config file

[link](https://pastebin.com/Dmm6hPyd)

## Verbose log

[link](https://pastebin.com/qv9ScwfW)

## st config.def.h

```
static char *font = "scientifica:size=8:antialias=true:autohint=true";
static char *font2[] = {
	"Typicons:size=8:antialias=true:autohint=true",
};
```

**Comment by wundrweapon** [comment]
I use [Luke Smith's build of st](https://github.com/lukesmithxyz/st), where the `font` and `font2` constants are just in `config.h` but the problem still exists. Neofetch reports JoyPixels, but my `~/.Xresources` sets the terminal to use Fira Code

**Comment by dylanaraps** [comment]
Send me the full output of `strings /path/to/st`.

**Comment by vaskark** [comment]
[Here](https://pastebin.com/9JhxNNKJ)

**Comment by wundrweapon** [comment]
[strings-st.txt](https://github.com/dylanaraps/neofetch/files/4671124/strings-st.txt)

**Comment by dylanaraps** [comment]
Yeah. We're not going to use strings. There's also no way for me to detect whether the Xresources patch has been applied either right? Honestly, supporting every combination of every patch is unworkable. We'll support font2 and leave it there.

**Comment by dylanaraps** [comment]
If we can detect Xresources patch, we'll add support for it.

**Comment by wundrweapon** [comment]
Since my last post here version 7.1.0 has been released, but without doing anything to my terminal neofetch now properly reports my terminal font
