### ISSUE TITLE
Coudn’t detect some info

### ISSUE THREAD

**Issue by Am1nCmd** [dylanaraps/neofetch#1457]
Hi there. I’m using neofetch v7.0 on iOS 13.3 Unc0ver

Dependency GAWK has been installed too...
But still, some info is missing. Detail available in the image

![image](https://user-images.githubusercontent.com/15339573/81500786-9e18df00-92fe-11ea-965c-e2b8d0b8fad1.png)

**Comment by dylanaraps** [comment]
This is fine. This info isn't supported on iOS (and won't ever be).
