### ISSUE TITLE
custom text and fixed(permanent) logo

### ISSUE THREAD

**Issue by speedfixer** [dylanaraps/neofetch#1458]
No a bug or feature request.

I understand the issues around missing os-release and/or lsb-release info files regarding OS detection.
I know I can use ' neofetch --ascii_art "Lubuntu" ' in command line or script to get the Lubuntu logo to display.

What I want is to change the config to provide the Lubuntu (or other) logo as the default to the simple 'neofetch' command.

I searched everywhere and read all the logo/OS related Github issues.
I noted that many are apparently putting custom text in their configs.

I **don't** see instructions anywhere for either the custom text or fixing a default logo into the config file.
(I did not try to examine anyone's source code to see how they did it.)

I did poke a little at my config file. I didn't find or see a way to display a permanently fixed logo using that file. I expect this is really simple task.

So - topics for wiki, and my questions are:

1 - How to put custom text into the config file.
2 - How to set a fixed OS logo/art/ascii_art in the config file.

Each such that a simple neofetch command with no tail will show these changes.

david

**Comment by dylanaraps** [comment]
This is all doable via the config file.

**Comment by speedfixer** [comment]
I believe you. That answer does not recognize that I tried to find an answer and could not. 

david
