### ISSUE TITLE
Xubuntu logo not appearing in Xubuntu

### ISSUE THREAD

**Issue by philipzae** [dylanaraps/neofetch#1461]
## Description
I've tested Xubuntu 18.04 and 20.04, Kubuntu 20.04, and Ubuntu Mate 20.04 and with ascii_distro set to "auto" in the configuration file, it shows the Ubuntu logo rather than the correct flavor logo. Neofetch seems to rely /usr/lib/os-release which ubuntu flavors don't modify to distinguish them apart.

- [X] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.0.0

## Screenshot
![preview](https://imgur.com/Rro2QsQ.png)

## Config file
[config.txt](https://github.com/dylanaraps/neofetch/files/4638325/config.txt)

## Verbose log
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/4638329/neofetchlog.txt)

**Comment by dylanaraps** [comment]
You need to use `--ascii_distro xubuntu` as there's no way to reliably detect Xubuntu (as it **is** Ubuntu).

**Comment by philipzae** [comment]
There is a possible way to detect the Ubuntu flavors using environment variables, like GDMSESSION, DESKTOP_SESSION, or XDG_CONFIG_DIRS.

**Xubuntu**
XDG_CONFIG_DIRS=/etc/xdg/xdg-xubuntu:/etc/xdg:/etc/xdg
DESKTOP_SESSION=xubuntu
XDG_SESSION_DESKTOP=xubuntu
XDG_DATA_DIRS=/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share
GDMSESSION=xubuntu

**Lubuntu**
XDG_CONFIG_DIRS=/etc/xdg/xdg-Lubuntu:/etc/xdg:/etc/xdg
DESKTOP_SESSION=Lubuntu
XDG_DATA_DIRS=/usr/share/Lubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop

**Ubuntu Mate**
XDG_CONFIG_DIRS=/etc/xdg/xdg-mate:/etc/xdg
DESKTOP_SESSION=mate
XDG_SESSION_DESKTOP=mate
XDG_CURRENT_DESKTOP=MATE
XDG_DATA_DIRS=/usr/share/mate:/usr/share/xfce4:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share
GDMSESSION=mate

**Kubuntu**
XDG_CONFIG_DIRS=/etc/xdg/xdg-plasma:/etc/xdg

**Comment by philipzae** [comment]
@dylanaraps Any reply about my last message
