### ISSUE TITLE
Display adapters/GPU shown in one line for Windows

### ISSUE THREAD

**Issue by zamiur** [dylanaraps/neofetch#1462]
## Description

Hi there, first time submitting an issue.  I am not sure whether this is an issue or not. Anyways, I have neofetch on Windows and whenever I run it, all the information prints out successfully except for the GPU and display adapter, they seem to be printed on the same line. A new feature for neofetch on Windows that could solve this issue is printing each seperate display adapter/gpu onto a new line like how neofetch does on linux.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

Yes.

#### Neofetch version
7.0.0
## Screenshot
![image](https://user-images.githubusercontent.com/20298544/82198150-6ce67300-98eb-11ea-9daa-e2a3d6e37ebe.png)
## Config file

I do not have one

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

The contents of neofetchlog are in this pastebin.
https://pastebin.com/4Q5dYiYu
Alternatively, I have made a copy on gist if the pastebin expires
https://gist.github.com/zamiur/ebc6d88682bef1c7b2bdaf4ad46b7518

**Comment by dylanaraps** [comment]
Please try the latest commit.
