### ISSUE TITLE
Add support for winget package manager

### ISSUE THREAD

**Issue by juchom** [dylanaraps/neofetch#1465]
## Description

Microsoft demoed the new winget package manager for windows at the Build this year. It would be great have it supported.

More information [here ](https://docs.microsoft.com/en-us/windows/package-manager/)

Thanks

**Comment by dylanaraps** [comment]
This isn't even a package manager (at least not yet). There's no support for listing installed packages for example: https://github.com/microsoft/winget-cli/issues/119

Closing this. Feel free to open an issue when listing packages is supported.
