### ISSUE TITLE
[Enhancement] Prettier Windows 10 ascii art

### ISSUE THREAD

**Issue by HotDog640** [dylanaraps/neofetch#1466]
## Description
I have made 4 different versions of the Windows 10 ASCII logo to possibly replace the current one. They are as follows:
#### "M"
```shell
            set_colors 6 7
            read -rd '' ascii_data <<'EOF'
${c1}                            .oodMMMM
                   .oodMMMMMMMMMMMMM
       ..oodMMM  MMMMMMMMMMMMMMMMMMM
 oodMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 MMMMMMMMMMMMMM  MMMMMMMMMMMMMMMMMMM
 `^^^^^^MMMMMMM  MMMMMMMMMMMMMMMMMMM
       ````^^^^  ^^MMMMMMMMMMMMMMMMM
                      ````^^^^^^MMMM
EOF
```
#### "M" Coloured
```shell
set_colors 6 7 2 1 3
            read -rd '' ascii_data <<'EOF'
${c3}                            .oodMMMM
                   .oodMMMMMMMMMMMMM
${c4}       ..oodMMM${c3}  MMMMMMMMMMMMMMMMMMM
${c4} oodMMMMMMMMMMM${c3}  MMMMMMMMMMMMMMMMMMM
${c4} MMMMMMMMMMMMMM${c3}  MMMMMMMMMMMMMMMMMMM
${c4} MMMMMMMMMMMMMM${c3}  MMMMMMMMMMMMMMMMMMM
${c4} MMMMMMMMMMMMMM${c3}  MMMMMMMMMMMMMMMMMMM
${c4} MMMMMMMMMMMMMM${c3}  MMMMMMMMMMMMMMMMMMM
${c4} MMMMMMMMMMMMMM${c3}  MMMMMMMMMMMMMMMMMMM
					    
${c1} MMMMMMMMMMMMMM${c5}  MMMMMMMMMMMMMMMMMMM
${c1} MMMMMMMMMMMMMM${c5}  MMMMMMMMMMMMMMMMMMM
${c1} MMMMMMMMMMMMMM${c5}  MMMMMMMMMMMMMMMMMMM
${c1} MMMMMMMMMMMMMM${c5}  MMMMMMMMMMMMMMMMMMM
${c1} MMMMMMMMMMMMMM${c5}  MMMMMMMMMMMMMMMMMMM
${c1} `^^^^^^MMMMMMM${c5}  MMMMMMMMMMMMMMMMMMM
${c1}       ````^^^^${c5}  ^^MMMMMMMMMMMMMMMMM
                      ````^^^^^^MMMM
EOF
```
#### "L"
```shell
            set_colors 6 7
            read -rd '' ascii_data <<'EOF'
${c1}                           ....iilll
                 ....iilllllllllllll
     ....iillll  lllllllllllllllllll
 iillllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 llllllllllllll  lllllllllllllllllll
 `^^^^^^lllllll  lllllllllllllllllll
       ````^^^^  ^^lllllllllllllllll
                      ````^^^^^^llll
EOF
```
#### "L" Coloured
```shell
            set_colors 6 7 2 1 3
            read -rd '' ascii_data <<'EOF'
${c3}                           ....iilll
                 ....iilllllllllllll
${c4}     ....iillll${c3}  lllllllllllllllllll
${c4} iillllllllllll${c3}  lllllllllllllllllll
${c4} llllllllllllll${c3}  lllllllllllllllllll
${c4} llllllllllllll${c3}  lllllllllllllllllll
${c4} llllllllllllll${c3}  lllllllllllllllllll
${c4} llllllllllllll${c3}  lllllllllllllllllll
${c4} llllllllllllll${c3}  lllllllllllllllllll

${c1} llllllllllllll${c5}  lllllllllllllllllll
${c1} llllllllllllll${c5}  lllllllllllllllllll
${c1} llllllllllllll${c5}  lllllllllllllllllll
${c1} llllllllllllll${c5}  lllllllllllllllllll
${c1} llllllllllllll${c5}  lllllllllllllllllll
${c1} `^^^^^^lllllll${c5}  lllllllllllllllllll
${c1}       ````^^^^${c5}  ^^lllllllllllllllll
                      ````^^^^^^llll
EOF
```
### Comparison:
![Screenshot](https://user-images.githubusercontent.com/17883314/82951389-f60e4180-9f9e-11ea-875a-f8d470b9e9a2.png)
If you want to use a coloured one, I'd probably recommend the "M" coloured. The "L" coloured would also be fine. Without colour, I'd probably recommend the "L" one. The current ASCII art is the last one in the screenshot.
###### Also in case you are curious, I am using Git Bash on Windows 10.

**Comment by Allakazan** [comment]
Hello ! How could i implement that in my neofetch config file ? 😃

**Comment by Allakazan** [comment]
nvm i figured out, just created the ascii file and put into the config.
Thanks for your work 😄 

https://github.com/dylanaraps/neofetch/wiki/Custom-Ascii-art-file-format

**Comment by Im-catfood** [comment]
How did you chose your set_colors #'s, and is it how you wanted it to look?
Working on a custom Linux ascii, got it 95% done, but without hex-color codes, I've been struck trying to fix last 2 colors, without also ruining terminal colors. Understand Windows bash is going to pull things differently, guess that's why I'm curious how you picked the colors numbers, maybe help me think outside the box to finish mine...

**Comment by HotDog640** [comment]
That color box at the bottom of the spec list are all the colors you can access in order. The top row is from 0 (black) to 7 (light grey), and the bottom row is from 8 (dark grey) to 15 (white).

The keys in the spec list (OS, Host, etc.) are set to the first set_colors color, and the text color is set to the second set_colors value. You can access these colors in the ascii art by using `${1}`, `${2}`, etc. Let's say you have the colors `6 7 2 1 3`, you would access color 6 with `${1}`, and color 3 with `${5}`, since that's the order you put them in set_colors.

Hope that helps.

**Comment by dylanaraps** [comment]
Current logo is fine. Users are free to use logos from this thread of course.
