### ISSUE TITLE
Neofetch do not provide nice output when there is multiple CPU in system

### ISSUE THREAD

**Issue by Nalorokk** [dylanaraps/neofetch#1467]
## Description

Neofetch provides such output on dual xeon:

CPU: Intel Xeon E5405 (8) @ 2.000GHz

I think it would be a lot cleaner if it would be instead like this:

CPU: 2 x Intel Xeon E5405 (4) @ 2.000GHz

#### Neofetch version
7.0

**Comment by dylanaraps** [comment]
Reopen this issue with a verbose log attached.
