### ISSUE TITLE
Feature request. Running on xorg or wayland and show gnome version

### ISSUE THREAD

**Issue by wallacehermano** [dylanaraps/neofetch#1471]
Description
Is there any chance to implement in future version display Gnome version and it's running on Wayland or Xorg?

Neofetch version: 7.0.0-1.1
Config file: https://pastebin.com/S5L93Z5U
Verbose log: https://pastebin.com/vEnup3hq

Screenshot:
![Screenshot from 2020-06-05 08-06-35](https://user-images.githubusercontent.com/7162381/83869807-849f6300-a703-11ea-87da-df1e6f903a2e.png)

**Comment by arisinfenix** [comment]
Displaying the version is disabled in your config, change it to `de_version="on"`.

Regarding Wayland I'm not sure if @dylanaraps would like to implement it.

**Comment by arisinfenix** [comment]
Adding ``[[ $WAYLAND_DISPLAY ]] && de="$de (Wayland)"`` at the end of the `get_de()` function (right above the `run_de=1` line) should do it.

**Comment by CiscoDeTours** [comment]
Three simple steps are needed to show the display server:

**1.** Open the configuration file

~~~
sudo nano ~/.config/neofetch/config.conf
~~~

**2.** Paste this between info lines

~~~
prin Session "$XDG_SESSION_TYPE"
~~~

**3.** Save changes.

**Comment by PlasmaMiasma** [comment]
I would suggest something like this above `de_run=1`:

```
case $XDG_SESSION_TYPE in
    wayland*) de="$de ($WAYLAND_DISPLAY)" ;;
    x11*)     de="$de ($DISPLAY)"
esac
```

However, it might be preferable to add a separate "DS" (display server) info line, with output resembling the following:
**DS**: Wayland (wayland-0)
**DS**: Xorg (:0)
