### ISSUE TITLE
Neofetch not displaying on Manjaro

### ISSUE THREAD

**Issue by FrenzyExists** [dylanaraps/neofetch#1476]
## Description
So, after making a ricing on my manjaro laptop I went to use neofetch to display an image. This is what I've typed this
`neofetch --w3m ~/Pictures/japan_manjaro.jpg`

But I ended with this: 
![image](https://user-images.githubusercontent.com/47986470/83982682-89783880-a8f6-11ea-858e-f1dc4ef886e8.png)

I checked if it had to do with w3m or any broken package, but w3m works fine:

![image](https://user-images.githubusercontent.com/47986470/83982702-af9dd880-a8f6-11ea-95f7-a65f6710ba11.png)

Same thing occurs with catimg and with feh. I'm using terminator here, but on kitty occurs the same. 

#### Neofetch version
7.0.0.0

## Config file
here's my config file, is pretty much the regular one, located in `~/.config/neofetch`
https://pastebin.com/XHViPiaA

## Verbose log
This is what I got from the logs:
![image](https://user-images.githubusercontent.com/47986470/83982789-5edaaf80-a8f7-11ea-8d09-79da9335474b.png)

Not sure why I'm getting this instead of an extensive log file

Any idea what could be wrong?

I've uninstall it and reinstall it just in case, and compared the config files with the one on my other laptop where neofetch works just fine and still can't grasp what is wrong

**Comment by OtakuLinux** [comment]
try full path

**Comment by dylanaraps** [comment]
You need to upload the verbose log. Otherwise I cannot help you.
