### ISSUE TITLE
#1237 Still present in 7.0.0

### ISSUE THREAD

**Issue by atheistd** [dylanaraps/neofetch#1480]
As from #1237 , I am still encountering this issue with `neofetch | lolcat`.

#### [Verbose log](https://pastebin.com/9dtM0PXV)

**Comment by atheistd** [comment]
I forgot the log of `neofetch -vv 2> neofetchloglolcat | lolcat`. It can be found [here](https://pastebin.com/hWiWMFfw).

**Comment by dylanaraps** [comment]
Is your lolcat up to date?

**Comment by atheistd** [comment]
Yeah. I'm on `100.0.1` which is exactly what is available [on GitHub](https://github.com/busyloop/lolcat/blob/master/lib/lolcat/version.rb).

**Comment by arisinfenix** [comment]
Are you sure you are running `100.0.1`? It should work with recent lolcat versions, see https://github.com/busyloop/lolcat/issues/94

I can confirm it works.

lolcat 42.0.99

![Untitled](https://user-images.githubusercontent.com/40315484/90518104-9b801e00-e166-11ea-87f4-776b7f648930.png)

lolcat 100.0.1

![Untitled2](https://user-images.githubusercontent.com/40315484/90518146-a76be000-e166-11ea-8872-f1c7460309ae.png)

**Comment by LinuxOnTheDesktop** [comment]
Let me contribute to rectifying this dreadful situation. :)

To get a version of lolcat that works with neofetch, do the following (at least if you use Debian or Ubuntu or an Ubuntu-based distro).

```
sudo apt remove lolcat -y
wget https://github.com/busyloop/lolcat/archive/master.zip
unzip master.zip
cd lolcat-master/bin
sudo gem install lolcat
```
