### ISSUE TITLE
[Documentation] Could a new link, like "Usage", be added onto the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [dylanaraps/neofetch#1485]
Hey there,

I found this by slackware changelog so I guess this must be quite popular. I have no experience
with it yet but I managed to install it - ok, that was not so hard on Linux. :-)

But it seems it also runs on HaikuOS which is cool.

Anyway: The main links right now are:

"More: [Dependencies] [Installation] [Wiki]"

Would it be possible to add a short new entry to this, like:

"More: [Dependencies] [Installation] [Usage][Wiki]"

or

"More: [Dependencies] [Installation] [Examples][Wiki]"

Or something like that? Just to quickly show a few examples and use cases. I assume
it is somewhere on the wiki but I am a lazy person and love clickable hyperlinks so
this is why I add this feature request. Feel free to close this issue at any moment in
time though.

**Comment by dylanaraps** [comment]
`--help`, `man neofetch` and `~/.config/neofetch/config.conf`. Basic usage is simply... `neofetch`.
