### ISSUE TITLE
Various parts broken on macOS 11 (Big Sur) Developer Preview

### ISSUE THREAD

**Issue by Seshpenguin** [dylanaraps/neofetch#1486]
## Description

Various parts of neofetch do not work correctly on macOS Big Sur, including:

- OS (displays "unknown")
- Uptime
- WM
- Memory

This occurs on the master branch.

#### Neofetch version
7.0.0

## Screenshot
<img width="810" alt="Screen Shot 2020-06-23 at 6 16 57 PM" src="https://user-images.githubusercontent.com/6313946/85471269-33ee8d80-b57e-11ea-8be4-cdf1484a4062.png">

## Config file
Default from Homebrew

## Verbose log
https://pastebin.com/LFhb00Su

**Comment by slinkouswasalreadytaken** [comment]
Can confirm this, though it's a bit different on my end: 
![Screen Shot 2020-06-29 at 2 30 55 PM](https://user-images.githubusercontent.com/53449377/86042632-6fbda300-ba15-11ea-8b3f-10bd768643e2.png)

**Comment by omBratteng** [comment]
Same issue, and it opens the xquartz app and doesn't close it.

**Comment by omBratteng** [comment]
@dylanaraps tested your commit on Big Sur Beta-2, and it works fine. And xquartz doesn't open.

**Comment by gottabeleGIT** [comment]
Could you push a release to include this fix?

**Comment by omBratteng** [comment]
@gottabeleGIT if you have installed it via brew, you can reinstall it but use the --HEAD flag to get the latest version. Or you could build it yourself

**Comment by gottabeleGIT** [comment]
That is what I have done in the interim, but thanks anyway for the tip :)

**Comment by gottabeleGIT** [comment]
Finally, seems to be resolved with release 7.1.0! Thanks @dylanaraps and @stevejkang :D
