### ISSUE TITLE
Why do the Ubuntu repos have a very old version?

### ISSUE THREAD

**Issue by rodrigograca31** [dylanaraps/neofetch#1488]
## Description

This is mostly just a question but why isn't the latest version of neofetch available on the default Ubuntu repos?
Why do we need to add the ppa...?
https://launchpad.net/~dawidd0811/+archive/ubuntu/neofetch

Can we get the version on the default repos updated, please?
Is there anything I can help within that regard?

After adding the ppa:
![image](https://user-images.githubusercontent.com/1134310/85854170-cb84f380-b7ab-11ea-8709-b6b2e83978e3.png)

**Comment by dylanaraps** [comment]
Ask whoever maintains the Ubuntu package.

**Comment by dawidd6** [comment]
https://askubuntu.com/questions/151283/why-dont-the-ubuntu-repositories-have-the-latest-versions-of-software
