### ISSUE TITLE
Pictures in different terminals

### ISSUE THREAD

**Issue by noaccOS** [dylanaraps/neofetch#1492]
## Description

It would be nice to have the option to select different backends for pictures rendering, or have different config files for different terminals.

At the moment I'm using Kitty with its backend, and whenever I open another terminal I experience one of these two behaviors:
1. It just launches but without showing pictures
2. I get a `Checking for graphics (10.0s max. wait)...` and after 10 seconds I have the same as number 1.

**Comment by dylanaraps** [comment]
This can be done externally to neofetch via environment variables and `neofetch --config`. This could even be done via the neofetch configuration file, it is a shell script after all. I don't feel like the complexity of this feature is worth small benefit it brings. Thanks for opening this issue.
