### ISSUE TITLE
GTK theme not being detected

### ISSUE THREAD

**Issue by ThurnisH41ey** [dylanaraps/neofetch#150]
I'm using Paper for my GTK theme and icons, and neofetch still displays Adwaita. All I've changed is the /usr/share/gtk-{2.0,3.0}/{gtkrc,settings.ini} files and my applications all use Paper, but neofetch isn't picking it up.

**Comment by iandrewt** [comment]
What is the output of these four commands?

`grep "^[^#]*$name" "$HOME/.gtkrc-2.0"`
`grep "^[^#]*$name" "/etc/gtk-2.0/gtkrc"`
`grep "^[^#]*$name" "$HOME/.config/gtk-3.0/settings.ini"`
`grep "^[^#]*$name" "/etc/gtk-3.0/settings.ini"`

**Comment by ThurnisH41ey** [comment]
All "No such file or directory"

**Comment by dylanaraps** [comment]
Please give me more info about your system.

- What DE are you using?
- What Linux distro are you using?
- Did this work on previous versions of neofetch?

**Comment by ThurnisH41ey** [comment]
bspwm, Arch, and I only just downloaded it so I'm not sure. iandrewt figured it out though - I guess neofetch doesn't parse /usr/share/gtk-2.0/gtkrc or /usr/share/gtk-3.0/settings.ini, which were the only files I made my theme changes in.

**Comment by dylanaraps** [comment]
I'll add a fallback to those locations when I get home, this will fix the issue.

**Comment by iandrewt** [comment]
@ThurnisH41ey Can you test #151, should work now.

**Comment by dylanaraps** [comment]
#151 fixes this issue, thanks for reporting it!
