### ISSUE TITLE
When using GDM WM identifies as Mutter regardless of the DE

### ISSUE THREAD

**Issue by AlanGriffiths** [dylanaraps/neofetch#1500]
## Description

I have multiple DEs installed and select one at login. Regardless of which I select, the WM is identified as Mutter.

#### Neofetch version

7.0.0 - but also happens on master

## Screenshot
```plain
$ neofetch
            .-/+oossssoo+/-.               alan@Octopull-PROX15-20 
        `:+ssssssssssssssssss+:`           ----------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: PROX15 Standard 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-40-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 days, 38 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2505 (dpkg), 22 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.16 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: egmde 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Adwaita [GTK3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Adwaita [GTK3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-9750H (12) @ 4.500GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel UHD Graphics 630 
      -+sssssssssssssssssyyyssss+-         GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
        `:+ssssssssssssssssss+:`           Memory: 1643MiB / 31973MiB 
            .-/+oossssoo+/-.
```                                                                   

The problem appears to be that `ps -e` is reporting on processes that don't belong to the current session, in particular:
```plain
$ ps -ef | grep gnome-shell$
gdm       304886  304804  0 10:21 ?        00:00:02 /usr/bin/gnome-shell
```
I suspect this could also be a problem if multiple users are logged into different DEs.

**Comment by arisinfenix** [comment]
Does it happen on Wayland or X11? Or on both?

**Comment by AlanGriffiths** [comment]
> Does it happen on Wayland or X11? Or on both?

What do you mean? Let me give a concrete example:

1. Install the egmde snap:
```plain
snap install --classic --edge egmde
```
2. Log out and select "egmde" from the greeter. (This supports both Wayland and X11.)

3. Start a terminal (`Ctrl-Alt-T`) and run `neofetch`.

You can see the same installing Weston, but you can clean up the above with just `snap remove --purge egmde`

**Comment by arisinfenix** [comment]
I asked because if `$WAYLAND` variable is set, neofetch greps the WM from `ps -e` output and on X11 the `_NET_WM_NAME`  property from `xprop` is used. So it would be helpful to know if only `ps -e` is the problem or also ` _NET_WM_NAME`. ;)

**Comment by AlanGriffiths** [comment]
In the cases I tried `WAYLAND_DISPLAY` was set.

If I run `env -u WAYLAND_DISPLAY neofetch` I get "WM: Mir XWM", which is good.

BTW You should be aware that `WAYLAND_DISPLAY` isn't a reliable way to detect Wayland, as Wayland backends default to connecting to `$XDG_RUNTIME_DIR/wayland-0` when it isn't set. It is better to test whether `$XDG_RUNTIME_DIR/${WAYLAND_DISPLAY:-wayland-0}` exists.

**Comment by arisinfenix** [comment]
I was not able to reproduce this on a fresh Ubuntu 20.04.1 installation.

1. installed Ubuntu

2. installed egmde as suggested `snap install --classic --edge egmde`

3. log out, log in into egmde

No WM is detected since in the `ps -e` output there is no entry neofetch is grepping for.
Especially there is no line with `gdm ... /usr/bin/gnome-shell` as in your first post.

**Comment by AlanGriffiths** [comment]
> I was not able to reproduce this on a fresh Ubuntu 20.04.1 installation.

Yes, same for me. There must have been something more I was doing when I hit this: will investigate.

**Comment by AlanGriffiths** [comment]
I've not worked out exactly what scenario lead to the initial description, but if I sign into a GNOME session and then switch to a test user using egmde I see something very similar.

Here's a (rather raw) hack that avoids the problem:
```plain
<         wm=$(ps "${ps_flags[@]}" | grep -m 1 -o -F \
---
>         wm=$(fuser -v "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY:-wayland-0}" 2>&1| grep -m 1 -o -F \
```

But it is probably right to get the compositor directly with something like:
```plain
fuser -v "${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY:-wayland-0}" 2>&1 | sed -rne "s/^\s+$USER.* ([^ ]*$)/\1/p"
```
