### ISSUE TITLE
Wrong Distro. Showing Arch Linux instead of Artix Linux

### ISSUE THREAD

**Issue by ZN0N15** [dylanaraps/neofetch#1502]
Showing Arch Linux instead of Artix Linux. 
It was working fine(Was showing Artix) until I installed; bspwm, lightdm-webkit2-greeter, lightdm-webkit-theme-aether and now Its showing as Arch Linux.

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

[neofetchlog](https://pastebin.com/Jrpkc4KL)

**Comment by dylanaraps** [comment]
The `lsb_release` command is outputting "Arch Linux". This is not a bug. Your distribution is not modifying this package to correctly report the distribution name. More information can be found at the following two links.

- https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linux-neofetch-reports-inaccurate-distro-name
- https://github.com/dylanaraps/pfetch/blob/master/pfetch#L131-L155

Thanks for opening this issue.
