### ISSUE TITLE
Terminal font detection fails

### ISSUE THREAD

**Issue by cinerea0** [dylanaraps/neofetch#1503]
## Description

Neofetch fails to detect my terminal font.

- [X] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.0.0

## Screenshot
![neofetch](https://user-images.githubusercontent.com/49368915/87265753-1f355380-c4b3-11ea-88fe-9958b633c703.png)

## Config file
neofetch config file: https://gist.github.com/cinerea0/ec6e6c92d5ad21411ad33f801c6a5b9e
alacritty config file: https://gist.github.com/cinerea0/d2dcfeb1c6bfb2df4b2104cab947de82

## Verbose log
https://gist.github.com/cinerea0/56e8c737c42e313a48e2ddb4e920d4b8

**Comment by dylanaraps** [comment]
Send your alacritty config file. :+1:

**Comment by cinerea0** [comment]
I've listed it under the config file section.

**Comment by arisinfenix** [comment]
@cinerea0 can you test https://github.com/arisinfenix/neofetch/commit/aac6f6530ef8940691390af9762a63b998359c9e ? It should solve the Issue.
