### ISSUE TITLE
neofetch using 90-100% of the CPU for ~30sec while detecting the CPU

### ISSUE THREAD

**Issue by deadda7a** [dylanaraps/neofetch#1504]
## Description

Hello,
sometimes (not always), while starting up neofetch it uses up 100% of the CPU, and two times it even crashed my PC (lol). I think this is happening at the point where it detects my CPU, because "WM" is the last thing displayed before it hangs, and in my config this is before the CPU. Since I am using zsh I can confirm this: `./neofetch  0.41s user 16.10s system 93% cpu 17.598 total` (this time it was faster, usually its about 30sec)

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.0.0

## Screenshot
n/a

## Config file
https://pastebin.com/GN5Dyrcp

## Verbose log
https://pastebin.com/BLgMZDF3 (Public IP redacted)

**Comment by dylanaraps** [comment]
Can you reproduce this with `--disable cpu`?

**Comment by deadda7a** [comment]
I will try when I can reproduce it next time! As I said, it doesn't always happen, but when it happens, it happens the next times too after that. I will also run a memtest over night today, just to be sure its not that..

**Comment by deadda7a** [comment]
As this stopped happening (it would have happened multiple times if it was following the old pattern), I am closing this issue. Probably this was not a bug in neofetch at all but only exposed by it.

**Comment by deadda7a** [comment]
Well, its happening again :( When i use the `--disable cpu` flag, it happens after the Resolution detection.
`neofetch --disable cpu  0.40s user 16.06s system 99% cpu 16.497 total`

**Comment by dylanaraps** [comment]
Not sure if this is pastebin but the config file you have uploaded contains Windows line endings, etc as well as a syntax error (missing end quote on last line).

**Comment by dylanaraps** [comment]
Can you reproduce this with `--config off`?

**Comment by deadda7a** [comment]
That's pastebin. My local file has "normal" UNIX line endings, and the missing end quote got lost while copy & paste!

**Comment by dylanaraps** [comment]
Closing as stale. No one else can reproduce either.
