### ISSUE TITLE
Show correct ubuntu flavor

### ISSUE THREAD

**Issue by philipzae** [dylanaraps/neofetch#1505]
There are different environment variables that can be used to correctly identify which ubuntu flavor is being used, primarily XDG_CONFIG_DIRS.

### Kubuntu
XDG_CONFIG_DIRS=/etc/xdg/**xdg-plasma**:/etc/xdg

### Ubuntu Mate
XDG_CONFIG_DIRS=/etc/xdg/**xdg-mate**:/etc/xdg
DESKTOP_SESSION=mate
XDG_SESSION_DESKTOP=mate
XDG_CURRENT_DESKTOP=MATE
XDG_DATA_DIRS=**/usr/share/mate**:/usr/share/xfce4:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share
GDMSESSION=mate

### Xubuntu
XDG_CONFIG_DIRS=/etc/xdg/**xdg-xubuntu**:/etc/xdg:/etc/xdg
DESKTOP_SESSION=**xubuntu**
XDG_SESSION_DESKTOP=**xubuntu**
XDG_DATA_DIRS=**/usr/share/xubuntu**:/usr/share/xfce4:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share
GDMSESSION=**xubuntu**

### Lubuntu
XDG_CONFIG_DIRS=/etc/xdg/**xdg-Lubuntu**:/etc/xdg:/etc/xdg
DESKTOP_SESSION=**Lubuntu**
XDG_DATA_DIRS=**/usr/share/Lubuntu**:/usr/local/share:/usr/share:/var/lib/snapd/desktop

**Comment by arisinfenix** [comment]
Here is a patch based on your infos. I've tested it only on Kubuntu, since I use it on my netbook.
https://github.com/arisinfenix/neofetch/commit/f47b8b07f7483b7323669a6df1d7cad98766a9e3

@dylanaraps let me know if I should open a PR.

**Comment by philipzae** [comment]
@arisinfenix thanks for the patch. I tested it in Xubuntu and Lubuntu and it worked.

It didn't work in Ubuntu Mate as you'd need to change your code to 'Ubuntu-MATE' rather than 'Ubuntu MATE'.

Please add to your patch detection of ubuntu budgie.
XDG_CONFIG_DIRS=/etc/xdg/**xdg-budgie-desktop**:/etc/xdg
DESKTOP_SESSION=**budgie-desktop**
XDG_SESSION_DESKTOP=**budgie-desktop**
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/**ubuntu-budgie**
XDG_CURRENT_DESKTOP=**Budgie:GNOME**
XDG_DATA_DIRS=/usr/share/**budgie-desktop**:/usr/local/share:/usr/share:/var/lib/snapd/desktop
GDMSESSION=**budgie-desktop**

Possibly also this one for ubuntu cinnamon if the icon is in neofetch.
XDG_CONFIG_DIRS=/etc/xdg/**xdg-cinnamon**:/etc/xdg
**CINNAMON**_VERSION=4.4.8
DESKTOP_SESSION=**cinnamon**
XDG_SESSION_DESKTOP=**cinnamon**
XDG_CURRENT_DESKTOP=**X-Cinnamon**
XDG_DATA_DIRS=/usr/share/gnome:**/usr/share/cinnamon**:/usr/local/share:/usr/share:/var/lib/snapd/desktop
GDMSESSION=**cinnamon**

**Comment by arisinfenix** [comment]
@philipzae thanks for testing. I've updated the patch, it should work now for MATE and Budgie too.
https://github.com/arisinfenix/neofetch/commit/a3cb1285ae4f3989ee9f098417e629a75529c84f

For ubuntu cinnamon there is no ascii logo yet.

Is there a reliable way to detect ubuntu studio? Its default DE is Xfce, but it can also be installed on any other ubuntu flavor. https://ubuntustudio.org/ubuntu-studio-installer

**Comment by philipzae** [comment]
Ubuntu Studio has xdg-ubuntustudio in XDG_CONFIG_DIRS. Using ubuntu-studio-installer doesn't convert a flavor into ubuntu studio, so there is nothing to worry about there. Also the next version of studio will use KDE rather than Xfce.

If the logo for Ubuntu Kylin is available, then detecting it is limited to searching in XDG_GREETER_DATA_DIR for ubuntu-kylin.

**Comment by arisinfenix** [comment]
Thank you for the info. I've opened PR #1507 and tested it with mate, budgie and studio.

**Comment by bdavjones** [comment]
Slightly concerned that this change infers the distro from the currently running DE, i.e. `$XDG_CONFIG_DIRS` - In cases where alternative DEs have been installed, this can give spurious results.

Could we use  `/var/log/installer/media-info` as a primary selection method for Ubuntu distros if present, then failback to the `XDG_CONFIG_DIRS` ?
