### ISSUE TITLE
[feature request] Add system boot time

### ISSUE THREAD

**Issue by haggen88** [dylanaraps/neofetch#1514]
Neofetch is a complete overview of the system features.
In that sense it would be a good idea to add the time required to start the system [system boot-up performance].

For distributions using Systemd:
>systemd-analyze time

**Comment by dylanaraps** [comment]
This is not something I believe is reliably doable. This is something you can start using right now via the config file though!
See: https://github.com/dylanaraps/neofetch/wiki/Customizing-Info

Thanks for opening this issue.
