### ISSUE TITLE
[Feature Request] Add seperate options for IPv4 and IPv6; Also use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by dfuentes87** [dylanaraps/neofetch#1515]
Currently the default site used for getting your public IP, http://ident.me, will return a IPv6 if your ISP provides it (and if your home network has it enabled), otherwise you are provided a IPv4. While it is possible to change the URL used from http://ident.me to http://v4.ident.me to force return a IPv4, it is not possible to have both IPv4 and IPv6 be shown by Neofetch at the same time without having the user make coding changes in several places. I would like to request the ability to show both as separate options, say "public_ipv4" and "public_ipv6", in case users want one or the other or both.

Additionally, I would like to see the URL updated to use HTTPS instead of HTTP, i.e. https://v4.ident.me

**Comment by dfuentes87** [comment]
Not sure if this the best way to do it (there's probably a more complex way which removes the need to duplicate code), but I essentially just renamed all public ip variables/functions to specify ipv4 and then duplicated those for ipv6. For example:

```
    # info "Public IPv4" public_ipv4
    # info "Public IPv6" public_ipv6
```

```
# Website to ping for the public IP
#
# Default: 'https://ident.me'
# Values:  'url'
# Flag:    --ip_host
public_ipv4_host="https://v4.ident.me"

# Website to ping for the public IP
#
# Default: 'https://ident.me'
# Values:  'url'
# Flag:    --ip_host
public_ipv6_host="https://v6.ident.me"
```


![Screen Shot 2020-08-02 at 12 45 15 PM](https://user-images.githubusercontent.com/11722608/89127780-6022f580-d4be-11ea-9258-ff289a4da94b.png)

**Comment by dylanaraps** [comment]
I actually think it's best to drop this feature altogether. I don't think neofetch should be doing network at all. Nothing prevents someone from doing: `prin "Public IPv4" "$(curl .....)"` in their neofetch configuration file after all.

**Comment by dylanaraps** [comment]
Unless this information can somehow be determined locally...

**Comment by dfuentes87** [comment]
Fair enough, I can close out the request as I do not see any way for a client to determine public IPs locally (apart from any craziness that would entail asking the modem/router what it was assigned by the ISP)
