### ISSUE TITLE
Use Hex Color Codes for ASCII art?

### ISSUE THREAD

**Issue by Im-catfood** [dylanaraps/neofetch#1523]
Current Neofetch version (7.0.0)

Trying to make my own "Distro" ASCII art. I have the art code done and matching your format for them. Curious if there is a way to plug in specific Hex Color Codes for it.
I tried to put hex colors directly into the:

`set_colors 16 0 99 1 3 7
            read -rd '' ascii_data <<'EOF'`

section, in place of the "single" digit color numbers you had for all the others, but this just kinda shredded the ascii art and/or broke neofetch when done. 
I tried random set_color numbers, 0-99, make install, neofetch over and over, and got a lot of colors close, but can't find some colors. Was curious what set_colors pulls from to where a small number stands for another color. Like is there somewhere I could force one distro to pull from another color pool? Or, how/where could I find a full list of available colors you are using, rather than trying a million random possibilities just tossing numbers in?

Thanks for your time, 
catfood

*update: changing .Xresources colors or using dkeger presetups can take hex colors from their code/scripts and overwrite neofetch assci colors, but it applies to entire terminal, so end up with terminal font colors I'd rather not have to make distro font correct...

**Comment by dylanaraps** [comment]
Color handling will be overhauled to accept escape sequences, etc. This issue will be handled then. :+1:

**Comment by dylanaraps** [comment]
Note: ASCII logos shipped with neofetch will always be limited to the basic terminal palette to maintain compatibility with everything new and old. Users will be free to use escape sequences, etc to make use of the 256 palette and true color.

**Comment by Im-catfood** [comment]
Thanks dylan. I slowly realized the I guess "dependency tree". All based on terminal limitations, was the limiting factor i did not understand. i will make dkeger Xresource themes that can keep the ascii art more true. Solvable on my end. I appreciate your script, please keep up the good work, regardless if people like my don't understand or question it... You are clearly doing A++ work on a like 8-16bit palate, lol. Thanks, God bless you sir. 

It was interesting to see the weird glitchy colors that came out of changing your color codes up to 999. It won't override a default X setting, but it could weirdly tweak to colors it should not allow in the range. Maybe someone can abuse this "bug" later to make more vibrant terminals :)

**Comment by dylanaraps** [comment]
Going to close this in favor of the more recent #1699
