### ISSUE TITLE
Song info is not retrieved from Audacious

### ISSUE THREAD

**Issue by MaxCorreia** [dylanaraps/neofetch#1524]
## Description

Neofetch displays the status of a song playing, however it does not pick up the information from Audacious as it does other music players (ie. Rhythmbox). I am unable to tell whether this is an issue coming from the end of Neofetch or Audacious (v4.0.4).

- [X] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.0.0 & git
## Screenshot
![screenshot](https://user-images.githubusercontent.com/18178526/89600927-360c6300-d831-11ea-8f4b-d4a3303610cc.png)
## Config file
https://pastebin.com/RpirVzXq
## Verbose log
https://pastebin.com/v01bdWaP

**Comment by arisinfenix** [comment]
This is the relevant part from your log file:
```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.audacious was not provided by any .service files
```
Can you post the output of `qdbus | grep mpris` while audacious is running?

**Comment by arisinfenix** [comment]
I've just tested it with the groovy live CD, and it works as aspected. So it seems it's an issue with your system and not neofetch.

![audacious](https://user-images.githubusercontent.com/40315484/89638480-31d15b80-d8ac-11ea-90de-54491927cc32.png)
