### ISSUE TITLE
Runs super slow on cygwin

### ISSUE THREAD

**Issue by mr-falafel** [dylanaraps/neofetch#1527]
## Description
Not much to say here. Neofetch is slow on cygwin. Time gives me 0m4.208s. This is compared to 0m0.646s on my raspberry pi.
Any ideas?

#### Neofetch version
7.0.0

## Verbose log
https://pastebin.com/Q7jcSjBC

**Comment by dylanaraps** [comment]
Where does it hang in the output? Which line of output takes a long time to appear? Can you reproduce with git master?

**Comment by dylanaraps** [comment]
Also, send your neofetch config.

**Comment by mr-falafel** [comment]
Thanks for the reply!
It doesn't seem to hang in any one place in particular. I could maybe take a screen recording. Would that help?
As for my neofetch config, all I've done is clone this github and ran the neofetch script. I'm not using any flags and haven't touched any config files.

**Comment by dylanaraps** [comment]
I wonder if Cygwin is to blame? I know there's *some* overhead, I didn't think it'd be this bad though.

**Comment by mr-falafel** [comment]
I can't say that I find cygwin slow, generally, but then I also don't generally run complex bash scripts on it. I'd be willing to believe there's a fair bit of overhead in running bash in windows... I was also able to test neofetch in MSYS2, which is based on cygwin I believe. It's similarly slow.

In retrospect, it was probably wrong of me to bring the issue up here, as screenfetch has the same issue. There's a port of screenfetch to C that runs very nicely but I really do prefer neofetch...
Thanks anyway!

**Comment by dylanaraps** [comment]
Support for cygwin/msys2 could be added to `pfetch` (https://github.com/dylanaraps/pfetch). It uses POSIX shell, does less and should be a lot faster.

**Comment by nonetrix** [comment]
Yeah same here it's a lot slower running on my Windows VM compared to my Arch host via ssh even with windows terminal and that uses dx12 to render text so it's not the terminal
