### ISSUE TITLE
Neofetch Taking up space

### ISSUE THREAD

**Issue by veryniceperson** [dylanaraps/neofetch#1532]
Help! I have just tried installing neofetch and my laptop shut down mid download. Now neofetch is taking up space and I can't even use it. I tried using the uninstall command to uninstall neofetch but it doesn't work. How can I remove the files that had been installed?

**Comment by dylanaraps** [comment]
This is the wrong place for this kind of bug. Sounds like you need to contact your distribution's maintainers.
