### ISSUE TITLE
term_font not working in alacritty when using default config (suggested fix)

### ISSUE THREAD

**Issue by PureArtistry** [dylanaraps/neofetch#1534]
Just switched terminal to alacritty, I'm using the default config found [here](https://github.com/alacritty/alacritty/releases/download/v0.5.0/alacritty.yml)
I noticed that it wasn't displaying my terminal font so I did a bit of digging, I took a look at how you were getting the font and tested the command

     awk -F ':|#' '/normal:/ {getline; print}' ~/.config/alacritty/alacritty.yml
        # Font family
        black:   '#0c0301'

this is the relevent bit from my config

    # Font configuration
    font:
      # Normal (roman) font face
      normal:
        # Font family
        #
        # Default:
        #   - (macOS) Menlo
        #   - (Linux/BSD) monospace
        #   - (Windows) Consolas
        family: Iosevka Nerd Font

as you can see, it's finding the comment and then deleting it a couple of lines later leaving $term_font empty.
To fix this I changed line ***3218*** to this

            term_font="$(sed -e '/^\s*#.*$/d' "${confs[0]}" | awk -F ':|#' '/normal:/ {getline; print}')"

using sed to remove all the comments before piping into awk, I imagine you know a better solution though

EDIT: should have looked a little closer at the issues list before posting this, this is the same issue as #1503 - really should have posted this in there, sorry

**Comment by arisinfenix** [comment]
This should also work.
```bash
awk '/normal:/ {while ($0!~ /family:/) {getline} print}'
```
You can check it out here https://github.com/arisinfenix/neofetch/commit/aac6f6530ef8940691390af9762a63b998359c9e
Does it solve the issue?

**Comment by PureArtistry** [comment]
this doesn't work for me, awk does not exit

**Comment by arisinfenix** [comment]
What exactly have you tried?

**Comment by dylanaraps** [comment]
I guess they ran the command as-is rather than inserting it into the right place in neofetch or giving it a file as input. So awk was waiting over stdin.

**Comment by arisinfenix** [comment]
That was my guess too. ;)

**Comment by arisinfenix** [comment]
Slightly simplified the awk command: https://github.com/arisinfenix/neofetch/commit/cc9025bdf10aae45daa120a3f8c9b6f6c047b966

**Comment by PureArtistry** [comment]
Sorry I took a while to get back, I edited the correct line

I changed 3218 from

`term_font="$(sed -e '/^\s*#.*$/d' "${confs[0]}" | awk -F ':|#' '/normal:/ {getline; print}')"`

to

`term_font="$(awk '/normal:/ {while ($0!~ /family:/) {getline} print}' "${confs[0]}")"`

when running neofetch it gets to where it's supposed to display the term_font and hangs
![scrot_20200817-124546](https://user-images.githubusercontent.com/53883649/90393242-4241bd00-e088-11ea-8f68-a4b034991847.png)

running the command in a terminal outputs

12:53:28 in ~
 awk '/normal:/ {while ($0!~ /family:/) {getline} print}' ~/.config/alacritty/alacritty.yml
    family: Iosevka Nerd Font

but awk doesn't exit, same thing with the revised version. Am I doing something wrong?

**Comment by arisinfenix** [comment]
Thanks. Hm... can you show your complete `~/.config/alacritty/alacritty.yml`?

**Comment by PureArtistry** [comment]
[alacritty.yml.txt](https://github.com/dylanaraps/neofetch/files/5084245/alacritty.yml.txt)

**Comment by arisinfenix** [comment]
Try https://github.com/arisinfenix/neofetch/commit/32c49b50425cfaf559b4565e6cb149dc72fcbc2a

**Comment by PureArtistry** [comment]
![scrot_20200817-164152](https://user-images.githubusercontent.com/53883649/90415288-cad05580-e0a8-11ea-9762-5171477ad128.png)

works perfect, thanks.
