### ISSUE TITLE
Neofetch showing Linux(Unknown) instead of Arch Linux 

### ISSUE THREAD

**Issue by Petricu** [dylanaraps/neofetch#1544]
## Description
Using the repo version of the app, It shows just Linux(Unknown) and an ASCII art of Tux instead of the Arch logo.
If you're suggesting a new feature then just a description will suffice.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.1.0
## Screenshot
![image](https://user-images.githubusercontent.com/49921909/91229451-88ef8100-e732-11ea-9ea8-5308997deda1.png)

## Config file

https://pastebin.com/rUfZ8qvS

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

https://pastebin.com/UqDXnxWQ

**Comment by dylanaraps** [comment]
Output of `cat /etc/os-release` and `lsb_release -si`?

**Comment by Petricu** [comment]
Output of ```cat /etc/os-release```:

```NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

```lsb_release -si``` shows no output

**Comment by dylanaraps** [comment]
Your issue is `lsb_release` being seemingly non-functional.

**Comment by Petricu** [comment]
Yes, it was corrupted. Thanks
