### ISSUE TITLE
GPU not displayed

### ISSUE THREAD

**Issue by something12356** [dylanaraps/neofetch#1545]
## Description

Neofetch doesn't display what GPU I'm using, it just says it's an nvidia device.

- [x] Does this issue still occur in the master branch?

**Comment by dylanaraps** [comment]
Could be related to: https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linuxfreebsd-why-doesnt-getgpu-show-my-exact-video-card-model

**Comment by something12356** [comment]
The fix suggested there worked, thank you!
