### ISSUE TITLE
I think there should be a gallery of sorts on this github page of what the ASCII art for each distro is

### ISSUE THREAD

**Issue by Cyne-wulf** [dylanaraps/neofetch#1546]
## Description
I've spent a whole lot of time looking around reddit and google for some of the more obscure distro's art and only just found the art buried a couple thousand lines down in the source code without color. I don't think it would be too hard to create a page where all the artwork is fully rendered. That's all.

**Comment by dylanaraps** [comment]
Use `--ascii_distro <name>`. The configuration file contains a full list of distributions. Will leave this exercise up to the user. Art is meant to be auto detected anyway. Thanks for opening this issue.
