### ISSUE TITLE
Wiki updates for iOS/iPadOS Installation

### ISSUE THREAD

**Issue by Diatrus** [dylanaraps/neofetch#1548]
## Description

If you're suggesting a new feature then just a description will suffice.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

This issue is related to the wiki and not the actual program, so the above information should be irrelevant. I run one of the two main Jailbroken iOS bootstrap repositories, Procursus, and include an always up-to-date neofetch on said repo.

I made a quick git patch for the wiki to describe:
[0001-Document-up-to-date-neofetch-from-the-Procursus-Repo.patch.zip](https://github.com/dylanaraps/neofetch/files/5147618/0001-Document-up-to-date-neofetch-from-the-Procursus-Repo.patch.zip)

Cheers!

**Comment by dylanaraps** [comment]
I've opened the WIki up to everyone again. Please make the required changes. Wiki was closed a few days ago due to vandalism by a user.
