### ISSUE TITLE
Neofetch Custom Image Not Displaying

### ISSUE THREAD

**Issue by cykadash** [dylanaraps/neofetch#1553]
## Description

The image I put in the "image_source" part of the config file won't show up and it instead shows the ascii. I have the "image_backend" set to w3m.

- [ ] Does this issue still occur in the master branch? Yes

## Screenshot
![2020-09-10-194410_1920x1080_scrot](https://user-images.githubusercontent.com/44590571/92826162-626e4e80-f39e-11ea-80d4-ce7dda8a0e76.jpg)

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/neofetch/issues/1392
