### ISSUE TITLE
Support for HarmonyOS 2.0

### ISSUE THREAD

**Issue by WakemanCK** [dylanaraps/neofetch#1554]
## Description

Huawei lauched its HarmonyOS 2.0 on 10 Sep. Please add support for it. Thanks!

**Comment by nmcain** [comment]
Do the coreutils even work on harmony v2?

**Comment by WakemanCK** [comment]
You are right. Actually it is probably too early to ask for this.

Right now, Android apps cannot be run on HarmonyOS 2.0. Huawei says that they will release a tool that helps developers to convert Android apps to HarmonyOS apps. Maybe I shall come back when they release this tool.
