### ISSUE TITLE
Lots of line breaks when running functions async

### ISSUE THREAD

**Issue by LelouBil** [dylanaraps/neofetch#1555]
## Description

Using neofetch on windows with git bash and all/some functions running async produces one extra newline for each function

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version

bfbefc7f6bacf3016a973e8c874b2346fae539e1 and https://github.com/dylanaraps/neofetch/releases/tag/7.1.0

## Screenshot

Whith all functions async
![image](https://user-images.githubusercontent.com/13931833/93182711-4e2da700-f73a-11ea-9178-b6a50c5a7e1b.png)
With default configuration
![image](https://user-images.githubusercontent.com/13931833/93182816-6e5d6600-f73a-11ea-9580-81f54e80d36c.png)

## Config file
https://gist.github.com/LelouBil/54b4419e8d7d7ad9b4f654599011cceb

## Verbose log
[neofetch.log](https://github.com/dylanaraps/neofetch/files/5223359/neofetch.log)

**Comment by dylanaraps** [comment]
Not sure if there's anything I can do about this. Running stuff async is more of a cool gimmick than anything officially supported (it'd be the default otherwise).
