### ISSUE TITLE
uptime_shorthand=off and uptime_shorthand=on display the same thing.

### ISSUE THREAD

**Issue by ShroomKing** [dylanaraps/neofetch#1563]
## Description
If I understand correctly when setting uptime_shorthand=off "mins" is supposed to display as "minutes".

Just something I noticed while configuring.

- [X] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Master-f74746d

## Screenshot
![ScreenShot 2020-09-24 at 8 35 22 PM](https://user-images.githubusercontent.com/26014865/94185463-9882f680-fea5-11ea-8855-75c1e2c5bb8e.png)

## Config file
https://pastebin.com/MrUXaLjs

## Verbose log
https://pastebin.com/E7GwsckT

**Comment by A-725-K** [comment]
I have tested it and I can confirm the bug you have reported. I think I'm able to fix it and send a pull request as soon as possible if it is ok :smile:

**Comment by ShroomKing** [comment]
That'd be great! I'm sure it's okay

**Comment by arisinfenix** [comment]
This should fix it https://github.com/arisinfenix/neofetch/commit/3c1b20bc42f263d4c67d507b1e16b89d82110440

@A-725-K if you don't mind I could open a PR.

**Comment by ShroomKing** [comment]
> This should fix it [arisinfenix@3c1b20b](https://github.com/arisinfenix/neofetch/commit/3c1b20bc42f263d4c67d507b1e16b89d82110440)
Yep, that works.

**Comment by arisinfenix** [comment]
Just opened #1564 with a better fix.

**Comment by A-725-K** [comment]
That's ok @arisinfenix :wink: I hope to contribute more in the future :grinning:

**Comment by ShroomKing** [comment]
fixed with #1564
