### ISSUE TITLE
catimg backend always falls back to ASCII

### ISSUE THREAD

**Issue by j-james** [dylanaraps/neofetch#1569]
The `--catimg` backend (from both `--catimg` and `--backend catimg` doesn't seem to be working on XFCE. The similar `--chafa` backend works fine. I've attached `-vv` logs below, but nothing really stood out in a diff - it looks like the `--catimg` backend thinks that it's `--ascii`. It's reproducible without a config file.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

```
teal@endeavour 
-------------- 
OS: EndeavourOS Linux x86_64 
Kernel: 5.8.12-arch1-1 
Shell: bash 5.0.18 
DE: Xfce 4.14 
WM: Xfwm4 
Terminal: xfce4-terminal 
Neofetch: 7.1.0 
```

https://gist.github.com/j-james/4c2500d379eaef25bacff6c3246a583f

(this also occurs on other terminal emulators, like `kitty`)

**Comment by dylanaraps** [comment]
#1392

**Comment by dylanaraps** [comment]
`catimg` is not a valid backend. https://github.com/dylanaraps/neofetch/commit/92ecdf0012f79500b569202ac191a6b838bc8e1d

**Comment by dylanaraps** [comment]
Updated Wiki to reflect this.

**Comment by j-james** [comment]
Ah, good to know. Any reason for its removal @dylanaraps ?
