### ISSUE TITLE
Catimg not working on neofetch but by using the command yes

### ISSUE THREAD

**Issue by IIPoliII** [dylanaraps/neofetch#1576]
I am not able to make it work by my side. But CatImg works 

` 2020-10-09 14:17:52 ⌚  Auth in ~
○ → neofetch -vv --catimg transparent--1-.png 2> neofetchlog
`

https://ptero.co/iduwiwohoc.diff

Any idea why?

![image](https://user-images.githubusercontent.com/29628512/95634327-ef81f180-0a89-11eb-8d34-ef9e2f8b5e30.png)

**Comment by dylanaraps** [comment]
#1392

**Comment by IIPoliII** [comment]
I know but I couldn't make it to work even by reading every comments... Any ideas?

**Comment by dylanaraps** [comment]
Post your issue there is all.
