### ISSUE TITLE
rendered width on iterm2

### ISSUE THREAD

**Issue by dotrachit** [dylanaraps/neofetch#1580]
## Description

The width of the rendered details of the command `neofetch` looks pretty stressed to me on iterm2.

#### Neofetch version
7.1.0

## How it looks (iterm2)
![image](https://user-images.githubusercontent.com/44428198/96354239-0790eb00-10f2-11eb-80f1-62e6e1edb414.png)

## How it should look (terminal)
![image](https://user-images.githubusercontent.com/44428198/96354253-21cac900-10f2-11eb-86f9-fd1cd28cbf91.png)

**Comment by dylanaraps** [comment]
I don't know what the issue is. Please reopen following the template. I need your configuration file and verbose logs from both.
