### ISSUE TITLE
Doesn't show term_font info

### ISSUE THREAD

**Issue by carlosala** [dylanaraps/neofetch#1582]
## Description

I'm using Debian Testing, Gnome console and zsh. The font used is inconsolata.
I have term_font in my config.conf and it doesn't show it, the log doesn't show any error.

#### Neofetch version
Neofetch 7.1.0

## Screenshot
![Captura de pantalla de 2020-10-19 16-43-33](https://user-images.githubusercontent.com/66907184/96466598-43c76700-122a-11eb-9f33-f9736182e3f4.png)

## Config file

print_info() {
    info title
    info underline

    info "OS" distro
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    # info "Resolution" resolution
    info "DE" de
    # info "WM" wm
    info "WM Theme" wm_theme
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "Terminal Font" term_font
    info "Host" model
    info "CPU" cpu
    info "GPU" gpu
    info "GPU Driver" gpu_driver  # Linux/macOS only
    info "Memory" memory

    # info "CPU Usage" cpu_usage
    # info "Disk" disk
    # info "Battery" battery
    # info "Font" font
    # info "Song" song
    # [[ "$player" ]] && prin "Music Player" "$player"
    # info "Local IP" local_ip
    # info "Public IP" public_ip
    # info "Users" users
    # info "Locale" locale  # This only works on glibc systems.

    info cols
}

**Comment by dylanaraps** [comment]
Reopen this issue with a verbose log attached and the template filled in.
