### ISSUE TITLE
[Feature request] GNOME Terminal font support

### ISSUE THREAD

**Issue by carlosala** [dylanaraps/neofetch#1583]
## Description
I'm using Debian Testing, Gnome console and zsh. The font used is inconsolata.
I have term_font in my config.conf and it doesn't show it, and I rebooted the PC.
#### Neofetch version
Neofetch 7.1.0
## Screenshot
![96466598-43c76700-122a-11eb-9f33-f9736182e3f4](https://user-images.githubusercontent.com/66907184/96472210-82f8b680-1230-11eb-9071-9baf2bef3a58.png)
## Config file
https://pastebin.com/GJWrDDDA
## Verbose log
https://pastebin.com/s3jvmcJj

**Comment by dylanaraps** [comment]
Can you reproduce this issue with `--config off`?

**Comment by dylanaraps** [comment]
It looks like Neofetch has no support for showing GNOME terminal font.

**Comment by carlosala** [comment]
With ```neofetch --config off``` doesn't appears too. I tried with bash (instead of zsh) and the same error appears.

**Comment by dylanaraps** [comment]
Duplicate of https://github.com/dylanaraps/neofetch/issues/887

Though... I don't know if the situation has changed since.
