### ISSUE TITLE
Neofetch takes long time (1.3 seconds) to detect packages in Fedora 33

### ISSUE THREAD

**Issue by swamytk** [dylanaraps/neofetch#1584]
## Description
Neofetch takes 1.249 seconds to detect packages out of total 1.850 seconds in Fedora 33.
It is observed with master branch too.

#### Neofetch version
Neofetch 7.1.0

## Screenshot
Running neofetch as usual: Total time: 1.850 seconds
![image](https://user-images.githubusercontent.com/73037782/96892360-3539b380-14a7-11eb-9343-7a564273bfbf.png)

Running neofetch without packages: Totoal time: 0.601 seconds
![image](https://user-images.githubusercontent.com/73037782/96892510-57333600-14a7-11eb-88d2-64723dcdddf5.png)

## Config file
[config.conf.txt](https://github.com/dylanaraps/neofetch/files/5423776/config.conf.txt)

## Verbose log
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/5423765/neofetchlog.txt)

**Comment by swamytk** [comment]
I found that the tool uses "rpm -qa" command to count packages. This command is the whole reason for the delay. Other alternative like 'dnf list installed" is worser than that. I am not sure whether it qualifies as a bug on neofetch. So closing this bug.

**Comment by YaBoiBurner** [comment]
Quick little thing, but it's possible to get packages a lot faster by using `/var/cache/dnf/packages.db`. It's an SQLite 3 database.
Running `sqlite3 -batch /var/cache/dnf/packages.db "SELECT count(pkg) FROM installed"` can count packages, and at least on my system it's at least 500 times faster than running `rpm -qa`
