### ISSUE TITLE
info "Disk" disk on macOS doesn't display disk sizes or percentages

### ISSUE THREAD

**Issue by Monty** [dylanaraps/neofetch#1586]
## Description

Results of:
    info "Memory" memory
    info "Disk" disk
    info "Resolution" resolution

**Neofetch 7.1.0 shows this**
Memory: 10521MiB / 16384MiB (64%)
Disk (/dev/disk1s1): /
Disk (/dev/disk1s2): /
Resolution: 3072x1920

**Instead of this**
Memory: 9536MiB / 16384MiB (58%)
Disk (/dev/disk1s1 466Gi 10Gi 359Gi 3% /): 10G / 466G (3%)
Disk (/dev/disk1s2 466Gi 92Gi 359Gi 21% /System/Volumes/Data): 92G / 466G (21%)
Resolution: 3072x1920

According to 
`git log -L /get_disk/,/disk_display/:neofetch
`
In commit c160c07399644533a778890ddb851ecb9d0a86a1 
the disk_info array indices were changed to negative numbers.
e.g.
disk="${disk_info[2]/i} / ${disk_info[1]/i}${disk_perc:+ ($disk_perc%)}"
was changed to 
disk="${disk_info[-4]/i} / ${disk_info[-5]/i}${disk_perc:+ ($disk_perc%)}"

If I change them back, it works as expected.

The specific error with the lines was 
disk_info: bad array subscript

macOS Catalina still comes with a pretty old bash,
as they switched to zsh for their interactive shell

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0

## Config file
    info "Memory" memory
    info "Disk" disk
    info "Resolution" resolution

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by yg-park** [comment]
I solved it by updating bash. `brew install bash`
As you said, it's too old bash on macOS Catalina.

**Comment by Monty** [comment]
I don’t use homebrew. It’s simpler for me to patch neofetch. 

-- Monty

**Comment by dylanaraps** [comment]
Let me know if the issue still occurs.

**Comment by Monty** [comment]
That fixed it. Tested on Big Sur, which was still broken yesterday.

Computer: MacBookPro16,1
CPU: Intel i7-9750H (12) @ 2.60GHz
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5300M
Memory: 9502MiB / 16384MiB (57%)
Disk (/): 14G / 466G (4%)
Resolution: 3072x1920
Battery: 100%
---
OS: macOS Big Sur 11.0.1 20B29 x86_64
Kernel: Darwin 20.1.0
Shell: zsh 5.8
Terminal: iTerm2
Terminal Font: Monaco 14
Locale: en_US.UTF-8
