### ISSUE TITLE
Resolution frequency

### ISSUE THREAD

**Issue by skipperguy12** [dylanaraps/neofetch#159]
Kind of new to this, first time ever seeing this project (so please just close this issue if it's in the wrong spot/doesn't belong here/isn't relevant to this project), but it would be nice to see it fetch information on the frequency (60hz, 144hz, etc) the screen is running at.

**Comment by dylanaraps** [comment]
Great idea!

I'll look into this.

**Comment by dylanaraps** [comment]
Implemented in #160.

**Comment by dylanaraps** [comment]
You can enable this with `--refresh_rate on` or by editing the config file.
