### ISSUE TITLE
Macos Sixel size issues. working but small image

### ISSUE THREAD

**Issue by uberkael** [dylanaraps/neofetch#1595]
## Description
Hi,
There are some problems with the sixel versión on macOS (installed both libsixel and neofetch through brew).
when I try a `neofetch --iterm2 image`
![image](https://user-images.githubusercontent.com/1783926/98173334-3a5d2080-1ef3-11eb-9039-b84e71a5ae78.png)
but with `neofetch --sixel image` the image is reduced.
![image](https://user-images.githubusercontent.com/1783926/98173358-46e17900-1ef3-11eb-9ef9-ece20f73a14d.png)
a normal `img2sixel image` works without a problem and the image is larger enough.
![image](https://user-images.githubusercontent.com/1783926/98173420-62e51a80-1ef3-11eb-9be4-eaaeb44b5d30.png)
I had tried with different pictures on mac and it happens in every case.
Also tried on Debian and Cygwin and worked without any problem.

I'm not sure if it is only an iterm2 because kitty on mac does not work with sixel (just print the raw data).

- [ x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0 (brew)

## Config file
default

**Comment by dylanaraps** [comment]
Resubmit this issue with the verbose log attached.
