### ISSUE TITLE
Display Chinese garbled code in Windows 10.

### ISSUE THREAD

**Issue by plain-dev** [dylanaraps/neofetch#1599]
## Description

If you're suggesting a new feature then just a description will suffice.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

Display Chinese garbled code in Windows 10.

## Verbose log

https://gist.github.com/plain-dev/1caa83f7b20509a266fd8554e7bd3634

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by plain-dev** [comment]
开启 `Beta版:使用Unicode UTF-8提供全球语言支持` 后正常了

**Comment by dylanaraps** [comment]
The verbose log link doesn't work?

**Comment by plain-dev** [comment]
I deleted log, I found a solution.
