### ISSUE TITLE
Refresh rate not measured correctly "FHD"Hz instead of 144

### ISSUE THREAD

**Issue by BitGrub** [dylanaraps/neofetch#1603]
![Screenshot 2020-11-11 at 01 21 02](https://user-images.githubusercontent.com/20694416/98753688-d045ef00-23bc-11eb-89fd-0f3f6a7971e1.png)

Haven't seen anything about this issue in the documentation OR in issues, so I have to assume I'm the first person to get this

**Comment by dylanaraps** [comment]
Reopen this issue with the template filled in.
