### ISSUE TITLE
manjaro linux can not display image

### ISSUE THREAD

**Issue by itxve** [dylanaraps/neofetch#1605]
## Description

If you're suggesting a new feature then just a description will suffice.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
neofetch-7.1.0-2

#### neofetch install
![image](https://user-images.githubusercontent.com/33005087/99142591-6ca81400-2691-11eb-9669-d1b2f78dd79a.png)
#### w3m install
![image](https://user-images.githubusercontent.com/33005087/99142630-d0cad800-2691-11eb-8021-e02b9c33607b.png)
#### use w3m output
![image](https://user-images.githubusercontent.com/33005087/99142554-091de680-2691-11eb-8399-aaa31221ae9c.png)
#### Is it true that I don't support output images
![image](https://user-images.githubusercontent.com/33005087/99142677-4df64d00-2692-11eb-883a-85c8b2f5f093.png)

## Config file
https://gist.github.com/itxve/b723a41c99508c72fc3903799f4862ec
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
Need a verbose log file. Also #1392

**Comment by itxve** [comment]
here my Verbose file
[log.txt](https://gist.github.com/itxve/69d49f4345243241bac5825c62e4fd28)

**Comment by itxve** [comment]
> Need a verbose log file. Also #1392
here my Verbose log
https://gist.github.com/itxve/69d49f4345243241bac5825c62e4fd28

**Comment by itxve** [comment]
@dylanaraps 
### here my log
https://gist.github.com/itxve/69d49f4345243241bac5825c62e4fd28
