### ISSUE TITLE
display current theme setting

### ISSUE THREAD

**Issue by aleprovencio** [dylanaraps/neofetch#1606]
Hello,
my main use of `pywal` is using the '--theme' argument to choose among custom made color schemes or the built-ins.

It would be nice if I could have a setting that displays the current `pywal` theme I'm using (ex: `base16-solarized`)

**Comment by dylanaraps** [comment]
The neofetch config is a shell script and one can trivially implement this themselves. See: https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
