### ISSUE TITLE
OS/X Big Sur doesn't show the true "11.0" version number

### ISSUE THREAD

**Issue by mitchblank** [dylanaraps/neofetch#1607]
## Description

To keep compatibility for apps looking for "10.X" version numbers, OS/X tries really hard to hand back programs the fake "10.16" version number rather than the true "11.0.X" one.

Amazingly, even directly reading the `SystemVersion.plist` file (like neofetch does) is not enough, since some (kernel-level?) shenanigans can redirect the filesystem access to the `SystemVersionCompat.plist` file instead.  Yes, really!
```
$ SYSTEM_VERSION_COMPAT=0 md5sum /System/Library/CoreServices/SystemVersion.plist
ea0589d185e0aa9aed8f317a8df60edd  /System/Library/CoreServices/SystemVersion.plist
$ SYSTEM_VERSION_COMPAT=1 md5sum /System/Library/CoreServices/SystemVersion.plist
d3e567e2b5ed0fd5048cf069b86a5edb  /System/Library/CoreServices/SystemVersion.plist
```

The result is that neofetch's `cache_uname()` function can end up reading the wrong version number.

In my testing, this fixes it:
```
diff --git a/neofetch b/neofetch
index 59e29d5..b1c1ecf 100755
--- a/neofetch
+++ b/neofetch
@@ -4774,7 +4774,7 @@ cache_uname() {
     kernel_machine="${uname[2]}"

     if [[ "$kernel_name" == "Darwin" ]]; then
-        IFS=$'\n' read -d "" -ra sw_vers <<< "$(awk -F'<|>' '/key|string/ {print $3}' \
+        IFS=$'\n' read -d "" -ra sw_vers <<< "$(SYSTEM_VERSION_COMPAT=0 awk -F'<|>' '/key|string/ {print $3}' \
                             "/System/Library/CoreServices/SystemVersion.plist")"
         for ((i=0;i<${#sw_vers[@]};i+=2)) {
             case ${sw_vers[i]} in
```

You could also set that `SYSTEM_VERSION_COMPAT=0` environment variable elsewhere, but just restricting it to that single `awk` command is sufficient to get the right version of that file.  Not sure what style you prefer.

- [ YES ] Does this issue still occur in the master branch? (**Required if issue**)

**Comment by dylanaraps** [comment]
Fixed, thanks.
