### ISSUE TITLE
Question about colors.

### ISSUE THREAD

**Issue by Fluffacorn** [dylanaraps/neofetch#1608]
## Description

I've started work on a pretty cool ASCII design, but before I put the time into finalizing it and assigning colors, I wanted to ask something about colors. The wiki says that you can use ${c1} to ${c6} to color the ascii, and I wanted to know if there was a way to use more than 6 colors in a design? This design is probably going to use around 14, if there is a limit.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)
#### Neofetch version
Neofetch 7.1.0

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/neofetch/issues/1523
