### ISSUE TITLE
How does neofetch show one image side by side from the text with catimg

### ISSUE THREAD

**Issue by IIPoliII** [dylanaraps/neofetch#1609]
Hey,

So I asked the following image on catimg but I think some neofetch users maybe have the reply, any ideas ?

I am trying to create something like catimg using bash. 

I want to show one image on the right and one ascii art (using the cat << EOF myascii EOF command)
So that I can show a logo and a text on the other side.

I want to use it as my login welcome screen when I ssh some of my machines.

So I was able to show the ascii art by doing :
```
cat << EOF

 _____         _   
|_   _|       | |  
  | | ___  ___| |_ 
  | |/ _ \/ __| __|
  | |  __/\__ \ |_ 
  \_/\___||___/\__|
                   
                   

EOF
```

And showing my image using `catimg myimage.png`

However I try to show them both side by side. I tried using pr.
`pr -m -t <(catimg) <(cat mytestfile.txt)` but it doesn't work and it cuts my ascii art.

It's the same using the paste command.

Was anyone able to do it. If yes how ?
My ascii art is quiet long too so without it to be cutted it would be awesome.

Thanks for your help.

**Comment by dylanaraps** [comment]
Hi. This tracker is for issues related to neofetch.

**Comment by IIPoliII** [comment]
Would love because of that to know how neofetch does it https://stackoverflow.com/questions/64931488/show-two-things-side-by-side-using-catimg-like-in-neofetch
