### ISSUE TITLE
Custom scrot settings ignores scrot_dir, doesn't convert time/date parameters

### ISSUE THREAD

**Issue by Brottweiler** [dylanaraps/neofetch#161]
I edited the config's scrot settings to have these options instead of the default.

```conf
scrot_cmd="maim -d 3"
scrot_dir="$HOME/Pictures/scrots"
```

I replaced **scrot** to use **[maim](https://github.com/naelstrof/maim)** instead, and I have a subfolder that I want it to save screenshots too.

I ran neofetch with the `-s` option and it seemed to work, but the screenshot ends up in `$HOME/Pictures` and not in the `scrots` folder.

Also, the name of the file is literally `neofetch-%Y-%m-%d-%H:%M.png`, so it didn't convert those parameters to date and time, this I assume could be related to me using **maim** instead of **scrot**.

Using version `1.5`.

**Comment by CousinMachu** [comment]
For the file name thing, I'm pretty sure that the default parameters are for scrot only. So you might want to use`scrot_name="neofetch-$(date +%F-%T).png"` instead of the default. No idea about the folder thing though, I assume the scrots folder exists right?

**Comment by Brottweiler** [comment]
Huh, changing the `scrot_name` still produces a filename like in my original post. It seems like maybe it completely ignores my config file changes. That makes sense, since I have `scrot` aliased to `maim`, although removing the alias seems to still produce an image.

I changed `maim` back to `scrot` in my config, and now it complains with `command not found`. So it _does_ read my config file.

With `scrot` in config file, it complains with command not found. With `maim`, it makes a screenshot. So changing `scrot_cmd` does work, but it ignores changes to `scrot_dir` and `scrot_name`, apparently.

**Comment by dylanaraps** [comment]
Thanks for reporting this, sorry I couldn't respond earlier!

I've found the issue and **#162** should fix it, before I merge the PR I'd like you
guys to test it out.

**Comment by dylanaraps** [comment]
Fixed with #162

**Comment by Brottweiler** [comment]
#162 fixed the `scrot_name` issue, and adding a `/` after the folder name fixed that too, thanks!

**Comment by dylanaraps** [comment]
No problem!
