### ISSUE TITLE
neofetch w3m image on w3m-patched st not working

### ISSUE THREAD

**Issue by nathanielevan** [dylanaraps/neofetch#1612]
## Description

st (simple terminal) has a [patch to support w3m images](https://st.suckless.org/patches/w3m/st-w3m-0.8.3.diff) which I've applied and confirmed to work using ranger's w3m image preview and w3m itself (e.g. w3m www.google.com displays the Google logo image without flickering). However, I can't get the neofetch image to display on that same st build, while it works fine on urxvt with the same neofetch config on the same machine (see config below).

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.1.0-2 on the Arch Linux repos (also tested against master branch)

## Screenshot
neofetch
![2020-11-23-203425](https://user-images.githubusercontent.com/9361126/99968129-51dd4a00-2dcb-11eb-8500-055e55f58d77.png)

w3m image preview working on ranger
![2020-11-23-203802](https://user-images.githubusercontent.com/9361126/99968530-d3cd7300-2dcb-11eb-9c94-aedfb16b9798.png)

## Config file
https://pastebin.com/ubUK69c3

## Verbose log
https://pastebin.com/fj6hLKBe

**Comment by dylanaraps** [comment]
> Failed to find terminal window size.

You are missing some dependencies.

Also. #1392

**Comment by nathanielevan** [comment]
Issue fixed by installing xorg-xwininfo on Arch Linux. Thank you!
