### ISSUE TITLE
Neofetch hangs at packages section when not run with sudo (Kubuntu 21.04, but happened also in older releases)

### ISSUE THREAD

**Issue by emk2203** [dylanaraps/neofetch#1616]
## Description

If you're suggesting a new feature then just a description will suffice.

- [x] Does this issue still occur in the master branch? (**Required if issue**)
Assuming installed neofetch 7.1.0-2 from Ubuntu = github 7.1.0 release = master

#### Neofetch version
7.1.0-2 from Ubuntu repo

## Screenshot
n/a

## Config file
Unchanged from default; fresh install after purging old config

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

Log section when hanging:

```bash
+ has mine
+ type -p mine
+ manager=mine
+ tot mine -q
+ IFS='
'
+ read -d '' -ra pkgs
++ mine -q
++ printf '\e[?25h\e[?7h' <---- interrupted here after a couple of minutes with ^C
```

Log section when run as `sudo neofetch`:

```bash
+ has mine
+ type -p mine
+ shopt -s nullglob
+ has brew
+ type -p brew
+ has emerge
+ type -p emerge
...
```

Full log: https://paste.ubuntu.com/p/j8P3Xy8XpJ/
If you need the full log of `sudo neofetch` as well, please let me know.

**Comment by dylanaraps** [comment]
Please try the latest master and let me know if the issue is resolved.

**Comment by emk2203** [comment]
Nope, didn't work. Also, `apt` adds a really noticeable delay (running `sudo neofetch`), while `dpkg` was very fast. So I would revert this change.

**Comment by quantum5** [comment]
@dylanaraps Can you revert 80174ea4d9b3f2e1fb35de8214b011275ed4b736? Not only is `apt list` very slow, it also lists all available packages instead of installed packages, which is not what we want.

**Comment by 825i** [comment]
This problem exists using WSL on Windows. It hangs for 4 whole seconds at the packages stage.
Surprisingly, running with 'sudo' step makes it instant.

Any fix for this?

Edit: I just commented out the packages line for now in.

`$HOME/.config/neofetch/config.conf`
