### ISSUE TITLE
Add support for Apple M1 Machines

### ISSUE THREAD

**Issue by sohansubhash** [dylanaraps/neofetch#1618]
## Description

The Host and CPU are incorrect for Apple M1 machines. I think that the CPU should be renamed to "Apple M1", and the Host should be "Mac mini m1" or "Mac mini late 2020". 

#### Neofetch version
Neofetch 7.1.0 running on macOS 11.0.1 Big Sur

## Screenshot
<img width="682" alt="Screen Shot 2020-11-26 at 11 31 54 AM" src="https://user-images.githubusercontent.com/13318243/100386693-fe414b00-2fda-11eb-84c9-efc84b222314.png">
<img width="698" alt="m1" src="https://user-images.githubusercontent.com/13318243/100386712-0a2d0d00-2fdb-11eb-9ee3-85b99d5c9954.png">

## Config file
I've left the config file as default. 

## Verbose log
https://pastebin.com/gVyrAgvU

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by HexaOneOfficial** [comment]
The cpu is correct as Minecraft displays the same type

**Comment by sohansubhash** [comment]
Minecraft and neofetch are running in [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)?wprov=sfti1), Apple's translation layer. Apple refers to the whole SOC as [M1](https://www.apple.com/mac/m1/). I could be wrong about this, but I'm fairly certain that Virtual CPU is symptom of Rosetta. I still think that the CPU should be called M1.

**Comment by HexaOneOfficial** [comment]
yeah there is not much you can do about it than

**Comment by oshaboy** [comment]
Isn't there an arm version of bash you can run?

**Comment by phschimm** [comment]
I switched my terminal to use Rosetta 2, installed neofetch via homebrew, did a `brew update/upgrade`, deactivated and reactivated Rosetta 2 translation for the terminal and now my neofetch is correctly showing macOS being the arm64 build.
 
<img width="567" alt="Screenshot 2020-12-24 at 16 23 41" src="https://user-images.githubusercontent.com/53938950/103096629-d60e3180-4604-11eb-9171-d9d1c2468c49.png">

Not sure if this helps or is reproducible, but I wanted to mention it ...

**Comment by unbeatable-101** [comment]
I installed using native M1 terminal and homebrew
<img width="682" alt="Screen Shot 2021-01-20 at 12 12 30 AM" src="https://user-images.githubusercontent.com/58151048/105129994-31bcc500-5ab4-11eb-8da5-a76a107b3186.png">

**Comment by sohansubhash** [comment]
hey all, I was able to replicate the the correct info  seen in the screenshots above. going to close the issue.
