### ISSUE TITLE
Wrong number of apt packages

### ISSUE THREAD

**Issue by divadsn** [dylanaraps/neofetch#1619]
## Description

As in the issue title already stated, neofetch seems to report the wrong number of installed apt packages.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version

Neofetch version 7.1.0 on Debian 10 Buster, taken directly from this repo.

## Screenshot

![image](https://user-images.githubusercontent.com/28547847/100441684-2bf3c600-30a7-11eb-8673-43677fc138a6.png)
![image](https://user-images.githubusercontent.com/28547847/100441899-7412e880-30a7-11eb-8446-db231bd9d1b5.png)

## Config file

https://pastebin.com/0vWPFNbT

## Verbose log

```
+ IFS='
'
+ read -d '' -ra pkgs
++ apt list

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

+ (( packages+=58019 ))
```

**Comment by A-725-K** [comment]
Hello @divadsn , I tested your issue and I'm facing the same problem. I have also submitted a pull request ( #1620 ) to fix this problem, the workaround could be considering only the packages showed by `apt list --installed` (minus 1 because the first line says "Listing..."). Hope this fix helps you!

**Comment by divadsn** [comment]
Thanks for your fix, works perfectly, although it's still counting very slow due to the fact that apt is a user-friendly wrapper for apt-get.

**Comment by vaskark** [comment]
Has this fix been merged into master? Because I'm still getting the wrong number listed (seems to be the total packages available from the repos rather than just what is installed). I'm on Ubuntu 20.10 with latest git.
Thanks.

**Comment by enigma9o7** [comment]
I'm having this issue too.  As mentioned, seems to be reporting total number of packages available to install with apt.  I just want to know how many debs actually installed, whether installed with apt, apt-get, gdebi, or dpkg directly.   I believe the correct solution is to use dpkg as it used too.....

https://github.com/dylanaraps/neofetch/issues/1719

**Comment by dylanaraps** [comment]
Fixed in master.
