### ISSUE TITLE
Inaccurate memory usage being reported

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/neofetch#1621]
## Description

Inaccurate memory usage being reported.

#### Neofetch version

7.1.0 (git)

## Screenshot

![2020-11-27_19-45](https://user-images.githubusercontent.com/33555080/100490436-6f6f2400-30e9-11eb-94fd-16739cd2bbfc.jpg)

## Config file

[link](https://pastebin.com/NNXnnhzV)

## Verbose log

[link](https://pastebin.com/7rPcVW4Z)

This is also occurring in the latest official release.
I'm on Ubuntu 20.10.
Thanks.

**Comment by Magicrafter13** [comment]
Similar/same issue here on Manjaro, seems to always be higher than the true amount.
![neofetch_free](https://user-images.githubusercontent.com/29127566/104499559-22a8b500-5592-11eb-8fbc-3ad97b462942.png)
![ksysguard](https://user-images.githubusercontent.com/29127566/104499589-2dfbe080-5592-11eb-9791-930336651728.png)

(Obviously KSysGuard and `free` are a little different, but this is probably just fluctuation between pressing enter to run `free`, and pressing print screen to grab the screenshot.)

**Comment by vaskark** [comment]
Glad to see I'm not the only one. I also have an Arch VM but it reports memory usage just fine. Let's hope there's a fix soon. Such a neat little app.

**Comment by enigma9o7** [comment]
https://github.com/dylanaraps/neofetch/issues/1719

I noticed something similar with current git version.

**Comment by dylanaraps** [comment]
Not an issue from what I recall (in master): https://github.com/dylanaraps/pfetch/issues/90

Reopen if I'm wrong.
