### ISSUE TITLE
Make Mandriva logo appear on Mandrake Linux

### ISSUE THREAD

**Issue by oshaboy** [dylanaraps/neofetch#1625]
https://i.imgur.com/r6cns3q.png

AFAIK the logo hasn't changed since the Mandrake days. So it should be trivial to implement.

**Comment by oshaboy** [comment]
How do I add labels?

**Comment by 6gk** [comment]
> How do I add labels?

You don't, that's up to project collaborators.

---

and I don't get how it is unclear that

> Neofetch supports almost 150 different operating systems. From Linux to Windows, all the way to more obscure operating systems like Minix, AIX and Haiku. If your favourite operating system is unsupported: Open up an issue and support will be added.

is referring to it not working, and not that it doesn't have a special logo.

(for onlookers, he was talking about this on discord, posting here for a bit of context to their issue)

**Comment by oshaboy** [comment]
Well, as I mentioned in the Discord. If I misunderstood the README, close the issue.
