### ISSUE TITLE
Picture does not load when I have neofetch in .zshrc 

### ISSUE THREAD

**Issue by Magnitudexx** [dylanaraps/neofetch#1626]
## Description
I have neofecth running with the kitty backend. When i add neofetch to my .zshrc file i get `;2059;1875t`. Running neofetch normally works.
- [ No] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.1.0
## Config file
https://pastebin.com/908q5hbW
## Verbose log
neofetch runs from .zshrc:
https://pastebin.com/p4pSTRaZ

**Comment by MaticBabnik** [comment]
same here, I get ` ;1368;1260t`

**Comment by dylanaraps** [comment]
Not a neofetch issue.
