### ISSUE TITLE
Possible wrong information on Windows

### ISSUE THREAD

**Issue by zikalify** [dylanaraps/neofetch#1627]
The window manager on Windows is DWM, not Explorer. Neofetch reports the shell as bash even though it's powershell, and the packages only reports those installed by scoop. 
![image](https://user-images.githubusercontent.com/1094772/101277166-6dbcf480-37aa-11eb-9cfa-84dde567e193.png)

**Comment by zikalify** [comment]
The DE is called Fluent on Windos 10, not Aero.

**Comment by rashil2000** [comment]
@zikalify The DE and WM have been fixed, they'll come with the next release.
