### ISSUE TITLE
Bug when using async mode

### ISSUE THREAD

**Issue by yeetologist** [dylanaraps/neofetch#1630]
## Description
The prompt get pushed so far down when using async

##Version
7.1.0
#
## Screenshot
![pic-full-201213-1715-56](https://user-images.githubusercontent.com/71173561/102009016-3e3c5800-3d67-11eb-983f-08626613526c.png)

## Config file
https://pastebin.com/6c2gjmGC

**Comment by Anu2001dev** [comment]
guess the numbler of new lines are equal to the number of information displayed

**Comment by karmicdude** [comment]
+1 from me

**Comment by m-wells** [comment]
Simple workaround.
```
neofetch | sed '/^[[:space:]]*$/d'
```

**Comment by Anu2001dev** [comment]
didn't work for me. I have 5 information displaying. the A cuts in half
![neofetch](https://i.imgur.com/ZLtBxbE.png)

**Comment by karmicdude** [comment]
> `neofetch | sed '/^[[:space:]]*$/d'`

`neofetch | cat -s` does it better than this regex, because it leaves single lines and removes duplicate lines more than 2 times.

**Comment by dylanaraps** [comment]
Dup of #1555
