### ISSUE TITLE
Cannot get correct informations on macOS Big Sur

### ISSUE THREAD

**Issue by beijingrice** [dylanaraps/neofetch#1632]
## Description

If you're suggesting a new feature then just a description will suffice.

- [Yes] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 6.1.0

## Screenshot
<img width="602" alt="截屏2020-12-17 20 50 02" src="https://user-images.githubusercontent.com/50019781/102490171-70bcbc80-40a9-11eb-9efe-9674c4324314.png">

## Config file
[config.txt](https://github.com/dylanaraps/neofetch/files/5709535/config.txt)

## Verbose log
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/5709525/neofetchlog.txt)

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by kotori2** [comment]
Master branch works for me. Is there any plan to update package in Homebrew?

**Comment by beijingrice** [comment]
idk @kotori2

**Comment by beijingrice** [comment]
What's your OS version? @kotori2

**Comment by kotori2** [comment]
```
Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```
aka 11.1 (20C69)

**Comment by vegadodo** [comment]
I found that this is due to the fact that the current code only counts packages installed in `/usr/local/Cellar/`, which only works with Intel version of Homebrew. I will open a PR addressing this issue soon.

**Comment by vegadodo** [comment]
Sorry, I misunderstood this issue. #1656 is unrelated.

**Comment by vegadodo** [comment]
@beijingrice Does this issue still occur on 7.1.0?
