### ISSUE TITLE
Neofetch showing wrong GPU (legit dont have any association with redhat)

### ISSUE THREAD

**Issue by Y32bit** [dylanaraps/neofetch#1640]
![Screenshot 2020-12-26 at 3 13 02 PM](https://user-images.githubusercontent.com/75537915/103159959-f8cb5200-478c-11eb-8f56-abbb4f3b96c8.png)
## Description

If you're suggesting a new feature then just a description will suffice.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by CodeLongAndProsper90** [comment]
That's because Crostini is using VirtIO, a technology for making VM's faster by letting the guest know they are virtualized, and it passes GPUs and NICs so it can use it natively. VirtIO was made by Red Hat/IBM and that's what the emulated GPU reports as.
