### ISSUE TITLE
FEATURE REQUEST: Display S.M.A.R.T status of the harddrives

### ISSUE THREAD

**Issue by JavierOramas** [dylanaraps/neofetch#1647]
## Description

In the summary data show a indicator of the health of the hard drives, one by one or at least a red flag to check for the non-healthy ones

**Comment by dylanaraps** [comment]
Outta scope. We simply wrap df. There's no portable way (even df usage requires we jump through hoops). 

The config is a shell script. You can make neofetch display whatever you like.

https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
