### ISSUE TITLE
RTX 3090 Shows as "NVIDIA 0a:00.0 NVIDIA Corporation Device 2204"

### ISSUE THREAD

**Issue by dylanmtaylor** [dylanaraps/neofetch#1649]
## Description

The card is listed wrong. This is the exact card: https://www.newegg.com/asus-geforce-rtx-3090-tuf-rtx3090-o24g-gaming/p/N82E16814126454?Item=N82E16814126454

- [x] Does this issue still occur in the master branch? (**Required if issue**)
Yes

#### Neofetch version

➜  ~ pacman -Qe | grep neofetch
neofetch 7.1.0-2

## Screenshot

![Screenshot from 2021-01-07 20-36-55](https://user-images.githubusercontent.com/277927/103963887-400bf800-5128-11eb-8a19-8e359488900f.png)

## Config file
Whatever Arch linux ships with

## Verbose log

+ (( ++info_height ))
+ prin=1
+ unset -v subtitle
+ info GPU gpu
+ [[ -n gpu ]]
+ subtitle=GPU
+ unset -v prin
+ get_gpu
+ case $os in
++ lspci -mm
++ awk -F '\"|\" \"|\\(' '/"Display|"3D|"VGA/ {a[$0] = $1 " " $3 " " $4}
                                           END {for(i in a) {if(!seen[a[i]]++) print a[i]}}'
+ gpu_cmd='0a:00.0  NVIDIA Corporation Device 2204'
+ IFS='
'
+ read -d '' -ra gpus
+ [[ 0a:00.0  NVIDIA Corporation Device 2204 == *Intel* ]]
+ for gpu in "${gpus[@]}"
+ [[ all == \d\e\d\i\c\a\t\e\d ]]
+ [[ all == \i\n\t\e\g\r\a\t\e\d ]]
+ case $gpu in
+ gpu='0a:00.0  NVIDIA Corporation Device 2204'
+ gpu='0a:00.0  NVIDIA Corporation Device 2204'
+ gpu='NVIDIA 0a:00.0  NVIDIA Corporation Device 2204'
+ [[ on == \o\f\f ]]
+ prin GPU 'NVIDIA 0a:00.0  NVIDIA Corporation Device 2204'
++ trim GPU
++ set -f
++ set -- GPU
++ printf '%s\n' GPU
++ set +f
+ [[ -n GPU ]]
+ [[ -n NVIDIA 0a:00.0  NVIDIA Corporation Device 2204 ]]
+ [[ -n '' ]]
+ string='GPU: NVIDIA 0a:00.0  NVIDIA Corporation Device 2204'
++ trim 'GPU: NVIDIA 0a:00.0  NVIDIA Corporation Device 2204'
++ set -f
++ set -- GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204
++ printf '%s\n' 'GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ set +f
+ string='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ strip_sequences 'GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ strip='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ strip='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ strip='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ strip='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ strip='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ strip='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
++ printf '%s\n' 'GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
+ length='GPU: NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
+ length=50
+ string='GPU\e[0m\e[0m:\e[0m NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
+ string='\e[1mGPU\e[0m\e[0m:\e[0m NVIDIA 0a:00.0 NVIDIA Corporation Device 2204'
+ printf '%b\n' '\e[41C\e[1mGPU\e[0m\e[0m:\e[0m NVIDIA 0a:00.0 NVIDIA Corporation Device 2204\e[0m '
+ (( ++info_height ))

**Comment by ChALkeR** [comment]
See #1646 and [FAQ](https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linuxfreebsd-why-doesnt-getgpu-show-my-exact-video-card-model).
[hwids](https://archlinux.org/packages/core/any/hwids/) is significantly outdated in Arch, which is causing this issue.

As a work-around, run `sudo update-pciids`.

I belive this is a duplicate and should be closed.

**Comment by dylanmtaylor** [comment]
> See #1646 and [FAQ](https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linuxfreebsd-why-doesnt-getgpu-show-my-exact-video-card-model).
> [hwids](https://archlinux.org/packages/core/any/hwids/) is significantly outdated in Arch, which is causing this issue.
> 
> As a work-around, run `sudo update-pciids` (which would override system-provided database though).
> 
> I belive this is a duplicate and should be closed.

It probably is a duplicate, you're right about that. Seeing as you have a 3090 as well, hopefully, they'll add our cards soon :)

**Comment by dylanmtaylor** [comment]
![Screenshot from 2021-02-08 23-13-52](https://user-images.githubusercontent.com/277927/107314804-77413200-6a63-11eb-9956-fbd5549dda02.png)

Closing because the suggested fix worked.
