### ISSUE TITLE
Image mode problem in Konsole terminal emulator

### ISSUE THREAD

**Issue by sardus-X** [dylanaraps/neofetch#1652]
Hi, I recently installed neofetch 7.0.0 via repository on KDE neon 20.04. Although in the terminal emulator table on the image mode wiki page, the KDE Konsole terminal emulator is not affected by oddities, in my case it seems to be affected by - Image disappears on window focus and resize - as for others terminal emulators.
In addition, using a png image with a transparent background in the terminal it actually appears opaque.
Is it possible to remedy these two drawbacks?

- [*] Does this issue still occur in the master branch? (**Required if issue**)

Neofetch 7.0.0

![Screenshot_20210112_164130](https://user-images.githubusercontent.com/29210004/104337019-52ee4600-54f5-11eb-9711-dc88ec69186e.png)

config:
https://pastebin.com/V34N81TB

neofetchlog:
https://pastebin.com/R3e56s3h

**Comment by karmicdude** [comment]
The same issue for me. Moreover, if I do a vertical split, when I try to draw neofetch on the right side, the image appears on the left side and blinking.

Archlinux, yakuake. Just default config with w3m backend and path to image 200x200px

**Comment by ivansaul** [comment]
Hi, @karmicdude @sardus-X 
I have a similar problem, in ArchLinux KDE, neofetch (Konsole) is not capable of displaying images even though it has all its dependencies installed and the config.conf file also correctly edited according to the neofetch wiki.
Any idea why it can't show images?

**Comment by dylanaraps** [comment]
#1392
