### ISSUE TITLE
ASCII Art doesn't appear on Chrome OS

### ISSUE THREAD

**Issue by saltedcoffii** [dylanaraps/neofetch#1653]
## Description

When installing neofetch with [chromebrew](https://github.com/skycocker/chromebrew/) directly onto a chromeos machine in developer mode, the chromeos ascii art does not appear without the `--ascii_distro chromeos` argument even though the OS field says "Chrome OS"

- [ x ] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0

#### Actual Behavior
![image](https://user-images.githubusercontent.com/55339220/104585132-99e15600-5631-11eb-8d9f-a52e292eec13.png)

#### Expected Behavior (without the `ascii_distro` part)
![image](https://user-images.githubusercontent.com/55339220/104585701-6e12a000-5632-11eb-882f-a6a3e3ba71f1.png)

## Verbose log
[https://hatebin.com/kevmfdswaq](https://hatebin.com/kevmfdswaq)

**Comment by TheWintelManager** [comment]
wow, this is cool

**Comment by TheWintelManager** [comment]
how do you get colors tho
