### ISSUE TITLE
Include entry for output device (e.g. /dev/tty1)

### ISSUE THREAD

**Issue by brainandforce** [dylanaraps/neofetch#1655]
I found that the addition of  Windows Terminal support ended up changing the Terminal entry from the terminal device to the name of the terminal emulator. I actually preferred the original behavior.

This could be included under a "Device" heading, since "Terminal" is taken and the output device may not necessarily be a terminal.

**Comment by dylanaraps** [comment]
Simply add:

> prin "Device" "$(tty)"

to your neofetch config inside print_info() as per https://github.com/dylanaraps/neofetch/wiki/Customizing-Info

I may add an option to print the device name. Will think about it.
