### ISSUE TITLE
Distribution Request: MUNIX

### ISSUE THREAD

**Issue by mad-css** [dylanaraps/neofetch#1661]
I'm made a Linux distribution and logo is [a Tux with BSD Daemon ears](https://avatars1.githubusercontent.com/u/77500196?s=400&u=1327c341d49f2d0764fdc9ad211642569ffe6346&v=4). I searched Tux ASCII art on all [/neofetch](https://github.com/dylanaraps/neofetch/blob/master/neofetch) file but I couldn't find it.

Can you please add it? The OS name is MUNIX.

**Comment by happyeggchen** [comment]
Same problem,I want to add it (the modified version) to my source too.But I can't find where ascii located in

**Comment by arisinfenix** [comment]
@handlederror There is a Tux ASCII https://github.com/dylanaraps/neofetch/blob/6dd85d67fc0d4ede9248f2df31b2cd554cca6c2f/neofetch#L7913

Use `neofetch --ascii_distro linux` to see how it looks.

**Comment by handlederror** [comment]
@arisinfenix but it's straight Linux mascot.

**Comment by happyeggchen** [comment]
found.
In the end of the script file.

**Comment by handlederror** [comment]
Thank you, @arisinfenix.
