### ISSUE TITLE
Add support for winget package manager

### ISSUE THREAD

**Issue by Dev727** [dylanaraps/neofetch#1673]
There was a previous issue opened before requesting to add support for Winget. It was closed due to Winget not being an actual package manager at the time, but I believe it is currently in an operational enough state to have a manifest created for Neofetch.

While Winget is still in its early stages, it is currently showing a lot of promise imo. Their roadmap shows a lot of promise for May this year, and they are adding experimental feature support for power users to enable in the meantime.

I would be willing to look into the creation of a manifest and submit it here as well.

**Comment by dylanaraps** [comment]
> The Windows Package Manager project is in Preview. 

Let's wait.

**Comment by lollilol** [comment]
any update?
