### ISSUE TITLE
Can't make neofetch --tycat work

### ISSUE THREAD

**Issue by enigma9o7** [dylanaraps/neofetch#1677]
![shot-2021-02-03_12-11-20](https://user-images.githubusercontent.com/30579733/106803462-1a83e880-6619-11eb-8587-e99a75f625d5.jpg)
What is neofetch looking for that prevents it from displaying png under terminology when tycat works fine?

I installed debian with no desktop and built window manager from source.  So I probably am missing some dependency, because this exact png and neofetch version works if I let debian installer install xfce or kde, etc.

**Comment by enigma9o7** [comment]
I just needed to rtfm.  imagemagick.

**Comment by enigma9o7** [comment]
Interestingly enough, I realized I do not have imagemagick installed on my primary machine (bodhi linux 5 = ubuntu 18) but it works there without it.  So must be something else can make it work too or something that comes with imagemagick... I'm curious...  but imagemagick fixed it for debian anyway.

**Comment by dylanaraps** [comment]
#1392 (also, imagemagick is always needed (the convert command specifically)). 

For next time. Provide logs. :)
