### ISSUE TITLE
feature request: display default browser

### ISSUE THREAD

**Issue by treeshateorcs** [dylanaraps/neofetch#1681]
## Description
pretty much self-explanatory. the default browser could be queried with `xdg-settings get default-web-browser`, for example

**Comment by dylanaraps** [comment]
This isn't worthwhile baking into neofetch.

Just modify your config.

- prin "Browser" "$(xdg-settings get default-web-browser)"
or
- prin "Browser" "$BROWSER"

in your print_info() function.

See https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
