### ISSUE TITLE
Neofetch missing cpu temperature on Raspberry Pi because temp_dir name cpu_thermal not matched

### ISSUE THREAD

**Issue by rotflol** [dylanaraps/neofetch#1682]
## Description

cpu_thermal should be added to the names of the temp_dir to display the temperature on a Pi.

**Comment by dylanaraps** [comment]
Master is unaffected.

**Comment by naz9ul** [comment]
Neofetch version 7.0.1 running on raspberry pi and debian bullseyes

Here is my patch to show the temperature:

            # Select the right temperature file.
            for temp_dir in /sys/class/hwmon/*; do
                [[ "$(< "${temp_dir}/name")" =~ (coretemp|fam15h_power|k10temp|cpu_thermal) ]] && {
                    temp_dirs=("$temp_dir"/temp*_input)
                    temp_dir=${temp_dirs[0]}
                    break
                }
            done

Results:

```
       _,met$$$$$gg.          root@node1 
    ,g$$$$$$$$$$$$$$$P.       ---------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) aarch64 
 ,$$P'              `$$$.     Host: Raspberry Pi 400 Rev 1.0 
',$$P       ,ggs.     `$$b:   Kernel: 5.15.30-v8+ 
`d$$'     ,$P"'   .    $$$    Uptime: 22 hours, 16 mins 
 $$P      d$'     ,    $$P    Packages: 1359 (dpkg), 4 (snap) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1200 
 Y$$.    `.`"Y$$$$P"'         CPU: BCM2835 (4) @ 1.800GHz [40.8°C] 
 `$$b      "-.__              Memory: 292MiB / 3794MiB 
  `Y$$                        Local IP: x.x.x.x
   `Y$$.                      Public IP: y.y.y.y 
     `$$b.
       `Y$$b.                                         
          `"Y$b._                                     
              `"""
```

**Comment by jslegers73** [comment]
> Neofetch version 7.0.1 running on raspberry pi and debian bullseyes
> 
> Here is my patch to show the temperature:
> 
> ```
>         # Select the right temperature file.
>         for temp_dir in /sys/class/hwmon/*; do
>             [[ "$(< "${temp_dir}/name")" =~ (coretemp|fam15h_power|k10temp|cpu_thermal) ]] && {
>                 temp_dirs=("$temp_dir"/temp*_input)
>                 temp_dir=${temp_dirs[0]}
>                 break
>             }
>         done
> ```
> 
> Results:
> 
> ```
>        _,met$$$$$gg.          root@node1 
>     ,g$$$$$$$$$$$$$$$P.       ---------- 
>   ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) aarch64 
>  ,$$P'              `$$$.     Host: Raspberry Pi 400 Rev 1.0 
> ',$$P       ,ggs.     `$$b:   Kernel: 5.15.30-v8+ 
> `d$$'     ,$P"'   .    $$$    Uptime: 22 hours, 16 mins 
>  $$P      d$'     ,    $$P    Packages: 1359 (dpkg), 4 (snap) 
>  $$:      $$.   -    ,d$$'    Shell: bash 5.1.4 
>  $$;      Y$b._   _,d$P'      Resolution: 1920x1200 
>  Y$$.    `.`"Y$$$$P"'         CPU: BCM2835 (4) @ 1.800GHz [40.8°C] 
>  `$$b      "-.__              Memory: 292MiB / 3794MiB 
>   `Y$$                        Local IP: x.x.x.x
>    `Y$$.                      Public IP: y.y.y.y 
>      `$$b.
>        `Y$$b.                                         
>           `"Y$b._                                     
>               `"""
> ```

Hi,

Sorry for the question but where do you place the this patch?
