### ISSUE TITLE
Cannot get desired image to print

### ISSUE THREAD

**Issue by misterch0c** [dylanaraps/neofetch#169]
Hi there,
I've been struggling to get a chosen image to output. if I run neofetch without any config I get my wallpaper showing as an image, but using --shuffle-dir or just giving an image as parameter I can't seem to change the image...
I've tried using iterm2 & then I get this:
http://i.imgur.com/cT24SeP.png

**Comment by dylanaraps** [comment]
Have you set `image_backend` to `iterm2`?

**Comment by misterch0c** [comment]
yes, and the result is the image I posted. So looks like raw data is outputed instead of the image

**Comment by dylanaraps** [comment]
@iandrewt, can you take a look at this? I don't have an OS X system to test on.

**Comment by iandrewt** [comment]
@misterch0c what does your config file look like in this section?

```sh
225 # Image Options {{{
226
227
228 # Image Source
229 # --image wall, shuffle, ascii, /path/to/img, off
230 image="wall"
231
232 # Thumbnail directory
233 thumbnail_dir="$HOME/.cache/thumbnails/neofetch"
234
235 # Image Backend
236 # Which program to draw images with
237 # --image_backend w3m, iterm2
238 image_backend="w3m"
239
240 # W3m-img path
241 # Some systems have this in another location
242 w3m_img_path="/usr/lib/w3m/w3mimgdisplay"
243
244 # Image position
245 # Only works with the w3m backend
246 # --image_position left/right
247 image_position="left"
248
249 # Shuffle dir
250 shuffle_dir="$HOME/Pictures/wallpapers/wash"
251
252 # Crop mode
253 # --crop_mode normal/fit/fill
254 crop_mode="normal"
255
256 # Crop offset
257 # Only affects normal mode.
258 # --crop_offset northwest/north/northeast/west/center
259 #               east/southwest/south/southeast
260 crop_offset="center"
261
262 # Image size
263 # The image is half the terminal width by default.
264 # --size auto, 00px, 00%
265 image_size="auto"
266
267 # Right gap between image and text
268 # --gap num
269 gap=4
270
271 # Image offsets
272 # --xoffset px
273 # --yoffset px
274 yoffset=0
275 xoffset=0
276
277
278 # }}}
```

This is the default config. I can't seem to reproduce this issue with the default config on version `1.5` when running `neofetch --image_backend iterm2 --shuffle_dir ~/Pictures`

**Comment by misterch0c** [comment]
My config the same except I changed the shuffle_dir value. Btw I'm on Archlinux, installed the neofetch-git package from the AUR. I also tried the neofetch one

**Comment by iandrewt** [comment]
The `iterm2` option is only for Mac users, it's the terminal emulator most of us use and has built in image support. When not using that option, it doesn't print any images at all, correct?

**Comment by misterch0c** [comment]
Yes it doesn't, it outputs raw data instead. I didn't realize it was only for mac users. But with w3m I'm not able to change the image. I tried using the shuffle_dir but still for some reasons it always shows my wallpaper (and changing wallpaper doesn't change the image in neofetch)

**Comment by iandrewt** [comment]
If you choose a specific image (with `--image /path/to/img`) does it show?

Also, when choosing a shuffle dir, are you using `neofetch --image shuffle --shuffle_dir /path/to/shuffle/dir`?

**Comment by misterch0c** [comment]
Hu well... My bad, I was using it wrong and didn't pass the --image shuffle
