### ISSUE TITLE
Possible license violation?

### ISSUE THREAD

**Issue by tsundaa** [dylanaraps/neofetch#170]
So, most of the ASCII logos are copied from screenFetch. My main concern is that all of screenfetch codes are (including ASCII) are [licensed under GPLv3](https://github.com/KittyKatt/screenFetch/blob/master/COPYING). And I believe this is licensed under MIT/X11 license.

Is this a GPL violation or not?

**Comment by dylanaraps** [comment]
I'm not too sure myself but iff this is an issue then I'll personally recreate the ascii art myself as I've done for other ascii logos already.

The creator of Screenfetch is also inactive on github so I'm not sure if they even know we exist. I'll contact him anyway to see his thoughts on the situation.

**Comment by DistantParadox** [comment]
Is it possible to just switch to a GPLv3 licence for future versions?  It shouldn't be a problem as the prior ones will just stay MIT.

**Comment by dylanaraps** [comment]
I just did some googling and we should be able to swap the license from MIT to GPLv3 without running into any issues. 

What do you guys think about re-licensing to GPLv3? **(+1 or -1 this comment)**

**Comment by DistantParadox** [comment]
Glad to hear it!

**Comment by dylanaraps** [comment]
I'm going to close this issue as I've done some more googling and come to the conclusion that the ascii from Screenfetch falls under fair use meaning it should be fine for us to use it this way. 

If @KittyKatt thinks otherwise we'll reopen this issue and explore the re-licensing further but until then no changes will be made.

Thanks for your input guys.

**Comment by tsundaa** [comment]
You probably should ask for every code contributor's permission,
since they still hold their copyrights, like what happened to MAME.

**Comment by dylanaraps** [comment]
@tsundaa

Yeah, if we eventually decide to relicence I will ask for every contributer's permission.

**Comment by KittyKatt** [comment]
If you need anything, most of my contact details are actually kinda inaccurate right now since I've lost a...LOT of things in my life. Please don't hesitate to find me on Rizon or Spotchat. Same nick.
