### ISSUE TITLE
Cannot identify qtile window manager

### ISSUE THREAD

**Issue by bnainar** [dylanaraps/neofetch#1701]
## Description
Neofetch displays LGD3, I don't know what that is. I'm using qtile. Same issue with dwm

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Latest as of 16 March
## Screenshot
![](https://i.redd.it/3bb8bxnxyym61.png)
## Config file
None

**Comment by dylanaraps** [comment]
Reopen with logs
