### ISSUE TITLE
Feature request : faster loadtime

### ISSUE THREAD

**Issue by arcolinuxz** [dylanaraps/neofetch#1703]
When my system is working "hard" it happens very often that neofetch (which is at the end of our .bashrc) loads in bits and pieces trying to get resource time to display its data.

What if we used a .cache file that can be just read or use environment variables?
Would that not make things faster to display?

We can still run the same process we use now in the background and if we see the result is different that what we have the cache file is updated.
So next time the data will be correct.

Re-edit : you might need a switch - when you are using neofetch to display music songs
neofetch --cache
or something

**Comment by dylanaraps** [comment]
Not worthwhile. 

Just save neofetch's output to a file and cat it at will.

Or look at pfetch https://github.com/dylanaraps/pfetch
