### ISSUE TITLE
Incomplete operation in ConEmu

### ISSUE THREAD

**Issue by dar-irl** [dylanaraps/neofetch#171]
Having issues running neofetch using ConEmu (w/ CygWin bash). Running neofetch through Conemu doesn't return any errors or anything, just a blank buffer. Attempting to close Conemu after trying to run neofetch causes a popup notifying me of an incomplete operation. I'm currently trying to use neofetch 1.6, but previous versions have had the same issue. Running neofetch through Mintty works fine, however, leading me to believe it's an issue with Conemu compatibility.

**Comment by dylanaraps** [comment]
I'm currently setting up CYGWIN/ConEmu to try and reproduce this and to hopefully come up with a fix for the issue.

**Comment by dylanaraps** [comment]
This seems to be the offending line that's causing ConEmu to hang:

```sh
# Get cursor position
info_height="$(IFS=';' read -srdR -p $'\E[6n' ROW COL; printf "%s" "${ROW#*[}")"
```

I've already got an idea for a permanent fix but in the meantime comment out this entire block near the bottom of the script.

```sh
if [ "$image" != "off" ]; then
    # Get cursor position
    info_height="$(IFS=';' read -srdR -p $'\E[6n' ROW COL; printf "%s" "${ROW#*[}")"

    # Set cursor position dynamically based on height of ascii/text.
    [ "$lines" -lt "$info_height" ] && lines="$info_height"

    printf "%b%s" "\033[${lines}H\033[${prompt_height}A"
fi

```

**Comment by dar-irl** [comment]
Still having the same issue with that block commented out, unfortunately.

**Comment by dylanaraps** [comment]
Keep the block commented and try launch neofetch with: 

- `neofetch --image ascii`
- `neofetch --image off`

Do the above commands work?

**Comment by dar-irl** [comment]
Yeah, neofetch works fine with those commands!

**Comment by dylanaraps** [comment]
Alright, I know what's causing the hangs now. `ConEmu` doesn't support the escape sequences
we're using to do image sizing and cursor positioning. 

I can possibly fix the hang caused by the bottom block (Cursor position) but I won't be able to fix
the problem with w3m image sizing unless the `ConEmu` devs implement the escape sequence.

I'll open an issue on their github repo and I'll see what they can do to solve this for us. In the 
meantime keep the block at the bottom commented and launch neofetch with `--image ascii` 
or `--image off`.

Sorry for the inconvenience.

**Comment by dylanaraps** [comment]
The exact escape sequences that ConEmu **doesn't** support are:

- `\033[6n` (Used to get the cursor position)
- `\033[14t` (Used for image sizing) (Gets the terminal window size in pixels)
- `\033[c` (Used for image sizing) (Used as a fallback to ascii mode)

**Comment by dylanaraps** [comment]
The issue has been opened on ConEmu's issue tracker.

**https://github.com/Maximus5/ConEmu/issues/608**

**Comment by Maximus5** [comment]
You should report the hung to cygwin team. It's not a ConEmu problem, unless you are using the [connector](https://conemu.github.io/en/CygwinMsysConnector.html).

**Comment by dylanaraps** [comment]
@Maximus5, these hangs were occuring *without* the connecter. Everyone works with the connector with the exception of `\033[14t` which isn't a huge concern.

See my comment in your repo.

**Comment by dylanaraps** [comment]
@dar-irl, it turns out that you need to use the CYGWIN connector for neofetch to work outside of the box with ConEmu. You can find setup instructions here:

https://conemu.github.io/en/CygwinMsysConnector.html
