### ISSUE TITLE
Custom ascii file not showing words info

### ISSUE THREAD

**Issue by chgara** [dylanaraps/neofetch#1710]
## Description

While using a custom ascii file like this one [this.](https://anonfiles.com/wancl8m2ua/anon_txt) and doing `neofetch --source anon.txt  ` it only shows the image and not the metrics and info

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.1.0

## Screenshot
![Screenshot from 2021-03-23 22-41-13](https://user-images.githubusercontent.com/57034271/112222536-f318c780-8c28-11eb-9b95-c4c35f6a87d2.png)

## Config file
 no config
## Verbose log
no verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
[Pastebin](https://pastebin.com/3e57TpBL)

**Comment by dylanaraps** [comment]
Need a verbose log. Though this is likely caused by escape sequences in the source file.

**Comment by dylanaraps** [comment]
Dup of #1699
