### ISSUE TITLE
Fedora: ASCII Logo needs updating to reflect new official logo

### ISSUE THREAD

**Issue by xalmat** [dylanaraps/neofetch#1711]
## Description

Fedora's official logo is changing. In order to keep consistent, the ASCII representation in neofetch should be updated.

More details on the new logo here:

https://www.youtube.com/watch?v=cHE3bgDo5Xg

**Comment by nickavem** [comment]
:+1: 

Would only need an ASCII of the new logo and to implement the old one as `fedora_old`. We're in a freeze, but could probably squeeze in a back port if this is done soon.

**Comment by nickavem** [comment]
xref: https://pagure.io/design/issue/736

**Comment by mairin** [comment]
Note that I am the designer of the new Fedora logo and the long term Fedora logo maintainer, and I approve of the last design in that ticket:
https://pagure.io/design/issue/736#comment-723845
