### ISSUE TITLE
Distro Request: Alma Linux

### ISSUE THREAD

**Issue by Mythbusters123** [dylanaraps/neofetch#1714]
## Description
It would be nice to have an alma linux ascii screen! :)

#### Neofetch version
Latest
## Screenshot
![image](https://user-images.githubusercontent.com/58893124/112912568-cc91db00-90c5-11eb-8e3a-5096a52ed478.png)

## Config file
Nothing changed, clean install
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

https://paste.rs/skM

**Comment by arisinfenix** [comment]
See #1715

**Comment by Mythbusters123** [comment]
Thanks a ton!
