### ISSUE TITLE
Apple Silicon - incorrect reading of brew installed packages

### ISSUE THREAD

**Issue by vom513** [dylanaraps/neofetch#1718]
## Description

On an Apple Silicon machine with brew installed (using the Homebrew recommended location of /opt/homebrew) - neofetch reports 1 package installed (I have ~ 90).

- [X] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version

7.1.0 (git current)

## Screenshot

<img width="500" alt="Screen Shot 2021-04-02 at 2 22 30 PM" src="https://user-images.githubusercontent.com/4698017/113442964-082aee80-93bf-11eb-96ad-9aa4fb7c167d.png">

## Config file

Using the default shipped (no changes).

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

[https://pastebin.com/C5JR1bXM](https://pastebin.com/C5JR1bXM)

PS: I see that "brew --cellar" gets called.  This is the output from the Apple Silicon machine:

`% brew --cellar`
`/opt/homebrew/Cellar`

**Comment by dylanaraps** [comment]
Fixed in master I believe.
