### ISSUE TITLE
cant get it to run propperly

### ISSUE THREAD

**Issue by thereal-Stiven** [dylanaraps/neofetch#1725]
## Description

hi, I am trying yo get it running on my manjaro machine.
It always displays the default manjaro pic and i tried the w3m google.com and it doesnt display pictures.
since I am prettey new with linux I would like to ask you to tell me what to do for further steps
br.
### Neofetch version
Neofetch 7.1.0
## Verbose log
https://pastebin.com/zCzSyPmu

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
#1392  

From your log:

- [0m[31m[!]\e[0m Image: Failed to find terminal window size.
- [0m[31m[!]\e[0m Image: Check the '\''Images in the terminal'\'' wiki page for more info,

You need xdotool or xwininfo.
