### ISSUE TITLE
number of snap package is not shown if snap list isnt ran before running neofetch

### ISSUE THREAD

**Issue by MeztliRA** [dylanaraps/neofetch#1728]
## Description

when i run neofetch the number of snap packages isnt shown
but if i run `snap list` and then run neofetch again it shows up

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0

## Screenshot
![before running snap list](https://user-images.githubusercontent.com/78863518/114527784-91b9a680-9c72-11eb-861c-50b7b523b135.png)
![after running snap list](https://user-images.githubusercontent.com/78863518/114527820-9aaa7800-9c72-11eb-97db-6ae97790b8d3.png)

## Config file
im using the default config

## Verbose log
https://pastebin.com/riP528Tp

**Comment by dylanaraps** [comment]
Yes. The daemon must be running otherwise snap list will hang the system. I'm guessing running it starts up the daemon on your machine. Not a bug.
