### ISSUE TITLE
MBA M1 Resolution Incorrectly Reported. 

### ISSUE THREAD

**Issue by danielktdoranie** [dylanaraps/neofetch#1731]
## Description

If you're suggesting a new feature then just a description will suffice.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)
So the resolution in Neofetch is reported as 1400 x 900 but it is actually 2560 × 1600. Attached screenshots. I have an Apple MacBook Air (2020, M1) running macOS Big Sur 11.2.3 (20D91)

#### Neofetch version
7.1.0
## Screenshot
https://files.catbox.moe/aogrcn.png
https://files.catbox.moe/lo26lb.png
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by danielktdoranie** [comment]
I'm guessing nobody give a sh*t

**Comment by 1alessandro1** [comment]
@dylanaraps BUMP!

**Comment by zhustec** [comment]
It seems to be caused by `screenresolution`, I just comment it on for temporary solution.

**Comment by danielktdoranie** [comment]
> It seems to be caused by `screenresolution`, I just comment it on for temporary solution.

Thanks for replying. I would view that as more of a work around versus solution, it doesn’t solve anything. 

I have discovered the issue is the same on my MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)

**Comment by danielktdoranie** [comment]
This is a Homebrew issue, not Neofetch. The MacPorts Neofetch works fine
