### ISSUE TITLE
Resolution display wrong for multi-monitor on Ubuntu 21.04

### ISSUE THREAD

**Issue by kimlimjustin** [dylanaraps/neofetch#1738]
## Description
When running neofetch on Ubuntu 21.04 with multiple monitors, the display resolution only shows up the second monitor resolution. This might be a duplicate of #1297 but it closed and the issue is fixed for the windows, but not for Ubuntu.
In my case, I got two monitor of 1366 x 768 and 1920 x 1080.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.1.0

## Screenshot
![image](https://user-images.githubusercontent.com/61906684/115951936-97827800-a50d-11eb-8fa4-bd9f3e05ff51.png)

## Verbose log
https://pastebin.com/uvV40nAR

**Comment by dylanaraps** [comment]
Fixed in master.

**Comment by officiallymarky** [comment]
> Fixed in master.

Will there be a tagged release?  It seems this (bugged) version is still the one being distributed everywhere.
