### ISSUE TITLE
Scoop git-with-openssh integration

### ISSUE THREAD

**Issue by Deiv70** [dylanaraps/neofetch#1740]
## Scoop installation of "neofetch" doesn't admit "git-with-openssh" as a "git" package alternative

- [X] Yes, this (issue / lack of feature)  does still occur in the master branch !

This improvement is a easy task, only need for a dual `scoop prefix [ git | git-with-openssh ]` check...

**Comment by dylanaraps** [comment]
I don't know what any of this means.
