### ISSUE TITLE
CPU information not displayed on G4 Mac Mini Running Leopard

### ISSUE THREAD

**Issue by EmNem543** [dylanaraps/neofetch#1745]
## Description
when the neofetch command is run it will not display any CPU information whatsoever. I have tried the various options.
- [ ] Does this issue still occur in the master branch? (**Required if issue**)
yes

#### Neofetch version
7.10
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
Send logs.
