### ISSUE TITLE
New Distribution Request: BuildRoot

### ISSUE THREAD

**Issue by ELECTROHAXZ** [dylanaraps/neofetch#1748]
Distro name: MotionEyeOS (based on BuildRoot)
Homepage: https://github.com/ccrisan/motioneyeos
Buildroot Homepage: https://buildroot.org/
Package manager: None (other BuildRoot OSs may have)

## Screenshot: https://i.imgur.com/669a2i9.png
MotionEyeOS Logo: https://i.imgur.com/5rdoUmv.png
BuildRoot Distro Logo: https://buildroot.org/images/logo.png

**Comment by alicela1n** [comment]
Why do people want buildroot supported? It's made for embedded systems and not desktop use, so why would you need to have neofetch on it?

**Comment by ELECTROHAXZ** [comment]
> 
> 
> Why do people want buildroot supported? It's made for embedded systems and not desktop use, so why would you need to have neofetch on it?

Because why not? It's an OS that isn't supported and some people (like me) want to check on the status of the OS, neofetch is handy for it. Looks nicer in screenshots too.

**Comment by alicela1n** [comment]
neofetch isn't really for that, there's other tools that work better for diagnostics
![image](https://user-images.githubusercontent.com/18562602/118293654-b7fb7d80-b48e-11eb-84ed-07d12ac9001a.png)

**Comment by ELECTROHAXZ** [comment]
> 
> 
> neofetch isn't really for that, there's other tools that work better for diagnostics
> ![image](https://user-images.githubusercontent.com/18562602/118293654-b7fb7d80-b48e-11eb-84ed-07d12ac9001a.png)

I also listed for screenshots too.

**Comment by nmcain** [comment]
Buildroot is not neccessarily a distribution itself, its a tool for generating basic Linux images for embedded environments, so the Linux logo that is shown in Neofetch is sufficient.
