### ISSUE TITLE
Sync music playback from browsers.

### ISSUE THREAD

**Issue by TheFenrisLycaon** [dylanaraps/neofetch#1751]
## Description

It would be really awesome if there was an option to sync my music playback from browsers. 
For example, I have a rather old system and installing spotify has a negitive impact on performance. So I generally use the web client. Only if I could sync it with neofetch... 

![Screenshot_~ : bash1](https://user-images.githubusercontent.com/54172306/118507443-dc37b280-b74b-11eb-8aaa-1dfe8205f992.png)

This thing is working with VLC. Would love to see it sync from browser sessions as well.

**Comment by oc1024** [comment]
Do you have `plasma-browser-integration` installed? Neofetch has support for it.

**Comment by TheFenrisLycaon** [comment]
Works like a charm. Thanks.
