### ISSUE TITLE
New Distribution Request: Bodhi Linux

### ISSUE THREAD

**Issue by HexGremlin** [dylanaraps/neofetch#1757]
## Description

New Distribution Request: Bodhi Linux

Logo: [https://image.spreadshirtmedia.com/image-server/v1/compositions/T757A1PA1578PT10X11Y23D11654563FS9999/views/3,width=650,height=650,appearanceId=1,backgroundColor=fff/the-bodhi-linux-logo.jpg](url)

![image](https://user-images.githubusercontent.com/70352769/119332475-8a79b580-bc80-11eb-8a2d-7e155c79e3c6.png)

**Comment by torculus** [comment]
If you want to skip the hard work, you're more than welcome to steal from my [repo](https://github.com/torculus/Unix-rices/tree/main/neofetch). It also includes work for illumos (general) and Genode

**Comment by torculus** [comment]
@HexGremlin, here's what I came up with. What do you think? If you're all good, I can initiate a pull request to merge
![bodhi](https://user-images.githubusercontent.com/20175597/128497349-18ea2188-7a32-43fc-8d83-514e78193025.png)

**Comment by dylanaraps** [comment]
That looks great. Send a PR whenever you are ready.

**Comment by HexGremlin** [comment]
That looks awesome! 😁🥳
