### ISSUE TITLE
More technical info to be presented

### ISSUE THREAD

**Issue by binarydepth** [dylanaraps/neofetch#1758]
Description

I would like more technical info to be presented. RAM speed and PCI GPU link if turbo boost is enabled KVM and also would be nice if it tells if Nvme drives are installed with it's PCI link. This are features that can render much different results in a system.

TY

RAM speed
PCI GPU link 
Nvme PCI link
turbo boost
SMT
KVM

**Comment by dylanaraps** [comment]
This is out of scope.

Thanks for opening this issue.
