### ISSUE TITLE
ASCII art width is calculated incorrectly for ANSI escapes

### ISSUE THREAD

**Issue by Scoder12** [dylanaraps/neofetch#1768]
## Description

ASCII art width is calculated incorrectly for ANSI escape codes using `\e`.
An example logo that uses ansi truecolor escapes:
```
\e[38;2;105;125;133m
                .:+yysoo/:.             
        -+yddddddhyssyydddds/.         
      .+hdddddddddddddddyysddddy/`      
    `oddddddddddddddddddddh/yddddh/     
  -dddddhs+::...-//oydddddd+odddddy.   
  :dddho//osyhddyo+::-`:odddd-sdddddh-  
-ddd++ydddddo:`         .odds.ddddddd  
`hdh+hdddddo.   \e[38;2;78;80;80m-+shhs+-\e[38;2;105;125;133m   -hd.hdddddd  
:dy+dddddd/    \e[38;2;78;80;80msdddddddds`\e[38;2;105;125;133m  -d.ddddddd  
od/dddddd/o   \e[38;2;78;80;80m/dddddddddd+\e[38;2;105;125;133m   o:ddddddy:.
o:ydddddo.s   \e[38;2;78;80;80m/dddddddddd+\e[38;2;105;125;133m   :ydddddd/d.
..dddddd:/d.   \e[38;2;78;80;80msdddddddds`\e[38;2;105;125;133m  `ydddddd+hd.
/dddddd:.dh.   \e[38;2;78;80;80m-+oyho+-\e[38;2;105;125;133m   :yddddds/hds 
-dddddd:`hddo`         `:yddddh+/oddd` 
  +dddddh`/ddddo-` -::+yyyyo+:.-odddh-  
  :hddddy`oddddddyo//-...::+shddddy.   
    `sddddh::hdddddddddddddddddddh/     
      .+hdddy+/sdddddddddddddddy/`      
        -+ydddy+o+oyydddddds/.         
            `-/+ooys+-    `             
\e[97m
```

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0 (latest master)

## Screenshot
Result:
![image](https://user-images.githubusercontent.com/34356756/120846676-54adba00-c527-11eb-8537-592831b7bbc3.png)

Expected result, generated using this logo file:
```
${c1}
                .:+yysoo/:.
        -+yddddddhyssyydddds/.
      .+hdddddddddddddddyysddddy/`
    `oddddddddddddddddddddh/yddddh/
  -dddddhs+::...-//oydddddd+odddddy.
  :dddho//osyhddyo+::-`:odddd-sdddddh-
-ddd++ydddddo:`         .odds.ddddddd
`hdh+hdddddo.   ${c2}-+shhs+-${c1}   -hd.hdddddd
:dy+dddddd/    ${c2}sdddddddds`${c1}  -d.ddddddd
od/dddddd/o   ${c2}/dddddddddd+${c1}   o:ddddddy:.
o:ydddddo.s   ${c2}/dddddddddd+${c1}   :ydddddd/d.
..dddddd:/d.   ${c2}sdddddddds`${c1}  `ydddddd+hd.
/dddddd:.dh.   ${c2}-+oyho+-${c1}   :yddddds/hds
-dddddd:`hddo`         `:yddddh+/oddd`
  +dddddh`/ddddo-` -::+yyyyo+:.-odddh-
  :hddddy`oddddddyo//-...::+shddddy.
    `sddddh::hdddddddddddddddddddh/
      .+hdddy+/sdddddddddddddddy/`
        -+ydddy+o+oyydddddds/.
            `-/+ooys+-    `
```

![image](https://user-images.githubusercontent.com/34356756/120846793-79099680-c527-11eb-80dc-d9b2a616c088.png)

## Config file
Default

## Verbose log
https://gist.github.com/Scoder12/0806fc1bcc3d7c72c7e32d8ac686f105

**Comment by dylanaraps** [comment]
Not a bug. Neofetch just doesn't support escape sequences in ascii files.

There's a PR open for this but I'm yet to test it out.

**Comment by dylanaraps** [comment]
Dup of https://github.com/dylanaraps/neofetch/issues/1699

**Comment by TheFierceLizard** [comment]
If you want to "paint" your ASCII art, you don't need to actually insert ANSI escape codes into the file itself. Instead, make use of `${c1}` - `${c6}` variables AND add the escape codes into the `--ascii_colors` flag. I was trying to insert an ASCII Red Bull logo with original colors into neofetch output and that's how I worked it around:

Here's the code for the art itself:
```${c2}                      ..                      
                 ............                 
${c1}    c       ,:dkxc'${c2}.........${c1}:oxx:,.      :    
   c   ',cxOOOOOkOkl${c2}......${c1}ckOkkOOOOkl;'   ;   
     .kOOkOOOOOOkOOdc${c2}....${c1}ckxOkkOOOOOOOOO;     
     :Okd. ;cokl:kkkx;${c2}..${c1},kkkxclko    lOOl.    
  ;l;       .o.  l::;;'.::;:c  co.      .dc,  
${c2}                    ......                    
```

And the neofetch command that paints it properly looks like this:
`neofetch --ascii /path/to/ascii --ascii_colors "\e[38;2;210;0;60" "\e[38;2;255;211;0"`

Hope this helps

**Comment by Nyameliaaaa** [comment]
> If you want to "paint" your ASCII art, you don't need to actually insert ANSI escape codes into the file itself. Instead, make use of `${c1}` - `${c6}` variables AND add the escape codes into the `--ascii_colors` flag. I was trying to insert an ASCII Red Bull logo with original colors into neofetch output and that's how I worked it around:
> 
> Here's the code for the art itself:
> 
> ```
>                  ............                 
> ${c1}    c       ,:dkxc'${c2}.........${c1}:oxx:,.      :    
>    c   ',cxOOOOOkOkl${c2}......${c1}ckOkkOOOOkl;'   ;   
>      .kOOkOOOOOOkOOdc${c2}....${c1}ckxOkkOOOOOOOOO;     
>      :Okd. ;cokl:kkkx;${c2}..${c1},kkkxclko    lOOl.    
>   ;l;       .o.  l::;;'.::;:c  co.      .dc,  
> ${c2}                    ......                    
> ```
> 
> And the neofetch command that paints it properly looks like this: `neofetch --ascii /path/to/ascii --ascii_colors "\e[38;2;210;0;60" "\e[38;2;255;211;0"`
> 
> Hope this helps

Just wondering, how did you generate the ANSI escape code from the hex code?

**Comment by TheFierceLizard** [comment]
> Just wondering, how did you generate the ANSI escape code from the hex code?

Oh, you just convert HEX to RGB basically. If we deconstruct the escape code, 38 states the foreground color (text color), 2 states it's in RGB and the last three numbers are for red, green and blue respectively.

Almost forgot to mention that if you wanna use the escape codes in the `--ascii_colors` flag, no need to add "m" as the final byte to every single one of them — it'll make that "m" appear in your artwork instead

**Comment by TheFierceLizard** [comment]
> If you want to "paint" your ASCII art, you don't need to actually insert ANSI escape codes into the file itself. Instead, make use of `${c1}` - `${c6}` variables AND add the escape codes into the `--ascii_colors` flag. I was trying to insert an ASCII Red Bull logo with original colors into neofetch output and that's how I worked it around:
> 
> Here's the code for the art itself:
> 
> ```
>                  ............                 
> ${c1}    c       ,:dkxc'${c2}.........${c1}:oxx:,.      :    
>    c   ',cxOOOOOkOkl${c2}......${c1}ckOkkOOOOkl;'   ;   
>      .kOOkOOOOOOkOOdc${c2}....${c1}ckxOkkOOOOOOOOO;     
>      :Okd. ;cokl:kkkx;${c2}..${c1},kkkxclko    lOOl.    
>   ;l;       .o.  l::;;'.::;:c  co.      .dc,  
> ${c2}                    ......                    
> ```
> 
> And the neofetch command that paints it properly looks like this: `neofetch --ascii /path/to/ascii --ascii_colors "\e[38;2;210;0;60" "\e[38;2;255;211;0"`
> 
> Hope this helps

Don't wanna necrobump, but this feature works good in terminals that actually do operate with ANSI escapes: Alacritty was messy as hell, while it worked like a charm on xfce4-terminal, so keep that in mind
