### ISSUE TITLE
Suggestion: Simplify and improve background retrieval (self-plug)

### ISSUE THREAD

**Issue by FallenWarrior2k** [dylanaraps/neofetch#1769]
## Description

I know it's probably bad style to advertise software you wrote yourself, but I recently wrote [xbgdump](https://github.com/FallenWarrior2k/xbgdump) for my own workflow. Looking at all the special-casing going on in neofetch to accommodate different desktop environments and whatnot, when most of it boils down to the same thing in the end, I feel like at least some of that work could be off-loaded to xbgdump.

In some cases, neofetch also currently selects the wrong wallpaper. For example, I have a `~/.fehbg` still lying around as a backup, even though I've been using Nitrogen to manage my wallpapers for a good while now due to its multi-monitor support saving me from having to manually stitch the files together. For those situations, instead of relying on a priority order heuristic that has a solid chance of being wrong, xbgdump would be able to reliably get the currently active wallpaper.

### Downsides

Since I'm advertising one of my own projects for integration with another, I feel it's doubly important to highlight potential issues that might result from such an integration.

In multi-monitor setups, xbgdump returns the combined background for all monitors as one big file. Beside the fact that such a file can look odd if displayed in the terminal, it can also take a while to create: on my machine (i7-4790, 1600 MHz DDR3, 3 monitors for a total of 5040x1920), getting the background as uncompressed PAM takes around 60-70ms, while PNG compression raises that to around 400ms.

In terms of features of the application itself, off-screen areas are not accounted for at the moment, meaning they generally end up as solid black pixels, which can be ugly if you have mixed landscape and portrait screens like me. I could see myself implementing something to mask those with full transparency in the future, but at the moment, those pixels are left untouched.

Also, as an application built on the X11 API, it does not work on Wayland (I haven't actually tested this because I'm on the proprietary Nvidia driver, but I have zero reason to assume it would work with XWayland).

And, finally, maybe the biggest issue is a dependency on a tool that's not currently packaged for any distribution. I've got an AUR package, but that's it so far.

### Conclusion

If there's interest in integration, I'd be willing to contribute and implement features you might want. If you feel that the downsides outweigh the potential benefit or that there's some other issue that I did not consider, I can completely understand that.

**Comment by dylanaraps** [comment]
This likely won't work for desktop environments which don't put wallpapers in the root window. (iirc GNOME, also possibly KDE). 

Current support is fine for now imo. 

Thanks for opening this issue.
