### ISSUE TITLE
Memory measurement on OpenBSD

### ISSUE THREAD

**Issue by feute** [dylanaraps/neofetch#177]
Memory info isn't being displayed correctly, i.e.: 

> Memory: -180MB / MB

I see that neofetch relies on `dmesg` to get the total memory, in my case, it's not possible because `dmesg` output gets filled by errors (on my system, at least) and 'real mem' can't be found there.

Another thing is that *free mem* is not what it seems, the memory part of `top -d 1` (taken from neofetch) in my system is:

> Memory: Real: 1078M/1735M act/tot Free: 252M Cache: 397M Swap: 57M/2295M

From this line, 252M it's not obviously the free memory.

My suggestion is to gather the total memory from the output of that line; and should be, in this case: 1735M + 252M, and get the free memory by substracting the result of the previous sum with 1078M.

**Comment by dylanaraps** [comment]
I've booted up an OpenBSD VM and I'm working on this now, thanks for opening the issue.

**Comment by dylanaraps** [comment]
I see that you're also getting a buggy output with `CPU` and `Uptime`, I want to also fix these issue for you. 

What's the output of these commands? 

```sh
sysctl -n hw.model
sysctl -n kern.boottime
```

**Comment by feute** [comment]
`sysctl -n hw.model`
> Intel(R) Pentium(R) 4 CPU 2.80GHz ("GenuineIntel" 686-class)

`sysctl -n kern.boottime`
> 1458597577

**Comment by dylanaraps** [comment]
Thanks!

Does this command below work on your system? What it does is print the 3 numbers we'll be doing math on in a single line so that I can add them to an array.

```sh
top -d 1 | awk -F ':  |/| |M' '/Memory:/ {printf $4 " " $6 " " $11 "\n"}'

# Output in my VM:
17 83 1892
```

**Comment by feute** [comment]
Yes! That's the one:

```
top -d 1 | awk -F ':  |/| |M' '/Memory:/ {printf $4 " " $6 " " $11 "\n"}'

1007 1675 312
```

**Comment by dylanaraps** [comment]
Memory output *should* work now, try out **https://github.com/dylanaraps/neofetch/pull/179**.

**Comment by feute** [comment]
Yes, it works now!

**Comment by dylanaraps** [comment]
Are you having any other issues with the script while we're on the topic of OpenBSD support?

**Comment by feute** [comment]
No, everything is being displayed correctly.

**Comment by dylanaraps** [comment]
Awesome! :+1:

I'll merge the PR once the uptime changes have been tested on OS X.
