### ISSUE TITLE
iTerm2 custom image has massive gap at the bottom

### ISSUE THREAD

**Issue by wiggleforlife** [dylanaraps/neofetch#1771]
## Description

Neofetch adds a massive gap below the image and system info. If a terminal window is less than ~3/4 of my screen height, I can't see Neofetch at all.

- [y] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.1.0

## Screenshot
<img width="780" alt="Screen Shot 2021-06-10 at 1 19 51 PM" src="https://user-images.githubusercontent.com/46230102/121591772-bd48db00-c9ee-11eb-993d-63706b1181ae.png">

## Config file
I've aliased `neofetch` to `neofetch --iterm2 ~/terminalstuff/3bf0jyvalh251.jpg --size 700px --gap -40`
[config.txt](https://github.com/dylanaraps/neofetch/files/6634199/config.txt)

## Verbose log
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/6634209/neofetchlog.txt)

**Comment by dylanaraps** [comment]
#1392

**Comment by Marko-Sanchez** [comment]
It's been close to a year, but commenting just in case someone else comes across this thread. I had a similar issue but as mentioned in the [wiki](https://github.com/dylanaraps/neofetch/wiki/What-is-Waifu-Crop%3F) setting the crop level to "fit" and making `image_size="560px"` will shorten the gap. Image size should be changed for you specific situation / image.
