### ISSUE TITLE
Installing on Windows via Winget

### ISSUE THREAD

**Issue by jos3s** [dylanaraps/neofetch#1782]
Make neofetch available through Winget for installation on Windows.

[Winget Pkgs](https://github.com/microsoft/winget-pkgs)

**Comment by dylanaraps** [comment]
No

**Comment by jos3s** [comment]
> No

@dylanaraps 

Any specific reason not to make neofetch available in Winget?

**Comment by dylanaraps** [comment]
This is not up to me. Anyone can go ahead and do this. I maintain neofetch, not its packages in every OS/Distro.
