### ISSUE TITLE
neofetch don't report correct distro

### ISSUE THREAD

**Issue by DorisCarson** [dylanaraps/neofetch#1789]
## Description
Recetly I Installed emerge (gentoo's package manager) on my laptop running artix linux (an arch fork without soystemd). And now neofetch report gentoo as my distro.

#### Neofetch version
```bash
$ neofetch --version
Neofetch 7.1.0
```
## Screenshot
**NOTE:** emerge is removed
![neofetch](https://user-images.githubusercontent.com/84324561/122672253-c7d85100-d1f4-11eb-96f3-ee8056133aca.jpg)

## Config file
https://gist.github.com/DorisCarson/df1aded08f76c9ddd09cd84a5c81bf03

## Verbose log
https://gist.github.com/DorisCarson/70909dbce2d479e21e4b54b55acfcb45

**Comment by dylanaraps** [comment]
Your /usr/lib/os-release file contains gentoo information. Not a neofetch bug.
