### ISSUE TITLE
GPU info not displayed on Windows

### ISSUE THREAD

**Issue by yzgyyang** [dylanaraps/neofetch#1798]
## Description

- [x] Does this issue still occur in the master branch? (**Required if issue**)

It seems like the GPU part errored out, so no info is printing. Relevant log from `-vv`:

```
+ get_gpu
+ case $os in
++ wmic path Win32_VideoController get caption
C:\Users\yzgyy\scoop\apps\neofetch\current\neofetch: line 2381: /dev/fd/62: No such file or directory
+ gpu=
++ wmic path Win32_VideoController get caption
```

Minimal reproducible:
```
yzgyy@YGY-AORUS MINGW64 ~/Projects/neofetch (master)
$ while read -r line; do
while read -r line; do
> echo $line
echo $line
> done < <(wmic path Win32_VideoController get caption)
done < <(wmic path Win32_VideoController get caption)
wmic path Win32_VideoController get caption
bash: /dev/fd/62: No such file or directory
wmic path Win32_VideoController get caption
```

So, looks like a bug in MINGW64, as described in: 

- https://github.com/bats-core/bats-core/issues/256
- https://github.com/rupa/z/issues/278

#### Neofetch version

7.1.0, also Github latest (master, https://github.com/dylanaraps/neofetch/tree/cc39539c55c612ca8cfcd313cc8ccb84d89b0f82).

## Screenshot

![image](https://user-images.githubusercontent.com/16748524/123419799-ab3b7080-d588-11eb-9846-47fd16bc20a7.png)

## Config file

Default/ N/A

**Comment by lesander** [comment]
I can confirm #1799 fixes the issue for me on Windows. However, this change was not pushed or ported to [the latest 7.1.0 release](https://raw.githubusercontent.com/dylanaraps/neofetch/7.1.0/neofetch). I would appreciate a new tag + an update to [the scoop repository](https://github.com/ScoopInstaller/Main/blob/master/bucket/neofetch.json).
