### ISSUE TITLE
Why there hasn't been any releases since 2021?

### ISSUE THREAD

**Issue by KermanX** [dylanaraps/neofetch#1802]
## Description

scoop can only update neofetch to the latest version.

but the latest version is:

![image](https://user-images.githubusercontent.com/63178754/123531055-d1e9da80-d733-11eb-939b-c917d3a9eb53.png)

**Comment by KermanX** [comment]
I think it's a big problem, because there is alot of people using scoop, but not cloning the responsitory

**Comment by dylanaraps** [comment]
A release will be made when I am ready to make one.

**Comment by yzgyyang** [comment]
I personally feel like this issue should be reopened to track the process and obstacles until a new release is out.

**Comment by dylanaraps** [comment]
There is no process and there are no obstacles. A release will be made when I am ready to make one..
