### ISSUE TITLE
[question, otherwise feature request] custom colors for text to the side of ascii art/image?

### ISSUE THREAD

**Issue by TPO100Cofficial** [dylanaraps/neofetch#1805]
## Description

if this is already in neofetch, so sorry for asking but i couldn't find it in documentation
if it isn't, however, can we have a way to set the colors in the text next to the ascii art ourselves?
![image](https://user-images.githubusercontent.com/33667869/123888467-16979080-d943-11eb-9896-f7a63fc6fd25.png)

**Comment by dylanaraps** [comment]
Yeah, it's in the documentation.

**Comment by TPO100Cofficial** [comment]
oh, alright
..where?

**Comment by dylanaraps** [comment]
man neofetch
