### ISSUE TITLE
[Distro Requset]

### ISSUE THREAD

**Issue by linux6os** [dylanaraps/neofetch#1810]
Name-Aravalli Linux 6
Webiste-linux6os.github.io
logo
![124266605-d1e34380-db54-11eb-8dee-b5d866b0c138](https://user-images.githubusercontent.com/86717971/124351199-9610b280-dc16-11eb-88c7-76bbd29a5235.png)

**Comment by dylanaraps** [comment]
Please put more effort into your request.
