### ISSUE TITLE
Fix Haiku OS ASCII logo

### ISSUE THREAD

**Issue by C47F15H** [dylanaraps/neofetch#1812]
## Screenshot
![image](https://user-images.githubusercontent.com/80169337/124376984-2b6b7f80-dcc7-11eb-8120-ed4107c18281.png)
Original logo ([source](https://www.haiku-os.org/images/haiku_logo_white.svg))
<img src="https://www.haiku-os.org/images/haiku_logo_white.svg" />

**Comment by C47F15H** [comment]
Is anyone working on it?

**Comment by dylanaraps** [comment]
You can work on it!

**Comment by C47F15H** [comment]
This is what i have come up with
```
      MM         MM
      MM         MM
      MM      . cmmmm-
      MM  .cMMMLMMM'
"'---cMMMMMMMMM"*lM
      M"*:Mc`"`` MM
      MM         MM
      ""         ""
```

**Comment by torculus** [comment]
@C47F15H, I made a slightly upscaled version of that which you can see here. Most distro asciis are 38-40 pixels wide
![haiku-neofetch](https://user-images.githubusercontent.com/20175597/128496727-4ccb8d68-e8b4-4a76-8a44-4158e8fd211e.png)

**Comment by C47F15H** [comment]
looks nice, but can the leaf colour be replaced with light green?

**Comment by torculus** [comment]
Yeah, you'd just use ascii color 10 instead of 2
Here's what it looks like
![neofetch-haiku](https://user-images.githubusercontent.com/20175597/128516693-69bd0d67-1918-4e13-b866-3ff5226e1c47.png)

**Comment by C47F15H** [comment]
nice, but can you send that part of the neofetch with the c{x}'s?

**Comment by torculus** [comment]
Sorry, I mixed up the two issues I'm working on. Here's the plaintext for the Haiku logo:



 ${c1}           MMMM              MMMM
            MMMM              MMMM
            MMMM              MMMM
            MMMM              MMMM
            MMMM${c2}        .**\ /**MMMM*-
 ${c1}           MMMM${c2}   .MMMMMMMMvMMMMM<
 #*         ,*MMMvMMMMMMMMMMMMMMM*
   '------cMMMMMMMMMMMMMMMMM^%.${c1}MMM
            MMMM${c2}%MMMM^MMMMM/  ${c1}MMMM
            MMMM              MMMM
            MMMM              MMMM
            """"              """"

**Comment by torculus** [comment]
Sorry, I mixed up the two issues I'm working on

If you like this version, I can just go ahead and create a new pull request for Haiku

**Comment by torculus** [comment]
Here is the version with {cx}'s
`

 ${c1}           MMMM              MMMM
            MMMM              MMMM
            MMMM              MMMM
            MMMM              MMMM
            MMMM${c2}        .**\ /**MMMM*-
 ${c1}           MMMM${c2}   .MMMMMMMMvMMMMM<
 #*         ,*MMMvMMMMMMMMMMMMMMM*
   '------cMMMMMMMMMMMMMMMMM^%.${c1}MMM
            MMMM${c2}%MMMM^MMMMM/  ${c1}MMMM
            MMMM              MMMM
            MMMM              MMMM
            """"              """"`

**Comment by C47F15H** [comment]
```
                        MMMM              MMMM
                        MMMM              MMMM
                        MMMM              MMMM
                        MMMM              MMMM
                        MMMM        cMl/MMMMMM*-
                        MMMM . .cMMMMMMMMMMMMM*`
              ,         ,*MMMvMMMMMMMMMMMMMMM*
               `*.__,-cMMMMMMMMMMMMMMMMM^%.MMM
                        MMMM%MMMMMMMMMM/  MMMM
                        MMMM              MMMM
                        MMMM              MMMM
                        """"              """"

```

**Comment by torculus** [comment]
Okay, so I have my version on the left (red circles), then yours (blue circles), then the original image, then my proposed compromise. I really like your leaf stem (in blue), while my version focused on the notches in the leaf (i.e. the red circles). However, your version gave me some insights about improving them, which I have in purple = red + blue = mine + yours

![haiku-changes](https://user-images.githubusercontent.com/20175597/128644324-9d5d3ca7-49fa-4e1a-9e7b-4db3941b8d96.png)

And here is the final (proposed) result
```


 ${c1}           MMMM              MMMM
            MMMM              MMMM
            MMMM              MMMM
            MMMM              MMMM
            MMMM${c2}       .ccc| /**MMMM*-
 ${c1}           MMMM${c2}   .ccccMMM|/MMMMM\`
  ,         ,*MM|/MMMMMMMMMMMMMMM*
   `*.__,-cMMMMMMMMMMMMMMMMM\`.${c1}MMM
            MM${c2}MM%MMMM\`.MMM/  ${c1}MMMM
            MMMM              MMMM
            MMMM              MMMM
            """"              """"
```
![image](https://user-images.githubusercontent.com/20175597/128644417-d33e0a66-241a-433f-b8dc-4627c6abf009.png)
What do you think?

**Comment by C47F15H** [comment]
The last leafcut is not needed. the ascii logo will look still represent Haiku even if it does not exist because it is very minor detail.
```
                                                                          this ⬇️ 
```
![user-images.githubusercontent.com/20175597/128644324-9d5d3ca7-49fa-4e1a-9e7b-4db3941b8d96.png](https://user-images.githubusercontent.com/20175597/128644324-9d5d3ca7-49fa-4e1a-9e7b-4db3941b8d96.png)

**Comment by torculus** [comment]
Okay, I have removed the last leafcut. Here is the current ascii running in the Haiku terminal. I changed the H color to black since the default terminal has a white background
![haiku-neofetch](https://user-images.githubusercontent.com/20175597/128921594-68d87b38-b70c-46ef-9c5a-8fdf5dad311d.png)

**Comment by C47F15H** [comment]
the leaf petiole needs to be a bit more visible
```
,
 `*o._,ccM
```
maybe like this

**Comment by C47F15H** [comment]
the theme for the information can be set to this - 1 3 7 2 and the `${c1}` can be changed `${c3}` and `${c2}` can be `${c4}`

**Comment by torculus** [comment]
So here is the logo with the new petiole
![full leaf](https://user-images.githubusercontent.com/20175597/129202012-6450f59f-e136-4c0d-ae7a-3ad8fe251192.png)

As for your other comment, I'm very confused. Colors 1 and 3 are red and yellow, and those aren't in the logo. I went ahead and changed ${c1} -> ${c3} and ${c2} -> ${c4}, and here is the result
![color2](https://user-images.githubusercontent.com/20175597/129202312-049faf51-9892-4ba1-a457-50dce2b79606.png)

Also, color 2 is the light green, and you said before that you don't like it. Here is the same thing with color 10 (dark green)
![color10](https://user-images.githubusercontent.com/20175597/129202402-f9166c0a-98e6-406f-aee3-bcb40b134152.png)

This is probably the closest we're going to get to the logo with ascii art. Are you ready to do a pull request?

**Comment by torculus** [comment]
@C47F15H, is this version acceptable for a pull request?

**Comment by torculus** [comment]
Okay, so I just noticed that you said "information" and I think I know what you're talking about. You want the text colors to be `1 3 7 2`, right? In other words, is this close to what you'd like?
![newest](https://user-images.githubusercontent.com/20175597/131515144-f4c67d66-bf88-4648-ba77-eda41f5a4baa.png)

**Comment by C47F15H** [comment]
Line 5, 6, 7 & 8
```
.ciO|/YMMMMM*"
```
```
.coMMMMM|/MMMMM/'
```
```
,iMM|/
```
Fix the ${cX}'s too:
```
MMM/`${cX}.MMM
```

**Comment by C47F15H** [comment]
Line 9
```
MMMMMMM/`":MM/
```

**Comment by C47F15H** [comment]
And I think we're done.

**Comment by C47F15H** [comment]
@torculus you can show a screenshot and then finally make a pull request!

**Comment by torculus** [comment]
Okay, I put it on a black background just to be certain that these are the colors you're happy with
![haiku](https://user-images.githubusercontent.com/20175597/131680569-7cc1caf9-1107-4573-9558-e6e66d116eec.png)

@dylanaraps , I see that you can set `${c1}, ${c2}`, etc. in each distro's `set_colors` call, but how do you make `--colors 1 3 7 10` persistent for each distro?

**Comment by C47F15H** [comment]
![image](https://user-images.githubusercontent.com/80169337/131685800-4374d48b-6cdb-410f-bbe6-7d0ea5e31b45.png)
```sh
set_colors 1 3 7 10
```

**Comment by torculus** [comment]
Final product, using `set_colors 1 3 7 10` and changing ${c1} -> ${c3}, ${c2} -> ${c4}. I think it's looking pretty good!
![Screenshot](https://user-images.githubusercontent.com/20175597/131715492-7f9fc9ac-8e32-4b32-b804-15ca79b5240f.png)
