### ISSUE TITLE
Distribution Request: Knoppix

### ISSUE THREAD

**Issue by oshaboy** [dylanaraps/neofetch#1821]
Comes up as Debian in neofetch.

**Comment by dylanaraps** [comment]
Send log.

**Comment by oshaboy** [comment]
https://pastebin.com/7EKYGUeX

**Comment by dylanaraps** [comment]
The distribution you're using identifies itself as Debian:

```sh
++ lsb_release -sd
+ distro='Debian GNU/Linux bullseye/sid'```

Neofetch is working as intended.

**Comment by oshaboy** [comment]
And there isn't a workaround to recognize it is Knoppix?

**Comment by dylanaraps** [comment]
Try removing the package which provides `lsb_release`. 

Or tell your distribution to provide its own `lsb_release`.
