### ISSUE TITLE
Manjaro logo

### ISSUE THREAD

**Issue by C47F15H** [dylanaraps/neofetch#1828]
The "new" Manjaro logo is not really new.
What: go to [manjaro.org](https://manjaro.org) and you will see a small image <img src="https://manjaro.org/images/b2021.png" alt="Back to 2021" height="28"> which reads, Back to 2021
Reason: unknown, maybe the developers want to make an "[Easter egg](https://en.wikipedia.org/wiki/Easter_egg_(media))"
## am not sure, this just what I think

**Comment by dylanaraps** [comment]
Reverted the Manjaro changes.
