### ISSUE TITLE
Support for os: Slax

### ISSUE THREAD

**Issue by Froozigiusz** [dylanaraps/neofetch#1836]
Slax is a Live CD operating system, and while you wouldn't normally use the neofetch in an OS typically used for maintenance, all of the code is working properly (the newer versions are based on Debian) and it isn't **that** unheard of (I think). Also I personally wouldn't consider another ASCII art a bloat

This is their current logo:
https://logos-download.com/wp-content/uploads/2019/07/Slax_Logo.png

**Comment by C47F15H** [comment]
Text:
```
            .cMMc.
      .,,.cMMMMMMm.      ..
    .cMMMMMMMMMMMMm  ,cmMMMMc.
    vMMMMMMMMMMMMMM cMMMMMMMM.
     \"MMMMMMMMMMMMMMMMMMMMMMm.
       `";mMMMMMMMMMMMMMMMMMMMMM\
 .cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy
 MMMMMMMMMMMMMMMMMMMMMMMMMMMM:"
 "MMMMMMMMMMMMMMMMMMMMMMc.
   `MMMMMMMMM:'MMMMMMMMMMMMc.
    MMMMMMMM" MMMMMMMMMMMMMM.
    `"MMM"` .  MMMMMMMMMMMMMy'
            | 'MMMMMMy
            l   `"""'
            "
```
Screenshot:
![Slax](https://user-images.githubusercontent.com/80169337/126599622-0764e684-453c-4e29-a159-e4532ca28fca.png)
Format | Colo(u)r
--|--
 R, G, B | 13, 212, 0 
C, M, Y, K | 94, 00, 100, 17
H, S, V | 116, 100, 83
Hex code | #0dd400
Preview: | <img src="https://via.placeholder.com/12/0dd400/?text=+">

**Comment by dylanaraps** [comment]
See my comment in #1837
