### ISSUE TITLE
Maybe add information about current IM module

### ISSUE THREAD

**Issue by Alexey-T** [dylanaraps/neofetch#1839]
As you can see in Lazarus forum
https://forum.lazarus.freepascal.org/index.php/topic,55424.msg412777.html#msg412777
sometimes it's needed to know the IM: this is result of 

```
echo $GTK_IM_MODULE
echo $QT_IM_MODULE
```
and QT framework version.

do you think it's good to add this to Neofetch results?

**Comment by dylanaraps** [comment]
This can easily be added to your neofetch config.

```
# inside print_info()
prin GTK_IM "$GTK_IM_MODULE"
prin QT_IM "$QT_IM_MODULE"
```

See: https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
