### ISSUE TITLE
PNG images are inverted in Konsole

### ISSUE THREAD

**Issue by madjoe** [dylanaraps/neofetch#1843]
## Description

Whilst running `neofetch --w3m --source ~/your_photo.png` the image displays inverted in Konsole, but it displays just fine in Yakuake.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0

## Screenshot
![](https://i.imgur.com/lHQKeTn.png)

## Config file
https://hastebin.com/ojanipogud.shell

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

https://hastebin.com/ejejopicat.diff

**Comment by dylanaraps** [comment]
#139

Also, I don't think this is a neofetch issue. Take it up with Konsole I reckon.
