### ISSUE TITLE
CyberOS logo does not match downstream

### ISSUE THREAD

**Issue by omaemae** [dylanaraps/neofetch#1845]
## Description
- [x] Does this issue still occur in the master branch? (**Required if issue**)

he CyberOS logo upstream does not match the one which is [downstream (in CyberOS repos)](https://github.com/omaemae/neofetch).

#### Neofetch version
master

## Screenshot
![upstream](https://user-images.githubusercontent.com/17727163/126950169-ab9e2894-aa41-449a-b84a-196221ea5a06.png)
![downstream](https://user-images.githubusercontent.com/17727163/126950206-3e9311b3-6534-4b30-b0c9-c61a13a0d67f.png)

**Comment by dylanaraps** [comment]
They should send a PR with their updated logo.
