### ISSUE TITLE
Cannot distinguish between WSL on Windows 10 vs Windows 11

### ISSUE THREAD

**Issue by dmadisetti** [dylanaraps/neofetch#1848]
## Description

**neofetch shows "on Windows 10" when on Windows 11**

Not sure how to do this aside from grepping Windows build numbers, but this seems like abit of a hack. Didn't see anything when searching through issues, so thought I would open here.

- [x]  Does this issue still occur in the master branch? (Required if issue)

#### Neofetch version

Neofetch 7.1.0 (newest source, top) + 2.0.2 (debian 9 stock, bottom)

#### Logs

https://gist.github.com/dmadisetti/7ec45a39e611ea4953c1029d2179c44c

## Screenshot

![image](https://user-images.githubusercontent.com/2689338/127213190-ac881bc8-7e99-4e28-a176-9b2b77c922fe.png)

**Comment by dylanaraps** [comment]
What is the issue exactly?

**Comment by dmadisetti** [comment]
neofetch shows "on Windows 10" when on Windows 11

**Comment by dylanaraps** [comment]
Send me a verbose log.

**Comment by dmadisetti** [comment]
https://gist.github.com/dmadisetti/7ec45a39e611ea4953c1029d2179c44c

**Comment by dylanaraps** [comment]
Yeah. We need a way to detect windows 10 vs 11 while inside WSL.

**Comment by dmadisetti** [comment]
in WSL `wmic.exe os get Version`
```
Version
10.0.22000
```

Windows 11 is still in preview mode, so this might not be worth examining until official release.

**Comment by MrVeink** [comment]
Windows 11 currently acts as an Windows 10 update. Until public release, you won't most likely have a way on detecting it.

**Comment by dylanaraps** [comment]
Let me know if the issue still occurs. Do not have Windows/WSL to test against.

**Comment by dmadisetti** [comment]
Close enough?
<img width="491" alt="image" src="https://user-images.githubusercontent.com/2689338/144783804-04256728-6b74-45c8-b633-23a5369a4368.png">
Lower is the old script, `neofetch.1` was the newest from `wget`ing github

Logs: https://gist.github.com/dmadisetti/4153cb71b09362bbf63386117b88a0bc

**Comment by dmadisetti** [comment]
Yeah, to access windows binaries `.exe` has to be specified https://gist.github.com/dmadisetti/4153cb71b09362bbf63386117b88a0bc#file-neofetch-1848-L28

<img width="231" alt="image" src="https://user-images.githubusercontent.com/2689338/144785394-5238e028-bf1b-4f58-aac4-b17669331f1f.png">

but also

<img width="272" alt="image" src="https://user-images.githubusercontent.com/2689338/144785586-773ce3a8-b790-4e5b-a7de-ff1d3115f717.png">

**Comment by dylanaraps** [comment]
Please try the latest master.

**Comment by dmadisetti** [comment]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/2689338/144788335-5b4156b5-d4ca-43e1-ba57-c9ab56662e98.png">

But at least it isn't hardcoded now? Feel free to blame microsoft

**Comment by dmadisetti** [comment]
Oh woops.
Truncated by th window:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/2689338/144788470-fb7130a0-0708-4443-b5a6-7eb7d6d46fb0.png">

**Comment by dmadisetti** [comment]
Update/Note: My system updates come from the pre-release channel. So this may not be representative of others. Maybe someone else can report with one of the october official releases?

I will say, I admire your dedication to your software, considering you don't even use windows.

**Comment by dmadisetti** [comment]
`wmic.exe os get Caption` gets distinguishing information
<img width="247" alt="image" src="https://user-images.githubusercontent.com/2689338/144866464-7cb2fe79-92ea-4f81-9322-cb6c295bd294.png">
