### ISSUE TITLE
Syntax error in SailfishOS

### ISSUE THREAD

**Issue by Smuger12** [dylanaraps/neofetch#1849]
## Description

When I run neofetch from SailfishOS (on Sony Xperia XA2 if thats matters lol) I get this error:
`./neofetch: line 36: syntax error: bad substitution`

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch from master branch.

## Config file

Using default config.

## Verbose log

The same error as I wrote in the description.

**Comment by dylanaraps** [comment]
I need a verbose log.

**Comment by Smuger12** [comment]
> I need a verbose log.

But when I run `./neofetch -vv 2> neofetchlog` command in the _neofetchlog_ there is only this line:
`./neofetch: line 36: syntax error: bad substitution`

**Comment by Smuger12** [comment]
Maybe this bug is because SailfishOS is using bash from BusyBox...

**Comment by dylanaraps** [comment]
That is ash, not bash. Neofetch requires bash. Look at https://github.com/dylanaraps/pfetch for POSIX shell.

**Comment by Smuger12** [comment]
> That is ash, not bash. Neofetch requires bash. Look at https://github.com/dylanaraps/pfetch for POSIX shell.

Thanks, closing this issue
