### ISSUE TITLE
Showing macOS Monterey instead of Ubuntu

### ISSUE THREAD

**Issue by agam778** [dylanaraps/neofetch#1853]
## Description

If you're suggesting a new feature then just a description will suffice.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)
No

#### Neofetch version
7.1.0/latest

## Screenshot
![image](https://user-images.githubusercontent.com/68941022/127731605-a0504bb9-ed6a-44c5-9d76-6598451e3541.png)

## Config file
[config.conf.txt](https://github.com/dylanaraps/neofetch/files/6910812/config.conf.txt)

## Verbose log
https://hastebin.com/raw/afajugohap

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by RickRollMaster101** [comment]
extremely hilarious tho lol

**Comment by dylanaraps** [comment]
Output of this command?: `lsb_release -sd`

**Comment by agam778** [comment]
tf
![image](https://user-images.githubusercontent.com/68941022/127731844-0f88304d-b571-4d25-884c-d042657bc7a8.png)

**Comment by agam778** [comment]
how do i fix this?

**Comment by dylanaraps** [comment]
No idea. This is an Ubuntu issue of some kind.

Closing.

**Comment by agam778** [comment]
kk
i'll see myself
