### ISSUE TITLE
Stop running on WSL2

### ISSUE THREAD

**Issue by miyouzi** [dylanaraps/neofetch#1854]
## Description

 - Windows 20H2 19042.1110
 - Ubuntu-20.04 (WSL2)

No config anything After installing neofetch.

Cannot show the items after `Shell`

Will not automatically exit, I need put `Ctrl+C`

#### Neofetch version
Neofetch 7.0.0

## Screenshot
![neofetch](https://user-images.githubusercontent.com/24269465/127756491-9cf7adb2-bf40-4bed-bc1b-7645e3848443.gif)

## Config file
no config yet

## Verbose log
[neofetchlog.zip](https://github.com/dylanaraps/neofetch/files/6912023/neofetchlog.zip)

**Comment by PurpleVibe32** [comment]
How did you insert the keys in the gif or video?

**Comment by miyouzi** [comment]
> How did you insert the keys in the gif or video?

It's the funtion of [ScreenToGif](https://github.com/NickeManarin/ScreenToGif)

**Comment by miyouzi** [comment]
I found where is the problem.

It's need to run  `VcXsrv` first

![image](https://user-images.githubusercontent.com/24269465/144974013-a5d7b7c9-197d-4b47-aa4e-bcfb4111ec4f.png)
