### ISSUE TITLE
Get wrong info on windows 11

### ISSUE THREAD

**Issue by zjuyk** [dylanaraps/neofetch#1855]
## Description

I install neofetch via scoop, but get wrong output.

1. OS: Garbled
2. Shell: I use powershell but output bash

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version

7.1.0

## Screenshot

![neofetch](https://user-images.githubusercontent.com/76436317/127760101-ba3f7c30-8e92-42b8-8eb5-c1a54edefc19.png)

## Config file

default config

**Comment by dylanaraps** [comment]
Fixed in master.

**Comment by dylanaraps** [comment]
Your `$SHELL` is bash is why it outputs it.
