### ISSUE TITLE
image doesn't display, st + w3m

### ISSUE THREAD

**Issue by Aurora-Aureus** [dylanaraps/neofetch#1856]
## Description
I was trying to configure neofetch, so that it displays an image. I am using the simple terminal, for which I read, that it supports the w3m image backend, I installed w3m, changed the config to use w3m instead of ascii and ran neofetch. Instead of displaying my wallpaper, it displayed nothing, not even a blank space. Seeing this, I downloaded terminology and changed the backend to tycat, this worked now, but st still didn't.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)
It does

#### Neofetch version
7.1.0
## Screenshot
https://imgur.com/a/9pbndt7
## Config file
https://controlc.com/f0745a8b
## Verbose log
https://controlc.com/460090c1
1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
when trying to append the output to a file, a file gets created, but it remains empty...
I have copied the output from the terminal, since that's the best I could do, sorry

**Comment by dylanaraps** [comment]
#1392

**Comment by Aurora-Aureus** [comment]
Oh, I apparently didn't search well enough for other issues. Thank you a lot, I'm sorry for any inconveniences I've caused

**Comment by dylanaraps** [comment]
No problem at all. :)
