### ISSUE TITLE
macOS ASCII logo Inconsistencies

### ISSUE THREAD

**Issue by C47F15H** [dylanaraps/neofetch#1865]
### Screenshot
![Unknown.png](https://user-images.githubusercontent.com/80169337/128587658-f16b12a0-fac4-4a87-b2ab-471cdf5bc433.png)

**Comment by C47F15H** [comment]
Line | error | Replace with
--|--|--
line 1 | `'c.` | `.c'`
line 5 |  `'` | `.` or `,`
line 5 | `looll` | `<space>.oll`
line 13, 14 | `.XMM` | `'XMM`
line 4 | `OMMMO,`| `lMM"`
last line | `.cooc,.`| `"cooc*"`
last line | `.,coo:.`| `"*coo'"`

**Comment by wallisch** [comment]
@dylanaraps Can be closed, already merged.

**Comment by cake03** [comment]
oof
