### ISSUE TITLE
Add Roblox OS

### ISSUE THREAD

**Issue by lc67846** [dylanaraps/neofetch#1868]
Pls Add Roblox os its linux based

**Comment by lc67846** [comment]
- [ ] Omg

**Comment by dylanaraps** [comment]
Cease the spam.

If you would like to be taken seriously, open a proper issue.

**Comment by lc67846** [comment]
it is im making a os and i need help with neofetch

**Comment by lc67846** [comment]
if u understod

**Comment by lc67846** [comment]
this is a real issue @dylanaraps

**Comment by dylanaraps** [comment]
You are welcome to open another issue. Please do it properly this time.
