### ISSUE TITLE
Add iOS iSH app ?

### ISSUE THREAD

**Issue by crazywhalecc** [dylanaraps/neofetch#1869]
## Description

If you're suggesting a new feature then just a description will suffice.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

<https://ish.app/>
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
What would you like me to do exactly?

What does neofetch output in ish right now?

**Comment by crazywhalecc** [comment]
Oh, sorry, I misunderstand this, I'll close issue.

But there's a question, neofetch logo only supports linux distribution? iSH app is just running alpine linux with busybox, not a distribution, but it is an independent app.
