### ISSUE TITLE
Jailbreak detection for iOS/iPadOS

### ISSUE THREAD

**Issue by turannul** [dylanaraps/neofetch#1874]
## Description

If you're suggesting a new feature then just a description will suffice.
The title is descriptive enough.
I wrote a script, but I don't know exactly how to integrate it.
[jailbreak-detect.txt](https://github.com/dylanaraps/neofetch/files/6985639/jailbreak-detect.txt)
Not good I guess, also I don't know how to detect odysseyra1n and legacy jailbreaks.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
7.1.0

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by SomethingGeneric** [comment]
This would be sweet!
