### ISSUE TITLE
Unable to find the config file on Windows 10.

### ISSUE THREAD

**Issue by bajajvatsal** [dylanaraps/neofetch#1901]
## Description

I have installed neofetch using scoop but unable to find the config file location on Windows 10 version 21H1 Build 19043.1165 

## Screenshot

Files inside the folder, scoop/apps/neofetch/7.1.0/

![image](https://user-images.githubusercontent.com/53997634/132289995-363ede77-82a6-4ff4-9e0a-330d1d4859e1.png)

**Comment by dylanaraps** [comment]
Create a new issue following the template. I need a verbose log, etc.

**Comment by bajajvatsal** [comment]
Just found out there is a different directory structure for windows & it is not as same as linux distro. Config files are stored in scoop\apps\neofetch\current\neofetch Windows. It would be helpful for windows users, if this information is mentioned in the Wiki.

**Comment by dylanaraps** [comment]
Take it up with Scoop. This issue is external to neofetch.
