### ISSUE TITLE
Feature- Bring back AmogOS

### ISSUE THREAD

**Issue by troler36** [dylanaraps/neofetch#1903]
## Description
in [this](https://github.com/dylanaraps/neofetch/commit/47f46834e788bfab383775ce9e2508c3d3827b28) commit AmogOS was removed.
I am asking for the commit to be reversed.
If not possible, to find out why it was removed.

**Comment by geshii** [comment]
maybe because it's AmogOS ?????

**Comment by ahrnbom** [comment]
Even if AmogOS is a nieche/joke OS, is there really any harm in having it in there?

**Comment by CrackedMatter** [comment]
I agree, AmogOS should have stayed.

**Comment by dylanaraps** [comment]
Feel free to send a PR with a logo not containing unicode characters. For the record, the AmogOS stuff has not yet made it into a release so I do not count it as ever being "in" neofetch.

**Comment by dylanaraps** [comment]
Please refrain from spamming this tracker with messages also.

**Comment by oshaboy** [comment]
Is there any reason that some ascii distros, including popular ones like Manjaro or NixOS, use unicode chars?  Or have you just not gotten around to replacing them with ascii logos?

**Comment by dylanaraps** [comment]
Those logos should also be fixed to use ASCII only characters. Will be getting around to it when I have more time.
