### ISSUE TITLE
[New Distro] CBL-Mariner

### ISSUE THREAD

**Issue by Krutonium** [dylanaraps/neofetch#1909]
Requesting Support for [CBL-Mariner](https://github.com/microsoft/CBL-Mariner) - A linux distribution for cloud computing by Microsoft. The Wiki more or less said this is all that is required.

**Comment by dylanaraps** [comment]
What does neofetch currently display when run on CBL-Mariner?

**Comment by Krutonium** [comment]
![Screenshot_linux2020 on QEMU_KVM_1](https://user-images.githubusercontent.com/3945538/133236889-6ac47223-a281-471e-9add-e880a6f8a18f.png)

**Comment by dylanaraps** [comment]
Just needs ascii art.

**Comment by Krutonium** [comment]
Yep

**Comment by alexcoder04** [comment]
Does CBL-Mariner actually have a logo? I couldn't find anything. Or should we use a generic Microsoft logo then?

**Comment by Krutonium** [comment]
Given my understanding that it's *primarily* used for Azure, perhaps https://www.vaisulweb.com/wp-content/uploads/2019/02/azure_logo_794_new.png this would be appropriate?

**Comment by alexcoder04** [comment]
That would make sense.
How about this one:
![scrot-211128_183106](https://user-images.githubusercontent.com/70093931/143779144-b7b13aa6-f6ae-4330-836d-bf1326d45c6c.png)
?

**Comment by Krutonium** [comment]
That looks reasonable to me, though afaik it's not my call.

**Comment by dylanaraps** [comment]
Send a PR. :)

**Comment by dylanaraps** [comment]
Thanks @alexcoder04 and everyone.
