### ISSUE TITLE
Adding Custom Info

### ISSUE THREAD

**Issue by Mat-DB** [dylanaraps/neofetch#1915]
Best,

I'm trying to get a custom info message to work, but I can't get it to work. I'd like to have the load average in the column as well.
The wiki page describing how to ad custom information is not very clear and I searched online. But I haven't found a solution.

Thanks in advance.
Regards, Mat

**Comment by dylanaraps** [comment]
Open another bug report with more information (things you have tried, config file, verbose log, etc).
