### ISSUE TITLE
Uebzerzug preview doesn't close

### ISSUE THREAD

**Issue by elwolf6** [dylanaraps/neofetch#1921]
## Description

It don't close like if i run neofetch I have to press ctrl + c but this isn't an image with lf even tho ueberzug still has to loop in it

If you're suggesting a new feature then just a description will suffice.

- [✅] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0
## Screenshot
![Issue Image](https://elwolf6.feen.us/a517pm.png)
## Config file
https://hastebin.com/amuvokafuz.shell
## Verbose log
https://hastebin.com/ubadumomij.diff
1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
See: #1392
