### ISSUE TITLE
Wrong theme displayed Plasma 5.23.2

### ISSUE THREAD

**Issue by PascalDutch** [dylanaraps/neofetch#1941]
## Description

When using KDE Plasma 5.23.2 I changed the theme globally (to my best knowledge, using "global theme"  in settings). I changed to Aritim-dark, yet neofetch shows somehow Breeze Light. This only happens for Plasma themes, GTK works fine.

- [ x] Does this issue still occur in the master branch?

#### Neofetch version
7.1.0

## Screenshot
![image](https://user-images.githubusercontent.com/32418202/139598044-c40d3a09-7af7-43f4-a2c0-b780a1221691.png)

## Config file
No idea where this is located, I didn't configure anything.

## Verbose log
https://pastebin.com/3dyuyUW4

**Comment by getchoo** [comment]
Having this same issue on `7.1.0` and the `master` branch

## Screenshot
![image](https://user-images.githubusercontent.com/48872998/140178827-127c5f08-5937-4575-8ed3-6b84881bde43.png)

## Config File
n/a

## Verbose log
https://pastebin.com/hMDyCqPg

**Comment by PascalDutch** [comment]
Did some digging, this seems to be a KDE issue. I think I open a ticket there.

**Comment by noobishply** [comment]
> Did some digging, this seems to be a KDE issue. I think I open a ticket there.

Hey, can you post the link of the issue where you posted it? Thanks.

**Comment by PascalDutch** [comment]
Hey, sorry I wasn't be able to open a ticket (haven't got time to it) and to be honest forgot about it.


________________________________

**Comment by getchoo** [comment]
@PascalDutch I actually opened an issue myself on their bugtracker already, just seems like I missed a reply to it; just updated it so we'll see where it goes.

(issue link)[
