### ISSUE TITLE
Question; As for Model, why use "product_*" instead of "board_*"

### ISSUE THREAD

**Issue by AliensInc** [dylanaraps/neofetch#1955]
## Description

As the heading says: As for Model, why use 'product_*' instead of 'board_*'
DMI_BOARD_NAME is often more useful
than DMI_PRODUCT_NAME, especially on standalone motherboards.
So either go for DMI_BOARD_NAME or test if DMI_PRODUCT_NAME is "O.E.M' then go for DMI_BOARD_NAME.
I got plenty of ASUS M/B's and none of the will display the model as they are all shown as OEM thus filtered away.

- [ ] Does this issue still occur in the master branch? (**Required if issue**)
Yes, v 7.1.0

#### Neofetch version
Yes, v 7.1.0

## Screenshot
With Current 7.1.0
`
                  -`                    basher52@ArchGamer
                  .o+`                   ------------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Kernel: Linux 5.14.16-arch1-1
               `+oooooo:                 Uptime: 3 days, 6 hours, 5 mins
               -+oooooo+:                Packages: 1397 (pacman)
             `/:-:++oooo+:               Shell: /bin/bash 5.1.8
            `/++++/+++++++:              Resolution: 1920x1080 @ 144.00Hz
           `/++++++++++++++:             WM: awesome
          `/+++ooooooooooooo/`           Theme: Arc-Dark [GTK2/3]
         ./ooosssso++osssssso+`          Icons: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Terminal: alacritty
       -osssssso.      :ssssssso.        CPU: AMD FX-8120 (8) @ 3.568GHz [29.8°C]
      :osssssss/        osssso+++.       GPU: NVIDIA GeForce GTX 1060 6GB
     /ossssssss/        +ssssooo/-       Memory: 4.13GiB / 15.58GiB (26%)
   `/ossssso+/:-        -:/+osssso+-
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/

With my patched version
                   -`                    basher52@ArchGamer
                  .o+`                   ------------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: SABERTOOTH 990FX Rev 1.xx
               `+oooooo:                 Kernel: Linux 5.14.16-arch1-1
               -+oooooo+:                Uptime: 3 days, 6 hours, 7 mins
             `/:-:++oooo+:               Packages: 1397 (pacman)
            `/++++/+++++++:              Shell: /bin/bash 5.1.8
           `/++++++++++++++:             Resolution: 1920x1080 @ 144.00Hz
          `/+++ooooooooooooo/`           WM: awesome
         ./ooosssso++osssssso+`          Theme: Arc-Dark [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: alacritty
      :osssssss/        osssso+++.       CPU: AMD FX-8120 (8) @ 3.411GHz [22.0°C]
     /ossssssss/        +ssssooo/-       GPU: NVIDIA GeForce GTX 1060 6GB
   `/ossssso+/:-        -:/+osssso+-     Memory: 4.16GiB / 15.58GiB (26%)
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/
 .`                                 `/

I just changed product_name and product_version to board_name and board_version
in the get_module() section. Also add board_vendor as that  in my case says: 'ASUSTeK COMPUTER INC.'

`
## Config file
Non added

## Verbose log
None added

**Comment by AliensInc** [comment]
Sorry, can't get the 'code' to be viewed properly :(

**Comment by AliensInc** [comment]
example:
elif [[ -f /sys/devices/virtual/dmi/id/board_name ||
                    -f /sys/devices/virtual/dmi/id/board_version ||
                    -f /sys/devices/virtual/dmi/id/board_vendor ]]; then
                model=$(< /sys/devices/virtual/dmi/id/board_vendor)
                model+=" $(< /sys/devices/virtual/dmi/id/board_name)"
                model+=" $(< /sys/devices/virtual/dmi/id/board_version)"

**Comment by dylanaraps** [comment]
I don't think this feature is worthwhile. Thanks for the issue.
