### ISSUE TITLE
Feature suggestion: Allowing multiple info items to be displayed on one line.

### ISSUE THREAD

**Issue by Salyrus** [dylanaraps/neofetch#1986]
## Description

Would it be possible to allow users to display more than one item on the same line? In some cases, this might be useful for more advanced customization. For example, I'm trying to line up the amount of info lines displayed with the height of the ASCII, but I would only be able to do so, and still display all info I want, by having mutliple items on one line.

The specific items I was thinking about combining is the distro and kernel, which would look something like `Void Linux (5.15.6_1)`, saving a line in the neofetch result.

Is this possible already? I dug through current and past issues as well as the wiki, but saw no reference to such a thing being possible.

**Comment by dylanaraps** [comment]
The configuration file is a shell script. Total freedom is given as to how neofetch displays information.
See this Wiki page for more information: https://github.com/dylanaraps/neofetch/wiki/Customizing-Info

**Comment by xeruf** [comment]
I looked at that wiki page in detail, but was unable to find a way to easily implement the requested feature - I wanted to combine `info wm` and `info wm_theme` into one line, but could not find a way short of recreating the functions.

After some experimenting, this is what I ended up with, maybe worth adding to the wiki:
```sh
pinfo() {
    info "$@" | sed -e 's/\x1b\[[0-9;]*[mC]//g' | xargs
}

...
    prin "Terminal" "$(pinfo term) $(pinfo "with font" term_font) running $(pinfo shell)"
    info "DE" de
    prin "WM" "$(pinfo wm) $(pinfo wm_theme)"
    prin "Theme" "$(pinfo theme) $(pinfo "with icons" icons)"
...
```
