### ISSUE TITLE
autorun of neofetch

### ISSUE THREAD

**Issue by loewal** [dylanaraps/neofetch#1987]
Sorry for coming back on this 'issue'!
I asked why neofetch is run automatically.
After a long search I discovered that, when installing armbian-config, following happens:

An executable file with the name "mymotd.sh" is placed in "/etc/myprofile.d", with one line saying "neofetch" and run at login.
On other distrubutions I found that I had to either create this same situation or place the command at the end of .bashrc or .zshrc.

Perhaps this can other people help temporarily disable auto-execute.

**Comment by dylanaraps** [comment]
This is not a neofetch issue. This is a distribution issue.
