### ISSUE TITLE
[Documentation] Include install guide for OpenWRT 

### ISSUE THREAD

**Issue by aindriu80** [dylanaraps/neofetch#1992]
## Description

No mention of OpenWRT

#### Neofetch version
Latest

# Screenshot
![2021-12-11_15-21](https://user-images.githubusercontent.com/8885837/145681855-23343180-9620-4079-af23-ad171924a0ba.png)

## Instructions

# Install Git ->
`opkg update && opkg install git git-http`

# Install Make ->
`opkg install make`

# Clone Neofetch ->
`git clone https://github.com/dylanaraps/neofetch`

# Build and Execute Neofetch ->

`cd neofetch/`
`make install`
`neofetch`

**Comment by dylanaraps** [comment]
This is up to others. The Wiki should be open to all. 

The universal installation method works everywhere as an alternative.
