### ISSUE TITLE
MacOS wrong resolution

### ISSUE THREAD

**Issue by PatrickBK** [dylanaraps/neofetch#1993]
## Description
Just installed Neofetch (stable 7.1.0) on my MB Pro (M1) and it reports the wrong display resolution. It does so both with my 4K external display as with the 'internal' display.

#### Neofetch version
7.1.0

## Screenshot
![Schermafbeelding 2021-12-12 om 19 14 08](https://user-images.githubusercontent.com/526917/145724406-e68bcac2-af64-45f1-9118-9868f0f90318.jpg)
![Schermafbeelding 2021-12-12 om 19 13 26](https://user-images.githubusercontent.com/526917/145724414-ea7f39f2-0264-4e07-895e-491e7324249f.jpg)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

https://pastebin.com/Wkqgt1aF

**Comment by dylanaraps** [comment]
Duplicate of: https://github.com/dylanaraps/neofetch/issues/1067
