### ISSUE TITLE
[FEATURE REQUEST] Show KDE libraries versions of Plasma, Frameworks and QT

### ISSUE THREAD

**Issue by RafaelLinux** [dylanaraps/neofetch#2013]
As KInfo (Plasma application) shows, it will be very interesting to show, when using KDE Plasma:

- Plasma version
- Frameworks version
- QT version

Thank you

**Comment by mistraube** [comment]
See #2019

**Comment by RafaelLinux** [comment]
Awesome!!! Just fast and better than expected.

Thank you
