### ISSUE TITLE
Can't get images working on Konsole (Gentoo)

### ISSUE THREAD

**Issue by GanerCodes** [dylanaraps/neofetch#2052]
I'm clueless at this point, I literally cannot get images working at all. I'm attaching a bunch of images to show hopefully everything relevent because I'm completely lost at this point. Neofetch just shows nothing in the spot an image does. w3m and fbi don't work either.

Neofetch vv log: https://www.toptal.com/developers/hastebin/ifizatijot.sql
![image](https://user-images.githubusercontent.com/34655998/153744987-42b2a35e-a0ad-4ff6-b0c3-c3060f3933a5.png)
![image](https://user-images.githubusercontent.com/34655998/153744992-fd333001-7a57-4ea0-990d-3b6fb7e9b044.png)
Literaly my entire kernel configuration: https://www.toptal.com/developers/hastebin/hosupimucu.ini

make.conf:
```
CHOST="x86_64-pc-linux-gnu"

USE="X gtk wayland nvidia opengl gles2 dbus icu v4l elogind fbcon symlink
hangouts pulseaudio bluetooth btpclient widgets kms libkms samba
python_targets_python3_9 python_targets_python3_10 python tk imlib 
networkmanager multilib joystick browser nvenc grub ssl freerdp rdp
-systemd -consolekit -gnome -gpm -telemetry -crypt"

MAKEOPTS="-j8 -l8"
EMERGE_DEFAULT_OPTS="-j8"
FEATURES="parallel-install sign"
PORTAGE_NICENESS=1
CLEAN_DELAY="0"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"
GENTOO_MIRRORS="http://gentoo.osuosl.org/ http://www.gtlib.gatech.edu/pub/gentoo http://distfiles.gentoo.org/"
VIDEO_CARDS="nvidia fbdev"
GRUB_PLATFORMS="efi-64"
INPUT_DEVICES="libinput synaptics joystick keyboard mouse"
# No idea if this following line is needed or does anything
KWIN_DRM_USE_EGL_STREAMS=1

COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

LC_MESSAGES=C
```

**Comment by bekaertruben** [comment]
w3m doesn't work on wayland. Try chafa or another image backend

**Comment by GanerCodes** [comment]
I'm not running wayland [although I for some reason do have it in my use flags]

Edit: chafa works but because it's text-based-ish the quality is really meh

**Comment by bekaertruben** [comment]
Terminal image solutions are all hacky and inconsistent between terminals. Chafa looks pretty nice on kitty and alacritty for me, but not konsole.

**Comment by GanerCodes** [comment]
Thing is on my laptop I remember I had w3m working on Konsole, I just can't get it working now, no idea if I'm missing a lib or messed up a use flag or something

**Comment by GanerCodes** [comment]
w3m had some update and it randomly fixed itself
