### ISSUE TITLE
Windows 11 Ascii Art (Scoop)

### ISSUE THREAD

**Issue by abhnva** [dylanaraps/neofetch#2091]
## Description
I'm using Windows 11. I installed neofetch with **Scoop**. I can't find Windows 11 ascii art in the list.

#### Neofetch version
7.1.0

**Comment by scottbeamer** [comment]
I'd like to know how to get it show the Windows 11 logo instead of the old Windows 7 logo.  I'm surprised it's not at least using the Windows 10 logo.

![image](https://user-images.githubusercontent.com/62769036/163248917-85226370-845e-4908-991e-f5273dc89cf1.png)

**Comment by Deltara3** [comment]
Replace the neofetch file in `%USERPROFILE%\scoop\apps\neofetch\current` with the one from the master branch.

**Comment by abhnva** [comment]
Thanks, it worked. 
![image](https://user-images.githubusercontent.com/93075695/163671238-4af32b5f-1d9a-4ae7-8dcf-578be9c5dd94.png)

**Comment by KBeDevel** [comment]
Shouldn't this be published as a new feature release?
