### ISSUE TITLE
Killed: 9 M1 Macbook Air

### ISSUE THREAD

**Issue by Aem1024** [dylanaraps/neofetch#2108]
Neofetch won't launch.
It gives me the error Killed: 9
2020 Macbook Air (M1)

**Comment by thebitstick** [comment]
Any other helpful information?

What version of macOS are you running?
What terminal app are you using?
Where did you download neofetch from (Homebrew, MacPorts, Nix)?

Additional information always help in diagnosing the problem.

**Comment by Aem1024** [comment]
> Any other helpful information?
> 
> What version of macOS are you running? What terminal app are you using? Where did you download neofetch from (Homebrew, MacPorts, Nix)?
> 
> Additional information always help in diagnosing the problem.

12.3 Monterey
Built in terminal with both Rosetta enabled and disabled
Homebrew

**Comment by Aem1024** [comment]
Fixed it by updating bash
