### ISSUE TITLE
64-bit Raspbian is incorrectly detected as Debian

### ISSUE THREAD

**Issue by illegitimate-egg** [dylanaraps/neofetch#2161]
## Description

On the 64-bit build of Raspberry Pi OS, `neofetch` prints out the Debian logo, whereas on 32-bit versions it prints out the Raspberry Pi logo.

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
`NeoFetch 7.1.0`
## Screenshot
![https://i.imgur.com/3YMIiVf.png](https://i.imgur.com/3YMIiVf.png)
## Config file
Default Config
## Verbose log

[PasteBin](https://pastebin.com/V4PZAHc1)

**Comment by Un1q32** [comment]
This is a bug with Raspbian.  Raspbian 64 bit identifies itself as Debian, but 32 bit doesn't.

**Comment by illegitimate-egg** [comment]
oh ok

**Comment by duarch** [comment]
Why this was closed?

**Comment by Un1q32** [comment]
> Why this was closed?

not really solvable, its impossible to tell the difference between raspberry pi os and debian
