### ISSUE TITLE
Very slow loading packages count

### ISSUE THREAD

**Issue by amithiel** [dylanaraps/neofetch#2163]
Hi!
After years of using neofetch in every single distro (being desktop or server), i'm experiencing the first issue that's driving me mad:

Problem: Every time i reboot my server, the first time neofetch runs...it gets stuck on the package listing

![time](https://user-images.githubusercontent.com/848214/180764322-f81e9ac6-c48f-43ea-b4b9-27f1e15ec9e7.png)

I was using ubuntu server 20.04, and never had such issue. Some days ago, i decided to fresh install ubuntu server 22.04.
Can't for the life of me figure out what's wrong.

cheers

Neofetch 7.1.0 ( also tried the master branch )
Log: https://pastebin.com/0EFbPmbz

**Comment by pendula95** [comment]
Same issue on Fedora, packages are slowest and it is bugging my UX

**Comment by pendula95** [comment]
What I found is that the code in version 7.1.0 uses old code where packages number was obtained by doing `rpm -qa`
After checking the code from master there is quick [fix](https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L1570) that obtains this data from dnf cache file. So I just used code from master to resolve the issue. 

@amithiel In your case it can be dpkg is slow or snap is slow. This command is used to get data `dpkg-query -f '.\n' -W`
I also have snap installed but it was fast in my case so I guess that is not the issue. You can check that also `snap list`
I am not familiar with dpkg but there might be a faster way to get info about installed packages.

**Comment by amithiel** [comment]
> What I found is that the code in version 7.1.0 uses old code where packages number was obtained by doing `rpm -qa` After checking the code from master there is quick [fix](https://github.com/dylanaraps/neofetch/blob/ccd5d9f52609bbdcd5d8fa78c4fdb0f12954125f/neofetch#L1570) that obtains this data from dnf cache file. So I just used code from master to resolve the issue.
> 
> @amithiel In your case it can be dpkg is slow or snap is slow. This command is used to get data `dpkg-query -f '.\n' -W` I also have snap installed but it was fast in my case so I guess that is not the issue. You can check that also `snap list` I am not familiar with dpkg but there might be a faster way to get info about installed packages.

well, i tried pfetch and also screenfetch and they worked with no issues, which led me to blame snaps (since they only list dpkg). i'm fed up with ubuntu anyway, i migrated my server to debian stable, and i have zero issues now.
cheers
