### ISSUE TITLE
Error with showing ram usage

### ISSUE THREAD

**Issue by Zbysiu3cytryny** [dylanaraps/neofetch#2176]
- [X] Does this issue still occur in the master branch? (**Required if issue**)
#### Neofetch version
7.1.0-2
## Screenshot
![image](https://user-images.githubusercontent.com/52840240/183736382-fa6ba425-7955-45b3-a9af-2ce202e976b8.png)
## Config file
[config.txt](https://github.com/dylanaraps/neofetch/files/9293828/config.txt)
## Verbose log
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/9293819/neofetchlog.txt)

**Comment by Chikmyvoltage** [comment]
`00036280: value too great for base (error token is "00036280")`

Looking into this, I believe it thinks its octal because of the leading zero when parsing **/proc/meminfo**... but the input is decimal and padded with zeros.

One way to fix this is to strip the leading zeros within the script.

Please apply this diff and report:

```
--- /usr/bin/neofetch	2022-08-20 03:17:00.242076721 +0300
+++ /usr/bin/neofetch.bak	2022-08-20 03:17:26.740413196 +0300
@@ -2540,6 +2540,7 @@
             # MemUsed = Memtotal + Shmem - MemFree - Buffers - Cached - SReclaimable
             # Source: https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
             while IFS=":" read -r a b; do
+            	b=${b#"${b%%[1-9]*}"}
                 case $a in
                     "MemTotal") ((mem_used+=${b/kB})); mem_total="${b/kB}" ;;
                     "Shmem") ((mem_used+=${b/kB}))  ;;
 ```

**Comment by Zbysiu3cytryny** [comment]
> `00036280: value too great for base (error token is "00036280")`
> 
> Looking into this, I believe it thinks its octal because of the leading zero when parsing **/proc/meminfo**... but the input is decimal and padded with zeros.
> 
> One way to fix this is to strip the leading zeros within the script.
> 
> Please apply this diff and report:
> 
> ```
> --- /usr/bin/neofetch	2022-08-20 03:17:00.242076721 +0300
> +++ /usr/bin/neofetch.bak	2022-08-20 03:17:26.740413196 +0300
> @@ -2540,6 +2540,7 @@
>              # MemUsed = Memtotal + Shmem - MemFree - Buffers - Cached - SReclaimable
>              # Source: https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
>              while IFS=":" read -r a b; do
> +            	b=${b#"${b%%[1-9]*}"}
>                  case $a in
>                      "MemTotal") ((mem_used+=${b/kB})); mem_total="${b/kB}" ;;
>                      "Shmem") ((mem_used+=${b/kB}))  ;;
> ```

Thanks for help, but kernel maintainer fixed that problem some time ago
