### ISSUE TITLE
Split neofetch into multiple files

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/neofetch#218]
neofetch is huge with almost 3000 lines of code. It should be split into multiple files.

We can also add a script that combines all the little scripts into a single one, making possible distributing *neo*fetch in a single file.

**Comment by dawidd6** [comment]
![giphy](https://cloud.githubusercontent.com/assets/9713907/14256241/787c0842-fa98-11e5-86da-2ea960395158.gif)

**Comment by tudurom** [comment]
*3000

**Comment by dylanaraps** [comment]
I *really* don't want to do this but I'll start work on it anyway.

**Comment by tudurom** [comment]
Why not?

**Comment by dylanaraps** [comment]
See **#219**

**Comment by konimex** [comment]
I really want to know why should we split this into many files. As @tudurom mentioned in #219 the speed is exactly the same. `screenfetch` has ~4000 lines in their code. IMO there's just no technical advantage to split it up.

**Comment by tudurom** [comment]
If we split neofetch in multiple files, it would be easier to contribute on it.

**Comment by dylanaraps** [comment]
It's still very easy to contribute to neofetch as the script is split up into folds which act as a break between functions/blocks. See these screenshots showing how easy it is to navigate to a specific info function:

![2016-04-11-020256_1020x898_scrot](https://cloud.githubusercontent.com/assets/6799467/14413671/8df854d8-ffc4-11e5-8488-d930768bc904.png)
![2016-04-11-020307_1020x898_scrot](https://cloud.githubusercontent.com/assets/6799467/14413672/8dfbc7bc-ffc4-11e5-9f2f-1bb006845454.png)

**Comment by tudurom** [comment]
iirc this kind of folds are for vim only

**Comment by dylanaraps** [comment]
The folds should work in any text editor that supports code folding, what text editor are you using?

https://en.wikipedia.org/wiki/Code_folding#Software_with_code_folding_capability

**Comment by tudurom** [comment]
i use neovim. neovim has a known issue for taking long to open long files.

**Comment by dylanaraps** [comment]
I'm also using neovim and have no issues opening the file, hm.

**Comment by tudurom** [comment]
Let's set a cap for when to split neofetch. Let's say if it exceeds 5000 lines, we split it.

**Comment by dylanaraps** [comment]
Nope. 

I don't want to split the script up into multiple files and I don't see the benefit in doing 
so.

I'm closing this issue now, if anybody can implement this with some clear benefits I'll 
think about merging it.
