### ISSUE TITLE
Package detection

### ISSUE THREAD

**Issue by 465joe55** [dylanaraps/neofetch#221]
Neofetch only displays 1 package installed under arch linux.

**Comment by dawidd6** [comment]
Just tried latest master and it's showing proper value for me on Arch

**Comment by dawidd6** [comment]
Give us output of these commands:
```
pacman -Qq --color never | wc -l
```
```
pacman -Qq --color never
```

**Comment by dylanaraps** [comment]
ping @465joe55

**Comment by dylanaraps** [comment]
Do you by any change have `dpkg` installed on arch?

**Comment by dylanaraps** [comment]
Fixed.
