### ISSUE TITLE
Wallpaper not displayed correctly while using urxvt

### ISSUE THREAD

**Issue by xstreamx** [dylanaraps/neofetch#222]
I have installed neofetch on my ubuntu. But wallpaper displayed like this photo. Wallpaper only displayed normally while using urxvt default font. I have imagemagick, w3m-img installed. Please help me fix this problem.
![problem](https://cloud.githubusercontent.com/assets/14888918/14411013/7ce4abf6-ff6f-11e5-80d3-beffe7ff0e61.png)

**Comment by konimex** [comment]
Issue #105 also dealt with the same thing, I guess? For now, try to use a bitmap font since I also get this bug when I use Xft fonts.

**Comment by xstreamx** [comment]
Yes, I try using terminus font too and image displayed normally. Wheter this issue come from w3m-img?

**Comment by dylanaraps** [comment]
URxvt and xft fonts don't play nicely with w3m-img, this isn't a neofetch issue.

**Comment by dylanaraps** [comment]
This issue has finally been fixed.
