### ISSUE TITLE
Should make a new release for distro packaging

### ISSUE THREAD

**Issue by slackingfred** [dylanaraps/neofetch#2237]
## Description

The version in many distros' package repo (Ubuntu, Arch, etc.) is still 7.1.0, which was released 2 years ago and contains some minor bugs that has long been fixed in master (like https://github.com/dylanaraps/neofetch/issues/1274).

Why is there no release after August 2020? Is there a plan for the next release?

**Comment by hykilpikonna** [comment]
This repo doesn't seem to be maintained anymore, maybe check out HyFetch

> [HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many issues and pull requests.
> 
> Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by slackingfred** [comment]
Related: https://github.com/hykilpikonna/hyfetch/issues/37
