### ISSUE TITLE
Specifying a different distro ascii with --ascii_distro doesn't work on Windows.

### ISSUE THREAD

**Issue by dar-irl** [dylanaraps/neofetch#224]
Attempting to display another distro's ascii with the --ascii_distro option doesn't change the logo, and neofetch displays the windows10 ascii regardless of the distro specified.

System: Cygwin w/ Mintty terminal emulator

Neofetch version: 1.6

Operating system: Windows 10

Verbose log: neofetchlog is returning

`/bin/neofetch: line 2: vim:: command not found`
`[6n[c` 

even though vim is installed. Definitely an issue on my end, once I get it sorted out I'll post a proper log.

**Comment by dylanaraps** [comment]
I can reproduce this, thanks for reporting it.

About the verbose log issue, you're getting the error because the instructions are for neofetch 1.7. I'll update them for users on 1.6 also.

**Comment by dylanaraps** [comment]
Fixed.

**Comment by dylanaraps** [comment]
Expect 1.7 to be released this weekend, until then you can use the latest git master. :)
