### ISSUE TITLE
Passing ASCII art from `ascii-image-converter`

### ISSUE THREAD

**Issue by leana8959** [dylanaraps/neofetch#2259]
## Description

- [x] Does this issue still occur in the master branch?

Hello,
I tried to use `neofetch` with an artwork I have generated with `ascii-image-converter`. However, it breaks neofetch if the artwork is generated with colour. I understand that neofetch isn't supposed to be used this way, but I'd still like to find a solution since it's not practical to recreate the nuances of colour using only six colours, manually.  
Is there any way to use an ASCII artwork with colour, without using the colour flags internally defined by neofetch?

Thanks a lot :)

## Screenshot 
Image with colour: no info is shown (more like pushed to the side somehow)
<img width="1500" alt="With color" src="https://user-images.githubusercontent.com/87855546/206852763-5558e760-a8e9-4684-a22b-d5b92cfdcf7a.png">

Image without colour: infos are shown correctly
<img width="1500" alt="Without color" src="https://user-images.githubusercontent.com/87855546/206852801-e3e0dc0d-e50f-43a0-bb24-e718387da705.png">

## [Config file, Verbose log, ASCII artwork](https://gist.github.com/leana8959/1dbae98d5c428d695bc5f60891837448)

Thank you !

**Comment by hykilpikonna** [comment]
This is fixed in HyFetch 1.4.0 / neowofetch 7.3.0 by the pull request https://github.com/dylanaraps/neofetch/pull/1543.

> This PR is merged into hyfetch since this repo (dylanaraps/neofetch) seems no longer maintained.
> 
> [HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.
>
> Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by leana8959** [comment]
Thanks for the reply, I tried ~~neowofetch~~ hyfetch with the command neowofetch and it worked like a charm :)  
Thanks !
![image](https://user-images.githubusercontent.com/87855546/206867142-002c2bdb-09bf-4e80-bb86-167e0a9951c3.png)
