### ISSUE TITLE
ascii_len calculation problem

### ISSUE THREAD

**Issue by tobyprime** [dylanaraps/neofetch#2265]
## Description

When I use a custom ascii drawing, the color code is also counted as a character length, resulting in a long interval between the ascii logo and the system info.

[I think it can add a cmd param to customize `ascii_len`](https://github.com/dylanaraps/neofetch/issues/2265)

- [x] Does this issue still occur in the master branch? (**Required if issue**)

#### Neofetch version
Neofetch 7.1.0
## Screenshot
![image](https://user-images.githubusercontent.com/89194556/208418617-9357f71e-3aef-44b6-8f00-6e464f0fc131.png)

**Comment by hykilpikonna** [comment]
This is fixed in HyFetch 1.4.0 / neowofetch 7.3.0 by the pull request https://github.com/dylanaraps/neofetch/pull/1543.

Instead of manually taking in ascii-len as a parameter, the fix in HyFetch automatically calculates the length without color escape sequences.

> This PR is merged into hyfetch since this repo (dylanaraps/neofetch) seems no longer maintained.
> 
> [HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.
>
> Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by tobyprime** [comment]
好诶，这就是我希望的
