### ISSUE TITLE
Void Linux package count 0.

### ISSUE THREAD

**Issue by TheDoctorsLife** [dylanaraps/neofetch#228]
## Description
After installing the void linux package, I've noticed that the package count has remained zero, whereas screenfetch correctly reports it as 1038.

## System Information
OS: Void Linux x86_64
Kernel: Linux 4.4.6_1 x86_64
Shell: /bin/zsh
WM: bspwm
CPU: AMD Turion Dual-Core RM-75 (2) @ 2.2GHz
GPU: NVIDIA C77 GeForce 8200M G
Memory: 1849MB / 2760MB

#### Neofetch version
1.6

#### Operating system
GNU/Linux 4.4.6_1
## Screenshot (If relevant)
![screenfetch](http://i.imgur.com/gSAPlIe.png)
![neofetch](http://i.imgur.com/QcASr1z.png)

## Verbose log
http://sprunge.us/UEYB

**Comment by dylanaraps** [comment]
Thanks for reporting this, I'm installing Void Linux now to fix this.

**Comment by dylanaraps** [comment]
Do you by any chance have another package manager installed alongside `xbps-query`? 
(`pacman`, `dpkg`, `rpm` and etc)

**Comment by TheDoctorsLife** [comment]
I only have pip installed besides xbps, 95% of packages are from the xbps package manager

**Comment by dylanaraps** [comment]
Does #229 fix your isssue?

It changes the package function to work when the user has multiple package managers installed.

**Comment by TheDoctorsLife** [comment]
It appears so, ![#229](http://i.imgur.com/3daVMfa.png)

**Comment by dylanaraps** [comment]
Awesome, I'm going to do some testing with various distros and #229 before I merge it.

I also just noticed that battery seems to be broken for you, what's the output for these commands?

- `cat /sys/class/power_supply/BAT*/capacity`
- `cat /sys/class/power_supply`

**Comment by TheDoctorsLife** [comment]
```
╭─ 02:58:55  benjamin@benjamin-laptop  ~/bin/neofetch   master  
╰─ cat /sys/class/power_supply/BAT*/capacity                                                                                       ✓ 
cat: /sys/class/power_supply/BAT0/capacity: No such device
╭─ 02:59:06  benjamin@benjamin-laptop  ~/bin/neofetch   master  
╰─ cat /sys/class/power_supply                                                                                                   1 ↵ 
cat: /sys/class/power_supply: Is a directory
```
As a note before you get to concerned, my battery won't hold a charge anymore and linux sometimes thinks its charging. If you want I can help you investigate this some, but I only have that battery there for when I order a replacement.

**Comment by dylanaraps** [comment]
The fix is now in master, thanks for reporting this!

**Comment by TheDoctorsLife** [comment]
Not a problem, thanks for the fix!

**Comment by dylanaraps** [comment]
Thanks. :)

**Comment by TheDoctorsLife** [comment]
Not a problem.
