### ISSUE TITLE
Rename neofetch to an easier remembered and more relevant name 

### ISSUE THREAD

**Issue by estatistics** [dylanaraps/neofetch#2283]
Each time that i wanted to find system info, i could not remember at all the name of this (very good) util. 

So , I propose either rename your util to an easier remembered and more relevant name OR include in your install / help file how to create an executable symbolic link to this program which will do that. 

e.g: sudo ln -s  /usr/bin/neofetch /usr/bin/system-info2

Then you need to run system-info2 in order to find system information in bash. :)

**Comment by hykilpikonna** [comment]
You can just use an alias for that.

Like, in your `~/.profile` or `~/.zprofile`

```
alias system-info2=neofetch
```

**Comment by estatistics** [comment]
I didnt know that. Thanks.
