### ISSUE TITLE
Red Debian logo?

### ISSUE THREAD

**Issue by eggbean** [dylanaraps/neofetch#2290]
Is there any way to force the Debian logo to come up in red rather than white?

I've been using [linux_logo](https://github.com/deater/linux_logo) for around 15 years, but started using neofetch for OSs that it doesn't support. I might as well now use neofetch for Debian as well now, but I would prefer the logo to be red. I would rather be able to do this in config rather than adding my own logo, but if I can do that without altering the package but add it using config, that would be fine too.

**Comment by eggbean** [comment]
Doesn't matter. I just realised that it's a bash file.

**Comment by eggbean** [comment]
Here's my mod if anybody else wants to make it red:

`$ neofetch --ascii debian_red`

debian_red:
```
${c1}       _,met$$$$$gg.
    ,g$$$$$$$$$$$$$$$P.
  ,g$$P"        """Y$$.".
 ,$$P'              `$$$.
',$$P       ,ggs.     `$$b:
`d$$'     ,$P"'   .    $$$
 $$P      d$'     ,    $$P
 $$:      $$.   -    ,d$$'
 $$;      Y$b._   _,d$P'
 Y$$.    `.`"Y$$$$P"'
 `$$b      "-.__
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

**Comment by hykilpikonna** [comment]
Or you can use the existing `--ascii_colors` argument like: `neofetch --ascii_distro debian --ascii_colors 7 1 1`

![image](https://user-images.githubusercontent.com/22280294/217606197-dedb0185-faf0-4871-86f9-7630e134f6dd.png)

**Comment by eggbean** [comment]
Thanks, that makes it easier.
