### ISSUE TITLE
[bug] part of the ascii art is printed below the command prompt

### ISSUE THREAD

**Issue by ghost** [dylanaraps/neofetch#2302]
## Description
Part of the ascii art for the Ubuntu logo is printed below the command prompt when `neofetch` is invoked. I haven't edited the config file, so it's all using the default settings. The issue is not constrained to just the new Ubuntu logo, I've tested it with a few other logos as well, and found that the new Arch logo, the CentOS logo, and the LinuxMint logo are all broken as well. This leads me to believe that there are others that are also broken but I've only checked a few logos. It's worth noting that **not all of the logos are broken**, only some of them.

#### information about my machine, in case it helps at all:
Operating system: `Ubuntu 22.10`
Terminal emulator: `gnome-terminal` 
Shell: `GNU bash, version 5.2.2(1)-release (x86_64-pc-linux-gnu)`
To check if the problem is shell specific, I tested `neofetch` on the default shell `sh` (which is a symbolic link to `/bin/dash`), and the error is also present there. (The version of `dash` that I have installed is `dash 0.5.11+git20210903+057cd650a4ed-8ubuntu1`.)

- [ ] Does this issue still occur in the master branch? (**Required if issue**)
I don't know. I ran `sudo apt install neofetch`, which I assume would install the master branch, but I don't know whether or not that it is.

#### Neofetch version
```
$ Neofetch --version
7.1.0
```

## Screenshot
Screenshot of the new Ubuntu logo:
![Screenshot from 2023-03-01 14-08-10](https://user-images.githubusercontent.com/110948069/222254276-0a383db1-7c76-4ed4-ac30-1b0e38e1d958.png)
Screenshot of the new Arch logo (I highlighted the line where the error is so that it's more visible):
![Screenshot from 2023-03-01 14-30-11](https://user-images.githubusercontent.com/110948069/222258375-be457566-b91b-40ba-a87c-e1aad3afc595.png)
Screenshot of the LinuxMint logo:
![Screenshot from 2023-03-01 14-31-15](https://user-images.githubusercontent.com/110948069/222258916-9c4dd96c-30f6-4241-a457-0b3dd5bf9e5a.png)

## Config file
I put both the config file and the verbose log in the following gist.
The title of the gist is the filename of the first file that I uploaded, "neofetch_config", because I couldn't figure out how to change the gist title, but both files *are* present in the gist.
https://gist.github.com/Resuscitating/a13fcbe7c8511e945afb694762779142

## Verbose log
I put both the config file and the verbose log in the following gist.
The title of the gist is the filename of the first file that I uploaded, "neofetch_config", because I couldn't figure out how to change the gist title, but both files *are* present in the gist.
https://gist.github.com/Resuscitating/a13fcbe7c8511e945afb694762779142

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by ghost** [comment]
If there's any more information that I can provide, please let me know. I'll try to get back to you as soon as possible.
I'm going to spend a bit of time looking through the source to see if I can locate what's causing the issue, and if I find something I'll submit a PR with a fix.

**Comment by hykilpikonna** [comment]
Similar to #2217, #2209. Fixed in HyFetch 1.4.3 / neowofetch 7.3.3 by the pull request https://github.com/hykilpikonna/hyfetch/pull/24.

> [HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.
>
> Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by ghost** [comment]
@hykilpikonna Thanks for your comment! Soon after I created this issue, I found HyFetch and I've been using it rather than NeoFetch since. I had meant to close this issue once I found out that this repo is no longer maintained, but I ended up getting distracted and forgetting.

I'm gonna go ahead and close the issue now. :)
