### ISSUE TITLE
Distro Request: Vanilla OS

### ISSUE THREAD

**Issue by dch82** [dylanaraps/neofetch#2308]
Hello, there is an emerging os called [Vanilla OS](https://vanillaos.org/).
The logo is this:
![vanilla-icon](https://user-images.githubusercontent.com/126612878/229278453-d7ff9137-597b-4270-863f-0af5e427f064.svg).

Thank you!

**Comment by hykilpikonna** [comment]
There is already a pull request for it: https://github.com/dylanaraps/neofetch/pull/2222. It was merged into HyFetch 1.4.3 / neowofetch 7.3.3.

> [HyFetch](https://github.com/hykilpikonna/hyfetch) is a fork of neofetch with LGBTQ pride flags, but the repo also maintains an updated version of the original neofetch, addressing many pull requests that are not merged in the original repo.
>
> Read the ["Running Updated Original Neofetch" section](https://github.com/hykilpikonna/hyfetch#running-updated-original-neofetch) for more info!

**Comment by dch82** [comment]
Sorry for not knowing!😀 

Thank you for informing me!
