### ISSUE TITLE
Neofetch doesn't fulfil it's purpose

### ISSUE THREAD

**Issue by ghost** [dylanaraps/neofetch#2423]
![neofetchhangs](https://github.com/dylanaraps/neofetch/assets/55464245/8779804d-6792-4aa2-ae5f-db8aa00d1ffc)

I have always thought that this is the whole thing about neofetch since I've never seen it go further on my computer. But I have seen people actually run much more than this, I tried it on my 2 old computers that I don't use anymore and neofetch works on them.

Components are as follows:
Intel Nuc NUC6i5SYH
i5 6260U
Iris 530
16GB SDDR4 single channel
512GB M.2

it seems like it's in a while loop, a graceful one that is or perhaps it's waiting for the system resource to obtain info about GPU, RAM...

I am not quite sure how I'd provide more info, you can see my kernel there, this one is stock! This is not my system being broken as I have reinstalled the system many times on this bad boy and it is always the same, it will always stay like this. Please tell me how I can provide more information so this can be of help.

Also I cropped my user and hostname, I hope you don't mind, that renders properly so I thought it's not relevant to dox myself over it.

**Comment by ncmprhnsbl** [comment]
`neofetch -v` to start with and `neofetch -vv` for more detail.
fyi: neofetch's developer has been on hiatus for quite some time..

**Comment by ghost** [comment]
It seems like it was looking for package "mine" which I had but it was my own program that was essentially waiting for input therefore being stuck in a loop.

neofetch -vv showed this behavior, renaming the package "mine" solved the issue.
