### ISSUE TITLE
doesn't respect config: info "host" model

### ISSUE THREAD

**Issue by 3xploiton3** [dylanaraps/neofetch#2442]
disable to show hostname, neofetch doesnt detect my configuration

#### Neofetch version
7.1

## Screenshot
![2024-02-17_11-22](https://github.com/dylanaraps/neofetch/assets/19517680/7460f628-3ddb-45da-864d-8d7e158d66d6)

## Verbose log
https://pastebin.com/raw/a749S60i

**Comment by warthunder1969** [comment]
Can confirm on Linux Mint 21.3, neofetch 7.1.0-3 same issue. Showing in  config.conf but nothing shows up.
![image](https://github.com/dylanaraps/neofetch/assets/88217087/b97a55d4-1f02-497e-b3dc-76e17b4f9350)
![image2](https://github.com/dylanaraps/neofetch/assets/88217087/ce69d126-f046-4bbe-aeab-754419051932)

**Comment by zevelix** [comment]
@3xploiton3 The line you commented out and the line you drew the box around in your output screenshot are not the same thing. Try commenting out line 4 (info title) if you don't want 'dedsec@arch' to print out.

**Comment by 3xploiton3** [comment]
ups sorry, thanks,
