### ISSUE TITLE
New Readme Screenshots

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#245]
Hello!

I'm looking for some new neofetch screenshots for the Readme. Post your screenshots 
below and I'll pick a few for the Readme. 

The current screenshots don't reflect a lot of the new neofetch features and It'd be nice
to see how some of you are using neofetch. :)

**Comment by iandrewt** [comment]
I'll submit some tomorrow, I'll have OS X and Arch

**Comment by konimex** [comment]
Hmm.. Let me try..

![neofetch-2016-05-15-23 00 24](https://cloud.githubusercontent.com/assets/15692230/15275263/fc1cb32c-1af0-11e6-9ee3-fe2f373b1e45.png)

Dunno if it is good enough for the Readme. But there you go.

**Comment by iandrewt** [comment]
![screen shot](https://cloud.githubusercontent.com/assets/12795256/15277734/aed2b2c4-1b4f-11e6-9806-e10f04191e6c.png)

Here's an OS X one, I can provide one with ASCII instead of the image if you want.

**Comment by dylanaraps** [comment]
Yeah, a screenshot with ascii art would be nice too. :)

**Comment by iandrewt** [comment]
![screen shot 2016-05-16 at 11 12 03 am](https://cloud.githubusercontent.com/assets/12795256/15278113/1c7d2c76-1b57-11e6-8a8c-b9e60320fc78.png)

**Comment by hashhar** [comment]
![2016-05-19_17-04-59_651x393](https://cloud.githubusercontent.com/assets/10473142/15392305/e98e3370-1de3-11e6-975a-68bade699757.png)
![2016-05-19_17-05-30_645x341](https://cloud.githubusercontent.com/assets/10473142/15392306/e99286be-1de3-11e6-8c31-7f2053c256a1.png)

**Comment by hashhar** [comment]
![2016-05-19_17-07-07_640x336](https://cloud.githubusercontent.com/assets/10473142/15392346/2a3d7c96-1de4-11e6-930e-ce1cd9f9c565.png)
![2016-05-19_17-07-17_642x386](https://cloud.githubusercontent.com/assets/10473142/15392345/2a392434-1de4-11e6-997b-368bbd11bada.png)

**Comment by xDemonessx** [comment]
![gilliamii_2016-05-19_10](https://cloud.githubusercontent.com/assets/3487603/15414592/b6513246-1e01-11e6-9934-7c3c4b7a18cb.png)  
 ヽ(´ー｀)ﾉ

**Comment by tudurom** [comment]
![screenie](http://pub.iotek.org/p/PZSdGlF.png)

**Comment by mclado** [comment]
Hey there, just thought about this idea but didn't saw this issue lol. 

Here is mine.

![neofetch_scrot_mclado](http://i.imgur.com/OkjOLSX.png)

**Comment by dylanaraps** [comment]
Thanks for the screenshots everyone, I'll update the readme.
