### ISSUE TITLE
Idea: change progress bar appearance based on the locale in use

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/neofetch#248]
The old progress bar looks better than the new one, but it was compatible only with unicode capable terminals. Neofetch should select the progressbar style automatically by using the output of the [`locale` command](http://unix.stackexchange.com/questions/210602/how-to-determine-if-current-locale-uses-utf-8-encoding).

**Comment by dylanaraps** [comment]
You can still use the old progress bar look, you just have to change the config 
file to use the Unicode char and set `progress_border` to `off`.

I don't like the idea of forcing a progress bar look based on whether or not
Unicode is available, I think the current behavior is fine as is.

**Comment by dylanaraps** [comment]
Closing this since I'm not going to implement this feature.
