### ISSUE TITLE
Terminal font

### ISSUE THREAD

**Issue by Brottweiler** [dylanaraps/neofetch#251]
## Description

When displaying GTK2/3 fonts, also display font used in terminal.

Maybe this is harder to look for, since it's specified in the config of the terminal application.

#### Neofetch version
`1.7`

**Comment by dylanaraps** [comment]
Here's my reddit comment for clarity:

>Terminal font will be more difficult to add due to there being no standard for getting the info.

>Neofetch will have to first figure out which terminal emulator it's running inside of to avoid issues when users have more than one type of terminal emulator open at once.

>Once we figure out the terminal emulator we need to figure out where it's config file is or if there's a command to get the information.

>I have an idea on how to do all this and I will give it a try, there's no guarantee though.

**Comment by Brottweiler** [comment]
As soon as I made the issue I realised how it would get the font, since it's in the config file and that's different depending on emulator.

**Comment by dylanaraps** [comment]
I've started work on this feature, please test out the function below and let me 
know if it works. 

This function prints the current terminal emulator that neofetch is running from. 

**Issues**

- [ ] Doesn't work when used inside tmux.

```sh
getterminalemulator () {
    parent="$(ps -p ${1:-$$} -o ppid=)"
    name="$(ps -p $parent -o comm=)"

    case "$name" in
        "${SHELL/*\/}" | *"sh") getterminalemulator "$parent" ;;
        *) terminalemulator="$name" ;;
    esac
}
getterminalemulator

printf "%s" "$terminalemulator"
```

**Comment by Brottweiler** [comment]
It detects the terminal emulator properly for me, yes.

**Comment by dylanaraps** [comment]
Awesome, Thanks.

I've just updated the function above and it should now work 
when running nested shells.

Example:

1. Open `bash`
2. Open `zsh`
3. Open `bash`
4. Open `bash`
5. etc

The function will still correctly find the terminal emulator.

**Comment by dylanaraps** [comment]
I've opened #252, which aims to close this issue and implement terminal font.

**Comment by dylanaraps** [comment]
#252 will be merged once I do some more testing.

Note: 

- Support for terminal emulators with profile based configs won't be
included with this PR.

- Support for `tmux` won't be included with this PR.

I'm going to open a new issue to these features.
