### ISSUE TITLE
add --block_height?

### ISSUE THREAD

**Issue by leofa** [dylanaraps/neofetch#253]
## Description

being there's an option to change block width, could control of block height be added?
having control over this could be nice to display colors with smaller blocks or a 1px height line of streched blocks.

**Comment by dylanaraps** [comment]
The blocks are actually just a text character so there's no way for me to 
add height sizing on a pixel basis.

I'm not even sure about how I'm going to implement block height based
on lines either.

I need to think about this one.

**Comment by leofa** [comment]
thanks for the quick respons, 
at least I'm glad you're thinking about it...

cheers

**Comment by dylanaraps** [comment]
I've almost finished adding this in my local branch. There will be a new option called
`block_height` which takes a number, that number then corresponds to the number
of lines each block will take up. (eg. `block_height=2`: Each block will be 2 lines high)

Here's a screenshot of some larger blocks:

![2016-05-28-092519_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6799467/15623412/79180614-24b6-11e6-8df9-d0a9b2c56916.png)

Sorry it took me so long, I just figured out how to do this now. :)

**Comment by dylanaraps** [comment]
Added in https://github.com/dylanaraps/neofetch/commit/7f2f83039bc5e4c781f653553f05a4cabf944224.

**Comment by leofa** [comment]
looking good! you're having a block party I see :), thank you so much for this! gonna try it asap.

**Comment by dylanaraps** [comment]
Anyitime :)
