### ISSUE TITLE
Image display isn't working

### ISSUE THREAD

**Issue by TheDoctorsLife** [dylanaraps/neofetch#256]
## Description

I'm not getting my wallpaper as a image in xfce4-terminal.

## System Information
 
OS: Void Linux x86_64
 Kernel: Linux 4.5.4_1 x86_64

#### Neofetch version

1.7_1
#### Operating system

OS: Void Linux x86_64

## Screenshot

http://i.imgur.com/kCADHXD.png

## Verbose log

http://sprunge.us/HiOH

**Comment by dylanaraps** [comment]
The config file is telling me that w3m-img is exiting with an exit code of 1 which causes neofetch to disable image mode and reset the padding to 0. 

The neofetch image functions are all working correctly and a valid image file is chosen. 

This isn't a neofetch bug from what I can see here. I'll take a closer look when I get home in a few hours.

**Comment by dylanaraps** [comment]
Neofetch is finding w3m-img as

**Comment by dylanaraps** [comment]
Do images work in `ranger` or `w3m`?

**Comment by TheDoctorsLife** [comment]
kinda, ![](http://i.imgur.com/BSIwaFA.png)

**Comment by dylanaraps** [comment]
Yeah, this looks like an issue with w3m-img instead of neofetch.

**Comment by TheDoctorsLife** [comment]
W3m images don't work in xfce-terminal

**Comment by TheDoctorsLife** [comment]
It appears that w3m image isn't working in void, I'll take this upstream.
