### ISSUE TITLE
Image not displaying properly.

### ISSUE THREAD

**Issue by KaasKop97** [dylanaraps/neofetch#257]
## Description
Image doesn't display properly, it sort of loads but there are bars just left out.

## System Information
Terminal: rxvt-unicode
Shell: zsh
#### Neofetch version
1.7 / also tried neofetch-git from AUR.
#### Operating system
Arch x64
## Screenshot
http://i.imgur.com/orfbBsh.png
## Verbose log
http://pastebin.com/jF5XqvCa

**Comment by iandrewt** [comment]
Image not working in rxvt-unicode is a known issue, see #222

**Comment by KaasKop97** [comment]
Wops didn't find that one, sorry!

**Comment by dylanaraps** [comment]
Duplicate of #222.

Also see this wiki page:

https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal

**Comment by dylanaraps** [comment]
This issue has finally been fixed.
