### ISSUE TITLE
CPU Usage is 404% on FreeBSD

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/neofetch#258]
## System Information

FreeBSD 10.3-RELEASE

#### Neofetch version

HEAD

## Screenshot

![Screenshot](http://pub.iotek.org/p/9mIE1NK.png)

## Verbose log

https://p.iotek.org/ha5

I should come with a fix later.

**Comment by tudurom** [comment]
**News:** `ps` aux reports 399.5% idle. I think the output should be divided by the number of cores.

**Comment by tudurom** [comment]
See #259. (yes, it's a recursive `see`)

**Comment by dylanaraps** [comment]
iostat doesn't come preinstalled on linux systems afaik. Is it preinstalled on BSD?

**Comment by tudurom** [comment]
It is.
On 21 May 2016 02:36, Dylan Araps <notifications@github.com> wrote:iostat doesn't come preinstalled on linux systems afaik. Is it preinstalled on BSD?
