### ISSUE TITLE
Images getting cropped strangely

### ISSUE THREAD

**Issue by WatermelonDriveway** [dylanaraps/neofetch#261]
Screenshot: https://u.pomf.is/wwnfbn.png

I set --size 100px for that screenshot just to show that it's not because the image is too big.

iTerm2, OS X 10.11.3, neofetch 1.5

**Comment by iandrewt** [comment]
Please try updating Neofetch first, we're up to version 1.7 now

**Comment by dylanaraps** [comment]
It would also be helpful to see the original image that you're using inside neofetch to see if we can reproduce the issue.

**Comment by WatermelonDriveway** [comment]
I just updated to 1.7 (I think I did it right, since 1.5 is the latest in the homebrew repo)  Still no luck, same results.  Maybe it is configured incorrectly.

config:  http://pastebin.com/raw/MPkiUqzP
image:  https://u.pomf.is/jnrhsi.png

although it does that to any image that I try. 

Thanks!

**Comment by dylanaraps** [comment]
I know why this is happening now, thanks.

I'll have some time to work on it this weekend.

**Comment by dylanaraps** [comment]
#266 should fix this issue.

It adds a new option to `--size` / `$image_size` called `none` which disables 
all resizing / cropping.

So running neofetch with `neofetch --size none` displays the image in its 
original size like so:

![2016-05-27-151809_540x410_scrot](https://cloud.githubusercontent.com/assets/6799467/15598513/4edcc0f8-241e-11e6-8db4-6032aa5c1907.png)

Test out #266 and let me know if this solves the problem for you. :)

**Comment by WatermelonDriveway** [comment]
Thanks for your response.

Where is the neofetch.1 file located?  I'm trying to make the changes.

**Comment by dylanaraps** [comment]
1. Clone the neofetch repo
    - `git clone https://github.com/dylanaraps/neofetch`
2. `cd neofetch`
3. `git checkout size_none`
4. `neofetch --size none‘

**Comment by dylanaraps** [comment]
Ping @WatermelonDriveway.

Can you test this out and let me know if it fixes your issue?

**Comment by WatermelonDriveway** [comment]
This is how it looks for me after following those steps

![screen shot 2016-05-30 at 8 24 22 pm](https://cloud.githubusercontent.com/assets/8306685/15660073/9298db1e-26a4-11e6-92d1-ebdacd2804c4.png)

**Comment by dylanaraps** [comment]
You have to run neofetch from the directory it was cloned to.

eg. `./neofetch --size none` or `./path/to/cloned/neofetch --size none`

**Comment by WatermelonDriveway** [comment]
Oh yeah woops... works now.  I had to set xoffset to -40 or else the spacing was huge between the image and the text, but obviously that's not a big deal.  Thanks!

![screen shot 2016-05-30 at 9 52 14 pm](https://cloud.githubusercontent.com/assets/8306685/15660937/ce3af056-26b0-11e6-8409-2b934f15befe.png)

**Comment by dylanaraps** [comment]
The spacing between the image and text shouldn't be that big. I just pushed a change, 
let me know if it fixes it.

You can try out the newest version of the PR like so:

(Inside the `neofetch` directory)

1. `git pull origin size_none`.
2. `./neofetch --size none`

**Comment by WatermelonDriveway** [comment]
Yup, running that with xoffset set to 0 puts the text right on the edge of the image.  Thanks!

**Comment by dylanaraps** [comment]
No problem!

I'll merge this to master now, thanks for testing.
