### ISSUE TITLE
why the image/ascii did not want to show ?

### ISSUE THREAD

**Issue by rahmatfauzi08** [dylanaraps/neofetch#265]
## Description

why the image/ascii did not want to show ? and how to show  ? 

#### Neofetch version
1.7
#### Operating system
Backbox 4.4
XFCE 4
## Screenshot
[http://imgbox.com/Okjv2s1d](url)

**Comment by dylanaraps** [comment]
I need a verbose log before I can help you with anything.


1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by iandrewt** [comment]
`value` isn't a valid option for `--ascii`

Can you try `neofetch --ascii ubuntu` please?

**Comment by rahmatfauzi08** [comment]
i try neofetch --ascii, then didn't show

**Comment by rahmatfauzi08** [comment]
+ verbose=on
+ shift
+ '[' 2 ']'
+ case $1 in
+ shift
+ '[' '' ']'
+ trap 'printf "\033[?25h"; clear; exit' 2
+ getdistro
+ '[' '!' -z '' ']'
+ case "$os" in
+ type -p lsb_release
++ lsb_release -d
++ awk -F : '/Description/ {printf $2}'
+ distro='	Ubuntu 14.04.4 LTS'
+ distro='Ubuntu 14.04.4 LTS'
+ distro='Ubuntu 14.04.4 LTS'
+ '[' on == on ']'
++ uname -m
+ distro+=' i686'
+ '[' on == off ']'
+ '[' on == off ']'
+ '[' -z '' ']'
+ ascii_distro='Ubuntu 14.04.4 LTS i686'
+ bold
+ case "$ascii_bold" in
+ ascii_bold=
+ case "$bold" in
+ bold='\033[1m'
+ colors
+ case "$ascii_distro" in
+ setcolors 7 1 3
++ color 7
++ case "$1" in
++ printf %b%s '\033[0m\033[37m'
+ c1=''
++ color 1
++ case "$1" in
++ printf %b%s '\033[0m\033[31m'
+ c2=''
++ color 3
++ case "$1" in
++ printf %b%s '\033[0m\033[33m'
+ c3=''
++ color
++ case "$1" in
++ printf %b%s '\033[38;5;m'
+ c4=''
++ color
++ case "$1" in
++ printf %b%s '\033[38;5;m'
+ c5=''
++ color
++ case "$1" in
++ printf %b%s '\033[38;5;m'
+ c6=''
+ '[' 3 == distro ']'
++ color 3
++ case "$1" in
++ printf %b%s '\033[0m\033[33m'
+ title_color=''
++ color 4
++ case "$1" in
++ printf %b%s '\033[0m\033[34m'
+ at_color=''
++ color 2
++ case "$1" in
++ printf %b%s '\033[0m\033[32m'
+ underline_color=''
++ color 6
++ case "$1" in
++ printf %b%s '\033[0m\033[36m'
+ subtitle_color=''
++ color 2
++ case "$1" in
++ printf %b%s '\033[0m\033[32m'
+ colon_color=''
++ color 2
++ case "$1" in
++ printf %b%s '\033[0m\033[32m'
+ info_color=''
+ '[' '4 6 1 8 9 6' == distro ']'
++ color 4 6 1 8 9 6
++ case "$1" in
++ printf %b%s '\033[0m\033[34m'
+ progress_color_elapsed=''
+ case "$progress_color_total $1" in
++ color 4 6 1 8 8 6
++ case "$1" in
++ printf %b%s '\033[0m\033[34m'
+ progress_color_total=''
+ '[' 4 '!=' distro ']'
+ setcolors 4 1 5 3
++ color 4
++ case "$1" in
++ printf %b%s '\033[0m\033[34m'
+ c1=''
++ color 1
++ case "$1" in
++ printf %b%s '\033[0m\033[31m'
+ c2=''
++ color 5
++ case "$1" in
++ printf %b%s '\033[0m\033[35m'
+ c3=''
++ color 3
++ case "$1" in
++ printf %b%s '\033[0m\033[33m'
+ c4=''
++ color
++ case "$1" in
++ printf %b%s '\033[38;5;m'
+ c5=''
++ color
++ case "$1" in
++ printf %b%s '\033[38;5;m'
+ c6=''
+ '[' 3 == distro ']'
++ color 3
++ case "$1" in
++ printf %b%s '\033[0m\033[33m'
+ title_color=''
++ color 4
++ case "$1" in
++ printf %b%s '\033[0m\033[34m'
+ at_color=''
++ color 2
++ case "$1" in
++ printf %b%s '\033[0m\033[32m'
+ underline_color=''
++ color 6
++ case "$1" in
++ printf %b%s '\033[0m\033[36m'
+ subtitle_color=''
++ color 2
++ case "$1" in
++ printf %b%s '\033[0m\033[32m'
+ colon_color=''
++ color 2
++ case "$1" in
++ printf %b%s '\033[0m\033[32m'
+ info_color=''
+ '[' '' == distro ']'
++ color ''
++ case "$1" in
++ printf %b%s '\033[38;5;m'
+ progress_color_elapsed='[38;5;m'
+ case "$progress_color_total $1" in
++ color ''
++ case "$1" in
++ printf %b%s '\033[38;5;m'
+ progress_color_total='[38;5;m'
+ '[' wall '!=' off ']'
+ trap 'printf "\033[?25h"' EXIT
+ clear

+ printf '\033[?25l'
+ '[' -n '' ']'
+ image_backend=w3m
+ '[' w3m == w3m ']'
+ '[' wall '!=' ascii ']'
+ getw3m_img_path
+ '[' -x /usr/lib/w3m/w3mimgdisplay ']'
+ return
+ getimage
+ type -p convert
+ case "$image" in
+ getwallpaper
+ case "$os" in
+ type -p feh
+ '[' -f /home/ratz/.fehbg ']'
+ type -p nitrogen
++ awk -F= '/file/ {printf $2;exit;}' /home/ratz/.config/nitrogen/bg-saved.cfg
+ img=/home/ratz/Downloads/Wallpaper/darthvader.png
+ '[' png == xml ']'
+ '[' -z /home/ratz/Downloads/Wallpaper/darthvader.png ']'
+ stty -echo
+ '[' -n '' ']'
+ printf %b%s '\033[14t\033[c'
+ read -t 1 -d c -s -r term_size
+ stty echo
+ term_size='4;375;600t?62;9;'
+ term_size='4375;600t?62;9;'
+ term_size='375;600t?62;9;'
+ term_size='375;600'
+ term_height=375
+ term_width=600
+ '[' '!' -f /home/ratz/Downloads/Wallpaper/darthvader.png ']'
+ '[' 7 -le 5 ']'
++ tput lines
+ lines=25
++ tput cols
+ columns=75
+ printinfoh=8
+ info titlege_size" in
+ subtitle=title
+ '[' -z '' ']'82
+ gettitle-lt 300 ']'
+ eval 'output=$title'
++ output=ratz@backboxn" in
+ '[' -z ratz@backbox ']'
+ case "$1" inme/ratz/.cache/thumbnails/neofetch
+ string='\033[1mratz@backbox'
+ string='\033[1mratz@\033[1mbackbox'ng
+ length=12f /home/ratz/.cache/thumbnails/neofetch/fit-center-282-darthvade+ '[' -z '' ']'
+ string='\033[1mratz@\033[1mbackbox'ofetch/fit-center-282-darthvader.png
+ printf '%b%s\n' '\033[0C\033[1mratz@\033[1mbackbox\033[0m'
+ratz@backbox=' ascii ']'
+ info underlineackend" in
+ subtitle=underline;1;0;0;282;282;;;;;/home/ratz/.cache/thumbnails/neofetc+ '[' -z '' ']'2-darthvader.png\n4;\n3;'
+ getunderline/w3mimgdisplay
+ eval 'output=$underline'
++ output=------------
+ '[' -z ------------ ']'
+ case "$1" in[0H'
+ string='------------'
+ '[' -z '' ']'
+ string='------------'
+ printf '%b%s\n' '\033[0C------------\033[0m'
 ------------
+ prin 'Every profesional starting from n00b'
+ '[' -z '' ']'
+ string='Every profesional starting from n00b'
+ length=36
+ printf '%b%s\n' '\033[0CEvery profesional starting from n00b\033[0m'
 Every profesional starting from n00b
+ info underline
+ subtitle=underline
+ '[' -z '' ']'
+ getunderline
+ eval 'output=$underline'
++ output=------------------------------------
+ '[' -z ------------------------------------ ']'
+ case "$1" in
+ string='------------------------------------'
+ '[' -z '' ']'
+ string='------------------------------------'
+ printf '%b%s\n' '\033[0C------------------------------------\033[0m'
 ------------------------------------
+ info OS distro
+ subtitle=OS
+ '[' -z distro ']'
+ getdistro
+ eval 'output=$distro'
++ output='Ubuntu 14.04.4 LTS i686'
+ '[' -z 'Ubuntu 14.04.4 LTS i686' ']'
+ case "$1" in
+ string='\033[1mOS\033[0m'
+ string+=': Ubuntu 14.04.4 LTS i686'
+ length=27
+ '[' -z distro ']'
+ printf '%b%s\n' '\033[0C\033[1mOS\033[0m: Ubuntu 14.04.4 LTS i686\033[0m'
 OS: Ubuntu 14.04.4 LTS i686
+ info Kernel kernel
+ subtitle=Kernel
+ '[' -z kernel ']'
+ getkernel
+ eval 'output=$kernel'
++ output=4.2.0-30-generic
+ '[' -z 4.2.0-30-generic ']'
+ case "$1" in
+ string='\033[1mKernel\033[0m'
+ string+=': 4.2.0-30-generic'
+ length=24
+ '[' -z kernel ']'
+ printf '%b%s\n' '\033[0C\033[1mKernel\033[0m: 4.2.0-30-generic\033[0m'
 Kernel: 4.2.0-30-generic
+ info Birthday birthday
+ subtitle=Birthday
+ '[' -z birthday ']'
+ getbirthday
+ eval 'output=$birthday'
++ output='Sat 14 May 2016 6:42 PM'
+ '[' -z 'Sat 14 May 2016 6:42 PM' ']'
+ case "$1" in
+ string='\033[1mBirthday\033[0m'
+ string+=': Sat 14 May 2016 6:42 PM'
+ length=33
+ '[' -z birthday ']'
+ printf '%b%s\n' '\033[0C\033[1mBirthday\033[0m: Sat 14 May 2016 6:42 PM\033[0m'
 Birthday: Sat 14 May 2016 6:42 PM
+ info Uptime uptime
+ subtitle=Uptime
+ '[' -z uptime ']'
+ getuptime
+ eval 'output=$uptime'
++ output='up 17 minutes'
+ '[' -z 'up 17 minutes' ']'
+ case "$1" in
+ string='\033[1mUptime\033[0m'
+ string+=': up 17 minutes'
+ length=21
+ '[' -z uptime ']'
+ printf '%b%s\n' '\033[0C\033[1mUptime\033[0m: up 17 minutes\033[0m'
 Uptime: up 17 minutes
+ info linebreak
+ subtitle=linebreak
+ '[' -z '' ']'
+ getlinebreak
+ eval 'output=$linebreak'
++ output=' '
+ '[' -z ' ' ']'
+ case "$1" in
+ string='\033[1mlinebreak\033[0m'
+ string+=':  '
+ length=12
+ '[' -z '' ']'
+ string=' '
+ printf '%b%s\n' '\033[0C \033[0m'
  
+ info Resolution resolution
+ subtitle=Resolution
+ '[' -z resolution ']'
+ getresolution
+ eval 'output=$resolution'
++ output=
+ '[' -z '' ']'
+ return
+ info DE de
+ subtitle=DE
+ '[' -z de ']'
+ getde
+ eval 'output=$de'
++ output=XFCE
+ '[' -z XFCE ']'
+ case "$1" in
+ string='\033[1mDE\033[0m'
+ string+=': XFCE'
+ length=8
+ '[' -z de ']'
+ printf '%b%s\n' '\033[0C\033[1mDE\033[0m: XFCE\033[0m'
 DE: XFCE
+ info WM wm
+ subtitle=WM
+ '[' -z wm ']'
+ getwm
+ eval 'output=$wm'
++ output=Xfwm4
+ '[' -z Xfwm4 ']'
+ case "$1" in
+ string='\033[1mWM\033[0m'
+ string+=': Xfwm4'
+ length=9
+ '[' -z wm ']'
+ printf '%b%s\n' '\033[0C\033[1mWM\033[0m: Xfwm4\033[0m'
 WM: Xfwm4
+ info 'WM Theme' wmtheme
+ subtitle='WM Theme'
+ '[' -z wmtheme ']'
+ getwmtheme
+ eval 'output=$wmtheme'
++ output=HackStation
+ '[' -z HackStation ']'
+ case "$1" in
+ string='\033[1mWM Theme\033[0m'
+ string+=': HackStation'
+ length=21
+ '[' -z wmtheme ']'
+ printf '%b%s\n' '\033[0C\033[1mWM Theme\033[0m: HackStation\033[0m'
 WM Theme: HackStation
+ info Theme theme
+ subtitle=Theme
+ '[' -z theme ']'
+ gettheme
+ eval 'output=$theme'
++ output='HackStation [GTK2], Flattice [GTK3] '
+ '[' -z 'HackStation [GTK2], Flattice [GTK3] ' ']'
+ case "$1" in
+ string='\033[1mTheme\033[0m'
+ string+=': HackStation [GTK2], Flattice [GTK3] '
+ length=43
+ '[' -z theme ']'
+ printf '%b%s\n' '\033[0C\033[1mTheme\033[0m: HackStation [GTK2], Flattice [GTK3] \033[0m'
 Theme: HackStation [GTK2], Flattice [GTK3] 
+ info Font font
+ subtitle=Font
+ '[' -z font ']'
+ getfont
+ eval 'output=$font'
++ output='Sans 10 [GTK2/3]'
+ '[' -z 'Sans 10 [GTK2/3]' ']'
+ case "$1" in
+ string='\033[1mFont\033[0m'
+ string+=': Sans 10 [GTK2/3]'
+ length=22
+ '[' -z font ']'
+ printf '%b%s\n' '\033[0C\033[1mFont\033[0m: Sans 10 [GTK2/3]\033[0m'
 Font: Sans 10 [GTK2/3]
+ info linebreak
+ subtitle=linebreak
+ '[' -z '' ']'
+ getlinebreak
+ eval 'output=$linebreak'
++ output=' '
+ '[' -z ' ' ']'
+ case "$1" in
+ string='\033[1mlinebreak\033[0m'
+ string+=':  '
+ length=12
+ '[' -z '' ']'
+ string=' '
+ printf '%b%s\n' '\033[0C \033[0m'
  
+ info CPU cpu
+ subtitle=CPU
+ '[' -z cpu ']'
+ getcpu
 CPU: AMD A10-5750M APU (4) @ 2.5GHz
+ eval 'output=$cpu'
++ output=
+ '[' -z '' ']'
+ return
+ info GPU gpu
+ subtitle=GPU
+ '[' -z gpu ']'
+ getgpu
+ eval 'output=$gpu'
++ output='AMD Radeon HD 8650G'
+ '[' -z 'AMD Radeon HD 8650G' ']'
+ case "$1" in
+ string='\033[1mGPU\033[0m'
+ string+=': AMD Radeon HD 8650G'
+ length=24
+ '[' -z gpu ']'
+ printf '%b%s\n' '\033[0C\033[1mGPU\033[0m: AMD Radeon HD 8650G\033[0m'
 GPU: AMD Radeon HD 8650G
+ info Memory memory
+ subtitle=Memory
+ '[' -z memory ']'
+ getmemory
+ eval 'output=$memory'
++ output='716MB / 3234MB'
+ '[' -z '716MB / 3234MB' ']'
+ case "$1" in
+ string='\033[1mMemory\033[0m'
+ string+=': 716MB / 3234MB'
+ length=22
+ '[' -z memory ']'
+ printf '%b%s\n' '\033[0C\033[1mMemory\033[0m: 716MB / 3234MB\033[0m'
 Memory: 716MB / 3234MB
+ info 'Local IP' localip
+ subtitle='Local IP'
+ '[' -z localip ']'
+ getlocalip
+ eval 'output=$localip'
++ output=192.168.43.52
+ '[' -z 192.168.43.52 ']'
+ case "$1" in
+ string='\033[1mLocal IP\033[0m'
+ string+=': 192.168.43.52'
+ length=23
+ '[' -z localip ']'
+ printf '%b%s\n' '\033[0C\033[1mLocal IP\033[0m: 192.168.43.52\033[0m'
 Local IP: 192.168.43.52
+ info linebreak
+ subtitle=linebreak
+ '[' -z '' ']'
+ getlinebreak
+ eval 'output=$linebreak'
++ output=' '
+ '[' -z ' ' ']'
+ case "$1" in
+ string='\033[1mlinebreak\033[0m'
+ string+=':  '
+ length=12
+ '[' -z '' ']'
+ string=' '
+ printf '%b%s\n' '\033[0C \033[0m'
  
+ info cols
+ subtitle=cols
+ '[' -z '' ']'
+ getcols
                                 
 + eval 'output=$cols'
++ output=
+ '[' -z '' ']'
+ return
+ info linebreak
+ subtitle=linebreak
+ '[' -z '' ']'
+ getlinebreak
+ eval 'output=$linebreak'
++ output=' '
+ '[' -z ' ' ']'
+ case "$1" in
+ string='\033[1mlinebreak\033[0m'
+ string+=':  '
+ length=12
+ '[' -z '' ']'
+ string=' '
+ printf '%b%s\n' '\033[0C \033[0m'
  
+ info linebreak
+ subtitle=linebreak
+ '[' -z '' ']'
+ getlinebreak
+ eval 'output=$linebreak'
++ output=' '
+ '[' -z ' ' ']'
+ case "$1" in
+ string='\033[1mlinebreak\033[0m'
+ string+=':  '
+ length=12
+ '[' -z '' ']'
+ string=' '
+ printf '%b%s\n' '\033[0C \033[0m'
  
+ '[' wall '!=' off ']'
++ stty -echo
++ IFS=';'
++ read -rdR -t 1 -d c -p '' ROW COL
++ printf %s 25
++ stty echo
+ info_height=25
+ '[' on == off ']'
+ '[' off == on ']'[25H\033[2A'
+ '[' on == on ']'
+ printf ''
+ printf '\033[?25h'

**Comment by rahmatfauzi08** [comment]
this is my changelog sir, http://pastebin.com/0pWQQRUt

**Comment by dylanaraps** [comment]
Can I have a log from lauching neofetch with `--ascii`?

1. Run `neofetch --ascii -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

Also:

- What is your terminal emulator?
- How did you install neofetch?

**Comment by rahmatfauzi08** [comment]
-  i use xfce4-terminal

- Like your tutorial sir. 
But, previously appeared ascii my ubuntu. Then i custom my config, and not show anything like a screenshoot

**Comment by iandrewt** [comment]
Can you upload your config file to pastebin?

**Comment by rahmatfauzi08** [comment]
[http://pastebin.com/BzDvL5Sk](url)

**Comment by iandrewt** [comment]
I think I've found the issue. Ubuntu doesn't have a small ascii art. Try running `neofetch --image ascii --ascii_logo_size normal`

If that works, in your config file change line 300 (the `image` variable) to `ascii` and line 365 (the `ascii_logo_size` variable) to `normal`

**Comment by rahmatfauzi08** [comment]
Work sir ! Thank you
[http://imgbox.com/Q9prIz9S](url)
