### ISSUE TITLE
Help with neofetch image cutoff

### ISSUE THREAD

**Issue by tjw0lf** [dylanaraps/neofetch#268]
I need help with neofetch if you can help me out please image cutoff and new to neofetch other help would be nice.  Would be nice to see a video on youtube for tut customization

 http://i.imgur.com/kHIxXnM.png

Thank you

**Comment by dylanaraps** [comment]
I need some more info from you:

- Terminal Emulator
- Neofetch Version

**Comment by tjw0lf** [comment]
Xfce Terminal 
neofetch 1.7

Anymore info let me know

Thank you

**Comment by dylanaraps** [comment]
Does `neofetch --gtk3 off` fix this issue? (Upload another screenshot)

**Comment by tjw0lf** [comment]
The line is gone when that command is typed in terminal. still overlaps on top

http://i.imgur.com/TjD2xqx.png

**Comment by dylanaraps** [comment]
You can fix the overlap on the top by using `--yoffset 25`. (in pixels)
Try larger/smaller numbers till the overlap is fixed.

You can also edit `$HOME/.config/neofetch/config` to set these
options automatically at launch.

There's nothing I can do about the image display issues sadly.

**Comment by tjw0lf** [comment]
So where do i put those commands in the config where at.

Do i put this in the config neofetch --gtk3 off  Where do i pput this at --yoffset 25

Thanks

**Comment by dylanaraps** [comment]
Neofetch has a config file located at `$HOME/.config/neofetch/config`.
Open it in a text editor and change these options to the new values:

You'll have to look inside the config to find these options.

```sh
gtk3="off"
yoffset="25"
```
