### ISSUE TITLE
Directory not terminated by "/" lead to error

### ISSUE THREAD

**Issue by aranega** [dylanaraps/neofetch#275]
When a directoy is passed as argument without "/" at the end, the expression L.2268

    files=("$image"*.{png,jpg,jpeg})

leads to an error. For example, in this call

    neofetch --image mydir

`$image` is resolved as `mydir` only and then `$files` to `mydir*.{png,jpg,jpeg}` instead of `mydir/*.{png,jpg,jpeg}`.

A solution could be something like this:

    files=("${image%/}"/*.{png,jpg,jpeg})

Sorry for raising a ticket about this, I'm not sure if it is relevant or not.

**Comment by iandrewt** [comment]
I've got an idea for how this could be done, but I'm not sure if the current behaviour is expected or not. I'll test this in a bit.

**Comment by iandrewt** [comment]
Your solution worked perfectly, feel free to open a pull request with the changes.

**Comment by dylanaraps** [comment]
Want me to quickly add this or do you want to open a PR?

**Comment by iandrewt** [comment]
Just add it to master, works fine.

**Comment by aranega** [comment]
Don't bother with a PR, it sounds a little oversized to me for only 5 chars :) You can directly add it!

**Comment by dylanaraps** [comment]
Done, thanks guys.

**Comment by aranega** [comment]
cool :) thanks for the reactivity, neofetch is just awsome!
