### ISSUE TITLE
Text color doesn't follow the config when set to 'barinfo'

### ISSUE THREAD

**Issue by konimex** [dylanaraps/neofetch#282]
## Description

When one changes the text color for info, when the info is displayed as `barinfo`, the info text does not follow. However when set to `infobar`, it works just fine.

#### Neofetch version

1.7

#### Operating system

Gentoo Linux

## Screenshot

![07tk6T5.png](http://i.imgur.com/07tk6T5.png)

(For comparison, I set one info to display as `infobar`)

## Verbose log
http://termbin.com/9jxv

**Comment by dylanaraps** [comment]
Fixed.

Thanks for reporting this.
