### ISSUE TITLE
Image display fails and fills terminal with spaces

### ISSUE THREAD

**Issue by sodatruck** [dylanaraps/neofetch#288]
## Description
Neofetch will run just as intended when run with --ascii, but refuses to draw any images in the terminal (Terminator).
I have checked and I'm pretty sure I have all the necessary dependencies.
The strange thing is, it doesn't seem to fallback to ascii when wallpaper or image display fails. It just prints the system information and fills my terminal with spaces, as seen in the screenshots I've attached. It makes it so my cursor is always at the bottom of the window.

I don't even need a solution to this problem, it's just going to bother me until I can discern the cause!

## System Information
OS: elementary OS Freya x86_64
Kernel: 3.19.0-61-generic
Shell: /usr/bin/zsh
DE: Pantheon
WM: Mutter(Gala)
WM Theme: Elementary
Theme: Elementary [GTK3] 
Icons: Elementary [GTK3] 
Font: Droid Sans 9 [GTK3] 
CPU: Intel Core2 Duo T9400 (2) @ 2.5GHz
GPU: Intel Integrated Graphics

#### Neofetch version
Neofetch 1.7

#### Operating system
Elementary OS 0.3.2 (Freya)

## Screenshots
![screenshot from 2016-06-15 16 01 10](https://cloud.githubusercontent.com/assets/19959832/16095440/89aecdc2-3312-11e6-846f-d6165d096a3c.png)
![screenshot from 2016-06-15 16 01 35](https://cloud.githubusercontent.com/assets/19959832/16095441/89b06470-3312-11e6-9990-56e7158f3a68.png)
![screenshot from 2016-06-15 16 02 10](https://cloud.githubusercontent.com/assets/19959832/16095442/89ceb6a0-3312-11e6-90c9-9a19428045c1.png)

Verbose log can be found here:
http://pastebin.com/cL3cdEW0

**Comment by dylanaraps** [comment]
The reason neofetch is displaying no ascii is that `w3m-img` mode is failing on line `3323` (Right at the end). Image mode is failing because `w3m-img` is exiting with an error code of `1`. When `w3m-img` fails and because we're at the end of the script we just set padding to `0` and disable all images. (This is what you're seeing in your first two screenshots).

So, in short. This is an issue with `w3m-img` on your system, neofetch is working as intended. Also, you're having the same issue as https://github.com/dylanaraps/neofetch/issues/256

Note: Terminator does have an issue with `w3m-img`, on window focus/resize the images will disappear. See this wiki page: https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal

**Comment by sodatruck** [comment]
Alright. Sorry to bother you.

**Comment by sodatruck** [comment]
Sorry to bump a closed thread, but I also just wanted to say that images display in xterm, but are uncropped.

![screenshot from 2016-06-15 17 46 06](https://cloud.githubusercontent.com/assets/19959832/16098455/10f95e4c-3321-11e6-8f50-f8ba789cb4e5.png)

Thank you!

**Comment by dylanaraps** [comment]
Can I see a verbose log from when you run it in xterm?

**Comment by sodatruck** [comment]
Here you go!
http://pastebin.com/BqV5KDCT

**Comment by dylanaraps** [comment]
Try the latest master.

**Comment by sodatruck** [comment]
No dice.

Another log:
http://pastebin.com/LcyLUdT5

![screenshot from 2016-06-16 09 08 52](https://cloud.githubusercontent.com/assets/19959832/16117860/37391b3e-33a2-11e6-8d6f-f62e9d49ab90.png)

**Comment by dylanaraps** [comment]
Weird.

The problem occurs because the image height is getting set to ` ?641` 
instead of `641` for some odd reason.

I'm working on a fix as we speak.

**Comment by dylanaraps** [comment]
Does the latest commit fix this issue?

**Comment by sodatruck** [comment]
Nope.
![screenshot from 2016-06-16 09 19 48](https://cloud.githubusercontent.com/assets/19959832/16118120/903c1708-33a3-11e6-8d97-ad2e84226081.png)

**Comment by dylanaraps** [comment]
Try my latest commit, It's going to take some trial and error to fix this,

**Comment by sodatruck** [comment]
Still no luck; it looks the same.
