### ISSUE TITLE
Cursor position moves to top of window when using --image off

### ISSUE THREAD

**Issue by iandrewt** [dylanaraps/neofetch#289]
## Description

When using `--image off`, the cursor position moves to the top of the window instead of below the output in iTerm2

#### Neofetch version

1.7

#### Operating system

OS X El Capitan 10.11.5 with iTerm2

## Screenshot (Asciinema)

[![asciicast](https://asciinema.org/a/9lnouzk4x95yftgek958y90k0.png)](https://asciinema.org/a/9lnouzk4x95yftgek958y90k0)

## Verbose log

[Three logs provided, image, ascii and none](https://gist.github.com/iandrewt/02afa90c187daf5ade7af488b0271364)

**Comment by dylanaraps** [comment]
Thanks for reporting this.

**Comment by iandrewt** [comment]
All good. Also, is the terminal supposed to clear first when using `--image off`? Because it doesn't...

**Comment by dylanaraps** [comment]
Should we clear the screen when `--image off`?

**Comment by iandrewt** [comment]
Hmm... Probably, if only for consistency

**Comment by dylanaraps** [comment]
Done.
