### ISSUE TITLE
neofetch doesn't detect resolution when using awk program other than gawk on xrandr

### ISSUE THREAD

**Issue by konimex** [dylanaraps/neofetch#291]
## Description

When one uses any `awk` program other than `gawk` (such as `mawk`, or the default `awk` on *BSD system) to fetch information on screen resolution on `xrandr`, it fails. (It works fine with `xdpyinfo`, but AFAIU from the neofetch source code it detects from `xrandr` first.)

#### Neofetch version

1.7

#### Operating system

Tested on FreeBSD in a VM.

## Screenshot

![virtualbox_freebsd_23_06_2016_05_34_24](https://cloud.githubusercontent.com/assets/15692230/16286170/f1d3421e-3904-11e6-9864-66d875a5d253.png)

## Verbose log

[Log](http://termbin.com/v7i1)

(P.S.: Since xrandr works fine, should we drop resolution detection using `xdpyinfo`?)

**Comment by dylanaraps** [comment]
So basically we're using GNU only features in the xrandr awk command which is causing it to not work on BSD systems?

**Comment by konimex** [comment]
Yep. Escaping the `*` fixed it.

However, detecting monitor resolution with refresh rates without `gawk` also fails (no output).

**Comment by dylanaraps** [comment]
I pushed a fix to a new branch called `xrandr`, please test it out and let me know if it fixes
the issue. I'm not on my main machine atm so I don't have any VMs I can boot up.

**Comment by konimex** [comment]
Yep, that fixes it.

**Comment by dylanaraps** [comment]
The fix is now in master, thanks for reporting this.
