### ISSUE TITLE
Missing distro ascii: GalliumOS

### ISSUE THREAD

**Issue by mrnoda** [dylanaraps/neofetch#292]
GalliumOS is a Ubuntu based distro targetting chromebooks/chromeos devices
See https://github.com/GalliumOS, https://galliumos.org/

I have tested neofetch on my GalliumOS device, it is recognised as a Linux Distro, and the contents report "GalliumOS" as parsed from /etc/lsb-release.

All that is needed is some ascii art, unfortunately I really suck at ASCII art, I did give it a go but I am sure someone else could do a better job. The logo can be found on the project site or at https://github.com/GalliumOS/galliumos-distro.

**Comment by dylanaraps** [comment]
- How do these look?
- Which one do you prefer?

![pic](https://i.imgur.com/fVMt0Q0.png)

![pic](https://i.imgur.com/YFMdFaI.png)

**Comment by mrnoda** [comment]
Looks great, I think I prefer the second one (looks more rounded in the middle), Great job @dylanaraps

**Comment by dylanaraps** [comment]
When I'm back on my main pc I'll push this to master.

**Comment by dylanaraps** [comment]
Done.
