### ISSUE TITLE
Doesn't show image on xfce4-terminal

### ISSUE THREAD

**Issue by gentoosiasta** [dylanaraps/neofetch#294]
## Description
Doesn't show image on xfce4-terminal

#### Neofetch version 
1.8
#### Operating system
Gentoo
## Screenshot
--
## Verbose log
http://termbin.com/atid

I'll appreciate any help...

**Comment by dylanaraps** [comment]
This isn't a neofetch issue, the log file shows that the image function inside 
neofetch completes successfully. This is most likely an issue with w3m-img
and xfce4-terminal on your system.

- Do images display inside w3m or ranger?
