### ISSUE TITLE
Neofetch doesn't show image on Fedora using Gnome-terminal

### ISSUE THREAD

**Issue by VerusGott** [dylanaraps/neofetch#295]
Fedora 24, Neofetch 1.7-2

![screenshot from 2016-08-02 05-42-58](https://cloud.githubusercontent.com/assets/20784788/17315431/f5ab4196-585a-11e6-95b6-e9d8622ff683.png)

Verbose log: https://gist.github.com/VerusGott/b6b2330e188e28340706c9817cc536d8
As I think, neofetch can't get terminal size, because "printf %b%s" doesn't work for me. I checked it in both, Wayland and X.Org sessions, no difference. Any ideas about this?

**Comment by dylanaraps** [comment]
This isn't a neofetch issue, the log file shows that the image function inside
neofetch completes successfully. This is most likely an issue with w3m-img
and whatever terminal you're using on your system.

- Do images display inside w3m or ranger?

**Comment by VerusGott** [comment]
Strange. I am using gnome-terminal, wiki says that in bundle with it all should work. But I checked and it really doesn't show any image inside w3m. But, in rxvt, neofetch and w3m correctly display images. This is my specific problem, or maybe we should update wiki?
----
OK, mb I'm found where is problem. RedHat patched gnome-terminal to add transparency, it seems that this functionality completely breaks display of images. Even if transparency is disabled. I have no idea about that. Can anyone confirm it?

**Comment by dylanaraps** [comment]
Images work for me in gnome-terminal on my Ubuntu install. This is either a problem 
with gnome-terminal on your system or a problem with the gnome-terminal package
in Fedora. I'm not entirely sure.

**Comment by VerusGott** [comment]
OK, it's currently working for me on Arch Linux with gnome-terminal (but not in Wayland session), you can close this bug. I think we need to clarify in wiki, that showing up images will not work in Fedora (can anyone confirm this?), because they patched gnome-terminal.

**Comment by dylanaraps** [comment]
I'll add a note to the wiki and I'll leave this issue open to see if any Fedora users 
stumble across it.

**Comment by avvk** [comment]
It wasn't working on Fedora 25 with gnome-terminal for me too. Apparently in version 3.23 it was fixed and the package is available from Fedora 26.  

![25](https://i.imgur.com/jQ1Um6L.png)
![27-rawhide](https://i.imgur.com/BlM3ze6.jpg)

**Comment by watzon** [comment]
Just tried on my Fedora 30 install, same result as above

**Comment by Hummenix** [comment]
I can also confirm it doesn't work

**Comment by Sanaki** [comment]
Same issue appears to apply to Mint, at least on 19.3.

**Comment by Sanquinary** [comment]
Same issue here; Fedora 33.

**Comment by Sophon96** [comment]
I can also confirm that it does not work on CentOS Stream 8.

**Comment by OlaoluwaM** [comment]
And fedora 35

**Comment by nairvarun** [comment]
same issue on fedora 36

**Comment by Titor8115** [comment]
(Edit: I even got it working on Alacritty but no luck on the fedora gnome-term)

Damn. It seems this issue lasted 6 years on Fedora for their distribution of gnome-terminal. Probably messed up somewhere when compiling the gnome-terminal from source. Also I find it interesting that the gnome-terminal on Fedora doesn't actually use any wrapper only the gnome-terminal-server is running

**Comment by LunarWatcher** [comment]
Same problem on Linux Mint 21, also using Gnome Terminal

**Comment by capta1nt0ad** [comment]
The same issue is occurring on Linux Mint 19.3, 20.3, and 21. Looks like they patched it too 😕

**Comment by Just-Koi** [comment]
Fedora 37, doesn't update the photo after running: neofetch --w3m --source /home/terminal/bad.png, w3m and imagemagick dependencies are installed successfuly

**Comment by TanXiRan** [comment]
Fedora39 and gnome terminal, dependencies are successfully installed, but it dosen't display the image.
