### ISSUE TITLE
Missing distro ASCII: OpenWRT

### ISSUE THREAD

**Issue by dawidd6** [dylanaraps/neofetch#314]
Would be nice to have it in neofetch. Original OpenWRT ASCII is located in file /etc/banner, can be useful.

**Comment by dylanaraps** [comment]
This PR adds the ascii logo, the only issue is that it's a lot longer than the other logos so the info might not fit on the screen. Are there any alternate logos?

**https://github.com/dylanaraps/neofetch/pull/315**

**Comment by dylanaraps** [comment]
There's also this alternate logo with `WIRELESS FREEEDOM` below it, let me know which variant you like.

```sh
"\
${c1} _______                     ________        __
|       |.-----.-----.-----.|  |  |  |.----.|  |_
|   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
|_______||   __|_____|__|__||________||__|  |____|
         |__| W I R E L E S S   F R E E D O M
"
```

**Comment by dawidd6** [comment]
It's good without. I thought so, that it will be a bit too wide
