### ISSUE TITLE
OpenWRT issues

### ISSUE THREAD

**Issue by dawidd6** [dylanaraps/neofetch#317]
Neofetch on OpenWRT 15.05.1 looks like this:

![zrzut ekranu z 2016-08-25 11-08-33](https://cloud.githubusercontent.com/assets/9713907/17963123/4ae17cbe-6ab4-11e6-989f-61e5c20fc361.png)

I've tried to figure it out myself and only what i have right now is:

1.
awk -F "'" '/^DISTRIB_DESCRIPTION/ {print $2}' /etc/openwrt_release
>this command prints OS name + version
>example: OpenWrt Chaos Calmer 15.05.1

2.
OpenWRT doesn't have os-release file, but openwrt_release

Here is neofetchlog:
http://termbin.com/t3pp

**Comment by dylanaraps** [comment]
Does the new branch `openwrt-fixes` solve the issue?

**Comment by dawidd6** [comment]
OK, i will just help you to fix this problems instead of making PR.

1. For now you don't have this uptime fix in **openwrt-fixes** branch. Revert revert it :-D
2. Disk usage is working with that command (busybox's `df` is limited):
`df -h 2>/dev/null | awk '/rootfs/ {print $2 ":" $3 ":" $5}'`
3. ASCII is in background of text, see screen below

Screen has been taken after **uptime** and **disk** fixes:

![zrzut ekranu z 2016-08-25 17-30-55](https://cloud.githubusercontent.com/assets/9713907/17975410/d1ef4d50-6ae9-11e6-86ae-12bd518a5ef8.png)

**Comment by dylanaraps** [comment]
I'm running OpenWRT in a VM now and here's what I've found so far.

- There's no `tput` or `stty` installed and you can't install them with `opkg`.
- There's no way to get max package count with `opkg`.

**Comment by dylanaraps** [comment]
Progress!

![virtualbox_openwrt_26_08_2016_11_11_56](https://cloud.githubusercontent.com/assets/6799467/17990975/f0b7e9d8-6b7d-11e6-835a-6027368d94b9.png)

**Comment by dylanaraps** [comment]
Changes merged.

Thanks for opening this issue. :P

**Comment by dawidd6** [comment]
Nice
