### ISSUE TITLE
support on debian testing and sid

### ISSUE THREAD

**Issue by jemadux** [dylanaraps/neofetch#331]
## Description

it would be awesome if you suport those brances of debian

**Comment by dylanaraps** [comment]
What isn't supported exactly?

iirc everything should work already.

Also screenshots would be helpful.

**Comment by konimex** [comment]
Debian stretch user here, everything works as expected.

I assume @jemadux wants the repo to extend its support to stretch and sid? It's just a package and using `jessie` for the repo in stretch/sid still works rather well so I don't see the point in adding more branches/"supporting" those.
