### ISSUE TITLE
Not clearing terminal produces mangled terminal text

### ISSUE THREAD

**Issue by GillesJ** [dylanaraps/neofetch#335]
## Description
I want to use neofetch by calling it as a message-of-the-day (motd) on an ubuntu server. (Neofetch is much better than screenfetch for this use-case as it is significantly faster.) Because I call neofetch after another motd is printed, I want to disable the screen clearing.

I removed the `clear` command on line 3124 of current source to achieve this. This produces weird glitches where the text of the following motd terminal output is mangled with the neofetch output.

Reproduce:
- Remove line 3124 in neofetch source (`clear`) to prevent clearing, recompile
- make the motd calling script for neofetch: 
`sudo nano /etc/update-motd.d/98-neofetch` containing
```
#!/bin/sh
echo
neofetch
echo
```
- make executable
`sudo chmod +x /etc/update-motd.d/98-neofetch`
- log in locally or remotey to see the motd if it is enabled on your distro. Terminal text looks mangled.

## System Information
Ubuntu 16.04 server edition. Zsh and bash shell.
#### Neofetch version
From latest source.

**Comment by dylanaraps** [comment]
I'll look into fixing this, thanks.

**Comment by dylanaraps** [comment]
#339 should fix this issue, please test it out.
