### ISSUE TITLE
neofetch cannot find arch linux os-release

### ISSUE THREAD

**Issue by bigmittens** [dylanaraps/neofetch#336]
Ever since [this](https://git.archlinux.org/svntogit/packages.git/commit/trunk/PKGBUILD?h=packages/filesystem&id=66553654434fbe2c3c30c0fa3f96e87bba79e3f4) commit the Arch Linux filesystem has installed os-release to /usr/lib/ instead of /etc/ (where neofetch looks for the release file).

While script will function for users who installed the Arch before 2014-07, any later installations will cause the script to fail to find the file.

**Comment by dylanaraps** [comment]
Fixed, thanks for opening this PR!
