### ISSUE TITLE
Allow uploading of images to file sharing site

### ISSUE THREAD

**Issue by uncled1023** [dylanaraps/neofetch#344]
## Description

Allow the option to automatically upload the image generated to a file storage website.  (Teknik, Imgur, Pomf, etc)

Most use simple json responses and rest APIs, so wouldn't be too hard to integrate.  Also, there are already some code snippets around doing it.

**Comment by iandrewt** [comment]
I'll work on an imgur function tomorrow. And also add screenshot support on macOS if it's not there already

**Comment by uncled1023** [comment]
Here's some sample code for uploading to some sites.    Only a few lines needed.

https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L2456

**Comment by dylanaraps** [comment]
Screenshot support defaults to using `scrot` and has options/flags to change the program used, we could possibly add OS/program detection but we'll need to think of the best way to do this first. 

What happens if the user has `scrot` + another screenshot program installed? I imagine that for Mac OS and Windows we can use whatever built in method they support which makes things easier.

I feel like screenshot uploading is a little out of scope for neofetch but if there's demand then I'm open to adding this. :+1:

**Comment by dylanaraps** [comment]
It seems as though Screenfetch's image uploading no longer works(?), the curl commands used return either a 403 or 404 error. It also looks like imgur now requires an api key so we'll have to either provide our own or prompt the user to get one and set it in the config.

Here's the updated curl commands so far:

```sh
# teknik
curl -sf -F "file=@${image_file}" https://api.teknik.io/v1/Upload
```



```

**Comment by dylanaraps** [comment]
Are there any specific sites apart from `teknik` and `imgur` that you guys would like to see added as an upload destination?

**Comment by uncled1023** [comment]
Ah yea, looks like screenfetch was using outdated APIs.  Those new curl commands should work.  Imgur requires an API key?  I was looking through the API docs and it looked like for anonymous uploads, only the Client-ID was needed.  (Or is that the key you are talking about)

**Comment by dylanaraps** [comment]
Yes

**Comment by dylanaraps** [comment]
I did some digging and it looks like we won't be able to get screenshot functionality working on Windows without adding a new program as a dependency. There's no built in way of taking screenshots from the command-line. 

See this page for a list of programs we can possibly use: http://superuser.com/questions/75614/take-a-screen-shot-from-command-line-in-windows

**Comment by dylanaraps** [comment]
Merged with support for Imgur and Teknik.

The enhancements to the scrot function will come in a later PR.
