### ISSUE TITLE
neofetch doesn't display wallpaper

### ISSUE THREAD

**Issue by killmaster** [dylanaraps/neofetch#346]
## Description

neofetch doesn't get my wallpaper correctly from gsettings and displays the ascii art. I don't have feh nor nitrogen installed and the `gsettings get org.gnome.desktop.background picture-uri` command returns the path to the wallpaper correctly.

#### Neofetch version
1.8 (but had the same problem with the previous one)
#### Operating system
Arch Linux x86_64
## Screenshot
[http://i.imgur.com/dJK2jV2.png](url)
## Verbose log
http://pastebin.com/KbFvsveq

**Comment by killmaster** [comment]
The problem is with the way spaces are treated. 
`img="${img//%20/ }"` when you strip quotes from the path solves this but generates a new bug. Now the image won't show if it exists in the cache.

**Comment by dylanaraps** [comment]
What is the file called on the disk?

**Comment by killmaster** [comment]
The file is called `380 - gm4yQSN.jpg`

**Comment by dylanaraps** [comment]
Adding this line `img="${img//%20/ }"` to the script, running `neofetch --clean` and then running neofetch normally fixed both issues for me. I've pushed the change to master so grab the latest git version or add the line to the script manually and let me know if this fixed it for you.

![neofetch-2016-10-03-10-09-53-21129](https://cloud.githubusercontent.com/assets/6799467/19024528/363c562e-8951-11e6-8fbd-0114c8017e10.png)

**Comment by killmaster** [comment]
I already had that change in my code but pulled yours from the repo. Same problem. Runs the first time but doesn't show the image on the next runs. If there's a thumbnail in the cache it just shows a blank spot where there should be an image. 
![screenshot from 2016-10-03 00-22-14](https://cloud.githubusercontent.com/assets/167298/19024644/321cf74c-88f7-11e6-8c82-e662ff264942.png)

**Comment by dylanaraps** [comment]
Weird, what are the contents of your thumbnail folder? 

- `ls "$HOME/.cache/thumbnails/neofetch"`

**Comment by killmaster** [comment]
Before or after the clean run?

**Comment by dylanaraps** [comment]
After running neofetch so it can generate a thumbnail.

**Comment by killmaster** [comment]
![screenshot from 2016-10-03 00-32-56](https://cloud.githubusercontent.com/assets/167298/19024716/3e67532e-88f9-11e6-9abe-eda23fe89d18.png)

**Comment by dylanaraps** [comment]
Can you also send me a log of when neofetch fails to display the image?

**Comment by killmaster** [comment]
Here you go:
http://pastebin.com/TQbFywum

I also noticed that it's not always reproducible. Sometimes it actually shows the image, but not most of the time. The only time it always shows it is with a clean thumbnail cache.

**Comment by dylanaraps** [comment]
I'm not entirely sure about how to fix this one, I'll have to take a closer 
look when I get home today.

**Comment by dylanaraps** [comment]
The log file shows that the correct image/path is passed to w3m-img and that w3m-img is running correctly. This is an issue elsewhere in the script, I'm working on a fix now.

**Comment by dylanaraps** [comment]
Adding `sleep 1` to line `3170` right below `getimage` stops the issue from occurring on my machine. This makes me think that the issue is timing related. (The `getimage` function finishes too quickly(?))

I'll mess around and see if I can fix this without adding a 1 second delay to the script. Try the above and let me know if it stops the issue from occurring.

**Comment by zar0us** [comment]
how can fix, same error @killmaster  @dylanaraps
