### ISSUE TITLE
neofetch doesn't display progress bar correctly in 1.8

### ISSUE THREAD

**Issue by konimex** [dylanaraps/neofetch#347]
## Description

See title.

#### Neofetch version

1.8

#### Operating system

Gentoo 

## Screenshot

`barinfo`
![2016-10-02-232910_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19022025/bf77d05c-88f8-11e6-8115-3342951430b5.png)

`infobar` (test mode)
![2016-10-02-233619_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19022047/230b4234-88f9-11e6-9881-70703cadf51c.png)

At first I think this is related because the terminal screen is too small, but when tested in 1.7, it works as expected.
![2016-10-02-234240_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19022097/ffed005c-88f9-11e6-8bf9-2bfb886217c8.png)
![2016-10-02-234413_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19022102/35c3dfac-88fa-11e6-854f-43a098ad2495.png)

## Verbose log
https://ptpb.pw/DDaR

**Comment by dylanaraps** [comment]
This might be related to locale, if you set the progress bar chars to these values does it work?

```sh
progress_char_elapsed="-"
progress_char_total="="
```

**Comment by konimex** [comment]
Applied the progress char, here's the result.

`barinfo`
![2016-10-03-214502_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19041608/ef695f96-89b2-11e6-800c-d67275980229.png)
`infobar` (test mode)
![2016-10-03-214621_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19041623/ffb040a4-89b2-11e6-9296-218f7995a715.png)

Comparison to 1.7:
`barinfo`
![2016-10-03-214522_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19041643/09faf590-89b3-11e6-9f2e-fc7c8e37660a.png)

`infobar` (test mode)
![2016-10-03-214639_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19041649/1078c5a0-89b3-11e6-9120-f891943aacaa.png)

Output of `locale`:
```
LANG=en_US.utf8
LC_CTYPE=en_US.utf8
LC_NUMERIC=id_ID.utf8
LC_TIME=id_ID.utf8
LC_COLLATE=C
LC_MONETARY=id_ID.utf8
LC_MESSAGES="en_US.utf8"
LC_PAPER=id_ID.utf8
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by dylanaraps** [comment]
Does the issue still occur with a clean/new config file? I can't seem to reproduce this, it works fine on my desktop and laptop.

**Comment by konimex** [comment]
Fresh from `/usr/share/neofetch/config`, test mode.
![2016-10-04-045128_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19055491/5d3ec9b2-89ee-11e6-8164-a373c6862f73.png)

For some reason it works fine on ASCII mode. Just image mode.
![2016-10-04-045318_570x346_scrot](https://cloud.githubusercontent.com/assets/15692230/19055526/899e78a4-89ee-11e6-98e0-e5db11f15fce.png)

**Comment by dylanaraps** [comment]
I can reproduce this now!

I'll work on a fix when I get home today. :)

**Comment by dylanaraps** [comment]
Fixed.
