### ISSUE TITLE
Typo in man pages, implies it knows the path to Hell.

### ISSUE THREAD

**Issue by zAMLz** [dylanaraps/neofetch#348]
## Description

Under `man neofetch`,  There is a type when talking about Shell paths and Shell versions.

`       --shell_path 'on/off' `
`              Enable/Disable showing HELL path`

`       --shell_version 'on/off'`
`              Enable/Disable showing HELL version`

#### Neofetch version
version 1.8
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
kek, thanks. :+1:
