### ISSUE TITLE
One line padding on top of the title when using the small ascii logo

### ISSUE THREAD

**Issue by tudurom** [dylanaraps/neofetch#352]
## Description

If I invoke neofetch with `--ascii_logo_size small` the title (`tudurom@cabbage`) is one line under the command invoked. See screenshot.

## System Information

I think you can find information about my system in the log. Anyway, it's a Lenovo laptop with Arch Linux on it.

#### Neofetch version

1.8.1 (running `neofetch --version` prints "Neofetch 1.9)

#### Operating system

Arch Linux x86_64, all packages up to date

## Screenshot

http://pub.iotek.org/p/2UjbD70.png

## Verbose log

```bash
neofetch --ascii_logo_size small -vv 2> log
```

http://hastebin.com/videmocore.bash

**Comment by dylanaraps** [comment]
Fixed, thanks for finding this.
