### ISSUE TITLE
URxvt and XFT fonts,  image rendering problems

### ISSUE THREAD

**Issue by nullrndtx** [dylanaraps/neofetch#357]
![alt text](http://i.imgur.com/5NCQyIN.png "image not load perfect")

**Comment by dylanaraps** [comment]
I've figured out the cause of this and I'm working on a fix.

I'm busy today but I'll be free in 8 hours to work on this.

**Comment by dylanaraps** [comment]
I just created #358 which fixes the issue. Try it out and let me know if it works.

**Comment by dylanaraps** [comment]
Fix is now in master.

**Comment by nullrndtx** [comment]
great work, dylan! :dancer:
