### ISSUE TITLE
macOS: Disk not showing?

### ISSUE THREAD

**Issue by mclado** [dylanaraps/neofetch#371]
Hey there!

Long time nothing from me, huh? 

Just did fresh install, loaded package with brew and disks are not showing, even tho they are enabled in config. I can't get it working. Any ideas? [Log](https://gist.github.com/mclado/92bf9418d6e09175ff6686169a26eb07).

**Comment by dylanaraps** [comment]
What's the output of these commands?

- `df`
- `df -l -H /`
- `df -l -H / | awk '/\// {print $2 ":" $3 ":" $5}'`

**Comment by dylanaraps** [comment]
Fixed.

**Comment by dylanaraps** [comment]
If the issue still occurs let me know.
