### ISSUE TITLE
Neofetch information is weird/off

### ISSUE THREAD

**Issue by androvix** [dylanaraps/neofetch#377]
## Description
The picture below gets you the gist of it. Basically little parts of the info is off.

## System Information
64 bit machine
#### Neofetch version
1.8
#### Operating system
Ubuntu MATE 16.10
## Screenshot
http://imgur.com/a/0zJT5

**Comment by dylanaraps** [comment]
I'm a little confused. I'm not sure if it's because I've just woken up but I can't see anything wrong in your screenshot.

**Comment by dylanaraps** [comment]
Ping @androvix

**Comment by dylanaraps** [comment]
Closing this as I still can't see any problems in your screenshot.

Feel free to reopen this when you're around and can explain this better.
