### ISSUE TITLE
Hyperthreading cores shown on Linux

### ISSUE THREAD

**Issue by iandrewt** [dylanaraps/neofetch#379]
## Description

A couple days ago I fixed a bug on macOS where the core count was including hyperthreading cores. I just noticed that my Arch Linux box is doing the same thing. Should this be changed to reflect the macOS changes?

#### Neofetch version

5274d2d54a402c9569449462b212a2a9fb7e8e29

#### Operating system

Arch Linux

**Comment by dylanaraps** [comment]
Maybe it's time to add an option to show hyper-threaded cores. We can call it `cpu_hyperthreaded` and have it on by default.

**Comment by dylanaraps** [comment]
PR opened.

https://github.com/dylanaraps/neofetch/pull/381
