### ISSUE TITLE
Show image in terminal emulator that don't support \033[14t

### ISSUE THREAD

**Issue by srdjantot** [dylanaraps/neofetch#382]
As far as I can tell, neofetch can't display image if it can't get terminal window size.
Do you think it is possible to use [xdotool](https://www.semicomplete.com/projects/xdotool/xdotool.xhtml) for getting window size? Maybe something like this:
```
WIN=$(xdotool getactivewindow)
xdotool getwindowgeometry --shell $WIN
```
It will return something like this:
```
WINDOW=102763394
X=1028
Y=526
WIDTH=826
HEIGHT=554
SCREEN=0
```
You can parse the output or eval it like this:
`eval $(xdotool getwindowgeometry --shell $WIN)`

**Comment by dylanaraps** [comment]
Opened https://github.com/dylanaraps/neofetch/pull/384 which solves this issue.

It adds support for:

- `xdotool`
- `xwininfo + xprop`
- `xwininfo + xdpyinfo`

Please test it out and let me know if it solves the issue for you.

**Comment by srdjantot** [comment]
Works like a charm!

**Comment by dylanaraps** [comment]
Awesome!

I'll merge it after I do some more testing.

Thanks for opening this issue.
