### ISSUE TITLE
Transparent image background

### ISSUE THREAD

**Issue by srdjantot** [dylanaraps/neofetch#386]
It should be great to have option to set image background. `w3mimgdisplay` supports `-bg` option so you should just forward whatever user enters in let's say `--background_color` to `w3mimgdisplay` in `displayimage` function.

**Comment by dylanaraps** [comment]
I need to figure out how to pass this to w3mimgdisplay since we send the values through stdin.

**Comment by srdjantot** [comment]
It is just a command line switch. I needed black background, so i made this quick hack:
```
printf "%b%s\n" "0;1;$xoffset;$yoffset;$width;$height;;;;;$img\n4;\n3;" |\
$w3m_img_path -bg black 2>/dev/null || padding="\033[0C"
```

**Comment by dylanaraps** [comment]
Oh!

**Comment by dylanaraps** [comment]
This doesn't seem to do anything when I try it, can I see a screenshot?

**Comment by srdjantot** [comment]
Sure.

These are screenshots and image I used for logo.

![before](https://cloud.githubusercontent.com/assets/3198465/19600964/8ff60dae-97a7-11e6-9639-e66cc952a1f0.png)
![after](https://cloud.githubusercontent.com/assets/3198465/19600965/8ff8f1d6-97a7-11e6-898a-f4d87a1b62d5.png)
![arch_sh-600x600](https://cloud.githubusercontent.com/assets/3198465/19600988/a4a698d6-97a7-11e6-8900-a6c8a9e42fc3.png)

**Comment by dylanaraps** [comment]
Done.

**Comment by srdjantot** [comment]
Works perfectly!
