### ISSUE TITLE
Draw image after info text

### ISSUE THREAD

**Issue by srdjantot** [dylanaraps/neofetch#387]
One last for today. Some terminal emulators (kde konsole for example) overwrite image when they output info text. If you could calculate everything first (image size, position, offset, info text position, etc...), then output info text, and in the end draw image, everything will look great.

For a quick try, I moved `displayimage` out of `if [ "$image" != "off" ]; then` block in `main` function, and place it after `printinfo` like this:
`[ "$image" != "off" ] && displayimage`

Everything looks nice with that hack even on konsole terminal emulator.

**Comment by dylanaraps** [comment]
Fixed.
