### ISSUE TITLE
cmus song output not working

### ISSUE THREAD

**Issue by ncmprhnsbl** [dylanaraps/neofetch#389]
song output for cmus seems not to work properly:   (with song_shorthand="off")
`Song: -`

heres relevant part output from -vv   
>  + info Song song
+ subtitle=Song
+ '[' -z song ']'
+ getsong
+ eval 'output=$song'
++ output=' - '
+ '[' -z ' - ' ']'
++ trim ' - '
++ set -f
++ builtin echo -E ' - '
++ set +f
+ output=' - '
+ case "$1" in
+ string='\033[1m\033[1mSong\033[0m'
+ string+='\033[0m: \033[0m - '
+ length=9
+ '[' -z song ']'
+ printf '%b%s\n' '\033[47C\033[1m\033[1mSong\033[0m\033[0m: \033[0m - \033[0m'
                                               Song:  - 

this part seems correct:
>$ cmus-remote -Q | grep "tag artist \|title \|status" 2>/dev/null | sort
status playing
tag artist Weedpecker
tag title Into The Woods

with song_shorthand="on"
output is:
`Song`

-vv
>+ info_height=20
+ info Song song
+ subtitle=Song
+ '[' -z song ']'
+ getsong
                                               Song
+ eval 'output=$song'
++ output=
+ '[' -z '' ']'
+ return
+ info linebreak
+ subtitle=linebreak
+ '[' -z '' ']'
+ getlinebreak
+ eval 'output=$linebreak'
++ output=' '
+ '[' -z ' ' ']'
++ trim ' '
++ set -f
++ builtin echo -E ' '
++ set +f
>+ output=' '

using cmus version 2.7.1, in void linux,  neofetch 1.8.1_2

**Comment by dylanaraps** [comment]
Fixed.

**Comment by ncmprhnsbl** [comment]
comfirmed,  thanks :+1:
