### ISSUE TITLE
Wallpaper is not shown on the Terminix terminal

### ISSUE THREAD

**Issue by AnDroidEL** [dylanaraps/neofetch#392]
## Description

Wallpaper is not shown on the Terminix terminal. But in any other terminal (as XTerm) works well.

#### Neofetch version

1.9

#### Operating system

Arch Linux

## Screenshot

![captura de tela de 2016-10-22 23-13-25](https://cloud.githubusercontent.com/assets/9509498/19623732/38642d80-98ad-11e6-91b6-df075f5ded4a.png)

## Verbose log

[http://pastebin.com/mk5kstcs](http://pastebin.com/mk5kstcs)

**Comment by dylanaraps** [comment]
The log file is telling me that all of the correct info is getting sent to w3m-img. For whatever reason w3m-img is exiting with an error code which is causing neofetch to revert to no image mode.

Images load fine in terminix for me. This is with a clean install of the latest version from the aur. Have you tried launching terminix with no config? You might have a config option set that is causing w3m-img to fail. I think the command is `terminix --profile none`.

![img]()

**Comment by AnDroidEL** [comment]
I ran the following command: `terminix --profile none --new-process`. The result continues equal, EXCEPT when I ran from the XTerm terminal. Take a look:

![captura de tela de 2016-10-23 01-14-44](https://cloud.githubusercontent.com/assets/9509498/19624174/5d5a6cb8-98c0-11e6-90a2-64b182f4f820.png)

So... was created a blank space in the Terminix and the image is shown into the XTerm... really, I'm bugged.

I'm using the Terminix 1.3.0 (stable version).

An error also appeared when I ran `neofetch -v > neofetchlog2`, that is:

`[!] Your terminal doesn't support \033[14t, falling back to ascii mode.`

I don't really think that is a problem, because both terminals (Terminix and XTerm) that I have tested here continues with the same result. So, just consider it as an alert.

**Comment by dylanaraps** [comment]
I've figured out why the image is getting drawn in the Xterm window and not the terminix window. It seems like the image is rendered in whatever terminal emulator spawned terminix.  I can reproduce this on my system using the following steps:

1. Open a terminal emulator that isn't terminix.
2. Launch terminix from this new terminal emulator.
3. Launch neofetch from the new terminix window.
4. The image will render in the 1st terminal and not terminix.

I've done some testing with other combinations of terminal emulators and it only affects terminix. If I launch a terminix process from another terminix window then neofetch works as expected.

To me this seems to be a bug between w3m-img and terminix, I don't know if this is causing your original issue though.

**Comment by AnDroidEL** [comment]
I did the same steps that you did.

> I've done some testing with other combinations of terminal emulators and it only affects terminix. If I launch a terminix process from another terminix window then w3m-img works as expected.

Yeah. I tested the Gnome-terminal and it's with the same response too. I agree you. But only the Terminix launched from another Terminix process doesn't show the wallpaper.

![captura de tela de 2016-10-23 02-57-09](https://cloud.githubusercontent.com/assets/9509498/19624475/228e11ee-98ce-11e6-8358-0557a3ce9af6.png)

> To me this seems to be a bug between w3m-img and terminix, I don't know if this is causing your original issue though.

Probably, yes. I don't know what I can do now after the conversation. But I need to thank you for your support. You can close this issue if you want. Thanks for that!

**Comment by dylanaraps** [comment]
It might be worth opening an issue on terminix's github page.
