### ISSUE TITLE
Bash on Windows 10 bugs

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#399]
There are various issues with bash on windows. 
- Uptime: `uptime` commands and `/proc/uptime` only count from when the terminal window was opened. **Not** when the pc was turned on.
- Disk: `df` only displays disk information from the disk Windows is installed on.
- ~~Local IP: `ip` and `/sbin/ifconfig` both crash on startup so we can't get any information.~~
    - This should be fixed in the latest WSL.
- CPU Usage: `ps` only displays processes from inside the bash terminal so we can't get an accurate usage output.

**Comment by dylanaraps** [comment]
If we can find a way to run `cmd` commands through the bash terminal then we can fix these issues.

**Comment by xilun** [comment]
@dylanaraps in the next version of WSL you'll be able to run .exe from within WSL (that feature is actually already available in Insider builds). On Win10 1607, short of using 3rd party tools, you can't.

**Comment by dylanaraps** [comment]
That's great to hear!

Thanks for letting me know.

**Comment by dylanaraps** [comment]
Closing this.

**Comment by mnpenner** [comment]
Has this been fixed now that the Creator's Update is out?

**Comment by dylanaraps** [comment]
I don't think so, I remember running into issues when using the `exe` files. (Though this was a while ago and things may have changed.)

I'll setup a windows 10 VM on Monday and have another crack at this.
