### ISSUE TITLE
New Readme Screenshots

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#405]
Hello,

I'm looking for some new neofetch screenshots for the Readme. Post your screenshots
below and I'll pick a few for the Readme.

**Comment by konimex** [comment]
![](https://ptpb.pw/ZKt1.png)

**Comment by donniebishop** [comment]
![neo](https://cloud.githubusercontent.com/assets/7742572/19909276/369cedf4-a05d-11e6-8b00-ce16c86bcee2.png)

**Comment by dylanaraps** [comment]
Thanks guys!
