### ISSUE TITLE
Budgie: Wrong theme information shown

### ISSUE THREAD

**Issue by erikdubois** [dylanaraps/neofetch#408]
## Description
I was posting some screenshots and then I saw that the following information is not read properly.
WM theme
GTK theme
Icon theme
I have included an image for your approval
#### Neofetch version

1.9

#### Operating system

Solus Budgie 1.2.1

## Screenshot

![neofetch](https://cloud.githubusercontent.com/assets/10594806/19898394/1e5fbc18-a05c-11e6-8978-ea8a98554e47.png)

## Verbose log

http://pastebin.com/f2rFJUzJ

**Comment by dylanaraps** [comment]
GTK Theme / Icon Theme has been fixed.

I just need to figure out how to get the WM theme on Budgie. The regular `gsettings` command always shows `Adwaita` for me.

**Comment by dylanaraps** [comment]
I've gone ahead and disabled WM Theme output for Budgie's `mutter` for the reasons in my previous comment.

I'm now closing this issue since the Theme/Icons are displayed correctly now.

**Comment by erikdubois** [comment]
disabling sounds good for budgie
however there is now also I3 on solus and Mate on Solus

**Comment by dylanaraps** [comment]
MATE and i3 shouldn't be affected by this bug afaik.

I'll setup a Solus VM and have a look anyway,

**Comment by dylanaraps** [comment]
MATE is unaffected.

**Comment by ikeydoherty** [comment]
Mutter uses the GTK theme for the WM theme now. So the old theme-name for Mutter is completely unused, and Mutter draws server-side decorations based on the GTK CSS.

This all currently comes from `org.gnome.desktop.interface gtk-theme`, so it's safe to report the existing theme as WM or omit WM theme, as they can never be different
