### ISSUE TITLE
Terminal Font: [Termite] Wrong font

### ISSUE THREAD

**Issue by leohahn** [dylanaraps/neofetch#409]
## Description
Given the following config on termite:
```
[options]
font = Terminess Powerline 16
font = Iosevka Term 14
```
Neofetch picks the font as Terminess, but the correct one is Iosevka (termite picks always the last).

#### Neofetch version
1.9
#### Operating system
OS: Arch Linux x86_64
Kernel: 4.8.6-1-ARCH

## Screenshot
![bug-neofetch](https://cloud.githubusercontent.com/assets/8649380/19908127/2daab954-a082-11e6-9086-02c253074d48.jpg)

**Comment by dylanaraps** [comment]
Fixed.
