### ISSUE TITLE
Division by 0 error

### ISSUE THREAD

**Issue by sykhro** [dylanaraps/neofetch#410]
## Description
The program halts due to a division by 0.
`/usr/bin/neofetch: line 2107: width / font_width + gap + xoffset/font_width: division by 0 (error tok)`

## System Information
Arch Linux x86_64 Linux 4.8.6-1-custom (amdgpu support)
bash 4.3.46, st terminal

#### Neofetch version
1.9-1 (from the AUR)

## Verbose log
http://pastebin.com/TMw7AQe0

**Comment by dylanaraps** [comment]
Fixed.
