### ISSUE TITLE
Division by zero when running over ssh

### ISSUE THREAD

**Issue by zeroxfourc** [dylanaraps/neofetch#415]
## Description
The program crashes when I run it while connected over ssh. It does not display anything other than `/usr/bin/neofetch: line 2107: width / font_width + gap + xoffset/font_width: division by 0 (error token is "font_width + gap + xoffset/font_width")`

#### Neofetch version
1.9

#### Operating system
Host (where Neofetch is): Arch Linux
Client (that I'm ssh-ing from): macOS Sierra 10.12.1

## Verbose log
http://pastebin.com/60nvi7aX

**Comment by dylanaraps** [comment]
Can you try with the latest master?

I'm pretty sure I fixed this issue a few days ago.

**Comment by zeroxfourc** [comment]
Ah, sorry!

**Comment by dylanaraps** [comment]
All good!
