### ISSUE TITLE
macOS bug

### ISSUE THREAD

**Issue by gilgameshskytrooper** [dylanaraps/neofetch#418]
## Description

With the following settings
    neofetch  --config off --underline off  --image/Users/andrewlee/Documents/Backup/neoterm/termstart.jpg --crop_mode fill --disable gpu disk shell os kernel username resolution packages model macos de wm terminal  --underline off -color_blocks off --speed_type max --cpu_speed on --cpu_display mode bar --gap 5

## System Information
Using Fish Shell
#### Neofetch version
Neofetch 1.9 from Homebrew
#### Operating system
macOS  10.12.1
## Screenshot
[https://68.media.tumblr.com/8be3640a92ed7448c21e053481502dce/tumblr_og4ap7hK6X1s5a4bko1_1280.png](url)
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by konimex** [comment]
This has been fixed in 1.9.1. [Please wait while we're waiting to get the PR accepted](https://github.com/Homebrew/homebrew-core/pull/6582).

**Comment by dylanaraps** [comment]
1.9.1 is in homebrew so I'm closing this.

If the issue still occurs feel free to reopen this.
