### ISSUE TITLE
Use "$OSTYPE" instead of "$(uname)" for OS detection.

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#433]
## Description

I just found out that `bash` sets a variable called `$OSTYPE` which stores the name of the OS bash is running on. If this variable works correctly in all the operating systems we support then we can drop a `uname` call and potentially speed up the script some more. 

I'm still going to include a fallback to `uname` just in case the variable is empty for some reason.

I can't check the value of the variable from all systems so I'd love some help.

## Testing

Just run this command in a terminal and send me the output:

```sh
bash -c "echo $OSTYPE"
```

| OS     | $OSTYPE |
| ----- | ---------- |
| Linux | `linux-gnu` |
| CYGWIN | `cygwin` |
| Bash on Windows 10 | `linux-gnu` |
| OpenBSD | `openbsd5.9` |
| FreeBSD | `FreeBSD` |
| NetBSD | |
| DragonflyBSD | |
| Mac OS | `darwin15.6.0` |
| iOS | `darwin9` |
| Solaris | `solaris2.11` |
| Android (termux) | `linux-android` |
| Android | `linux-gnu` |
| Haiku OS | `haiku` |
| GNU Hurd | |

**Comment by iandrewt** [comment]
macOS Sierra 10.12.1: `darwin15.6.0`

**Comment by dylanaraps** [comment]
Thanks!

I'll make a branch and get Travis to do it, then we can call Mac OS done imo.

**Comment by dylanaraps** [comment]
PR opened. #434

**Comment by dylanaraps** [comment]
It might be more ideal to use #432 instead of this since `$os` is also used as the distro name on some BSDs. The speed benefit is still there since we have to run uname later on anyway. 

#432 might actually be faster than this.

**Comment by dylanaraps** [comment]
Closing in favor of #432.

**Comment by sharils** [comment]
Hi @dylanaraps - FYI, I just found that $OSTYPE for FreeBSD is `freebsd11.0` instead of `FreeBSD`.

**Comment by dylanaraps** [comment]
iirc we explored this in the past and I don’t remember why but there was a
reason we couldn’t use it.

I’ll search through previous issues and Gitter to see if I can find it.

**Comment by jjlin** [comment]
On NetBSD 8.0, `$OSTYPE` is `netbsd`.
