### ISSUE TITLE
Haiku OS not recognized

### ISSUE THREAD

**Issue by PauloGDPeixoto** [dylanaraps/neofetch#443]
## Description

After installing and running on Haiku OS, I get the error: "Unkown OS detected: Haiku".

#### Neofetch version
1.9.1
#### Operating system
Haiku R1/Alpha 4.1

**Comment by dylanaraps** [comment]
Haiku OS support was added to 2.0 which hasn't been released yet. See the changelog:

https://github.com/dylanaraps/neofetch/blob/master/CHANGELOG.md#operating-system

You'll have to wait till 2.0 is released or install the latest master to use neofetch on Haiku OS.
