### ISSUE TITLE
Bunsenlabs Neofetch has formatting and logo issues

### ISSUE THREAD

**Issue by androvix** [dylanaraps/neofetch#446]
## Description
This is a fresh Bunsenlabs install and neofetch's logo, formatting and font coloration is completely bojangled
## System Information
AMD E1-2100 APU gpu and AMD Radeon HD 8210
#### Neofetch version
1.9.1
#### Operating system
BunsenLabs 8.6
## Screenshot
http://imgur.com/a/O7N01
## Verbose log
???
1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
http://pastebin.com/UpS8TvRx

**Comment by dylanaraps** [comment]
A couple of things:

- What terminal emulator are you using?
   - The screenshot says `x-terminal-emul ` but I can't find any info about it.
- That's not the verbose log.
   - Did you upload the file `neofetchlog`?
   - Did you type it correctly?
- What's the output of `neofetch --version`?
   - It looks like you're using a git version.

In order for me to fix this I need to be able to reproduce it. 

Can you follow these instructions and try out a clean install? Install neofetch using the instructions below and run it with `./neofetch --config off`.

https://github.com/dylanaraps/neofetch/wiki/Installation#latest-git-master-bleeding-edge

**Comment by androvix** [comment]
I found that when the window is inactive, the slight shadow reveals the logo and other missing parts(namely the parts of the neofetch that had dark bold letters).This the combined issue of my terminal and color scheme, solarized dark, messing things up. When switching to a different color scheme the neofetch works fine when compiled from source as you instructed.

**Comment by dylanaraps** [comment]
So this is partly an issue in 1.9.1 and partly an issue with your colorscheme?

Here's a few things you can try:

- `neofetch --bold off`
- `neofetch --ascii_distro arch` (Just to test the colors)
- `neofetch --ascii_colors 1 2 3 4 5 6`

This also might be an issue with your config file, can you upload it to pastebin? (~/.config/neofetch/config)

**Comment by dylanaraps** [comment]
I can reproduce this in any terminal emulator with the Solarized Dark theme. This issue occurs because the color `8` is set to the background color instead of the usual lighter black. 

Neofetch can't do any detection like that so the only workaround is for you to use `neofetch --ascii_colors x` to change the colors of the logo. (There's also a config option)

Note: The only logos affected by this are **Linux** and **Bunsenlabs**.

**Comment by dylanaraps** [comment]
Using a workaround inside the script the text colors will now be colored using the default foreground color of your color scheme. This should fix the text color when using Solarized or other color schemes that color `8` differently.

Thanks for opening this issue.
