### ISSUE TITLE
Imgur not working

### ISSUE THREAD

**Issue by ErraticFox** [dylanaraps/neofetch#450]
I've entered my client id from my application, though where do I go to view the image? I've checked my account even, but didn't find anything new. Verbose log doesn't say anything other than stuff I don't need like uptime.

**Comment by dylanaraps** [comment]
iirc neofetch uploads anonymously to imgur. Even though we upload anonymously the client ID is still needed. I'll take a look and see if we can get account based upload working.

**Comment by dylanaraps** [comment]
Ok, so here's what we have to do to upload to imgur as a user.

1.

**Comment by ErraticFox** [comment]
You took it out of context. I meant if it's uploaded anonymously, how can I find it?

**Comment by dylanaraps** [comment]
The link is printed to the terminal.

**Comment by ErraticFox** [comment]
It doesn't print anything for me. It just runs the ASCII art and info and that's it.

**Comment by dylanaraps** [comment]
Have you modified the client id?

**Comment by ErraticFox** [comment]
I can't edit comment on mobile, but I was doing imgur with single quotes around it.

**Comment by dylanaraps** [comment]
Can I see a screenshot of neofetch?

Also try running it like this:

`neofetch --config off -su --image_host imgur --ascii`

**Comment by ErraticFox** [comment]
What's -su do? I'll have to try it out tomorrow as I'm not at my computer though I'm most likely sure it was the quotes I put around imgur that made it not work.

**Comment by dylanaraps** [comment]
`-s` takes a screenshot.
`-su` takes a screenshot and uploads it.

**Comment by dylanaraps** [comment]
Also, the quotes shouldn't cause issues.
