### ISSUE TITLE
Can't show image with Urxvt

### ISSUE THREAD

**Issue by Raptorneutron** [dylanaraps/neofetch#451]
## Description
Hi there, i've been trying to show my wall with neofetch in urxvt but it doesn't show nothing. I'm running Slackware Current and in Arch I can do it.
I have the latest Neofetch version, cloned on github.

## Screenshot
http://imgur.com/a/FiYI5

**Comment by dylanaraps** [comment]
Can you please send me a log file?

**Comment by Raptorneutron** [comment]
Okay, now I'm at class. When I arrive home I'll sen it.

**Comment by Raptorneutron** [comment]
http://pastebin.com/gxhFhBvw

**Comment by dylanaraps** [comment]
From the log file, neofetch is functioning correctly. 

A few more questions:

- What terminal emulator are you using on Arch?
- What terminal emulator are you using on Slackware?
- What are the versions of the terminal emulators?
- Does this command change anything? `neofetch --config off -vv`
- Do images work inside `ranger` or `w3m` on Slackware?

**Comment by dylanaraps** [comment]
Ping @Raptorneutron

**Comment by Raptorneutron** [comment]
In Slackware i use URxvt v/ 9.22
In Arch I use URxvt v/ 9.22-2
The command doesn't change anything
Ranger and w3m can't display pictures

**Comment by dylanaraps** [comment]
If images also aren't working in w3m and Ranger then this is an issue with your machine and not neofetch.

**Comment by dylanaraps** [comment]
Closing this as it seems to be an issue with @Raptorneutron's system and not neofetch.
