### ISSUE TITLE
neofetch --disable "Packages" doesn't work. 

### ISSUE THREAD

**Issue by shirishag75** [dylanaraps/neofetch#456]
## Description

I tried using neofetch --disable "Packages" as I don't want to show the number of Packages in my system but that didn't work. 

## System Information 

```
-- System Information:
Debian Release: stretch/sid
  APT prefers testing
  APT policy: (600, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (1, 'experimental-debug'), (1, 'experimental'), (1, 'unstable')
Architecture: amd64 (x86_64)

Kernel: Linux 4.8.0-1-amd64 (SMP w/2 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

-- no debconf information
```

Output from neofetch -

```
 shirish@debian 
    ,g$$$$$$$$$$$$$$$P.      -------------- 
  ,g$$P"\     """Y$$.".      Model: System Product Name System Version 
 ,$$P'              `$$$.    OS: Debian GNU/Linux testing (stretch) x86_64 
',$$P       ,ggs.     `$$b:  Kernel: 4.8.0-1-amd64 
`d$$'     ,$P"'   .    $$$   Uptime: 10 hours, 35 minutes 
 $$:      $$.   -    ,d$$'   Shell: zsh 5.2 
 $$\;      Y$b._   _,d$P'    Resolution: 1600x900 
 Y$$.    `.`"Y$$$$P"'        DE: MATE 
 `$$b      "-.__             WM: Metacity (Marco) 
  `Y$$                       Theme: Menta [GTK2/3] 
   `Y$$.                     Icons: Menta [GTK2/3] 
     `$$b.                   CPU: Pentium E5400 (2) @ 2.7GHz 
       `Y$$b.                GPU: Intel Integrated Graphics 
          `"Y$b._            Memory: 1507MB / 1994MB 
              `"""            
```

I have deliberately left out the Packages information. 

#### Neofetch version

```
┌─[shirish@debian] - [~] - [6567]
└─[$] neofetch --version
                                                                                                             
Neofetch 1.9.1
```

#### Operating system

Debian 

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

This is what I got -

https://paste.debian.net/898658/

I don't see any difference between neofetch and neofetchlog except on the next prompt I see these following characters -

```
┌─[shirish@debian] - [~] - [6576]
└─[$] ;592;1585t62;9;c 
```

**Comment by dylanaraps** [comment]
The correct command is `neofetch --disable "packages"`. Due to the way the `--disable` flag works the arguments have to all be in lowercase. 

However, I've just pushed a change to neofetch that fixes this requirement and `--disable packages/Packages/PACKAGES` now all work. I've updated the docs to mention this too.

So until the next version of neofetch is released, keep in mind that the arguments for `--disable` must all be lowercase.
