### ISSUE TITLE
Packages: Neofetch launches pacman game.

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#457]
Original bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845629

## Description

Neofetch's package manager detection detects the game `pacman` as arch's package manager and launches it. This stops neofetch from functioning correctly and also opens a window on the user's system. 

One possible solution from the link above is to remove `/usr/games` (Where Debian and Ubuntu installs the game) from the path inside the script. This is a good solution if we can implement it reliably and I'm working on it as we speak.

When neofetch was packaged for Solus they ran into the same issue. Only their solution was to patch neofetch and remove the two lines related to `pacman` altogether. They did this because there's no way of ever running Arch's package manager on Solus.

**Comment by dylanaraps** [comment]
Here's a patch against 1.9.1.

Patch (1.9.1):

```diff
--- neofetch	2016-11-25 23:54:15.623345609 +1100
+++ neofetch-fix	2016-11-25 23:54:29.370012337 +1100
@@ -375,6 +375,14 @@
 # Package Count {{{
 
 getpackages() {
+    # Remove /usr/games from $PATH.
+    # This solves issues with neofetch opening the
+    # 'pacman' game.
+    local PATH=":${PATH}:"
+    local PATH="${PATH/':/usr/games:'/:}"
+    local PATH="${PATH%:}"
+    local PATH="${PATH#:}"
+
     case "$os" in
         "Linux" | "iPhone OS" | "Solaris")
             type -p pacman >/dev/null 2>&1 && \

```

**Comment by konimex** [comment]
>```+++ neofetch-fix	2016-11-25 23:54:29.370012337 +1100```Here's a patch against 1.9.1.

Shouldn't this be just `neofetch` since we're patching the same file?

Anyway, pinging neofetch Debian maintainer @iwamatsu.

**Comment by dylanaraps** [comment]
The patch still works correctly (at least on my machine). I've fixed it anyway. :+1:

**Comment by iwamatsu** [comment]
Hi!

LGTM. and I just upload debian package for fixed version.

Thanks!

**Comment by dylanaraps** [comment]
Thanks! :)
