### ISSUE TITLE
GPU not identified anymore

### ISSUE THREAD

**Issue by zoutiyx** [dylanaraps/neofetch#465]
## Description
Upon installing for the first time (some time in the 1st quarter of this year), my GPU showed in the output of the neofetch command. Now with 1.9.1, my GPU defaults to a generic name `Intel Integrated Graphics` (in the screenshot below).

I have done my own tests to verify my GPU using the command in the script. The output of `$(PATH="/sbin:$PATH" lspci -mm | awk -F '\\"|\\" \\"' '/3D|VGA|/ {print $3 " " $4}')` on my system (formatted) is: 

```
Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor DRAM Controller
Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller
Intel Corporation 4th Gen Core Processor Integrated Graphics Controller
Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI
Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1
Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 
Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller 
Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 
Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #2 
Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 
Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 
Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 
Intel Corporation HM86 Express LPC Controller 
Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] 
Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller
NVIDIA Corporation GM107M [GeForce GTX 860M]
Intel Corporation Wireless 7260 
Realtek Semiconductor Co., Ltd. RTL8411B PCI Express Card 
Reader Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
```
Line 16 (the 4th to last line) confirms the presence of my NVIDIA GPU.

I then went to the github repo and downloaded tag versions 1.6 (around the time neofetch used to work) through to 1.9.1 and I realized that from 1.6 to 1.8.1, my GPU is shown and refused to show in versions 1.9 and 1.9.1 (screenshots below). I even downloaded the `gpu_fix` tag to no avail.

### Isolated Problem First Occurrence 
I managed to isolate when the problem first occurred by forking the repository and doing a by-tag compare and opening all commits with gpu in their description. I then proceeded to download and run each which revealed the problem lied in the commit [Refactor GPU](https://github.com/zoutiyx/neofetch/commit/cc9095ccd5bcd31383fb51d754cd998d118e16d6). Due to my limited bash knowledge and absence of time, I won't be able to fix it myself. But I'm hoping it can be resolved.

#### Neofetch version
1.9.1

## Screenshots (labeled versions)
**1.9.1**
[![neofetch 1.9.1.png](https://s12.postimg.org/mrxboh51p/neofetch_1_9_1.png)](https://postimg.org/image/rqku308uh/)

**1.9**
[![1.9.png](https://s18.postimg.org/40qez2hyx/1_9.png)](https://postimg.org/image/bgpokv5o5/)

**1.8.1**
[![neofetch1.8.png](https://s12.postimg.org/9h62h1d19/neofetch1_8.png)](https://postimg.org/image/aw7n5re49/)

**1.6**
[![neofetch1.6.png](https://s17.postimg.org/f9gw0kpq7/neofetch1_6.png)](https://postimg.org/image/5ox9dp0e3/)

**commit 5dddaa0b260d115d1db2f06c5e6c7838f6e6a48d**
[![commit.png](https://s17.postimg.org/hzvetazb3/commit.png)](https://postimg.org/image/x8lc72szf/)

## Verbose log
if still necessary, posted on [pastebin](http://pastebin.com/n7y5N94F)

**Comment by konimex** [comment]
I'm going to guess, you're on a laptop?

I had the same problem with you, only my problem is not because of lack of detection, but rather lack a `Display` in the awk (`/Display|3D|VGA/`). But since you said that it worked on 1.8.1, I'm going to take a guess that it because of the behavior as following:

If you run `PATH="/sbin:$PATH" lspci -mm | awk -F '\\"|\\" \\"' '/Display|3D|VGA/ {print $3 " " $4}'` (I added Display on purpose because it seems `3D` doesn't exist anymore in my output and replaced by `Display`), it should be similar like this:

```
Intel Corporation Device 5916
Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430]
```

lspci detects Intel Integrated GPU first then your discrete GPU, then because neofetch picked up Intel first, neofetch takes Intel based on the next case.

-----

In the git (2.0) version, though, the method will be replaced by detecting which GPU is active. If one is using a laptop, and runs the command:
`PATH="/sbin:$PATH" lspci -k | grep -A2 -F 'VGA' | grep -B2 -F 'Kernel driver in use'`
the output will be always "Intel" should one use an Intel CPU (because the display will always be connected with Intel GPU, only calling discrete GPU when needed), as the discrete GPU is in 3D/Display instead of VGA (this is not the case in regular computers, though).

**Comment by zoutiyx** [comment]
@konimex,

> In the git (2.0) version, though, the method will be replaced by detecting which GPU is active. If one is using a laptop, and runs the command:
> PATH="/sbin:$PATH" lspci -k | grep -A2 -F 'VGA' | grep -B2 -F 'Kernel driver in use'

This will be rather ineffective in accurately displaying the system information. CPU != GPU, especially when there is a discrete GPU installed on the machine. There needs to be more accuracy involved. 

I wonder what the change from the old method?

**Comment by konimex** [comment]
I believe it's PR #421.

**Comment by dylanaraps** [comment]
We could add multi GPU handling to neofetch by splitting the output into two or more lines like we do with battery. Example:

```sh
GPU0: Intel Integrated Graphics
GPU1: AMD HD 7950
```

Another solution is to check if a dedicated card is found next to the integrated one and then favor the dedicated card in the output. So if neofetch finds and Intel and NVIDIA card, we discard the Intel one and only display the NVIDIA one.

The second option seems easy to implement, what do you guys think?

**Comment by konimex** [comment]
Unless there's a case where someone is so rich he has a separate NVIDIA and AMD GPU for his rig, the second one seems to be a better option.

I'm fine with either way.

**Comment by dylanaraps** [comment]
@zoutiyx, does https://github.com/dylanaraps/neofetch/pull/468 fix your issues?

**Comment by dylanaraps** [comment]
Ping @zoutiyx

**Comment by konimex** [comment]
#468 fixed it in my end (I had the exact same issue, just realized).

**Comment by dylanaraps** [comment]
Awesome, I'll merge it then.

**Comment by zoutiyx** [comment]
@dylanaraps,

I apologize for the late reply, but yes, it did fix my issue. Had to leat you know it did.

[![FIXED.png](https://s11.postimg.org/q48zr6rcz/FIXED.png)](https://postimg.org/image/airo78fen/)

**Comment by dylanaraps** [comment]
You're seeing the issue with the `\` in the ascii art because you're using ascii art files from version **1.9.1** with the **git version** of Neofetch. The ascii art file format changed recently so you can't use the old files with the newest version of Neofetch.

**Comment by zoutiyx** [comment]
What do you mean? The screenshot above was taken 2 minutes before my comment above from the master branch. a `neofetch --version` reveals version `Neofetch 2.0`. Anything I'm missing?

**Comment by dylanaraps** [comment]
The git version is always labeled internally as the next version number to be released so that when I do release a new version the version numbers already line up. 

When 2.0 is released the internal version numbers will be bumped to 2.1 and the cycle continues. 

I hope this clears things up. Neofetch 2.0 will be released hopefully this week, I'm still writing docs and wiki pages.

**Comment by zoutiyx** [comment]
@dylanaraps,

> The git version is always labeled internally as the next version number to be released so that when I do release a new version the version numbers already line up.

Okay I see.

> You're seeing the issue with the \ in the ascii art because you're using ascii art files from version 1.9.1 with the git version of Neofetch

How do I go about fixing this?

**Comment by dylanaraps** [comment]
Run `sudo make install` inside the git version's directory to install the newer files.

Again, please stop commenting on the issue tracker for unrelated issues. Use the gitter chatroom as I said above... 

https://gitter.im/dylanaraps/neofetch

> Note: Next time you want to chat, use the gitter. Everytime someone comments on an issue the ~40 watchers of this repo get a notification. https://gitter.im/dylanaraps/neofetch
