### ISSUE TITLE
Unreal very big CPU Intel Core i7-3930K (12) @ 5.7GHz frequency

### ISSUE THREAD

**Issue by esoner** [dylanaraps/neofetch#469]
## Description
I got an unreal very big CPU Intel Core i7-3930K (12) @ 5.7GHz frequency.

#### Neofetch version
neofetch_1.9.1-1ubuntu1_all

## Screenshot
![0001](https://cloud.githubusercontent.com/assets/12882586/20771619/129b1be6-b742-11e6-8acd-951934679bdb.jpg)

**Comment by esoner** [comment]
astronom@ubuntu:~$ grep MHz /proc/cpuinfo
cpu MHz		: 1695.000
cpu MHz		: 1442.125
cpu MHz		: 1359.750
cpu MHz		: 1464.000
cpu MHz		: 1322.250
cpu MHz		: 1273.250
cpu MHz		: 1970.625
cpu MHz		: 1600.250
cpu MHz		: 1620.125
cpu MHz		: 1457.875
cpu MHz		: 1828.750
cpu MHz		: 1697.875

**Comment by dylanaraps** [comment]
Thanks for opening this!

What's the output of these commands?

```sh
# Default value
# Same as neofetch --speed_type max
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

# Prints current usage
# Same as neofetch --speed_type current
/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq

# List all speed types
ls /sys/devices/system/cpu/cpu0/cpufreq/
```

**Comment by esoner** [comment]
astronom@ubuntu:~$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
5700000

astronom@ubuntu:~$ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
1270250

astronom@ubuntu:~$ ls /sys/devices/system/cpu/cpu0/cpufreq/
affected_cpus               related_cpus                 scaling_max_freq
cpuinfo_cur_freq            scaling_available_governors  scaling_min_freq
cpuinfo_max_freq            scaling_cur_freq             scaling_setspeed
cpuinfo_min_freq            scaling_driver
cpuinfo_transition_latency  scaling_governor
astronom@ubuntu:~$

**Comment by dylanaraps** [comment]
Running neofetch with `neofetch --speed_type current` or editing the config file and changing `speed_type="max"` to `speed_type="current"` will fix your issue.

I'm also going to change the default value in the next version of neofetch to `current`.

Thanks for opening this issue. :)

**Comment by esoner** [comment]
![0004](https://cloud.githubusercontent.com/assets/12882586/20775185/9bcfd708-b751-11e6-9188-10105b63aea5.png)

**Comment by dylanaraps** [comment]
Did this fix your issue?

**Comment by esoner** [comment]
Yes, of course.
