### ISSUE TITLE
Permanent ebuild thread for updates

### ISSUE THREAD

**Issue by z1lt0id** [dylanaraps/neofetch#47]
Hi Dylan,

Letting you know i've updated the ebuild to correspond to your makefile.  On a side note still only one 970 pops up.

**Comment by dylanaraps** [comment]
Awesome, thanks!

I'll remove the gpu count stuff for now, I know why it isn't working and it'll be tricky to fix.

**Comment by dylanaraps** [comment]
@z1lt0id, GPU count should be fixed now, pleast test it out!

**Comment by z1lt0id** [comment]
`GPU: Nvidia GeForce GTX 970  x 2`

worked but there is a double white space before the

**Comment by dylanaraps** [comment]
Before the `x`??

**Comment by z1lt0id** [comment]
correct 

On 2016-02-03 21:32, Dylan Araps wrote: 

> Before the x?? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/dylanaraps/fetch/issues/47#issuecomment-179156089

**Comment by dylanaraps** [comment]
I pushed a fix about an hour ago, are you able to test it out?

**Comment by dylanaraps** [comment]
@z1lt0id, any update on you testing the GPU count?

**Comment by z1lt0id** [comment]
It works :)

**Comment by dylanaraps** [comment]
`dylan.araps at gmail.com`

**Comment by z1lt0id** [comment]
Yes sir

**Comment by z1lt0id** [comment]
Updated ebuild to official 1.1

**Comment by z1lt0id** [comment]
added 9999 ebuild of fetch - its essentially the "-git" version equivalent in aur.  so it will just grab the latest commit.

**Comment by z1lt0id** [comment]
1.3 is now available

**Comment by dylanaraps** [comment]
See https://github.com/dylanaraps/neofetch/issues/115
