### ISSUE TITLE
Wallpaper: [Cinnamon] Wrong wallpaper displayed.

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [dylanaraps/neofetch#470]
## Description

Please see title and attached image.

#### Neofetch version

1.9.1-1ubuntu1

## Screenshot

![screenshot](https://cloud.githubusercontent.com/assets/9998846/20807685/d775f994-b7f7-11e6-82c6-9d053b9382ac.png)

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

Logs:

http://pastebin.com/4pLCgby9
http://pastebin.com/86GUac68

I am on Linux Mint 18.1. Reinstalling neofetch did not help. Previously I had no problem. (I am unsure what has changed on my system in the meantime.)

**Comment by dylanaraps** [comment]
I need some more info before I'll be able to help:

- Do you have a `.fehbg` file in your home directory? 
    - If so, delete it and see if this fixes the issue.
- The two pastebin links aren't neofetch logs, they're config files.
    - The log file is different, it looks like this: http://pastebin.com/gxhFhBvw

**Comment by ACinnamonUserInUK** [comment]
Thank you for the response.

I do not seem to have that .fehbg file anywhere on my system.

Sorry about providing the wrong log file(s). The correct one should now
be here: http://pastebin.com/fLFPZj05

**Comment by dylanaraps** [comment]
All good!

This is the command Neofetch is running to get your current wallpaper:

```sh
gsettings get org.gnome.desktop.background picture-uri

# Output from neofetch
/home/nicholas/Firefox_wallpaper.png
```

Cinnamon might have it's own gsettings command for getting the wallpaper, I'll do some investigation.

**Comment by dylanaraps** [comment]
Does this command print out the right image?

```sh
 gsettings get org.cinnamon.desktop.background picture-uri
```

**Comment by ACinnamonUserInUK** [comment]
The output of that command is as follows (and the quotation marks are in
the original).

   
'file:///home/nicholas/Desktop/Pictures/wallpapers/Misc%20backgrounds/Black,%20grey/68554494-black-abstract-wallpapers.jpg'

and that does seem to be the right file. (Unfortunately I have some
rather similar images with similar names. I could give the files names
that are more intuitive.) Still, I should be seeing not a wallpaper but
a distribution logo, no? That's what I use to see, and what I am used to
seeing in people's screenshots.

**Comment by dylanaraps** [comment]
If image mode is available (w3m-img / imagemagick are installed) then Neofetch will use it by default. You can launch Neofetch with `--ascii` or edit your config file and change `image="wall"` to `image="ascii"` to get the ascii art logos.

I've also fixed the incorrect wallpaper issue and it'll be available next release or if you can't wait you can install the git version. 

If you need anymore help let me know.

**Comment by ACinnamonUserInUK** [comment]
Aha. The ascii mode works when called with the command line option and,
now that I've changed the config file in the manner you suggested, as
the default. Since I don't think I want the image mode, I'm happy.

Also, I am pleased that you fixed the problem with the code. (Does that
include changing the position within the terminal of the fragment of
wallpaper? You can see from the screenshot I supplied that the image
overlaps the window border.)

What puzzles me is that somehow my instance of Neofetch went from
displaying ascii to displaying wallpaper without my having done anything
- not so far as I recall, anyway.

Thank you for the helpful and extremely speed response.

**Comment by ACinnamonUserInUK** [comment]
Ah: perhaps I installed one of the dependencies for the image mode,
thereby enabling it . .

**Comment by dylanaraps** [comment]
The program we're using to draw images `w3m-img` uses a hack to display the images. It just finds the top left corner of the window and plops it there. Neofetch has a couple of config options that alow you to manually fix the issue but no automatic detection of menu bars or etc can be done. 

You can use the launch flags `--xoffset px` or `--yoffset px` to change the left and top margins of the image. There are also config options called `xoffset` and `yoffset` which let you save the values. Here's an example command you can try: `neofetch --yoffset 25`

You'll have to keep messing around with the values until the image isn't covering the ui. :)

Image mode was probably enabled when you installed either `w3m` or `imagemagick`. Neofetch at first didn't support ascii logos so this is why it's default. 

I hope this helps. :)

**Comment by ACinnamonUserInUK** [comment]
The bug - the wrong background showing, and it is misprinted - is alive in Neofetch 3.0.1.2. 

![image](https://cloud.githubusercontent.com/assets/9998846/23098198/4d9f3316-f640-11e6-9451-f78b21f19402.png)

_I have the problem_ **only** _when I assume super-user privileges_ in the terminal. As before, `gsettings get org.gnome.desktop.background picture-uri` names the wrong wallpaper and `gsettings get org.cinnamon.desktop.background picture-uri` gives the right one.

I've been messing with my .bashrc files (specifically, a /etc/bash.bashrc file is now the master one); perhaps that is the (proximate?) cause of the problem.
