### ISSUE TITLE
Public IP: Find a better way for caching

### ISSUE THREAD

**Issue by iandrewt** [dylanaraps/neofetch#474]
## Description

On my laptop, my public IP changes a minimum of 2 times a day, and I rarely reboot my laptop. Using a cache that only resets when rebooting will simply not work with my configuration, so finding a way to make the cache reset on network change (maybe store the BSSID or MAC address of the device the current network interface is connected to and compare the current one with the cached one) or after a time interval would be ideal

#### Neofetch version

2.0

**Comment by dylanaraps** [comment]
The simplest and easiest way to fix this is to disable caching for `public_ip()` and go back to the old behavior. The `public_ip()` function is one of the simpler functions and doesn't have any OS specific detection. We just check for `curl`, `dig` or `wget` and use what's available.

If we decide to try and use MAC address or other identifiers the function would then need OS detection for finding this new info and the function would then grow to a much larger size for the sole purpose of making it faster after first run.

`dig` is already instantaneous so there's no real issue there. If there is however a way to check if the network has changed using `curl` or `wget` then there's a possibility of implementing what I talked about above. This would also keep the function OS independent. 

I'll try and do some investigation but the goal is to get this resolved by `2.0.1`.

**Comment by dylanaraps** [comment]
I've gone and disabled caching until we can come up with a better solution. I had a look at `curl` / `wget` and there doesn't seem to be any flags/options we can use to identify the local network. 

I'll keep this open for a little longer and I'll keep working on this but I doubt we'll be able to get the desired behavior we want.

**Comment by dylanaraps** [comment]
Closing this as there doesn't seem to be a simple way of doing it.
