### ISSUE TITLE
"CPU speed type" config typo

### ISSUE THREAD

**Issue by Brottweiler** [dylanaraps/neofetch#475]
## Description

The [comment](https://github.com/dylanaraps/neofetch/blob/master/config/config#L135) saying what is default, and what actually is default, do not match.

It sais `max` should be default, but actually `current` is default. 

#### Neofetch version

`2.0`

## Screenshot

```sh
# Default: 'max'
# Values:  'current', 'min', 'max', 'bios',
#          'scaling_current', 'scaling_min',
#          'scaling_max'
# Flag:    --speed_type
# Supports: Linux with 'cpufreq'
speed_type="current"
```

**Comment by dylanaraps** [comment]
Thanks! :+1:
