### ISSUE TITLE
Arch Linux Logo is now Apple Logo

### ISSUE THREAD

**Issue by jhova-** [dylanaraps/neofetch#479]
## Description

Before last night update, neofetch displayed evrything correctly, with new update, it displays Apple Logo instead of Arch Linux Logo. I think its because I'm using a kind of new Arch-based distro, but like I said, before the update it displayed Arch Linux Logo.

#### Neofetch Version
2.0-1 (aur package)

## Screenshot
![neofetch](https://cloud.githubusercontent.com/assets/9682838/20852530/7b53d4d6-b8a3-11e6-8752-0bf3c311862b.png)

## Verbose log

http://pastebin.com/Ymt7BviV

**Comment by dylanaraps** [comment]
I've figured out what's causing this and it's definitely a bug. There are two options to fix this, I can make the Arch logo display on Apricity OS again or I can add the Apricity OS logo.

What do you think?

**Comment by jhova-** [comment]
I would say Apricity OS, mainly because its the OS even though its based on Arch. Fast reply mate, keep up the good work.

**Comment by dylanaraps** [comment]
How does this look?

![2016-12-03-094251_3200x1800_scrot](https://cloud.githubusercontent.com/assets/6799467/20852871/7ac54dbc-b93c-11e6-97c0-7f2b731b3645.png)

**Comment by jhova-** [comment]
I think it looks good. And not to criticize but, its a narwhal ;D

**Comment by dylanaraps** [comment]
I guess you're right. ;P

Neofetch 2.0.1 will be released some time this week and the new logo will be available then. Until it's released you can use `neofetch --ascii_distro arch`.

**Comment by jhova-** [comment]
Alrighty then, keep up the great work.
