### ISSUE TITLE
Identify the boot loader and payload

### ISSUE THREAD

**Issue by picsi** [dylanaraps/neofetch#482]
It would be nice to have the boot loader identified: BIOS, UEFI, EFI, Coreboot, Libreboot...

Also the payload: GRUB, SeaBIOS, depthcharge.

See related item: https://github.com/KittyKatt/screenFetch/issues/345

**Comment by dylanaraps** [comment]
This feature is very unlikely to be added to Neofetch as I fail to see how we're going to implement it for every Operating System we support. I foresee this involving a hardcoded list of Bootloaders + bootloader config files and I don't want to go down that route. 

I'm closing this issue. If anyone comes up with any ideas then feel free to open a new issue or comment in this one.
