### ISSUE TITLE
Wrong distro identified (Ubuntu instead of Mint)

### ISSUE THREAD

**Issue by armageddon51** [dylanaraps/neofetch#488]
## Description

As specified, the new version 2 wrongly display Ubuntu instead of Mint.

#### Neofetch version

2.0

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by konimex** [comment]
What's the output of `/etc/os-release`?

**Comment by armageddon51** [comment]
Hello Dylan, thanks for the very quick response.

Ok first, the command was not executable so I change it (chmod a+x) but 
the output give nothing (blank).
Did you change the detection mode from 1.9 ? It works fine there.

Tx

P.S Nice utility ! Great work.

**Comment by konimex** [comment]
We deleted the `lsb_release` way of detecting it and instead relying on `/etc/os-release` and `/etc/*-release` as a fallback but that's about it.

**Comment by armageddon51** [comment]
Ok thanks,

Any way I am not alone with the problem as in the comments
http://www.omgubuntu.co.uk/2016/12/cli-system-tool-neofetch-2-0-released

btw funny : my "lsb_release" output on Mint Kde 17.3 doesn't mention 
Mint in the output. ;-)
and the command does not work in Mint Cinnamon 18 (no lsb module are 
available)

If I can help you in any way don't hesitate.

**Comment by konimex** [comment]
Please paste the output of `cat /etc/os-release`, and `lsb_release -dir`.

**Comment by armageddon51** [comment]
> *maurice@KDE4-MINT:~ >* cat /etc/os-release
> NAME="Ubuntu"
> VERSION="14.04.3 LTS, Trusty Tahr"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 14.04.3 LTS"
> VERSION_ID="14.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

> *maurice@KDE4-MINT:~ >* lsb_release -dir
> Distributor ID: LinuxMint
> Description:    Linux Mint 17.3 Rosa
> Release:        17.3

Roughly the same for Mint 18 but for Version : Xenial 16.04 (different 
computer)
Ah that's interesting !

**Comment by konimex** [comment]
Interesting, `/etc/os-release` is not filled properly by Clement and co. but `lsb_release` is filled in properly.

What do you say about this, @dylanaraps? Should we reinstate `lsb_release` in `get_distro`?

**Comment by dylanaraps** [comment]
We originally removed `lsb_release` from distro detection since it was incorrectly identifying Arch based distros as `Arch` instead of `Antergos` and etc. This is the same issue only backwards.

I've got a solution, if `os-release` says the distro is Ubuntu, we also run `lsb_release`. There shouldn't be a speed decrease since the `os-release` stuff is instantaneous anyway.

**Comment by dylanaraps** [comment]
The best solution will be to use the `/etc/lsb-release` file if it exists. This file stores the information that `lsb_release` uses and will still allow us to drop the `lsb_release` program.

@armageddon51 is there a file called `/etc/lsb-release` on your system?

**Comment by dylanaraps** [comment]
I did some googling and found the same issue on Linux Mint's tracker. Apparently this only affects new installs and updating your system will populate the `os-release` file correctly(?).

Sources:

- https://bugs.launchpad.net/linuxmint/+bug/1641491
- https://bugs.launchpad.net/linuxmint/+bug/1491391

**Comment by dylanaraps** [comment]
Fixed.
