### ISSUE TITLE
Incorrect logo for Ubuntu

### ISSUE THREAD

**Issue by popey** [dylanaraps/neofetch#489]
## Description

On Ubuntu systems the 3 colour 'circle of friends' is used. This is the (very) old, and now incorrect logo. The new single colour logo was introduced in March 2010.

I tested this with neofetch 2.0.1

![image](https://cloud.githubusercontent.com/assets/1841272/20861649/1596625e-b98d-11e6-8a1c-1d03678b5401.png)

**Comment by dylanaraps** [comment]
Neofetch 2.0.1 already includes the new logo. 

https://github.com/dylanaraps/neofetch/blob/master/ascii/distro/ubuntu

**Comment by popey** [comment]
Yay! I wonder why I'm not seeing it in 2.0.1 here?

**Comment by dylanaraps** [comment]
You might be using the 2.0 ascii art with 2.0.1. Neofetch first checks `/usr/share/neofetch` for the ascii art before falling back to the script directory.
