### ISSUE TITLE
Incorrect GPU

### ISSUE THREAD

**Issue by Xeronel** [dylanaraps/neofetch#491]
## Description
The GPU that is detected is incorrect. It is instead grabbing my sound card.

#### Neofetch version
Neofetch 2.0

## Screenshot
![Incorrect GPU](https://puu.sh/sDi0q/341b6ae639.png)

## Verbose log
[Verbose Log](https://paste.ee/p/3rGna)

**Comment by konimex** [comment]
What's the output of `lspci | awk '/Display|3D|VGA/ {print}' ?

**Comment by Xeronel** [comment]
![output](https://puu.sh/sE1Zh/3676e9784e.png)

**Comment by dylanaraps** [comment]
It's matching the `3D` in the sound card name!

I'll update the awk command to fix this.

Thanks

**Comment by dylanaraps** [comment]
@Xeronel, does this command fix your issue?

```sh
PATH="/sbin:$PATH" lspci -mm | awk -F '\\"|\\" \\"' '/"Display|"3D|"VGA/ {print $3 " " $4}'
```

**Comment by Xeronel** [comment]
Looks good to me! :)
![screenshot](https://puu.sh/sEvit/298bf3421d.png)

**Comment by dylanaraps** [comment]
I'll merge the fix into master, thanks for being patient. :)
