### ISSUE TITLE
Cinnamon version not displayed

### ISSUE THREAD

**Issue by erikdubois** [dylanaraps/neofetch#494]
Consider displaying the version of cinnamon.
Applying themes like arc and mint-y for cinnamon it matters if you have a 3.0 or 3.2 cinnamon version.

Thanks for considering to display it.

![mint-y-froly](https://cloud.githubusercontent.com/assets/10594806/20864863/43ed50fe-ba00-11e6-9e50-452fcd45f880.jpg)

**Comment by dylanaraps** [comment]
Fixed.
