### ISSUE TITLE
information very high memory usage

### ISSUE THREAD

**Issue by iagor0ger** [dylanaraps/neofetch#495]
![Imagem](http://i.imgur.com/XqctEru.jpg)

**Comment by dylanaraps** [comment]
I'm booting up a FreeBSD VM to see if I can reproduce this.

Does Screenfetch display the correct amount of memory?

**Comment by iagor0ger** [comment]
Yes and not the amount of memory to be sure, the memory used returns high values

sorry my bad english, i'm not american

**Comment by dylanaraps** [comment]
Your English is great! 

I've figured out the problem and I'm working on it. 

I'm not American either :P

**Comment by dylanaraps** [comment]
Does this command print the correct amount of memory?

```sh
top -d 1 | awk -F ',' '/^Mem:/ {print $5}'
```

**Comment by iagor0ger** [comment]
I think Yes

**Comment by dylanaraps** [comment]
Awesome, thanks for testing!

**Comment by dylanaraps** [comment]
Fixed!

The next neofetch version will be released in a few days.
