### ISSUE TITLE
Display actual IP Address

### ISSUE THREAD

**Issue by mr-gosh** [dylanaraps/neofetch#496]
## Description

to use neofetch as a welcome message it would be helpfull to display the actual ip of the system next to its name - could help to prevent irritation if you use many terminals....

**Comment by dawidd6** [comment]
Private IP or Public IP? It's already in neofetch, just need to enable it in config

**Comment by mr-gosh** [comment]
I meant the private ip
Really? So i didn't search long enough...

**Comment by dylanaraps** [comment]
Neofetch can already display private IP, you just need to enable it in your config.

See this wiki page for more info:

https://github.com/dylanaraps/neofetch/wiki/Customizing-Info

**Comment by anonhostpi** [comment]
How does neofetch handle multiple interfaces?
