### ISSUE TITLE
RFRemix 24 is using the default Linux logo instead of Fedora

### ISSUE THREAD

**Issue by Kunagi7** [dylanaraps/neofetch#497]
## Description

After updating to version 2.0 on RFRemix 24 (Fedora 24) it stopped to display the correct distro. Instead of displaying the Fedora logo it's now displaying the default Linux logo.
OS: RFRemix 24 (Twenty Four) x86_64
#### Neofetch version
Installed from fedora repo:
Name        : neofetch
Arch        : noarch
Epoch       : 0
**Version     : 2.0**
Release     : 1.fc24
Size        : 188 k

## Screenshot

[Screenshot](http://i.imgur.com/M874hi6.png)
Log:
https://gist.github.com/Kunagi7/bfab4028d1d09fadba3ad8acf5a04a11

**Comment by dylanaraps** [comment]
Fixed.
