### ISSUE TITLE
Request adding AOSC OS support

### ISSUE THREAD

**Issue by LER0ever** [dylanaraps/neofetch#503]
## Description
Request adding logo of AOSC OS (a Linux distro)  
Homepage: [aosc.io](https://aosc.io)  
And the AOSC OS 4 Logo is ![here](https://raw.githubusercontent.com/AOSC-Dev/LOGO/master/PNG/aosc-os4-256.png)

**Comment by dylanaraps** [comment]
What's the output of `cat /etc/os-release`?

**Comment by LER0ever** [comment]
```
everette@LER0ever-RPI3 [ ~ ] $ cat /etc/os-release
PRETTY_NAME="AOSC OS (4.0.1)"
NAME="AOSC OS"
VERSION_ID="4.0.1"
VERSION="4.0.1 (Duang-Duang)"
ID=aosc
ANSI_COLOR="1;36"
HOME_URL="https://aosc.io/"
SUPPORT_URL="https://github.com/AOSC-Dev/aosc-os"
BUG_REPORT_URL="https://github.com/AOSC-Dev/aosc-os-abbs"
```
That's the output from Raspberry Pi3 running AOSC OS

**Comment by dylanaraps** [comment]
Done.

**Comment by LER0ever** [comment]
Thanks for the support. (That's fast)

**Comment by dylanaraps** [comment]
Anytime. :)
