### ISSUE TITLE
Wrong OS in 2.0

### ISSUE THREAD

**Issue by rodrigograca31** [dylanaraps/neofetch#506]
## Description
2 days ago I updated my `neofetch` from 1.9.1 to 2.0 and since then it has been giving the wrong output...

![screenshot-window-2016-12-05-161256](https://cloud.githubusercontent.com/assets/1134310/20892341/b952f2c6-bb05-11e6-8bc6-58ca1ff4b874.png)

I'm on Linux Mint, as you can see `screenfetch` shows the correct info `neofetch` doesn't.....

#### Neofetch version
2.0

## Verbose log

```
[!] Config: Sourced default config. (/usr/share/neofetch/config)
[!] Config: Sourced user config.    (/home/unknown/.config/neofetch/config)
[!] Config: $osx_buildversion is deprecated, use $distro_shorthand instead.
[!] Config: $osx_codename is deprecated, use $distro_shorthand instead.
[!] Config: $cpu_cores='on' is deprecated, use $cpu_cores='logical|physical|off' instead.
[!] Config: $image is deprecated, use $image_source instead.
[!] Config: $progress_border is deprecated, use $bar_border instead.
[!] Config: $progress_length is deprecated, use $bar_length instead.
[!] Config: $progress_color_elapsed is deprecated, use $bar_color_elapsed instead.
[!] Config: $progress_color_total is deprecated, use $bar_color_total instead.
[!] Image: w3m-img wasn't found on your system, falling back to ascii mode.
```

**Comment by dylanaraps** [comment]
This has already been fixed in 2.0.1. 2.0.1 will be released once #478 is fixed.

**Comment by rodrigograca31** [comment]
Doesn't seem to be th same issue... If you say so...

**Comment by dylanaraps** [comment]
From the changelog:

> Fixed bug that caused Linux Mint systems to be identified as Ubuntu.

Was this not your issue?

**Comment by rodrigograca31** [comment]
Oh... Sorry. I thought you said my issue was the same as #478.... I got confused...

**Comment by dylanaraps** [comment]
All good :)
