### ISSUE TITLE
Incorrect package number

### ISSUE THREAD

**Issue by Limdel** [dylanaraps/neofetch#508]
after today's update (probably) neofetch is showing one less package then it should.
http://hastebin.com/dimesujoyu.coffeescript

**Comment by dylanaraps** [comment]
I can reproduce this.

**Comment by dylanaraps** [comment]
I've reverted the commit that caused this. I don't know if this affects all package managers so I might have to release another version of Neofetch.

**Comment by konimex** [comment]
For some reason it only affects system with `pacman`, I can reproduce this on my laptop, but not on my desktop (`emerge`).
