### ISSUE TITLE
Disable GPU Brand not working

### ISSUE THREAD

**Issue by Brottweiler** [dylanaraps/neofetch#509]
## Description

I expected that `NVIDIA` would be removed if I switched that setting to `off`, but it wasn't.

#### Neofetch version

`2.0.1`

## Screenshot

```sh
gpu_brand="on"
GPU: NVIDIA GeForce GTX 750 Ti
```

```sh
gpu_brand="off"
GPU: NVIDIA GeForce GTX 750 Ti
```

## Verbose log

[gist/07bb652a6366e6acff98daeb828be886](https://gist.github.com/07bb652a6366e6acff98daeb828be886)

**Comment by dylanaraps** [comment]
I can reproduce this, working on a fix now.

**Comment by dylanaraps** [comment]
Fixed.

It looks like I'm going to have to do another minor release tomorrow.
