### ISSUE TITLE
Linux Mint Font and Icons not detected correctly

### ISSUE THREAD

**Issue by hellscyth142** [dylanaraps/neofetch#510]
## Description

Linux mint 18 Sarah, the font is being detected as size 9 (default size) when I have it set to 12. It also detects my icon theme as Mint-X (also the default) when I have it set to ultra-flat-orange. 

Only fill in the fields below if relevant. If you're
suggesting a new feature then just a description will suffice.

#### Neofetch version

latest 2.0.1 ubuntu ppa

## Screenshot

Icons: Mint-X 
Font: Noto Sans 9 

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

http://pastebin.com/RqzMLvzb

**Comment by dylanaraps** [comment]
Thanks for opening this bug report.

Does Screenfetch display the correct info?

**Comment by hellscyth142** [comment]
No, screnfetch detects the font and icon theme correctly.

**Comment by dylanaraps** [comment]
I just pushed a commit to master that should fix the issue. 

Can you try the latest master?

**Comment by hellscyth142** [comment]
My current version is from the ubuntu ppa. Give me a minute to get the latest one working.

**Comment by hellscyth142** [comment]
Update, yeah the fixed worked. Thanks for the quick repair. You can safely close this bug report it looks like.

**Comment by dylanaraps** [comment]
Thanks for testing! :)
