### ISSUE TITLE
Incorrect logo on Mac w/Linux

### ISSUE THREAD

**Issue by SarissahSojourner** [dylanaraps/neofetch#515]
## Description

Incorrect logo when running Trisquel (possibly others?) on Mac hardware.

#### Neofetch version

2.0.2

## Screenshot

![screenshot from 2016-12-08 22 50 10](https://cloud.githubusercontent.com/assets/24469189/21038142/e85e7884-bd98-11e6-9913-967fe04e33ef.png)

## Verbose log

[http://pastebin.com/Fab3h64A](http://pastebin.com/Fab3h64A)

**Comment by dylanaraps** [comment]
Fixed, thanks.
