### ISSUE TITLE
Neofetch doesn't detect iTerm2, it uses w3m-img

### ISSUE THREAD

**Issue by coffeecore** [dylanaraps/neofetch#517]
## Description

I try to use Neofetch on Mac OS X El Capitan, but, it looks trying to use w3m-img but I use iTerm2, so no need.

#### Neofetch version

2.0.2 from Homebrew

## Verbose log

https://gist.github.com/coffeecore/cc88cc0521d70fbf22b209b8bc8840cf

**Comment by konimex** [comment]
Hello, this problem was addressed in #513 and fixed in commit 926dea972b82d1b81e5501e63c8d4395ee274b84.

**Comment by coffeecore** [comment]
Must I wait that neofetch on Brew would be patched ?

I searched for this issue, but didn't found :/

**Comment by konimex** [comment]
I think we can update the homebrew repo with a patch for this problem. pinging @iandrewt

**Comment by coffeecore** [comment]
Finally, I cloned this repo, and it works well.

I prefered by Brew, but not worked.
Thanks
