### ISSUE TITLE
Packaging Fetch for other Distros

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#52]
I'd love to see fetch packaged for other distros and operating systems.

Fetch is currently packaged for these distros:

| Distro               | Type   | Maintainer     | URL |
| ------------------- | ------- | ----------------- | ------ |
| Arch Linux        | aur     | @dylanaraps | [neofetch](https://aur.archlinux.org/packages/neofetch/), [neofetch-git](https://aur.archlinux.org/packages/neofetch-git/) |
| Gentoo/Funtoo | ebuild | @z1lt0id        | 
| Crux                 |  port    | @ix                |
| Debian/Ubuntu | repo     | @dawidd6     |
| Fedora             | repo     | @konimex     |
| RHEL/CentOS  | repo     | @konimex     | 
| Void Linux        | repo     | @konimex     |
| Mac OS X         | homebrew |  @iandrewt |

I don't have any experience in creating packages for other distros so any help
is appreciated.

**Comment by z1lt0id** [comment]
I'll install some docker instances and see what I can come up with :)

On 8 February 2016 12:06:03 pm AEDT, Dylan Araps <notifications@github.com> wrote:
>I'd love to see fetch packaged for other distros and operating systems
>
>Fetch is currently packaged for:
>
>- [X] Arch Linux (aur)
>- [X] Gentoo/Funtoo (ebuild)
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanaraps/fetch/issues/52

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dylanaraps** [comment]
Sounds good!  :+1:

**Comment by dylanaraps** [comment]
I'm working on creating a Fedora rpm, I'm just waiting for Fedora to finish downloading so I can run it in a vm.

**Comment by z1lt0id** [comment]
I'd recommend the docker route over vm. Much faster and less hassle

On 8 February 2016 1:14:18 pm AEDT, Dylan Araps <notifications@github.com> wrote:
>I'm working on creating a Fedora rpm, I'm just waiting for Fedora to
>finish downloading so I can run it in a vm.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanaraps/fetch/issues/52#issuecomment-181161606

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dylanaraps** [comment]
I haven't played around with docker before, I'll take a look.

**Comment by tudurom** [comment]
Why not use [The OpenSUSE Build Service](https://build.opensuse.org/)?

**Comment by dylanaraps** [comment]
That looks neat!

**Comment by tudurom** [comment]
I played around with it and it seems the most easy way to package fetch for a couple of distros is feeding a rpm to the OBS. Make a RPM and we will see.

**Comment by dylanaraps** [comment]
I'm also messing around with it and can't seem to get it working. I'll try adding an rpm file as the source to see if that works.

**Comment by tudurom** [comment]
Does it work?

**Comment by dylanaraps** [comment]
I spent hours yesterday trying to get Fedora to build an rpm and eventually gave up. 

If anyone else wants to have a go, be my guest.

**Comment by dylanaraps** [comment]
You can now install fetch through homebrew with this command:

```sh
brew install dylanaraps/tools/fetch
```

I haven't tested the formula, it should work in theory but I don't have any
OS X devices to test it on. Once someone has tested this and confimed 
that it works I'll add this to the readme.

The formula doesn't handle dependencies yet either, I'm working on this
as we speak.

**Comment by ix** [comment]
i packaged it for crux, but it currently fetches from git rather than from releases (as 1.3 doesn't have a release tag yet).

**Comment by tudurom** [comment]
I think both the ebuild and the PKGBUILD are fetching from git so that's
not a problem.

**Comment by ix** [comment]
okay then!

**Comment by dylanaraps** [comment]
@ix, are you able to write up some install instructions?

I want to add them to the readme. :)

**Comment by dylanaraps** [comment]
Thanks @ix!

**Comment by tudurom** [comment]
There are threads for updates on the ebuild and the CRUX port. Shouldn't the news be posted here?

**Comment by ix** [comment]
this is the issue for packages for new distros

other packages for existing distros should be kept in their own threads

**Comment by tudurom** [comment]
Then let's make a thread for already made packages.

**Comment by dawidd6** [comment]
I can make a .deb package

**Comment by danielwaltz** [comment]
I attempted to install fetch using the brew formula and it failed. Here is the error:

`Error: /usr/local/Library/Taps/dylanaraps/homebrew-tools/fetch.rb:1: class/module name must be CONSTANT`
`class fetch < Formula`

It's so easy to build that I don't see this as important, I just wanted to let you know.

**Comment by dylanaraps** [comment]
@dawidd6 :+1:

@danielwaltz, Thanks for testing the formula, I think I'll wait for someone else to create one.

**Comment by dawidd6** [comment]
So here it is, a .deb package (must be in zip, because github doesn't like .deb):
[fetch.zip](https://github.com/dylanaraps/fetch/files/149304/fetch.zip)

If you find this package in the state you don't like it, please let me know

**Comment by dylanaraps** [comment]
Nice!

How do we go about getting this into Debian and Ubuntu's repos?

**Comment by tudurom** [comment]
Let's begin with a ppa.

**Comment by dylanaraps** [comment]
Oh yeah, forgot all about ppas. I'll look into creating one!

**Comment by dylanaraps** [comment]
I've decided that I'm only going to maintain the aur package, if you want 
neofetch packaged for your distro then you or someone else will need to 
create a package, ppa or whatever and maintain it.

I'll gladly accept PRs with install instructions for X distro as I've done for
Gentoo/Funtoo and Crux.

**Comment by dylanaraps** [comment]
I'd also prefer it if every package used the same issue for updates instead
of having multiple seperate issues for them. 

See **https://github.com/dylanaraps/neofetch/issues/115**.

**Comment by konimex** [comment]
I'm going to try to make an rpm for Fedora, I'll report back here if I am succeeded.

**Comment by konimex** [comment]
The packaging has been successful. Tested on Fedora 23 but it should work in Fedora 22, 24 and Rawhide.

**Comment by tudurom** [comment]
If we have a RPM, we can use the OpenSUSE build service to package fetch
for many more distros!

**Comment by dylanaraps** [comment]
I don't want to maintain anymore packages but for anyone out there who wants to take a crack at setting up the build service, be my guest. :)

**Comment by konimex** [comment]
On 03/11/2016 03:17 PM, Tudor Roman wrote:
> If we have a RPM, we can use the OpenSUSE build service to package fetch
> for many more distros!

Hmm, I think the advantage of using OBS will be limited
to openSUSE, since we've already covered Debian, Ubuntu,
Arch, and Fedora. What does OBS cover, besides the 4 I
mentioned earlier?

**Comment by konimex** [comment]
We're now live on Void Linux's official repository. I'll maintain the package build template. Installation instructions coming in later.

**Comment by dylanaraps** [comment]
Post new package news in #115
