### ISSUE TITLE
--image not working

### ISSUE THREAD

**Issue by niichtsShaiaz** [dylanaraps/neofetch#543]
/usr/bin/neofetch: line 2187: 6: syntax error: operand expected (error token is "6")

#### Neofetch version
2.0.1

## Verbose log
http://pastebin.com/ZYM2dWU2

**Comment by dylanaraps** [comment]
I can see any errors in the log file.

How are you launch neofetch? Just `neofetch --image`?

**Comment by niichtsShaiaz** [comment]
Yes

**Comment by dylanaraps** [comment]
`--image` requires an argument.

Can you upload a log file of these commands: `neofetch --image wallpaper` and `neofetch --image /path/to/img`?

**Comment by niichtsShaiaz** [comment]
http://pastebin.com/bRtS6gey

**Comment by dylanaraps** [comment]
Fixed.

Thanks!
