### ISSUE TITLE
Termite with w3m-img and imagemagick still won't keep image [VIDEO]

### ISSUE THREAD

**Issue by kekpons** [dylanaraps/neofetch#553]
I can't seem to get this to work in terminite, please help, url to video and pastebin, also rate my desktop?
[http://pastebin.com/bsf1AMSN](url)
[https://vid.me/neQ9](url)

**Comment by dylanaraps** [comment]
Hi,

- Does this issue occur in other terminal emulators?
- What are those aur packages for?
    - Neofetch works just fine with vanilla termite.
    - Have you tried Neofetch without those aur packages?
- What happens if you make the terminal window a larger size?
    - (Large enough so it doesn't scroll the output.)

**Comment by kekpons** [comment]
The only terminal emulator it works in is 'terminology' I used it in as my default for awhile but its not my preferred terminal.

**Comment by dylanaraps** [comment]
Terminology doesn't use `w3m-img`.

**Comment by dylanaraps** [comment]
If you want me to help you then you need to provide me with more information. I can't help you if I can't find out what's causing this or how to reproduce it.

**Comment by kekpons** [comment]
Just removed termite and reinstalled same thing. I want my terminal to be dank just please help.

**Comment by dylanaraps** [comment]
@kekpons made a comment and deleted it:

> Just removed termite and reinstalled same thing. I want my terminal to be dank just please help.

At this point I think you're a troll so I'm closing this issue.
