### ISSUE TITLE
Output of the wrong GPU , maybe should output both if there is more than one.

### ISSUE THREAD

**Issue by Videonauth** [dylanaraps/neofetch#568]
## Description
I just found your repository and ought to give it a spin on my Ubuntu machine. Only issue i found is (Im having two Nvidia cards of one sits in a PCI slot) that it only displays one of them and its actually not the main one sitting in the PCIe slot

#### Neofetch version
2.0.2

## Screenshot
![selection_410](https://cloud.githubusercontent.com/assets/9640109/21472259/b3cbce4c-cad0-11e6-850d-10846e538ab9.png)

Like stated before I have a GTX 750 Ti sitting in the PCIe slot and the GT 610 is sitting actually in a PCI slot, it would be better if it would output both cards if there are multiple

**Comment by dylanaraps** [comment]
Can you try out the latest master? 

This feature was actually added a few days ago and will be `on` by default in newer versions. There's also a new option called `gpu_type` which allows you to show `all` (default), `dedicated` or `integrated` GPUs.

Source: https://github.com/dylanaraps/neofetch/pull/554

**Comment by Videonauth** [comment]
When im at home tomorrow Ill will build it here and give it a try. For now I just installed it from the repo given in the installation instructions.

**Comment by Videonauth** [comment]
Works as intended on the master branch.
![selection_411](https://cloud.githubusercontent.com/assets/9640109/21473576/1d364d90-cb11-11e6-9336-d4eddcd75b59.png)

**Comment by dylanaraps** [comment]
Awesome!
