### ISSUE TITLE
Neofetch Always Shows Battery as Charging

### ISSUE THREAD

**Issue by eccentricayman** [dylanaraps/neofetch#570]
## Description

Neofetch shows the battery as charging even when it is not.

#### Neofetch version
2.02

## Screenshot
<img src="http://i.imgur.com/0FDl6iV.png" />

## Verbose log

[Link](http://pastebin.com/7bp89DpH)

**Comment by iandrewt** [comment]
Did you install Neofetch with Homebrew? This has been patched in the homebrew repositories, but is not in the official 2.0.2 release.

If you're not using Homebrew, please use the latest version in the master branch or apple [this patch](https://github.com/dylanaraps/neofetch/commit/926dea972b82d1b81e5501e63c8d4395ee274b84.patch) to `neofetch`
