### ISSUE TITLE
Wallpaper detection fails on international characters on Mint, possibly others

### ISSUE THREAD

**Issue by jherazob** [dylanaraps/neofetch#573]
## Description

I run latest stable Mint (18, release based on Ubuntu 16.04). 
My current wallpaper is located in the directory "~/Imágenes/Walls/". So, when neofetch tries to get the current wallpaper it gets something on the lines of "file:///home/username/Im%C3%A1genes/Walls/somewallpaperfile.jpg". 
This later fails because no such file exists (verbose mode gets to "Image: '/home/username/Im%C3%A1genes/Walls/somewallpaperfile.jpg' doesn't exist, falling back to ascii mode"). 
This of course is due to gsettings returning url-encoded filenames, which transforms any international character on the path into it's encoded version, not the same one as the actual file path.

#### Neofetch version
2.0.2-1ubuntu1

## Potential solution
[This Gist i found on Google shows a native Bash solution to URL encoding and decoding of strings](https://gist.github.com/cdown/1163649), a few seconds of dabbling make it seem to me like it could work, although you may want to test it more. After that, any filename or path returned by gsettings should get a run through the url decoder.

**Comment by dylanaraps** [comment]
Thanks for opening this bug report and thanks for the link!

I just opened a PR #573, can you test it and confirm that the fix works for you?

**Comment by dylanaraps** [comment]
Ping @jherazob

**Comment by jherazob** [comment]
Sorry, with the end of year things haven't had a chance to test it, i'll do it on monday, sorry

**Comment by dylanaraps** [comment]
I merged this anyway, I did some testing and it works fine.
