### ISSUE TITLE
Custom image not showing up in Termite.

### ISSUE THREAD

**Issue by iyyel** [dylanaraps/neofetch#577]
Hi! I'm having problems trying to display a custom image using the image="wallpaper" option, which is set in my config.

The image does not show up in Termite at all, not blinking, no image at all. This is with neofetch 2.0.2. It works fine in rxvt-unicode.

Screenshot:
![2016-12-28-185443_2560x1440_scrot](https://cloud.githubusercontent.com/assets/9578704/21528064/0fd87558-cd30-11e6-91c4-54b721e6c3d5.png)

Log:
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/676220/neofetchlog.txt)

EDIT 1: Updated with right log.txt.

EDIT 2: I can see that the thumbnails are correctly generated in ~/.cache/thumbnails/neofetch/pic.jpg
Previewing using feh works.

**Comment by dylanaraps** [comment]
The log file tells me that Neofetch is working correctly.

- Do you have a compositor running?
    - Do images work if you turn it off?
- Do images work if you run Termite **without** its config file?
 
I need to be able to reproduce the issue to fix it and Termite + w3m-img work fine on my system. :P

**Comment by iyyel** [comment]
That's interesting.

1. Do you have a compositor running?
    Yes, Compton.
    1.1 Do images work if you turn it off?
     Exact same result as before.
2. Do images work if you run Termite without its config file?
     Exact same result as before.

Yeah, of course, I understand. It's really weird.

Here is my neofetch config, if that would be for any help: 
[neofetchconfig.txt](https://github.com/dylanaraps/neofetch/files/676937/neofetchconfig.txt)

**Comment by dylanaraps** [comment]
> The image I am using is a 4K image. Would that have any effect?

Nope.

Does this command work? 
 - `neofetch --config off --image wallpaper` or `neofetch --config off --image /path/to/img.jpg`

**Comment by dylanaraps** [comment]
One more thing: Do images work in `ranger` or `w3m`?

**Comment by dylanaraps** [comment]
Ping @iyyel

**Comment by iyyel** [comment]
I apologize for being absent. School just started up again, so I have had no time unfortunately. I'll edit this within an hour or so with the necessary information.

**Comment by dylanaraps** [comment]
All good!

> Does not work in ranger or w3m. I suppose that means its not neofetch specific then.

Yup, that confirms that it's an issue with your setup and w3m-img. 

There's a patched termite in the aur that includes a w3m-img fix. I haven't tried it since default termite works on my system but it's worth a shot.

https://aur.archlinux.org/packages/termite-ranger-fix-git/

**Comment by Alkeryn** [comment]
The issue only happen when using termite + bspwm it isn't a neofetch issue but a w3m + bspwm issue
