### ISSUE TITLE
Running ". neofetch" command adds a penguin to image each successive time.

### ISSUE THREAD

**Issue by pkgodara** [dylanaraps/neofetch#578]
I ran command ". neofetch" from terminal in my home directory ~.It adds an penguin each successive time I run it on same terminal(If i change terminal it starts from begining). I am using ubuntu 16.04.1 LTS. But "neofetch" shows correct output each time. 

output1.txt : for first terminal
output2.txt : for second terminal

[output1.txt](https://github.com/dylanaraps/neofetch/files/678466/output1.txt)
[output2.txt](https://github.com/dylanaraps/neofetch/files/678467/output2.txt)

neofetchlog : http://pastebin.com/9Wpz5SCK

**Comment by dylanaraps** [comment]
Sorry, I'm a little confused, can I see a screenshot?

**Comment by konimex** [comment]
It seems I can reproduce this, however there are certain conditions.

You need to run `bash` first.

[This is when I tried to run `. neofetch` in my default shell.](https://asciinema.org/a/08u2txogqdummmaulq55ear3f)

[This is when I tried to run `. neofetch` in bash.](https://asciinema.org/a/6rd7znuaqrasgtnncz6sn0nt1)

**Comment by pkgodara** [comment]
Yes, I am using it in Bash as shown by @konimex .
Do you still have any confusion, I can add screenshot, @dylanaraps

**Comment by dylanaraps** [comment]
I still can't reproduce this. 

What I don't understand is why you're trying to launch neofetch like this.

**Comment by pkgodara** [comment]
I also need a shell & linux expert here. :) I don't know why I remembered running shell scripts using this way(bad luck),I was just testing it and ran . neofetch in place of ./neofetch (didn't used till a long time, forgot actual command), It looked like working , so reran after some time and found that.
Now coming again , I googled it,
see http://askubuntu.com/questions/38661/how-do-i-run-sh-files .
See third comment to first answer.
"Actually, you can use . /path/to/yourscript.sh if the script have to set up some environment variables".

**Comment by pkgodara** [comment]
See this : I ran .vim
pk@PK:~$ . vim
bash: .: /usr/bin/vim: cannot execute binary file

**Comment by konimex** [comment]
Well, you *aren't* supposed to run vim that way because vim is not a shell script.

Also, using `. /path/to/script` apparently runs the script *and* overrides the environment variable, as shown in my 2nd asciinema.

As Dylan said earlier, you aren't supposed to run `neofetch`, (or any programs, really) that way.

**Comment by pkgodara** [comment]
Ok, Thanks, I ran . vim just to check from where it is trying to execute this.
Anyways, thanks for the info.
