### ISSUE TITLE
KDE/Plasma 5 WM Theme detection fails

### ISSUE THREAD

**Issue by mstraube** [dylanaraps/neofetch#586]
On my Arch system WM Theme detection fails for KDE/Plasma 5 and `~/.kde4/share/config/kdeglobals` is used instead of `~/.config/kdeglobals`. I guess the `.kde4` folder exists because some older applications I've installed created it, or for backwards compatibility?

 [This](https://github.com/mstraube/neofetch/commit/e90cf76440f6b2c778012ac46597bb3ca80f9638) might be a solution.

Some notes about the changes:
-  KDE / Plasme 5 default config dir seems to be just `~/.config` not `~/<kde*>/share/config`
- `kf5-config` has no `--localprefix` option so I changed the others to `--path config`. 
- `$KDE_CONFIG_DIR` is empty on my system. I thought about to set it to `$KDE_CONFIG_DIR/share/config`, but that would lead to a wrong path if it's value is `~/.confg`. I don't know if that could happen on a Plasma 5 system, so I commented it.
- I assumed kwinrc has only one ```library=org.kde.<theme>``` line. The section of my kwinrc looks like this (library=org.kde.breeze is the last line of the file). 
```
[org.kde.kdecoration2]
BorderSize=Normal
ButtonsOnLeft=MS
ButtonsOnRight=HIAX
CloseOnDoubleClickOnMenu=false
library=org.kde.breeze
```

Edit:
Just noticed that line [688](https://github.com/mstraube/neofetch/commit/e90cf76440f6b2c778012ac46597bb3ca80f9638#diff-e863270127ca6116fd30e708cdc582fcR688) can be removed if the slash is stripped in the variable assignments `kde_config_dir="${kde_config_dir/$'/:'*}"`

After line [1353](https://github.com/mstraube/neofetch/commit/e90cf76440f6b2c778012ac46597bb3ca80f9638#diff-e863270127ca6116fd30e708cdc582fcL1353) it's used unstripped...

**Comment by mstraube** [comment]
For the Plastik theme kwinrc looks like this
```
[org.kde.kdecoration2]
BorderSize=Normal
ButtonsOnLeft=MS
ButtonsOnRight=HIAX
CloseOnDoubleClickOnMenu=false
library=org.kde.kwin.aurorae
theme=kwin4_decoration_qml_plastik
```
[Updated](https://github.com/mstraube/neofetch/commit/a7fa5a8df8c52de62e7cddd67db394d0c2f28988) the Kwin theme detection, maybe this needs some more elaboration...

**Comment by dylanaraps** [comment]
Can you open a pull request? :)

Thanks for taking a look at this.

**Comment by mstraube** [comment]
Sure, should I modify the assignments to `kde_config_dir="${kde_config_dir/$'/:'*}"` and remove line [688](https://github.com/mstraube/neofetch/commit/e90cf76440f6b2c778012ac46597bb3ca80f9638#diff-e863270127ca6116fd30e708cdc582fcR688) ? If so I'll do it tomorrow.

**Comment by dylanaraps** [comment]
Yeah, all good! :+1:
