### ISSUE TITLE
Image: [Windows] syntax error: operand expected (error  token is " 1080 " )

### ISSUE THREAD

**Issue by apathyrecharge** [dylanaraps/neofetch#601]
i was talking to you through PM on reddit, issue is [pictured here](https://i.imgur.com/VVqneKL.png), the image displays perfectly for a second and as neofetch finishes collecting the sysinfo it cuts out and displays an error.

i'm using neofetch version 2.1.0, urxvt, cygwin + xwin as an xserver

[here's a link to the log](http://pastebin.com/2JB1phHz)

**Comment by dylanaraps** [comment]
Can you try out the latest commit and let me know if the issue still occurs? Also tell me which line number the error occurs on as I can't find the line from your screenshot.

**Comment by apathyrecharge** [comment]
on the version i was using it occured on line 2762, with the latest commit the issue persists and the error is on line 3331

**Comment by dylanaraps** [comment]
Does this PR fix the issue?

https://github.com/dylanaraps/neofetch/pull/605

**Comment by apathyrecharge** [comment]
perhaps i misunderstand, but i added "height="${height//[[:space:]]}"" to line 2219 but the error still occurs. [here's an update log](http://pastebin.com/HEgrKGsV) if you need it

**Comment by dylanaraps** [comment]
I need to be able to reproduce the issue to fix it, I can't reproduce it right now. Does the issue also occur in neofetch 2.0.2?

**Comment by apathyrecharge** [comment]
i've tried it on 2.0.2 and the [issue persists still](http://pastebin.com/w7iMZFRJ). if you cant reproduce it then hopefully im the only one encountering the error, i can live without the image function i just thought it'd be nice to see.

**Comment by dylanaraps** [comment]
I just managed to reproduce this! 

The variable `$height` contains an escape sequence on Windows, either `\r` or another sequence and this is what's causing the syntax error.

By setting `$height` to this:

```sh
height=$'\n\r\n\r\n1080\n\r\n\r'
```

I get the same error you're getting, I can work on a fix now. :)

**Comment by dylanaraps** [comment]
Can you try out the latest master and let me know if the fix worked? :)

**Comment by apathyrecharge** [comment]
looks like that did the trick! great work man, and thanks a lot :D

**Comment by dylanaraps** [comment]
No problem! :)
