### ISSUE TITLE
Rewrite Neofetch to be a "Generic Information Tool". 

### ISSUE THREAD

**Issue by bobblestiltskin** [dylanaraps/neofetch#607]
While neofetch is a useful tool, I think that it may be missing the facility to become a versatile system information tool, which may be useful in e.g. a unix pipeline

On AIX, I can run ...

bash-4.4$ ./neofetch 
           `:+ssssossossss+-`              bob@bobaixgcc62 
        .oys///oyhddddhyo///sy+.           --------------- 
      /yo:+hNNNNNNNNNNNNNNNNh+:oy/         OS: AIX 6.1.0.0 00FA21314C00 
    :h/:yNNNNNNNNNNNNNNNNNNNNNNy-+h:       Model: IBM,8284-22A 
  `ys.yNNNNNNNNNNNNNNNNNNNNNNNNNNy.ys      Kernel: 1 
 `h+-mNNNNNNNNNNNNNNNNNNNNNNNNNNNNm-oh     Uptime: 32 days, 2 hours, 4 mins 
 h+-NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN.oy    Shell: ksh 
/d`mNNNNNNN/::mNNNd::m+:/dNNNo::dNNNd`m:   CPU: PowerPC_POWER8 ( 1) @ 3.4GHz 
h//NNNNNNN: . .NNNh  mNo  od. -dNNNNN:+y   Memory: 2913MB / 4096MB 
 .sNNNNNN+ -N/ -NNh  mNNd.   sNNNNNNNo-m 
N.sNNNNNs  +oo  /Nh  mNNs` ` /mNNNNNNo-m                           
 //NNNNh  ossss` +h  md- .hm/ `sNNNNN:+y 
:d`mNNN+/yNNNNNd//y//h//oNNNNy//sNNNd`m- 
 yo-NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNm.ss 
 `h+-mNNNNNNNNNNNNNNNNNNNNNNNNNNNNm-oy 
   sy.yNNNNNNNNNNNNNNNNNNNNNNNNNNs.yo 
    :h+-yNNNNNNNNNNNNNNNNNNNNNNs-oh- 
      :ys:/yNNNNNNNNNNNNNNNmy/:sy: 
        .+ys///osyhhhhys+///sy+. 
            -/osssossossso/- 

bash-4.4$ ./neofetch --ascii_distro none | perl -p -e 's/\x1b\[1m//g' | perl -p -e 's/\x1b\[0m:/|/g' | perl -p -e 's/\x1b\[0m//' | grep '|' | awk -F '|' '{print $1,"\t",$2}'
OS 	  AIX 6.1.0.0 00FA21314C00 
Model 	  IBM,8284-22A 
Kernel 	  1 
Uptime 	  32 days, 2 hours, 4 mins 
Shell 	  ksh 
CPU 	  PowerPC_POWER8 ( 1) @ 3.4GHz 
Memory 	  2915MB / 4096MB 
bash-4.4$ 

On Linux, similarly I see ...

bob@bobspc:~$ neofetch --ascii_distro none | perl -p -e 's/\x1b\[1m//g' | perl -p -e 's/\x1b\[0m:/|/g' | perl -p -e 's/\x1b\[0m//' | grep '|' | awk -F '|' '{print $1,"\t",$2}'
                        OS 	  Debian GNU/Linux unstable (sid) x86_64 
                        Model 	  Vostro 460 
                        Kernel 	  3.16.0-4-amd64 
                        Uptime 	  6 hours, 10 minutes 
                        Packages 	  4451 
                        Shell 	  fish 2.4.0 
                        Resolution 	  1920x1080 
                        WM 	  Enlightenment 
                        Theme 	  Adwaita [GTK3] 
                        Icons 	  Adwaita [GTK3] 
                        CPU 	  Intel i5-2500 (4) @ 3.7GHz 
                        GPU 	  AMD Radeon HD 6450/7450/8450 
                        Memory 	  1811MB / 7986MB 
bob@bobspc:~$ 

So filtering the output through perl, grep and awk will give me tab-delimited output of the system information, so I can live with what is currently available.

I do wonder though, how much work it would be to restructure the code so that it might support, say a --pipeline switch (maybe with a tab/xml flag) so that the neofetch could be used in more places than originally envisaged. In general, I think that separating the code between work, and display of the results of that work, is useful. (If only so that a different display model can be swapped easily)?

**Comment by dylanaraps** [comment]
Neofetch used to have a mode called `stdout` which would just print the function output in plain text. It was removed about 6 months ago but re-implementing won't take long this time due to the changes we've made to Neofetch in this version.

Exporting to `xml` or other formats is a great idea. This shouldn't be too hard to implement either. 

Example of the old mode:

```sh
# Command
neofetch --stdout memory

# Output
450MB / 4096MB

# Command
neofetch --stdout memory cpu

# Output
450MB / 4096MB
AMD FX-6300 (6) @ 4.2GHZ

# Optional output with --stdout_separator '|'
(Separator between info can be set)
450MB / 4096MB | AMD FX-6300 (6) @ 4.2GHZ

# Optional output with --stdout_subtitle on
# (There was also an option to display subtitles with the output)
Memory: 450MB / 4096MB
CPU: AMD FX-6300 (6) @ 4.2GHZ
```

**Comment by dylanaraps** [comment]
On second thought, we're going to have to rewrite a large chunk of the script. Here's how the information printing currently works:

```sh
# Most functions don't print anything and just set a variable.
get_cpu --> $cpu
    CPU: AMD FX-6300 (6) @ 4.2GHz

# Some functions (Disk, Battery, etc) print directly if they're displaying 
# multi-line information.
get_disk -->
    Disk (/): 42G / 400G (10%)
    Disk (/media/Local): 42G / 400G (10%)
```

We should either:

1) Make Neofetch print directly for all functions.
2) Make `info()` / `prin()` support printing multi-line output.

**Comment by bobblestiltskin** [comment]
./neofetch --ascii_distro none | perl -p -e 's/\x1b\[1m//g' | perl -p -e 's/\x1b\[0m:/|/g' | perl -p -e 's/\x1b\[0m//g' | perl -p -e 's/\x1b\[24C//g' | grep '|' | awk -F '|' '{print $1,"\t",$2}' - this gived more consistent output on Linux and AIX - I will leave the consideration about restructuring the code with you

**Comment by DmitryHetman** [comment]
@bobblestiltskin If you need custom solution it's better to write from scratch.
![170419rmrqonvjyspt](https://cloud.githubusercontent.com/assets/18743742/25191341/ca0f9442-251e-11e7-97b1-5aa048040b0e.png)

**Comment by dylanaraps** [comment]
Added `--json` to print the output in a json format.

Closing this as it's likely we won't go further than this.

**Comment by bobblestiltskin** [comment]
Thank you for your work on this, and that my request is useful to others, too.
