### ISSUE TITLE
Terminal font detection for termite takes it from wrong place

### ISSUE THREAD

**Issue by Brottweiler** [dylanaraps/neofetch#608]
## Description

Using [Termite](https://github.com/thestinger/termite), the script will fetch the font name from the `font` that is at the [`END`](https://github.com/dylanaraps/neofetch/blob/2d7114e03513ba7876934ed4597fabe0fe3461f8/neofetch#L1606)(?) of the file. 

A minimal version of the [default](https://github.com/thestinger/termite/blob/master/config) config looks like this.

```cfg
[options]
font = Monospace 9
[hints]
#font = Monospace 12
```

The first `font` option specifies the font used in the terminal, this is what neofetch *should* output. In this case, neofetch *will* output `Monospace 9`. But if we uncomment the `[hints]` `font` option, neofetch will output `Monospace 12` instead, which is **wrong**.

Neofetch should always output the `font` option that is under `[options]`, which should be at the beginning of the file. My bash/awk knowledge is limited, but as I said above, in the script `END` is mentioned. I assume this looks for `font` at the END of the file, not beginning.

#### Neofetch version

`2.0.2`

**Comment by mstraube** [comment]
If it's guaranteed that the`[options]` sections is always above `[hints]` then this should do it

```bash
term_font="$(awk -F '= ' '/^font/ {a=$2; exit} END{print a}' "${XDG_CONFIG_HOME}/termite/config")"
```

I also noticed on a fresh installed `termite` there is no config file in `$HOME/.config` (at least at Arch).
But there is a global config file `/etc/xdg/termite/config`. Maybe that should also be checked, if the first command gives no result.

@Brottweiler the END has nothing to with the search location in the file. ;)

**Comment by Brottweiler** [comment]
It should be that order unless someone purposely changed it in their personal config.

>the `END` has nothing to do with the search location in the file

Thanks for the info!
