### ISSUE TITLE
CPU bad information on Windows Subsys

### ISSUE THREAD

**Issue by otlet** [dylanaraps/neofetch#610]
## Description
neofetch don't show correctly CPU information. Now i have 0.0GHz 👍 

#### Neofetch version
2.0.2-1

## Screenshot
![image](https://cloud.githubusercontent.com/assets/1035900/21850493/1fb668f0-d80b-11e6-9185-6d296cd925ad.png)

## Verbose log
http://pastebin.com/xBCDtSsp

**Comment by konimex** [comment]
What is the contents of `/sys/devices/system/cpu/cpu0/cpufreq`?

**Comment by otlet** [comment]
![image](https://cloud.githubusercontent.com/assets/1035900/21869384/aab2d726-d857-11e6-95ba-2362dca8c67a.png)

**Comment by dylanaraps** [comment]
Thanks, I've added another fallback to `cpuinfo_max_freq`. Neofetch will now also check that file.

**Comment by otlet** [comment]
GJ :) Thanks 👍
