### ISSUE TITLE
Resolution: [Windows] Multiple monitors not detected

### ISSUE THREAD

**Issue by BlindMute** [dylanaraps/neofetch#611]
Version 2.1.0

I am running two monitors in extended mode, the main is 1920x1080 and the side is 1680x1050. Neofetch displays "Resolution: 1680 x 1050" despite the larger monitor being the 'primary' and the shell being on that screen.
This is on W7 Ultimate x64

**Comment by dylanaraps** [comment]
What's are the outputs of these commands?:

```sh
wmic path Win32_VideoController get CurrentHorizontalResolution
wmic path Win32_VideoController get CurrentVerticalResolution
```

**Comment by BlindMute** [comment]
It outputs 1680 and 1050 respectively. I understand that neofetch uses wmic for its Windows resolution, but is there perhaps a better way to do so? I don't believe wmic supports multiple monitors.

**Comment by dylanaraps** [comment]
I don't think there's a better (or mulit-monitor) way of getting the resolution on Windows. This is sadly what we're stuck with.

**Comment by dylanaraps** [comment]
I'm closing this since there's no clear way of fixing it. I've also added it to the TODO list so I won't forget about it. 

#613
