### ISSUE TITLE
`--color_blocks off` adds an extra new line in the output

### ISSUE THREAD

**Issue by BojanStipic** [dylanaraps/neofetch#628]
## Description

passing `--color_blocks off` as an argument, color blocks get removed, but an extra new line is added at the end of output, making neofetch not fit completely in my terminal.

It worked fine in 2.0.2 version, and I got this issue after an AUR update today.

#### Neofetch version
3.0

## Screenshot

With `--color_blocks off`. There are 4 new lines as highlighted. Notice the top row with my username missing.
![image](https://cloud.githubusercontent.com/assets/13490088/22202746/d62c99d0-e169-11e6-8ab5-a5a92919995d.png)

Without `--color_blocks off`. There are 3 new lines as highlighted.
![image](https://cloud.githubusercontent.com/assets/13490088/22202809/2b0e1fc8-e16a-11e6-89b9-aedc357ae2f5.png)

## Verbose log

[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/723480/neofetchlog.txt)

**Comment by dylanaraps** [comment]
Does the issue still occur if you run neofetch without a config file?

```sh
neofetch --config off --color_blocks off
```

**Comment by BojanStipic** [comment]
Yes, just tried it. But I have no config file anyway, just an alias in my `.bashrc`.
```bash
$ type neofetch
neofetch is aliased to `neofetch --colors 203 fg 203 203 203 fg --ascii_colors 203 --color_blocks off '
```

**Comment by dylanaraps** [comment]
Try out the latest master, the issue should be fixed now.

**Comment by lukelbd** [comment]
Weirdly, the extra newline is fixed only if `neofetch` is called **directly**. If I put the line `neofetch --color_blocks off` in my `.bashrc` two extra newlines are printed (total of four newlines with `--color_blocks off`, total of two newlines with `--color_blocks on`). Perhaps this issue should be re-opened.
