### ISSUE TITLE
Neofetch 3.0 shell command broken with /bin/zsh shell

### ISSUE THREAD

**Issue by iraquitan** [dylanaraps/neofetch#633]
## Description

The neofetch output seems to be broken on the shell command. I'm using Neofetch 3.0 installed through homebrew and using the same config file as in master. My current shell script is as folows:

```shell
$ echo $SHELL
/bin/zsh
```

#### Neofetch version
Neofetch 3.0

## Screenshot
The cropped output:
<img width="879" alt="screen shot 2017-01-24 at 08 19 34" src="https://cloud.githubusercontent.com/assets/3467229/22245293/01323e42-e20e-11e6-9f51-c7d7ce7732c4.png">

if I comment the shell command on config, the output is not cropped:
<img width="852" alt="screen shot 2017-01-24 at 08 22 21" src="https://cloud.githubusercontent.com/assets/3467229/22245379/5b91a954-e20e-11e6-891e-da67ef054f86.png">

## Verbose log
The verbose log is found here: http://pastebin.com/sifHL6EJ

## Config file
And the config file used here: http://pastebin.com/K2YF33jv

**Comment by dylanaraps** [comment]
Thanks for opening this. :)

- Does the issue still occur with `neofetch --shell_version off`?
- What's the output of this command?: `zsh --version`

**Comment by iraquitan** [comment]
With `neofetch --shell_version off` the issue is gone.
![screenshot 2017-01-24 10 02 35](https://cloud.githubusercontent.com/assets/3467229/22248218/514b6436-e21c-11e6-99af-47f249d3760e.png)

 *note: I'm now at work in a different machine, but I had the same issue as in my personal machine.

**Comment by dylanaraps** [comment]
What's the output of `zsh --version`? This is the only command that gets run in the shell function, which makes it the only possible cause of the issue.

**Comment by iraquitan** [comment]
zsh 5.3.1 (x86_64-apple-darwin15.6.0)

**Comment by dylanaraps** [comment]
Weird.

What about this?

- `"$SHELL" --version`

Also what version of bash do you have installed?

- `bash --version`

**Comment by iraquitan** [comment]
I have homebrew `zsh` installed but not used. Thats why `zsh --version` is different

```shell
$ "$SHELL" --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

```shell
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by dylanaraps** [comment]
The shell function *might* include something incompatible with `bash 3` and that's why it's suddenly exiting. I'll install `bash 3` and see if I can reproduce this.

**Comment by dylanaraps** [comment]
I can reproduce this with `bash 3`, working on a fix now. :+1:

**Comment by dylanaraps** [comment]
This was the offending line: `shell="${shell/ ${SHELL##*/}}"`, I'm not sure why this caused `bash` to crash. The issue should be fixed now, try out the latest master and let me know if it still occurs. :)

**Comment by dylanaraps** [comment]
Closing this, reopen it if you're still experiencing the issue. :)

**Comment by snjy5** [comment]
> Closing this, reopen it if you're still experiencing the issue. :)

I have got the same problem with $SHELL as zsh, it displays properly when  $SHELL is /bin/bash

**Comment by heapframe** [comment]
Im still experiencing this issue after a fresh reinstall of ubuntu 22.10
