### ISSUE TITLE
w3m is cutoff by output/scrot triggers before full output

### ISSUE THREAD

**Issue by Flat** [dylanaraps/neofetch#635]
## Description

When running neofetch using w3m as the backend and specifying the image parts of the image are cutoff. When running neofetch with the -s flag the screenshot is taken before the full output is printed and the image is displayed correctly.

#### Neofetch version
3.0
## Screenshot
running ```neofetch```
![2017-01-24-16 45 11](https://cloud.githubusercontent.com/assets/2048861/22268248/d1a0b70c-e254-11e6-81f3-0aadbb524f5a.png)

```neofetch -s```
![neofetch-2017-01-24-04-49-14-26749](https://cloud.githubusercontent.com/assets/2048861/22268363/498b86de-e255-11e6-941c-25986a197e22.png)

## Verbose log

https://gist.github.com/Flat/092a2ee0b808622505b59bfd3b67c2cb

Terminal is xfce4-terminal since neofetch can't seem to detect it.

**Comment by dylanaraps** [comment]
There's something wrong with your log file. Here's what it should look like: http://pastebin.com/raw/sifHL6EJ Can you send me a valid log file of both `neofetch` and `neofetch-s`?

I'll need some more info as well:

- Did these issues occur in other versions of neofetch?
- Do these issues occur with other terminal emulators? 
- Do these issues still occur if you disable your compositor?
- Do these issue still occur in ascii mode? `neofetch --ascii`.

**Comment by Flat** [comment]
Had to redirect err to sdout and ```| tee``` it to get a readable logfile. :thinking:. Anywho updated the gist with the fixed log as well as the log for the ```-s``` option. [Link again for your convience](https://gist.github.com/Flat/092a2ee0b808622505b59bfd3b67c2cb)

- I've never used any other version of neofetch.
- In gnome-terminal and urxvt the image does not show up at all.
- There is no way to disable the compositor in budgie-desktop (Seeing as it works without tmux I don't think it's a compositor issue. See below)
- ascii mode is a jumble of malformed text that seems to break my terminal

I should have also mentioned this was inside tmux. Outside of tmux regular neofetch seems to display the image correctly, however the ```-s``` flag still takes the screenshot too soon. Both inside and outside of tmux ```--ascii``` mode is still broken and looks like this: 
![2017-01-24-18 29 11](https://cloud.githubusercontent.com/assets/2048861/22271542/08b92d06-e263-11e6-953a-2e01d81c971b.png)

I've tried to add the log for ```--ascii``` to the gist, but it's 13MB so here's another link to that https://files.catbox.moe/fqhrhs.log

**Comment by dylanaraps** [comment]
Can you send me the output of `locale`?

**Comment by Flat** [comment]
```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by dylanaraps** [comment]
What's the output of `echo $TERM`?

**Comment by Flat** [comment]
```
echo $TERM
tmux
```
Outside tmux:
```
echo $TERM
xterm-256color
```

**Comment by dylanaraps** [comment]
Does `neofetch --ascii` work in other terminal emulators? 

Sorry for asking all of these questions, I need to be able to reproduce this (or at least find the cause) so I can fix it. :)

**Comment by Flat** [comment]
```neofetch --ascii``` does not work in other terminals.
It does work without an image_source set in the config. (For showing the distro ascii text. just making that clear) 

And no problem. Ask all the questions you need to. I know how bug hunting goes when you can't activate the same bug on your end. It's a pain. Thank you for working to try and fix it!

**Comment by dylanaraps** [comment]
Can you try out the `locale-remove` branch? I've removed all locale modification to see if this is the issue, in the 13MB log file you sent me the garbage starts getting printed right after Neofetch changes your locale.

Just run Neofetch in both `w3m` and `ascii modes with this branch and let me know if anything changes.

**Comment by Flat** [comment]
Using that branch the image doesn't display inside tmux at all. ASCII is still a jumbled mess both using tmux and sans.

**Comment by dylanaraps** [comment]
Does neofetch work in a TTY?

**Comment by Flat** [comment]
It does not. Same garbled text.

**Comment by dylanaraps** [comment]
Does Screenfetch work? Do you experience similar issues with any other programs?

**Comment by dylanaraps** [comment]
This seems like the same issue:

http://unix.stackexchange.com/questions/109650/some-garbage-characters-in-linux-terminal

**Comment by Flat** [comment]
neofetch *does* display fine without image_source set (with a default config everything works fine). As far as I know screenfetch doesn't support images on the terminal nor image to ascii. I believe the garbled text issue may be due to whatever backend neofetch uses on source_image to convert to ascii.

**Comment by dylanaraps** [comment]
Can you send me your config file?

**Comment by Flat** [comment]
Sure. Here it is. The only changes I've made from default are image_source and image_backend though.

[config](https://gist.github.com/Flat/2e14bdd263a8f1f90303070e9c39c323)

**Comment by dylanaraps** [comment]
I know what's causing the ascii issue. If `image_source` is an image file and you're in `ascii` mode then Neofetch will try and use the image file as ascii art. (This shouldn't happen)

I'll work on a fix for this issue and we'll see what issues remain afterwards.

**Comment by dylanaraps** [comment]
I've fixed the ascii issue, please try out the latest master.

**Comment by Flat** [comment]
ascii now works with image_source set. ```-s``` also works with full text.

w3m shows no image in tmux.

**Comment by dylanaraps** [comment]
So the only issue now is `w3m` not displaying images in `tmux`?

**Comment by Flat** [comment]
Correct.

**Comment by dylanaraps** [comment]
Does `ranger` or `w3m` display images properly inside `tmux`?

You can test out `w3m` by using this command: `w3m https://github.com/dylanaraps/neofetch`. Do the README images load?

You can test out `ranger` by setting `set preview_images` to `true` in `ranger`'s `rc.conf` file and navigating to an image.

**Comment by Flat** [comment]
Images work in ```w3m``` inside ```tmux```. After restarting ```tmux``` ```neofetch``` does display the image using ```w3m``` but it's still looks like the screenshot in the initial report. (Lines missing through it)

**Comment by dylanaraps** [comment]
Try out the latest master, the issue should be fixed now. :)

**Comment by Flat** [comment]
Yup! Looks perfect in ```tmux``` now. Thanks!

**Comment by dylanaraps** [comment]
Anytime :)
