### ISSUE TITLE
Disk label is yellow by default

### ISSUE THREAD

**Issue by chrishtanaka** [dylanaraps/neofetch#636]
## Description

By default, the label for `info disk` is yellow:
```
print_info() {
    ...
    info memory
    info disk
    ...
}
```

#### Neofetch version
3.0 on OSX 10.12.3

## Screenshot
![screen shot 2017-01-25 at 11 18 57 am](https://cloud.githubusercontent.com/assets/2514771/22303349/28b0eb8e-e2f0-11e6-9374-53d0d942b7cd.png)

## Verbose log
https://gist.github.com/anonymous/c2ef68eafb09e48c8aa3719844e7faa9

**Comment by dylanaraps** [comment]
Can you send me your config file? I can't reproduce this at all.

**Comment by konimex** [comment]
I'm curious, is this the expected output (since you deleted the subtitle)?

```
2294MB / 16384MB
58G / 279G
```

**Comment by dylanaraps** [comment]
I've fixed the issue. #641 

I won't merge this until @konimex's question is answered so we can figure out the expected output. The PR currently prints it like the comment above.

**Comment by chrishtanaka** [comment]
I agree with @konimex. Totally missed the label added.

**Comment by dylanaraps** [comment]
Will merge the fix now :+1:

**Comment by chrishtanaka** [comment]
@dylanaraps Not too sure what you would do in the case of multiple disks though...

**Comment by dylanaraps** [comment]
We can append the disk name to the end of the string:

```sh
58G / 279G (21%) [/]
58G / 279G (21%) [/mnt/Local Disk]
```

**Comment by chrishtanaka** [comment]
Actually, I'd prefer it at the beginning hierarchy-wise. Thoughts?

**Comment by dylanaraps** [comment]
Like this?

Also which brackets (if any)?

```sh
[/] 58G / 279G (21%)
[/mnt/Local Disk] 58G / 279G (21%) 

(/) 58G / 279G (21%)
(/mnt/Local Disk) 58G / 279G (21%) 

```

**Comment by chrishtanaka** [comment]
Yes. As far as formatting goes I would remove the brackets. Just like how the OS X`diskutil list` command does:
```
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         500.3 GB   disk0
   1:                        EFI EFI                     314.6 MB   disk0s1
   2:          Apple_CoreStorage Macintosh HD            300.3 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
   4:       Microsoft Basic Data BOOTCAMP                199.0 GB   disk0s4

/dev/disk1 (internal, virtual):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                            Macintosh HD           +300.0 GB   disk1
```

**Comment by dylanaraps** [comment]
Just to confirm, you'd prefer this?:

```sh
/: 58G / 279G (21%)
/mnt/Local Disk: 58G / 279G (21%) 
```

**Comment by dylanaraps** [comment]
Also what color would you expect the output to be?

This is what it currently looks like:

![2017-01-26-184521_210x74_scrot](https://cloud.githubusercontent.com/assets/6799467/22323554/ccc91946-e3f7-11e6-8985-7a0d3d4fa8de.png)

**Comment by chrishtanaka** [comment]
Yes, but that's just my opinion. It's think it's arbitrary and can be changed later if needed/wanted.

I would expect the color to be the color of the title if it's considered as part of the title:
```
Disk /: 58G / 279G (21%)
Disk /mnt/Local Disk: 58G / 279G (21%) 
```
Otherwise I'd expect it to be the same color of the value:
```
Disk:
    /: 58G / 279G (21%)
    /mnt/Local Disk: 58G / 279G (21%) 
```

**Comment by dylanaraps** [comment]
Done! 

Thanks for your input. :)
