### ISSUE TITLE
/usr/local/bin/neofetch: line 3263: cd: wall: No such file or directory

### ISSUE THREAD

**Issue by lazeran** [dylanaraps/neofetch#637]
## Description
Error Mesage:
/usr/local/bin/neofetch: line 3263: cd: wall: No such file or directory

#### Neofetch version
3.0
## Screenshot
[https://i.imgur.com/gq3Ioym.png](Screenshot)
## Verbose log
http://sprunge.us/aAEB

**Comment by IAmNotImportant** [comment]
This happened to me before, when I didn't specified path to config file.
`--config file` needed to be changed to `--config ~/.config/neofetch/file`

Check paths you have modified.

**Comment by dylanaraps** [comment]
Two things:

- Sprunge is down. Can you re-upload your log file?
- Can you also upload your config file?

**Comment by dylanaraps** [comment]
Does the issue still occur with a new config file?

**Comment by dylanaraps** [comment]
Figured out what the issue was.

Fixed.

**Comment by Sudharshaun** [comment]
What was the issue and solution. I'm facing the same issue.
