### ISSUE TITLE
USB neofetch

### ISSUE THREAD

**Issue by jensenbox** [dylanaraps/neofetch#640]
## Description

It would be awesome if you could provide a means to build a USB stick that once booted simply dumps to a text file (or post to a URL).

Would be great for system inventory tracking.

Thanks!

**Comment by dylanaraps** [comment]
This seems *really* out of scope for neofetch.

This could easily be done with an additional script that made use of `curl`. 

- You can store neofetch's output in a file by just appending `> file` to your neofetch command.
- You can use `curl` to upload the file to a file host.
