### ISSUE TITLE
Custom ascii defaulting to distro logo ascii

### ISSUE THREAD

**Issue by GillesJ** [dylanaraps/neofetch#643]
## Description
My custom ascii no longer works and defaults to the distro logo. Perhaps this is due to a change in the image backend with the new major version 3.0?

`neofetch --ascii /path/to/ascii` and `neofetch --backend ascii --source /etc/lt3asciineofetch` both produce this error.

Custom ascii (format as per wiki):
```
${c3}     ${c1}od${c3}   ${c2}'d;;d'lo'ol${c3}
${c3}   ${c1}. :c${c3}   ${c2}.c,,c.;c.:: .${c3}
${c3}  ${c1}cl,cl.${c3}  ${c2}'c;;l,cc'cc,l:${c3}
${c3}  ${c1}co,oo.${c3}          ${c2}.ll,oc${c3}
${c3}  ${c1}:l'cl${c3}  ${c2}.:,,:.;:.cc.l:${c3}
${c3}  ${c1};l.cc${c3}  ${c2}.l,,l.:c.c:.c;${c3}
${c3}  ${c1};l.cc${c3}  ${c2}.;'';.,;.c:.c;${c3}
${c3}  ${c1}cl,ll.${c3}          ${c2}.lc,lc${c3}
${c3}  ${c1}co,ll,ol,o::o,${c2}cl'll,lc${c3}
${c3}     ${c1}cl.lc'o;,o'${c2}:l.cc${c3}
${c3}     ${c1}:c.c:.c,,c.${c2}:c.c:${c3}
```

#### Neofetch version
neofetch 3.0

## Verbose log
<script src="https://gist.github.com/GillesJ/f6b03dc96ba3f06ffad88f4d56dbe29c.js"></script>

**Comment by dylanaraps** [comment]
I can reproduce this.

**Comment by dylanaraps** [comment]
Fixed, thanks for reporting this!
