### ISSUE TITLE
Underline not displaying

### ISSUE THREAD

**Issue by jp1995** [dylanaraps/neofetch#647]
## Description
Pretty straightforward. After updating to 3.0, I can't get underlines to display anymore. They still take up a line, but no actual characters are printed. In the screenshot below, I would expect an underline to be displayed right above OS info. I tried changing the colour, which didn't help.
I've also got
```
underline_enabled="on"
underline_char="-"
```

## Neofetch version
3.0

## Screenshot
https://i.imgur.com/6TUwN2F.png

## Config file
http://pastebin.com/4Qwz32PE

## Verbose log
http://pastebin.com/6VkWfJY2

**Comment by jp1995** [comment]
When I use the config file from https://github.com/dylanaraps/neofetch/wiki/Config-File then it does work. 
The only difference between config files regarding the underline is the colors option. In default config, it's colors=(distro), whereas in mine they are manually set.

**Comment by dylanaraps** [comment]
I can reproduce this, working on a fix.

(The issue is that lines using `prin` don't work with `underline`)

**Comment by dylanaraps** [comment]
Fixed!

**Comment by jp1995** [comment]
Awesome, thanks!
