### ISSUE TITLE
Image won´t show in Archlinux with Plasma/KDE

### ISSUE THREAD

**Issue by techMod** [dylanaraps/neofetch#650]
When I call neofetch, it will not show an image and falls back to ascii mode.
I start ist with the following options:

`neofetch -- image wallpaper path/to/wall` (wall lives in home)
`neofetch --config none /path/to/config` (config lives in home and has permissions of -rwxrwxrwx)
`neofetch --image /path to image`

Doesn´t work also with feh/nitrogen/gsettings installed (eventhough they don´t need to be installed - just tried it to double-check)

##Version
Version is 3.0-1

##Screenshot
![screenshot_20170129_123709](https://cloud.githubusercontent.com/assets/15875927/22404049/55d87bf8-e620-11e6-986d-ffefb0a4a85e.png)
![screenshot_20170129_124005](https://cloud.githubusercontent.com/assets/15875927/22404051/55dcbd9e-e620-11e6-8280-e7450e1691d7.png)
![screenshot_20170129_124109](https://cloud.githubusercontent.com/assets/15875927/22404050/55db6c14-e620-11e6-9824-e13e587fc69a.png)

## Config file

[config.txt](https://github.com/dylanaraps/neofetch/files/737514/config.txt)

## Verbose log

https://gist.github.com/techMod/5853dd089f7504d4d1e3be91a21e1ede

**Comment by konimex** [comment]
Can you try `neofetch --w3m --source <file>`.

**Comment by techMod** [comment]
i just tried it. It shows an odd output. See here:

![screenshot_20170129_130524](https://cloud.githubusercontent.com/assets/15875927/22404180/c77df046-e623-11e6-8f89-66855c085ba8.png)

**Comment by dylanaraps** [comment]
The first log file in the first posts says that the directory you gave neofetch doesn't exist or is inaccessible. 

Can you upload a log file of  `neofetch --w3m --source <file>`?

**Comment by techMod** [comment]
Here is the log, but it is very short...


`[?25l[?7l[0m[34m[1m                   -` 
                  .o+` 
                 `ooo/ 
                `+oooo: 
               `+oooooo: 
               -+oooooo+: 
             `/:-:++oooo+: 
            `/++++/+++++++: 
           `/++++++++++++++: 
          `/+++ooooooooooooo/` 
         ./ooosssso++osssssso+` 
        .oossssso-````/ossssss+` 
       -osssssso.      :ssssssso. 
      :osssssss/        osssso+++. 
     /ossssssss/        +ssssooo/- 
   `/ossssso+/:-        -:/+osssso+- 
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/ 
 .`                                 `/ 
[19A[9999999D[41C[0m[1m[34m[1mdaniel[0m@[34m[1mW520[0m 
[41C[0m[1m[0m-----------[0m 
[41C[0m[34m[1mOS[0m[0m:[0m Arch Linux x86_64[0m 
[41C[0m[34m[1mModel[0m[0m:[0m 4284A54 ThinkPad W520[0m 
[41C[0m[34m[1mKernel[0m[0m:[0m 4.9.6-1-ARCH[0m 
[41C[0m[34m[1mUptime[0m[0m:[0m 5 mins[0m 
[41C[0m[34m[1mPackages[0m[0m:[0m 741[0m 
[41C[0m[34m[1mShell[0m[0m:[0m bash 4.4.11[0m 
[41C[0m[34m[1mResolution[0m[0m:[0m 1600x900[0m 
[41C[0m[34m[1mDE[0m[0m:[0m KDE[0m 
[41C[0m[34m[1mWM[0m[0m:[0m KWin[0m 
[41C[0m[34m[1mWM Theme[0m[0m:[0m Breeze[0m 
[41C[0m[34m[1mTheme[0m[0m:[0m Breeze[0m 
[41C[0m[34m[1mIcons[0m[0m:[0m Breeze[0m 
[41C[0m[34m[1mTerminal[0m[0m:[0m konsole[0m 
[41C[0m[34m[1mTerminal Font[0m[0m:[0m Hack 10[0m 
[41C[0m[34m[1mCPU[0m[0m:[0m Intel i7-2760QM (8) @ 3.5GHz[0m 
[41C[0m[34m[1mGPU1[0m[0m:[0m Intel Integrated Graphics[0m 
[41C[0m[34m[1mGPU2[0m[0m:[0m NVIDIA Quadro 1000M[0m 
[41C[0m[34m[1mMemory[0m[0m:[0m 1426MB / 32062MB[0m 
[41C[0m[34m[1mDisk (/)[0m[0m:[0m 6.3G / 50G (14%)[0m 
[41C[0m[34m[1mUsers[0m[0m:[0m daniel[0m 
[41C[0m[34m[1mInstall Date[0m[0m:[0m Tue 24 Jan 2017 11:33 PM[0m 

[41C[0m[30m[40m   [0m[31m[41m   [0m[32m[42m   [0m[33m[43m   [0m[34m[44m   [0m[35m[45m   [0m[36m[46m   [0m[37m[47m   [0m


[?25h[?7h`

Is it possible, that neofetch thinks, that home is a root directory, since it is spelled like so:

`neofetch --image /home/path/to/png`

instead of

`neofetch --image home/path/to/png` ?

**Comment by dylanaraps** [comment]
That's not a correct log file. Did you type out the command like this:?

```sh
neofetch --w3m /home/dylan/Pictures/Wallpapers/10.jpg -vv 2> neofetchlog
```

**Comment by techMod** [comment]
checked again, my bad sorry I made a gist with the correct one.

https://gist.github.com/techMod/6ef6f1e4d559f8cdf7674365ac28a98f

**Comment by dylanaraps** [comment]
Here's the error:

```sh
to_ascii 'Image: Failed to find terminal window size.'
err 'Image: Failed to find terminal window size.'
```

Do you have all of the dependencies for image mode?

https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal#dependencies

**Comment by techMod** [comment]
Yes I habe them installed, but the output stays the same.

**Comment by dylanaraps** [comment]
Can you send me the outputs of these commands?

```sh
printf '\033[14t'
xdpyinfo | grep -E -o "focus:.*0x[0-9a-f]+"
xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}'
xwininfo -root
```

**Comment by techMod** [comment]
Okay I got it going now. But this issue can sneak under the radar. In general all dependencies are preinstalled on a an arch/plasma setup. The sneaky deps are xorg-inininfo and imlib2. Now the command  `neofetch --w3m --source /path/to/pic` works nicely. Assuming it will work in general, but haven't created a script yet.

**Comment by MilkyPL** [comment]
There's no such thing as xorg-inininfo. Could you please provide the valid name? I have the same issue.

**Comment by techMod** [comment]
Hi, the valid package is xorg-xwininfo. Sorry for the delay.

**Comment by dylanaraps** [comment]
Can you try the latest git release with a new confg file and: `neofetch --w3m /path/to/img --config off`?

**Comment by techMod** [comment]
I got version 3.3.0-1 installed. The AUR shows the git version with 3.2.0. I assume the 3.3.0 version is the latest?
