### ISSUE TITLE
Commenting out 'info cols' instead of setting 'color_blocks=off' adds 3 new lines - possibly related to #628

### ISSUE THREAD

**Issue by Taijian** [dylanaraps/neofetch#652]
## Description

After updating to 3.0.1 from 3.0 I noticed that neofetch would insert 3(three) extra new lines below it's usual output. Investigating the issue I found that after re-enabling 'info cols' (which I had previously coomented out in my personal config file) and instead specifying 'color_blocks=off', the issue would go away.

I would wish for the two customizations: a) commening out 'info cols' and b) setting 'color_blocks=off' to behave in an identical fashion.

#### Neofetch version

3.0 -->  #3.0.1

## Verbose log

https://gist.github.com/Taijian/9ffc4350201f86273986680d2911402a

**Comment by dylanaraps** [comment]
The issue should be fixed now, try out the latest master and let me know if it still occurs.

**Comment by Taijian** [comment]
I have now installed the lastest git (gb4e5169) and the issue has indeed disappeared - mostly. Now the difference between the two options is that 'info cols' enabled AND 'color_bars=off' does insert a blank line into the output, whereas commenting out 'info cols' does not.

**Comment by dylanaraps** [comment]
Thanks for the info, the behavior should be consistent now. Try out the latest master and let me know if it works as expected now. :)

**Comment by Taijian** [comment]
OK, I'm now on gbff259f and both options behave exactly alike! Thank you for the swift fix!

**Comment by dylanaraps** [comment]
No problem :)
