### ISSUE TITLE
Adding Whitespaces in .config doesnt rearrange

### ISSUE THREAD

**Issue by sarvdaman** [dylanaraps/neofetch#653]
## Description 
 
Added whitespaces to config but still no effect on output. 

my config is --

print_info() {

    info title
    info underline

    info "OS"              distro
    info "Model          " model
    info "Kernel         " kernel
    info "Uptime         " uptime
    info "Packages       " packages
    info "Shell          " shell

    info "Battery        " battery
    info "Disk           " disk

    info "CPU            " cpu
    info "CPU Usage      " cpu_usage
    info "Memory         " memory

    info "GPU            " gpu
    info "Resolution     " resolution
    info "DE             " de
    info "WM             " wm
    info "WM Theme       " wm_theme
    info "Theme          " theme
    info "Icons          " icons
    info "Terminal       " term
    info "Terminal Font  " term_font

    info line_break
    info cols
    info line_break
}

and output is --

                   -`                    nilesh@ArchLinux 
                  .o+`                   ---------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Model : HP Pavilion dv6 Notebook PC Rev 1 
               `+oooooo:                 Kernel : Linux 4.9.6-1-ARCH 
               -+oooooo+:                Uptime : 1 hour, 41 minutes 
             `/:-:++oooo+:               Packages : 966 
            `/++++/+++++++:              Shell : bash 4.4.11 
           `/++++++++++++++:             Battery 0: 93% [Charging] 
          `/+++ooooooooooooo/`           Disk (/): 9.0G / 50G (20%) 
         ./ooosssso++osssssso+`          CPU : Intel 2 Duo T6600 (2) @ 2.2GHz [46.0°C] 
        .oossssso-````/ossssss+`         CPU Usage : 18% 
       -osssssso.      :ssssssso.        Memory : 1391MiB / 3924MiB 
      :osssssss/        osssso+++.       GPU : AMD Mobility Radeon HD 4650/5165 
     /ossssssss/        +ssssooo/-       Resolution : 1360x768 @ 59Hz 
   `/ossssso+/:-        -:/+osssso+-     DE : GNOME

**Comment by dawidd6** [comment]
What do you want to achieve exactly?

**Comment by sarvdaman** [comment]
see the "arrangement" of output text below- 

this is what i'm getting currently -

[what i get.txt](https://github.com/dylanaraps/neofetch/files/745871/what.i.get.txt)

and this, which i want -

[what i want.txt](https://github.com/dylanaraps/neofetch/files/745876/what.i.want.txt)

**Comment by dylanaraps** [comment]
The alignment using white-space was broken in 3.0 due to the changes between `info()` and `prin()`. I won't be able to fix this until I finish rewriting large parts of the script.

I'm closing this and adding it to the TODO issue since it's related to some of the tasks already on it. 

#613
