### ISSUE TITLE
Possible L10n support?

### ISSUE THREAD

**Issue by MingcongBai** [dylanaraps/neofetch#654]
## Description

Just wondering if `neofetch` has a plan on introducing localization support via Gettext or other forms of localization manager, I would think it could be useful to at least translate the categories of information given by `neofetch` ("processor:", "uptime:", etc.).

#### Neofetch version

All

**Comment by konimex** [comment]
I think this is simply impossible. Because you can set the subtitle yourself.

**Comment by dylanaraps** [comment]
I agree with @konimex, you can just modify your config file to change the subtitle names.

This will be difficult to implement (If it's possible to begin with) and I don't think it can be done cleanly (It needs to be portable and work on all OS)

**Comment by MingcongBai** [comment]
Okay... I'm quite certain that Gettext should work with Bash, but oh well, it might just bloat the software up with a load of excessive data. Closing.
