### ISSUE TITLE
Cannot run neofetch on cygwin

### ISSUE THREAD

**Issue by eti0** [dylanaraps/neofetch#655]
## Description

Can't run neofetch on cygwin, loads of errors appear.

#### Neofetch version

Latest git version.

## Screenshot

![fish homeetigitneofetch](https://cloud.githubusercontent.com/assets/14180792/22618606/0e065082-eae1-11e6-9b1f-ffd3c222a528.png)

## Config file

Default one, nothing changed.

## Verbose log

Would be useless because it simply can't run.

Dependencies are all installed, maybe I'm missing something obvious but I don't really know.

**Comment by dylanaraps** [comment]
Did you edit neofetch using a Windows text editor?

Googling `$'\r' command not found` tells me that the file is full of Windows line endings which is causing bash to error.

Sources: 

- https://www.google.com.au/search?q=%24'\r'+command+not+found
- http://stackoverflow.com/questions/20821260/r-command-not-found-ubuntu-13-04
- http://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile

Closing this as it's not a neofetch issue.

**Comment by eti0** [comment]
Thanks a lot, I should have Googled it before I guess.

I'm still having issues running the script thought.
[See here.](https://paste.teknik.io/Simple/m9edN)

**Comment by dylanaraps** [comment]
Neofetch can't find it's config file.

Have you installed neofetch correctly?

**Comment by eti0** [comment]
Might be an issue on my side, but the `neofetch` file doesn't appear in /usr/bin.

![fish homeetigitneofetch](https://cloud.githubusercontent.com/assets/14180792/22619782/6481b684-eafc-11e6-9d4e-1612e731bfd5.png)

**Comment by eti0** [comment]
Can't seem to manage to install it but I could just run it from the git folder.

![fish homeetigitneofet454ch](https://cloud.githubusercontent.com/assets/14180792/22619848/af0dd0d8-eafd-11e6-9d0e-cb8d580ab688.png)


If anyone is wondering why it can't work properly you just need to edit the filed via your favorite text editor and change the EOL to Unix.

Thanks for the help.

**Comment by dylanaraps** [comment]
The line endings were wrong because you edited the file in a Windows text editor. The line endings are already Unix.

**Comment by eti0** [comment]
I actually used cygwin's dos2unix feature and applied it to all of the files.
Still, it worked afterwards so that's okay.

**Comment by brianscottwilson** [comment]
If you read the neofetch script, there are some library files that need to be installed as well as the bash script itself.  You might want to use the RPM to install a standard package.

**Comment by JasonMo1** [comment]
After 5 years, I finally find this quetion! I solve this quetion now. I use pacman on Msys2 to download a neofetch, and I copy the file "<MSY2 install path>/usr/bin/neofetch" into "<cygwin install path>/bin/" ,and I input the "neofetch" command in the cygwin, and it finally work!
