### ISSUE TITLE
Neofetch not displaying images.

### ISSUE THREAD

**Issue by furycd001** [dylanaraps/neofetch#657]
HI Guys.

Running **Ubuntu 16.04.2 LTS x86_64** and just installed neofetch through the given ppa here on github. I cannot seem to get neofetch to display any given image. I am running neofetch in both up to date xterm & xfce4-terminal with the following command  **neofetch --image /home/furycd001/.hello/Terminal.jpg** Neofetch will run with this command but only display ascii art and not my given image. Link to my config file at bottom. I don't know how to find or access any log files so if someone could tell me how to do so then I'll kindly upload them asap. Also it does not matter if I use --w3m or --image with the full path or without. Either way neofetch still shows only ascii. Thank you very much for your time and help.

http://paste.ubuntu.com/24042889/

**Comment by furycd001** [comment]
Under the image source I have tried using --image wall, /path/to/img and also a direct link to my image /home/furycd001/.hello/Terminal.jpg. Ascii and off work fine, just not anything image related. I have made sure that I have w3m & w3m-img installed and that they both work, which they do. Any help will be appreciated as I may just be missing something or doing something wrong. Many thanks...

**Comment by konimex** [comment]
Please include a verbose log because as of now we have not enough data on your problem. A screenshot also would be helpful.

To produce a verbose log,

1. Run `neofetch <options> -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by furycd001** [comment]
Thank you for the help with finding / creating the log file.  I opened it with gedit and copied/pasted it to [here](http://paste.ubuntu.com/24047973/) Please let me know if you need anything else or if I am simply doing something wrong. Thank you for your help...

**Comment by dylanaraps** [comment]
Your config file is *really* outdated, try starting with a fresh config file. This should fix the issue based on what the log file tells me.

**Comment by furycd001** [comment]
Don't know why I would have had an old config file but I created a new one and everything works perfectly now. Thank you very much for your help...
