### ISSUE TITLE
Add font detection for iTerm2 on macOS

### ISSUE THREAD

**Issue by jorgegonzalez** [dylanaraps/neofetch#664]
## Description

I think this feature is long overdue and would be appreciated by all Neofetch users that use iTerm.

The command `defaults read ~/Library/Preferences/com.googlecode.iterm2.plist | grep 'Normal Font'` will return a line of the following form: `"Normal Font" = "Lemonmedium 14";`.

I've been trying to do this for a while but I don't know Bash well enough to format the output correctly. Ideally the conversions should look like this: 

```
"Normal Font" = "RobotoMono-Regular 13";     -> Roboto Mono
"Normal Font" = "SourceCodePro-Regular 13";  -> Source Code Pro
"Normal Font" = "AndaleMono 13";             -> Andale Mono
"Normal Font" = "Lemonmedium 14";            -> Lemon
```

Of course displaying anything at all is better than nothing, so even `RobotoMono` or `SourceCodePro` is (at least for me) a good start.

**Comment by dylanaraps** [comment]
The problem we came across when trying to implement this earlier was that iTerm2 uses profiles for configuration and we couldn't figure out how to find the right font for the current profile.

Does the command above do that?

Also about formatting the fonts, something like this might work:

```sh
term_font="$(defaults read ~/Library/Preferences/com.googlecode.iterm2.plist | grep -F "Normal Font")"
term_font="${term_font//-/ }"
term_font="${term_font/Mono/ Mono}"
term_font="${term_font/medium/ medium}"

# We could even just hide '-Regular'
term_font="${term_font/\-Regular}"
```

This only covers the fonts in your post above as I'm unsure about the other formats.

**Comment by jorgegonzalez** [comment]
I see the issue.

What if we assume that a user only has a single profile? This could be implemented since the command above will only output a single line. If a user has more than one profile (i.e. the command above outputs more than one line), then `term_font` will not be set.

The code you suggested does not work; there is no change from the original form.

**Comment by jorgegonzalez** [comment]
Sorry, there is _some_ change:

```
"Normal Font" = "SourceCodePro-Medium 14"; -> "Normal Font" = "SourceCodePro medium 14"
```

**Comment by jorgegonzalez** [comment]
This is working nicely for the formatting: 

```
line="$(defaults read ~/Library/Preferences/com.googlecode.iterm2.plist | grep 'Normal Font')"
re='"Normal Font" = "([^-" ]+).*";'

if [[ $line =~ $re ]]; then
    term_font=${BASH_REMATCH[1]}
fi

term_font="${term_font//-/ }"
term_font="${term_font/Mono/ Mono}"
term_font="${term_font/medium/ medium}"
```

```
"Normal Font" = "SourceCodePro-Medium 14"; -> SourceCodePro
"Normal Font" = "Lemonmedium 14"; -> Lemon medium
"Normal Font" = "RobotoMono-Regular 13"; -> Roboto Mono
"Normal Font" = "AndaleMono 13"; -> Andale Mono
"Normal Font" = "Tamzen7x14Medium 14"; -> Tamzen7x14 medium
```

**Comment by dylanaraps** [comment]
You can change this:

```sh
if [[ $line =~ $re ]]; then
    term_font=${BASH_REMATCH[1]}
fi
```

to this:

```sh
[[ "$line" =~ $re ]] && term_font=${BASH_REMATCH[1]}
```

**Comment by jorgegonzalez** [comment]
```bash
line="$(defaults read ~/Library/Preferences/com.googlecode.iterm2.plist | grep -F 'Normal Font')"
re='"Normal Font" = "([^-" ]+).*";'
[[ "$line" =~ $re ]] && term_font=${BASH_REMATCH[1]}

term_font="${term_font//-/ }"
term_font="${term_font/Mono/ Mono}"
term_font="${term_font/medium/}"
term_font="${term_font/Medium/}"
term_font="${term_font/CodePro/ Code Pro}"
term_font="${term_font/ForPowerline/}"
```

This works for just about every font I've tested it with.

There is a noticeable lag, I'm guessing due to the regex.

Also I want to be explicit that this assumes the user only has a single profile

**Comment by dylanaraps** [comment]
It might be due to the command that reads the plist file. I think we read
the plist differently elsewhere in the script. It might be worth taking a
look at.
