### ISSUE TITLE
neofetch | lolcat have strange chars

### ISSUE THREAD

**Issue by atommixz** [dylanaraps/neofetch#666]
## Description
I have ugly looking neofetch over lolcat

#### Neofetch version
3.0.1.r29.g1af650e-1
## Screenshot
![2017-03-01-062002_3200x1080_scrot](https://cloud.githubusercontent.com/assets/359276/23444730/e08ff08e-fe47-11e6-87ef-b19f24175ebb.png)

## Config file
default from pkg ArchLinux aur/neofetch-git http://ix.io/nR0

## Verbose log
http://ix.io/nQZ

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by atommixz** [comment]
$ grep -i font .config/termite/config 
font = Monospace 18

**Comment by dylanaraps** [comment]
This is related to the escape sequences neofetch uses to format the output. There's no way for me to fix this.

**Comment by dylanaraps** [comment]
Neofetch now works with `lolcat`! :fireworks:
