### ISSUE TITLE
Neofetch not showing any disks

### ISSUE THREAD

**Issue by Shawniac** [dylanaraps/neofetch#667]
## Description

Neofetch doesn't seem to show any disks for me. Either I'm doing something wrong or there seems to be a bug.

#### Neofetch version
3.0.1

## Screenshot
https://imgur.com/a/CxDtH

## Config file
none/default

## Verbose log
https://gist.github.com/Shawniac/9ed73e16c65177be9c8b292ea6d41437

**Comment by dylanaraps** [comment]
Does the `df` command work on your system?

**Comment by konimex** [comment]
Because you used default config, have you removed the comment for disk in the config?

```sh
# info "Disk" disk
```

**Comment by Shawniac** [comment]
> Because you used default config, have you removed the comment for disk in the config?

I've copied over the default config from /etc/neofetch to the local ~/.config/neofetch directory and uncommented that line, it works now, thank you!

But still, should there not be an option to make disks visible without a config file?

**Comment by dylanaraps** [comment]
That's on the TODO list, due to the way neofetch prints the info this isn't possible right now.

**Comment by DoTheEvo** [comment]
err, why is it not shown on default? 
its one of the more important info 
and now I am writing ansible stuff for myself and have to add another task uncommenting it for no reason..
will be also enabling local IP I guess
