### ISSUE TITLE
Faster eopkg installed-count

### ISSUE THREAD

**Issue by ikeydoherty** [dylanaraps/neofetch#669]
Running `eopkg list-installed` can take a bit of time as it has to load the XML descriptions to spit them back out. Here's a suggestion, if you're up for it :)

A faster method is:

`ls /var/lib/eopkg/package -1 | wc -l`

Each directory in that directory contains `files.xml` and `metadata.xml`, and constitute on-disk package DB entries.

New method
```
time ls /var/lib/eopkg/package -1 | wc -l
1821
ls --color=tty /var/lib/eopkg/package -1  0.00s user 0.00s system 95% cpu 0.003 total
wc -l  0.00s user 0.00s system 23% cpu 0.003 total
```

Old method
```
time eopkg list-installed | wc -l
1821
eopkg list-installed  3.20s user 0.06s system 100% cpu 3.260 total
wc -l  0.00s user 0.01s system 0% cpu 3.259 total
```

**Comment by konimex** [comment]
Applied to master, thanks!

**Comment by ikeydoherty** [comment]
Cheers bud :D
