### ISSUE TITLE
Support locale information

### ISSUE THREAD

**Issue by hannesfrank** [dylanaraps/neofetch#679]
The locale is an important system setting which often causes problem with applications. `neofetch` should be able to report it.

(On Ubuntu) one could use the `LANG` environment variable, or in general the output of the `locale` command:

```
$ locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

The output could be then:

```
Language: de_DE.UTF-8
```

**Comment by dylanaraps** [comment]
I've opened #682 which implements this.
