### ISSUE TITLE
Screenshot should work without configuration

### ISSUE THREAD

**Issue by hannesfrank** [dylanaraps/neofetch#680]
## Description

One should be able to take a screenshot with `neofetch -s [path]`.

On a non-english this fails because there is no `~/Pictures` folder. (On an X11 system) the actual location can be found using `xdg-user-dir PICTURES`.

Also the `--help` states that `-s path` is possible, but it seems to be not.

## Expected behavior

The following is the behavior I would expect, but is incompatible with the current behavior.

1. `neofetch -s` should save a screenshot to the *current directory* using the name `neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png`. Right now the `-s` just seems to be a flag enable screenshot taking, in contrast to the statement in the `--help` text.

2. `neofetch -s path/to/image.png` should save a file `image.png` in the folder `./path/to/` if it exists. Right now this argument seems to be ignored.

#### Neofetch version

`Neofetch 3.0.1`

## Log

```
$ neofetch --config none -s image.png -vv 2> neolog
# ...
Screenshot:  doesn't exist. Edit the config file or create the directory to take screenshots.
```

```
# neolog:
# ...
+ export LC_ALL=C
+ LC_ALL=C
+ [[ ascii != \o\f\f ]]
+ printf %b '\033[16A\033[9999999D'
+ old_functions
+ type printinfo
+ get_cache_dir
+ case "$os" in
+ cache_dir=/tmp
+ print_info
+ dynamic_prompt
+ case "$image_backend" in
+ (( lines < info_height ))
+ printf '\n'
+ return
+ [[ ascii == *w3m* ]]
+ [[ on == \o\n ]]
+ take_scrot
+ [[ -d '' ]]
+ printf '%s\n' 'Screenshot:  doesn'\''t exist. Edit the config file or create the directory to take screenshots.'
+ [[ '' == \o\n ]]
+ [[ on == \o\n ]]
+ printf %b '[!]\033[0m Config: Sourced default config. (/etc/neofetch/config)\n[!]\033[0m Info: Couldn'\''t detect Terminal Font.\n'
[!] Config: Sourced default config. (/etc/neofetch/config)
[!] Info: Couldn't detect Terminal Font.
+ return 0
+ printf '\033[?25h\033[?7h'
```

**Comment by dylanaraps** [comment]
I've opened #681 which should fix all of the issues you've found.

Let me know if I've missed anything.
