### ISSUE TITLE
[Terminal Font] Add support for Terminix/Tilix

### ISSUE THREAD

**Issue by rockrij** [dylanaraps/neofetch#684]
Hello!

I'm using Arch Linux Xfce and I have two terminal emulators, Xfce4 Terminal 0.6.3 (Gtk2) and Terminix 1.5.2 (Gtk3)... neofetch version is 3.0.1... I'm using the default config. Terminal font info is shown in Xfce4 Terminal but not in Terminix. Attached screenshot shows Terminix on the upper left, Xfce4 Terminal on the lower left and the opened config file on the right.
![screenshot_2017-03-29_14-59-38](https://cloud.githubusercontent.com/assets/26760601/24442709/e6ab102e-1491-11e7-93cf-6222fd962b4b.png)

Thank you.

**Comment by dylanaraps** [comment]
Notes:

- The config file is profile based.
- There are two proprietery variables we can use to get profile name and number.
    - `${sessionName}`
    - `${sessionNumber}`
- The config file uses dconf and is possibly binary(?).
- We may need to use `dconf` to extract the info.

**Comment by rockrij** [comment]
Thanks.

**Comment by mstraube** [comment]
I looked a bit into this (used the tilix packages from AUR).

We can get a list of available profiles and the fonts they use from dconf
```
$ dconf dump /com/gexperts/Tilix/
[profiles]
default='d64c2ac0-1557-44da-99fa-9630a4a8590c'
list=['2b7c4080-0ddd-46c5-8f23-563fd3ba789d', 'd64c2ac0-1557-44da-99fa-9630a4a8590c']

[profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d]
use-system-font=false
visible-name='Standard'
font='Nimbus Mono PS 12'

[profiles/d64c2ac0-1557-44da-99fa-9630a4a8590c]
use-system-font=true
visible-name='Unnamed'
```
If `use-system-font` is `true` we can get the font from gsettings.
```
gsettings get org.gnome.desktop.interface monospace-font-name
```
We can get the PID of the current Window/Tab with `get_ppid "$$"`

Now, the hard part is to figure out which profile is in use for that PID.
I don't know if that's possible at all. Until now I wasn't able to find a way..
