### ISSUE TITLE
Allow custom names in Disk Subtitle

### ISSUE THREAD

**Issue by TimoVerbrugghe** [dylanaraps/neofetch#687]
## Description
I use neofetch on my home server, which has several drives on several mount points (sometimes far in my home folder). So both the mount & name options for disk_subtitle is not perfect for my situation. An option to define names for the disks themselves or just use the folder name where the disk is mounted (instead of the entire path) could be a better option.

But just a small nitpick, it's a great tool dylanaraps!

**Comment by dylanaraps** [comment]
I've opened #688 which adds an option to just use the folder name as the subtitle.

Adding custom names will be more difficult so it'll take me a little longer to add it.

**Comment by TimoVerbrugghe** [comment]
Amazing! Works great in my situation, thanks!
