### ISSUE TITLE
Support for MINGW64_NT-6.2 (Windows 8 Enterprise N)

### ISSUE THREAD

**Issue by Septenary** [dylanaraps/neofetch#690]
## Description
Microsoft Windows 8 Enterprise N is not supported. I installed neofetch through Git Bash and upon running it was told: "
Unknown OS detected: 'MINGW64_NT-6.2', aborting...
Open an issue on GitHub to add support for your OS.
"
http://prntscr.com/eskw5i

#### Neofetch version
version="3.0.2"
http://prntscr.com/eskvof

## Screenshot
http://prntscr.com/eskw5i

## Config file
[config.txt](https://github.com/dylanaraps/neofetch/files/895055/config.txt)

## Verbose log
https://pastebin.com/qyb3yaDy

**Comment by konimex** [comment]
Because MinGW works identically like MSYS2, I will try to implement a fix.

**Comment by konimex** [comment]
Try #692 and let me know if it has been supported.

**Comment by Septenary** [comment]
Appears to be working just fine. The interaction that Git Bash has with shebangs caused it to throw up: "#!/usr/bin/env: No such file or directory" , however, adding "clear" as line 2 to neofetch resolves this aesthetically in my context. http://prntscr.com/esojnb http://prntscr.com/esorxt
