### ISSUE TITLE
Local IP address detected incorrectly

### ISSUE THREAD

**Issue by matoro** [dylanaraps/neofetch#691]
## Description

Assuming you are using the method described in https://stackoverflow.com/a/25851186 to retrieve a local IP address, it seems to be producing the wrong result.  The command ```ip route get 1``` returns the results:
```
1.0.0.0 via 10.62.128.1 dev wlp6s0 src 10.62.132.129 uid 1000 
    cache
```
which results in neofetch displaying a local IP of ```1000``` when it should be ```10.62.132.129```.

#### Neofetch version
neofetch 3.0.1-1

## Screenshot
https://my.mixtape.moe/mmorvg.png

## Config file
https://my.mixtape.moe/nbdaen

## Verbose log
https://my.mixtape.moe/efqsux

**Comment by konimex** [comment]
Addressed in #663.
