### ISSUE TITLE
XTerm: Division by 0 error.

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [dylanaraps/neofetch#704]
Hello I get an error when using the image mode in xterm

neofetchlog  https://pastebin.com/4ZmC0qHg

![2017-04-25-220504_1024x600_scrot](https://cloud.githubusercontent.com/assets/19531907/25420018/aad20b10-2a5e-11e7-8a8e-599f4320ee4d.png)
![2017-04-25-220605_1024x600_scrot](https://cloud.githubusercontent.com/assets/19531907/25420019/aad958ac-2a5e-11e7-9f83-ef8a339c084b.png)
![2017-04-26-085730_1024x600_scrot](https://cloud.githubusercontent.com/assets/19531907/25420032/c0700562-2a5e-11e7-8d0d-505c711a7112.png)

**Comment by konimex** [comment]
Please include your neofetch config.

**Comment by konfou** [comment]
Are you having `xdotool` or 'xwininfo' with `xpyinfo` or `xprop` installed?

**Comment by xxxvik-xakerxxx** [comment]
xdotool yes

**Comment by I2obiN** [comment]
Having the same issue at the moment on xterm and getting the same 'division by zero'. If you'll notice in the screenshot posted here all height and width values are 0. I thought perhaps maybe it's a permissions issue with the file or access to it but tried sudo and chmod +x on the picture but still no luck.

Anyway just thought I'd post that observation about the values being 0.

![screenshot from 2017-06-28 18-47-20](https://user-images.githubusercontent.com/7683830/27652069-4dd504c0-5c32-11e7-9bb2-7935b388552e.png)

**Comment by dylanaraps** [comment]
Fixed in latest master.

**Comment by boardfish** [comment]
Running v3.2.0 with `xwininfo` and `xprop` both installed, here's where the fun starts in the verbose log. Pretty sure I compiled from the latest master, I'd sooner do that than add a ppa. All that's left in the terminal is the penultimate line of the logs below:

https://pastebin.com/cWG9d1Rn
