### ISSUE TITLE
Support for IRIX

### ISSUE THREAD

**Issue by pgmassey** [dylanaraps/neofetch#706]
## Description
Running $ neofetch on SGI IRIX 6.5.29 (on an SGI Octane) returns the following:
Unknown OS detected: 'IRIX64', aborting...
Open an issue on GitHub to add support for your OS.

I am happy to provide any information, support, testing, etc; to add IRIX to the list of support UNIX systems (as it is a true, certified UNIX).

$ uname -a
IRIX64 Octane 6.5 01090133 IP30

#### Neofetch version
3.1.0

**Comment by dylanaraps** [comment]
I've opened #708 which will be where I'll work on this.

There's also a TODO list in the PR which lists everything we need to implement.

**Comment by dylanaraps** [comment]
Can you give me the output of these comands?:

- `uname -s`
- `uname -r`
- `uname -m`
- `uptime`
- `df`

**Comment by pgmassey** [comment]
Here you go:
    
    [Octane]:~ $ uname -s
      IRIX64
      [Octane]:~ $ uname -r
      6.5
      [Octane]:~ $ uname -m
      IP30
      [Octane]:~ $ uptime
       11:44pm  up 2 days, 22:14,  1 user,  load average: 0.02, 0.01,
      0.00
      [Octane]:~ $ df
      Filesystem             Type  blocks     use     avail  %use
      Mounted on
      /dev/root               xfs 70856064 49418512 21437552  70  /
      [Octane]:~ $
      
    
    
    On 4/26/2017 11:43 PM, Dylan Araps
      wrote:
    
    
      Can you give me the output of these comands?:
      
        uname -s
        uname -r
        uname -m
        uptime
        df
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dylanaraps/neofetch","title":"dylanaraps/neofetch","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dylanaraps/neofetch"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dylanaraps in #706: Can you give me the output of these comands?:\r\n\r\n- `uname -s`\r\n- `uname -r`\r\n- `uname -m`\r\n- `uptime`\r\n- `df`"}],"action":{"name":"View Issue","url":"https://github.com/dylanaraps/neofetch/issues/706#issuecomment-297603390"}}}

**Comment by dylanaraps** [comment]
Neofetch will now run on IRIX (it won't abort before printing anything) though the amount of info that will be displayed is small.

What we need to do now is add support for all of the info functions. I'll use google and implement as much as I can, you can also look at the list and do some investigation if you'd like.

**Comment by pgmassey** [comment]
Okay cool.  I will see what I can add, but anything that you cannot figure out (or that I cannot) the nekochan community is a very active IRIX community, and very happy to help adding IRIX support to just about anything.

**Comment by dylanaraps** [comment]
Awesome, I'll make an account there. :+1:

**Comment by konimex** [comment]
I have a few questions before I can continue adding things for IRIX support.

What is the output of these commands:
- `memstat`
- `versions` (If the output is too long, just pipe `head -5` and post the output here)
- `df -P`
- `ls --version 2>&1`

**Comment by pgmassey** [comment]
See below.  Please note that on IRIX 'versions' is like running
      rpm -qa, so it will show a lot of data (I truncated as
      requested).  memstat does not exist on IRIX, and there is no
      equivalent to either Sun's vmstat or Linux's free command.  Also,
      for ls, most native IRIX utilities do not accept long options, and
      there is no option for ls to show it's version (I just double
      checked the man page)
    
    
    
    [Octane]:~ $ memstat
      -bash: memstat: command not found
      [Octane]:~ $ versions | head -10
      I = Installed, R = Removed
      
         Name                 Date        Description
      
      I  4Dwm                 02/23/2014  Desktop Window Manager, 6.5.29
      I  4Dwm.man             02/23/2014  Desktop Window Manager Man
      Pages, 6.5.29
      I  4Dwm.man.4Dwm        12/11/2006  Desktop Window Manager Man
      Pages
      I  4Dwm.man.relnotes    02/23/2014  Desktop Window Manager Release
      Notes
      I  4Dwm.sw              02/23/2014  Desktop Window Manager, 6.5.29
      I  4Dwm.sw.4Dwm         02/23/2014  Desktop Window Manager
      [Octane]:~ $ df -P
      Filesystem          512-blocks   Used   Available Capacity Mounted
      on
      /dev/root             70856064 49433216 21422848   70%      /
      [Octane]:~ $ ls --version 2>&1
      Illegal option -- v
      Illegal option -- e
      Usage: ls -RadC1xmnloghrtucpFbqisfLAHMDPSj [files]
      [Octane]:~ $ 
    
    
    On 5/9/2017 11:56 AM, Herdiansyah
      wrote:
    
    
      I have a few questions before I can continue adding things for
        IRIX support.
      What is the output of these commands:
      
        memstat
        versions (If the output is too long, just pipe
          head -5 and post the output here)
        df -P
        ls --version 2>&1
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dylanaraps/neofetch","title":"dylanaraps/neofetch","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dylanaraps/neofetch"}},"updates":{"snippets":[{"icon":"PERSON","message":"@konimex in #706: I have a few questions before I can continue adding things for IRIX support.\r\n\r\nWhat is the output of these commands:\r\n- `memstat`\r\n- `versions` (If the output is too long, just pipe `head -5` and post the output here)\r\n- `df -P`\r\n- `ls --version 2\u003e\u00261`"}],"action":{"name":"View Issue","url":"https://github.com/dylanaraps/neofetch/issues/706#issuecomment-300210249"}}}

**Comment by konimex** [comment]
>Please note that on IRIX 'versions' is like running `rpm -qa`, so it will show a lot of data (I truncated as requested).

I feel like that is way too detailed, even comparing to `rpm -qa`, with manpages, etc.

What about `versions -b` instead?

>memstat does not exist on IRIX, and there is no equivalent to either Sun's vmstat or Linux's free command.

Alright, I must've been reading the wrong docs, then.

>Also, for ls, most native IRIX utilities do not accept long options, and there is no option for ls to show it's version (I just double checked the man page)

It's okay. It's intended to be that way because neofetch will use the error output instead of whatever `--version` is supposed to be. It's the only workaround to detect which version of `ls` is used (because in some cases, there are some people that use GNU coreutils to replace their native utilities. Or in my personal case, Busybox is being used to replace GNU coreutils).

Also, can you do the same for `df`?

**Comment by pgmassey** [comment]
Here you go for df

[Octane]:~ $ df --version
Illegal option -- -
Usage: df [-befhikmPlnqrtV] [-F type] [-w width] [filesystem ...]
Usage: devnm name
[Octane]:~ $

Slightly more compact with versions:
[Octane]:~ $ versions -b | head -10
I = Installed, R = Removed

   Name                 Date        Description
I  4Dwm                 02/23/2014  Desktop Window Manager, 6.5.29
I  CaseVision           10/13/2013  CASEVision Environment, Version 2.6.5
I  FDDIXPress           02/23/2014  FDDIXPress, 6.5.29
I  InPerson             12/11/2006  InPerson Desktop Conferencing, 2.2.1
I  OpenOffice           05/21/2013  OpenOffice: Office Suite, v1.0.3.1a
I  OutOfBox             03/24/2010  O2 OutOfBox Experience, version 2.4
I  PeoplePages          12/11/2006  PeoplePages - The Indigo Magic Phonebook, 1.2.1
[Octane]:~ $

**Comment by pgmassey** [comment]
Also, it dawned on me we can grab memory usage from the command 'pmem' - it's like ps but just shows RAM usage.  The configured and free memory values are given in kilobytes (I have 1280MB RAM):

[Octane]:~ $ pmem | head -10
Host: Octane   Configured: 1310720   Free: 1126448   Mon May 15 07:40:06 2017
    pid    ppid     user vtxt  ptxt  vdat  pdat  vshm  pshm  command
      1       0     root 1648    89   416   384     0     0  /etc/init
     37       1     root 1696    73   336   288     0     0  /sbin/xlv_plexd -
    110       1     root 1616    59   416   315     0     0  /usr/etc/syslogd
    208       1     root 1840   233   864   688     0     0  /usr/etc/rpcbind
    221       1     root 1920   359  1136   668     0     0  /usr/etc/nsd -a n
    225       1     root    0     0     0     0     0     0  bio3d
    238       1     root 2016   304   464   338     0     0  /usr/etc/gssd
    246       1     root 1760   104   848   384     0     0  /usr/etc/rpc.moun
[Octane]:~ $

**Comment by konimex** [comment]
Most functions has been added (aside from model and battery, but that's for later when we can find an SGI laptop). However I cannot confirm that all the functions can work correctly.

Please test it by pulling from the latest master on git, and checkout branch `upstream/irix` to test neofetch on IRIX.

Or you can download https://github.com/dylanaraps/neofetch/archive/irix.tar.gz

Report any inaccuracies that are occurred during testing.
