### ISSUE TITLE
Broken on BASH < 3.2

### ISSUE THREAD

**Issue by pgmassey** [dylanaraps/neofetch#707]
## Description

Attempting to run Neofetch on Solaris 10 on a Netra T1 returns the following:

/usr/bin/neofetch: line 27: shopt: nocasematch: invalid shell option name
/usr/bin/neofetch: line 329: unexpected argument `(' to conditional binary operator
/usr/bin/neofetch: line 329: syntax error near `(B'
/usr/bin/neofetch: line 329: `    if [[ "$os" =~ (BSD|MINIX) && "$distro" == *"$kernel_name"* ]]; then'

System does have bash installed:

armanox@apollo:~ $ bash --version
GNU bash, version 3.00.16(1)-release (sparc-sun-solaris2.10)
Copyright (C) 2004 Free Software Foundation, Inc.
armanox@apollo:~ $ uname -a
SunOS apollo 5.10 Generic_142909-17 sun4u sparc SUNW,UltraAX-i2

Once again, happy to provide any information, testing, logging, support, etc; needed to add Solaris properly.  I will be testing Solaris 11 on SPARC later (and I also have access to Solaris 9 - 11 on x86)

#### Neofetch version
3.1.0

**Comment by dylanaraps** [comment]
I think I need to update the minimum version for `bash` in the dependency list. The errors should go away if you update bash to `3.2`. (This is when `nocasematch` and the regex matching were added/changed)

If this isn't possible, I'll look into a workaround for these two issues.

**Comment by dylanaraps** [comment]
I'm going to close this as a "won't fix". Neofetch actually requires BASH 3.2+ to function and I've updated the DOCS to reflect this. BASH 3.1 and 3.2 introduce some features that Neofetch uses throughout the script.
