### ISSUE TITLE
Ubuntu Mate ASCII Logo

### ISSUE THREAD

**Issue by mekatronik-achmadi** [dylanaraps/neofetch#712]
## Description

I'm just curious about Ubuntu MATE ascii logo, because all Ubuntu variants seem has their ascii logo, except MATE variant

Thanks

#### Neofetch version

I use 3.1.0 version on Arch Linux (AUR)

**Comment by dylanaraps** [comment]
Done.

You can use the ascii with `neofetch --ascii_distro ubuntu-mate` or by editing your config file.

**Comment by robaxelsen** [comment]
> Done.
> 
> You can use the ascii with `neofetch --ascii_distro ubuntu-mate` or by editing your config file.

Is it possible to make it use ubuntu-mate log by default if DE is MATE? If so, I'd happily submit an issue, and possibly also a PR.
