### ISSUE TITLE
Weird a-like letters between w3m image and output

### ISSUE THREAD

**Issue by SuperPrower** [dylanaraps/neofetch#715]
## Description

Check screenshot - you will see it. They do not appear when you use ascii. Haven't checked other backends.

I am using Arch Linux, urxvt terminal. w3m seems to work fine in other applications (like ranger).

#### Neofetch version
Neofetch 3.1.0-git, also tried non-git version (Arch Linux)
## Screenshot
![neofetch](https://cloud.githubusercontent.com/assets/10908110/25776126/7d9b632c-32be-11e7-9c07-bca03b5b962b.png)

## Config file
Doesn't matter- tried it with `--config=none --w3m`, same problem
## Verbose log
https://pastebin.com/Acv6LpPv

**Comment by dylanaraps** [comment]
Try out this PR and let me know id the problem perists:

https://github.com/dylanaraps/neofetch/pull/716/files

**Comment by SuperPrower** [comment]
So, I know it's silly, but I manually did the changes to /usr/bin/neofetch, and lauched it, and it didn't helped - same garbage.
I believe I have to do this some other way, correct?

**Comment by SuperPrower** [comment]
Ok, so it looks like it was my fault and I forgot to set locale.conf when I was installing system.
When I set utf8 locale, problem is gone.
I do have patch applied, but I don't know if problem is present without it, and I don't really want to check.

**Comment by dylanaraps** [comment]
All good.
