### ISSUE TITLE
Target directories are assumed at runtime

### ISSUE THREAD

**Issue by rekado** [dylanaraps/neofetch#718]
## Description

`neofetch` checks for the existence of either `/etc/neofetch` or `/usr/local/etc/neofetch`, and for `/usr/share/neofetch`.  These directories might not exist.  This prevents neofetch from being installed to any prefix.

Likewise, the `Makefile` assumes that it can write to `$DESTDIR/etc`.  On Guix we install all files to a unique prefix, including `/etc/neofetch`.  This means that for our package we needed to patch the Makefile to replace `$(DESTDIR)/etc` with `$(PREFIX)/etc`, and in `neofetch` replace `/etc/neofetch` with `/the/actual/prefix/etc/neofetch`, and `/usr/share/neofetch` with `/the/actual/prefix/share/neofetch`.

It would be nice if these locations in `neofetch` were placeholders that could be substituted at configure time.  This could be achieved with a simple configure script and `m4` or `sed`.

#### Neofetch version

3.1.0

**Comment by konimex** [comment]
>This means that for our package we needed to patch the Makefile to replace `$(DESTDIR)/etc` with `$(PREFIX)/etc`, and in neofetch replace `/etc/neofetch` with `/the/actual/prefix/etc/neofetch`

I don't know how Guix works, but can't it be done with `make DESTDIR=/the/actual/prefix`?

**Comment by konimex** [comment]
Closing this one since #754 is now merged.
