### ISSUE TITLE
Image mode not working in Ubuntu Gnome 16.04 LTS

### ISSUE THREAD

**Issue by adalvigi** [dylanaraps/neofetch#719]
## Description
I'm using Gnome Terminal. I followed the "images in the terminal" wiki page and enabled w3m-img and imagemagick, also changed image_source to wallpaper and tried to run neofetch `--image wall`, `--image wallpaper` or `--image ~/source/to/image`, but it keeps falling back to ASCII mode... how can I manage to have m'waifu on the terminal? Perhaps it's important to notice that I didn't have any files in m'~/.config/neofetch folder so I created a config file and pasted the code [here](https://github.com/dylanaraps/neofetch/wiki/Config-File), but this approach seems to work for the other things like showing a song, battery or stuff... 
Thanks in advance for your help and your work on neofetch, m'djentlesir, I really love this program and I hope I'll be able to use the beloved image mode.

#### Neofetch version
Latest, just cloned from source, master branch. Installed with checkinstall for what it's worth.

## Config file
https://pastebin.com/GumQgaFm

## Verbose log
https://pastebin.com/hpTaF1uR

**Comment by dylanaraps** [comment]
Have you tried: `neofetch --w3m` or `neofetch --w3m /path/to/img`?

**Comment by adalvigi** [comment]
I-it works! Sir, you're a djentleman and a scholar! :smiley: 
How can I make it use this command by default every time I run neofetch? Can I do it via config file?

**Comment by dylanaraps** [comment]
Yes, just chang the value of `image_backend` in your config file.

**Comment by adalvigi** [comment]
Thanks a lot sir, it works like a charm! I'd reccommmend to add this info in the "images in the terminal" section to make it easier for idiots like me to get their minimal waifu in the shell lol 
btw I just noticed that you used Pearl Jam's Betterman as an example song, great music taste! I myself was using their Given to Fly to try that feature out kek.
Thanks again for making this great tool and for being so kind in answering questions and receiving feedback to fix bugs, it's people like you who make FOSS great!

**Comment by dylanaraps** [comment]
I'll edit the wiki page!

Thanks for using neofetch :)
