### ISSUE TITLE
Add Support for KSLinux

### ISSUE THREAD

**Issue by Takeya-Yuki** [dylanaraps/neofetch#724]
## Description

I'd like to add support for KSLinux
kernel version: 4.4.2-kslinux

#### Neofetch version
neofetch 3.1.0-git

## Screenshot
![virtualbox_vm_17_05_2017_14_47_38](https://cloud.githubusercontent.com/assets/14171239/26142174/fb5eb826-3b11-11e7-8295-f957887bb211.png)

## Config file
default config
## Verbose log

Due to the init program is bash, so I can't get an error log
I have a /tool/cross/bin/env instead of  /usr/bin/env (but have /usr/bin folder)
It has a kpm package manager, use `kpm --get-selections` to get package list.

df -h has following output:
Filesys All     Used   %     Mounted
rootfs 1.8GB 1.6GB 87% /

It need 3.5GB Memory to startup the system due to / is rootfs

**Comment by Takeya-Yuki** [comment]
I had added support for KSLinux on my personal master branch (Takeya-Yuki/neofetch).

**Comment by dylanaraps** [comment]
Merged #727
