### ISSUE TITLE
Using --ascii_distro windows10 always displays the Win7 ascii art

### ISSUE THREAD

**Issue by SitiSchu** [dylanaraps/neofetch#725]
## Description

When running `neofetch --ascii_distro windows10` it displays the  Windows 7 ASCII art instead of the Windows10 one.

It doesn't work on my Debian 8 server(via SSH) and the Win10 built in Bash

#### Neofetch version
Neofetch 3.1.0-git

## Screenshot
![ss 2017-05-18 at 01 03 12](https://cloud.githubusercontent.com/assets/18517178/26179760/d2832938-3b65-11e7-9ecb-5c62008039f3.png)

## Config file
Default Config

## Verbose log
Debian 8 : https://pastebin.com/raw/GPBh7nbD
Win10: https://pastebin.com/raw/4eiJ1yGT

**Comment by dylanaraps** [comment]
Fixed, thanks for reporting this.

In the meantime (`--ascii_distro "windows 10"`) will work.
