### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by joeldamata** [dylanaraps/neofetch#728]
I cannot get any non-ascii image to display. Im not sure what to make of the log file. The thumbnails created in my home directory are working using display and look like they are cropped correctly. 

Fedora 25
neofetch-3.1.0-1
terminator-1.91-2
w3m-img-0.5.3-30
w3m-0.5.3-30
ImageMagick-6.9.3.0-6
ImageMagick-libs-6.9.3.0-6
xdotool-3.20150503.1-2

![screenshot from 2017-05-18 11-53-59](https://cloud.githubusercontent.com/assets/16352519/26211586/c88d002e-3bc0-11e7-860a-e5e253f694c4.png)

Config -> https://pastebin.com/c5v4wUXi

Log -> https://pastebin.com/LqbdXEPS.

**Comment by dylanaraps** [comment]
Do images work in `ranger`?

**Comment by joeldamata** [comment]
No. Also tried using just `w3m xkcd.com` in terminator and it doesn't display images.

With xterm both ranger/neofetch seems to work.

**Comment by dylanaraps** [comment]
This isn't a neofetch issue then. It's an issue with your system. Look into disabling terminal transparency, it might fix the issue.

**Comment by oblitum** [comment]
Just for information purposes: I got same issue on ArchLinux/xfce4-terminal. I also use transparency and disabled it but it didn't help.
