### ISSUE TITLE
How to quit

### ISSUE THREAD

**Issue by m4xcoat** [dylanaraps/neofetch#731]
I want to launch neofetch just at the beginning of a zsh session, jut like in the attached screenshot (the first screenshot shows screenfetch), but neofetch doesn't quit automatically so i have to press Ctrl+C… 
So if I log in on my device, it looks like that (second screenshot)…
would be great if there would be at least a launch option to automatically quit (or i didn't figure it out^^)…
![screenshot_20170526_012254](https://cloud.githubusercontent.com/assets/16852197/26474538/e5edb91e-41b1-11e7-9d56-02d4b747f2aa.png)
![screenshot_20170526_012516](https://cloud.githubusercontent.com/assets/16852197/26474619/5e37f8da-41b2-11e7-9834-c1808aa569e2.png)

**Comment by iandrewt** [comment]
Where in your zshrc have you put the `neofetch` line? This is working fine for me with zsh 5.3.1 when I have it towards the end of the file

**Comment by konimex** [comment]
This is either caused by resolution detection (which may be impossible since you are ssh-ing to the machine) or terminal detection. Can you provide your config file **and** your neofetch logs?

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by m4xcoat** [comment]
I put the neofetch line at the end of my zshrc

neofetch logs: https://pastebin.com/ahNMKDL6
config file is attached
[config.txt](https://github.com/dylanaraps/neofetch/files/1031091/config.txt)

**Comment by konimex** [comment]
I can reproduce this using ssh. It seems neofetch fails to get your terminal type when you are connected to another device using ssh.

The workaround for these kind of errors is to delete `info "Terminal" term` in your config, but we'll look into methods to disable detecting this when one connects into a device using SSH.
