### ISSUE TITLE
w3m transparency not functioning in terminator

### ISSUE THREAD

**Issue by undying-fish** [dylanaraps/neofetch#738]
## Description

As above. I've got a PNG image with transparency, and in the terminal, it shows as follows [here](http://imgur.com/a/2abG1), where all black sections are transparent in the original image.

#### Neofetch version

Probably the most recent but it doesn't seem like there's actually a way to find out. At least it's not listed in --help.

## Screenshot

Above.

**Comment by dylanaraps** [comment]
This isn't a neofetch issue and there's nothing I can do to fix it.

(You can use `--version` for future reference)
