### ISSUE TITLE
w3m-img not displaying correctly

### ISSUE THREAD

**Issue by furycd001** [dylanaraps/neofetch#739]
HI. I just installed Neofetch 3.1.0 on Xubuntu 16.04 and cannot get w3m-img to work correctly within xfce4-terminal 0.6.3. Defined img or wallpaper appears offset and only partly. Everything works fine whenever I use xvt or xterm. Please see below my config file, verbose log and screenshot of the problem I'm facing. Many thanks in advance for any help and for creating such an amazing and awesome app...

[SCREENSHOT](http://i.imgur.com/DEYTtyH.png)  //  [CONFIG FILE](http://paste.ubuntu.com/24747161/)  //  [VERBOSE LOG](http://paste.ubuntu.com/24747167/)

**Comment by dylanaraps** [comment]
This is an issue with `w3m-img` and your environment, not a Neofetch issue. The log file shows that Neofetch is functioning correctly.
