### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by erikdubois** [dylanaraps/neofetch#743]
no issue just a question
archlabs has a top that is broken now in current release
github has been updated already to address this issue - thanks for including it
just wondering when you would release the next version

thanks

**Comment by dylanaraps** [comment]
I've been insanely busy with university.

I've got one more exam left (on Tuesday) and after that I'll have a month break till next semester. During that time I'll be able to work on Neofetch and also flag releases.

Expect a new release over the next week or so.

**Comment by erikdubois** [comment]
no problem your studies are more important
