### ISSUE TITLE
neofetch is hanging my headless terminal

### ISSUE THREAD

**Issue by anniesbbs** [dylanaraps/neofetch#744]
## Description

neofetch is attempting to fetch DE, WM, WM_THEME, GTK2, and GTK3 information in a headless terminal.

I have opted to disable fetching GTK2 and GTK3.

attempting to alter the config to disable DE, WM, and WM_THEME fetching does not resolve because the user cannot even disable DE, WM and WM_THEME fetching. placing a # in front of the calls does not resolve. 

#### Neofetch version

Neofetch 3.1.0-git

## Config file
https://pastebin.com/PSVgswBs

## Verbose log
https://pastebin.com/FXMF3TfH

**Comment by dylanaraps** [comment]
Is `$DISPLAY` set in your environment?

**Comment by konimex** [comment]
I'm closing this issue because there are no response in more than 1 month. Please reopen this issue if your issue still persists and don't forget to update your Neofetch version.
