### ISSUE TITLE
neofetch | lolcat issue

### ISSUE THREAD

**Issue by 5P4D3** [dylanaraps/neofetch#747]
Just having an issue while combining neofetch and lolcat
![screenshot at 2017-06-13 12-38-03](https://user-images.githubusercontent.com/18681023/27066264-5a2df6ae-5035-11e7-9c45-b19ebe3fadd6.png)

Its cool if it's fix :D

**Comment by dylanaraps** [comment]
Yo, a quick search for "lolcat" in the tracker would've led you to these issues:

https://github.com/dylanaraps/neofetch/issues/685

https://github.com/dylanaraps/neofetch/issues/666

**Comment by dylanaraps** [comment]
Neofetch now works with `lolcat`! :fireworks:
