### ISSUE TITLE
Antergos shown as Arch after installing lsb-release

### ISSUE THREAD

**Issue by LER0ever** [dylanaraps/neofetch#755]
## Description
Neofetch works fine on a fresh installation of Antergos. But does not show the correct ascii logo after lsb-release is installed.  
The lsb_release file of Antergos indeed shows "Arch Linux Rolling", so **maybe we should source /etc/os-release before detecting lsb_release?**

#### Neofetch version
3.2.0

## Screenshot
![image](https://user-images.githubusercontent.com/10568668/27376602-2d7abbbe-5662-11e7-98e5-ac6e94126d92.png)

**Comment by dylanaraps** [comment]
Duplicate of https://github.com/dylanaraps/neofetch/issues/634

If we swap the detection around it'll break detection for Ubuntu and CentOS based distros. There's no middle ground.

The root cause of the issue is distros (especially distros based on a parent distro, Antergos in this case) not populating these files properly according to the spec.

The conclusion was that there's nothing we can really do about this to fix it.

**Comment by konimex** [comment]
See also: #488, #493.

**Comment by dylanaraps** [comment]
To add to above: The problem with these child distros is that they use their parent's packages. When you install `lsb_release` on Antergos it installs the `lsb_release` package for Arch Linux which contains the Arch Linux identification.

The only way for Antergos to fix this (as far as I'm aware) is to package their own version of `lsb_release` that prints the correct information.

**Comment by LER0ever** [comment]
> Duplicate of #634. #689
> The root cause of the issue is distros (especially distros based on a parent distro, Antergos in this case) not populating these files properly according to the spec.

Sorry I didn't search the existing issues before posting this. 
But how about we detect the presence of `pacman`. If it's arch-based, we use /etc/os-release first, so that the change won't affect the dpkg-based distros. Is that an acceptable option?

**Comment by konimex** [comment]
Well, I don't know. As of now it's entirely possible (albeit *really* unlikely in a normal scenario) to have multiple package managers in one distro. My system has two package managers (pacman and rpm, three with Gentoo Prefix).

For example, I am using Gentoo as my primary package manager, but I have installed pacman and rpm at the same time. If we use `case`, it's more than likely that we encounter a similar problem to #221 again.

**Comment by dylanaraps** [comment]
I don't want to add edge cases for every specific distro that may or may not follow one of the many standards that Neofetch currently supports. 

We've already got hard-coded detection for very specific distros such as `Linux on Windows 10`, `GoboLinux` (Different filesystem layout), `RedStar` (Would print in Korean without the special check) among others. These distros have specific reasons for needing special detection, Antergos and other child distros *don't*.

Neofetch currently supports `/etc/os-release`, `lsb_release` and `/etc/distro_name-release` for detection on Linux. If your distro can't be detected using either of the 3 standard methods and without good reason then I wouldn't call this a Neofetch issue.

I think it's up to the distro to populate the correct files with the correct information.

**Comment by LER0ever** [comment]
Alright. Since it's a distro-level issue, I'll create a issue report to antergos packagers. 
Closing this as duplicate.
