### ISSUE TITLE
Neofetch causes hangup during non-interactive login on CentOS 6

### ISSUE THREAD

**Issue by rkujawa** [dylanaraps/neofetch#760]
## Description

I have neofetch installed via RPM package and running upon every shell startup, by having the following script in /etc/profile.d/neofetch.sh :
```
/usr/bin/neofetch --disable packages
```

When I log in to the system in a non-interactive way, neofetch hangs and spins eating 100% CPU.

#### Neofetch version

neofetch-3.2.0-1.el6.noarch

This behaviour appeared after updating from 3.1.0 to 3.2.0.

## Screenshot

```
$ ssh bitfenix.local ls
(hangs, waits indefinitely)
```

In the meantime, the following can be observed the target machine (bitfenix):
```
$ ps axu | grep bash
(...)
rkujawa  20931 99.3  0.0 107044  2456 ?        R    18:06   0:32 bash /usr/bin/neofetch --disable packages
```

As you can see, 100% CPU usage. Looks like the offending bash command was spawned from within login shell. Here's a fragment of `pstree`:

```
`-sshd(20916)---sshd(20921)---bash(20922)---bash(20931)
```

And indeed, it is neofetch:
```
$ cat /proc/20931/cmdline
bash/usr/bin/neofetch--disablepackages
```

After killing the neofetch process, the orignal login process gets unstuck and executes correctly.

## Config file

Stock delivered with RPM.

## Verbose log

I've changed the script that executed neofetch to include logging:

```
/usr/bin/neofetch -vv --disable packages >/tmp/neofetchlog
```

However, the output does not include any useful information:
https://gist.github.com/rkujawa/c434c869373f2ede6f50ee5b6149a955

**Comment by rkujawa** [comment]
Okay, not including useful information was actually my fault, here's an output of:
`/usr/bin/neofetch -vv --disable packages 2>/tmp/neofetchlog.2`

https://gist.github.com/0e58de6415c6429ae2e679c9541f5b25

**Comment by konimex** [comment]
For some reason I cannot reproduce this on CentOS 7. I'll try this in CentOS 6 later, but it's either the terminal or the CPU detection.

Try to use `--disable packages term` as a workaround.

**Comment by rkujawa** [comment]
Indeed, it must be a problem with terminal detection, disabling `term` helped.

Btw. not seeing an actual output of neofetch when running `ssh <remote> ls` is normal and expected. That's how it should work, and it behaves like that for me now, after disabling term. I.e.: interactive login results in neofetch being displayed as always, while non-interactive login suppresses neofetch output and does not hang anymore.

My guess is that neofetch *is* executed, no matter if login is interactive or not, just that it's not displayed in the second case. Perhaps having no usable terminal breaks detection and causes this infinite loop.

**Comment by konimex** [comment]
I can reproduce it now.

Since the login is non-interactive, the value of `SSH_TTY` is empty, and neofetch requests `SSH_TTY` when `SSH_CONNECTION` is filled. This causes the infinite loop.

Anyway, fixed that one. Thanks for reporting.

**Comment by rkujawa** [comment]
Will there be a rebuilt RPM package?

**Comment by konimex** [comment]
I don't think so, release should be as close to upstream as possible. So you'll have to wait for 3.3.0/3.2.1.

**Comment by rkujawa** [comment]
Maybe it's a good idea to do a bugfix release then 😛 ... This could have hit a lot of users. Maybe most do not update Neofetch automatically, so they didn't notice yet.

**Comment by crankyoldbugger** [comment]
I'm having the same problem on one of my Fedora 26 machines.  Same sort of details as rkujawa described.

Just one the one machine, though, and not all connecting machines (i.e. the ones I ssh from) cause this issue.  In other words, if I try to ssh from my two Ubuntu machines (in the local LAN), one will connect and I will see the neofetch screen fine, while the other one will cause the Fedora machine to freeze halfway through drawing the neofetch details (right after the "Shell: bash 4.4.12" line).

And to further complicate things... I may have inadvertently fixed it by doing the following:

(fyi, target is Fedora 26 laptop, source is Ubuntu 17.04 desktop.)

From source Ubuntu machine, I tried to do a ssh-copy-id to copy my keys over to the target Fedora machine for passwordless login.  The process froze while neofetch was drawing the logo/details.
On the Fedora (target) machine I killed the neofetch process.
The ssh key copy continued and finished (the screen on source machine was a mess but the key copy worked).
I was then able to ssh from source to target without any neofetch issues.  It was almost as if neofetch needed the source machine to successfully connect once before it could work reliably.

Sorry if I'm not providing any useful details, but hopefully my experiences will help others....

**Comment by rkujawa** [comment]
I just wanted to add that this issue became so much of a problem for me, that I have just disabled neofetch on all my production machines, so that it does not execute anymore as a part of login process.

**Comment by konimex** [comment]
Alright, sorry for your inconveniences. Neofetch 3.3.0 has been released and has been pushed to the third-party repo in all RPM distros.

**Comment by rkujawa** [comment]
Thanks!

**Comment by crankyoldbugger** [comment]
Excellent work, konimex!

**Comment by netblues** [comment]
I'm having same issues when neofetch is enabled in .bashrc on centos8 and access is via sftp.
Process hangs.

neofetch version 7.1.0
Running it via .bash_profile seems to work as a workaround
But since so many articles out there suggest putting in in .bashrc maybe a fix is required

Regards
