### ISSUE TITLE
XTerm: Division by Zero as a result of Fallback not working

### ISSUE THREAD

**Issue by I2obiN** [dylanaraps/neofetch#761]
## Description
Using Debian 9 stable, xterm, and bash.

Noticed get_image_size() was not correctly getting font_width and font_height but getting columns and lines fine.

Basically turned out get_term_size() was not using xdotool correctly but I'm not sure how. Initial testing shows that the commands work fine on my system and assign values to a bash variable with no issue.

I'm no bash expert but I expect the issue is around lines 2407-2412 perhaps in how the height and width variables are assigned

#### Neofetch version
Neofetch 3.2.1-git

## Screenshots
![screenshot from 2017-06-30 04-23-19](https://user-images.githubusercontent.com/7683830/27719674-e408c1a6-5d4b-11e7-9ab3-e5dbb417295e.png)

**Comment by dylanaraps** [comment]
What does this display in your terminal?

```sh
printf "%b" "\033[14t"
```

**Comment by I2obiN** [comment]
Nothing unfortunately

**Comment by dylanaraps** [comment]
What about this one?

```sh
printf "%b" "\033[14t\033[c"
```

**Comment by I2obiN** [comment]
`printf "%b" "\033[14t\033[c"`

outputs

`^[[?64;1;2;6;9;15;18;21;22c`

is this why it's not falling back to xdotool?

**Comment by dylanaraps** [comment]
Yes!

I should be able to fix the issue now, thanks.

**Comment by dylanaraps** [comment]
Also, what gets printed after the prompt?

**Comment by dylanaraps** [comment]
See: 

![2017-06-30-135409_256x49_scrot](https://user-images.githubusercontent.com/6799467/27720303-2eec1f24-5d9c-11e7-9d15-bc4764d5349c.png)

**Comment by I2obiN** [comment]
My prompt ends up looking like this after the output,

`☯ kevinflynn@[encomos] ☯ 
:/usr/bin$ 64;1;2;6;9;15;18;21;22c`

**Comment by dylanaraps** [comment]
Thanks!

**Comment by dylanaraps** [comment]
Please try the latest master.

**Comment by I2obiN** [comment]
![screenshot from 2017-06-30 05-05-49](https://user-images.githubusercontent.com/7683830/27720530-dcf061b6-5d51-11e7-9947-ef2b20ed866f.png)

Working.. pretty good you could say 👍 thank you friend

**Comment by dylanaraps** [comment]
Thanks for running those commands. :)
