### ISSUE TITLE
Show GPU driver in use.

### ISSUE THREAD

**Issue by GrayJack** [dylanaraps/neofetch#766]
## Description

Some info are kinda wrong. The WM Theme is showing "Kwin.aurorae", although I'm using a aurorae theme I'm using a specific one over a lot of the aurorae themes that exist, in this case is the theme Breezemite Dark. Another issue is the Theme, it's showing "Breeze" while it should show "Breath Dark", I know, Breath and Breath Dark are variants of Breeze, but yet, it would be cool if showed the right name.

- [x] KDE wrong Theme name
- [x] WM Theme wrong 

I also have a request: to show the GTK themes even on Qt DE, a lot friends ask me about the theme I use for the compatibility layer for GTK on KDE Plasma. Another fun think to show would be the used driver for the GPU.

- [x] Show GTK Themes info on KDE
- [ ] Show driver used for GPU

## Screenshot
![screenshot_20170712_042202](https://user-images.githubusercontent.com/17973728/28106668-1d6c0264-66bb-11e7-921b-c069114eed40.png)

**Comment by mstraube** [comment]
Can you try the [kde branch](https://github.com/mstraube/neofetch/tree/kde) of my fork and report if it solves the theme issue?

**Comment by GrayJack** [comment]
Tested the Theme fix, it worked!!

**Comment by mstraube** [comment]
Thanks for testing GrayJack. 

Is the Breath Dark theme installed by default on Manjaro? I'm on Arch and installed plasma5-themes-breath from AUR, but there is no Breath Dark, just the normal one.

So I cannot set the window decoration to Breath Dark to look at the WM-Theme issue.
Can you post your `~/.config/kwinrc`?

**Comment by GrayJack** [comment]
There only one Breath desktop theme, but seems that screenfetch get it from the colour scheme where there ir a Breath and a Breath Dark

**Comment by mstraube** [comment]
Ah, ok. `WM Theme` is showing the selected window decoration, so if there is no Breath Dark decoration... 

Regarding the `Kwin.aurorae` issue: 
- What is your selected window decoration? 
- Please post your `~/.config/kwinrc`

**Comment by mstraube** [comment]
I tested some other Aurorae themes and they were all detected as `Kwin.aurorae`.

Should be fixed by: df2c85b496c4089560570ba1c204288ef2343eb9

**Comment by mstraube** [comment]
Tested some other Aurorae themes and they were all detected as `Kwin.aurorae`.
Should be fixed with: 9f5ab665c93f3d2abd289f532f38cf0c774db6e7

**Comment by GrayJack** [comment]
Here is my kwrite related to decoration:

> [org.kde.kdecoration2]
> BorderSize=Normal
> ButtonsOnLeft=XIA
> ButtonsOnRight=MFS
> CloseOnDoubleClickOnMenu=false
> library=org.kde.kwin.aurorae
> theme=__aurorae__svg__Breezemite_dark

**Comment by GrayJack** [comment]
With the latest commit, it only shows "Dark" xD
And sorry, I mistaken the name, it's Breezemite Dark

**Comment by mstraube** [comment]
Thanks.

>With the latest commit, it only shows "Dark" xD

That's because of the underscore in the theme name. 
Did not think about that possibility. :)

I'll try to find a solution that also covers such cases.

**Comment by mstraube** [comment]
Should display `Breezemite_ dark` now.

**Comment by GrayJack** [comment]
Thanks, it worked just fine now!!!

**Comment by konimex** [comment]
>The memory info are also wrong, by the time i used the neofetch i was with 2418MiB of used memory and it showed 3385MiB.

Actually, that's the correct one. [See our FAQ for more information.](https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions)

----

I merged #767, but I'm not closing this issue for this one because of the two below:

>I also have a request: to show the GTK themes even on Qt DE, a lot friends ask me about the theme I use for the compatibility layer for GTK on KDE Plasma.

In KDE, `gtk_shorthand` is hardcoded `on` by default.

>Another fun think to show would be the used driver for the GPU.

This and above depends on @dylanaraps' decision, IMO.

**Comment by GrayJack** [comment]
> Actually, that's the correct one.
Oh, I didn't know, why the shared memory are included? (i'll remove the memory then

**Comment by konimex** [comment]
Shared memory `Shmem` is actually part of `Cached` in `/proc/meminfo`. `Shmem` covers e.g. `tmpfs`, which is included in cache, but is not actually reclaimable, so it is added back to reflect the used memory.

**Comment by konimex** [comment]
Just a question since I never touched KDE, is the GTK theme on KDE different from the Qt theme?

**Comment by mstraube** [comment]
Yes, GTK2 and GTK3 themes can be configured separately.

**Comment by mstraube** [comment]
GTK config files used by Plasma 5

`~/.gtkrc-2.0`

`~/.config/gtk-3.0/settings.ini`

**Comment by dylanaraps** [comment]
I've opened #808 which implements the GTK theme output on KDE systems. Please test it and let me know if it satisfies your needs. :)

**Comment by GrayJack** [comment]
I liked it, it shows the info nicely and using the already existing info menu, unlike screenfetch the needs a new menu to show the extra info

**Comment by dylanaraps** [comment]
Awesome!

I'll merge it, thsnks for testing. :)

**Comment by dylanaraps** [comment]
I'll work on adding GPU driver support soon.

Notes:

- It will be it's own custom function.
    - This will most likely only work on Linux.
        - This requires yet another `lspci` call.
- It will be disabled by default.

**Comment by dylanaraps** [comment]
I've opened #819 which adds support for this. Please test it out!

(*You need add `info "GPU Driver" gpu_driver` to your config file.*)

**Comment by GrayJack** [comment]
It's working for me, using a HD graphics 620

**Comment by dylanaraps** [comment]
I’ve tested on AMD, we just need an NVIDIA user to test before I can merge
this. :)

**Comment by dylanaraps** [comment]
I did some googling and it should work fine for NVIDIA users too so I've merged this.

**Comment by iandrewt** [comment]
There should be a way to add GPU Driver support to macOS too, although it'd be a little less featured than the Linux one. It'd only be able to say whether it's using the built in driver or Nvidia's Web Driver (for Mac Pro and Hackintosh). I'll look into how it can be checked for in Bash tonight.
