### ISSUE TITLE
Picture scaling out of bounds (outside of terminal)

### ISSUE THREAD

**Issue by VinLark** [dylanaraps/neofetch#768]
With every image I use, the image is scaling outside of the terminal. Can I fix this or is this just the image/terminal? I saw no issue on the spreadsheet of terminals. I am using gnome-terminal. 

Version - 3.2.0

![neofetch-2017-07-12-03-03-32-2782](https://user-images.githubusercontent.com/17298607/28137613-8bd52106-6713-11e7-9962-e365b0eb074f.png)

https://gist.githubusercontent.com/VinLark/fc8cf626dd3387168b1178d386fe3bed/raw/9aa40e1e1c1efeeabed03927e5f954cc1bfd77d5/config.sh

https://gist.githubusercontent.com/VinLark/fc8cf626dd3387168b1178d386fe3bed/raw/9aa40e1e1c1efeeabed03927e5f954cc1bfd77d5/neofetchlog

Thanks

**Comment by dylanaraps** [comment]
`w3m-img` draws on-top of the window, it doesn't know where the terminal cells start/end. It just finds the window it was started from and displays an image on-top of it.

The workaround is to use the `--yoffset 000` flag to set the image offset. Example: `neofetch --w3m --yoffset 30`.

There's nothing I can do to fix this.
