### ISSUE TITLE
Ascii art not showing

### ISSUE THREAD

**Issue by iamshapeless** [dylanaraps/neofetch#769]
## Description
The ascii art is not displaying next to the stats when running the command
#### Neofetch version
2.0.2
## Screenshot
http://i.imgur.com/mufgmyR.png
## Config file
Default
## Verbose log
https://pastebin.com/n5gVWDPs

**Comment by dylanaraps** [comment]
Neofetch is on version `3.2.0`, can you update and let me know if the issue still occurs?

**Comment by iamshapeless** [comment]
> Neofetch is on version 3.2.0, can you update and let me know if the issue still occurs?
Updating solved the problem, for whatever reason neofetch is still version 2.0.2 in the stable branch for gentoo.
