### ISSUE TITLE
Neofetch showing wrong OS in info

### ISSUE THREAD

**Issue by superwhiskers** [dylanaraps/neofetch#770]
## Neofetch shows my OS as ChromeOS on Raspbian

https://i.imgur.com/xoRUNFx.png

For some reason, neofetch thinks I'm using ChromeOS
and Raspbian on my Pi at the same time.

Version: 3.2.0
Log: https://pastebin.com/1wSgQANN
Config: default

**Comment by konimex** [comment]
1. Does `/dev/cros_ec` exist on your system?
2. What is the contents of `/proc/version`?

**Comment by mstraube** [comment]
Not related to the OS issue, but I just noticed that the CPU frequency in the screenshot is 9.00GHz.
I think that's also wrong. ;)

**Comment by konimex** [comment]
Yeah that one should be 900MHz.

**Comment by superwhiskers** [comment]
/proc/version: Linux version 4.9.35-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1014 SMP Fri Jun 30 14:47:43 BST 2017

/dev/cros_ec: non-existent

**Comment by LER0ever** [comment]
**So it's because the "crosstool" string matches the "cros" ...** And I guess I'm responsible for this bug, since I wrote that check. Maybe we can find a better way to check ChromeOS with /proc/version. But a lot of _version_ file examples would be necessary to find out the common part...

My /proc/version:
```
chronos@localhost / $ cat /proc/version 
Linux version 4.4.64-09073-ga59021b1b5e2 (chrome-bot@cros-beefy132-c2) (gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_4.9.2-r154-32c89c19b042a12b5a1bf0153299154ea5435c03_4.9.2-r154) ) #1 SMP PREEMPT Fri Jun 9 03:00:11 PDT 2017
```

**Comment by superwhiskers** [comment]
You could see if all ChromeOS systems are built by the chrome-bot

**Comment by superwhiskers** [comment]
Here, this should fix it: https://pastebin.com/gstBy2y9
@LER0ever, try this on your ChromeOS box.

**Comment by LER0ever** [comment]
@superwhiskers My apologies for the late reply. That does show the correct output on my Chromebook. If you are sure that every chromebook has "chrome-bot" in kernel info and the change solves your problem, please just make a pull request changing "cros" to "chrome-bot".

**Comment by dylanaraps** [comment]
We could also change the `cros` match to match `cros-` if we're unsure about the `chrome-bot` string.

**Comment by LER0ever** [comment]
@dylanaraps from what I saw on other chromebooks, there isn't necessarily a `-` after the `cros`. What I can make sure is that on almost every Chrome OS/Chromium OS, no matter what your google account is, the username is always `chronos`. This check is accurate unless a linux user intentionally set the user name to `chronos`...

**Comment by konimex** [comment]
Snooping at PRs, bug reports and logs gives that not every Chromebook has the cros, but  do have the `chrome-bot` in their kernel builds.

Ref:
* https://github.com/dnschneid/crouton/issues/864
* https://github.com/getlantern/lantern/issues/3223#issuecomment-145200240yy
* https://gist.github.com/znuh/4041082
* https://bugs.chromium.org/p/chromium/issues/detail?id=572592#c8

**Comment by superwhiskers** [comment]
Well, I guess I should make a pull request then.

**Comment by dylanaraps** [comment]
Fixed.
