### ISSUE TITLE
DE: Issue with window mangers started via SDDM

### ISSUE THREAD

**Issue by mstraube** [dylanaraps/neofetch#772]
## Description
If I start Openbox or Fluxbox from the SDDM login manager, DE is displayed as

`DE: /usr/share/xsessions/fluxbox`
`DE: /usr/share/xsessions/openbox`

That's what is in `$DESKTOP_SESSION`

#### Neofetch version
git

## Possible  solution
change [Line 637](https://github.com/dylanaraps/neofetch/blob/1378d3b33ed68c7791149e2025c79475ad62a9f3/neofetch#L637) to:
```bash
[[ "$wm" && "$de" =~ $wm$ ]] && { unset -v de; return; }
```
But I'm not sure if using `$wm$` instead of `^$wm$` could break something else.

**Comment by dylanaraps** [comment]
Should be fixed in this commit.
