### ISSUE TITLE
Konsole detected as kdeinit4 on FreeBSD

### ISSUE THREAD

**Issue by mstraube** [dylanaraps/neofetch#791]
## Description
![bsd-konsole](https://user-images.githubusercontent.com/20053197/28715911-acf211e4-739a-11e7-8681-520141a91e2d.png)

KDE/Plasma 5 is not in the official ports collection yet.
Is it worth adding a case for this in `get_term()`? f3791469f0e16f4c74ad7fdff1e69386f13f1605

**Comment by dylanaraps** [comment]
I don't think that adding an exception for this is accurate as I'm pretty sure that you can launch any program with `kdeinit`. We're better off ignoring it and printing nothing as the emulator imo.

**Comment by mstraube** [comment]
Ok, printing nothing instead of something possibly wrong sounds reasonable. Added `kdeinit` to the ignored names.

**Comment by mstraube** [comment]
Should I open a PR for the last commit or better just leave it as is?

**Comment by dylanaraps** [comment]
Open a PR.
