### ISSUE TITLE
Hyperterm Image Support?

### ISSUE THREAD

**Issue by mike3run** [dylanaraps/neofetch#792]
![screen shot 2017-07-28 at 12 17 06 pm](https://user-images.githubusercontent.com/7088511/28728548-b0a410be-738e-11e7-8d7e-b0b055510818.png)

I think Hyper being made with html+css can handle the images right?

**Comment by dylanaraps** [comment]
Hyper doesn't support `w3m-img` as it doesn't seem to set the `WINDOW ID`. If Hyper set the window id then the `w3m` backend (`neofetch --w3m path/to/img.png`) would probably work.

Now about built-in image support for Hyper (Like iTerm2) I found some issues on Hyper's tracker about it. 

Sources:

- https://github.com/zeit/hyper/issues/101
- https://github.com/zeit/hyper/issues/258
