### ISSUE TITLE
Neofetch thinks I am running elementary OS.

### ISSUE THREAD

**Issue by Maksim112** [dylanaraps/neofetch#794]
## Description
When running neofetch it shows the icon of elementery os.
I installed elementary os(enviroment) and after that I uninstalled it and it still thinks it is running it. How do I reset it?
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
I need some more info as stated in the template you filled in.

- Verbose log
- Screenshot
- Neofetch version
