### ISSUE TITLE
Homepage suggestion - versioned archive, such as "neofetch-1.2.3.tar.gz"

### ISSUE THREAD

**Issue by shevegen** [dylanaraps/neofetch#796]
Hello Dylan,

I have a suggestion to make or a proposal or request, if you so will.

May it be possible that the project offers versioned tarball releases as well?

With an URL such as:

https://github.com/seccomp/libseccomp/releases/download/v2.3.2/libseccomp-2.3.2.tar.gz

For example, similar to this:

https://github.com/seccomp/libseccomp/releases/download/v1.2.3/neofetch-1.2.3.tar.gz

I am not sure if this is currently possible. If so, feel free to close this issue request.

I should briefly explain why I would like this.

I use scripts to automatically fetch the source of programs, and while it is possible
to use git checkouts just fine, via the v2.3.2 links and then extract, it is easier for
me to programmatically obtain the name of the program at hand and the version
it has. This is usually based on the URL, which would be nice.

I do not know how simple it is to support this; if it is too much work, just close
this issue request. Thanks for reading!

**Comment by dylanaraps** [comment]
You can already do this with regular GitHub releases.

See: 

> https://github.com/dylanaraps/neofetch/archive/3.2.0.tar.gz

This dates back all the way to the first release of `fetch`:

> https://github.com/dylanaraps/neofetch/archive/0.1.tar.gz

Page with all of the releases:

> https://github.com/dylanaraps/neofetch/releases

**Comment by konimex** [comment]
If you need the `$name-$version` format, you can use

> https://github.com/dylanaraps/neofetch/archive/<version>/neofetch-<version>.tar.gz

We don't need separate tarballs because unlike `libseccomp`, we don't use GNU Autoconf so we don't have to generate `./configure`.
