### ISSUE TITLE
Display virtualization information

### ISSUE THREAD

**Issue by timkgh** [dylanaraps/neofetch#798]
## Description

Display if the host is actual hardware or a VM, and if VM which hypervisor is used, something like this (from Linux):

```
$ hostnamectl
   Static hostname: myvm
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a3105...
           Boot ID: eef0be...
    Virtualization: kvm
  Operating System: Ubuntu 16.04.3 LTS
            Kernel: Linux 4.10.0-28-generic
      Architecture: x86-64
```

**Comment by konimex** [comment]
`hostnamectl` is a part of systemd, so we'll need an alternative (or figure out how systemd get it).

IIRC, (at least for Linux) VirtualBox already identifies it in their `/sys/devices/virtual/dmi/id/product_{name,version}`.

**Comment by dylanaraps** [comment]
Doesn't the `Model:` function print the virtualization information (*as a side-effect but it works*)?

From what I've seen it supports: `VirtualBox`, `VMWare` and `Google Compute Engine`. 

If we can test with other VM software and it does indeed work then adding an extra function isn't really necessary. We could change the default subtitle from `Model:` to `Host:` to more accurately portray the output.

**Comment by timkgh** [comment]
It doesn't for KVM, it shows something like:
`Model: Standard PC (i440FX + PIIX, 1996)`

**Comment by dylanaraps** [comment]
Googling that output tells me that it's specific to `KVM` \[1\]. We should be able to safely assume that `Standard PC*` --> `KVM/QEMU`.

\[1\] https://www.google.com.au/search?q=Standard+PC+%28i440FX+%2B+PIIX%2C+1996%29&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=GZSTWYHQPIrp8weL06n4Cg

**Comment by dylanaraps** [comment]
Also, this `qemu` command (`qemu-system-x86_64 -machine help`) shows all of the possible values for the `Model:` output:

```sh
~ ily qemu-system-x86_64 -machine help
Supported machines are:
pc                   Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-2.9)
pc-i440fx-2.9        Standard PC (i440FX + PIIX, 1996) (default)
pc-i440fx-2.8        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.7        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.6        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.5        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.4        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.3        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.2        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.1        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-2.0        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.7        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.6        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.5        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-1.4        Standard PC (i440FX + PIIX, 1996)
pc-1.3               Standard PC (i440FX + PIIX, 1996)
pc-1.2               Standard PC (i440FX + PIIX, 1996)
pc-1.1               Standard PC (i440FX + PIIX, 1996)
pc-1.0               Standard PC (i440FX + PIIX, 1996)
pc-0.15              Standard PC (i440FX + PIIX, 1996)
pc-0.14              Standard PC (i440FX + PIIX, 1996)
pc-0.13              Standard PC (i440FX + PIIX, 1996)
pc-0.12              Standard PC (i440FX + PIIX, 1996)
pc-0.11              Standard PC (i440FX + PIIX, 1996)
pc-0.10              Standard PC (i440FX + PIIX, 1996)
q35                  Standard PC (Q35 + ICH9, 2009) (alias of pc-q35-2.9)
pc-q35-2.9           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.8           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.7           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.6           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.5           Standard PC (Q35 + ICH9, 2009)
pc-q35-2.4           Standard PC (Q35 + ICH9, 2009)
isapc                ISA-only PC
none                 empty machine
```

**Comment by dylanaraps** [comment]
The model function (*renamed to `Host:`*) now supports displaying KVM/QEMU information.

**Comment by dylanaraps** [comment]
Closing this as `get_model` now displays the virtualization information for `VirtualBox`, `VMWare`, `QEMU/KVM` and `Google Compute Engine`. I don't have the time to install `Xen`, `bochs` or other virtualization software to test if this works in them or not.
