### ISSUE TITLE
Bug: Resolution output

### ISSUE THREAD

**Issue by lexruee** [dylanaraps/neofetch#803]
**Problem:**
As pointed out by @konimex in the pull-request https://github.com/dylanaraps/neofetch/pull/801, there seems to be a minor issue in the resolution output. In short, the resolution output is odd. It does not correctly print the resolution.

Since the commit 688bcd6e5534ff8ef08aa72b60092ba32d48fc25 I get the following output from neofetch: 

![neofetch-resolution2](https://user-images.githubusercontent.com/649340/29242652-f607bb3e-7f90-11e7-9234-af173c7aa68b.png)

In contrast, in the previous commit e9f491656e2a0a2c93eb5f18395253a91f4e11f3, I get the following output from neofetch: 
![neofetch-resolution1](https://user-images.githubusercontent.com/649340/29242650-f0dd755e-7f90-11e7-942c-bce71641307d.png)

I hope this helps to solve the issue :smile:. As the screenshots show I run Debian Sid so I'm used to bugs^^.

**Comment by konimex** [comment]
Please provide the verbose log.

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by lexruee** [comment]
I uploaded the output to the debian paste service:
http://paste.debian.net/981088/

**Comment by dylanaraps** [comment]
Can you upload the output from `xrandr --nograb --current`?  It'll help to compare it with the output of my machine and others.

**Comment by lexruee** [comment]
Here is the output of `xrandr --nograb --current` (or see [here](http://paste.debian.net/981155/)):
```
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
eDP-1 connected (normal left inverted right x axis y axis)
   1920x1080     60.02 +  59.93  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1280x1024     60.02  
   1440x900      59.89  
   1280x960      60.00  
   1360x768      59.80    59.96  
   1152x864      60.00  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   960x600       60.00  
   960x540       59.99  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   800x512       60.17  
   700x525       59.98  
   640x512       60.02  
   720x450       59.89  
   640x480       60.00    59.94  
   680x384       59.80    59.96  
   576x432       60.06  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
DP-2-1 disconnected (normal left inverted right x axis y axis)
DP-2-2 disconnected (normal left inverted right x axis y axis)
DP-2-3 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
```

The version of `xrandr` is 1.5.0, as shown below:
```
xander@xonix:~$ xrandr --version
xrandr program version       1.5.0
Server reports RandR version 1.5

```

I guess the problem is my display configuration :smile:.

**Comment by dylanaraps** [comment]
Fixed. :)
