### ISSUE TITLE
OS display value for SUSE Linux Enterprise Server

### ISSUE THREAD

**Issue by bwgartner** [dylanaraps/neofetch#807]
## Description

Due to the length of string output for distro plus arch - "**OS: SUSE Linux Enterprise Server 12 SP**3 x86_6**4**" this gets unfortunately cropped/trimmed (on an 80x24 default terminal) to "OS: SUSE Linux Enterprise Server 12 SP4". This is confusing, given the release naming by SUSE of incrementing SP#s over time for a given major release (12, in this case). This can currently be worked around with a wider terminal or by turning off os_arch.

#### Neofetch version

neofetch --version : 3.2.1-git
(used from packaged at https://build.opensuse.org/package/show/utilities/neofetch as neofetch-3.2.0+git20170813)

## Screenshot

![neofetch-sle](https://user-images.githubusercontent.com/2212000/29349053-ebd9ee1c-8214-11e7-9863-b171796db6ee.png)

## Config file

no changes from default

## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.
https://pastebin.com/aXfHjH0x

**Comment by dylanaraps** [comment]
I've pushed a change to remove `Enterprise Server` from the output. The line should now fit.
