### ISSUE TITLE
Can't display image with w3m-img and Terminator

### ISSUE THREAD

**Issue by PrimordialHelios** [dylanaraps/neofetch#809]
## Description

Attempting to display an image with w3m-img in Terminator displays emptiness where the picture should be.

#### Neofetch version

3.2.0

## Screenshot

![screenshot_2017-08-17_02-04-10](https://user-images.githubusercontent.com/8160403/29398088-6223305c-82f0-11e7-99b5-b96a20063537.png)

## Config file

https://pastebin.com/RRnMJtck

## Verbose log

https://pastebin.com/TZXFRLNR

**Comment by dylanaraps** [comment]
There's nothing I can do to fix this, it's an issue with Terminator and w3m-img.

See this list of compatible terminals: https://github.com/dylanaraps/neofetch/wiki/Images-in-the-terminal#terminal-emulator

**Comment by PrimordialHelios** [comment]
Ah, seems I misunderstood that list. Thanks anyway!
