### ISSUE TITLE
No output on Raspberry Pi 1

### ISSUE THREAD

**Issue by CallumHoward** [dylanaraps/neofetch#812]
## Description
After running `neofetch` there is no output.
I am on a Raspberry Pi 1, running Raspbian.
TERM=screen-256color

`screenfetch` works as expected.

#### Neofetch version
Installed with LinuxBrew:
```
stable 3.2.0, HEAD
Built from source on 2017-08-21 at 09:13:24
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/neofetch.rb
```

## Config file
I am not using any config.

## Verbose log
https://gist.github.com/CallumHoward/518657780eb078fcd083ca2b11f18c24

**Comment by dylanaraps** [comment]
You haven't installed Neofetch correctly (*You can't just drop `neofetch` in `/bin` and expect it to work.*). The log file tells me that Neofetch can't find any of the files it needs to function (*Config file, ascii files etc*).

**Comment by konimex** [comment]
Because you're using Linuxbrew, you need to copy the default config file manually as Neofetch cannot detect the default config file. This should be fixed in the next Neofetch release.

Try `cp $(brew --prefix)/etc/neofetch/config $HOME/.config/neofetch/config`.

**Comment by CallumHoward** [comment]
@konimex Thanks, that mostly worked. It doesn't display the ascii logo however, even though I have verified that it is located in `/home/linuxbrew/.linuxbrew/Cellar/neofetch/3.2.0/share/neofetch/ascii/distro/raspbian`.

From the verbose log, it appears it is looking in the wrong folder:
`/home/linuxbrew/.linuxbrew/Cellar/neofetch/3.2.0/bin/ascii/distro/raspbian`

new log is here: https://gist.github.com/CallumHoward/4511e1a2adcc1c1676bbd5496a58bccf

**Comment by konimex** [comment]
Same problem with earlier (solved in the git version), but use a workaround for the time being.

Set the `image_source` manually, either by setting it in the config file, or enable the flag by running `neofetch --image_source /home/linuxbrew/.linuxbrew/Cellar/neofetch/3.2.0/share/neofetch/ascii/distro/raspbian`.

**Comment by CallumHoward** [comment]
It worked with the `--source` flag, thanks.

One other interesting thing to mention: I tried `brew reinstall neofetch --HEAD`, however this failed with the following output:

```
==> Reinstalling neofetch
==> Cloning https://github.com/dylanaraps/neofetch.git
Cloning into '/home/pi/.cache/Homebrew/neofetch--git'...
remote: Counting objects: 150, done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 150 (delta 0), reused 68 (delta 0), pack-reused 0
Receiving objects: 100% (150/150), 79.22 KiB | 0 bytes/s, done.
Checking connectivity... done.
==> Checking out branch master
Error: inreplace failed
Makefile:
  expected replacement of "$(DESTDIR)/etc" with "$(DESTDIR)$(SYSCONFDIR)"
```

This also occurred when manually uninstalling and then installing again. The git repo in `.cache/...` appears to be checked out on master, so I guess it's an error with the brew recipe.
I tried the same thing on macOS with the same result.

**Comment by konimex** [comment]
The Makefile has since changed from 3.2.0 so the brew Formula failed to patch the HEAD version of the Makefile.

Anyway, I'm closing this since the fix is upstream and the workaround has been provided.
