### ISSUE TITLE
Possible bug with OS detection on Gentoo

### ISSUE THREAD

**Issue by yyualice** [dylanaraps/neofetch#822]
## Description

Neofetch does not print the Gentoo logo and incorrectly includes `NAME=` in the OS' name field. Could be an issue with my system as I don't recall if I've updated Neofetch and it was working correctly some time ago. Tried unmerging and re-emerging Neofetch.

#### Neofetch version
` neofetch-2.0.2 `
## Screenshot
![](http://i.imgur.com/MUNegX1.png)
## Config file
Default config.
## Verbose log
See screenshot.

## neofetchlog
https://pastebin.com/CKBJ0Zfp

**Comment by konimex** [comment]
Try to update neofetch to the latest version. For some reason my request to stabilize 3.2 (or 3.1 iirc) to gentoo is not accepted yet.

**Comment by yyualice** [comment]
The issue persists. I  unmerged the previous version and emerged the latest, being 3.2.

![](http://i.imgur.com/83BENf9.png)

**Comment by dylanaraps** [comment]
What's the output of these commands?:

- `cat /etc/os-release`
- `cat /etc/gentoo-release`

**Comment by dylanaraps** [comment]
Can you do `source /etc/os-release` in your shell and let me know if any errors occur?

**Comment by yyualice** [comment]
It executed silently without error.

**Comment by dylanaraps** [comment]
Try the latest master and let me know if the issue is fixed.

**Comment by yyualice** [comment]
Fixed on the latest commit. Thanks Dylan!
![](https://i.imgur.com/5BF1yTH.png)

**Comment by sillen102** [comment]
Having the same issue with neofetch 3.3.0.

![bild](https://user-images.githubusercontent.com/11628578/38019983-5fd7a48e-3279-11e8-8524-687c49a17805.png)

![bild](https://user-images.githubusercontent.com/11628578/38020007-742e30e2-3279-11e8-978d-097782809c98.png)

![bild](https://user-images.githubusercontent.com/11628578/38020021-80230f80-3279-11e8-8f96-4b31bd55e796.png)

**Comment by BANANMANX47** [comment]
@sillen102 Hello I had the same issue as you, I solved it by emerging "=app-misc/neofetch-9999" instead. This is already written in here but if you dont know about "master" or 9999 packages the wording might be a bit unclear so I hope this helps you or future internet searchers.
