### ISSUE TITLE
Text overflow onto image

### ISSUE THREAD

**Issue by rogerogden** [dylanaraps/neofetch#826]
## Description

When I run the executable, parts of the system information seems to be wrapping prematurely and being written onto my wallpaper.

#### Neofetch version
3.2.0

## Screenshot
![screen shot 2017-09-15 at 1 06 52 pm](https://user-images.githubusercontent.com/5980704/30499250-f367bad2-9a16-11e7-9367-448a84bb0508.png)

## Config file
[Pastebin](https://pastebin.com/nJV72c7A)

## Verbose log

[Pastebin](https://pastebin.com/iR2Nhdyv)

**Comment by dylanaraps** [comment]
- Does this happen everytime you run neofetch?
- Does it occur at other window sizes?
- Does it occur in ascii mode?

**Comment by yyualice** [comment]
I've encountered this in specific cases in the past, and simply adding a blank line:
`neofetch && echo "\n"`
Will output an extra blank line and should fix the issue.

**Comment by dylanaraps** [comment]
Also, does this issue occur in the latest release? I think this issue was fixed. (`3.3.0`)

**Comment by rogerogden** [comment]
Hi @dylanaraps, sorry I'm so late getting back to you. I was away from my laptop for the weekend.

- Yes, this happens every time I run neofetch. 
- Yes, it occurs at other window sizes
- No, it does not appear to happen while in ascii mode.

@yyualice's recommendation did not work for me, either.

**Comment by rogerogden** [comment]
Also, I am installing `neofetch` via `brew`. The latest version on there is 3.2.0. I'll search out 3.3.0.

**Comment by dylanaraps** [comment]
Have you tried the latest git master (*or the latest release*)?

You can follow these instructions: https://github.com/dylanaraps/neofetch/wiki/Installation#latest-git-master-bleeding-edge

(*Closing this as I'm sure it was fixed in master.*)
