### ISSUE TITLE
Renaming 'Fetch'

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#83]
We should rename Fetch to something that makes us stand out more, 
there are already multiple programs that share the same name as us
and we're pretty hard to find in a google search or github search.

I created this issue to ask for your ideas and suggestions to what we
should rename the script to. 

Thanks to @z1lt0id for coming up with the idea.

Possible names I've come up with:

- neofetch (Next gen fetch)
- fetchy
- sf

Here's the poll:

http://strawpoll.me/6894425

Here are the results:

http://strawpoll.me/6894425/r

**Comment by tudurom** [comment]
Nufetch → alternative screen*fetch*

**Comment by tudurom** [comment]
(read newfetch)

**Comment by ix** [comment]
`ft`

while it may seem somewhat too simple, lots of standard unix tools are named in this manner

**Comment by z1lt0id** [comment]
@ix I like that use - how very suckless of you :)

**Comment by dylanaraps** [comment]
Wouldn't we be even harder to find in searches with that name?

**Comment by z1lt0id** [comment]
Yeah it would be, i do like neofetch though. Reminds me of neovim, etc.

**Comment by dylanaraps** [comment]
Yup, that's where I got the idea from.

**Comment by z1lt0id** [comment]
nufetch reminds me too much of nu-metal. ;)

**Comment by dylanaraps** [comment]
I'll wait for some more submissions and then make a poll so that
we can all vote on the new name.

**Comment by z1lt0id** [comment]
I was gonna say *nixfetch

**Comment by tudurom** [comment]
Fetch also supports Windows.

**Comment by dylanaraps** [comment]
We support Windows through Cygwin which creates a *nix environment. So it's technically correct. :)

**Comment by z1lt0id** [comment]
@tudurom That maybe hypothetically true, but you cannot run it purely natively under Windows.  You still have to run it under cygwin which gives Windows the ability to run a POSIX environment to run these application.  So it is still *NIX :)

**Comment by tudurom** [comment]
Another idea derived from "neofetch": novofetch (or novafetch). "Novo" (or "nova") means "new" in Bulgarian. I think fetch should not be renamed to neofetch because the majority of users are ricers and many of them may know about neovim, so novofetch is more original.

**Comment by tudurom** [comment]
It seems "novo" means "new" also in Portuguese.

**Comment by dylanaraps** [comment]
`neo` also means `young`, `new` in Greek.

**Comment by tudurom** [comment]
I know. That's why I choose novo: it means the same thing.

**Comment by mclado** [comment]
What about syfetch, like "system fetch"?

**Comment by xDemonessx** [comment]
I was thinking something along the lines of "img-fetch", but that could also be misleading and people might think its some kind of image downloading script... what is standoutish about it already (obviously) is the image functionality as well as color script capabilities.

wall-fetch? scene-fetch?

**Comment by dylanaraps** [comment]
The name doesn't have to include `fetch` at all, it can be entirely different.
What I'll do is create a straw poll  and let you guys vote on which name we
should use.

**Comment by dylanaraps** [comment]
Here's the poll:

http://strawpoll.me/6894425

Here are the results:

http://strawpoll.me/6894425/r

**Comment by dylanaraps** [comment]
It looks like `neofetch` is the clear winner, should we also rename the executable 
or should we leave it as `fetch`?

**Comment by z1lt0id** [comment]
I'll rename it as neofetch

On 27 February 2016 5:34:46 pm AEDT, Dylan Araps <notifications@github.com> wrote:
>It looks like `neofetch` is the clear winner, should we also rename the
>executable 
>or should we leave it as `fetch`?
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dylanaraps/fetch/issues/83#issuecomment-189585592

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dylanaraps** [comment]
The rename is complete on my end, the aur package has also been renamed. 

@z1lt0id and @ix, jsut a reminder that you need to also rename your packages.

**Comment by z1lt0id** [comment]
done

**Comment by dylanaraps** [comment]
Thanks :+1:

**Comment by dylanaraps** [comment]
The rename is complete everywhere afaik so I'm closing this.

**Comment by mclado** [comment]
So we are leaving two folders in .config for now, like neofetch and fetch? Because I removed it and tried installing again.

**Comment by dylanaraps** [comment]
Neofetch no longer looks for `.config/fetch/config` it instead looks for `.config/neofetch/config`.
It would also be unwise to delete the old config and it should be left up to the user.
