### ISSUE TITLE
Add gif support in neofetch

### ISSUE THREAD

**Issue by black4t** [dylanaraps/neofetch#830]

**Comment by dylanaraps** [comment]
I've thought about this and it's pretty useless no? Neofetch is typically used in screenshots (where gifs become images).

**Comment by hpjansson** [comment]
neofetch has an optional dependency on Chafa, which already has more featureful GIF animation support than gif-for-cli. Just in case you want to support this after all.

**Comment by akaia-shadowfox** [comment]
> I've thought about this and it's pretty useless no? Neofetch is typically used in screenshots (where gifs become images).

No, it's not :)
bump

**Comment by XenoWad01** [comment]
I would also appreciate this. Its not just about the screenshots, it's also about the experience.

**Comment by pnydiffuser** [comment]
I too have a use for gif in neofetch
