### ISSUE TITLE
Kernel info not showed on freeBSD

### ISSUE THREAD

**Issue by GrayJack** [dylanaraps/neofetch#831]
## Description
Kernel info not showed on freeBSD

#### Neofetch version
Latest master commit

## Screenshot
![screenshot_2017-09-21_03-02-31](https://user-images.githubusercontent.com/17973728/30681075-e04648a8-9e79-11e7-9dc3-dd90502b4806.png)

## Config file
https://up1.secretalgorithm.com/#NW9VaJw69fFwpFWRgLP3Cg

**Comment by konimex** [comment]
This is an intended behavior since in FreeBSD, kernel version = OS version. To show kernel version, set your `distro_shorthand` to `on` or `tiny`.

**Comment by GrayJack** [comment]
But what about the freeBSD based distributions, like ghostBSD, midnightBSD, etc that have the OS name different but still uses the freeBSD kernel?

**Comment by konimex** [comment]
Shouldn't be affected, unless the kernel is `MidnightBSD` or `GhostBSD` respectively.

The `get_kernel` function only does the thing when the distro name matches the kernel name.

**Comment by GrayJack** [comment]
I see, nice feature, so that exaplains the same behaviour on ghostBSD, they forgotten to change the OS name and version, thanks!!!
