### ISSUE TITLE
Add album variable to Song feature

### ISSUE THREAD

**Issue by KamranMackey** [dylanaraps/neofetch#836]
If possible, I would appreciate it if an album variable was added to neofetch's Song feature instead of just having the "Song" and "Artist" variables. The Album variable could be a separate setting one could toggle, or it could be part of the song shorthand toggle being set to "on". It's always nice if the album name is displayed, at least to me, so I would really appreciate it if this was added.

**Comment by iandrewt** [comment]
I'll figure out how this can be done for each of the music players we support. Which music player do you use? I'll do that one first (if it provides that information)

**Comment by KamranMackey** [comment]
@iandrewt I use Spotify, and cmus for local files.

**Comment by iandrewt** [comment]
Can you send the output of these two commands? I don't use either of those but I'll be able to add support using the output of these commands. You'll need to be playing music for it to work I think

cmus: `cmus-remote -Q`

Spotify: `dbus-send --print-reply --dest=org.mpris.MediaPlayer2."${1}" /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`

**Comment by KamranMackey** [comment]
@iandrewt Here you go: https://gist.github.com/KamranMackey/bbb7f69a17374a3767065f0d7bc498bd

**Comment by KamranMackey** [comment]
Hopefully that is good enough, I actually converted the gist to Markdown instead of just plain-text to try and make it look nicer.

**Comment by konimex** [comment]
Since most (dbus-enabled) music players use the same D-Bus spec (MPRIS), it should suffice to just add `album` to the `dbus-send` command.

**Comment by KamranMackey** [comment]
@konimex That would work, you would just have to add I think the /album/ variable to the last awk command in the `song` variable in the `get_song_info() function and somehow add it to the song statement at the end of `get_song()`, where the "artist" and "song" variables are located.
