### ISSUE TITLE
w3m image overlays onto other terminal tabs in same window

### ISSUE THREAD

**Issue by Wintermote** [dylanaraps/neofetch#841]
## Description
Using w3m to display an image instead of an ascii logo for the distro causes display issues when switching tabs.

This may be related to the 'loop' feature to ensure an image properly displays.

How to replicate:
1. Configure neofetch to display an image instead of an ascii logo, and to loop the image
2. Open a terminal
3. Open a second tab in the terminal
4. Run 'neofetch' in the first tab
5. Switch to the second tab

Result: image partially renders on top of second tab
Expected result: image does not render over second tab

#### Neofetch version
3.3.0

## Screenshot
Tab 1 running neofetch: https://i.imgur.com/GBT9J3Z.png
Tab 2, not running neofetch: https://i.imgur.com/KhvjYb3.png

Neofetch is displaying the image from tab 1, onto tab 2

Image being used: https://i.imgur.com/MHxsUaU.png

## Config file
https://pastebin.com/jZVLzu9j

## Verbose log
https://pastebin.com/sNiYuXQs

**Comment by Wintermote** [comment]
Just to clarify: My terminal is configured not to display tab bars or the menu, which is why neither screenshot shows multiple tabs anywhere. There are multiple tabs - but the bar showing how many I have and what they are named is just not being displayed.

In the Tab 2 screenshot, you can see that the image covers the majority of my prompt. In the Tab 1 screenshot there is no prompt as neofetch is running with the image 'loop' argument.

**Comment by dylanaraps** [comment]
This is due to how `w3m-img` works. It uses a hack to draw on-top of the window, it doesn't use nor even know about the terminal, cells etc. 

Closing this as it's not a `neofetch` issue.
