### ISSUE TITLE
Neofetch is not displaying Wallpaper

### ISSUE THREAD

**Issue by mananapr** [dylanaraps/neofetch#843]
#### Neofetch version
Neofetch 3.3.0

### Config file
https://p.teknik.io/lp17V

### Verbose log
https://p.teknik.io/K0KO9

### Problem

```neofetch --source /path/to/image``` works but ```neofetch --source wallpaper``` doesn't. 
In the logs, it shows ```Image: 'wallpaper' doesn't exist, falling back to ascii mode```

**Comment by dylanaraps** [comment]
The verbose log tells me that your `~/.fehbg` file doesn't contain the correct information. This causes neofetch to fallback to checking for ascii files before finally using distro ascii.

What's the output of `cat ~/.fehbg`?

**Comment by mananapr** [comment]
`cat .fehbg `
#!/bin/sh
'feh' '--bg-fill' '/home/manan/Pictures/Washed-2/S7UyYDp.jpg'

**Comment by dylanaraps** [comment]
Does ‘neofetch --config off --w3m’ work?

**Comment by mananapr** [comment]
I tried:
`neofetch --config off --w3m ~/Pictures/Washed-2/S7UyYDp.jpg`
and it works

**Comment by dylanaraps** [comment]
I just did some testing with your config file and this issue was already fixed sometime in the git version.
