### ISSUE TITLE
[MacOS] Showing wrong Window Manager

### ISSUE THREAD

**Issue by Electrux** [dylanaraps/neofetch#847]
## Description

Neofetch shows kwm as my window manager on Mac OS when it actually is the default one - Quartz Compositor. I am not able to find the cause of it though.

#### Neofetch version

3.3.0

## Screenshot

https://imgur.com/a/nCJ5Q

## Config file

Default one.

## Verbose log

https://pastebin.com/ipZWaJ3M

**Comment by iandrewt** [comment]
This has already been fixed with #834

**Comment by Electrux** [comment]
oh ok thanks :)
