### ISSUE TITLE
Wrong temperature on AMD platform

### ISSUE THREAD

**Issue by AlienKnuckle** [dylanaraps/neofetch#848]
Neofetch (3.3.0) print GPU temp instead of CPU on AMD platform.
Temp of CPU at the time of screenshot was 53.5°C.

CPUTIN: +53.5°C  (high = +80.0°C, hyst = +75.0°C)

amdgpu-pci-0100
Adapter: PCI adapter
fan1:         801 RPM
temp1:        +59.0°C

![screenshot from 2017-10-19 18-41-47](https://user-images.githubusercontent.com/31382035/31778655-bcacf2c0-b4e0-11e7-9aff-a33962e26363.png)

**Comment by dylanaraps** [comment]
Does this command output the correct temp?

```sh
echo "$(($(< /sys/class/hwmon/hwmon1/temp1_input) * 100 / 10000))"
```

Note: The output will be 3 digits. Example: `278` --> `27.8C`

**Comment by konimex** [comment]
Just curious here, but what's the output/name of `/sys/class/hwmon/hwmon0/name` and `/sys/class/hwmon/hwmon1/name` respectively?

**Comment by AlienKnuckle** [comment]
The output of "echo "$(($(< /sys/class/hwmon/hwmon1/temp1_input) * 100 / 10000))"" is 10.6°C, I checked with lm_sensors and I think it belong to FCH (south chipset)

k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +10.8°C

bash-4.4$ cat /sys/class/hwmon/hwmon0/name
amdgpu
bash-4.4$ cat /sys/class/hwmon/hwmon1/name
k10temp

**Comment by dylanaraps** [comment]
Do you have any other `hwmon` numbers? Does the `name` file of any additional files list the CPU name  (*or anything related to it*)?

**Comment by AlienKnuckle** [comment]
bash-4.4$ sensors
nct6791-isa-0290
Adapter: ISA adapter
Vcore:                  +0.94 V  (min =  +0.00 V, max =  +1.74 V)
in1:                    +1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:                   +3.33 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:                  +3.33 V  (min =  +2.98 V, max =  +3.63 V)
in4:                    +1.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                    +2.04 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                    +0.30 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:                   +3.38 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:                   +3.31 V  (min =  +2.70 V, max =  +3.63 V)
in9:                    +0.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                   +0.18 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                   +0.18 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                   +1.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                   +1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                   +0.22 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                   553 RPM  (min =    0 RPM)
fan2:                  1231 RPM  (min =    0 RPM)
fan3:                   571 RPM  (min =    0 RPM)
fan4:                   543 RPM  (min =    0 RPM)
fan5:                  1273 RPM  (min =    0 RPM)
SYSTIN:                 +34.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
CPUTIN:                 +41.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor  <===  CPU
AUXTIN0:                +99.0°C    sensor = thermistor
AUXTIN1:                +96.0°C    sensor = thermistor
AUXTIN2:                +97.0°C    sensor = thermistor
AUXTIN3:                +99.0°C    sensor = thermistor
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
PCH_CHIP_TEMP:           +0.0°C  
PCH_CPU_TEMP:            +0.0°C  
PCH_MCH_TEMP:            +0.0°C  
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled

fam15h_power-pci-00c4
Adapter: PCI adapter
power1:           N/A  (crit =  94.91 W)

amdgpu-pci-0100
Adapter: PCI adapter
fan1:         804 RPM
temp1:        +53.0°C  (crit =  +0.0°C, hyst =  +0.0°C)  <===  GPU

asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

k10temp-pci-00c3
Adapter: PCI adapter
temp1:         +7.1°C  (high = +70.0°C)  <===  FCH?
                       (crit = +80.0°C, hyst = +79.0°C)

**Comment by AlienKnuckle** [comment]
bash-4.4$ cat /sys/class/hwmon/hwmon2/name
fam15h_power
bash-4.4$ cat /sys/class/hwmon/hwmon3/name
asus
bash-4.4$ cat /sys/class/hwmon/hwmon4/name
nct6791

**Comment by dylanaraps** [comment]
Fixed in https://github.com/dylanaraps/neofetch/commit/8540a2f1e30a1233aca663bf23ebb5141630f4d6
