### ISSUE TITLE
Wrong GPU name. AMD Curacao XT instead of RX 270X

### ISSUE THREAD

**Issue by Lladdmi** [dylanaraps/neofetch#849]
# Desctiption
neofetch showing wrong GPU name. AMD Curacao XT instead of RX 270X

## Version
3.3.0

## Screenshot
![zrzut ekranu z 2017-10-21 16-55-36](https://user-images.githubusercontent.com/26869550/31852947-bbc3d8fa-b680-11e7-9e5e-7ebcee47829d.png)

## Config file
Default confing (I just added local IP address)

## Verbose log
https://pastebin.com/UCwPcf2u

**Comment by dylanaraps** [comment]
Does this solve the issue?

https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linuxfreebsd-why-does-getgpu-doesnt-show-my-exact-video-card-name

**Comment by konimex** [comment]
In the logs, lspci actually picked up the right name:

`'Advanced Micro Devices, Inc. Curacao XT / Trinidad XT [Radeon R7 370 / R9 270X/370X]'`

For some reason the function decided to strip out whatever comes after `Curacao XT`.
