### ISSUE TITLE
No locale detected in Neofetch

### ISSUE THREAD

**Issue by Fred6681** [dylanaraps/neofetch#851]
## Description
The text is in english, we can not add the modification of locale in the config file?
or then detected them directly from the system

_(Sorry for my bad english)_

#### Neofetch version
version: 3.3.0 (archlinux - AUR)

## Screenshot
![capture du 2017-10-27 14-37-43](https://user-images.githubusercontent.com/6896497/32104469-da763484-bb24-11e7-8000-5efa32d1f59e.png)

## Config file
https://pastebin.com/f8e33kev

**Comment by konimex** [comment]
It's going to be hard to use per-language settings in the sections you circled, because the function to display uptime and month has been hardcoded to use `hours` `mins` and the English day and months respectively.

**Comment by dylanaraps** [comment]
It'll be overly complicated and slow to try and support separate locales in bash anyway.
