### ISSUE TITLE
No transparency in terminal for png image

### ISSUE THREAD

**Issue by Fred6681** [dylanaraps/neofetch#852]
## Description
In a transparent terminal the transparency of a png image is not displayed

#### Neofetch version
version: 3.3.0 (archlinux - AUR)

## Screenshot
![capture du 2017-10-27 15-03-36](https://user-images.githubusercontent.com/6896497/32105248-17b5aac0-bb28-11e7-96f1-3b1a6ee93506.png)

#### Original` image
![archlinux-logo](https://user-images.githubusercontent.com/6896497/32105290-3b2fedd0-bb28-11e7-9895-d0383d794d1a.png)

## Config file
https://pastebin.com/f8e33kev

## Verbose log
https://pastebin.com/sVzP8xBC

**Comment by dylanaraps** [comment]
I can't reproduce this on my machine. Does it occur in all terminal emulators or only MATE-terminal?

![2017-10-28-09-51-59](https://user-images.githubusercontent.com/6799467/32127763-d6b06630-bbc4-11e7-82e0-0c5a837fa418.png)

**Comment by Fred6681** [comment]
After testing, it looks like it's the same with xfce4-terminal
![xfce4](https://user-images.githubusercontent.com/6896497/32129037-8cad8856-bb83-11e7-8ba3-af76a8cf35b1.png)

and the problem and the same with konsole
![konsole](https://user-images.githubusercontent.com/6896497/32129066-bdea1ca4-bb83-11e7-9664-bb9c87296304.png)

with gnome-terminal it does the same but the image disappears almost instantly
