### ISSUE TITLE
Problem with the system font display

### ISSUE THREAD

**Issue by Fred6681** [dylanaraps/neofetch#853]
## Description
on KaOs the font display of the system looks odd

#### Neofetch version
3.3.0 
build from the Arch-Linux AUR package with this method :
https://kaosx.us/docs/package/#aur

## Screenshot
![screenshot_20171028_161215](https://user-images.githubusercontent.com/6896497/32135180-1316833a-bbfb-11e7-9dd1-45af00f7006c.png)
![screenshot_20171028_162259](https://user-images.githubusercontent.com/6896497/32135244-5b7721f6-bbfc-11e7-8199-7c4850462f6a.png)

## Config file
https://pastebin.com/2ZAjqUVU
## Verbose log
https://pastebin.com/K28qwTaS

**Comment by dylanaraps** [comment]
I can't reproduce this in the latest version.
