### ISSUE TITLE
Not working on my server

### ISSUE THREAD

**Issue by myopenflixr** [dylanaraps/neofetch#854]
## Description

Neofetch only works when I run the command "neofetch' from command line. I have uninstalled and reinstalled serveral times with no luck.

I have another ubuntu test server that I installed neofetch on and it works perfectly every time I log in to my terminal via puTTY.

I cannot get this to work on my main server and have no idea why.

#### Neofetch version
3.3.0

## Config file
This config file only got written to my /home/userdirectory/.config/neofetch directory AFTER I ran the command neofetch from a command prompt.

https://pastebin.com/21VT8zcz

## Verbose log
https://pastebin.com/b3BtXi3r

**Comment by dylanaraps** [comment]
Based on the log file you've given me, Neofetch is working correctly.
