### ISSUE TITLE
FreeBSD 12-CURRENT detected on TrueOS

### ISSUE THREAD

**Issue by cubedev2539** [dylanaraps/neofetch#855]
## Description
I have a newly installed version of the latest TrueOS Stable, but when Neofetch is run it detects FreeBSD 12.0-CURRENT. As far as I know TrueOS already seems to have support in Neofetch separate from FreeBSD.

#### Neofetch version
Neofetch 3.3.0
## Screenshot
![screenshot-2017-10-31-04-19-56](https://user-images.githubusercontent.com/11370809/32207526-2891c5b2-bdc2-11e7-84fb-4b9379b4ffdd.png)
## Config file
Used the default config, still pasted in a text file for reference:
[config.conf.txt](https://github.com/dylanaraps/neofetch/files/1429608/config.conf.txt)
## Verbose log
https://pastebin.com/mJWuRgDx

**Comment by dylanaraps** [comment]
The TrueOS detection is hardcoded to checking if `/etc/rc.conf.trueos` exists. We do this as there's no other way of detecting the difference between FreeBSD and TrueOS. This file may no longer exist in new versions so it looks like we'll need to find another way of detecting TrueOS.

**Comment by dawidd6** [comment]
@cubedev2539 see this #869

**Comment by konimex** [comment]
#869 should fix this issue. I'm closing this for the time being, but feel free to reopen if the issue still persists.
