### ISSUE TITLE
Better Sawfish WM Theme

### ISSUE THREAD

**Issue by parkmino** [dylanaraps/neofetch#858]
## Description
Sawfish WM Theme shows '(quote typo' as the following screenshot.
'Typo' would be better.
FYI, 'grep default-frame-style ~/.sawfish/custom' result is
(custom-set-typed-variable (quote default-frame-style) (quote typo) (quote frame-style))
#### Neofetch version
3.3.0
## Screenshot
![2017-11-04-000702_655x415_scrot](https://user-images.githubusercontent.com/12131158/32380741-31162932-c0f4-11e7-9c6c-2785eafcfab8.png)
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
Fixed in https://github.com/dylanaraps/neofetch/commit/7fc4f84217c101c49636732912e32e74d7ce6e2e
