### ISSUE TITLE
AmigaOS Support

### ISSUE THREAD

**Issue by P1nkz** [dylanaraps/neofetch#860]
There's no *fetch for AmigaOS.
Will we see support for AmigaOS (especially OS 3.1-3.9)?
That's would be great, please consider, thanks!

**Comment by dylanaraps** [comment]
What's the latest version of `bash` available on AmigaOS? Also, what's the easiest way for me to boot up a VM to test on?

**Comment by P1nkz** [comment]
Right now the only optimized sources for Bash I've found are for version 2.01. That could be problematic. 
The easiest way would be with WinUAE. It's an Amiga emulator that behaves pretty much like a modern VM would. 
If you are still interested in taking a shot at it, I could put together a bundle with the ROM, OS and WinUAE to make it a little easier.

**Comment by dylanaraps** [comment]
Neofetch requires `bash 3.2+` so I don't think it's possible to add support for AmigaOS.

**Comment by dylanaraps** [comment]
Reopen this if bash 3.2+ becomes available.
