### ISSUE TITLE
Support for HP-UX 11i v1

### ISSUE THREAD

**Issue by nfinit** [dylanaraps/neofetch#861]
Giving neofetch a try on my Visualize C3000 gave me this:
`Unknown OS detected: 'HP-UX', aborting...`
I'd love to do what I can to help get it supported, I took a look at the [previous issue for IRIX support](https://github.com/dylanaraps/neofetch/issues/706) and tried to get the output of anything useful I could come up with:

`[uname -s] HP-UX`

`[uname -r] B11.11`

`[uname -m] 9000/785`

`[uptime] 10:30pm  up 43 mins,  2 users,  load average: 5.21, 4.44, 3.63`

[df]****************************************************************************
/home                (/dev/vg00/lvol5     ):  1034224 blocks     16273 i-nodes
/opt                 (/dev/vg00/lvol6     ):   378848 blocks      5934 i-nodes
/store               (/dev/dsk/c3t5d0     ): 138251104 blocks   2177154 i-nodes
/tmp                 (/dev/vg00/lvol4     ):   379120 blocks      5939 i-nodes
/usr                 (/dev/vg00/lvol7     ):   778656 blocks     12237 i-nodes
/var                 (/dev/vg00/lvol8     ):  2058624 blocks     32390 i-nodes
/stand               (/dev/vg00/lvol1     ):   409904 blocks     32194 i-nodes
/                    (/dev/vg00/lvol3     ):   241568 blocks      3785 i-nodes

[df -P]*************************************************************************
Filesystem           512-blocks  Used  Available Capacity Mounted on
/dev/vg00/lvol5       2040032  1005808  1034224    50%   /home
/dev/vg00/lvol6       4994224  4615376   378848    93%   /opt
/dev/dsk/c3t5d0       142286256  4035152 138251104     3%   /store
/dev/vg00/lvol4       407648    28528   379120     7%   /tmp
/dev/vg00/lvol7       4638848  3860192   778656    84%   /usr
/dev/vg00/lvol8       2523440   464816  2058624    19%   /var
/dev/vg00/lvol1       531040   121136   409904    23%   /stand
/dev/vg00/lvol3       407792   166224   241568    41%   /

This should show the total amount of physical memory:
`[/usr/sbin/dmesg | grep Physical]    Physical: 524288 Kbytes, lockable: 363560 Kbytes, available: 439440 Kbytes`

I believe this shows the current physical memory usage too, but I'm not sure:
[swapinfo -tam]*****************************************************************
             Mb      Mb      Mb   PCT  START/      Mb
TYPE      AVAIL    USED    FREE  USED   LIMIT RESERVE  PRI  NAME
dev        1024       0    1024    0%       0       -    1  /dev/vg00/lvol2
reserve       -     184    -184
memory      355      63     292   18%
total      1379     247    1132   18%       -       0    -

This will give you the CPU model, I don't know if this output is reliable across different systems or if it's formatted similarly on Itanium systems:
`[cat /var/tombstones/ts99 | grep CPU | tail -n 1]        PA 8500-8500 CPU    2.3`

11i v1 lacks a few utilities present in 11i v3 like `machinfo`, so it doesn't seem like there's a way to get the CPU clock speed.

`versions` isn't present in HP-UX but I think you can still get total package count using `swlist` and counting the lines. In the case of my system you can subtract 13 from the line count (information and empty lines) to get the total number of installed packages/bundles, I can provide the output if that would help, though it's a little long.

If there's anything else that you think would be useful I'll be happy to do what I can to provide or test it for you. I've only had this system for a few months so I'm still not very acquainted with the ins and outs of it.

**Comment by nfinit** [comment]
Sorry, I just noticed there was a pull request already for 11i v3 support after I submitted this, 11i v1 is a little different, so I'm not sure if this issue should be kept open as a separate request or discussion moved into what's already there.

**Comment by konimex** [comment]
Hello there. While I do have access to an HP-UX server (an IA64, 11i v3) I have no root access, so `dmesg` is inaccessible to me. And as you know some commands in hppa and IA64 are different and produces different outputs.

Anyway, `/var/tombstones/ts99` is not available in the ia64 one.

If you want to test what's available, you can clone neofetch and track the `hp-ux` branch, *or* download this tarball:

https://github.com/dylanaraps/neofetch/archive/hp-ux.tar.gz

Expect no output from `get_cpu` since the only support available is for 11.31 ia64 at the moment.

**Comment by nfinit** [comment]
Sorry, I don't really know why I put dmesg output in there now that I look at it. Interesting detail about tombstones as well.

You might have already seen these, but I was digging around and turned up [an interesting thread on the HPE forums](https://community.hpe.com/t5/System-Administration/Command-to-check-HP-UX-server-spec/td-p/4026530) with a script someone uses on their own systems to get general information (last post, does use `machinfo` but maybe that portion is more reliable than others) and this [script that can get the CPU type on PA-RISC systems running >11.00 using getconf](http://unix.derkeiler.com/Mailing-Lists/HP-UX-Admin/2003-04/0003.html) that I just successfully tested on my system. 

I don't know if you guys have already considered it, but perhaps you could use the `model` command to choose a path to take. From what I've found it looks like PA-RISC systems will always be prefixed with `9000` while IA-64 systems will sport `ia64`.

I'll definitely try that branch out and maybe experiment a little on my side, thanks for the link!
