### ISSUE TITLE
Neofetch formulae not upgraded in Brew

### ISSUE THREAD

**Issue by Nifled** [dylanaraps/neofetch#863]
[Brew formulae](http://formulae.brew.sh/formula/neofetch) for neofetch doesn't seem to be updated to `v3.3.1`. Due to this, there doesn't seem to be support for macOS High Sierra. 

![image](https://user-images.githubusercontent.com/16827499/32632186-e3515b2a-c55f-11e7-81cc-40714019be13.png)

**Comment by konimex** [comment]
The latest neofetch release is `3.3.0`, not `3.3.1`. Therefore there are no High Sierra support yet because High Sierra is released way after Neofetch 3.3.0 is released.

**Comment by konimex** [comment]
Anyway, you can use the git version of neofetch for High Sierra support.
