### ISSUE TITLE
Extra trailing newline.

### ISSUE THREAD

**Issue by Swedneck** [dylanaraps/neofetch#866]
## Description
When running neofetch so that it doesn't need to scroll the terminal content up, it has an extra newline at the end.

#### Neofetch version
3.3.0
## Screenshot
![image](https://user-images.githubusercontent.com/31285258/32692066-d27daa7a-c711-11e7-9f54-4f7fe7114c49.png)

## Config file
[neofetch.conf.txt](https://github.com/dylanaraps/neofetch/files/1463964/neofetch.conf.txt)

## Verbose log
[neofetchlog.txt](https://github.com/dylanaraps/neofetch/files/1463952/neofetchlog.txt)

**Comment by dylanaraps** [comment]
Fixed. https://github.com/dylanaraps/neofetch/commit/9f263fe1849d0a6a78232682368f9f4b9e650190
