### ISSUE TITLE
Manually define cropping center for image backends

### ISSUE THREAD

**Issue by boardfish** [dylanaraps/neofetch#875]
## Description

So far waifu crop, as it's known, works automatically. That's all well and good for minimalist images such as the examples, but for other images, a way to define a center per image may be welcome. Perhaps a cache could be built as it is with `pywal` that allows us to define a crop style and/or center per image. I'd imagine cache text files could contain either the coordinates for the image center (such as `-100x0` for 100 pixels left of the center) or a crop method (such as `auto`).

A cache is pretty important to me because I change wallpapers very often - I've got a script `theme` that runs everything `wal`-related on a random image in a given folder. Thoughts?

**Comment by dylanaraps** [comment]
There's already `--crop_offset` (see config file for available values) which allows you to set how the image is cropped. This also caches the crop offset as part of the filename. The only problem is that you'll need to specify the crop mode each time you want to display the image.

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/neofetch/issues/1392
