### ISSUE TITLE
Show NVIDIA GPU driver version

### ISSUE THREAD

**Issue by techtonik** [dylanaraps/neofetch#876]
## Description

#819 output is strange on Ubuntu. When enabled, it gives just a string `nvidia`. If GPU is NVIDIA it is logical that it will be `nvidia`.
```
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce GT 520
    .ossssssssssssssssssdMMMNysssso.       Memory: 1583MiB / 7979MiB
      -+sssssssssssssssssyyyssss+-         GPU Driver: nvidia
```
What I expected to see is exact driver version in GPU line:
```
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce GT 520 (384.98)
    .ossssssssssssssssssdMMMNysssso.       Memory: 1583MiB / 7979MiB
```
Which can be fetched with:
```
$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.98  Thu Oct 26 15:16:01 PDT 2017
GCC version:  gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3) 
```
It would be also nice to see if there is an updated version.

**Comment by dylanaraps** [comment]
Added in https://github.com/dylanaraps/neofetch/commit/1e8f12dd4a876fd2b8868641e506efde9a4e683c

**Comment by techtonik** [comment]
Awesome! Thanks. =)
