### ISSUE TITLE
Custom image not being loaded in Termite

### ISSUE THREAD

**Issue by martmists** [dylanaraps/neofetch#877]
## Description

I set neofetch to use my wallpaper or certain image, but it refuses to change. even with the `--config off` flag it still uses the config.conf in .config/neofetch/config.conf

w3m is able to display images just fine.

#### Neofetch version

 39cda4

## Screenshot

![image](https://user-images.githubusercontent.com/16361449/33555438-adae2b10-d900-11e7-89f9-bcc5b6986834.png)

## Config file

https://gist.github.com/martmists/bd5162823f26a0bfd8866054bc85d8f6

## Verbose log

https://gist.github.com/martmists/2fdf75a4dbcdbf4ea08bbf20aa455617

**Comment by dylanaraps** [comment]
You need to manually give neofetch the image path since using the current wallpaper in KDE isn't possible (`neofetch --w3m /path/to/img.jpg`). This is why neofetch is falling back to ascii mode.
