### ISSUE TITLE
Neofetch on windows-subsystem-for-linux

### ISSUE THREAD

**Issue by Jay1** [dylanaraps/neofetch#878]
![neofetch](https://user-images.githubusercontent.com/1072434/33808410-b5b7ada6-ddb3-11e7-850a-30246e81cc93.png)

I tried to install w3m and imagemagick to get a custom image but I suppose hyperterminal is not supported like iterm2 and linux terminals.

am I wasting my time trying to customize neofetch on windows subsystem for linux?  I have a strong feeling there is a lot of incompatibility issue in the end.  

From my understanding, the current ASCII logo I am seeing right now is the default "fallback"  logo when something goes wrong with the custom one. If I'm not mistaken the terminal need to pass the size of the window to w3m/imagemagick to resize the logo.  That's why in the end you need a compatible linux terminal to customize properly neofetch.  

Those are the current result with the --w3m alias
![w3m](https://user-images.githubusercontent.com/1072434/33808491-701f335c-ddb5-11e7-949b-c34d332ce2f3.png)

**Comment by konimex** [comment]
See #792. HyperTerm is not supported yet because of their inabilities to render images. Have you tried other terminals on WSL like xterm/urxvt? (You will need to use Xming or [Cygwin/X](https://superuser.com/questions/1180005/cygwin-x-and-windows-subsystem-for-linux) to do that)

**Comment by sintaxx** [comment]
@Jay1 how do i get my WSL2 terminal to look pretty like yours ? care to share ?
