### ISSUE TITLE
More GPU information.

### ISSUE THREAD

**Issue by HaoZeke** [dylanaraps/neofetch#879]
## Description

Attempts to evangelize neofetch on [StackExchange](https://askubuntu.com/questions/5417/how-to-get-the-gpu-info/985004?noredirect=1#comment1585104_985004) has lead to comments that the GPU information is not **detailed**.

Might more details be displayed? Like *video card frequency* and *memory*?

**Comment by ssspacez** [comment]
I would like to see more details too, like drivers, frequency and memory.

Also, my neofetch GPU output is a bit generic:
> GPU: Intel Sandybridge Mobile

My GPU is Intel HD Graphics 3000.

So maybe a better output would be something like:
> GPU: Intel Sandybridge Mobile (Intel HD Graphics 3000)

An even better output would be:
> GPU: Intel Sandybridge Mobile (Intel HD Graphics 3000)
> Frequency:
> Memory: 
> Driver:

**Comment by dylanaraps** [comment]
What's the output of these commands on your systems?:

- `lspci -mm`
- `lspci -mm | awk -F '\\"|\\" \\"|\\(' '/"Display|"3D|"VGA/ {a[$0] = $3 " " $4} END{for(i in a) {if(!seen[a[i]]++) print a[i]}}'`

**Comment by ssspacez** [comment]
`lspci -mm`

> ```
> 00:00.0 "Host bridge" "Intel Corporation" "2nd Generation Core Processor Family DRAM Controller" -r09 "LG Electronics, Inc." "2nd Generation Core Processor Family DRAM Controller"
> 00:02.0 "VGA compatible controller" "Intel Corporation" "2nd Generation Core Processor Family Integrated Graphics Controller" -r09 "LG Electronics, Inc." "2nd Generation Core Processor Family Integrated Graphics Controller"
> 00:16.0 "Communication controller" "Intel Corporation" "6 Series/C200 Series Chipset Family MEI Controller #1" -r04 "LG Electronics, Inc." "6 Series/C200 Series Chipset Family MEI Controller"
> 00:1a.0 "USB controller" "Intel Corporation" "6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2" -r04 -p20 "LG Electronics, Inc." "6 Series/C200 Series Chipset Family USB Enhanced Host Controller"
> 00:1b.0 "Audio device" "Intel Corporation" "6 Series/C200 Series Chipset Family High Definition Audio Controller" -r04 "LG Electronics, Inc." "6 Series/C200 Series Chipset Family High Definition Audio Controller"
> 00:1c.0 "PCI bridge" "Intel Corporation" "6 Series/C200 Series Chipset Family PCI Express Root Port 1" -rb4 "" ""
> 00:1c.1 "PCI bridge" "Intel Corporation" "6 Series/C200 Series Chipset Family PCI Express Root Port 2" -rb4 "" ""
> 00:1c.3 "PCI bridge" "Intel Corporation" "6 Series/C200 Series Chipset Family PCI Express Root Port 4" -rb4 "" ""
> 00:1d.0 "USB controller" "Intel Corporation" "6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1" -r04 -p20 "LG Electronics, Inc." "6 Series/C200 Series Chipset Family USB Enhanced Host Controller"
> 00:1f.0 "ISA bridge" "Intel Corporation" "HM65 Express Chipset Family LPC Controller" -r04 "LG Electronics, Inc." "HM65 Express Chipset Family LPC Controller"
> 00:1f.2 "SATA controller" "Intel Corporation" "6 Series/C200 Series Chipset Family 6 port Mobile SATA AHCI Controller" -r04 -p01 "LG Electronics, Inc." "6 Series/C200 Series Chipset Family 6 port Mobile SATA AHCI Controller"
> 00:1f.3 "SMBus" "Intel Corporation" "6 Series/C200 Series Chipset Family SMBus Controller" -r04 "LG Electronics, Inc." "6 Series/C200 Series Chipset Family SMBus Controller"
> 07:00.0 "Network controller" "Ralink corp." "RT3090 Wireless 802.11n 1T/1R PCIe" "Askey Computer Corp." "RT3090 Wireless 802.11n 1T/1R PCIe"
> 0d:00.0 "Ethernet controller" "Qualcomm Atheros" "AR8151 v2.0 Gigabit Ethernet" -rc0 "LG Electronics, Inc." "AR8151 v2.0 Gigabit Ethernet"
> ```
> 
> 
> 

------------------

`lspci -mm | awk -F '\\"|\\" \\"|\\(' '/"Display|"3D|"VGA/ {a[$0] = $3 " " $4} END{for(i in a) {if(!seen[a[i]]++) print a[i]}}'`

> Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller

**Comment by dylanaraps** [comment]
Also:

- `glxinfo | grep -F "Device:"`

**Comment by ssspacez** [comment]
`glxinfo | grep -F "Device:"`

>     Device: Mesa DRI Intel(R) Sandybridge Mobile  (0x116)

**Comment by dylanaraps** [comment]
Your system doesn't seem to store the correct GPU model name anywhere...

**Comment by ssspacez** [comment]
Oh, thanks for the info and replys.

Also, neofetch is great, thank you!
