### ISSUE TITLE
ASCII free output

### ISSUE THREAD

**Issue by xreeckz** [dylanaraps/neofetch#882]
## Description

ScreenFetch has the -n option, which at times comes in very handy. Would be great for Neofetch to also have it.

**Comment by simoniz0r** [comment]
You mean like `neofetch --off`?

![image](https://user-images.githubusercontent.com/16279904/34083629-2ef6562e-e339-11e7-8d42-f87d9321e447.png)

**Comment by xreeckz** [comment]
Yeah, exactly. Wasn't aware that was a thing and couldn't find it anywhere in the wiki.

**Comment by konimex** [comment]
You can also try `neofetch --stdout` for pure text output.

**Comment by dylanaraps** [comment]
The wiki won't have all of the information. Next time also check `man neofetch` or `neofetch --help` for info about command-line usage.
