### ISSUE TITLE
w3m images not displaying at all

### ISSUE THREAD

**Issue by gdspd** [dylanaraps/neofetch#883]
I'm on Debian 9 stable, I'm using urxvt and w3m images don't show up at all in neofetch for me.

w3m does display images without any problems by itself though. So maybe something is off in my neofetch config and I just can't figure what it is. 
Here's my neofetchlog https://pastebin.com/jVPDd0rz

**Comment by dylanaraps** [comment]
Can you also upload your config file?

**Comment by gdspd** [comment]
Of course, I thought the relevant config options would be mentioned in the log. My bad. Should've looked through it, but I didn't bother as I've never been that good with troubleshooting myself.

**Comment by dylanaraps** [comment]
Change `image_backend` from `auto` to `w3m` in your config file and images will display. Alternatively you can keep it as is and use `--w3m` to display images.

**Comment by gdspd** [comment]
Doesn't seem to work. It doesn't even reserve the space for the image.
Here's a picture.
https://i.imgur.com/iRHj0DD.png

**Comment by dylanaraps** [comment]
Does the issue occur on the latest git version with a fresh config file?

**Comment by gdspd** [comment]
The latest master works like a charm. Thanks for helping me figure it out.

**Comment by purpleleaf** [comment]
Hi have the same problem on linux mint 18.3 using the latest deb from ppa
