### ISSUE TITLE
Error installing from source on OpenIndiana

### ISSUE THREAD

**Issue by GrayJack** [dylanaraps/neofetch#886]
## Description
I'm getting
make: Fatal error in reader: Makefile, line 1: Badly formed macro assignment

## Screenshot
![screenshot at 2017-12-27 13-07-27](https://user-images.githubusercontent.com/17973728/34380027-b350485e-eae5-11e7-81bb-a7063131c4cc.png)

**Comment by dylanaraps** [comment]
OpenIndiana doesn't support `?=`, you need to use `gmake`. I'll update the wiki to explain this.

source: https://stackoverflow.com/questions/18567963/makefile-errors-in-solaris-when-using-conditional-assignment
