### ISSUE TITLE
No terminal font for gnome terminal

### ISSUE THREAD

**Issue by SanketDG** [dylanaraps/neofetch#887]
```
[!] Info: Couldn't detect Terminal Font.
```

from the log

**Comment by konimex** [comment]
Please provide your complete log and your config (if not default).

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by SanketDG** [comment]
log: http://sprunge.us/BhDh
default config

**Comment by mstraube** [comment]
Font detection for gnome-terminal isn't supported.

I don't know if there is a way to get the font info. It would work similar to mate-terminal detection, but sadly the `--save-config` option was removed from gnome-terminal.
