### ISSUE TITLE
Negative number in "neofetch --block_range" gives garbadge characters (Not Really An Issue?)

### ISSUE THREAD

**Issue by Arefu** [dylanaraps/neofetch#888]
## Description
When running this script with --block_range, if you provide a negative number as in 
neofetch --block_range -123 it will print corrupt characters.

#### Neofetch version
Neofetch 3.1.0

## Screenshot
![neofetch-2017-12-30-10-15-04-16477](https://user-images.githubusercontent.com/11144734/34447606-52a1e960-ed4a-11e7-8bc9-01441617503a.png)

## Config file
You can have a config flie!?!?!

## Verbose log
N/A

**Comment by dylanaraps** [comment]
Negative values work in true color terminals and terminals that support 256 colors. Closing this as a non-issue. 

> You can have a config flie!?!?!

`~/.config/neofetch/config.conf`
