### ISSUE TITLE
Color scheme rendering issues

### ISSUE THREAD

**Issue by shelldandy** [dylanaraps/neofetch#890]
## Description

Some unescaped characters are showing...

#### Neofetch version
Github master

## Screenshot

<img width="1214" alt="34458382-6cce12b8-ed96-11e7-9944-2bdea343a1f6" src="https://user-images.githubusercontent.com/7088511/34532844-53c20e5c-f07d-11e7-9000-2ae1526de979.png">

## Config file
https://github.com/mike3run/dotfiles/blob/master/config/neofetch/config

## Verbose log
https://pastebin.com/VRbevGW5

**Comment by mike3run** [comment]
Here's more info based on releases and current version:

To reproduce I cloned the repo and then ran `./neofetch` on different tags: `git checkout tags/3.2.0` etc

On v.3.2.0 everything works perfect on iTerm

<img width="1214" alt="screen shot 2018-02-19 at 11 28 46 am" src="https://user-images.githubusercontent.com/7088511/36390349-68d1e5d2-1568-11e8-8404-a69426bcbec3.png">

On v.3.3.0 images stop working altogether

<img width="1214" alt="screen shot 2018-02-19 at 11 30 02 am" src="https://user-images.githubusercontent.com/7088511/36390413-95402b74-1568-11e8-8606-0f87ff680fcf.png">

On `master` is where the escaping of characters is happenning:

<img width="1214" alt="screen shot 2018-02-19 at 11 29 38 am" src="https://user-images.githubusercontent.com/7088511/36390471-c109882c-1568-11e8-8c4b-fb770b2691c7.png">

**Comment by konimex** [comment]
Since neither Dylan nor I have access to a Mac, I think we will need your help here.

In the latest git master of neofetch, can you do a `git bisect` of the repo?

Assuming the latest good commit is 3.2.0, please do a `git bisect start HEAD 3.2.0`, and test neofetch for every given commit (`git bisect <good/bad>`) and report back the bad commit (I'm assuming it's my commit from back then).

**Comment by iandrewt** [comment]
Is this issue still happening? Seems to be working fine for me with `master` running `./neofetch --iterm2 image.png`

**Comment by shelldandy** [comment]
I can confirm on the current master is working fine again :)
