### ISSUE TITLE
st terminal detection

### ISSUE THREAD

**Issue by SanketDG** [dylanaraps/neofetch#898]
st exposes a "$TERM" with default value, "st-256color", can this be used to detect st?

**Comment by konimex** [comment]
The usual function in neofetch should work for `st`, no?

![2018-01-28-194629_814x638_scrot](https://user-images.githubusercontent.com/15692230/35482178-5390b2e8-0429-11e8-8820-02d98c06f205.png)

(Terrible font, I know, I didn't bother to configure st)

**Comment by SanketDG** [comment]
I don't know how I missed that, sorry! Closing.
