### ISSUE TITLE
Support for Anarchy Linux, Calculate Linux, and NuTyX

### ISSUE THREAD

**Issue by robertwolter** [dylanaraps/neofetch#900]
I extended neofetch to support more Linux distros and would like to get this merged into neofetch.

Here is the diff output as of 30-Jan-2018:

diff neofetch neofetch-rw
3243a3244,3249
> # RW added Anarchy
>         "Anarchy"*)
>             set_colors 4 6
>             ascii_file="anarchy"
>         ;;
> 
3334a3341,3347
> 
> # RW added Caluclate
>         "Calculate"*)
>             set_colors 0 3 
>             ascii_file="calculate"
>         ;;
> 
3638a3652,3657
>         ;;
> 
> # RW added NuTyx
>         "NuTyX"*)
>             set_colors 4
>             ascii_file="nutyx"

neofetch-rw:  https://pastebin.com/3Nz64DeJ
ascii-art file anarchy: https://pastebin.com/KRhgb2nf
ascii-art file calculate: https://pastebin.com/S9NgCRUs
ascii-art file nutyx: https://pastebin.com/FpGiQXzD

**Comment by dylanaraps** [comment]
Please submit this as a PR.

**Comment by robertwolter** [comment]
Ok, done.
