### ISSUE TITLE
Several features broken due to 100-char line limit fixes

### ISSUE THREAD

**Issue by JadeMatrix** [dylanaraps/neofetch#902]
I've been trying to fix some issues with neofetch on macOS, and I've noticed most of them have to do with commits made ~6 months ago enforcing a 100-char line length.  For example, [the `awk` call checking for open music players](https://github.com/dylanaraps/neofetch/blame/2cecb142e1bc651427e0590672144b609714f903/neofetch#L1525) won't work for the first program on each line — `Google Play`, `xmms2d`, and `guayadeque`.  While I don't run any of those, I noticed it when I changed the regex for Spotify to `[sS]potify` which pushed it onto the next line.

Another place I've noticed this is the calls to `osascript` where the script to execute is split across multiple lines, reporting `syntax error: A unknown token can’t go after this property`.

I've been able to fix all of these by making them one-liners again (removing the backslash-newlines).  I'm not really a `bash` expert, so I'm not sure if there's another newline-escape method to use so I can continue my other macOS fixes.

### Code examples:

Detects Spotify on macOS (modified [line 1525](https://github.com/dylanaraps/neofetch/blame/2cecb142e1bc651427e0590672144b609714f903/neofetch#L1525)):
```bash
player="$(ps x | awk '!(/ awk|Helper|Cache|ibus|indicator/) && /mpd|mopidy|cmus|mocp|[sS]potify|\
Google Play|iTunes.app|rhythmbox|banshee|amarok|deadbeef|audacious|\
xmms2d|gnome-music|lollypop|clementine|pragha|exaile|juk|bluemindo|\
guayadeque|yarock|qmmp|quodlibet|deepin-music|tomahawk|pogo|elisa/ {printf $5 " " $6; exit}')"
```

Fails to detect Spotify on macOS:
```bash
player="$(ps x | awk '!(/ awk|Helper|Cache|ibus|indicator/) && /mpd|mopidy|cmus|mocp|\
[sS]potify|Google Play|iTunes.app|rhythmbox|banshee|amarok|deadbeef|audacious|\
xmms2d|gnome-music|lollypop|clementine|pragha|exaile|juk|bluemindo|\
guayadeque|yarock|qmmp|quodlibet|deepin-music|tomahawk|pogo|elisa/ {printf $5 " " $6; exit}')"
```

Detects Spotify on macOS:
```bash
player="$(ps x | awk '!(/ awk|Helper|Cache|ibus|indicator/) && /mpd|mopidy|cmus|mocp|[sS]potify|Google Play|iTunes.app|rhythmbox|banshee|amarok|deadbeef|audacious|xmms2d|gnome-music|lollypop|clementine|pragha|exaile|juk|bluemindo|guayadeque|yarock|qmmp|quodlibet|deepin-music|tomahawk|pogo|elisa/ {printf $5 " " $6; exit}')"
```

Fails to get artist & track from Spotify on macOS ([line 1580](https://github.com/dylanaraps/neofetch/blame/2cecb142e1bc651427e0590672144b609714f903/neofetch#L1580)):
```bash
song="$(osascript -e 'tell application "Spotify" to artist of current track as \
                      string & " - " & name of current track as string')"
```

Successfully gets artist & track from Spotify on macOS:
```bash
song="$(osascript -e 'tell application "Spotify" to artist of current track as string & " - " & name of current track as string')"
```

**Comment by dylanaraps** [comment]
Do these issues occur in the latest git master?

**Comment by JadeMatrix** [comment]
Yeah, I just cloned master today to work on the macOS stuff, which I noticed was broken in 3.3.0 installed via Homebrew.

**Comment by dylanaraps** [comment]
I'll revert the 100 line changes.

**Comment by dylanaraps** [comment]
Reverted all lines that are probably problematic. https://github.com/dylanaraps/neofetch/commit/7a543e8fa6902a3d946a4b912c898546eb794db9

**Comment by dylanaraps** [comment]
Fixed the player command by swapping to `grep`. https://github.com/dylanaraps/neofetch/commit/bac9dcf3f4a347f8364d293a38d8d1390994be7d

**Comment by JadeMatrix** [comment]
Okay, seems like those two commits fixed these issues.  I'll try out the multi-line string syntax for `osascript`.  Also, this usage of `grep` seems to pick up stuff just fine regardless of case (unlike the `awk` before) so only one case for Spotify is needed.

**Comment by JadeMatrix** [comment]
Looks like that way of running AppleScripts works; do you want me to go ahead and add a commit to my fork changing them, since I've already got one for my additions?  If so, how far do you want them indented (if it matters):

```bash
                    song="$(osascript <<END
                      tell application "Spotify"
                        artist of current track as string & " - " & name of current track as string
                      end tell
END
)"
```
vs.
```bash
                    song="$(osascript <<END
tell application "Spotify"
    artist of current track as string & " - " & name of current track as string
end tell
END
)"

**Comment by dylanaraps** [comment]
Second one. 

Yeah, submit a PR if possible :)
