### ISSUE TITLE
Image host addition request.

### ISSUE THREAD

**Issue by esgwpl** [dylanaraps/neofetch#903]
Could you add [https://postimages.org/](url) as an alternative? I've been using it for years now and it has yet to fail me.

**Comment by dylanaraps** [comment]
Does postimages have an api we can use? I can't find anything on their site.

**Comment by esgwpl** [comment]
Same here, I contacted them about it, will report back when I get an answer.

**Comment by dylanaraps** [comment]
Yeah, there's no public api. 

Sources: https://github.com/ShareX/CustomUploaders/issues/71 https://github.com/ShareX/ShareX/issues/472
