### ISSUE TITLE
Asus n551zu

### ISSUE THREAD

**Issue by APakrohk** [dylanaraps/neofetch#906]
Hardware is wrong.
GPU*

![screenshot from 2018-02-03 07-46-14](https://user-images.githubusercontent.com/27810360/35762947-81f65142-08b6-11e8-8f13-6f9c4d52a59a.png)

------------------------------------------------------------------------------------------------------------------
Asus website
https://www.asus.com/Laptops/N551ZU/

**Comment by dylanaraps** [comment]
Send me the output of “lspci -mm”.

**Comment by APakrohk** [comment]
`00:00.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Complex" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Complex"
00:00.2 "IOMMU" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) I/O Memory Management Unit" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) I/O Memory Management Unit"
00:01.0 "VGA compatible controller" "Advanced Micro Devices, Inc. [AMD/ATI]" "Kaveri [Radeon R7 Graphics]" "ASUSTeK Computer Inc." "Kaveri [Radeon R7 Graphics]"
00:01.1 "Audio device" "Advanced Micro Devices, Inc. [AMD/ATI]" "Kaveri HDMI/DP Audio Controller" "ASUSTeK Computer Inc." "Kaveri HDMI/DP Audio Controller"
00:02.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1424" "" ""
00:02.1 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1425" "" ""
00:03.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1424" "" ""
00:03.1 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Port" "" ""
00:03.2 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Root Port" "" ""
00:04.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Device 1424" "" ""
00:10.0 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB XHCI Controller" -r09 -p30 "ASUSTeK Computer Inc." "FCH USB XHCI Controller"
00:10.1 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB XHCI Controller" -r09 -p30 "ASUSTeK Computer Inc." "FCH USB XHCI Controller"
00:11.0 "SATA controller" "Advanced Micro Devices, Inc. [AMD]" "FCH SATA Controller [IDE mode]" -r40 -p01 "ASUSTeK Computer Inc." "FCH SATA Controller [IDE mode]"
00:12.0 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB OHCI Controller" -r11 -p10 "ASUSTeK Computer Inc." "FCH USB OHCI Controller"
00:12.2 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB EHCI Controller" -r11 -p20 "ASUSTeK Computer Inc." "FCH USB EHCI Controller"
00:13.0 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB OHCI Controller" -r11 -p10 "ASUSTeK Computer Inc." "FCH USB OHCI Controller"
00:13.2 "USB controller" "Advanced Micro Devices, Inc. [AMD]" "FCH USB EHCI Controller" -r11 -p20 "ASUSTeK Computer Inc." "FCH USB EHCI Controller"
00:14.0 "SMBus" "Advanced Micro Devices, Inc. [AMD]" "FCH SMBus Controller" -r16 "ASUSTeK Computer Inc." "FCH SMBus Controller"
00:14.2 "Audio device" "Advanced Micro Devices, Inc. [AMD]" "FCH Azalia Controller" -r01 "ASUSTeK Computer Inc." "FCH Azalia Controller"
00:14.3 "ISA bridge" "Advanced Micro Devices, Inc. [AMD]" "FCH LPC Bridge" -r11 "ASUSTeK Computer Inc." "FCH LPC Bridge"
00:14.4 "PCI bridge" "Advanced Micro Devices, Inc. [AMD]" "FCH PCI Bridge" -r40 -p01 "" ""
00:18.0 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 0" "" ""
00:18.1 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 1" "" ""
00:18.2 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 2" "" ""
00:18.3 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 3" "" ""
00:18.4 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 4" "" ""
00:18.5 "Host bridge" "Advanced Micro Devices, Inc. [AMD]" "Family 15h (Models 30h-3fh) Processor Function 5" "" ""
01:00.0 "Display controller" "Advanced Micro Devices, Inc. [AMD/ATI]" "Bonaire PRO [Radeon R9 M270X]" -rff -pff "" ""
02:00.0 "Network controller" "Intel Corporation" "Wireless 7260" -rbb "Intel Corporation" "Dual Band Wireless-N 7260"
03:00.0 "Unassigned class [ff00]" "Realtek Semiconductor Co., Ltd." "RTL8411B PCI Express Card Reader" -r01 "ASUSTeK Computer Inc." "RTL8411B PCI Express Card Reader"
03:00.1 "Ethernet controller" "Realtek Semiconductor Co., Ltd." "RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller" -r12 "ASUSTeK Computer Inc." "RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller"
`

**Comment by dylanaraps** [comment]
There's no reference to the `280x` in your `lspci` output. Either your laptop doesn't match the specs on the website or the kernel is reporting the gpu name wrong.

Anyway, this isn't a neofetch issue.
