### ISSUE TITLE
Requesting for support for Magpie OS

### ISSUE THREAD

**Issue by Neil-seu** [dylanaraps/neofetch#908]
Magpie OS is first arch based distro from bangladesh. I am from Bangladesh. 
http://www.magpieos.net/
This is the link for magpie os.

![27786157_2212284419009152_662630214_o](https://user-images.githubusercontent.com/24956423/35882770-73bd61c8-0baf-11e8-8753-3d1711371b4a.png)
this is the logo for magpie os.

So if possible please add a support for it.
I appreciate your help :)

Thank you :)

**Comment by robertwolter** [comment]
Do you have al link to an SVG file that contains only the logo?

**Comment by dylanaraps** [comment]
What's the output of this command?:

```sh
cat /etc/os-release
```

**Comment by robertwolter** [comment]
`cat /etc/lsb-release`
`LSB_VERSION=1.4`
`DISTRIB_ID=MagpieOS`
`DISTRIB_RELEASE=v2.0`
`DISTRIB_CODENAME=Ormeli`
`DISTRIB_DESCRIPTION="MagpieOS"`

`cat /etc/os-release`
`NAME="MagpieOS"`
`ID=MagpieOS`
`ID_LIKE="arch"`
`VERSION_ID=v2.0`
`PRETTY_NAME="MagpieOS"`
`ANSI_COLOR="0;36"`

It's an Arch-based distro with GNOME as default DE.

**Comment by robertwolter** [comment]
And the colored output would look like this.
![bildschirmfoto vom 2018-02-07 17-31-36](https://user-images.githubusercontent.com/18753171/35928217-e58fd43e-0c2c-11e8-8dc4-1beb3d339837.png)

**Comment by dylanaraps** [comment]
That ascii art looks too tall. Can you by any chance make it shorter?

**Comment by robertwolter** [comment]
Define max height and width.

**Comment by dylanaraps** [comment]
height: 20 lines
width: 40 chars

You can go a little bigger if you must.

**Comment by Neil-seu** [comment]
I will let you know brother. I am reviewing your encountered issues :) Is
it okay to mail you?

**Comment by robertwolter** [comment]
With a height of 20 chars it looks like this:
![bildschirmfoto vom 2018-02-08 15-55-57](https://user-images.githubusercontent.com/18753171/35979419-96c35526-0ce8-11e8-84f6-f57e75c692fb.png)

**Comment by Neil-seu** [comment]
Its amazing Bro. Thank you for your kindness bro. Would you mind to hold
this as draft? We are currently in trouble as the new version's installer
is not working. We can let you know tomorrow. Is it okay for you? :)

**Comment by Neil-seu** [comment]
But I think this design should be okay though we can let you the final
thoughts tomorrow :)

**Comment by robertwolter** [comment]
Ok, we'll see tomorrow :)

**Comment by Neil-seu** [comment]
Hi Dylan,

Here is the zip file. You can find png and svg file. :) We prefer red and
green mixing. :)

**Comment by Neil-seu** [comment]
You can prepare the Blue one too! Cause we don't know yet which one will be
beautiful looking. :)

**Comment by Neil-seu** [comment]
Hey Guys,

Did you receive my mail? :)

**Comment by dylanaraps** [comment]
Yes, I’m just a little busy at the moment. If you could open a PR it’d speed things up.

**Comment by Neil-seu** [comment]
okay. I am reopening the issue.. Thank you and sorry for interrupting you..
:)

**Comment by Rizwan-Hasan** [comment]
[MagpieOS Logo (SVG).zip](https://github.com/dylanaraps/neofetch/files/1713217/MagpieOS.Logo.SVG.zip)

**Comment by robertwolter** [comment]
With a height of 20 chars and blue replaced by green it looks like this. Now you must decide betwenn blue and green, since there is only one ascii art file for each distro.
![bildschirmfoto_2018-02-10_17-48-53](https://user-images.githubusercontent.com/18753171/36064415-fa601594-0e8a-11e8-9602-5517a03c5692.png)

**Comment by Rizwan-Hasan** [comment]
Thanks.It's awesome.This green one now final.

**Comment by robertwolter** [comment]
Ok, then I'll make the pull request.

**Comment by Rizwan-Hasan** [comment]
Ok

**Comment by dylanaraps** [comment]
Done.

**Comment by Neil-seu** [comment]
THANKS MAN!!! sorry for the late reply :( Wish you good luck :)
