### ISSUE TITLE
Gnome terminal issue

### ISSUE THREAD

**Issue by rawsh** [dylanaraps/neofetch#913]
I think the image says it all. w3m

![screenshot from 2018-02-12 11-57-09](https://user-images.githubusercontent.com/7035671/36111477-dffc8248-0feb-11e8-8660-d42e046ca72a.png)

**Comment by dylanaraps** [comment]
This is not a Neofetch issue but a w3m-img issue. W3m-img draws on top of the window, it doesn’t know what it’s drawing on. You can use —xoffset and —yoffset to fix this.
