### ISSUE TITLE
is it possible to make neofetch compatible with lolcat?

### ISSUE THREAD

**Issue by Neil-seu** [dylanaraps/neofetch#914]
![archmerge_2018-02-14_16-01-52](https://user-images.githubusercontent.com/24956423/36214093-73b9001e-11a0-11e8-871a-d5a36edef229.png)

**Comment by Rizwan-Hasan** [comment]
Need this

**Comment by dylanaraps** [comment]
No

Duplicate of #666, #685, #747. 

Check for previous issues before op ning another one.

**Comment by konimex** [comment]
It is *kind of* possible with `--stdout`, but no ASCII art.

**Comment by dylanaraps** [comment]
Neofetch now works with `lolcat`! :fireworks:

**Comment by Neil-seu** [comment]
Yeah I saw that and tested it!! Thank you so much!! And sorry for the late
reply!😣

**Comment by ProxyNeko** [comment]
I know this was said to be fixed but I'm still getting the issue even after downloading version 5 from the releases here on Github. had it installed from Debian repos at first until I found out that is no longer updated so just swapped the files over and still the same issue. Any pointers?

**Comment by ARAGATO** [comment]
Same here. Just tried it with neofetch v6.0.0 and output is still buggy.

**Comment by treier57lol** [comment]
I got it working, the problem was that I installed lolcat with apt, which installed an old version, 42.0.99. I removed lolcat, installed it with `gem install lolcat` and rebooted. Everything now works!

**Comment by kaanoguzhan** [comment]
> Neofetch now works with `lolcat`! 🎆

An Explanation could be nice you know

**Comment by G3NSVRV** [comment]
it is possible to only print the ascii art in lolcat colouring and the rest as default?
