### ISSUE TITLE
Incorrect reported GPU(lspci vs glxinfo)

### ISSUE THREAD

**Issue by lilianmoraru** [dylanaraps/neofetch#915]
## Description

I have a `Radeon RX 550` GPU but `neofetch` reports it as being `AMD Radeon RX 560`.
`lspci` reports the same:
```
VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 560]
```

While KInfoCenter(KDE's system info) reports correctly:
```
Radeon RX 550 Series (POLARIS11 / DRM 3.23.0 / 4.15.2-1-default, LLVM 5.0.1)
```

Which is exactly the same output `glxinfo` reports.
KInfoCenter seems to call directly an API because I didn't have `glxinfo` installed when I was looking at the reported GPU(openSuse Tumbleweed didn't come with `glxinfo` preinstalled).

#### Neofetch version
[Master branch as of today](https://github.com/dylanaraps/neofetch/tree/8a17129ad2575558560f4711da5d30ef50dd06d8)(3.3.0?)

**Comment by konimex** [comment]
What is the output of `lspci -nn`?

**Comment by dylanaraps** [comment]
also lspci -mm

**Comment by lilianmoraru** [comment]
Tried to avoid displaying to much info and keep it only to relevant data.
But ok(this data doesn't really invade my "privacy"), here it is:
- [`lspci -nn`](https://gist.github.com/lilianmoraru/461e21b41590778c87762c6fee902e18)
- [`lspci -mm`](https://gist.github.com/lilianmoraru/6b53ed00a2c1d8fe59646f717897da3d)
- [`glxinfo`](https://gist.github.com/lilianmoraru/47298d5b7a0925a2d1b3913c1ebc861f)(note that I had to install this separately - it was not available on the system by default)

**Comment by konimex** [comment]
This is not a neofetch issue but rather an issue with pci-ids database itself, I suspect it has to do with something [here](https://github.com/GPUOpen-Tools/common-src-DeviceInfo/commit/5bc6e3ca77254ca2b42e57e7af4260170f9952a2#diff-fdd3c86dd88500382e70fe0ef61d0a50R361).

I've addressed this in the [database](https://pci-ids.ucw.cz/read/PC/1002/67ff), let's see if they got something.

**Comment by lilianmoraru** [comment]
For the context, this is a 2018 refresh of the low-power `Sapphire Radeon RX 550 Pulse` card.
This card switches from Polaris 12(RX 550), 512 streams -- to --> Polaris 21(originally RX 560), 640 streams.
It seems that it might be a "reduced" RX 560 chip on RX 550 :)

**Comment by konimex** [comment]
I'm closing this since the database has been updated.
