### ISSUE TITLE
Strange "a" characters when displaying image with w3m

### ISSUE THREAD

**Issue by 27Spiff** [dylanaraps/neofetch#916]
## Description

When runing neofetch --w3m ~/path/to/picture I get "a" characters in front of every detail entry. I saw a post where someone had the same problem which resulted from not selecting his locales. I have my locales defined.

## Neofetch version

3.3.0

## Screenshot

https://i.imgur.com/avNgp85.png

## Config file

default config

## Verbose log

https://pastebin.com/Z0ZyH5hG

**Comment by dylanaraps** [comment]
What's the output of this command?:

```sh
printf "%b\n" "\xE2\x80\x8B\x20"
```

**Comment by 27Spiff** [comment]
Hey, I just got around to running this command. The result is the same "a" characters. Sorry for the delay. Any further help is appreciated. https://i.imgur.com/i23eHfe.png

**Comment by dylanaraps** [comment]
What's your locale?

Run this command:

```sh
locale
```

**Comment by 27Spiff** [comment]
```
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

**Comment by 27Spiff** [comment]
Wow, okay I'm an idiot. I uncommented and ran `locale-gen` but forgot to edit my locale.conf. I'm sorry for wasting your time. Thanks for you patience.
