### ISSUE TITLE
catimg backend always uses lower resolution despite the fact that using higher resolution is possible

### ISSUE THREAD

**Issue by SuperPrower** [dylanaraps/neofetch#921]
### Description

catimg backend should figure out whether it can use higher resolution mode, but for some reason, in neofetch it always uses lower resolution mode.

#### Possible solution

Manually set `-r 2` instead of `-r 0` in neofetch, but this could break compatibility with many terminal emulators. Maybe, add option to force this, or maybe universal option value of which would be passed to the backend?

#### Neofetch version
Neofetch 3.2.1-git

**Comment by dylanaraps** [comment]
Fixed.

**Comment by SuperPrower** [comment]
Unfortunately I don't believe it fixes the issue, at least for me. Option `-r 0` shouldn't have any effect at all, since it only accepts 1 or 2, and not having this options is just like with `-r 0` - it tries to automatically use best option possible, but it uses one with bigger squares. Only forcibly adding `-r 2` to script seems to enable better resolution mode.

**Comment by Allakazan** [comment]
Hello, i'm having problems with the resolution too. How should i set to 1 ? :) 

Also the catimg has the "-c" parameter that simplifies the color palette of the image, would be cool if i could set this up too
