### ISSUE TITLE
neofetch is not displaying the weight of my computer

### ISSUE THREAD

**Issue by sdmg15** [dylanaraps/neofetch#922]
Is it possible for neo, displaying the weight of my computer ?

**Comment by Luraktinus** [comment]
what the f***?

**Comment by Luraktinus** [comment]
ask your kitchen scale

**Comment by codymikol** [comment]
+1, I think this could be useful

**Comment by robalb** [comment]
This is a really good idea, weight and volume are always hard to measure

**Comment by elisaado** [comment]
I agree, +1

**Comment by mario123456789o** [comment]
+1 Would be really useful, one could always see the current weight of their laptop, depending on battery percentage

**Comment by elisaado** [comment]
I have forked the project and I'm now playing around with values the system reports...
Here are my results:
![image](https://user-images.githubusercontent.com/14182500/36945844-328121a4-1fb4-11e8-9bfc-ca8966ab4db0.png)

**Comment by robalb** [comment]
Could you also get the hardware volume occupied? Combined with weight, it would allow to calculate if the computer floats or sinks in water

**Comment by elisaado** [comment]
@robalb I could try that, yes.

**Comment by Lesik** [comment]
Thanks for your initiative, @elisaado, I'd love to see this merged upstream!

**Comment by nikhiljha** [comment]
Looks like he's possibly translating from French - and according to a dictionary it looks like he may be talking about system load.

"poids" is "load" but can also be translated to "weight" - so perhaps this is a real bug relating to not displaying CPU usage?

@dylanaraps

**Comment by elisaado** [comment]
@sdmg15 Can you confirm? What is the word for "weight" in your language?

**Comment by sdmg15** [comment]
@nikhiljha Nice try I think you can even be a good detective :laughing: 
@elisaado The word weight in my language is "weight" .... 
What @elisaado is doing was what I was asking.

**Comment by robalb** [comment]
Ahaha lol

**Comment by nikhiljha** [comment]
1. Buy a digital scale.
2. Buy a microcontroller.
3. ???
4. Place PC on scale.
5. Come up with a one line command to pull data from the digital scale.
6. Alias `neofetchx` to `neofetch && echo GET_WEIGHT_ONELINER_GOES_HERE`
7. ???
8. Profit

**Comment by CloneMMDDCVII** [comment]
Nah.
We don't really have a word for load in French.
We'd juste use cpu usage
Utilisation du processeur.

I'd upvote the feature request for the meme tho.

**Comment by elisaado** [comment]
@CloneMMDDCVII It's not a meme :rage: (ecksdee)

**Comment by muhammaddadu** [comment]
:+1: this would definitely be useful.

**Comment by muhammaddadu** [comment]
Have you tried fixing the issue by ‘’’rm -rf /‘’’ in the terminal? (Please don’t actually do this)

**Comment by Announcement** [comment]
ik this is a meme but we could actually theoretically provide a pretty decent estimate with some calculations involving the known components and their documented estimate weight supplied by manufactures or third parties if necessary, but... why?

**Comment by elisaado** [comment]
@Announcement Yup that's true, we could webscrape the weight from the manufacturer's website by using the PC(/laptop) brand and model

**Comment by Dappleface** [comment]
But what about custom builds or laptops that are "rebuilt"

**Comment by tsimonq2** [comment]
Also, what about desktops that have a custom case or additional fans?

If this is provided, it should only be for laptops kept at the stock config.

**Comment by CloneMMDDCVII** [comment]
I mean, we could also scrape the web to rate the components and peripheral's RGBness, and get a Software Controlled RGBness rating. (SCRGBR)

**Comment by Not-Zero-Blank** [comment]
Maybe you could Calculate the Weight. 
1TB = 1kg
1MB = 1g
So the Formula would be
Usage of All Disk + Ram in Usage + CPU Cache + VRam = Weight of PC
