### ISSUE TITLE
Adding feature for iconic print

### ISSUE THREAD

**Issue by ypraw** [dylanaraps/neofetch#927]
## Description
hello, i have some configuration on my neofetch config, but i don't have more knowledge about bash programming, the point is i want to print icon for information, with some trial and googling, i found this command , and if you wish , this might be an addtional feature for the next update with minimal function for print icon xixixi, thanks
```bash
$(perl -CS -E 'say "\x{f135}"')
```

#### Neofetch version
3.3.0

## Screenshot
![screenshot from 2018-03-19 12-59-14](https://user-images.githubusercontent.com/16682706/37580287-8018e86c-2b75-11e8-8a51-e623d12f63a7.png)

## Config file
https://github.com/ypraw/myDotfiles/blob/master/neofetch/config.conf

## fontawesome support
https://github.com/gabrielelana/awesome-terminal-fonts

**Comment by konimex** [comment]
Since this requires the use of external font (FontAwesome), and this won't work in a pure tty (where neofetch is also used), the "support" is already there and only needs modification in your `print_info`. There will be no addition of function.

**Comment by ypraw** [comment]
Oh all right, I see, thanks for your response
