### ISSUE TITLE
Kali/Debian WSL

### ISSUE THREAD

**Issue by Zekfad** [dylanaraps/neofetch#928]
## Description

Please fix Kali and Debian on WSL (Windows 10).

#### Neofetch version
Neofetch 3.3.0

## Screenshot
![image](https://user-images.githubusercontent.com/8970959/37599439-cd3574b0-2b95-11e8-9113-ae78f7bbb6eb.png)

## Config file
default

## Verbose log

https://pastebin.com/pW5CXBFE

**Comment by konimex** [comment]
Does #929 fix your issue?

**Comment by konimex** [comment]
I'm going ahead and merge #929, if you still have the issue even if the git master is installed, feel free to reopen.
