### ISSUE TITLE
Support chunkwm

### ISSUE THREAD

**Issue by LEARAX** [dylanaraps/neofetch#931]
## Description

I'd like to see support for chunkwm. At the moment, neofetch appears to identify chunkwm as the deprecated kwm.

It also detects my terminal (alacritty) as "launchd," but that's a separate issue.

```
$ brew services list`

Name       Status  User Plist
pulseaudio started Will /Users/Will/Library/LaunchAgents/homebrew.mxcl.pulseaudio.plist
chunkwm    started Will /Users/Will/Library/LaunchAgents/homebrew.mxcl.chunkwm.plist
dbus       stopped
skhd       started Will /Users/Will/Library/LaunchAgents/homebrew.mxcl.skhd.plist
mpd        started root /Library/LaunchDaemons/homebrew.mxcl.mpd.plist
mysql      stopped
```

#### Neofetch version

NeoFetch 3.3.0
Installed via homebrew:
Poured from bottle on 2017-09-25 at 11:26:23

## Screenshot

![screen shot 2018-03-22 at 15 22 39](https://user-images.githubusercontent.com/27088630/37799356-1a2a7dfa-2de5-11e8-9328-90d0266c73b5.png)

## Verbose log

[https://gist.github.com/LEARAX/e85cc44a6f57b70964b038ee94f26bbd#file-neofetchlog-txt-L715](https://gist.github.com/LEARAX/e85cc44a6f57b70964b038ee94f26bbd#file-neofetchlog-txt-L715)

**Comment by LEARAX** [comment]
I just saw [this commit](https://github.com/dylanaraps/neofetch/commit/3217b921e5c57c101b8a07604aae00fab051e6b0). When will it be released?

**Comment by dylanaraps** [comment]
When I get time to make a new release. It takes me a good 2-3 hours to release a new version and make sure things go smoothly.

I’ve got a break from university coming up so I’ll probably make a release then.
