### ISSUE TITLE
Can't get neofetch and w3m to work in Termite, works fine in urxvt

### ISSUE THREAD

**Issue by zachschultz** [dylanaraps/neofetch#932]
## Description

I'm trying to get `neofetch --w3m /home/zach/Downloads/fw-blue-sky-moon.jpg` to work in Termite but all I see is the textual output from neofetch, with no image.

It works perfectly in `urxvt`, which makes me think Termite is doing something weird. I cleared out my Termite config (which only had colors), but the problem persists.

#### Neofetch version
Neofetch 3.3.0

## Config file
Default config file with `image_backend="w3m"` as the only change

## Verbose log
https://pastebin.com/BuHBCAeH

**Comment by dylanaraps** [comment]
Do images work in ranger or w3m itself?

**Comment by zachschultz** [comment]
Yes, I can open images with w3m

**Comment by zachschultz** [comment]
here is proof that w3m and Termite are working:

![w3m-proof](https://user-images.githubusercontent.com/2520702/37854722-1425989c-2eba-11e8-9ab9-d7e432afd495.png)

**Comment by thyeun** [comment]
i having wallpaper disappear, as you can see from below

[https://asciinema.org/a/RXWeEPDaMXhpSPtLkPie3BLBC](url)

my neofetch config file
[https://paste.ubuntu.com/p/mDMNPQHvhn/](url)

**Comment by dylanaraps** [comment]
According to the verbose log, `w3m-img` is exiting with a status code of `1` (error). 

Does the following script display any images correctly?:

```sh
#!/bin/sh

# Replace this with a proper path.
img="${HOME}/Pictures/Wallpapers/12.jpg"

# Hide the cursor and move it below the image.
printf "%b" "\e[?25l\e[2J\e[10;f"

# Display the imahe.
printf "%b\n" "0;1;0;0;200;200;;;;;${img}\n4;\n3;" \
    | /usr/lib/w3m/w3mimgdisplay || echo error

# Show the cursor
printf "%b" "\e[?25h"
```

1. Save it to a file.
2. Make it executable.
3. Change the image path to a correct one.
4. Run the script in your terminal.

**Comment by thyeun** [comment]
@dylanaraps nothing appear and no error message

[here](https://asciinema.org/a/nDHAgNkqe8zojXsTcW82ULc5H)

**Comment by thyeun** [comment]
@dylanaraps below is the link to show you the script show the images but once mouse out of it, it will disappear.

[here](https://youtu.be/y5WfpBNAmS4)

**Comment by dylanaraps** [comment]
Also, you can workaround this by using `--loop` with `neofetch`. `neofetch --w3m wall --loop`.

**Comment by thyeun** [comment]
@dylanaraps question is, the script and actual are different

for the script, images appear but disappear when mouse move out . (yes, it might be terminal or w3m issue).

but the wallpaper not appear while launching a new terminal, this is the main issue i'm facing now. 

did this line given any affected or not?
line 5041 ``` [[ "$image_backend" == *w3m* ]] && display_image```

**Comment by dylanaraps** [comment]
Closing this as I don't believe this is a Neofetch issue. The original OP is also MIA.
