### ISSUE TITLE
"Intel Core 2" displayed as "Intel Core2"

### ISSUE THREAD

**Issue by MingcongBai** [dylanaraps/neofetch#939]
With the fix pushed to address https://github.com/dylanaraps/neofetch/issues/926, the issue has now became that Neofetch displays "Core 2" as "Core2", as the match patterns removes "(TM)" from the branding. However, the Intel Core 2 shows up in `lscpu` as "Intel Core(TM)2", and removing the "(TM)" results in a missing space.

**Comment by dylanaraps** [comment]
Is there really a missing space? There’s no space in the lscpu output. Had there been a space it would be “Intel Core(TM) 2” no?

I can add a case for this in the code but is it really necessary?

**Comment by konimex** [comment]
In the Intel products guide there are really no space between Core and 2 too besides the trademark.

For example: https://ark.intel.com/products/29765/Intel-Core2-Quad-Processor-Q6600-8M-Cache-2_40-GHz-1066-MHz-FSB

Unless there's a branding guide by Intel to specifically address the old Intel(R) Core(TM)2 series as Intel Core 2, I see no reason to change it.

**Comment by MingcongBai** [comment]
I suppose at this point it's more of a question about aesthetics then. Intel Core2 is at least called "Intel Core 2" on Wikipedia, Amazon (listings), and most of the listings on eBay - maybe my original report lays with a sort of "common knowledge", for me at least.

**Comment by dylanaraps** [comment]
Fixed.

**Comment by MingcongBai** [comment]
Thanks!
