### ISSUE TITLE
Cannot Install on Debian 7

### ISSUE THREAD

**Issue by Dreyannz** [dylanaraps/neofetch#940]
root@debian-s-1vcpu-1gb-sgp1-01:~# sudo apt-get install neofetch
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  imagemagick cmus feh mpc nitrogen moc
The following NEW packages will be installed:
  neofetch
0 upgraded, 1 newly installed, 0 to remove and 40 not upgraded.
Need to get 70.0 kB of archives.
After this operation, 334 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  neofetch
Install these packages without verification [y/N]? Y
Err http://dl.bintray.com/dawidd6/neofetch/ jessie/main neofetch all 3.3.0-1
  Could not connect to dl.bintray.com:80 (75.126.118.188). - connect (110: Connection timed out)
Failed to fetch http://dl.bintray.com/dawidd6/neofetch/pool/n/neofetch/neofetch_3.3.0-1_all.deb  Could not connect to dl.bintray.com:80 (75.126.118.188). - connect (110: Connection timed out)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by dylanaraps** [comment]
This is not a Neofetch issue but an issue in your system.
