### ISSUE TITLE
Strip ANSI codes when counting line length in `get_ascii`

### ISSUE THREAD

**Issue by xPMo** [dylanaraps/neofetch#942]
## Description

I converted some pixel art to sgr/ansi images. For an example, [here is Celeste's icon](http://ix.io/141p).
However, if I run `curl ix.io141p > icon; neofetch --source icon`, [the info text is sent far to the right](https://i.imgur.com/QCrsE9J.png).

[I have to add `--gap -140` to correct for the escape codes.](https://i.imgur.com/nJ9YVxf.png)  If there's a way to portably strip ansi codes in `get_ascii`'s line calculations. I think it would make a good feature.

**Comment by dylanaraps** [comment]
Fixed.

**Comment by xPMo** [comment]
The `line=${line//[??;?;???m}` fix for this removed in v5.0.0. Was this a mistake, or is this a WONTFIX now?

**Comment by gfeun** [comment]
Stumbled into this today ! 

Had to add `--gap 900` for my image with ansi escape codes to be displayed properly along neofetch text.
