### ISSUE TITLE
Not sure what went wrong between root neofetch and user neofetch!!

### ISSUE THREAD

**Issue by thyeun** [dylanaraps/neofetch#943]
OS : Arch Linux
WM : i3-gaps
terminal : urxvt
neofetch : 3.4.0

i'm trying it out using ```sudo su``` than with ```neofetch``` , i get a different result but my ```/etc/neofetch/config.conf``` exactly same with my ```~/.config/neofetch/config.conf```

so what went wrong?
![screenshot_2018-04-08_20-04-37](https://user-images.githubusercontent.com/1939446/38467255-41c814cc-3b68-11e8-9854-1e2cb518a03f.png)

**Comment by konimex** [comment]
Please provide your logs AND your config for both instances of neofetch as mentioned when you made the issue.

**Comment by thyeun** [comment]
@konimex log and config
[neofetchlog.zip](https://github.com/dylanaraps/neofetch/files/1887492/neofetchlog.zip)

[config.conf.zip](https://github.com/dylanaraps/neofetch/files/1887493/config.conf.zip)

**Comment by konimex** [comment]
Again, *both* instances of neofetch. You need to provide logs for root neofetch.

Also, consider to use a pastebin service like [gist.github.com](https://gist.github.com).

P.S.: You may want to check `/root/.config/neofetch/` for any files, that may override `/etc/neofetch/config.conf`.

**Comment by thyeun** [comment]
@konimex u can easily to reproduce

**Comment by thyeun** [comment]
@konimex, omg, why i'm using ```locate neofetch``` , ```/root/.config/neofetch/``` it wont appear at my result table? 

ok, that the file insde ```/root/.config/neofetch/``` override 

thanks for helping out..!!
