### ISSUE TITLE
Detection of Anarchy Linux doesn't work any longer

### ISSUE THREAD

**Issue by robertwolter** [dylanaraps/neofetch#952]
The latest version of neofetch shows "OS: Arch Linux x86_64" although /etc/lsb-release still contains:
DISTRIB_ID=Anarchy
DISTRIB_DESCRIPTION="Anarchy Linux"

**Comment by konimex** [comment]
`lsb_release -a`

And you need to provide logs or we can't look at the problem.

**Comment by robertwolter** [comment]
lsb_release -a
command not found
pacman -Ss lsb_release
trizen lsb_release
:: No packages found...

![bildschirmfoto_2018-04-19_02-11-22](https://user-images.githubusercontent.com/18753171/38964446-32c11ec6-4377-11e8-9915-334589999290.png)

**Comment by dylanaraps** [comment]
I did some digging and from what I can see: Anarchy Linux doesn't package `lsb-release` in their repos. They're using Arch's package.

Source: https://anarchy-linux.org/packages/

**Comment by robertwolter** [comment]
lsb_release -a
command not found
pacman -Ss lsb_release
trizen lsb_release
:: No packages found...

![Uploading Bildschirmfoto_2018-04-19_02-11-22.png…]()

**Comment by robertwolter** [comment]
Ok, I renamed /etc/lsb-release and installed the package lsb-release, but now the original Arch /etc/lsb-release contains of course:
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

The original Anarchy Linux version of /etc/lsb-release contains:
LSB_VERSION=1.4
DISTRIB_ID=Anarchy
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Anarchy Linux"

**Comment by robertwolter** [comment]
The problem is that the file /etc/lsb-release exists, but not the command lsb_release that neofetch needs. I suggest the maintainers of Anarchy Linux to create their own version of the package "lsb-release", containg /etc/lsb-release, /usr/bin/lsb_release and the man page. Then neofetch will work fine with Anarchy Linux, I just tested it.

**Comment by dylanaraps** [comment]
Yup. I think this is an issue of another Arch based distro not really being a new distro. It’s just Arch with an additional repository (which probably only includes some aur packages) and half-assed identification files.
