### ISSUE TITLE
support for ArcoLinux + ascii

### ISSUE THREAD

**Issue by arcolinuxz** [dylanaraps/neofetch#958]
Improvement

Please add support for ArcoLinux

https://arcolinux.info

Ascii file is here 
[Link to ascii code](https://github.com/arcolinux/arcolinux-neofetch-ascii/blob/master/distro/arco)

**Comment by robertwolter** [comment]
Does "lsb_release -a" show "ArcoLinux"? Then it would look like this (with a corrected ASCII file):
![bildschirmfoto_2018-04-24_23-10-28](https://user-images.githubusercontent.com/18753171/39214436-bfd86430-4814-11e8-8daa-63c1b6f88800.png)
:

**Comment by erikdubois** [comment]
```
[erik@ArcoLinux ~]$ lsb_release -a
LSB Version:	1.4
Distributor ID:	ArcoLinux
Description:	ArcoLinux
Release:	v6.7.1
Codename:	Kirk
[erik@ArcoLinux ~]$ 
```

**Comment by erikdubois** [comment]
I called my file" arco" if you could call yours "arcolinux" ... there will be no pacman conflict in the future.
On the other hand I see you called Arch Linux also Arch. 
So you decide how you call the ascii file, I will communicate it to the users if need be.

**Comment by erikdubois** [comment]
ok with me

**Comment by robertwolter** [comment]
Ok, then I'll prepare a pull request.

**Comment by konimex** [comment]
An Arch-based distro using Arch's repo with proper lsb_release, now that's a rare breed.
