### ISSUE TITLE
ATI Radeon Graphics Cards Displayed as "AMD Radeon"

### ISSUE THREAD

**Issue by MingcongBai** [dylanaraps/neofetch#959]
## Description

Older ATI Radeon graphics cards, like the one found on iBook G4 - ATI Radeon 9550, is displayed as "AMD Radeon 9550". Any Radeon graphics card before the HD6000 series should be referred to as "ATI Radeon".

#### Neofetch version

3.4.0.

**Comment by dylanaraps** [comment]
Ping @MingcongBai

**Comment by MingcongBai** [comment]
My apologies... I'm a little bit caught up in school work at the moment, please do allow up to Tuesday next week.

**Comment by dylanaraps** [comment]
Ping @MingcongBai

**Comment by MingcongBai** [comment]
It worked out, thanks... My apologies.
