### ISSUE TITLE
Processor Information Displayed Incorrectly on a Jetson TX1 Development Board

### ISSUE THREAD

**Issue by MingcongBai** [dylanaraps/neofetch#960]
## Description

On a Jetson TX1 Development Board, the CPU information is displayed as follows when using `lscpu`:

```
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Model:               1
Model name:          ARMv8 Processor rev 1 (v8l)
CPU max MHz:         1734.0000
CPU min MHz:         102.0000
BogoMIPS:            38.40
L1d cache:           32K
L1i cache:           48K
L2 cache:            2048K
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
```

While Neofetch fails to display any information regarding the processor model.

#### Neofetch version

3.4.0.

## Screenshot

![2018-04-23 01-11-46](https://user-images.githubusercontent.com/5006263/39109625-4b5c10d4-4693-11e8-8a9a-54968606ad1b.png)

## Config file

N/A.

## Verbose log

https://pastebin.aosc.io/paste/GkEV3Lh6FfyQoKVp-M5S0g

**Comment by MingcongBai** [comment]
Well it does show something for me here...

```
processor	: 0
model name	: ARMv8 Processor rev 1 (v8l)
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1

processor	: 1
model name	: ARMv8 Processor rev 1 (v8l)
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1

processor	: 2
model name	: ARMv8 Processor rev 1 (v8l)
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1

processor	: 3
model name	: ARMv8 Processor rev 1 (v8l)
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1
```

Uname info:

```
Linux tegra210 4.4.38-tegra #1 SMP PREEMPT Thu Mar 1 20:44:58 PST 2018 aarch64 GNU/Linux
```

**Comment by konimex** [comment]
Apart from generic ARM board info, I saw nothing that can identify this as a TX1.

**Comment by MingcongBai** [comment]
My original issue refers to the processor model which clearly shows up as "ARMv8 Processor rev 1 (v8l)", yet in Neofetch output, it only displays "(4)", which suggests that Neofetch failed to display any processor information.

It should have displayed "Processor: ARMv8 Processor rev 1 (v8l) (4) @ 1.734GHz".

**Comment by konimex** [comment]
If a processor has a sane developer (which is unsurprising since we're talking about NVIDIA), the useful info should've been in a new field called `Hardware`

For example, take a look at an ARM64 processor's `/proc/cpuinfo`.

```sh
Processor       : AArch64 Processor rev 1 (aarch64)
processor       : 0
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0x201
CPU revision    : 1

processor       : 1
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0x201
CPU revision    : 1

processor       : 2
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0x205
CPU revision    : 1

processor       : 3
BogoMIPS        : 38.40
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x51
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0x205
CPU revision    : 1

Hardware        : Qualcomm Technologies, Inc MSM8996pro
```

If neofetch detects any ARM-style processor with generic names, it will look into `Hardware` instead since clearly the original Processor field yields no useful output.

I'm not sure how to handle this case so I'll wait for what @dylanaraps has to say.

**Comment by MingcongBai** [comment]
Well, I don't see why a generic name shouldn't be displayed - or did I misunderstand something?

**Comment by konimex** [comment]
Displaying generic information like `ARMv8 Processor rev 1` is equivalent to `x86_64 Processor`, an information that already exist in the OS field.

**Comment by dylanaraps** [comment]
True, it’s probably best to just leave it as is then.

**Comment by MingcongBai** [comment]
@konimex however in this case it only displays a "(4)" which (to me at least) is quite confusing.

**Comment by dylanaraps** [comment]
Closing this as per discussion above.
