### ISSUE TITLE
DOesnt show exact info in WSL debian.

### ISSUE THREAD

**Issue by alo0oz** [dylanaraps/neofetch#966]
## Description

The OS is shown wrong, is tead of debian on windows, it says on windows.
The ASCII image os also of windows (If it can be said so.)
But screenfetch shows the data right.

#### Neofetch version
2.02
## Screenshot
![image](https://user-images.githubusercontent.com/25322308/39561440-761fdb02-4ec7-11e8-8e9a-6e47b5893acf.png)
## Verbose log

https://pastebin.com/RCgKTQb1

**Comment by dylanaraps** [comment]
Try the latest version.

**Comment by alo0oz** [comment]
Ok I installed the latest version from istallation page ( by chance :)) (Why debian repos version is so old :O)
Now everything is ok. :)
Thanks for your response :
