### ISSUE TITLE
Neofetch now has a Discord server

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/neofetch#975]
I've been using Discord more and more lately and have decided to open a server for discussion about Neofetch and my other projects. When Matrix/Riot.im mature we will migrate to their platform or 
run our own instance.

Note: I know that Discord is proprietary but so is GitHub.

Click here to join: [![Discord](https://img.shields.io/discord/440354555197128704.svg)](https://discord.gg/BtnTPFF)

**Comment by diver-down** [comment]
Just as a head's up, the invite link appears to be invalid when I try to join. (yes, am logged-in to Discord)

**Comment by dylanaraps** [comment]
Weird. It works for me. Discord also shows that they don't expire.

**Comment by diver-down** [comment]
> Weird. It works for me. Discord also shows that they don't expire.

...would a screencast help with troubleshooting?

I’ve verified the issue on 3 machines (well, 2 and one phone) on my end. With and without being logged-in.

**Comment by diver-down** [comment]
Update -- while recording the screencast to help with this, I inadvertently got the invite link to work. I had to log out of Discord, clear all cookies, and log back in to the app as well as the browser.

From there, the invite link worked. Hopefully this helps anyone else having this issue.

**Comment by dylanaraps** [comment]
The server has been closed.
