### ISSUE TITLE
song: issues with using audtool for audacious

### ISSUE THREAD

**Issue by mstraube** [dylanaraps/neofetch#986]
## Description

Since audtool's output is always `artist - album - title`  with hardcoded separator, there are some issues with using audtool.

With `--song_shorthand on` it does not work due to the `-` separator, and we already fallback to `get_song_dbus` when shorthand is on.

With the new `--song_format` flag only `$artist` is set, `$album` and `$title` are emtpy when shorthand is off. That adds two `-` at the end of the song line. Here is an example:

`Song: Amon Amarth - Jomsviking - Vengeance Is My Name - -`

Is there any special reason why `audtool` was preferred over `get_song_dbus`?
Just using `get_song_dbus` would simplify things. ;)

Or a possible workaround would be to add a extra check for audacious.

```bash
    # Display Artist, Album and Title on separate lines.
    if [[ "$song_shorthand" == "on" ]]; then
        [[ "$(trim "$artist")" ]] && prin "Artist" "$artist"
        [[ "$(trim "$album")" ]]  && prin "Album" "$album"
        [[ "$(trim "$song")" ]]   && prin "Song" "$title"
    else
        if [[ "$player" != "audacious" ]]; then
            song="${song_format/\%artist\%/${artist}}"
            song="${song/\%album\%/${album}}"
            song="${song/\%title\%/${title}}"
        fi
    fi
```
@dylanaraps Waht do you think is better? Remove audtool or add a workaround for audacious?

Edit: or maybe some smarter solution? :)

#### Neofetch version
git-master

**Comment by dylanaraps** [comment]
Remove audtool
