### ISSUE TITLE
GPU info is showing twice

### ISSUE THREAD

**Issue by WyRe** [dylanaraps/neofetch#991]
## Description

GPU info is showing twice

#### Neofetch version
3.4.0

## Screenshot
![captura de pantalla_2018-05-17_10-47-58](https://user-images.githubusercontent.com/4059108/40166838-db98deea-59bf-11e8-8c8b-d0c4ea96e443.png)

## Config file
http://ix.io/1aCa

## Verbose log
http://ix.io/1aCc

I've tried to solve this issue modifying the `config.conf` file; specially the `gpu_type` parammeter but It did not work, as "dedicated" does not shown any gpu and as "integrated" it shows twice. 

Thank you.

**Comment by dylanaraps** [comment]
Try the newest release (4.0.0).

**Comment by WyRe** [comment]
The newest version what I've got in my distro repos are this, as you can see

```┌————— [wyre] ————— [~] 
└▶ $ yaourt -Ss neofetch
community/neofetch 3.4.0-2.0 [installed]
    A CLI system information tool written in BASH that supports displaying images.
aur/neofetch-git 3.2.0.r28.g2eca41d-1 (Out of Date) (21) (0,43)
    A CLI system information tool written in BASH that supports displaying images.
┌————— [wyre] ————— [~] 
└▶ $ 
```

**Comment by dylanaraps** [comment]
`4.0.0` was released today. Neofetch is now a single file so you can just download the newest version and run it.

**Comment by WyRe** [comment]
Where could find I the built binary to replace it?

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/neofetch/releases/tag/4.0.0

**Comment by WyRe** [comment]
Thank you and sorry for so many questions.
