### ISSUE TITLE
I want to hidden the wrong information

### ISSUE THREAD

**Issue by ourfor** [dylanaraps/neofetch#998]
## Description
When I enter ` neofetch `, it shows that ` /data/data/com.termux/files/usr/bin/neofetch: line 8682: /dev/stdin: No such file or directory `
So what should i edit the config file to hidden it?
config is default.
If you're suggesting a new feature then just a description will suffice.

#### Neofetch version
4.0.1
## Screenshot
<img src="http://ozkg680jm.bkt.clouddn.com/Screenshot_20180520-003303.png">
## Verbose log

1. Run `neofetch -vv 2> neofetchlog`
2. Upload the contents of `neofetchlog` to pastebin, gist or equivalent.

**Comment by dylanaraps** [comment]
This is fixed in master.

**Comment by ourfor** [comment]
OK，great, thank  you.

**Comment by dylanaraps** [comment]
A new release was also made. :)
